-- =============================================================================
-- Central Bank loans — 20 GPSL calendar month repayment schedule
-- Run once after central_bank_loans.sql
-- =============================================================================

ALTER TABLE public.club_loans
  ADD COLUMN IF NOT EXISTS repayment_months smallint NOT NULL DEFAULT 20
    CHECK (repayment_months > 0 AND repayment_months <= 40),
  ADD COLUMN IF NOT EXISTS drawdown_gpsl_month text,
  ADD COLUMN IF NOT EXISTS installments_paid smallint NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.club_loan_installments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id bigint NOT NULL REFERENCES public.club_loans (id) ON DELETE CASCADE,
  installment_no smallint NOT NULL CHECK (installment_no >= 1),
  due_season_id bigint NOT NULL REFERENCES public.competition_seasons (id),
  due_gpsl_month text NOT NULL CHECK (
    due_gpsl_month IN (
      'august', 'september', 'october', 'november', 'december',
      'january', 'february', 'march', 'april', 'may'
    )
  ),
  principal_due numeric(14, 2) NOT NULL CHECK (principal_due > 0),
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'paid', 'skipped')),
  paid_amount numeric(14, 2) NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
  paid_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT club_loan_installments_unique UNIQUE (loan_id, installment_no)
);

CREATE INDEX IF NOT EXISTS club_loan_installments_due_idx
  ON public.club_loan_installments (due_season_id, due_gpsl_month, status);

CREATE OR REPLACE FUNCTION public.competition_gpsl_month_from_sort(p_sort smallint)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE p_sort
    WHEN 1 THEN 'august'
    WHEN 2 THEN 'september'
    WHEN 3 THEN 'october'
    WHEN 4 THEN 'november'
    WHEN 5 THEN 'december'
    WHEN 6 THEN 'january'
    WHEN 7 THEN 'february'
    WHEN 8 THEN 'march'
    WHEN 9 THEN 'april'
    WHEN 10 THEN 'may'
    ELSE NULL
  END;
$$;

/** p_months_ahead: 1 = first GPSL month after drawdown month. */
CREATE OR REPLACE FUNCTION public.competition_resolve_gpsl_month_offset(
  p_base_season_id bigint,
  p_base_month text,
  p_months_ahead integer
)
RETURNS TABLE (due_season_id bigint, due_gpsl_month text)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_base_sort smallint;
  v_target_sort int;
  v_season_shift int;
  v_month_sort smallint;
BEGIN
  v_base_sort := public.competition_gpsl_month_sort(p_base_month);
  IF v_base_sort IS NULL OR p_months_ahead IS NULL OR p_months_ahead < 1 THEN
    RETURN;
  END IF;

  v_target_sort := v_base_sort + p_months_ahead;
  v_season_shift := (v_target_sort - 1) / 10;
  v_month_sort := ((v_target_sort - 1) % 10) + 1;

  due_gpsl_month := public.competition_gpsl_month_from_sort(v_month_sort);

  SELECT s.id
  INTO due_season_id
  FROM public.competition_seasons s
  WHERE s.id >= p_base_season_id
  ORDER BY s.id
  OFFSET v_season_shift
  LIMIT 1;

  IF due_season_id IS NULL THEN
    SELECT max(s.id) INTO due_season_id
    FROM public.competition_seasons s
    WHERE s.id >= p_base_season_id;
  END IF;

  RETURN NEXT;
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_loan_generate_installments(
  p_loan_id bigint,
  p_principal numeric,
  p_base_season_id bigint,
  p_drawdown_month text,
  p_months smallint DEFAULT 20
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_months smallint := coalesce(p_months, 20);
  v_base numeric;
  v_last numeric;
  v_i smallint;
  v_due record;
BEGIN
  DELETE FROM public.club_loan_installments WHERE loan_id = p_loan_id;

  v_base := round(p_principal / v_months, 2);
  v_last := round(p_principal - (v_base * (v_months - 1)), 2);

  FOR v_i IN 1..v_months LOOP
    SELECT * INTO v_due
    FROM public.competition_resolve_gpsl_month_offset(
      p_base_season_id,
      p_drawdown_month,
      v_i
    );

    IF v_due.due_season_id IS NULL OR v_due.due_gpsl_month IS NULL THEN
      RAISE EXCEPTION 'Could not resolve GPSL month for installment %', v_i;
    END IF;

    INSERT INTO public.club_loan_installments (
      loan_id,
      installment_no,
      due_season_id,
      due_gpsl_month,
      principal_due,
      status
    )
    VALUES (
      p_loan_id,
      v_i,
      v_due.due_season_id,
      v_due.due_gpsl_month,
      CASE WHEN v_i = v_months THEN v_last ELSE v_base END,
      'pending'
    );
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_loan_apply_principal_payment(
  p_loan_id bigint,
  p_amount numeric,
  p_description text DEFAULT NULL,
  p_installment_id bigint DEFAULT NULL
)
RETURNS numeric
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_pay numeric;
  v_balance numeric;
  v_loan record;
  v_desc text;
BEGIN
  SELECT *
  INTO v_loan
  FROM public.club_loans
  WHERE id = p_loan_id
    AND status = 'active'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Active loan not found';
  END IF;

  IF v_club IS NOT NULL AND v_club <> '' AND v_loan.club_short_name <> v_club THEN
    IF NOT public.is_gpsl_admin() THEN
      RAISE EXCEPTION 'Not your loan';
    END IF;
  END IF;

  v_pay := least(round(coalesce(p_amount, 0)::numeric, 2), v_loan.outstanding_principal);
  IF v_pay <= 0 THEN
    RETURN 0;
  END IF;

  SELECT balance INTO v_balance
  FROM public."Club_Finances"
  WHERE club_name = v_loan.club_short_name;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Club_Finances row missing';
  END IF;

  IF v_balance < v_pay THEN
    RAISE EXCEPTION 'Insufficient balance to repay % (balance %)', v_pay, v_balance;
  END IF;

  v_desc := coalesce(
    p_description,
    format('Loan principal repayment (loan #%s)', v_loan.id)
  );

  PERFORM public.post_club_ledger(
    v_loan.club_short_name,
    'loan_repayment_principal',
    -v_pay,
    v_desc,
    jsonb_build_object(
      'loan_id', v_loan.id,
      'installment_id', p_installment_id
    ),
    v_loan.season_id,
    NULL,
    true,
    true
  );

  UPDATE public.club_loans
  SET outstanding_principal = outstanding_principal - v_pay,
      updated_at = now(),
      installments_paid = installments_paid + CASE
        WHEN p_installment_id IS NOT NULL THEN 1
        ELSE 0
      END,
      status = CASE
        WHEN outstanding_principal - v_pay <= 0 THEN 'paid'
        ELSE 'active'
      END,
      closed_at = CASE
        WHEN outstanding_principal - v_pay <= 0 THEN now()
        ELSE closed_at
      END
  WHERE id = v_loan.id;

  IF p_installment_id IS NOT NULL THEN
    UPDATE public.club_loan_installments
    SET status = 'paid',
        paid_amount = v_pay,
        paid_at = now()
    WHERE id = p_installment_id
      AND loan_id = p_loan_id;
  END IF;

  IF v_loan.outstanding_principal - v_pay <= 0 THEN
    UPDATE public.club_loan_installments
    SET status = 'skipped'
    WHERE loan_id = p_loan_id
      AND status = 'pending';
  END IF;

  UPDATE public.gpsl_bank_account
  SET loan_book_outstanding = greatest(0, loan_book_outstanding - v_pay),
      reserves = reserves + v_pay,
      updated_at = now()
  WHERE id = 1;

  RETURN v_pay;
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_loan_process_due_for_club(p_club text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_active_month text;
  v_active_sort smallint;
  v_inst record;
  v_paid numeric := 0;
  v_count int := 0;
  v_desc text;
BEGIN
  IF p_club IS NULL OR btrim(p_club) = '' THEN
    RETURN jsonb_build_object('processed', 0, 'total_paid', 0);
  END IF;

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true AND status = 'active'
  ORDER BY id DESC
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('processed', 0, 'total_paid', 0);
  END IF;

  v_active_month := public.competition_active_gpsl_month(v_season_id, now());
  v_active_sort := coalesce(public.competition_gpsl_month_sort(v_active_month), 10);

  FOR v_inst IN
    SELECT i.*
    FROM public.club_loan_installments i
    JOIN public.club_loans l ON l.id = i.loan_id
    WHERE l.club_short_name = btrim(p_club)
      AND l.status = 'active'
      AND i.status = 'pending'
      AND (
        i.due_season_id < v_season_id
        OR (
          i.due_season_id = v_season_id
          AND public.competition_gpsl_month_sort(i.due_gpsl_month) <= v_active_sort
        )
      )
    ORDER BY i.due_season_id, public.competition_gpsl_month_sort(i.due_gpsl_month), i.installment_no
  LOOP
    BEGIN
      v_desc := format(
        'Scheduled loan repayment — %s %s (inst %s/%s, loan #%s)',
        public.competition_gpsl_month_label(v_inst.due_gpsl_month),
        (SELECT label FROM public.competition_seasons WHERE id = v_inst.due_season_id),
        v_inst.installment_no,
        (SELECT repayment_months FROM public.club_loans WHERE id = v_inst.loan_id),
        v_inst.loan_id
      );

      PERFORM public.club_loan_apply_principal_payment(
        v_inst.loan_id,
        v_inst.principal_due,
        v_desc,
        v_inst.id
      );

      v_count := v_count + 1;
      v_paid := v_paid + v_inst.principal_due;
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
  END LOOP;

  RETURN jsonb_build_object('processed', v_count, 'total_paid', v_paid);
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_loan_process_my_due_installments()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to your account';
  END IF;
  RETURN public.club_loan_process_due_for_club(v_club);
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_process_loan_installments(
  p_season_id bigint,
  p_gpsl_month text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_total int := 0;
  v_paid numeric := 0;
  v_res jsonb;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  FOR v_club IN
    SELECT DISTINCT l.club_short_name
    FROM public.club_loans l
    JOIN public.club_loan_installments i ON i.loan_id = l.id
    WHERE l.status = 'active'
      AND i.status = 'pending'
      AND i.due_season_id = p_season_id
      AND i.due_gpsl_month = p_gpsl_month
  LOOP
    v_res := public.club_loan_process_due_for_club(v_club);
    v_total := v_total + coalesce((v_res ->> 'processed')::int, 0);
    v_paid := v_paid + coalesce((v_res ->> 'total_paid')::numeric, 0);
  END LOOP;

  RETURN jsonb_build_object('clubs', v_total, 'total_paid', v_paid);
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_take_loan(p_amount numeric)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_amount numeric;
  v_season_id bigint;
  v_bank record;
  v_outstanding numeric;
  v_loan_id bigint;
  v_ledger_id bigint;
  v_desc text;
  v_drawdown_month text;
  v_months smallint := 20;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to your account';
  END IF;

  v_amount := round(coalesce(p_amount, 0)::numeric, 2);
  IF v_amount <= 0 THEN
    RAISE EXCEPTION 'Loan amount must be positive';
  END IF;

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true AND status = 'active'
  ORDER BY id DESC
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No active competition season';
  END IF;

  v_drawdown_month := public.competition_active_gpsl_month(v_season_id, now());
  IF v_drawdown_month IS NULL THEN
    v_drawdown_month := 'august';
  END IF;

  SELECT
    loans_enabled,
    loan_min_drawdown,
    loan_max_drawdown,
    loan_max_outstanding_per_club,
    policy_interest_rate_pct
  INTO v_bank
  FROM public.gpsl_bank_account
  WHERE id = 1
  FOR UPDATE;

  IF NOT coalesce(v_bank.loans_enabled, false) THEN
    RAISE EXCEPTION 'Bank loans are currently disabled';
  END IF;

  IF v_amount < v_bank.loan_min_drawdown THEN
    RAISE EXCEPTION 'Minimum loan is %', v_bank.loan_min_drawdown;
  END IF;

  IF v_amount > v_bank.loan_max_drawdown THEN
    RAISE EXCEPTION 'Maximum per drawdown is %', v_bank.loan_max_drawdown;
  END IF;

  v_outstanding := public.club_loan_outstanding_for(v_club);

  IF v_outstanding + v_amount > v_bank.loan_max_outstanding_per_club THEN
    RAISE EXCEPTION 'Would exceed max outstanding loan (%) for your club',
      v_bank.loan_max_outstanding_per_club;
  END IF;

  INSERT INTO public.club_loans (
    club_short_name,
    season_id,
    principal_drawn,
    outstanding_principal,
    interest_rate_pct,
    status,
    repayment_months,
    drawdown_gpsl_month,
    installments_paid
  )
  VALUES (
    v_club,
    v_season_id,
    v_amount,
    v_amount,
    v_bank.policy_interest_rate_pct,
    'active',
    v_months,
    v_drawdown_month,
    0
  )
  RETURNING id INTO v_loan_id;

  PERFORM public.club_loan_generate_installments(
    v_loan_id,
    v_amount,
    v_season_id,
    v_drawdown_month,
    v_months
  );

  v_desc := format(
    'Central bank loan drawdown (loan #%s) — %s GPSL months from %s',
    v_loan_id,
    v_months,
    public.competition_gpsl_month_label(v_drawdown_month)
  );

  v_ledger_id := public.post_club_ledger(
    v_club,
    'loan_drawdown',
    v_amount,
    v_desc,
    jsonb_build_object('loan_id', v_loan_id, 'repayment_months', v_months),
    v_season_id,
    NULL,
    true,
    true
  );

  UPDATE public.gpsl_bank_account
  SET loan_book_outstanding = loan_book_outstanding + v_amount,
      updated_at = now()
  WHERE id = 1;

  RETURN v_loan_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_repay_loan(p_amount numeric, p_loan_id bigint DEFAULT NULL)
RETURNS numeric
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_amount numeric;
  v_loan record;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to your account';
  END IF;

  v_amount := round(coalesce(p_amount, 0)::numeric, 2);
  IF v_amount <= 0 THEN
    RAISE EXCEPTION 'Repayment amount must be positive';
  END IF;

  IF p_loan_id IS NOT NULL THEN
    SELECT *
    INTO v_loan
    FROM public.club_loans
    WHERE id = p_loan_id
      AND club_short_name = v_club
      AND status = 'active'
    FOR UPDATE;
  ELSE
    SELECT *
    INTO v_loan
    FROM public.club_loans
    WHERE club_short_name = v_club
      AND status = 'active'
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE;
  END IF;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No active loan to repay';
  END IF;

  RETURN public.club_loan_apply_principal_payment(
    v_loan.id,
    v_amount,
    format('Voluntary loan repayment (loan #%s)', v_loan.id),
    NULL
  );
END;
$function$;

DROP VIEW IF EXISTS public.club_loan_installments_public;

CREATE VIEW public.club_loan_installments_public
WITH (security_invoker = true)
AS
SELECT
  i.id,
  i.loan_id,
  i.installment_no,
  i.due_season_id,
  s.label AS due_season_label,
  i.due_gpsl_month,
  public.competition_gpsl_month_label(i.due_gpsl_month) AS due_gpsl_month_label,
  i.principal_due,
  i.status,
  i.paid_amount,
  i.paid_at,
  l.club_short_name,
  l.repayment_months
FROM public.club_loan_installments i
JOIN public.club_loans l ON l.id = i.loan_id
JOIN public.competition_seasons s ON s.id = i.due_season_id
WHERE l.club_short_name = public.my_club_shortname();

GRANT SELECT ON public.club_loan_installments_public TO authenticated;

DROP VIEW IF EXISTS public.club_loans_public;

CREATE VIEW public.club_loans_public
WITH (security_invoker = true)
AS
SELECT
  l.id,
  l.club_short_name,
  l.season_id,
  l.principal_drawn,
  l.outstanding_principal,
  l.interest_rate_pct,
  l.status,
  l.repayment_months,
  l.drawdown_gpsl_month,
  public.competition_gpsl_month_label(l.drawdown_gpsl_month) AS drawdown_gpsl_month_label,
  l.installments_paid,
  (
    SELECT i.due_gpsl_month
    FROM public.club_loan_installments i
    WHERE i.loan_id = l.id AND i.status = 'pending'
    ORDER BY i.due_season_id, public.competition_gpsl_month_sort(i.due_gpsl_month), i.installment_no
    LIMIT 1
  ) AS next_due_gpsl_month,
  (
    SELECT public.competition_gpsl_month_label(i.due_gpsl_month)
    FROM public.club_loan_installments i
    WHERE i.loan_id = l.id AND i.status = 'pending'
    ORDER BY i.due_season_id, public.competition_gpsl_month_sort(i.due_gpsl_month), i.installment_no
    LIMIT 1
  ) AS next_due_gpsl_month_label,
  (
    SELECT i.principal_due
    FROM public.club_loan_installments i
    WHERE i.loan_id = l.id AND i.status = 'pending'
    ORDER BY i.due_season_id, public.competition_gpsl_month_sort(i.due_gpsl_month), i.installment_no
    LIMIT 1
  ) AS next_installment_due,
  l.created_at,
  l.updated_at,
  l.closed_at
FROM public.club_loans l
WHERE l.club_short_name = public.my_club_shortname();

GRANT SELECT ON public.club_loans_public TO authenticated;

DROP VIEW IF EXISTS public.club_loans_league_public;

CREATE VIEW public.club_loans_league_public
WITH (security_invoker = false)
AS
SELECT
  l.id,
  l.club_short_name,
  c."Club" AS club_name,
  l.season_id,
  l.principal_drawn,
  l.outstanding_principal,
  l.interest_rate_pct,
  l.status,
  l.repayment_months,
  l.installments_paid,
  l.drawdown_gpsl_month,
  l.created_at,
  l.updated_at,
  l.closed_at
FROM public.club_loans l
JOIN public."Clubs" c ON c."ShortName" = l.club_short_name;

GRANT SELECT ON public.club_loans_league_public TO authenticated;

ALTER TABLE public.club_loan_installments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_loan_installments_select_own ON public.club_loan_installments;
CREATE POLICY club_loan_installments_select_own ON public.club_loan_installments
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.club_loans l
      WHERE l.id = loan_id
        AND l.club_short_name = public.my_club_shortname()
    )
  );

DROP POLICY IF EXISTS club_loan_installments_admin ON public.club_loan_installments;
CREATE POLICY club_loan_installments_admin ON public.club_loan_installments
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.club_loan_installments TO authenticated;

GRANT EXECUTE ON FUNCTION public.club_loan_process_my_due_installments() TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_process_loan_installments(bigint, text) TO authenticated;

NOTIFY pgrst, 'reload schema';
