-- =============================================================================
-- Admin: owner last login + login counts (previous & current GPSL month)
--
-- Primary: public.owner_site_login_events (written on password sign-in).
-- Fallback: auth.sessions.created_at (covers logins when the client hook missed).
-- Per window we take GREATEST(events, sessions) so one login is not double-counted
-- when both sources have it, but we still see a login if only sessions has it.
-- Safe re-run.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.owner_site_login_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  logged_in_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS owner_site_login_events_owner_at_idx
  ON public.owner_site_login_events (owner_id, logged_in_at DESC);

CREATE INDEX IF NOT EXISTS owner_site_login_events_at_idx
  ON public.owner_site_login_events (logged_in_at DESC);

ALTER TABLE public.owner_site_login_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS owner_site_login_events_select_admin ON public.owner_site_login_events;
CREATE POLICY owner_site_login_events_select_admin
  ON public.owner_site_login_events
  FOR SELECT
  TO authenticated
  USING (public.is_gpsl_admin());

GRANT SELECT ON public.owner_site_login_events TO authenticated;

CREATE OR REPLACE FUNCTION public.record_owner_site_login()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not signed in';
  END IF;

  -- Debounce: ignore duplicate calls within 30s (double-submit / verify password).
  IF EXISTS (
    SELECT 1
    FROM public.owner_site_login_events e
    WHERE e.owner_id = v_uid
      AND e.logged_in_at > now() - interval '30 seconds'
  ) THEN
    RETURN;
  END IF;

  INSERT INTO public.owner_site_login_events (owner_id, logged_in_at)
  VALUES (v_uid, now());
END;
$function$;

GRANT EXECUTE ON FUNCTION public.record_owner_site_login() TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_owner_last_logins()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_cur text;
  v_prev text;
  v_cur_unlock timestamptz;
  v_cur_lock timestamptz;
  v_prev_unlock timestamptz;
  v_prev_lock timestamptz;
  v_cur_end timestamptz;
  v_prev_end timestamptz;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT s.id INTO v_season_id
  FROM public.competition_seasons s
  WHERE s.is_current = true
    AND s.status IN ('active', 'preseason')
  ORDER BY CASE s.status WHEN 'active' THEN 0 ELSE 1 END, s.id DESC
  LIMIT 1;

  IF v_season_id IS NOT NULL THEN
    v_cur := public.competition_active_gpsl_month(v_season_id, now());

    IF v_cur IS NOT NULL THEN
      SELECT m.unlock_at, m.lock_at
      INTO v_cur_unlock, v_cur_lock
      FROM public.competition_season_calendar m
      WHERE m.season_id = v_season_id
        AND lower(btrim(m.gpsl_month)) = lower(btrim(v_cur))
      LIMIT 1;

      SELECT m.gpsl_month, m.unlock_at, m.lock_at
      INTO v_prev, v_prev_unlock, v_prev_lock
      FROM public.competition_season_calendar m
      WHERE m.season_id = v_season_id
        AND public.competition_gpsl_month_sort(m.gpsl_month)
          < public.competition_gpsl_month_sort(v_cur)
      ORDER BY public.competition_gpsl_month_sort(m.gpsl_month) DESC
      LIMIT 1;
    END IF;
  END IF;

  -- Active GPSL month window is unlock ≤ now < lock; count unlock → now.
  v_cur_end := now();
  -- Previous month: unlock → lock (or current unlock if lock missing).
  v_prev_end := coalesce(v_prev_lock, v_cur_unlock, now());

  -- If calendar unlock is missing, still count recent activity in a wide window.
  IF v_cur IS NOT NULL AND v_cur_unlock IS NULL THEN
    v_cur_unlock := now() - interval '45 days';
  END IF;

  RETURN jsonb_build_object(
    'current_gpsl_month', v_cur,
    'current_gpsl_month_label', public.competition_gpsl_month_label(v_cur),
    'previous_gpsl_month', v_prev,
    'previous_gpsl_month_label', public.competition_gpsl_month_label(v_prev),
    'owners', coalesce(
      (
        WITH owner_ids AS (
          SELECT r.owner_id FROM public.gpsl_owner_registry r
          UNION
          SELECT cl.owner_id FROM public."Clubs" cl WHERE cl.owner_id IS NOT NULL
        ),
        event_counts AS (
          SELECT
            e.owner_id,
            count(*) FILTER (
              WHERE v_cur_unlock IS NOT NULL
                AND e.logged_in_at >= v_cur_unlock
                AND e.logged_in_at <= v_cur_end
            )::int AS cur_n,
            count(*) FILTER (
              WHERE v_prev_unlock IS NOT NULL
                AND e.logged_in_at >= v_prev_unlock
                AND e.logged_in_at < v_prev_end
            )::int AS prev_n
          FROM public.owner_site_login_events e
          GROUP BY e.owner_id
        ),
        session_counts AS (
          SELECT
            s.user_id AS owner_id,
            count(*) FILTER (
              WHERE v_cur_unlock IS NOT NULL
                AND s.created_at >= v_cur_unlock
                AND s.created_at <= v_cur_end
            )::int AS cur_n,
            count(*) FILTER (
              WHERE v_prev_unlock IS NOT NULL
                AND s.created_at >= v_prev_unlock
                AND s.created_at < v_prev_end
            )::int AS prev_n
          FROM auth.sessions s
          GROUP BY s.user_id
        ),
        login_counts AS (
          SELECT
            o.owner_id,
            greatest(coalesce(ec.cur_n, 0), coalesce(sc.cur_n, 0)) AS logins_current_month,
            greatest(coalesce(ec.prev_n, 0), coalesce(sc.prev_n, 0)) AS logins_previous_month
          FROM owner_ids o
          LEFT JOIN event_counts ec ON ec.owner_id = o.owner_id
          LEFT JOIN session_counts sc ON sc.owner_id = o.owner_id
        )
        SELECT jsonb_agg(
          row_to_json(x)::jsonb
          ORDER BY x.sort_ts DESC NULLS LAST,
                   x.owner_tag ASC NULLS LAST,
                   x.club_short_name ASC NULLS LAST
        )
        FROM (
          SELECT
            o.owner_id,
            public.owner_registry_resolve_tag(o.owner_id) AS owner_tag,
            coalesce(
              reg.status,
              CASE WHEN c.owner_id IS NOT NULL THEN 'active' ELSE 'member' END
            )::text AS registry_status,
            c."ShortName"::text AS club_short_name,
            c."Club"::text AS club_name,
            u.last_sign_in_at AS last_sign_in_at,
            u.created_at AS account_created_at,
            coalesce(u.last_sign_in_at, u.created_at) AS sort_ts,
            coalesce(lc.logins_current_month, 0) AS logins_current_month,
            coalesce(lc.logins_previous_month, 0) AS logins_previous_month
          FROM owner_ids o
          JOIN auth.users u ON u.id = o.owner_id
          LEFT JOIN public."Clubs" c ON c.owner_id = o.owner_id
          LEFT JOIN public.gpsl_owner_registry reg ON reg.owner_id = o.owner_id
          LEFT JOIN login_counts lc ON lc.owner_id = o.owner_id
          WHERE coalesce(reg.status, '') IS DISTINCT FROM 'archived'
        ) x
      ),
      '[]'::jsonb
    )
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.admin_owner_last_logins() TO authenticated;

NOTIFY pgrst, 'reload schema';
