-- =============================================================================
-- Club Medical Room — doctor, physios (max 5), specialist tokens
--
-- Run in Supabase SQL editor (in order):
--   1) this file: club_medical_room.sql
--   2) competition_injuries_engine.sql  (physio chance + doctor −1 hooks)
-- Safe re-run.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Ledger entry types (rebuild from live rows + known types + medical)
-- A hard-coded IN (...) list fails if the DB already has newer entry_types.
-- ---------------------------------------------------------------------------
DO $ledger_types$
DECLARE
  v_list text;
BEGIN
  SELECT string_agg(quote_literal(t), ', ' ORDER BY t)
  INTO v_list
  FROM (
    SELECT DISTINCT entry_type AS t
    FROM public.competition_finance_ledger
    WHERE entry_type IS NOT NULL
    UNION
    SELECT unnest(ARRAY[
      'gate_league_home',
      'gate_cup_share',
      'prize',
      'prize_league',
      'prize_cup',
      'prize_challenge',
      'tv_revenue',
      'gov_hg_subsidy',
      'gov_youth_subsidy',
      'gov_bnb_subsidy',
      'gov_fine_compensation',
      'gov_emergency_tax',
      'gov_income_tax',
      'wage_squad',
      'wage_renewal_34plus',
      'wage_star_tax',
      'adjustment',
      'admin_one_off_injection',
      'admin_purchase_payment',
      'transfer_sale',
      'transfer_purchase',
      'transfer_agent_fee',
      'transfer_foreign_sale',
      'transfer_overflow_release',
      'loan_drawdown',
      'loan_repayment_principal',
      'loan_interest_payment',
      'infra_maintenance',
      'infra_purchase',
      'infra_expansion',
      'infra_expansion_refund',
      'infra_expansion_penalty',
      'contract_release_comp',
      'contract_release_comp_received',
      'contract_termination',
      'contract_signing_offer',
      'staff_manager_salary',
      'eos_debt_interest',
      'eos_ffp_charge',
      'eos_balance_interest',
      'eos_injection',
      'special_auction_fee',
      'special_auction_prize',
      'season_loan_fee',
      'season_loan_refund',
      'new_owner_release',
      'voluntary_contract_release',
      'medical_physio_hire',
      'medical_doctor_hire'
    ])
  ) s;

  ALTER TABLE public.competition_finance_ledger
    DROP CONSTRAINT IF EXISTS competition_finance_ledger_entry_type_check;

  EXECUTE format(
    'ALTER TABLE public.competition_finance_ledger
       ADD CONSTRAINT competition_finance_ledger_entry_type_check
       CHECK (entry_type IN (%s))',
    v_list
  );
END;
$ledger_types$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.club_medical_centre (
  club_short_name text PRIMARY KEY,
  specialist_tokens int NOT NULL DEFAULT 0 CHECK (specialist_tokens >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.club_medical_staff (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_short_name text NOT NULL,
  role text NOT NULL CHECK (role IN ('doctor', 'physio')),
  gender text NOT NULL CHECK (gender IN ('male', 'female')),
  display_name text,
  slot_index int CHECK (slot_index IS NULL OR (slot_index BETWEEN 1 AND 5)),
  seasons_remaining int NOT NULL DEFAULT 3 CHECK (seasons_remaining >= 0),
  hired_season_id bigint REFERENCES public.competition_seasons (id) ON DELETE SET NULL,
  hire_cost numeric NOT NULL DEFAULT 0,
  hired_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT club_medical_staff_doctor_slot CHECK (
    (role = 'doctor' AND slot_index IS NULL)
    OR (role = 'physio' AND slot_index IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS club_medical_staff_one_doctor_idx
  ON public.club_medical_staff (club_short_name)
  WHERE role = 'doctor';

CREATE UNIQUE INDEX IF NOT EXISTS club_medical_staff_physio_slot_idx
  ON public.club_medical_staff (club_short_name, slot_index)
  WHERE role = 'physio';

CREATE TABLE IF NOT EXISTS public.club_medical_token_use (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_short_name text NOT NULL,
  injury_id bigint NOT NULL
    REFERENCES public.competition_player_injuries (id) ON DELETE CASCADE,
  matches_removed int NOT NULL,
  used_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT club_medical_token_use_one_per_injury UNIQUE (injury_id)
);

ALTER TABLE public.club_medical_centre ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.club_medical_staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.club_medical_token_use ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_medical_centre_select_own ON public.club_medical_centre;
CREATE POLICY club_medical_centre_select_own
  ON public.club_medical_centre FOR SELECT TO authenticated
  USING (
    club_short_name = public.my_club_shortname()
    OR public.is_gpsl_admin()
  );

DROP POLICY IF EXISTS club_medical_staff_select_own ON public.club_medical_staff;
CREATE POLICY club_medical_staff_select_own
  ON public.club_medical_staff FOR SELECT TO authenticated
  USING (
    club_short_name = public.my_club_shortname()
    OR public.is_gpsl_admin()
  );

DROP POLICY IF EXISTS club_medical_token_use_select_own ON public.club_medical_token_use;
CREATE POLICY club_medical_token_use_select_own
  ON public.club_medical_token_use FOR SELECT TO authenticated
  USING (
    club_short_name = public.my_club_shortname()
    OR public.is_gpsl_admin()
  );

GRANT SELECT ON TABLE public.club_medical_centre TO authenticated;
GRANT SELECT ON TABLE public.club_medical_staff TO authenticated;
GRANT SELECT ON TABLE public.club_medical_token_use TO authenticated;

-- ---------------------------------------------------------------------------
-- Pricing / constants helpers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.medical_physio_hire_cost(p_slot int)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE p_slot
    WHEN 1 THEN 20000000::numeric
    WHEN 2 THEN 35000000::numeric
    WHEN 3 THEN 55000000::numeric
    WHEN 4 THEN 80000000::numeric
    WHEN 5 THEN 110000000::numeric
    ELSE NULL
  END;
$$;

CREATE OR REPLACE FUNCTION public.medical_doctor_hire_cost()
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT 150000000::numeric;
$$;

CREATE OR REPLACE FUNCTION public.medical_ensure_centre(p_club text)
RETURNS public.club_medical_centre
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_row public.club_medical_centre;
BEGIN
  INSERT INTO public.club_medical_centre (club_short_name)
  VALUES (p_club)
  ON CONFLICT (club_short_name) DO NOTHING;

  SELECT * INTO v_row FROM public.club_medical_centre WHERE club_short_name = p_club;
  RETURN v_row;
END;
$function$;

CREATE OR REPLACE FUNCTION public.medical_club_physio_count(p_club text)
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT count(*)::int
  FROM public.club_medical_staff
  WHERE club_short_name = p_club
    AND role = 'physio'
    AND seasons_remaining > 0;
$$;

CREATE OR REPLACE FUNCTION public.medical_club_has_doctor(p_club text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.club_medical_staff
    WHERE club_short_name = p_club
      AND role = 'doctor'
      AND seasons_remaining > 0
  );
$$;

CREATE OR REPLACE FUNCTION public.medical_injury_chance_reduction(p_club text)
RETURNS numeric
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 0.005::numeric * public.medical_club_physio_count(p_club);
$$;

-- ---------------------------------------------------------------------------
-- State for UI
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.medical_room_state(p_club text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := nullif(btrim(p_club), '');
  v_centre public.club_medical_centre;
  v_doctor jsonb;
  v_physios jsonb;
  v_injuries jsonb;
  v_balance numeric;
  v_physio_n int;
BEGIN
  IF v_club IS NULL THEN
    v_club := public.my_club_shortname();
  END IF;
  IF v_club IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'No club');
  END IF;
  IF v_club IS DISTINCT FROM public.my_club_shortname()
     AND NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Not allowed';
  END IF;

  v_centre := public.medical_ensure_centre(v_club);
  v_physio_n := public.medical_club_physio_count(v_club);

  SELECT balance INTO v_balance
  FROM public."Club_Finances"
  WHERE club_name = v_club;

  SELECT to_jsonb(s) INTO v_doctor
  FROM public.club_medical_staff s
  WHERE s.club_short_name = v_club AND s.role = 'doctor'
  LIMIT 1;

  SELECT coalesce(jsonb_agg(to_jsonb(s) ORDER BY s.slot_index), '[]'::jsonb)
  INTO v_physios
  FROM public.club_medical_staff s
  WHERE s.club_short_name = v_club AND s.role = 'physio';

  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'injury_id', i.id,
      'player_id', i.player_id,
      'player_name', p."Name",
      'label', i.label,
      'severity', i.severity,
      'matches_out_remaining', coalesce(i.matches_out_remaining, 0),
      'recovery_remaining', coalesce(i.recovery_remaining, 0),
      'token_used', EXISTS (
        SELECT 1 FROM public.club_medical_token_use u WHERE u.injury_id = i.id
      )
    )
    ORDER BY i.id
  ), '[]'::jsonb)
  INTO v_injuries
  FROM public.competition_player_injuries i
  LEFT JOIN public."Players" p ON p."Konami_ID"::text = i.player_id
  WHERE i.club_short_name = v_club
    AND i.status = 'active'
    AND (
      coalesce(i.matches_out_remaining, 0) > 0
      OR coalesce(i.recovery_remaining, 0) > 0
    );

  RETURN jsonb_build_object(
    'ok', true,
    'club_short_name', v_club,
    'balance', coalesce(v_balance, 0),
    'specialist_tokens', v_centre.specialist_tokens,
    'physio_count', v_physio_n,
    'injury_chance_reduction_pct', round(v_physio_n * 0.5, 1),
    'has_doctor', public.medical_club_has_doctor(v_club),
    'doctor', v_doctor,
    'doctor_hire_cost', public.medical_doctor_hire_cost(),
    'physio_hire_costs', jsonb_build_object(
      '1', public.medical_physio_hire_cost(1),
      '2', public.medical_physio_hire_cost(2),
      '3', public.medical_physio_hire_cost(3),
      '4', public.medical_physio_hire_cost(4),
      '5', public.medical_physio_hire_cost(5)
    ),
    'physios', coalesce(v_physios, '[]'::jsonb),
    'active_injuries', coalesce(v_injuries, '[]'::jsonb),
    'specialist_matches_removed', 2,
    'doctor_matches_off', 1,
    'physio_bonus_each_pct', 0.5,
    'max_physios', 5,
    'contract_seasons', 3
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.medical_room_state(text) TO authenticated;

-- ---------------------------------------------------------------------------
-- Hire physio
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.medical_hire_physio(
  p_slot int,
  p_gender text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_gender text := lower(nullif(btrim(p_gender), ''));
  v_cost numeric;
  v_balance numeric;
  v_season bigint;
  v_id bigint;
BEGIN
  IF v_club IS NULL THEN RAISE EXCEPTION 'No club linked to this account'; END IF;
  IF p_slot IS NULL OR p_slot < 1 OR p_slot > 5 THEN
    RAISE EXCEPTION 'Physio slot must be 1–5';
  END IF;
  IF v_gender NOT IN ('male', 'female') THEN
    RAISE EXCEPTION 'Choose male or female physio';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.club_medical_staff
    WHERE club_short_name = v_club AND role = 'physio' AND slot_index = p_slot
  ) THEN
    RAISE EXCEPTION 'That physio slot is already filled';
  END IF;

  IF public.medical_club_physio_count(v_club) >= 5 THEN
    RAISE EXCEPTION 'Maximum 5 physios';
  END IF;

  v_cost := public.medical_physio_hire_cost(p_slot);
  PERFORM public.medical_ensure_centre(v_club);

  SELECT balance INTO v_balance
  FROM public."Club_Finances"
  WHERE club_name = v_club
  FOR UPDATE;

  IF v_balance IS NULL THEN RAISE EXCEPTION 'Club finances not found'; END IF;
  IF v_balance < v_cost THEN
    RAISE EXCEPTION 'Insufficient balance (need %, have %)', v_cost, v_balance;
  END IF;

  SELECT s.id INTO v_season
  FROM public.competition_seasons s
  WHERE s.is_current = true
  ORDER BY s.id DESC
  LIMIT 1;

  PERFORM public.post_club_ledger(
    v_club,
    'medical_physio_hire',
    -v_cost,
    format('Medical Room — physio hire (slot %s)', p_slot),
    jsonb_build_object('slot', p_slot, 'gender', v_gender),
    v_season,
    NULL,
    false,
    true
  );

  INSERT INTO public.club_medical_staff (
    club_short_name, role, gender, display_name, slot_index,
    seasons_remaining, hired_season_id, hire_cost
  )
  VALUES (
    v_club, 'physio', v_gender,
    CASE WHEN v_gender = 'female' THEN 'Club physiotherapist' ELSE 'Club physiotherapist' END,
    p_slot, 3, v_season, v_cost
  )
  RETURNING id INTO v_id;

  RETURN jsonb_build_object(
    'ok', true,
    'staff_id', v_id,
    'slot', p_slot,
    'cost', v_cost,
    'physio_count', public.medical_club_physio_count(v_club)
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.medical_hire_physio(int, text) TO authenticated;

-- ---------------------------------------------------------------------------
-- Hire doctor
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.medical_hire_doctor(p_gender text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_gender text := lower(nullif(btrim(p_gender), ''));
  v_cost numeric := public.medical_doctor_hire_cost();
  v_balance numeric;
  v_season bigint;
  v_id bigint;
BEGIN
  IF v_club IS NULL THEN RAISE EXCEPTION 'No club linked to this account'; END IF;
  IF v_gender NOT IN ('male', 'female') THEN
    RAISE EXCEPTION 'Choose male or female doctor';
  END IF;

  IF public.medical_club_has_doctor(v_club) THEN
    RAISE EXCEPTION 'Club already has a doctor';
  END IF;

  PERFORM public.medical_ensure_centre(v_club);

  SELECT balance INTO v_balance
  FROM public."Club_Finances"
  WHERE club_name = v_club
  FOR UPDATE;

  IF v_balance IS NULL THEN RAISE EXCEPTION 'Club finances not found'; END IF;
  IF v_balance < v_cost THEN
    RAISE EXCEPTION 'Insufficient balance (need %, have %)', v_cost, v_balance;
  END IF;

  SELECT s.id INTO v_season
  FROM public.competition_seasons s
  WHERE s.is_current = true
  ORDER BY s.id DESC
  LIMIT 1;

  PERFORM public.post_club_ledger(
    v_club,
    'medical_doctor_hire',
    -v_cost,
    'Medical Room — club doctor hire',
    jsonb_build_object('gender', v_gender),
    v_season,
    NULL,
    false,
    true
  );

  INSERT INTO public.club_medical_staff (
    club_short_name, role, gender, display_name, slot_index,
    seasons_remaining, hired_season_id, hire_cost
  )
  VALUES (
    v_club, 'doctor', v_gender, 'Club doctor', NULL, 3, v_season, v_cost
  )
  RETURNING id INTO v_id;

  RETURN jsonb_build_object('ok', true, 'staff_id', v_id, 'cost', v_cost);
END;
$function$;

GRANT EXECUTE ON FUNCTION public.medical_hire_doctor(text) TO authenticated;

-- ---------------------------------------------------------------------------
-- Apply specialist token (−2 matches from current phase)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.medical_apply_specialist_token(p_injury_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_inj public.competition_player_injuries%rowtype;
  v_remove int := 2;
  v_applied int := 0;
  v_tokens int;
BEGIN
  IF v_club IS NULL THEN RAISE EXCEPTION 'No club linked to this account'; END IF;
  IF NOT public.medical_club_has_doctor(v_club) THEN
    RAISE EXCEPTION 'A club doctor is required before using specialist consultants';
  END IF;

  SELECT * INTO v_inj
  FROM public.competition_player_injuries
  WHERE id = p_injury_id
  FOR UPDATE;

  IF NOT FOUND OR v_inj.club_short_name IS DISTINCT FROM v_club THEN
    RAISE EXCEPTION 'Injury not found for your club';
  END IF;
  IF v_inj.status <> 'active' THEN
    RAISE EXCEPTION 'Injury is not active';
  END IF;
  IF EXISTS (SELECT 1 FROM public.club_medical_token_use WHERE injury_id = p_injury_id) THEN
    RAISE EXCEPTION 'A specialist consult was already used on this injury';
  END IF;

  PERFORM public.medical_ensure_centre(v_club);

  SELECT specialist_tokens INTO v_tokens
  FROM public.club_medical_centre
  WHERE club_short_name = v_club
  FOR UPDATE;

  IF coalesce(v_tokens, 0) < 1 THEN
    RAISE EXCEPTION 'No specialist tokens available';
  END IF;

  IF coalesce(v_inj.matches_out_remaining, 0) > 0 THEN
    v_applied := least(v_remove, v_inj.matches_out_remaining);
    UPDATE public.competition_player_injuries
    SET matches_out_remaining = matches_out_remaining - v_applied
    WHERE id = p_injury_id;
  ELSIF coalesce(v_inj.recovery_remaining, 0) > 0 THEN
    v_applied := least(v_remove, v_inj.recovery_remaining);
    UPDATE public.competition_player_injuries
    SET recovery_remaining = recovery_remaining - v_applied
    WHERE id = p_injury_id;
  ELSE
    RAISE EXCEPTION 'Nothing left to shorten on this injury';
  END IF;

  UPDATE public.club_medical_centre
  SET specialist_tokens = specialist_tokens - 1,
      updated_at = now()
  WHERE club_short_name = v_club;

  INSERT INTO public.club_medical_token_use (club_short_name, injury_id, matches_removed)
  VALUES (v_club, p_injury_id, v_applied);

  UPDATE public.competition_player_injuries i
  SET status = 'recovered',
      recovered_at = coalesce(i.recovered_at, now())
  WHERE i.id = p_injury_id
    AND coalesce(i.matches_out_remaining, 0) <= 0
    AND coalesce(i.recovery_remaining, 0) <= 0;

  PERFORM public.competition_injury_assign_fixtures(p_injury_id);

  RETURN jsonb_build_object(
    'ok', true,
    'injury_id', p_injury_id,
    'matches_removed', v_applied,
    'tokens_left', v_tokens - 1
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.medical_apply_specialist_token(bigint) TO authenticated;

-- ---------------------------------------------------------------------------
-- Admin / reward: grant tokens
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.medical_grant_specialist_tokens(
  p_club text,
  p_tokens int DEFAULT 1
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := nullif(btrim(p_club), '');
  v_n int := greatest(coalesce(p_tokens, 0), 0);
  v_row public.club_medical_centre;
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  IF v_club IS NULL THEN RAISE EXCEPTION 'Club required'; END IF;
  IF v_n <= 0 THEN RAISE EXCEPTION 'Token count must be > 0'; END IF;

  v_row := public.medical_ensure_centre(v_club);
  UPDATE public.club_medical_centre
  SET specialist_tokens = specialist_tokens + v_n,
      updated_at = now()
  WHERE club_short_name = v_club
  RETURNING * INTO v_row;

  RETURN jsonb_build_object(
    'ok', true,
    'club_short_name', v_club,
    'specialist_tokens', v_row.specialist_tokens,
    'granted', v_n
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.medical_grant_specialist_tokens(text, int) TO authenticated;

-- ---------------------------------------------------------------------------
-- Season tick (call with manager season-end)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.medical_process_season_end()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_retired int := 0;
  v_ticked int := 0;
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  UPDATE public.club_medical_staff
  SET seasons_remaining = seasons_remaining - 1
  WHERE seasons_remaining > 0;
  GET DIAGNOSTICS v_ticked = ROW_COUNT;

  DELETE FROM public.club_medical_staff
  WHERE seasons_remaining <= 0;
  GET DIAGNOSTICS v_retired = ROW_COUNT;

  RETURN jsonb_build_object(
    'ok', true,
    'contracts_ticked', v_ticked,
    'staff_retired', v_retired
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.medical_process_season_end() TO authenticated;

NOTIFY pgrst, 'reload schema';
