-- =============================================================================
-- Club finance season archive — snapshot final finances when a season is archived.
-- Run once in Supabase SQL Editor after competition_history.sql.
-- Re-run competition_admin_archive_season hook is included below.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_club_finance_season_archive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  season_label text NOT NULL,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  opening_balance numeric(14, 2) NOT NULL DEFAULT 0,
  closing_balance numeric(14, 2) NOT NULL DEFAULT 0,
  income_total numeric(14, 2) NOT NULL DEFAULT 0,
  cost_total numeric(14, 2) NOT NULL DEFAULT 0,
  net_total numeric(14, 2) NOT NULL DEFAULT 0,
  ledger_lines jsonb NOT NULL DEFAULT '[]'::jsonb,
  archived_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_club_finance_season_archive_unique
    UNIQUE (season_id, club_short_name)
);

CREATE INDEX IF NOT EXISTS competition_club_finance_season_archive_club_idx
  ON public.competition_club_finance_season_archive (club_short_name, season_id DESC);

-- ---------------------------------------------------------------------------
-- Income helper (mirrors finances UI isFinanceIncomeEntry)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_finance_entry_is_income(
  p_entry_type text,
  p_amount numeric
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT p_entry_type = ANY (
    ARRAY[
      'gate_league_home',
      'gate_cup_share',
      'prize',
      'prize_league',
      'prize_cup',
      'prize_challenge',
      'tv_revenue',
      'gov_hg_subsidy',
      'gov_youth_subsidy',
      'gov_bnb_subsidy',
      'adjustment',
      'admin_one_off_injection',
      'transfer_sale',
      'transfer_foreign_sale',
      'transfer_overflow_release',
      'loan_drawdown'
    ]::text[]
  )
  OR coalesce(p_amount, 0) > 0;
$$;

-- ---------------------------------------------------------------------------
-- Archive all club finances for one season
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_archive_club_finances_for_season(
  p_season_id bigint
)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season public.competition_seasons%rowtype;
  v_club text;
  v_income numeric(14, 2);
  v_cost numeric(14, 2);
  v_net numeric(14, 2);
  v_closing numeric(14, 2);
  v_opening numeric(14, 2);
  v_lines jsonb;
  v_count int := 0;
BEGIN
  SELECT * INTO v_season
  FROM public.competition_seasons
  WHERE id = p_season_id;

  IF NOT FOUND THEN
    RETURN 0;
  END IF;

  FOR v_club IN
    SELECT DISTINCT u.club_short_name
    FROM (
      SELECT l.club_short_name
      FROM public.competition_finance_ledger l
      WHERE l.season_id = p_season_id
      UNION
      SELECT a.club_short_name
      FROM public.competition_club_season_archive a
      WHERE a.season_id = p_season_id
    ) u
    WHERE u.club_short_name IS NOT NULL
      AND u.club_short_name <> 'FOREIGN'
    ORDER BY u.club_short_name
  LOOP
    SELECT
      coalesce(sum(
        CASE
          WHEN public.competition_finance_entry_is_income(l.entry_type, l.amount)
            THEN l.amount
          ELSE 0
        END
      ), 0),
      coalesce(sum(
        CASE
          WHEN public.competition_finance_entry_is_income(l.entry_type, l.amount)
            THEN 0
          ELSE abs(l.amount)
        END
      ), 0)
    INTO v_income, v_cost
    FROM public.competition_finance_ledger l
    WHERE l.season_id = p_season_id
      AND l.club_short_name = v_club;

    v_net := v_income - v_cost;

    SELECT cf.balance
    INTO v_closing
    FROM public."Club_Finances" cf
    WHERE cf.club_name = v_club;

    v_closing := coalesce(v_closing, 0);
    v_opening := v_closing - v_net;

    SELECT coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', l.id,
          'season_id', l.season_id,
          'fixture_id', l.fixture_id,
          'club_short_name', l.club_short_name,
          'entry_type', l.entry_type,
          'amount', l.amount,
          'description', l.description,
          'metadata', l.metadata,
          'created_at', l.created_at,
          'matchday', f.matchday,
          'competition_type', f.competition_type,
          'home_club_short_name', f.home_club_short_name,
          'away_club_short_name', f.away_club_short_name
        )
        ORDER BY l.created_at DESC
      ),
      '[]'::jsonb
    )
    INTO v_lines
    FROM public.competition_finance_ledger l
    LEFT JOIN public.competition_fixtures f ON f.id = l.fixture_id
    WHERE l.season_id = p_season_id
      AND l.club_short_name = v_club;

    INSERT INTO public.competition_club_finance_season_archive (
      season_id,
      season_label,
      club_short_name,
      opening_balance,
      closing_balance,
      income_total,
      cost_total,
      net_total,
      ledger_lines
    )
    VALUES (
      v_season.id,
      v_season.label,
      v_club,
      v_opening,
      v_closing,
      v_income,
      v_cost,
      v_net,
      v_lines
    )
    ON CONFLICT (season_id, club_short_name)
    DO UPDATE SET
      season_label = excluded.season_label,
      opening_balance = excluded.opening_balance,
      closing_balance = excluded.closing_balance,
      income_total = excluded.income_total,
      cost_total = excluded.cost_total,
      net_total = excluded.net_total,
      ledger_lines = excluded.ledger_lines,
      archived_at = now();

    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$function$;

-- Admin backfill for a past season (re-snapshot)
CREATE OR REPLACE FUNCTION public.competition_admin_backfill_finance_archive(
  p_season_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_count int;
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    RAISE EXCEPTION 'season_id required';
  END IF;

  v_count := public.competition_archive_club_finances_for_season(p_season_id);

  RETURN jsonb_build_object(
    'ok', true,
    'season_id', p_season_id,
    'clubs_finance_archived', v_count
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Hook into season archive (before season rollover)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_admin_archive_season(p_season_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season public.competition_seasons%rowtype;
  v_row record;
  v_cup record;
  v_player record;
  v_agg record;
  v_max_round int;
  v_winner text;
  v_runner text;
  v_fix_id bigint;
  v_awards jsonb;
  v_clubs int := 0;
  v_players int := 0;
  v_cups int := 0;
  v_finance int := 0;
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    SELECT * INTO v_season
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    SELECT * INTO v_season FROM public.competition_seasons WHERE id = p_season_id;
  END IF;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Season not found';
  END IF;

  FOR v_row IN
    SELECT *
    FROM public.competition_standings_public s
    WHERE s.season_id = v_season.id
    ORDER BY s.division, s.table_position
  LOOP
    INSERT INTO public.competition_club_season_archive (
      club_short_name, season_label, division, final_position,
      season_id, mp, won, drawn, lost, gf, ga, gd, pts
    )
    VALUES (
      v_row.club_short_name,
      v_season.label,
      v_row.division,
      v_row.table_position::smallint,
      v_season.id,
      v_row.mp::smallint,
      v_row.w::smallint,
      v_row.d::smallint,
      v_row.l::smallint,
      v_row.gf::smallint,
      v_row.ga::smallint,
      v_row.gd::smallint,
      v_row.pts::smallint
    )
    ON CONFLICT (club_short_name, season_label)
    DO UPDATE SET
      division = excluded.division,
      final_position = excluded.final_position,
      season_id = excluded.season_id,
      mp = excluded.mp,
      won = excluded.won,
      drawn = excluded.drawn,
      lost = excluded.lost,
      gf = excluded.gf,
      ga = excluded.ga,
      gd = excluded.gd,
      pts = excluded.pts;

    v_clubs := v_clubs + 1;
  END LOOP;

  FOR v_cup IN
    SELECT unnest(ARRAY['super8','plate','shield','bowl','league_cup']) AS cup_code
  LOOP
    SELECT max(n.round_no) INTO v_max_round
    FROM public.competition_cup_bracket_nodes n
    WHERE n.season_id = v_season.id AND n.cup_code = v_cup.cup_code;

    IF v_max_round IS NULL THEN
      CONTINUE;
    END IF;

    SELECT n.winner_club_short_name, n.fixture_id
    INTO v_winner, v_fix_id
    FROM public.competition_cup_bracket_nodes n
    WHERE n.season_id = v_season.id
      AND n.cup_code = v_cup.cup_code
      AND n.round_no = v_max_round
      AND n.winner_club_short_name IS NOT NULL
    ORDER BY n.match_no
    LIMIT 1;

    IF v_winner IS NULL THEN
      CONTINUE;
    END IF;

    SELECT CASE
      WHEN f.home_club_short_name = v_winner THEN f.away_club_short_name
      ELSE f.home_club_short_name
    END
    INTO v_runner
    FROM public.competition_fixtures f
    WHERE f.id = v_fix_id;

    INSERT INTO public.competition_cup_season_winner (
      season_id, season_label, cup_code,
      winner_club_short_name, runner_up_club_short_name, final_fixture_id
    )
    VALUES (
      v_season.id, v_season.label, v_cup.cup_code,
      v_winner, v_runner, v_fix_id
    )
    ON CONFLICT (season_id, cup_code)
    DO UPDATE SET
      winner_club_short_name = excluded.winner_club_short_name,
      runner_up_club_short_name = excluded.runner_up_club_short_name,
      final_fixture_id = excluded.final_fixture_id,
      archived_at = now();

    v_cups := v_cups + 1;
  END LOOP;

  FOR v_player IN
    SELECT DISTINCT m.player_id, m.club_short_name, ccs.division
    FROM public.competition_match_player_stats m
    JOIN public.competition_fixtures f ON f.id = m.fixture_id
    LEFT JOIN public.competition_club_seasons ccs
      ON ccs.season_id = m.season_id AND ccs.club_short_name = m.club_short_name
    WHERE m.season_id = v_season.id
      AND f.status = 'played'
      AND m.appeared = true
  LOOP
    SELECT * INTO v_agg
    FROM public.competition_aggregate_player_season_row(
      v_season.id, v_player.player_id, v_player.club_short_name
    );

    INSERT INTO public.competition_player_season_archive (
      season_id, season_label, player_id, club_short_name, division,
      player_position, stat_role,
      appearances, starts, goals, assists, avg_rating, potm_awards,
      clean_sheets, ballon_points
    )
    VALUES (
      v_season.id, v_season.label, v_player.player_id, v_player.club_short_name,
      v_player.division, v_agg.player_position, v_agg.stat_role,
      v_agg.appearances, v_agg.starts, v_agg.goals, v_agg.assists,
      v_agg.avg_rating, v_agg.potm_awards, v_agg.clean_sheets, v_agg.ballon_points
    )
    ON CONFLICT (season_id, player_id, club_short_name)
    DO UPDATE SET
      division = excluded.division,
      player_position = excluded.player_position,
      stat_role = excluded.stat_role,
      appearances = excluded.appearances,
      starts = excluded.starts,
      goals = excluded.goals,
      assists = excluded.assists,
      avg_rating = excluded.avg_rating,
      potm_awards = excluded.potm_awards,
      clean_sheets = excluded.clean_sheets,
      ballon_points = excluded.ballon_points,
      archived_at = now();

    v_players := v_players + 1;
  END LOOP;

  v_awards := public.competition_finalize_season_player_awards(v_season.id, v_season.label);

  v_finance := public.competition_archive_club_finances_for_season(v_season.id);

  RETURN jsonb_build_object(
    'ok', true,
    'season_id', v_season.id,
    'season_label', v_season.label,
    'clubs_archived', v_clubs,
    'players_archived', v_players,
    'cups_archived', v_cups,
    'clubs_finance_archived', v_finance,
    'player_awards', v_awards
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public view
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_club_finance_season_archive_public
WITH (security_invoker = false)
AS
SELECT
  a.season_id,
  a.season_label,
  a.club_short_name,
  c."Club" AS club_name,
  a.opening_balance,
  a.closing_balance,
  a.income_total,
  a.cost_total,
  a.net_total,
  a.ledger_lines,
  a.archived_at
FROM public.competition_club_finance_season_archive a
JOIN public."Clubs" c ON c."ShortName" = a.club_short_name;

GRANT SELECT ON public.competition_club_finance_season_archive_public TO authenticated;
GRANT SELECT ON public.competition_club_finance_season_archive_public TO anon;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_club_finance_season_archive ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_club_finance_season_archive_select
  ON public.competition_club_finance_season_archive;
CREATE POLICY competition_club_finance_season_archive_select
  ON public.competition_club_finance_season_archive
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_club_finance_season_archive_admin
  ON public.competition_club_finance_season_archive;
CREATE POLICY competition_club_finance_season_archive_admin
  ON public.competition_club_finance_season_archive
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.competition_club_finance_season_archive TO authenticated;

GRANT EXECUTE ON FUNCTION public.competition_archive_club_finances_for_season(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_backfill_finance_archive(bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';
