-- =============================================================================
-- Club Wire — live outbid / outcome alerts for owners (dashboard + nav badge)
-- =============================================================================
-- One small alert row per owner + market + subject + kind (repeat outbids on
-- the same player update the row instead of stacking). Written by triggers on
-- the bid tables; the site polls club_wire_list() about once a minute.
--
--   Open auctions (live "outbid"):
--     player draft, transfer list, club auction, manager draft / market,
--     snap special auctions.
--     Retaking the lead (incl. your own max bid / auto-bid answering) clears
--     your outbid alert, so max-bid wars end on the true result.
--   Private / sealed (result only, nothing leaked while live):
--     direct offers accepted / rejected,
--     lowest-unique + blind gauntlet special auctions (won / lost at settle),
--     expiring-contract wage bids (won / lost at rollover).
--
-- Every trigger body is wrapped in an exception block: an alert can never
-- block or slow a bid beyond one indexed lookup. Not sent to the Inbox.
--
-- Run off-peak (creates indexes on the bid tables). Safe re-run.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.club_wire_alerts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL,
  club_short_name text,
  market text NOT NULL,
  kind text NOT NULL,
  subject_key text NOT NULL,
  subject_name text,
  amount numeric,
  by_label text,
  href text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  dismissed_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS club_wire_alerts_live_uidx
  ON public.club_wire_alerts (owner_id, market, subject_key, kind)
  WHERE dismissed_at IS NULL;

CREATE INDEX IF NOT EXISTS club_wire_alerts_owner_recent_idx
  ON public.club_wire_alerts (owner_id, updated_at DESC);

ALTER TABLE public.club_wire_alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_wire_alerts_select_own ON public.club_wire_alerts;
CREATE POLICY club_wire_alerts_select_own
  ON public.club_wire_alerts FOR SELECT TO authenticated
  USING (owner_id = auth.uid());

REVOKE INSERT, UPDATE, DELETE ON public.club_wire_alerts FROM anon, authenticated;
GRANT SELECT ON public.club_wire_alerts TO authenticated;

-- Indexes for the "who led before this bid" lookups
CREATE INDEX IF NOT EXISTS player_transfer_bids_listing_amount_idx
  ON public."Player_Transfer_Bids" (listing_id, bid_amount DESC)
  WHERE listing_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS club_auction_bids_listing_amount_idx
  ON public."Club_Auction_Bids" (listing_id, bid_amount DESC);

CREATE INDEX IF NOT EXISTS special_auction_bids_auction_amount_idx
  ON public.special_auction_bids (auction_id, bid_amount DESC);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.club_wire_owner_of(p_club text)
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT c.owner_id FROM public."Clubs" c
  WHERE c."ShortName" = btrim(p_club)
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.club_wire_club_name(p_club text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(
    (SELECT nullif(btrim(c."Club"), '') FROM public."Clubs" c WHERE c."ShortName" = btrim(p_club) LIMIT 1),
    p_club
  );
$$;

CREATE OR REPLACE FUNCTION public.club_wire_push(
  p_owner uuid,
  p_club text,
  p_market text,
  p_kind text,
  p_subject_key text,
  p_subject_name text,
  p_amount numeric,
  p_by text,
  p_href text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF p_owner IS NULL OR p_subject_key IS NULL THEN
    RETURN;
  END IF;

  INSERT INTO public.club_wire_alerts (
    owner_id, club_short_name, market, kind, subject_key,
    subject_name, amount, by_label, href
  )
  VALUES (
    p_owner, p_club, p_market, p_kind, p_subject_key,
    p_subject_name, p_amount, p_by, p_href
  )
  ON CONFLICT (owner_id, market, subject_key, kind) WHERE dismissed_at IS NULL
  DO UPDATE SET
    subject_name = excluded.subject_name,
    amount = excluded.amount,
    by_label = excluded.by_label,
    href = excluded.href,
    club_short_name = excluded.club_short_name,
    updated_at = now();

  DELETE FROM public.club_wire_alerts a
  WHERE a.owner_id = p_owner
    AND a.updated_at < now() - interval '3 days';
END;
$function$;

-- Bidder took (back) the lead: their outbid alert for this subject is stale
CREATE OR REPLACE FUNCTION public.club_wire_clear_outbid(
  p_owner uuid,
  p_market text,
  p_subject_key text
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  DELETE FROM public.club_wire_alerts a
  WHERE a.owner_id = p_owner
    AND a.market = p_market
    AND a.subject_key = p_subject_key
    AND a.kind = 'outbid'
    AND a.dismissed_at IS NULL;
$$;

REVOKE ALL ON FUNCTION public.club_wire_push(uuid, text, text, text, text, text, numeric, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.club_wire_clear_outbid(uuid, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.club_wire_owner_of(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.club_wire_club_name(text) FROM PUBLIC, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 1) Player draft + transfer-list bids
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trg_club_wire_player_bid()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_top_id bigint;
  v_prev record;
  v_market text;
  v_pid text;
  v_name text;
  v_href text;
BEGIN
  BEGIN
    IF NEW.listing_id IS NULL THEN
      RETURN NULL;
    END IF;
    IF NEW.is_direct AND NEW.seller_club_id IS NOT NULL THEN
      RETURN NULL;
    END IF;

    SELECT b.bid_id INTO v_top_id
    FROM public."Player_Transfer_Bids" b
    WHERE b.listing_id = NEW.listing_id
      AND b.bidder_club_id IS DISTINCT FROM b.seller_club_id
    ORDER BY b.bid_amount DESC, b.bid_time ASC, b.bid_id ASC
    LIMIT 1;

    IF v_top_id IS DISTINCT FROM NEW.bid_id THEN
      RETURN NULL;
    END IF;

    v_pid := coalesce(NEW.player_id, NEW.direct_bid_id::text);
    IF NEW.is_direct AND NEW.seller_club_id IS NULL THEN
      v_market := 'player_draft';
      v_href := 'draftauction_player.html?player=' || v_pid;
    ELSE
      v_market := 'transfer_list';
      v_href := 'all_listings.html';
    END IF;

    PERFORM public.club_wire_clear_outbid(
      public.club_wire_owner_of(NEW.bidder_club_id), v_market, v_pid
    );

    SELECT b.bidder_club_id, b.bid_amount INTO v_prev
    FROM public."Player_Transfer_Bids" b
    WHERE b.listing_id = NEW.listing_id
      AND b.bid_id <> NEW.bid_id
      AND b.bidder_club_id IS DISTINCT FROM b.seller_club_id
    ORDER BY b.bid_amount DESC, b.bid_time ASC, b.bid_id ASC
    LIMIT 1;

    IF v_prev.bidder_club_id IS NULL OR v_prev.bidder_club_id = NEW.bidder_club_id THEN
      RETURN NULL;
    END IF;

    SELECT p."Name" INTO v_name FROM public."Players" p WHERE p."Konami_ID"::text = v_pid;

    PERFORM public.club_wire_push(
      public.club_wire_owner_of(v_prev.bidder_club_id),
      v_prev.bidder_club_id,
      v_market,
      'outbid',
      v_pid,
      coalesce(v_name, 'Player ' || v_pid),
      NEW.bid_amount,
      public.club_wire_club_name(NEW.bidder_club_id),
      v_href
    );
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'club wire (player bid): %', SQLERRM;
  END;
  RETURN NULL;
END;
$function$;

DROP TRIGGER IF EXISTS player_transfer_bids_zz_club_wire ON public."Player_Transfer_Bids";
CREATE TRIGGER player_transfer_bids_zz_club_wire
  AFTER INSERT ON public."Player_Transfer_Bids"
  FOR EACH ROW EXECUTE FUNCTION public.trg_club_wire_player_bid();

-- ---------------------------------------------------------------------------
-- 2) Direct offers accepted / rejected
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trg_club_wire_direct_offer()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_pid text;
  v_name text;
BEGIN
  BEGIN
    IF NOT (NEW.is_direct AND NEW.seller_club_id IS NOT NULL) THEN
      RETURN NULL;
    END IF;
    IF NEW.status NOT IN ('accepted', 'rejected')
       OR OLD.status IS NOT DISTINCT FROM NEW.status THEN
      RETURN NULL;
    END IF;

    v_pid := coalesce(NEW.player_id, NEW.direct_bid_id::text);
    SELECT p."Name" INTO v_name FROM public."Players" p WHERE p."Konami_ID"::text = v_pid;

    PERFORM public.club_wire_push(
      public.club_wire_owner_of(NEW.bidder_club_id),
      NEW.bidder_club_id,
      'direct_offer',
      'offer_' || NEW.status,
      v_pid || ':' || NEW.bid_id::text,
      coalesce(v_name, 'Player ' || v_pid),
      NEW.bid_amount,
      public.club_wire_club_name(NEW.seller_club_id),
      CASE WHEN NEW.status = 'accepted' THEN 'all_listings.html'
           ELSE 'GPDB.html?player=' || v_pid END
    );
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'club wire (direct offer): %', SQLERRM;
  END;
  RETURN NULL;
END;
$function$;

DROP TRIGGER IF EXISTS player_transfer_bids_zz_club_wire_offer ON public."Player_Transfer_Bids";
CREATE TRIGGER player_transfer_bids_zz_club_wire_offer
  AFTER UPDATE OF status ON public."Player_Transfer_Bids"
  FOR EACH ROW EXECUTE FUNCTION public.trg_club_wire_direct_offer();

-- ---------------------------------------------------------------------------
-- 3) Manager draft + manager market bids
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trg_club_wire_manager_bid()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_top_id bigint;
  v_prev record;
  v_type text;
  v_seller text;
  v_market text;
  v_name text;
  v_key text := NEW.manager_id::text;
BEGIN
  BEGIN
    SELECT l.listing_type, l.seller_club_id INTO v_type, v_seller
    FROM public."Manager_Transfer_Listings" l WHERE l.id = NEW.listing_id;

    SELECT b.id INTO v_top_id
    FROM public."Manager_Transfer_Bids" b
    WHERE b.listing_id = NEW.listing_id
      AND b.bidder_club_id IS DISTINCT FROM v_seller
    ORDER BY b.bid_amount DESC, b.bid_time ASC, b.id ASC
    LIMIT 1;

    IF v_top_id IS DISTINCT FROM NEW.id THEN
      RETURN NULL;
    END IF;

    v_market := CASE WHEN v_type = 'draft' THEN 'manager_draft' ELSE 'manager_market' END;

    PERFORM public.club_wire_clear_outbid(
      public.club_wire_owner_of(NEW.bidder_club_id), v_market, v_key
    );

    SELECT b.bidder_club_id, b.bid_amount INTO v_prev
    FROM public."Manager_Transfer_Bids" b
    WHERE b.listing_id = NEW.listing_id
      AND b.id <> NEW.id
      AND b.bidder_club_id IS DISTINCT FROM v_seller
    ORDER BY b.bid_amount DESC, b.bid_time ASC, b.id ASC
    LIMIT 1;

    IF v_prev.bidder_club_id IS NULL OR v_prev.bidder_club_id = NEW.bidder_club_id THEN
      RETURN NULL;
    END IF;

    SELECT m.name INTO v_name FROM public."Managers" m WHERE m.id = NEW.manager_id;

    PERFORM public.club_wire_push(
      public.club_wire_owner_of(v_prev.bidder_club_id),
      v_prev.bidder_club_id,
      v_market,
      'outbid',
      v_key,
      coalesce(v_name, 'Manager'),
      NEW.bid_amount,
      public.club_wire_club_name(NEW.bidder_club_id),
      CASE WHEN v_type = 'draft'
        THEN 'manager_draftauction_manager.html?manager=' || NEW.manager_id
        ELSE 'manager_listings.html' END
    );
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'club wire (manager bid): %', SQLERRM;
  END;
  RETURN NULL;
END;
$function$;

DROP TRIGGER IF EXISTS manager_transfer_bids_zz_club_wire ON public."Manager_Transfer_Bids";
CREATE TRIGGER manager_transfer_bids_zz_club_wire
  AFTER INSERT ON public."Manager_Transfer_Bids"
  FOR EACH ROW EXECUTE FUNCTION public.trg_club_wire_manager_bid();

-- ---------------------------------------------------------------------------
-- 4) Club auction (bidders are owners without a club yet)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trg_club_wire_club_auction_bid()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_top_id bigint;
  v_prev record;
  v_by text;
BEGIN
  BEGIN
    SELECT b.id INTO v_top_id
    FROM public."Club_Auction_Bids" b
    WHERE b.listing_id = NEW.listing_id
    ORDER BY b.bid_amount DESC, b.bid_time ASC, b.id ASC
    LIMIT 1;

    IF v_top_id IS DISTINCT FROM NEW.id THEN
      RETURN NULL;
    END IF;

    PERFORM public.club_wire_clear_outbid(NEW.bidder_owner_id, 'club_auction', NEW.club_short_name);

    SELECT b.bidder_owner_id, b.bid_amount INTO v_prev
    FROM public."Club_Auction_Bids" b
    WHERE b.listing_id = NEW.listing_id
      AND b.id <> NEW.id
    ORDER BY b.bid_amount DESC, b.bid_time ASC, b.id ASC
    LIMIT 1;

    IF v_prev.bidder_owner_id IS NULL OR v_prev.bidder_owner_id = NEW.bidder_owner_id THEN
      RETURN NULL;
    END IF;

    IF to_regclass('public.gpsl_owner_registry') IS NOT NULL THEN
      EXECUTE 'SELECT owner_tag FROM public.gpsl_owner_registry WHERE owner_id = $1 LIMIT 1'
      INTO v_by USING NEW.bidder_owner_id;
    END IF;

    PERFORM public.club_wire_push(
      v_prev.bidder_owner_id,
      NULL,
      'club_auction',
      'outbid',
      NEW.club_short_name,
      public.club_wire_club_name(NEW.club_short_name),
      NEW.bid_amount,
      coalesce(nullif(btrim(v_by), ''), 'another owner'),
      'club_auction.html'
    );
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'club wire (club auction): %', SQLERRM;
  END;
  RETURN NULL;
END;
$function$;

DROP TRIGGER IF EXISTS club_auction_bids_zz_club_wire ON public."Club_Auction_Bids";
CREATE TRIGGER club_auction_bids_zz_club_wire
  AFTER INSERT ON public."Club_Auction_Bids"
  FOR EACH ROW EXECUTE FUNCTION public.trg_club_wire_club_auction_bid();

-- ---------------------------------------------------------------------------
-- 5) Special auctions: live outbid for SNAP only (others are sealed)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trg_club_wire_special_bid()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_type text;
  v_title text;
  v_top_id bigint;
  v_prev record;
BEGIN
  BEGIN
    SELECT a.auction_type, a.title INTO v_type, v_title
    FROM public.special_auctions a WHERE a.id = NEW.auction_id;

    IF v_type IS DISTINCT FROM 'snap' THEN
      RETURN NULL;
    END IF;

    SELECT b.id INTO v_top_id
    FROM public.special_auction_bids b
    WHERE b.auction_id = NEW.auction_id
    ORDER BY b.bid_amount DESC, b.bid_time ASC, b.id ASC
    LIMIT 1;

    IF v_top_id IS DISTINCT FROM NEW.id THEN
      RETURN NULL;
    END IF;

    PERFORM public.club_wire_clear_outbid(NEW.owner_id, 'special_auction', NEW.auction_id::text);

    SELECT b.club_id, b.owner_id INTO v_prev
    FROM public.special_auction_bids b
    WHERE b.auction_id = NEW.auction_id
      AND b.id <> NEW.id
    ORDER BY b.bid_amount DESC, b.bid_time ASC, b.id ASC
    LIMIT 1;

    IF v_prev.club_id IS NULL OR v_prev.club_id = NEW.club_id THEN
      RETURN NULL;
    END IF;

    PERFORM public.club_wire_push(
      coalesce(public.club_wire_owner_of(v_prev.club_id), v_prev.owner_id),
      v_prev.club_id,
      'special_auction',
      'outbid',
      NEW.auction_id::text,
      coalesce(v_title, 'Special auction'),
      NEW.bid_amount,
      public.club_wire_club_name(NEW.club_id),
      'special_auction.html?id=' || NEW.auction_id
    );
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'club wire (special bid): %', SQLERRM;
  END;
  RETURN NULL;
END;
$function$;

DROP TRIGGER IF EXISTS special_auction_bids_zz_club_wire ON public.special_auction_bids;
CREATE TRIGGER special_auction_bids_zz_club_wire
  AFTER INSERT ON public.special_auction_bids
  FOR EACH ROW EXECUTE FUNCTION public.trg_club_wire_special_bid();

-- ---------------------------------------------------------------------------
-- 6) Special auctions settled: won / lost for every participant
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trg_club_wire_special_settled()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  r record;
  v_href text;
  v_winner_name text;
BEGIN
  BEGIN
    IF NEW.status IS DISTINCT FROM 'settled' OR OLD.status IS NOT DISTINCT FROM 'settled' THEN
      RETURN NULL;
    END IF;

    v_href := CASE WHEN NEW.auction_type = 'blind_gauntlet'
      THEN 'special_auction_gauntlet.html?id=' || NEW.id
      ELSE 'special_auction.html?id=' || NEW.id END;
    v_winner_name := CASE WHEN NEW.winning_club_id IS NULL THEN NULL
      ELSE public.club_wire_club_name(NEW.winning_club_id) END;

    FOR r IN
      SELECT DISTINCT x.club_id, x.owner_id
      FROM (
        SELECT b.club_id, b.owner_id FROM public.special_auction_bids b WHERE b.auction_id = NEW.id
        UNION ALL
        SELECT g.club_id, g.owner_id FROM public.special_auction_gauntlet_bids g WHERE g.auction_id = NEW.id
      ) x
    LOOP
      PERFORM public.club_wire_clear_outbid(
        coalesce(public.club_wire_owner_of(r.club_id), r.owner_id),
        'special_auction', NEW.id::text
      );
      PERFORM public.club_wire_push(
        coalesce(public.club_wire_owner_of(r.club_id), r.owner_id),
        r.club_id,
        'special_auction',
        CASE WHEN r.club_id = NEW.winning_club_id THEN 'won' ELSE 'lost' END,
        NEW.id::text,
        coalesce(NEW.title, 'Special auction'),
        NEW.winning_amount,
        v_winner_name,
        v_href
      );
    END LOOP;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'club wire (special settled): %', SQLERRM;
  END;
  RETURN NULL;
END;
$function$;

DROP TRIGGER IF EXISTS special_auctions_zz_club_wire ON public.special_auctions;
CREATE TRIGGER special_auctions_zz_club_wire
  AFTER UPDATE OF status ON public.special_auctions
  FOR EACH ROW EXECUTE FUNCTION public.trg_club_wire_special_settled();

-- ---------------------------------------------------------------------------
-- 7) Expiring-contract wage bids: won / lost when resolved at rollover
--    (bids are deleted right after the player is assigned to the winner)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trg_club_wire_wage_bid_resolved()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_holder text;
  v_name text;
BEGIN
  BEGIN
    SELECT public.player_contracted_club_key(p."Contracted_Team"), p."Name"
    INTO v_holder, v_name
    FROM public."Players" p
    WHERE p."Konami_ID"::text = OLD.player_id;

    IF v_holder IS NULL THEN
      RETURN NULL;
    END IF;

    PERFORM public.club_wire_push(
      public.club_wire_owner_of(OLD.bidder_club_short_name),
      OLD.bidder_club_short_name,
      'wage_bid',
      CASE WHEN v_holder = OLD.bidder_club_short_name THEN 'won' ELSE 'lost' END,
      OLD.player_id || ':' || coalesce(OLD.season_label, ''),
      coalesce(v_name, 'Player ' || OLD.player_id),
      OLD.wage_offer,
      public.club_wire_club_name(v_holder),
      'squad.html'
    );
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'club wire (wage bid): %', SQLERRM;
  END;
  RETURN NULL;
END;
$function$;

DROP TRIGGER IF EXISTS contract_expiry_wage_bids_zz_club_wire ON public.contract_expiry_wage_bids;
CREATE TRIGGER contract_expiry_wage_bids_zz_club_wire
  AFTER DELETE ON public.contract_expiry_wage_bids
  FOR EACH ROW EXECUTE FUNCTION public.trg_club_wire_wage_bid_resolved();

-- ---------------------------------------------------------------------------
-- Owner RPCs
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.club_wire_list(p_limit int DEFAULT 8)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH live AS (
    SELECT a.*
    FROM public.club_wire_alerts a
    WHERE a.owner_id = auth.uid()
      AND a.dismissed_at IS NULL
      AND a.updated_at > now() - interval '24 hours'
  )
  SELECT jsonb_build_object(
    'count', (SELECT count(*) FROM live),
    'items', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', l.id,
        'market', l.market,
        'kind', l.kind,
        'subject_name', l.subject_name,
        'amount', l.amount,
        'by_label', l.by_label,
        'href', l.href,
        'updated_at', l.updated_at
      ) ORDER BY l.updated_at DESC)
      FROM (SELECT * FROM live ORDER BY updated_at DESC LIMIT greatest(1, least(coalesce(p_limit, 8), 30))) l
    ), '[]'::jsonb)
  );
$$;

CREATE OR REPLACE FUNCTION public.club_wire_dismiss(p_id bigint DEFAULT NULL)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_n int;
BEGIN
  UPDATE public.club_wire_alerts a
  SET dismissed_at = now()
  WHERE a.owner_id = auth.uid()
    AND a.dismissed_at IS NULL
    AND (p_id IS NULL OR a.id = p_id);
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$function$;

REVOKE ALL ON FUNCTION public.club_wire_list(int) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.club_wire_dismiss(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.club_wire_list(int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_wire_dismiss(bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';

-- Check
SELECT
  to_regclass('public.club_wire_alerts') IS NOT NULL AS table_ok,
  (SELECT count(*) FROM pg_trigger t
    WHERE t.tgname IN (
      'player_transfer_bids_zz_club_wire', 'player_transfer_bids_zz_club_wire_offer',
      'manager_transfer_bids_zz_club_wire', 'club_auction_bids_zz_club_wire',
      'special_auction_bids_zz_club_wire', 'special_auctions_zz_club_wire',
      'contract_expiry_wage_bids_zz_club_wire')) AS triggers_should_be_7,
  to_regprocedure('public.club_wire_list(integer)') IS NOT NULL AS list_rpc_ok;
