-- =============================================================================
-- GPSL Injuries engine
-- Catalogue + season caps + per-club secret risk + post-match rolls +
-- out/recovery fixture absences + pre-season recovery ticks.
--
-- Rules (confirmed):
--   Roll once per club per played fixture (league + cup)
--   Caps: 1 major, 2 moderate, 4 minor, 4 total per club/season
--   Out + recovery both unavailable (Injured vs Gaining match fitness)
--   Anyone can be injured except sole remaining fit GK
--   Pre-season months (default may/june/july): no new injuries; 4 virtual
--     matches per month tick off remaining out then recovery
--   Club injury_risk is admin-secret only
--
-- Run after competition_fixture_unavailable.sql. Safe re-run.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Settings (singleton)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_injury_settings (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  max_major int NOT NULL DEFAULT 1,
  max_moderate int NOT NULL DEFAULT 2,
  max_minor int NOT NULL DEFAULT 4,
  max_total int NOT NULL DEFAULT 4,
  base_match_chance numeric(6,4) NOT NULL DEFAULT 0.1500,
  weight_minor numeric(6,2) NOT NULL DEFAULT 70,
  weight_moderate numeric(6,2) NOT NULL DEFAULT 25,
  weight_major numeric(6,2) NOT NULL DEFAULT 5,
  preseason_months text[] NOT NULL DEFAULT ARRAY['may','june','july']::text[],
  preseason_matches_per_month int NOT NULL DEFAULT 4,
  risk_min numeric(6,3) NOT NULL DEFAULT 0.700,
  risk_max numeric(6,3) NOT NULL DEFAULT 1.300,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.competition_injury_settings (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Catalogue
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_injury_catalogue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('Minor', 'Moderate', 'Major')),
  matches_out int NOT NULL CHECK (matches_out >= 0),
  recovery_matches int NOT NULL DEFAULT 0 CHECK (recovery_matches >= 0),
  active boolean NOT NULL DEFAULT true,
  CONSTRAINT competition_injury_catalogue_name_key UNIQUE (name)
);

-- ---------------------------------------------------------------------------
-- Extend injury rows
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_player_injuries
  ADD COLUMN IF NOT EXISTS catalogue_id bigint
    REFERENCES public.competition_injury_catalogue (id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS severity text,
  ADD COLUMN IF NOT EXISTS matches_out int,
  ADD COLUMN IF NOT EXISTS recovery_matches int,
  ADD COLUMN IF NOT EXISTS matches_out_remaining int,
  ADD COLUMN IF NOT EXISTS recovery_remaining int,
  ADD COLUMN IF NOT EXISTS source_fixture_id bigint
    REFERENCES public.competition_fixtures (id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS incurred_season_id bigint
    REFERENCES public.competition_seasons (id) ON DELETE SET NULL;

ALTER TABLE public.competition_player_injury_fixtures
  ADD COLUMN IF NOT EXISTS phase text NOT NULL DEFAULT 'out';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'competition_player_injury_fixtures_phase_check'
  ) THEN
    ALTER TABLE public.competition_player_injury_fixtures
      ADD CONSTRAINT competition_player_injury_fixtures_phase_check
      CHECK (phase IN ('out', 'recovery'));
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Per-club season state (secret risk + counters)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_club_injury_season (
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL,
  injury_risk numeric(6,3) NOT NULL DEFAULT 1.000,
  count_major int NOT NULL DEFAULT 0,
  count_moderate int NOT NULL DEFAULT 0,
  count_minor int NOT NULL DEFAULT 0,
  count_total int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (season_id, club_short_name)
);

CREATE TABLE IF NOT EXISTS public.competition_fixture_injury_roll (
  fixture_id bigint NOT NULL REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  club_short_name text NOT NULL,
  rolled_at timestamptz NOT NULL DEFAULT now(),
  did_injure boolean NOT NULL DEFAULT false,
  injury_id bigint REFERENCES public.competition_player_injuries (id) ON DELETE SET NULL,
  PRIMARY KEY (fixture_id, club_short_name)
);

CREATE TABLE IF NOT EXISTS public.competition_injury_preseason_tick (
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  gpsl_month text NOT NULL,
  ticks_applied int NOT NULL DEFAULT 0,
  applied_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (season_id, gpsl_month)
);

-- ---------------------------------------------------------------------------
-- Seed catalogue
-- ---------------------------------------------------------------------------

INSERT INTO public.competition_injury_catalogue (name, severity, matches_out, recovery_matches)
VALUES
  ('Ankle knock', 'Minor', 1, 0),
  ('Hamstring tightness', 'Minor', 1, 0),
  ('Groin tightness', 'Minor', 1, 0),
  ('Calf tightness', 'Minor', 1, 0),
  ('Back spasm', 'Minor', 2, 0),
  ('Neck stiffness', 'Minor', 1, 0),
  ('Shoulder bruise', 'Minor', 2, 0),
  ('Foot bruise', 'Minor', 1, 0),
  ('Knee bruise', 'Minor', 2, 0),
  ('Thigh contusion', 'Minor', 3, 0),
  ('Light concussion', 'Minor', 4, 0),
  ('Blister', 'Minor', 1, 0),
  ('Dead leg', 'Minor', 2, 0),
  ('Hip flexor strain', 'Minor', 3, 0),
  ('Hamstring strain', 'Minor', 4, 0),
  ('Groin strain', 'Minor', 4, 0),
  ('Calf strain', 'Minor', 3, 0),
  ('Quadriceps strain', 'Minor', 4, 0),
  ('Lower back strain', 'Minor', 3, 0),
  ('Achilles irritation', 'Minor', 5, 0),
  ('Plantar fasciitis flare', 'Minor', 5, 0),
  ('Mild ankle sprain', 'Minor', 4, 0),
  ('Mild knee sprain', 'Minor', 4, 0),
  ('Shoulder strain', 'Minor', 3, 0),
  ('Wrist sprain', 'Minor', 2, 0),
  ('Elbow sprain', 'Minor', 2, 0),
  ('Hip pointer injury', 'Minor', 3, 0),
  ('Rib bruise', 'Minor', 3, 0),
  ('Abdominal strain', 'Minor', 4, 0),
  ('Light illness (flu)', 'Minor', 1, 0),
  ('Food poisoning', 'Minor', 1, 0),
  ('Sinus infection', 'Minor', 1, 0),
  ('Migraine episode', 'Minor', 1, 0),
  ('Severe ankle sprain', 'Moderate', 6, 2),
  ('Severe knee sprain', 'Moderate', 7, 2),
  ('Hamstring tear (grade 2)', 'Moderate', 8, 2),
  ('Groin tear (grade 2)', 'Moderate', 7, 2),
  ('Calf tear (grade 2)', 'Moderate', 7, 2),
  ('Quadriceps tear (grade 2)', 'Moderate', 8, 2),
  ('Hip flexor tear (grade 2)', 'Moderate', 7, 2),
  ('Shoulder ligament damage', 'Moderate', 9, 2),
  ('Wrist ligament damage', 'Moderate', 6, 2),
  ('Elbow ligament damage', 'Moderate', 6, 2),
  ('Broken toe', 'Moderate', 7, 2),
  ('Broken finger', 'Moderate', 6, 2),
  ('Broken nose', 'Moderate', 6, 2),
  ('Fractured rib', 'Moderate', 8, 2),
  ('Severe concussion', 'Moderate', 10, 2),
  ('Meniscus irritation', 'Moderate', 7, 2),
  ('Patellar tendon irritation', 'Moderate', 8, 2),
  ('Achilles strain (grade 2)', 'Moderate', 9, 2),
  ('Hip labrum irritation', 'Moderate', 8, 2),
  ('Severe back spasm', 'Moderate', 6, 2),
  ('Severe illness (viral)', 'Moderate', 7, 2),
  ('Chest infection', 'Moderate', 6, 2),
  ('Tendonitis flare-up', 'Moderate', 7, 2),
  ('Bursitis (knee)', 'Moderate', 6, 2),
  ('Bursitis (hip)', 'Moderate', 6, 2),
  ('Ankle ligament tear (grade 3)', 'Major', 14, 4),
  ('Knee ligament tear (grade 3)', 'Major', 16, 4),
  ('Hamstring tear (grade 3)', 'Major', 15, 4),
  ('Groin tear (grade 3)', 'Major', 14, 4),
  ('Calf tear (grade 3)', 'Major', 14, 4),
  ('Quadriceps tear (grade 3)', 'Major', 16, 4),
  ('Achilles partial tear', 'Major', 18, 4),
  ('Shoulder dislocation', 'Major', 17, 4),
  ('Elbow dislocation', 'Major', 15, 4),
  ('Hip dislocation', 'Major', 18, 4),
  ('Broken ankle', 'Major', 18, 4),
  ('Broken wrist', 'Major', 14, 4),
  ('Broken arm', 'Major', 19, 4),
  ('Broken collarbone', 'Major', 17, 4),
  ('Fractured tibia', 'Major', 20, 4),
  ('Fractured fibula', 'Major', 18, 4),
  ('Severe patellar tendon tear', 'Major', 19, 4),
  ('Severe Achilles tendonitis', 'Major', 15, 4),
  ('Severe plantar fasciitis', 'Major', 14, 4),
  ('Severe rib fracture', 'Major', 16, 4),
  ('Severe concussion syndrome', 'Major', 18, 4),
  ('Severe hip labrum tear', 'Major', 19, 4),
  ('Severe shoulder rotator cuff tear', 'Major', 20, 4),
  ('ACL sprain (grade 1)', 'Moderate', 10, 2),
  ('ACL partial tear (grade 2)', 'Major', 18, 4),
  ('MCL sprain (grade 1)', 'Minor', 4, 0),
  ('MCL sprain (grade 2)', 'Moderate', 7, 2),
  ('MCL tear (grade 3)', 'Major', 16, 4),
  ('PCL sprain (grade 1)', 'Minor', 4, 0),
  ('PCL tear (grade 2)', 'Moderate', 8, 2),
  ('PCL tear (grade 3)', 'Major', 18, 4),
  ('Meniscus tear', 'Moderate', 9, 2),
  ('Severe meniscus tear', 'Major', 17, 4),
  ('Groin adductor rupture', 'Major', 18, 4),
  ('Hamstring rupture', 'Major', 20, 4),
  ('Calf rupture', 'Major', 18, 4),
  ('Quadriceps rupture', 'Major', 20, 4),
  ('Severe hip flexor rupture', 'Major', 19, 4),
  ('Sports hernia', 'Moderate', 8, 2),
  ('Severe sports hernia', 'Major', 16, 4)
ON CONFLICT (name) DO UPDATE
SET severity = excluded.severity,
    matches_out = excluded.matches_out,
    recovery_matches = excluded.recovery_matches,
    active = true;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_injury_settings_row()
RETURNS public.competition_injury_settings
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT * FROM public.competition_injury_settings WHERE id = 1;
$$;

CREATE OR REPLACE FUNCTION public.competition_injury_is_preseason_month(p_month text)
RETURNS boolean
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT lower(btrim(p_month)) = ANY (
    SELECT lower(unnest(s.preseason_months))
    FROM public.competition_injury_settings s
    WHERE s.id = 1
  );
$$;

CREATE OR REPLACE FUNCTION public.competition_injury_player_is_out(p_player_id text)
RETURNS boolean
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.competition_player_injuries i
    WHERE i.player_id = p_player_id
      AND i.status = 'active'
      AND coalesce(i.matches_out_remaining, 0) > 0
  );
$$;

CREATE OR REPLACE FUNCTION public.competition_injury_fit_gk_count(p_club text)
RETURNS int
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT count(*)::int
  FROM public."Players" p
  WHERE p."Contracted_Team" = p_club
    AND upper(coalesce(p."Position", '')) = 'GK'
    AND NOT public.competition_injury_player_is_out(p."Konami_ID"::text);
$$;

CREATE OR REPLACE FUNCTION public.competition_injury_ensure_club_season(
  p_season_id bigint,
  p_club text
)
RETURNS public.competition_club_injury_season
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_settings public.competition_injury_settings;
  v_row public.competition_club_injury_season;
  v_risk numeric;
BEGIN
  v_settings := public.competition_injury_settings_row();

  SELECT * INTO v_row
  FROM public.competition_club_injury_season
  WHERE season_id = p_season_id AND club_short_name = p_club;

  IF FOUND THEN
    RETURN v_row;
  END IF;

  v_risk := v_settings.risk_min
    + random() * (v_settings.risk_max - v_settings.risk_min);
  v_risk := round(v_risk::numeric, 3);

  INSERT INTO public.competition_club_injury_season (
    season_id, club_short_name, injury_risk
  )
  VALUES (p_season_id, p_club, v_risk)
  ON CONFLICT (season_id, club_short_name) DO NOTHING
  RETURNING * INTO v_row;

  IF v_row.club_short_name IS NULL THEN
    SELECT * INTO v_row
    FROM public.competition_club_injury_season
    WHERE season_id = p_season_id AND club_short_name = p_club;
  END IF;

  RETURN v_row;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_injury_assign_fixtures(
  p_injury_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_inj public.competition_player_injuries%rowtype;
  v_season_id bigint;
  v_fx record;
  v_seq int := 0;
  v_need_out int;
  v_need_rec int;
BEGIN
  SELECT * INTO v_inj FROM public.competition_player_injuries WHERE id = p_injury_id;
  IF NOT FOUND THEN RETURN; END IF;

  v_need_out := greatest(coalesce(v_inj.matches_out_remaining, 0), 0);
  v_need_rec := greatest(coalesce(v_inj.recovery_remaining, 0), 0);

  DELETE FROM public.competition_player_injury_fixtures
  WHERE injury_id = p_injury_id AND served = false;

  SELECT s.id INTO v_season_id
  FROM public.competition_seasons s
  WHERE s.is_current = true
  ORDER BY s.id DESC
  LIMIT 1;

  IF v_season_id IS NULL THEN
    v_season_id := coalesce(v_inj.season_id, v_inj.incurred_season_id);
  END IF;

  FOR v_fx IN
    SELECT f.id
    FROM public.competition_fixtures f
    WHERE f.season_id = v_season_id
      AND f.status = 'scheduled'
      AND (f.home_club_short_name = v_inj.club_short_name
           OR f.away_club_short_name = v_inj.club_short_name)
      AND (v_inj.source_fixture_id IS NULL OR f.id IS DISTINCT FROM v_inj.source_fixture_id)
    ORDER BY coalesce(f.matchday, 9999), f.id
  LOOP
    EXIT WHEN v_need_out <= 0 AND v_need_rec <= 0;
    v_seq := v_seq + 1;

    IF v_need_out > 0 THEN
      INSERT INTO public.competition_player_injury_fixtures (
        injury_id, fixture_id, phase, served
      ) VALUES (p_injury_id, v_fx.id, 'out', false)
      ON CONFLICT (injury_id, fixture_id) DO UPDATE
        SET phase = 'out', served = false;
      v_need_out := v_need_out - 1;
    ELSIF v_need_rec > 0 THEN
      INSERT INTO public.competition_player_injury_fixtures (
        injury_id, fixture_id, phase, served
      ) VALUES (p_injury_id, v_fx.id, 'recovery', false)
      ON CONFLICT (injury_id, fixture_id) DO UPDATE
        SET phase = 'recovery', served = false;
      v_need_rec := v_need_rec - 1;
    END IF;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_injury_issue(
  p_season_id bigint,
  p_club text,
  p_player_id text,
  p_catalogue_id bigint,
  p_source_fixture_id bigint
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cat public.competition_injury_catalogue%rowtype;
  v_id bigint;
  v_state public.competition_club_injury_season;
BEGIN
  SELECT * INTO v_cat FROM public.competition_injury_catalogue WHERE id = p_catalogue_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Injury catalogue row not found'; END IF;

  v_state := public.competition_injury_ensure_club_season(p_season_id, p_club);

  INSERT INTO public.competition_player_injuries (
    season_id, incurred_season_id, player_id, club_short_name,
    label, status, catalogue_id, severity,
    matches_out, recovery_matches,
    matches_out_remaining, recovery_remaining,
    source_fixture_id
  )
  VALUES (
    p_season_id, p_season_id, p_player_id, p_club,
    v_cat.name, 'active', v_cat.id, v_cat.severity,
    v_cat.matches_out, v_cat.recovery_matches,
    v_cat.matches_out, v_cat.recovery_matches,
    p_source_fixture_id
  )
  RETURNING id INTO v_id;

  UPDATE public.competition_club_injury_season
  SET count_total = count_total + 1,
      count_major = count_major + CASE WHEN v_cat.severity = 'Major' THEN 1 ELSE 0 END,
      count_moderate = count_moderate + CASE WHEN v_cat.severity = 'Moderate' THEN 1 ELSE 0 END,
      count_minor = count_minor + CASE WHEN v_cat.severity = 'Minor' THEN 1 ELSE 0 END
  WHERE season_id = p_season_id AND club_short_name = p_club;

  PERFORM public.competition_injury_assign_fixtures(v_id);
  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_injury_pick_severity(
  p_state public.competition_club_injury_season,
  p_settings public.competition_injury_settings
)
RETURNS text
LANGUAGE plpgsql
STABLE
SET search_path = public
AS $function$
DECLARE
  v_w_min numeric := 0;
  v_w_mod numeric := 0;
  v_w_maj numeric := 0;
  v_total numeric;
  v_roll numeric;
BEGIN
  IF p_state.count_total >= p_settings.max_total THEN
    RETURN NULL;
  END IF;

  IF p_state.count_minor < p_settings.max_minor THEN
    v_w_min := p_settings.weight_minor;
  END IF;
  IF p_state.count_moderate < p_settings.max_moderate THEN
    v_w_mod := p_settings.weight_moderate;
  END IF;
  IF p_state.count_major < p_settings.max_major THEN
    v_w_maj := p_settings.weight_major;
  END IF;

  v_total := v_w_min + v_w_mod + v_w_maj;
  IF v_total <= 0 THEN
    RETURN NULL;
  END IF;

  v_roll := random() * v_total;
  IF v_roll < v_w_min THEN
    RETURN 'Minor';
  ELSIF v_roll < v_w_min + v_w_mod THEN
    RETURN 'Moderate';
  END IF;
  RETURN 'Major';
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_injury_roll_for_club(
  p_fixture_id bigint,
  p_club text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures%rowtype;
  v_settings public.competition_injury_settings;
  v_state public.competition_club_injury_season;
  v_chance numeric;
  v_severity text;
  v_cat public.competition_injury_catalogue%rowtype;
  v_player_id text;
  v_injury_id bigint;
  v_fit_gk int;
BEGIN
  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'fixture_not_found');
  END IF;

  IF v_fixture.status <> 'played' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'fixture_not_played');
  END IF;

  IF public.competition_injury_is_preseason_month(v_fixture.gpsl_month) THEN
    INSERT INTO public.competition_fixture_injury_roll (fixture_id, club_short_name, did_injure)
    VALUES (p_fixture_id, p_club, false)
    ON CONFLICT DO NOTHING;
    RETURN jsonb_build_object('ok', true, 'did_injure', false, 'reason', 'preseason_month');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.competition_match_player_stats m
    WHERE m.fixture_id = p_fixture_id
      AND m.club_short_name = p_club
      AND m.appeared = true
  ) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_stats_yet');
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.competition_fixture_injury_roll r
    WHERE r.fixture_id = p_fixture_id AND r.club_short_name = p_club
  ) THEN
    RETURN jsonb_build_object('ok', true, 'did_injure', false, 'reason', 'already_rolled');
  END IF;

  v_settings := public.competition_injury_settings_row();
  v_state := public.competition_injury_ensure_club_season(v_fixture.season_id, p_club);

  IF v_state.count_total >= v_settings.max_total THEN
    INSERT INTO public.competition_fixture_injury_roll (fixture_id, club_short_name, did_injure)
    VALUES (p_fixture_id, p_club, false);
    RETURN jsonb_build_object('ok', true, 'did_injure', false, 'reason', 'cap_total');
  END IF;

  v_chance := least(1.0, greatest(0.0, v_settings.base_match_chance * v_state.injury_risk));
  IF random() >= v_chance THEN
    INSERT INTO public.competition_fixture_injury_roll (fixture_id, club_short_name, did_injure)
    VALUES (p_fixture_id, p_club, false);
    RETURN jsonb_build_object('ok', true, 'did_injure', false, 'reason', 'no_hit');
  END IF;

  v_severity := public.competition_injury_pick_severity(v_state, v_settings);
  IF v_severity IS NULL THEN
    INSERT INTO public.competition_fixture_injury_roll (fixture_id, club_short_name, did_injure)
    VALUES (p_fixture_id, p_club, false);
    RETURN jsonb_build_object('ok', true, 'did_injure', false, 'reason', 'no_severity_left');
  END IF;

  SELECT * INTO v_cat
  FROM public.competition_injury_catalogue c
  WHERE c.active AND c.severity = v_severity
  ORDER BY random()
  LIMIT 1;

  IF NOT FOUND THEN
    INSERT INTO public.competition_fixture_injury_roll (fixture_id, club_short_name, did_injure)
    VALUES (p_fixture_id, p_club, false);
    RETURN jsonb_build_object('ok', true, 'did_injure', false, 'reason', 'empty_catalogue');
  END IF;

  v_fit_gk := public.competition_injury_fit_gk_count(p_club);

  SELECT m.player_id INTO v_player_id
  FROM public.competition_match_player_stats m
  JOIN public."Players" p ON p."Konami_ID"::text = m.player_id
  WHERE m.fixture_id = p_fixture_id
    AND m.club_short_name = p_club
    AND m.appeared = true
    AND NOT public.competition_injury_player_is_out(m.player_id)
    AND NOT (
      upper(coalesce(p."Position", '')) = 'GK'
      AND v_fit_gk <= 1
    )
  ORDER BY random()
  LIMIT 1;

  IF v_player_id IS NULL THEN
    INSERT INTO public.competition_fixture_injury_roll (fixture_id, club_short_name, did_injure)
    VALUES (p_fixture_id, p_club, false);
    RETURN jsonb_build_object('ok', true, 'did_injure', false, 'reason', 'no_eligible_player');
  END IF;

  v_injury_id := public.competition_injury_issue(
    v_fixture.season_id, p_club, v_player_id, v_cat.id, p_fixture_id
  );

  INSERT INTO public.competition_fixture_injury_roll (
    fixture_id, club_short_name, did_injure, injury_id
  ) VALUES (p_fixture_id, p_club, true, v_injury_id);

  RETURN jsonb_build_object(
    'ok', true,
    'did_injure', true,
    'injury_id', v_injury_id,
    'player_id', v_player_id,
    'injury', v_cat.name,
    'severity', v_cat.severity
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_injury_roll_for_fixture(p_fixture_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures%rowtype;
  v_home jsonb;
  v_away jsonb;
BEGIN
  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false);
  END IF;

  v_home := public.competition_injury_roll_for_club(p_fixture_id, v_fixture.home_club_short_name);
  v_away := public.competition_injury_roll_for_club(p_fixture_id, v_fixture.away_club_short_name);

  RETURN jsonb_build_object('ok', true, 'home', v_home, 'away', v_away);
END;
$function$;

-- Serve injury fixture absences + decrement remaining
CREATE OR REPLACE FUNCTION public.competition_serve_injuries_for_fixture(
  p_fixture_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_row record;
BEGIN
  FOR v_row IN
    SELECT iff.id, iff.injury_id, iff.phase
    FROM public.competition_player_injury_fixtures iff
    WHERE iff.fixture_id = p_fixture_id
      AND iff.served = false
  LOOP
    UPDATE public.competition_player_injury_fixtures
    SET served = true
    WHERE id = v_row.id;

    IF v_row.phase = 'out' THEN
      UPDATE public.competition_player_injuries
      SET matches_out_remaining = greatest(coalesce(matches_out_remaining, 1) - 1, 0)
      WHERE id = v_row.injury_id;
    ELSE
      UPDATE public.competition_player_injuries
      SET recovery_remaining = greatest(coalesce(recovery_remaining, 1) - 1, 0)
      WHERE id = v_row.injury_id;
    END IF;
  END LOOP;

  UPDATE public.competition_player_injuries i
  SET status = 'recovered',
      recovered_at = coalesce(i.recovered_at, now())
  WHERE i.status = 'active'
    AND coalesce(i.matches_out_remaining, 0) <= 0
    AND coalesce(i.recovery_remaining, 0) <= 0
    AND EXISTS (
      SELECT 1 FROM public.competition_player_injury_fixtures iff
      WHERE iff.injury_id = i.id
    )
    AND NOT EXISTS (
      SELECT 1 FROM public.competition_player_injury_fixtures iff
      WHERE iff.injury_id = i.id AND iff.served = false
    );

  -- Roll new injuries for this fixture (idempotent per club)
  PERFORM public.competition_injury_roll_for_fixture(p_fixture_id);
END;
$function$;

-- Pre-season virtual match ticks
CREATE OR REPLACE FUNCTION public.competition_injury_tick_preseason_month(
  p_season_id bigint,
  p_gpsl_month text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_settings public.competition_injury_settings;
  v_month text := lower(btrim(p_gpsl_month));
  v_ticks int;
  v_inj record;
  v_left int;
  v_updated int := 0;
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  v_settings := public.competition_injury_settings_row();
  IF NOT public.competition_injury_is_preseason_month(v_month) THEN
    RAISE EXCEPTION 'Month % is not configured as a pre-season month', v_month;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.competition_injury_preseason_tick t
    WHERE t.season_id = p_season_id AND t.gpsl_month = v_month
  ) THEN
    RETURN jsonb_build_object('ok', true, 'already_applied', true, 'month', v_month);
  END IF;

  v_ticks := greatest(v_settings.preseason_matches_per_month, 0);

  FOR v_inj IN
    SELECT *
    FROM public.competition_player_injuries i
    WHERE i.status = 'active'
      AND (
        i.season_id = p_season_id
        OR i.incurred_season_id = p_season_id
        OR EXISTS (
          SELECT 1 FROM public.competition_club_injury_season cis
          WHERE cis.season_id = p_season_id
            AND cis.club_short_name = i.club_short_name
        )
      )
  LOOP
    v_left := v_ticks;

    WHILE v_left > 0 AND coalesce(v_inj.matches_out_remaining, 0) > 0 LOOP
      v_inj.matches_out_remaining := v_inj.matches_out_remaining - 1;
      v_left := v_left - 1;
    END LOOP;

    WHILE v_left > 0 AND coalesce(v_inj.recovery_remaining, 0) > 0 LOOP
      v_inj.recovery_remaining := v_inj.recovery_remaining - 1;
      v_left := v_left - 1;
    END LOOP;

    UPDATE public.competition_player_injuries
    SET matches_out_remaining = v_inj.matches_out_remaining,
        recovery_remaining = v_inj.recovery_remaining,
        status = CASE
          WHEN coalesce(v_inj.matches_out_remaining, 0) <= 0
           AND coalesce(v_inj.recovery_remaining, 0) <= 0
          THEN 'recovered'
          ELSE status
        END,
        recovered_at = CASE
          WHEN coalesce(v_inj.matches_out_remaining, 0) <= 0
           AND coalesce(v_inj.recovery_remaining, 0) <= 0
          THEN coalesce(recovered_at, now())
          ELSE recovered_at
        END
    WHERE id = v_inj.id;

    DELETE FROM public.competition_player_injury_fixtures
    WHERE injury_id = v_inj.id AND served = false;

    IF coalesce(v_inj.matches_out_remaining, 0) > 0
       OR coalesce(v_inj.recovery_remaining, 0) > 0 THEN
      PERFORM public.competition_injury_assign_fixtures(v_inj.id);
    END IF;

    v_updated := v_updated + 1;
  END LOOP;

  INSERT INTO public.competition_injury_preseason_tick (season_id, gpsl_month, ticks_applied)
  VALUES (p_season_id, v_month, v_ticks);

  RETURN jsonb_build_object(
    'ok', true,
    'month', v_month,
    'ticks', v_ticks,
    'injuries_updated', v_updated
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_injury_init_season_risks(p_season_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_n int := 0;
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  FOR v_club IN
    SELECT DISTINCT r.club_short_name
    FROM public.competition_club_seasons r
    WHERE r.season_id = p_season_id
  LOOP
    PERFORM public.competition_injury_ensure_club_season(p_season_id, v_club);
    v_n := v_n + 1;
  END LOOP;

  -- Also ensure any club with players
  IF v_n = 0 THEN
    FOR v_club IN
      SELECT DISTINCT p."Contracted_Team"
      FROM public."Players" p
      WHERE p."Contracted_Team" IS NOT NULL AND btrim(p."Contracted_Team") <> ''
    LOOP
      PERFORM public.competition_injury_ensure_club_season(p_season_id, v_club);
      v_n := v_n + 1;
    END LOOP;
  END IF;

  RETURN jsonb_build_object('ok', true, 'clubs', v_n);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Admin settings RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.admin_injury_settings_get()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  RETURN to_jsonb(public.competition_injury_settings_row());
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_injury_settings_save(p_settings jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  UPDATE public.competition_injury_settings
  SET max_major = coalesce((p_settings ->> 'max_major')::int, max_major),
      max_moderate = coalesce((p_settings ->> 'max_moderate')::int, max_moderate),
      max_minor = coalesce((p_settings ->> 'max_minor')::int, max_minor),
      max_total = coalesce((p_settings ->> 'max_total')::int, max_total),
      base_match_chance = coalesce((p_settings ->> 'base_match_chance')::numeric, base_match_chance),
      weight_minor = coalesce((p_settings ->> 'weight_minor')::numeric, weight_minor),
      weight_moderate = coalesce((p_settings ->> 'weight_moderate')::numeric, weight_moderate),
      weight_major = coalesce((p_settings ->> 'weight_major')::numeric, weight_major),
      preseason_months = coalesce(
        ARRAY(SELECT jsonb_array_elements_text(p_settings -> 'preseason_months')),
        preseason_months
      ),
      preseason_matches_per_month = coalesce(
        (p_settings ->> 'preseason_matches_per_month')::int,
        preseason_matches_per_month
      ),
      risk_min = coalesce((p_settings ->> 'risk_min')::numeric, risk_min),
      risk_max = coalesce((p_settings ->> 'risk_max')::numeric, risk_max),
      updated_at = now()
  WHERE id = 1;

  RETURN public.admin_injury_settings_get();
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_injury_club_risks(p_season_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season bigint := p_season_id;
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_season IS NULL THEN
    SELECT s.id INTO v_season
    FROM public.competition_seasons s
    WHERE s.is_current = true
    ORDER BY s.id DESC
    LIMIT 1;
  END IF;

  RETURN coalesce((
    SELECT jsonb_agg(
      jsonb_build_object(
        'season_id', cis.season_id,
        'club_short_name', cis.club_short_name,
        'club_name', c."Club",
        'injury_risk', cis.injury_risk,
        'count_major', cis.count_major,
        'count_moderate', cis.count_moderate,
        'count_minor', cis.count_minor,
        'count_total', cis.count_total
      )
      ORDER BY c."Club" NULLS LAST, cis.club_short_name
    )
    FROM public.competition_club_injury_season cis
    LEFT JOIN public."Clubs" c ON c."ShortName" = cis.club_short_name
    WHERE cis.season_id = v_season
  ), '[]'::jsonb);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_injury_active_list(p_season_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season bigint := p_season_id;
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  RETURN coalesce((
    SELECT jsonb_agg(
      jsonb_build_object(
        'id', i.id,
        'player_id', i.player_id,
        'player_name', p."Name",
        'club_short_name', i.club_short_name,
        'label', i.label,
        'severity', i.severity,
        'matches_out_remaining', i.matches_out_remaining,
        'recovery_remaining', i.recovery_remaining,
        'status', i.status,
        'created_at', i.created_at
      )
      ORDER BY i.created_at DESC
    )
    FROM public.competition_player_injuries i
    LEFT JOIN public."Players" p ON p."Konami_ID"::text = i.player_id
    WHERE i.status = 'active'
      AND (v_season IS NULL OR i.season_id = v_season OR i.incurred_season_id = v_season)
  ), '[]'::jsonb);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Update unavailable RPC (injured vs gaining match fitness)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_fixture_unavailable_players(
  p_fixture_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures%rowtype;
  v_club text := public.my_club_shortname();
  v_home jsonb;
  v_away jsonb;
BEGIN
  SELECT * INTO v_fixture
  FROM public.competition_fixtures
  WHERE id = p_fixture_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role')
     AND (
       v_club IS NULL
       OR v_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name)
     ) THEN
    RAISE EXCEPTION 'Only participating clubs can view unavailable players for this fixture';
  END IF;

  WITH suspended AS (
    SELECT
      s.club_short_name,
      s.player_id,
      p."Name" AS player_name,
      p."Position" AS position,
      'suspended'::text AS reason,
      CASE
        WHEN s.reason = 'red_card' THEN 'Suspended — red card (2-match ban)'
        WHEN s.reason = 'yellow_accumulation' THEN
          format(
            'Suspended — %s yellows (2-match ban)',
            coalesce(s.yellow_count_at_issue, 8)
          )
        ELSE 'Suspended'
      END AS detail,
      s.id AS source_id
    FROM public.competition_player_suspension_matches sm
    JOIN public.competition_player_suspensions s ON s.id = sm.suspension_id
    LEFT JOIN public."Players" p ON p."Konami_ID"::text = s.player_id
    WHERE sm.fixture_id = p_fixture_id
      AND sm.served = false
      AND s.status = 'active'
  ),
  injured AS (
    SELECT
      i.club_short_name,
      i.player_id,
      p."Name" AS player_name,
      p."Position" AS position,
      CASE
        WHEN iff.phase = 'recovery' THEN 'recovery'
        ELSE 'injured'
      END AS reason,
      CASE
        WHEN iff.phase = 'recovery' THEN
          format('Gaining match fitness — %s', coalesce(i.label, 'Injury'))
        ELSE
          format('Injured — %s', coalesce(i.label, 'Injured'))
      END AS detail,
      i.id AS source_id
    FROM public.competition_player_injury_fixtures iff
    JOIN public.competition_player_injuries i ON i.id = iff.injury_id
    LEFT JOIN public."Players" p ON p."Konami_ID"::text = i.player_id
    WHERE iff.fixture_id = p_fixture_id
      AND iff.served = false
      AND i.status = 'active'
  ),
  combined AS (
    SELECT * FROM suspended
    UNION ALL
    SELECT * FROM injured
  )
  SELECT
    coalesce((
      SELECT jsonb_agg(
        jsonb_build_object(
          'player_id', c.player_id,
          'player_name', coalesce(c.player_name, c.player_id),
          'position', c.position,
          'reason', c.reason,
          'detail', c.detail,
          'source_id', c.source_id
        )
        ORDER BY c.reason, c.player_name
      )
      FROM combined c
      WHERE c.club_short_name = v_fixture.home_club_short_name
    ), '[]'::jsonb),
    coalesce((
      SELECT jsonb_agg(
        jsonb_build_object(
          'player_id', c.player_id,
          'player_name', coalesce(c.player_name, c.player_id),
          'position', c.position,
          'reason', c.reason,
          'detail', c.detail,
          'source_id', c.source_id
        )
        ORDER BY c.reason, c.player_name
      )
      FROM combined c
      WHERE c.club_short_name = v_fixture.away_club_short_name
    ), '[]'::jsonb)
  INTO v_home, v_away;

  RETURN jsonb_build_object(
    'fixture_id', p_fixture_id,
    'home_club_short_name', v_fixture.home_club_short_name,
    'away_club_short_name', v_fixture.away_club_short_name,
    'home', coalesce(v_home, '[]'::jsonb),
    'away', coalesce(v_away, '[]'::jsonb)
  );
END;
$function$;

-- Block recovery + out via unavailable helper
CREATE OR REPLACE FUNCTION public.competition_player_unavailable_for_fixture(
  p_fixture_id bigint,
  p_player_id text
)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
  SELECT detail
  FROM (
    SELECT
      CASE
        WHEN s.reason = 'red_card' THEN 'Suspended — red card'
        WHEN s.reason = 'yellow_accumulation' THEN 'Suspended — yellow accumulation'
        ELSE 'Suspended'
      END AS detail,
      1 AS ord
    FROM public.competition_player_suspension_matches sm
    JOIN public.competition_player_suspensions s ON s.id = sm.suspension_id
    WHERE sm.fixture_id = p_fixture_id
      AND sm.served = false
      AND s.status = 'active'
      AND s.player_id = p_player_id

    UNION ALL

    SELECT
      CASE
        WHEN iff.phase = 'recovery' THEN
          format('Gaining match fitness — %s', coalesce(nullif(btrim(i.label), ''), 'Injury'))
        ELSE
          format('Injured — %s', coalesce(nullif(btrim(i.label), ''), 'Injured'))
      END AS detail,
      2 AS ord
    FROM public.competition_player_injury_fixtures iff
    JOIN public.competition_player_injuries i ON i.id = iff.injury_id
    WHERE iff.fixture_id = p_fixture_id
      AND iff.served = false
      AND i.status = 'active'
      AND i.player_id = p_player_id
  ) x
  ORDER BY ord
  LIMIT 1;
$function$;

-- Keep serve_suspensions calling injury serve (which now also rolls)
CREATE OR REPLACE FUNCTION public.competition_serve_suspensions_for_fixture(
  p_fixture_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  UPDATE public.competition_player_suspension_matches sm
  SET served = true
  WHERE sm.fixture_id = p_fixture_id
    AND sm.served = false;

  UPDATE public.competition_player_suspensions s
  SET status = 'completed'
  WHERE s.status = 'active'
    AND EXISTS (
      SELECT 1 FROM public.competition_player_suspension_matches sm
      WHERE sm.suspension_id = s.id
    )
    AND NOT EXISTS (
      SELECT 1 FROM public.competition_player_suspension_matches sm
      WHERE sm.suspension_id = s.id
        AND sm.served = false
    );

  PERFORM public.competition_serve_injuries_for_fixture(p_fixture_id);
END;
$function$;

GRANT SELECT ON TABLE public.competition_injury_catalogue TO authenticated;
GRANT SELECT ON TABLE public.competition_injury_settings TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_injury_settings_get() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_injury_settings_save(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_injury_club_risks(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_injury_active_list(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_injury_tick_preseason_month(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_injury_init_season_risks(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_fixture_unavailable_players(bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';
