-- =============================================================================
-- Challenge target templates (survive season / league resets)
--
-- competition_challenge_config is tied to season_id ON DELETE CASCADE.
-- Templates live outside seasons so admin can re-apply after a reset.
--
-- Safe re-run.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.competition_challenge_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  -- Array of challenge objects (no season_id)
  targets jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_challenge_templates_name_nonempty
    CHECK (nullif(btrim(name), '') IS NOT NULL),
  CONSTRAINT competition_challenge_templates_targets_array
    CHECK (jsonb_typeof(targets) = 'array')
);

CREATE UNIQUE INDEX IF NOT EXISTS competition_challenge_templates_name_uidx
  ON public.competition_challenge_templates (lower(btrim(name)));

ALTER TABLE public.competition_challenge_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_challenge_templates_select ON public.competition_challenge_templates;
CREATE POLICY competition_challenge_templates_select
  ON public.competition_challenge_templates
  FOR SELECT TO authenticated
  USING (public.is_gpsl_admin());

COMMENT ON TABLE public.competition_challenge_templates IS
  'Named challenge target presets — not season-scoped; survives league/season resets.';

-- Snapshot current season targets into a named template
CREATE OR REPLACE FUNCTION public.competition_admin_save_challenge_template(
  p_name text,
  p_season_id bigint DEFAULT NULL,
  p_description text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_name text := nullif(btrim(coalesce(p_name, '')), '');
  v_targets jsonb;
  v_id bigint;
  v_count int;
  v_desc text := nullif(btrim(coalesce(p_description, '')), '');
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_name IS NULL THEN
    RAISE EXCEPTION 'Template name required';
  END IF;

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No current season';
  END IF;

  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'title', c.title,
      'description', c.description,
      'window_phase', c.window_phase,
      'gpsl_month_from', c.gpsl_month_from,
      'gpsl_month_to', c.gpsl_month_to,
      'stat_type', c.stat_type,
      'stat_param', c.stat_param,
      'target_value', c.target_value,
      'prize_amount', c.prize_amount,
      'include_league', coalesce(c.include_league, true),
      'include_cup', coalesce(c.include_cup, false),
      'is_active', coalesce(c.is_active, true),
      'sort_order', coalesce(c.sort_order, 0)
    )
    ORDER BY c.window_phase, c.sort_order, c.id
  ), '[]'::jsonb)
  INTO v_targets
  FROM public.competition_challenge_config c
  WHERE c.season_id = v_season_id;

  v_count := jsonb_array_length(v_targets);
  IF v_count = 0 THEN
    RAISE EXCEPTION 'No challenge targets on this season to save';
  END IF;

  SELECT id INTO v_id
  FROM public.competition_challenge_templates
  WHERE lower(btrim(name)) = lower(v_name);

  IF v_id IS NULL THEN
    INSERT INTO public.competition_challenge_templates (name, description, targets)
    VALUES (v_name, v_desc, v_targets)
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.competition_challenge_templates
    SET
      name = v_name,
      description = coalesce(v_desc, description),
      targets = v_targets,
      updated_at = now()
    WHERE id = v_id;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'id', v_id,
    'name', v_name,
    'target_count', v_count,
    'season_id', v_season_id
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_list_challenge_templates()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  RETURN coalesce((
    SELECT jsonb_agg(
      jsonb_build_object(
        'id', t.id,
        'name', t.name,
        'description', t.description,
        'target_count', jsonb_array_length(coalesce(t.targets, '[]'::jsonb)),
        'start_count', (
          SELECT count(*)::int
          FROM jsonb_array_elements(coalesce(t.targets, '[]'::jsonb)) x
          WHERE x.value->>'window_phase' = 'start'
        ),
        'mid_count', (
          SELECT count(*)::int
          FROM jsonb_array_elements(coalesce(t.targets, '[]'::jsonb)) x
          WHERE x.value->>'window_phase' = 'mid'
        ),
        'updated_at', t.updated_at,
        'created_at', t.created_at
      )
      ORDER BY lower(t.name)
    )
    FROM public.competition_challenge_templates t
  ), '[]'::jsonb);
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_delete_challenge_template(p_template_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  DELETE FROM public.competition_challenge_templates WHERE id = p_template_id;
END;
$function$;

-- Apply template into a season for Start, Mid, or both.
-- p_window_phase: 'start' | 'mid' | NULL (NULL = all phases in the template)
-- p_replace: clears existing season targets for the selected phase(s) first
DROP FUNCTION IF EXISTS public.competition_admin_apply_challenge_template(bigint, bigint, boolean);
DROP FUNCTION IF EXISTS public.competition_admin_apply_challenge_template(bigint, bigint, boolean, text);

CREATE OR REPLACE FUNCTION public.competition_admin_apply_challenge_template(
  p_template_id bigint,
  p_season_id bigint DEFAULT NULL,
  p_replace boolean DEFAULT false,
  p_window_phase text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_targets jsonb;
  v_name text;
  v_row jsonb;
  v_inserted int := 0;
  v_existing int := 0;
  v_default numeric;
  v_title text;
  v_phase text;
  v_from text;
  v_to text;
  v_stat text;
  v_param text;
  v_target int;
  v_prize numeric;
  v_want text := nullif(lower(btrim(coalesce(p_window_phase, ''))), '');
  v_phase_count int := 0;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_want IS NOT NULL AND v_want NOT IN ('start', 'mid') THEN
    RAISE EXCEPTION 'window_phase must be start, mid, or null';
  END IF;

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No current season';
  END IF;

  SELECT name, targets INTO v_name, v_targets
  FROM public.competition_challenge_templates
  WHERE id = p_template_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Template not found';
  END IF;

  IF jsonb_typeof(v_targets) <> 'array' OR jsonb_array_length(v_targets) = 0 THEN
    RAISE EXCEPTION 'Template "%" has no targets', v_name;
  END IF;

  IF v_want IS NOT NULL THEN
    SELECT count(*)::int INTO v_phase_count
    FROM jsonb_array_elements(v_targets) x
    WHERE lower(btrim(coalesce(x.value->>'window_phase', ''))) = v_want;

    IF coalesce(v_phase_count, 0) = 0 THEN
      RAISE EXCEPTION 'Template "%" has no % challenges to apply',
        v_name,
        CASE v_want WHEN 'mid' THEN 'mid-season' ELSE 'start-of-season' END;
    END IF;
  END IF;

  SELECT count(*)::int INTO v_existing
  FROM public.competition_challenge_config
  WHERE season_id = v_season_id
    AND (v_want IS NULL OR window_phase = v_want);

  IF v_existing > 0 AND NOT coalesce(p_replace, false) THEN
    RAISE EXCEPTION
      'Season already has % % challenge(s). Pass replace=true to clear them first, or delete manually.',
      v_existing,
      CASE WHEN v_want IS NULL THEN 'total' WHEN v_want = 'mid' THEN 'mid-season' ELSE 'start-of-season' END;
  END IF;

  IF coalesce(p_replace, false) AND v_existing > 0 THEN
    DELETE FROM public.competition_challenge_config
    WHERE season_id = v_season_id
      AND (v_want IS NULL OR window_phase = v_want);
  END IF;

  v_default := coalesce(
    (SELECT challenge_default_prize FROM public.global_settings WHERE id = 1),
    1000000
  );

  FOR v_row IN SELECT * FROM jsonb_array_elements(v_targets)
  LOOP
    v_title := nullif(btrim(coalesce(v_row->>'title', '')), '');
    v_phase := lower(btrim(coalesce(v_row->>'window_phase', 'start')));
    v_from := lower(btrim(coalesce(v_row->>'gpsl_month_from', '')));
    v_to := lower(btrim(coalesce(v_row->>'gpsl_month_to', '')));
    v_stat := btrim(coalesce(v_row->>'stat_type', ''));
    v_param := nullif(btrim(coalesce(v_row->>'stat_param', '')), '');
    v_target := coalesce((v_row->>'target_value')::int, 0);
    v_prize := coalesce((v_row->>'prize_amount')::numeric, v_default);

    IF v_title IS NULL OR v_stat = '' OR v_target <= 0 THEN
      CONTINUE;
    END IF;
    IF v_phase NOT IN ('start', 'mid') THEN
      v_phase := 'start';
    END IF;

    -- Only apply the chosen window (Start or Mid)
    IF v_want IS NOT NULL AND v_phase <> v_want THEN
      CONTINUE;
    END IF;

    IF v_from IS NULL OR v_from = '' THEN
      v_from := CASE WHEN v_phase = 'mid' THEN 'january' ELSE 'august' END;
    END IF;
    IF v_to IS NULL OR v_to = '' THEN
      v_to := CASE WHEN v_phase = 'mid' THEN 'may' ELSE 'december' END;
    END IF;

    INSERT INTO public.competition_challenge_config (
      season_id, title, description, window_phase,
      gpsl_month_from, gpsl_month_to,
      stat_type, stat_param, target_value, prize_amount,
      include_league, include_cup, is_active, sort_order
    )
    VALUES (
      v_season_id,
      v_title,
      nullif(btrim(coalesce(v_row->>'description', '')), ''),
      v_phase,
      v_from,
      v_to,
      v_stat,
      v_param,
      v_target,
      greatest(v_prize, 0.01),
      coalesce((v_row->>'include_league')::boolean, true),
      coalesce((v_row->>'include_cup')::boolean, false),
      coalesce((v_row->>'is_active')::boolean, true),
      coalesce((v_row->>'sort_order')::smallint, 0)
    );

    v_inserted := v_inserted + 1;
  END LOOP;

  RETURN jsonb_build_object(
    'ok', true,
    'template_id', p_template_id,
    'template_name', v_name,
    'season_id', v_season_id,
    'window_phase', v_want,
    'replaced', coalesce(p_replace, false),
    'inserted', v_inserted
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.competition_admin_save_challenge_template(text, bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_list_challenge_templates() TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_delete_challenge_template(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_apply_challenge_template(bigint, bigint, boolean, text) TO authenticated;

NOTIFY pgrst, 'reload schema';
