-- =============================================================================
-- Match discipline: yellow/red cards, suspensions, GPSL history
--
-- Rules:
--   Red card          → 2-match ban (next club fixtures: league + cup)
--   Every 8 yellows   → 2-match ban (8, 16, 24, … this season)
-- Cards are ticked on Match Day stats and stored on competition_match_player_stats.
--
-- Run once. Safe re-run.
-- =============================================================================

ALTER TABLE public.competition_match_player_stats
  ADD COLUMN IF NOT EXISTS yellow_card boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS red_card boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.competition_player_suspensions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  player_id text NOT NULL,
  club_short_name text NOT NULL,
  reason text NOT NULL CHECK (reason IN ('red_card', 'yellow_accumulation')),
  yellow_count_at_issue integer,
  source_fixture_id bigint REFERENCES public.competition_fixtures (id) ON DELETE SET NULL,
  ban_matches smallint NOT NULL DEFAULT 2 CHECK (ban_matches > 0),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_player_suspensions_source_unique
    UNIQUE (player_id, source_fixture_id, reason)
);

CREATE INDEX IF NOT EXISTS competition_player_suspensions_player_idx
  ON public.competition_player_suspensions (player_id, season_id);

CREATE INDEX IF NOT EXISTS competition_player_suspensions_club_active_idx
  ON public.competition_player_suspensions (club_short_name, season_id)
  WHERE status = 'active';

CREATE TABLE IF NOT EXISTS public.competition_player_suspension_matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suspension_id bigint NOT NULL
    REFERENCES public.competition_player_suspensions (id) ON DELETE CASCADE,
  fixture_id bigint NOT NULL REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  sequence_no smallint NOT NULL CHECK (sequence_no > 0),
  served boolean NOT NULL DEFAULT false,
  CONSTRAINT competition_player_suspension_matches_seq UNIQUE (suspension_id, sequence_no),
  CONSTRAINT competition_player_suspension_matches_fix UNIQUE (suspension_id, fixture_id)
);

CREATE INDEX IF NOT EXISTS competition_player_suspension_matches_fixture_idx
  ON public.competition_player_suspension_matches (fixture_id)
  WHERE served = false;

-- ---------------------------------------------------------------------------
-- Fixture short label for UI ("MD12 vs Arsenal", cup labels)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_fixture_discipline_label(
  p_fixture public.competition_fixtures,
  p_club text
)
RETURNS text
LANGUAGE plpgsql
STABLE
SET search_path = public
AS $function$
DECLARE
  v_opp text;
  v_opp_name text;
  v_base text;
BEGIN
  IF p_fixture.home_club_short_name = p_club THEN
    v_opp := p_fixture.away_club_short_name;
  ELSE
    v_opp := p_fixture.home_club_short_name;
  END IF;

  SELECT c."Club" INTO v_opp_name
  FROM public."Clubs" c
  WHERE c."ShortName" = v_opp;

  IF p_fixture.competition_type = 'cup'
     AND to_regprocedure('public.competition_cup_fixture_label(public.competition_fixtures)') IS NOT NULL THEN
    v_base := public.competition_cup_fixture_label(p_fixture);
  ELSE
    v_base := format('MD%s', coalesce(p_fixture.matchday::text, '?'));
  END IF;

  RETURN format('%s vs %s', v_base, coalesce(v_opp_name, v_opp, '?'));
END;
$function$;

-- ---------------------------------------------------------------------------
-- Next N unplayed fixtures for a club (after a source fixture)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_next_club_fixtures(
  p_season_id bigint,
  p_club text,
  p_after_fixture_id bigint,
  p_limit int DEFAULT 2
)
RETURNS TABLE (fixture_id bigint, seq int)
LANGUAGE sql
STABLE
SET search_path = public
AS $function$
  WITH upcoming AS (
    SELECT
      f.id,
      row_number() OVER (
        ORDER BY
          CASE
            WHEN to_regprocedure('public.match_schedule_agreed_kickoff(bigint)') IS NOT NULL
            THEN coalesce(
              public.match_schedule_agreed_kickoff(f.id),
              'infinity'::timestamptz
            )
            ELSE 'infinity'::timestamptz
          END,
          coalesce(f.matchday, 9999),
          f.id
      )::int AS seq
    FROM public.competition_fixtures f
    WHERE f.season_id = p_season_id
      AND f.status = 'scheduled'
      AND f.id IS DISTINCT FROM p_after_fixture_id
      AND (f.home_club_short_name = p_club OR f.away_club_short_name = p_club)
  )
  SELECT u.id, u.seq
  FROM upcoming u
  WHERE u.seq <= greatest(p_limit, 1);
$function$;

-- ---------------------------------------------------------------------------
-- Create or refresh a suspension + assign next matches
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_issue_player_suspension(
  p_season_id bigint,
  p_player_id text,
  p_club text,
  p_reason text,
  p_source_fixture_id bigint,
  p_yellow_count int DEFAULT NULL,
  p_ban_matches int DEFAULT 2
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint;
  v_fx record;
BEGIN
  INSERT INTO public.competition_player_suspensions (
    season_id, player_id, club_short_name, reason,
    yellow_count_at_issue, source_fixture_id, ban_matches, status
  )
  VALUES (
    p_season_id, p_player_id, p_club, p_reason,
    p_yellow_count, p_source_fixture_id, p_ban_matches, 'active'
  )
  ON CONFLICT (player_id, source_fixture_id, reason) DO UPDATE
    SET yellow_count_at_issue = excluded.yellow_count_at_issue,
        ban_matches = excluded.ban_matches,
        status = 'active'
  RETURNING id INTO v_id;

  DELETE FROM public.competition_player_suspension_matches
  WHERE suspension_id = v_id
    AND served = false;

  FOR v_fx IN
    SELECT *
    FROM public.competition_next_club_fixtures(
      p_season_id, p_club, p_source_fixture_id, p_ban_matches
    )
  LOOP
    INSERT INTO public.competition_player_suspension_matches (
      suspension_id, fixture_id, sequence_no, served
    )
    VALUES (v_id, v_fx.fixture_id, v_fx.seq, false)
    ON CONFLICT (suspension_id, fixture_id) DO NOTHING;
  END LOOP;

  RETURN v_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- After stats written: cards → suspensions; block banned players
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_process_match_discipline(
  p_fixture_id bigint,
  p_season_id bigint,
  p_club text,
  p_player_stats jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_item jsonb;
  v_player_id text;
  v_appeared boolean;
  v_started boolean;
  v_subbed boolean;
  v_yellow boolean;
  v_red boolean;
  v_y_count int;
  v_prev_count int;
  v_threshold int;
BEGIN
  FOR v_item IN SELECT value FROM jsonb_array_elements(coalesce(p_player_stats, '[]'::jsonb))
  LOOP
    v_player_id := trim(both '"' FROM (v_item ->> 'player_id'));
    IF v_player_id IS NULL OR v_player_id = '' THEN
      CONTINUE;
    END IF;

    v_started := coalesce((v_item ->> 'started')::boolean, false);
    v_subbed := coalesce((v_item ->> 'subbed_on')::boolean, false);
    IF v_item ? 'started' OR v_item ? 'subbed_on' THEN
      v_appeared := v_started OR v_subbed;
    ELSE
      v_appeared := coalesce((v_item ->> 'appeared')::boolean, false);
    END IF;

    v_yellow := coalesce((v_item ->> 'yellow_card')::boolean, false)
      OR coalesce((v_item ->> 'yellow')::boolean, false);
    v_red := coalesce((v_item ->> 'red_card')::boolean, false)
      OR coalesce((v_item ->> 'red')::boolean, false);

    IF (v_yellow OR v_red) AND NOT v_appeared THEN
      RAISE EXCEPTION 'Player % must have appeared to receive a card', v_player_id;
    END IF;

    IF v_appeared AND EXISTS (
      SELECT 1
      FROM public.competition_player_suspension_matches sm
      JOIN public.competition_player_suspensions s ON s.id = sm.suspension_id
      WHERE sm.fixture_id = p_fixture_id
        AND sm.served = false
        AND s.player_id = v_player_id
        AND s.status = 'active'
    ) THEN
      RAISE EXCEPTION 'Player % is suspended for this match', v_player_id;
    END IF;
  END LOOP;

  -- Persist card flags on written rows
  FOR v_item IN SELECT value FROM jsonb_array_elements(coalesce(p_player_stats, '[]'::jsonb))
  LOOP
    v_player_id := trim(both '"' FROM (v_item ->> 'player_id'));
    IF v_player_id IS NULL OR v_player_id = '' THEN
      CONTINUE;
    END IF;

    v_yellow := coalesce((v_item ->> 'yellow_card')::boolean, false)
      OR coalesce((v_item ->> 'yellow')::boolean, false);
    v_red := coalesce((v_item ->> 'red_card')::boolean, false)
      OR coalesce((v_item ->> 'red')::boolean, false);

    UPDATE public.competition_match_player_stats
    SET yellow_card = v_yellow,
        red_card = v_red
    WHERE fixture_id = p_fixture_id
      AND club_short_name = p_club
      AND player_id = v_player_id;
  END LOOP;

  -- Issue bans from this match's cards
  FOR v_item IN SELECT value FROM jsonb_array_elements(coalesce(p_player_stats, '[]'::jsonb))
  LOOP
    v_player_id := trim(both '"' FROM (v_item ->> 'player_id'));
    IF v_player_id IS NULL OR v_player_id = '' THEN
      CONTINUE;
    END IF;

    v_yellow := coalesce((v_item ->> 'yellow_card')::boolean, false)
      OR coalesce((v_item ->> 'yellow')::boolean, false);
    v_red := coalesce((v_item ->> 'red_card')::boolean, false)
      OR coalesce((v_item ->> 'red')::boolean, false);

    IF v_red THEN
      PERFORM public.competition_issue_player_suspension(
        p_season_id, v_player_id, p_club, 'red_card', p_fixture_id, NULL, 2
      );
    END IF;

    IF v_yellow THEN
      SELECT count(*)::int
      INTO v_y_count
      FROM public.competition_match_player_stats m
      WHERE m.season_id = p_season_id
        AND m.player_id = v_player_id
        AND m.yellow_card = true;

      v_prev_count := greatest(v_y_count - 1, 0);
      IF (v_y_count / 8) > (v_prev_count / 8) THEN
        v_threshold := (v_y_count / 8) * 8;
        PERFORM public.competition_issue_player_suspension(
          p_season_id, v_player_id, p_club, 'yellow_accumulation',
          p_fixture_id, v_threshold, 2
        );
      END IF;
    END IF;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_serve_suspensions_for_fixture(
  p_fixture_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  UPDATE public.competition_player_suspension_matches sm
  SET served = true
  WHERE sm.fixture_id = p_fixture_id
    AND sm.served = false;

  UPDATE public.competition_player_suspensions s
  SET status = 'completed'
  WHERE s.status = 'active'
    AND EXISTS (
      SELECT 1 FROM public.competition_player_suspension_matches sm
      WHERE sm.suspension_id = s.id
    )
    AND NOT EXISTS (
      SELECT 1 FROM public.competition_player_suspension_matches sm
      WHERE sm.suspension_id = s.id
        AND sm.served = false
    );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Apply club stats (extended with cards + discipline)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_apply_club_player_stats(
  p_fixture_id bigint,
  p_season_id bigint,
  p_club text,
  p_player_stats jsonb,
  p_expected_goals int
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_item jsonb;
  v_player_id text;
  v_goals int;
  v_assists int;
  v_rating numeric;
  v_potm boolean;
  v_started boolean;
  v_subbed boolean;
  v_appeared boolean;
  v_yellow boolean;
  v_red boolean;
  v_team_goals int := 0;
  v_potm_count int := 0;
  v_started_count int := 0;
  v_subbed_count int := 0;
BEGIN
  IF p_player_stats IS NULL OR jsonb_typeof(p_player_stats) <> 'array' THEN
    RAISE EXCEPTION 'player_stats must be a JSON array';
  END IF;

  IF jsonb_array_length(p_player_stats) = 0 THEN
    RAISE EXCEPTION 'Squad match stats are required';
  END IF;

  DELETE FROM public.competition_match_player_stats
  WHERE fixture_id = p_fixture_id
    AND club_short_name = p_club;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_player_stats)
  LOOP
    v_player_id := trim(both '"' FROM (v_item ->> 'player_id'));
    v_goals := coalesce((v_item ->> 'goals')::int, 0);
    v_assists := coalesce((v_item ->> 'assists')::int, 0);
    v_rating := nullif(v_item ->> 'rating', '')::numeric;
    v_potm := coalesce((v_item ->> 'potm')::boolean, false);
    v_started := coalesce((v_item ->> 'started')::boolean, false);
    v_subbed := coalesce((v_item ->> 'subbed_on')::boolean, false);
    v_yellow := coalesce((v_item ->> 'yellow_card')::boolean, false)
      OR coalesce((v_item ->> 'yellow')::boolean, false);
    v_red := coalesce((v_item ->> 'red_card')::boolean, false)
      OR coalesce((v_item ->> 'red')::boolean, false);

    IF v_item ? 'started' OR v_item ? 'subbed_on' THEN
      v_appeared := v_started OR v_subbed;
    ELSE
      v_appeared := coalesce((v_item ->> 'appeared')::boolean, false);
    END IF;

    IF v_started AND v_subbed THEN
      RAISE EXCEPTION 'Player % cannot be both started and subbed on', v_player_id;
    END IF;

    IF v_player_id IS NULL OR v_player_id = '' THEN
      CONTINUE;
    END IF;

    IF NOT v_appeared
       AND v_goals = 0 AND v_assists = 0 AND v_rating IS NULL AND NOT v_potm
       AND NOT v_yellow AND NOT v_red THEN
      CONTINUE;
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM public."Players" p
      WHERE p."Konami_ID"::text = v_player_id
        AND p."Contracted_Team" = p_club
    ) THEN
      RAISE EXCEPTION 'Player % is not on your club roster', v_player_id;
    END IF;

    IF v_potm THEN
      v_potm_count := v_potm_count + 1;
    END IF;

    IF v_started THEN
      v_started_count := v_started_count + 1;
    END IF;
    IF v_subbed THEN
      v_subbed_count := v_subbed_count + 1;
    END IF;

    v_team_goals := v_team_goals + v_goals;

    INSERT INTO public.competition_match_player_stats (
      fixture_id, season_id, club_short_name, player_id,
      appeared, started, subbed_on, goals, assists, rating, is_player_of_match,
      yellow_card, red_card
    )
    VALUES (
      p_fixture_id, p_season_id, p_club, v_player_id,
      v_appeared, v_started, v_subbed, v_goals, v_assists, v_rating, v_potm,
      v_yellow, v_red
    );
  END LOOP;

  IF v_started_count <> 11 THEN
    RAISE EXCEPTION 'Exactly 11 players must be marked as started (currently %)', v_started_count;
  END IF;

  IF v_subbed_count > 5 THEN
    RAISE EXCEPTION 'Maximum 5 players can be subbed on (currently %)', v_subbed_count;
  END IF;

  IF v_potm_count > 1 THEN
    RAISE EXCEPTION 'Only one player of the match allowed';
  END IF;

  IF v_team_goals > 0 AND v_team_goals <> p_expected_goals THEN
    RAISE EXCEPTION 'Player goals (%) must match your team score (%)', v_team_goals, p_expected_goals;
  END IF;

  PERFORM public.competition_process_match_discipline(
    p_fixture_id, p_season_id, p_club, p_player_stats
  );

  PERFORM public.competition_serve_suspensions_for_fixture(p_fixture_id);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public read helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_active_suspensions(
  p_club text DEFAULT NULL,
  p_player_ids text[] DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := nullif(btrim(p_club), '');
BEGIN
  RETURN coalesce((
    SELECT jsonb_agg(row_to_json(x) ORDER BY x.player_id, x.suspension_id)
    FROM (
      SELECT
        s.id AS suspension_id,
        s.player_id,
        s.club_short_name,
        s.season_id,
        s.reason,
        s.yellow_count_at_issue,
        s.ban_matches,
        s.status,
        s.source_fixture_id,
        s.created_at,
        coalesce((
          SELECT jsonb_agg(
            jsonb_build_object(
              'fixture_id', sm.fixture_id,
              'sequence_no', sm.sequence_no,
              'served', sm.served,
              'label', public.competition_fixture_discipline_label(f, s.club_short_name),
              'matchday', f.matchday,
              'competition_type', f.competition_type
            )
            ORDER BY sm.sequence_no
          )
          FROM public.competition_player_suspension_matches sm
          JOIN public.competition_fixtures f ON f.id = sm.fixture_id
          WHERE sm.suspension_id = s.id
            AND sm.served = false
        ), '[]'::jsonb) AS pending_matches,
        (
          SELECT count(*)::int
          FROM public.competition_match_player_stats m
          WHERE m.season_id = s.season_id
            AND m.player_id = s.player_id
            AND m.yellow_card = true
        ) AS season_yellows,
        (
          SELECT count(*)::int
          FROM public.competition_match_player_stats m
          WHERE m.season_id = s.season_id
            AND m.player_id = s.player_id
            AND m.red_card = true
        ) AS season_reds
      FROM public.competition_player_suspensions s
      WHERE s.status = 'active'
        AND (v_club IS NULL OR s.club_short_name = v_club)
        AND (
          p_player_ids IS NULL
          OR cardinality(p_player_ids) = 0
          OR s.player_id = ANY (p_player_ids)
        )
        AND EXISTS (
          SELECT 1 FROM public.competition_player_suspension_matches sm
          WHERE sm.suspension_id = s.id AND sm.served = false
        )
    ) x
  ), '[]'::jsonb);
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_player_cards_season(
  p_player_id text,
  p_season_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_pid text := btrim(p_player_id);
  v_season bigint := p_season_id;
BEGIN
  IF v_season IS NULL THEN
    SELECT s.id INTO v_season
    FROM public.competition_seasons s
    WHERE coalesce(s.is_current, false) = true
       OR s.status = 'active'
    ORDER BY coalesce(s.is_current, false) DESC, s.id DESC
    LIMIT 1;
  END IF;

  RETURN jsonb_build_object(
    'season_id', v_season,
    'yellow_cards', coalesce((
      SELECT count(*)::int FROM public.competition_match_player_stats m
      WHERE m.player_id = v_pid AND m.season_id = v_season AND m.yellow_card
    ), 0),
    'red_cards', coalesce((
      SELECT count(*)::int FROM public.competition_match_player_stats m
      WHERE m.player_id = v_pid AND m.season_id = v_season AND m.red_card
    ), 0)
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Career bundle: add discipline history
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_player_career_bundle(p_player_id text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_pid text := btrim(p_player_id);
  v_player jsonb;
  v_stints jsonb;
  v_honours jsonb;
  v_awards jsonb;
  v_totals jsonb;
  v_transfers jsonb;
  v_discipline jsonb;
BEGIN
  SELECT to_jsonb(p)
  INTO v_player
  FROM (
    SELECT
      p."Konami_ID" AS player_id,
      p."Name" AS player_name,
      p."Position" AS position,
      p."Rating" AS rating,
      p."Nation" AS nation,
      p."Contracted_Team" AS current_club
    FROM public."Players" p
    WHERE p."Konami_ID"::text = v_pid
    LIMIT 1
  ) p;

  SELECT coalesce(jsonb_agg(row_to_json(c) ORDER BY c.season_label DESC), '[]'::jsonb)
  INTO v_stints
  FROM public.competition_player_career_public c
  WHERE c.player_id = v_pid;

  SELECT coalesce(jsonb_agg(row_to_json(h) ORDER BY h.honoured_at DESC), '[]'::jsonb)
  INTO v_honours
  FROM public.competition_player_honours_public h
  WHERE h.player_id = v_pid;

  SELECT coalesce(jsonb_agg(row_to_json(a) ORDER BY a.season_label DESC), '[]'::jsonb)
  INTO v_awards
  FROM public.competition_season_awards_public a
  WHERE a.player_id = v_pid;

  SELECT jsonb_build_object(
    'appearances', coalesce(sum(appearances), 0),
    'goals', coalesce(sum(goals), 0),
    'assists', coalesce(sum(assists), 0),
    'potm_awards', coalesce(sum(potm_awards), 0),
    'clean_sheets', coalesce(sum(clean_sheets), 0),
    'avg_rating', round(avg(avg_rating) FILTER (WHERE avg_rating IS NOT NULL), 2),
    'yellow_cards', coalesce((
      SELECT count(*)::int FROM public.competition_match_player_stats m
      WHERE m.player_id = v_pid AND m.yellow_card
    ), 0),
    'red_cards', coalesce((
      SELECT count(*)::int FROM public.competition_match_player_stats m
      WHERE m.player_id = v_pid AND m.red_card
    ), 0)
  )
  INTO v_totals
  FROM public.competition_player_career_public c
  WHERE c.player_id = v_pid;

  SELECT coalesce(jsonb_agg(row_to_json(t) ORDER BY t.transfer_time DESC), '[]'::jsonb)
  INTO v_transfers
  FROM (
    SELECT
      h.player_id::text AS player_id,
      public.transfer_history_season_label(h.transfer_time) AS season_label,
      h.transfer_time,
      h.seller_club_id AS seller_club_short_name,
      h.buyer_club_id AS buyer_club_short_name,
      h.foreign_buyer_name,
      h.transfer_sale_note,
      coalesce(h.fee, 0)::numeric AS fee,
      coalesce(h.agent_fee, 0)::numeric AS agent_fee,
      (coalesce(h.fee, 0) + coalesce(h.agent_fee, 0))::numeric AS total_cost,
      CASE
        WHEN coalesce(h.fee, 0) <= 0 THEN 'free'
        WHEN h.transfer_sale_note = 'squad_overflow' THEN 'overflow_release'
        WHEN h.foreign_buyer_name IS NOT NULL AND btrim(h.foreign_buyer_name) <> '' THEN 'foreign_sale'
        ELSE 'transfer'
      END AS move_kind
    FROM public."Transfer_History" h
    WHERE h.player_id::text = v_pid
  ) t;

  SELECT coalesce(jsonb_agg(row_to_json(d) ORDER BY d.created_at DESC), '[]'::jsonb)
  INTO v_discipline
  FROM (
    SELECT
      s.id AS suspension_id,
      s.season_id,
      se.label AS season_label,
      s.club_short_name,
      s.reason,
      s.yellow_count_at_issue,
      s.ban_matches,
      s.status,
      s.source_fixture_id,
      s.created_at,
      CASE
        WHEN s.reason = 'red_card' THEN 'Red card — 2 match ban'
        WHEN s.reason = 'yellow_accumulation' THEN
          format('Yellow card accumulation (%s) — 2 match ban', coalesce(s.yellow_count_at_issue, 8))
        ELSE s.reason
      END AS summary,
      coalesce((
        SELECT jsonb_agg(
          jsonb_build_object(
            'fixture_id', sm.fixture_id,
            'sequence_no', sm.sequence_no,
            'served', sm.served,
            'label', public.competition_fixture_discipline_label(f, s.club_short_name)
          )
          ORDER BY sm.sequence_no
        )
        FROM public.competition_player_suspension_matches sm
        JOIN public.competition_fixtures f ON f.id = sm.fixture_id
        WHERE sm.suspension_id = s.id
      ), '[]'::jsonb) AS matches
    FROM public.competition_player_suspensions s
    LEFT JOIN public.competition_seasons se ON se.id = s.season_id
    WHERE s.player_id = v_pid
  ) d;

  RETURN jsonb_build_object(
    'player', coalesce(v_player, '{}'::jsonb),
    'stints', coalesce(v_stints, '[]'::jsonb),
    'honours', coalesce(v_honours, '[]'::jsonb),
    'awards', coalesce(v_awards, '[]'::jsonb),
    'totals', coalesce(v_totals, '{}'::jsonb),
    'transfers', coalesce(v_transfers, '[]'::jsonb),
    'discipline', coalesce(v_discipline, '[]'::jsonb)
  );
END;
$function$;

GRANT SELECT ON TABLE public.competition_player_suspensions TO authenticated;
GRANT SELECT ON TABLE public.competition_player_suspension_matches TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_active_suspensions(text, text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_active_suspensions(text, text[]) TO anon;
GRANT EXECUTE ON FUNCTION public.competition_player_cards_season(text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_player_cards_season(text, bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.competition_player_career_bundle(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_apply_club_player_stats(bigint, bigint, text, jsonb, int) TO authenticated;

NOTIFY pgrst, 'reload schema';
