-- =============================================================================
-- Fixture unavailable players (suspended + injured) — visible to both clubs
--
-- RPC: competition_fixture_unavailable_players(fixture_id)
--   → home/away lists for participating owners (and admins)
--
-- Suspensions: existing competition_player_suspension_matches
-- Injuries: stub tables ready for a later injury UI
--
-- Run after competition_player_discipline.sql. Safe re-run.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.competition_player_injuries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  player_id text NOT NULL,
  club_short_name text NOT NULL,
  label text NOT NULL DEFAULT 'Injured',
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'recovered', 'cancelled')),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  recovered_at timestamptz
);

CREATE INDEX IF NOT EXISTS competition_player_injuries_club_active_idx
  ON public.competition_player_injuries (club_short_name, season_id)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS competition_player_injuries_player_idx
  ON public.competition_player_injuries (player_id, season_id);

-- Fixtures this injury causes the player to miss
CREATE TABLE IF NOT EXISTS public.competition_player_injury_fixtures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  injury_id bigint NOT NULL
    REFERENCES public.competition_player_injuries (id) ON DELETE CASCADE,
  fixture_id bigint NOT NULL REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  served boolean NOT NULL DEFAULT false,
  CONSTRAINT competition_player_injury_fixtures_unique UNIQUE (injury_id, fixture_id)
);

CREATE INDEX IF NOT EXISTS competition_player_injury_fixtures_fixture_idx
  ON public.competition_player_injury_fixtures (fixture_id)
  WHERE served = false;

-- ---------------------------------------------------------------------------
-- Shared unavailable list for one fixture (both participating owners)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_fixture_unavailable_players(
  p_fixture_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures%rowtype;
  v_club text := public.my_club_shortname();
  v_home jsonb;
  v_away jsonb;
BEGIN
  SELECT * INTO v_fixture
  FROM public.competition_fixtures
  WHERE id = p_fixture_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role')
     AND (
       v_club IS NULL
       OR v_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name)
     ) THEN
    RAISE EXCEPTION 'Only participating clubs can view unavailable players for this fixture';
  END IF;

  WITH suspended AS (
    SELECT
      s.club_short_name,
      s.player_id,
      p."Name" AS player_name,
      p."Position" AS position,
      'suspended'::text AS reason,
      CASE
        WHEN s.reason = 'red_card' THEN 'Suspended — red card (2-match ban)'
        WHEN s.reason = 'yellow_accumulation' THEN
          format(
            'Suspended — %s yellows (2-match ban)',
            coalesce(s.yellow_count_at_issue, 8)
          )
        ELSE 'Suspended'
      END AS detail,
      s.id AS source_id
    FROM public.competition_player_suspension_matches sm
    JOIN public.competition_player_suspensions s ON s.id = sm.suspension_id
    LEFT JOIN public."Players" p ON p."Konami_ID"::text = s.player_id
    WHERE sm.fixture_id = p_fixture_id
      AND sm.served = false
      AND s.status = 'active'
  ),
  injured AS (
    SELECT
      i.club_short_name,
      i.player_id,
      p."Name" AS player_name,
      p."Position" AS position,
      'injured'::text AS reason,
      format('Injured — %s', coalesce(nullif(btrim(i.label), ''), 'Injured')) AS detail,
      i.id AS source_id
    FROM public.competition_player_injury_fixtures iff
    JOIN public.competition_player_injuries i ON i.id = iff.injury_id
    LEFT JOIN public."Players" p ON p."Konami_ID"::text = i.player_id
    WHERE iff.fixture_id = p_fixture_id
      AND iff.served = false
      AND i.status = 'active'
  ),
  combined AS (
    SELECT * FROM suspended
    UNION ALL
    SELECT * FROM injured
  )
  SELECT
    coalesce((
      SELECT jsonb_agg(
        jsonb_build_object(
          'player_id', c.player_id,
          'player_name', coalesce(c.player_name, c.player_id),
          'position', c.position,
          'reason', c.reason,
          'detail', c.detail,
          'source_id', c.source_id
        )
        ORDER BY c.reason, c.player_name
      )
      FROM combined c
      WHERE c.club_short_name = v_fixture.home_club_short_name
    ), '[]'::jsonb),
    coalesce((
      SELECT jsonb_agg(
        jsonb_build_object(
          'player_id', c.player_id,
          'player_name', coalesce(c.player_name, c.player_id),
          'position', c.position,
          'reason', c.reason,
          'detail', c.detail,
          'source_id', c.source_id
        )
        ORDER BY c.reason, c.player_name
      )
      FROM combined c
      WHERE c.club_short_name = v_fixture.away_club_short_name
    ), '[]'::jsonb)
  INTO v_home, v_away;

  RETURN jsonb_build_object(
    'fixture_id', p_fixture_id,
    'home_club_short_name', v_fixture.home_club_short_name,
    'away_club_short_name', v_fixture.away_club_short_name,
    'home', coalesce(v_home, '[]'::jsonb),
    'away', coalesce(v_away, '[]'::jsonb)
  );
END;
$function$;

-- Mark injury absences served when a fixture is played (alongside suspensions)
CREATE OR REPLACE FUNCTION public.competition_serve_injuries_for_fixture(
  p_fixture_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  UPDATE public.competition_player_injury_fixtures iff
  SET served = true
  WHERE iff.fixture_id = p_fixture_id
    AND iff.served = false;

  UPDATE public.competition_player_injuries i
  SET status = 'recovered',
      recovered_at = coalesce(i.recovered_at, now())
  WHERE i.status = 'active'
    AND EXISTS (
      SELECT 1 FROM public.competition_player_injury_fixtures iff
      WHERE iff.injury_id = i.id
    )
    AND NOT EXISTS (
      SELECT 1 FROM public.competition_player_injury_fixtures iff
      WHERE iff.injury_id = i.id
        AND iff.served = false
    );
END;
$function$;

-- Block injured players from appearing (extend discipline check)
CREATE OR REPLACE FUNCTION public.competition_player_unavailable_for_fixture(
  p_fixture_id bigint,
  p_player_id text
)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
  SELECT detail
  FROM (
    SELECT
      CASE
        WHEN s.reason = 'red_card' THEN 'Suspended — red card'
        WHEN s.reason = 'yellow_accumulation' THEN 'Suspended — yellow accumulation'
        ELSE 'Suspended'
      END AS detail,
      1 AS ord
    FROM public.competition_player_suspension_matches sm
    JOIN public.competition_player_suspensions s ON s.id = sm.suspension_id
    WHERE sm.fixture_id = p_fixture_id
      AND sm.served = false
      AND s.status = 'active'
      AND s.player_id = p_player_id

    UNION ALL

    SELECT
      format('Injured — %s', coalesce(nullif(btrim(i.label), ''), 'Injured')) AS detail,
      2 AS ord
    FROM public.competition_player_injury_fixtures iff
    JOIN public.competition_player_injuries i ON i.id = iff.injury_id
    WHERE iff.fixture_id = p_fixture_id
      AND iff.served = false
      AND i.status = 'active'
      AND i.player_id = p_player_id
  ) x
  ORDER BY ord
  LIMIT 1;
$function$;

-- Patch process_match_discipline to also block injured (redefine check loop via helper)
-- Soft patch: update serve call inside apply to also serve injuries.

CREATE OR REPLACE FUNCTION public.competition_serve_suspensions_for_fixture(
  p_fixture_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  UPDATE public.competition_player_suspension_matches sm
  SET served = true
  WHERE sm.fixture_id = p_fixture_id
    AND sm.served = false;

  UPDATE public.competition_player_suspensions s
  SET status = 'completed'
  WHERE s.status = 'active'
    AND EXISTS (
      SELECT 1 FROM public.competition_player_suspension_matches sm
      WHERE sm.suspension_id = s.id
    )
    AND NOT EXISTS (
      SELECT 1 FROM public.competition_player_suspension_matches sm
      WHERE sm.suspension_id = s.id
        AND sm.served = false
    );

  PERFORM public.competition_serve_injuries_for_fixture(p_fixture_id);
END;
$function$;

-- Tighten appearance block in process_match_discipline
CREATE OR REPLACE FUNCTION public.competition_process_match_discipline(
  p_fixture_id bigint,
  p_season_id bigint,
  p_club text,
  p_player_stats jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_item jsonb;
  v_player_id text;
  v_appeared boolean;
  v_started boolean;
  v_subbed boolean;
  v_yellow boolean;
  v_red boolean;
  v_y_count int;
  v_prev_count int;
  v_threshold int;
  v_block text;
BEGIN
  FOR v_item IN SELECT value FROM jsonb_array_elements(coalesce(p_player_stats, '[]'::jsonb))
  LOOP
    v_player_id := trim(both '"' FROM (v_item ->> 'player_id'));
    IF v_player_id IS NULL OR v_player_id = '' THEN
      CONTINUE;
    END IF;

    v_started := coalesce((v_item ->> 'started')::boolean, false);
    v_subbed := coalesce((v_item ->> 'subbed_on')::boolean, false);
    IF v_item ? 'started' OR v_item ? 'subbed_on' THEN
      v_appeared := v_started OR v_subbed;
    ELSE
      v_appeared := coalesce((v_item ->> 'appeared')::boolean, false);
    END IF;

    v_yellow := coalesce((v_item ->> 'yellow_card')::boolean, false)
      OR coalesce((v_item ->> 'yellow')::boolean, false);
    v_red := coalesce((v_item ->> 'red_card')::boolean, false)
      OR coalesce((v_item ->> 'red')::boolean, false);

    IF (v_yellow OR v_red) AND NOT v_appeared THEN
      RAISE EXCEPTION 'Player % must have appeared to receive a card', v_player_id;
    END IF;

    IF v_appeared THEN
      v_block := public.competition_player_unavailable_for_fixture(p_fixture_id, v_player_id);
      IF v_block IS NOT NULL THEN
        RAISE EXCEPTION 'Player % is unavailable for this match (%)', v_player_id, v_block;
      END IF;
    END IF;
  END LOOP;

  FOR v_item IN SELECT value FROM jsonb_array_elements(coalesce(p_player_stats, '[]'::jsonb))
  LOOP
    v_player_id := trim(both '"' FROM (v_item ->> 'player_id'));
    IF v_player_id IS NULL OR v_player_id = '' THEN
      CONTINUE;
    END IF;

    v_yellow := coalesce((v_item ->> 'yellow_card')::boolean, false)
      OR coalesce((v_item ->> 'yellow')::boolean, false);
    v_red := coalesce((v_item ->> 'red_card')::boolean, false)
      OR coalesce((v_item ->> 'red')::boolean, false);

    UPDATE public.competition_match_player_stats
    SET yellow_card = v_yellow,
        red_card = v_red
    WHERE fixture_id = p_fixture_id
      AND club_short_name = p_club
      AND player_id = v_player_id;
  END LOOP;

  FOR v_item IN SELECT value FROM jsonb_array_elements(coalesce(p_player_stats, '[]'::jsonb))
  LOOP
    v_player_id := trim(both '"' FROM (v_item ->> 'player_id'));
    IF v_player_id IS NULL OR v_player_id = '' THEN
      CONTINUE;
    END IF;

    v_yellow := coalesce((v_item ->> 'yellow_card')::boolean, false)
      OR coalesce((v_item ->> 'yellow')::boolean, false);
    v_red := coalesce((v_item ->> 'red_card')::boolean, false)
      OR coalesce((v_item ->> 'red')::boolean, false);

    IF v_red THEN
      PERFORM public.competition_issue_player_suspension(
        p_season_id, v_player_id, p_club, 'red_card', p_fixture_id, NULL, 2
      );
    END IF;

    IF v_yellow THEN
      SELECT count(*)::int
      INTO v_y_count
      FROM public.competition_match_player_stats m
      WHERE m.season_id = p_season_id
        AND m.player_id = v_player_id
        AND m.yellow_card = true;

      v_prev_count := greatest(v_y_count - 1, 0);
      IF (v_y_count / 8) > (v_prev_count / 8) THEN
        v_threshold := (v_y_count / 8) * 8;
        PERFORM public.competition_issue_player_suspension(
          p_season_id, v_player_id, p_club, 'yellow_accumulation',
          p_fixture_id, v_threshold, 2
        );
      END IF;
    END IF;
  END LOOP;
END;
$function$;

GRANT SELECT ON TABLE public.competition_player_injuries TO authenticated;
GRANT SELECT ON TABLE public.competition_player_injury_fixtures TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_fixture_unavailable_players(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_player_unavailable_for_fixture(bigint, text) TO authenticated;

NOTIFY pgrst, 'reload schema';
