-- =============================================================================
-- Team of the Month / Team of the Season, monthly stats, Ballon (SL only),
-- Championship Player of the Season. No club financial rewards.
-- Run after: competition_history.sql, club_finance_season_archive.sql,
--            squad_minimum_august_auto_tick.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extend season awards
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_season_award
  ADD COLUMN IF NOT EXISTS gpsl_month text;

ALTER TABLE public.competition_season_award
  DROP CONSTRAINT IF EXISTS competition_season_award_award_type_check;

ALTER TABLE public.competition_season_award
  ADD CONSTRAINT competition_season_award_award_type_check CHECK (
    award_type IN (
      'ballon_dor',
      'golden_boot',
      'golden_playmaker',
      'golden_glove',
      'season_potm',
      'team_of_month',
      'team_of_season',
      'championship_player_of_season'
    )
  );

ALTER TABLE public.competition_season_award
  DROP CONSTRAINT IF EXISTS competition_season_award_unique;

CREATE UNIQUE INDEX IF NOT EXISTS competition_season_award_singleton_idx
  ON public.competition_season_award (season_id, award_type)
  WHERE award_type IN (
    'ballon_dor',
    'golden_boot',
    'golden_playmaker',
    'golden_glove',
    'season_potm',
    'championship_player_of_season'
  );

CREATE UNIQUE INDEX IF NOT EXISTS competition_season_award_team_month_player_idx
  ON public.competition_season_award (season_id, gpsl_month, award_type, player_id)
  WHERE award_type = 'team_of_month';

CREATE UNIQUE INDEX IF NOT EXISTS competition_season_award_team_season_player_idx
  ON public.competition_season_award (season_id, award_type, player_id)
  WHERE award_type = 'team_of_season';

-- ---------------------------------------------------------------------------
-- Stored XI (display / history)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_period_team (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  season_label text NOT NULL,
  gpsl_month text,
  period_kind text NOT NULL CHECK (period_kind IN ('month', 'season')),
  division_scope text NOT NULL CHECK (division_scope IN ('superleague', 'championship')),
  formation_id text NOT NULL,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  computed_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_period_team_unique
    UNIQUE (season_id, period_kind, division_scope, gpsl_month)
);

CREATE TABLE IF NOT EXISTS public.competition_period_team_member (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id bigint NOT NULL REFERENCES public.competition_period_team (id) ON DELETE CASCADE,
  pitch_slot text NOT NULL,
  slot_label text NOT NULL,
  player_id text NOT NULL,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  selection_score numeric(12, 2) NOT NULL DEFAULT 0,
  appearances int NOT NULL DEFAULT 0,
  goals int NOT NULL DEFAULT 0,
  assists int NOT NULL DEFAULT 0,
  avg_rating numeric(4, 2),
  clean_sheets int NOT NULL DEFAULT 0,
  CONSTRAINT competition_period_team_member_unique UNIQUE (team_id, pitch_slot)
);

CREATE INDEX IF NOT EXISTS competition_period_team_season_idx
  ON public.competition_period_team (season_id, period_kind, gpsl_month);

ALTER TABLE public.competition_period_team ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_period_team_member ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_period_team_select ON public.competition_period_team;
CREATE POLICY competition_period_team_select ON public.competition_period_team
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_period_team_member_select ON public.competition_period_team_member;
CREATE POLICY competition_period_team_member_select ON public.competition_period_team_member
  FOR SELECT TO authenticated USING (true);

GRANT SELECT ON public.competition_period_team TO authenticated, anon;
GRANT SELECT ON public.competition_period_team_member TO authenticated, anon;
GRANT SELECT ON public.competition_period_team_member TO authenticated, anon;

-- ---------------------------------------------------------------------------
-- Position / scoring helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_position_fits_slot_label(
  p_position text,
  p_slot_label text
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE upper(btrim(coalesce(p_slot_label, '')))
    WHEN 'GK' THEN upper(btrim(coalesce(p_position, ''))) = 'GK'
    WHEN 'LB' THEN upper(btrim(p_position)) IN ('LB', 'LWB')
    WHEN 'RB' THEN upper(btrim(p_position)) IN ('RB', 'RWB')
    WHEN 'CB' THEN upper(btrim(p_position)) = 'CB'
    WHEN 'DMF' THEN upper(btrim(p_position)) IN ('DMF', 'CMF')
    WHEN 'LMF' THEN upper(btrim(p_position)) IN ('LMF', 'LW', 'WG')
    WHEN 'RMF' THEN upper(btrim(p_position)) IN ('RMF', 'RW', 'WG')
    WHEN 'CMF' THEN upper(btrim(p_position)) IN ('CMF', 'DMF', 'AMF')
    WHEN 'AMF' THEN upper(btrim(p_position)) IN ('AMF', 'SS', 'CMF')
    WHEN 'LWF' THEN upper(btrim(p_position)) IN ('LWF', 'LW', 'SS', 'CF')
    WHEN 'RWF' THEN upper(btrim(p_position)) IN ('RWF', 'RW', 'SS', 'CF')
    WHEN 'CF' THEN upper(btrim(p_position)) IN ('CF', 'SS')
    ELSE false
  END;
$$;

CREATE OR REPLACE FUNCTION public.competition_player_clean_sheets_month(
  p_season_id bigint,
  p_gpsl_month text,
  p_player_id text,
  p_club_short_name text DEFAULT NULL
)
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT count(*)::int
  FROM public.competition_match_player_stats m
  JOIN public.competition_fixtures f ON f.id = m.fixture_id
  JOIN public."Players" p ON p."Konami_ID"::text = m.player_id
  WHERE m.season_id = p_season_id
    AND f.gpsl_month = p_gpsl_month
    AND f.competition_type = 'league'
    AND m.player_id = btrim(p_player_id)
    AND m.started = true
    AND f.status = 'played'
    AND (
      p_club_short_name IS NULL
      OR m.club_short_name = btrim(p_club_short_name)
    )
    AND public.competition_player_stat_role(p."Position") IN ('goalkeeper', 'defender')
    AND public.competition_player_conceded_in_fixture(f.id, m.club_short_name) = 0;
$$;

CREATE OR REPLACE FUNCTION public.competition_player_selection_score(
  p_stat_role text,
  p_position text,
  p_appearances int,
  p_goals int,
  p_assists int,
  p_avg_rating numeric,
  p_clean_sheets int
)
RETURNS numeric
LANGUAGE plpgsql
IMMUTABLE
AS $function$
DECLARE
  v_pos text := upper(btrim(coalesce(p_position, '')));
  v_role text := coalesce(p_stat_role, 'outfield');
  v_rating numeric := coalesce(p_avg_rating, 0);
  v_apps int := greatest(coalesce(p_appearances, 0), 0);
BEGIN
  IF v_apps < 1 THEN
    RETURN 0;
  END IF;

  IF v_role = 'goalkeeper' THEN
    RETURN round(v_rating * 10 + greatest(coalesce(p_clean_sheets, 0), 0) * 15 + v_apps * 0.5, 2);
  ELSIF v_role = 'defender' AND v_pos IN ('LB', 'RB', 'LWB', 'RWB') THEN
    RETURN round(
      v_rating * 10
      + greatest(coalesce(p_assists, 0), 0) * 8
      + greatest(coalesce(p_goals, 0), 0) * 4
      + v_apps * 0.3,
      2
    );
  ELSIF v_role = 'defender' THEN
    RETURN round(
      v_rating * 10
      + greatest(coalesce(p_clean_sheets, 0), 0) * 12
      + greatest(coalesce(p_assists, 0), 0) * 3
      + v_apps * 0.3,
      2
    );
  ELSIF v_role IN ('midfielder', 'forward') THEN
    RETURN round(
      v_rating * 10
      + greatest(coalesce(p_goals, 0), 0) * 8
      + greatest(coalesce(p_assists, 0), 0) * 6
      + v_apps * 0.2,
      2
    );
  END IF;

  RETURN round(
    v_rating * 10
    + greatest(coalesce(p_goals, 0), 0) * 7
    + greatest(coalesce(p_assists, 0), 0) * 5
    + v_apps * 0.2,
    2
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Monthly stats (league)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_player_month_stats_public
WITH (security_invoker = false)
AS
SELECT
  m.season_id,
  s.label AS season_label,
  f.gpsl_month,
  m.player_id,
  p."Name" AS player_name,
  m.club_short_name,
  c."Club" AS club_name,
  ccs.division,
  p."Position" AS player_position,
  public.competition_player_stat_role(p."Position") AS stat_role,
  count(*) FILTER (WHERE m.appeared)::int AS appearances,
  count(*) FILTER (WHERE m.started)::int AS starts,
  coalesce(sum(m.goals), 0)::int AS goals,
  coalesce(sum(m.assists), 0)::int AS assists,
  round(avg(m.rating) FILTER (WHERE m.rating IS NOT NULL), 2) AS avg_rating,
  count(*) FILTER (WHERE m.is_player_of_match)::int AS potm_awards,
  public.competition_player_clean_sheets_month(
    m.season_id,
    f.gpsl_month,
    m.player_id,
    m.club_short_name
  ) AS clean_sheets,
  public.competition_player_selection_score(
    public.competition_player_stat_role(p."Position"),
    p."Position",
    count(*) FILTER (WHERE m.appeared)::int,
    coalesce(sum(m.goals), 0)::int,
    coalesce(sum(m.assists), 0)::int,
    round(avg(m.rating) FILTER (WHERE m.rating IS NOT NULL), 2),
    public.competition_player_clean_sheets_month(
      m.season_id,
      f.gpsl_month,
      m.player_id,
      m.club_short_name
    )
  ) AS selection_score
FROM public.competition_match_player_stats m
JOIN public.competition_fixtures f ON f.id = m.fixture_id
JOIN public.competition_seasons s ON s.id = m.season_id
JOIN public."Players" p ON p."Konami_ID"::text = m.player_id
JOIN public."Clubs" c ON c."ShortName" = m.club_short_name
LEFT JOIN public.competition_club_seasons ccs
  ON ccs.season_id = m.season_id AND ccs.club_short_name = m.club_short_name
WHERE f.status = 'played'
  AND f.competition_type = 'league'
  AND f.gpsl_month IS NOT NULL
GROUP BY
  m.season_id, s.label, f.gpsl_month, m.player_id, p."Name",
  m.club_short_name, c."Club", ccs.division, p."Position";

GRANT SELECT ON public.competition_player_month_stats_public TO authenticated, anon;

-- ---------------------------------------------------------------------------
-- Formation templates (slot id + role label)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_formation_slot_defs(p_formation_id text)
RETURNS TABLE (pitch_slot text, slot_label text, sort_order int)
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT v.pitch_slot, v.slot_label, v.sort_order
  FROM (
    VALUES
      ('4-4-2', 'GK', 'GK', 1),
      ('4-4-2', 'LB', 'LB', 2),
      ('4-4-2', 'CB1', 'CB', 3),
      ('4-4-2', 'CB2', 'CB', 4),
      ('4-4-2', 'RB', 'RB', 5),
      ('4-4-2', 'LMF', 'LMF', 6),
      ('4-4-2', 'CMF', 'CMF', 7),
      ('4-4-2', 'RMF', 'RMF', 8),
      ('4-4-2', 'RWF', 'RMF', 9),
      ('4-4-2', 'LWF', 'CF', 10),
      ('4-4-2', 'CF', 'CF', 11),
      ('4-3-3', 'GK', 'GK', 1),
      ('4-3-3', 'LB', 'LB', 2),
      ('4-3-3', 'CB1', 'CB', 3),
      ('4-3-3', 'CB2', 'CB', 4),
      ('4-3-3', 'RB', 'RB', 5),
      ('4-3-3', 'LMF', 'CMF', 6),
      ('4-3-3', 'CMF', 'CMF', 7),
      ('4-3-3', 'RMF', 'CMF', 8),
      ('4-3-3', 'LWF', 'LWF', 9),
      ('4-3-3', 'CF', 'CF', 10),
      ('4-3-3', 'RWF', 'RWF', 11),
      ('4-2-3-1', 'GK', 'GK', 1),
      ('4-2-3-1', 'LB', 'LB', 2),
      ('4-2-3-1', 'CB1', 'CB', 3),
      ('4-2-3-1', 'CB2', 'CB', 4),
      ('4-2-3-1', 'RB', 'RB', 5),
      ('4-2-3-1', 'LMF', 'DMF', 6),
      ('4-2-3-1', 'RMF', 'DMF', 7),
      ('4-2-3-1', 'CMF', 'AMF', 8),
      ('4-2-3-1', 'LWF', 'LWF', 9),
      ('4-2-3-1', 'RWF', 'RWF', 10),
      ('4-2-3-1', 'CF', 'CF', 11)
  ) AS v(formation_id, pitch_slot, slot_label, sort_order)
  WHERE v.formation_id = p_formation_id
  ORDER BY v.sort_order;
$$;

-- Pick best XI from candidate stats (month or season rows in a temp-like query)
CREATE OR REPLACE FUNCTION public.competition_pick_period_team(
  p_candidates jsonb,
  p_formation_ids text[] DEFAULT ARRAY['4-4-2', '4-3-3', '4-2-3-1']
)
RETURNS jsonb
LANGUAGE plpgsql
IMMUTABLE
AS $function$
DECLARE
  v_form text;
  v_slot record;
  v_pick record;
  v_used text[] := ARRAY[]::text[];
  v_lineup jsonb := '[]'::jsonb;
  v_all_filled boolean;
BEGIN
  IF p_candidates IS NULL OR jsonb_array_length(p_candidates) = 0 THEN
    RETURN NULL;
  END IF;

  FOREACH v_form IN ARRAY p_formation_ids LOOP
    v_used := ARRAY[]::text[];
    v_lineup := '[]'::jsonb;
    v_all_filled := true;

    FOR v_slot IN
      SELECT * FROM public.competition_formation_slot_defs(v_form)
      ORDER BY sort_order
    LOOP
      SELECT c.*
      INTO v_pick
      FROM jsonb_to_recordset(p_candidates) AS c(
        player_id text,
        club_short_name text,
        player_position text,
        stat_role text,
        appearances int,
        goals int,
        assists int,
        avg_rating numeric,
        clean_sheets int,
        selection_score numeric
      )
      WHERE c.appearances >= 2
        AND c.selection_score > 0
        AND public.competition_position_fits_slot_label(c.player_position, v_slot.slot_label)
        AND NOT (c.player_id = ANY (v_used))
      ORDER BY c.selection_score DESC, c.goals DESC, c.assists DESC, c.avg_rating DESC NULLS LAST
      LIMIT 1;

      IF NOT FOUND THEN
        v_all_filled := false;
        EXIT;
      END IF;

      v_used := array_append(v_used, v_pick.player_id);
      v_lineup := v_lineup || jsonb_build_array(
        jsonb_build_object(
          'pitch_slot', v_slot.pitch_slot,
          'slot_label', v_slot.slot_label,
          'player_id', v_pick.player_id,
          'club_short_name', v_pick.club_short_name,
          'player_position', v_pick.player_position,
          'appearances', v_pick.appearances,
          'goals', v_pick.goals,
          'assists', v_pick.assists,
          'avg_rating', v_pick.avg_rating,
          'clean_sheets', v_pick.clean_sheets,
          'selection_score', v_pick.selection_score
        )
      );
    END LOOP;

    IF v_all_filled AND jsonb_array_length(v_lineup) = 11 THEN
      RETURN jsonb_build_object('formation_id', v_form, 'lineup', v_lineup);
    END IF;
  END LOOP;

  RETURN NULL;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Compute & persist team of month / season
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_store_period_team(
  p_season_id bigint,
  p_season_label text,
  p_gpsl_month text,
  p_period_kind text,
  p_division_scope text,
  p_team jsonb
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_team_id bigint;
  v_member jsonb;
  v_award_type text;
BEGIN
  IF p_team IS NULL OR NOT (p_team ? 'lineup') THEN
    RETURN NULL;
  END IF;

  v_award_type := CASE p_period_kind
    WHEN 'month' THEN 'team_of_month'
    WHEN 'season' THEN 'team_of_season'
    ELSE NULL
  END;

  DELETE FROM public.competition_period_team_member m
  USING public.competition_period_team t
  WHERE m.team_id = t.id
    AND t.season_id = p_season_id
    AND t.period_kind = p_period_kind
    AND t.division_scope = p_division_scope
    AND coalesce(t.gpsl_month, '') = coalesce(p_gpsl_month, '');

  DELETE FROM public.competition_period_team
  WHERE season_id = p_season_id
    AND period_kind = p_period_kind
    AND division_scope = p_division_scope
    AND coalesce(gpsl_month, '') = coalesce(p_gpsl_month, '');

  IF p_period_kind = 'month' THEN
    DELETE FROM public.competition_season_award
    WHERE season_id = p_season_id
      AND award_type = 'team_of_month'
      AND gpsl_month = p_gpsl_month;
  ELSIF p_period_kind = 'season' THEN
    DELETE FROM public.competition_season_award
    WHERE season_id = p_season_id
      AND award_type = 'team_of_season';
  END IF;

  INSERT INTO public.competition_period_team (
    season_id, season_label, gpsl_month, period_kind, division_scope, formation_id, detail
  )
  VALUES (
    p_season_id,
    p_season_label,
    p_gpsl_month,
    p_period_kind,
    p_division_scope,
    p_team ->> 'formation_id',
    jsonb_build_object('formation_id', p_team ->> 'formation_id')
  )
  RETURNING id INTO v_team_id;

  FOR v_member IN
    SELECT value FROM jsonb_array_elements(p_team -> 'lineup')
  LOOP
    INSERT INTO public.competition_period_team_member (
      team_id, pitch_slot, slot_label, player_id, club_short_name,
      selection_score, appearances, goals, assists, avg_rating, clean_sheets
    )
    VALUES (
      v_team_id,
      v_member ->> 'pitch_slot',
      v_member ->> 'slot_label',
      v_member ->> 'player_id',
      v_member ->> 'club_short_name',
      coalesce((v_member ->> 'selection_score')::numeric, 0),
      coalesce((v_member ->> 'appearances')::int, 0),
      coalesce((v_member ->> 'goals')::int, 0),
      coalesce((v_member ->> 'assists')::int, 0),
      nullif(v_member ->> 'avg_rating', '')::numeric,
      coalesce((v_member ->> 'clean_sheets')::int, 0)
    );

    IF v_award_type IS NOT NULL THEN
      INSERT INTO public.competition_season_award (
        season_id, season_label, award_type, player_id, club_short_name,
        stat_value, gpsl_month, detail
      )
      VALUES (
        p_season_id,
        p_season_label,
        v_award_type,
        v_member ->> 'player_id',
        v_member ->> 'club_short_name',
        coalesce((v_member ->> 'selection_score')::numeric, 0),
        p_gpsl_month,
        jsonb_build_object(
          'formation_id', p_team ->> 'formation_id',
          'pitch_slot', v_member ->> 'pitch_slot',
          'slot_label', v_member ->> 'slot_label',
          'gpsl_month', p_gpsl_month
        )
      )
      ON CONFLICT DO NOTHING;
    END IF;
  END LOOP;

  RETURN v_team_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_compute_team_of_month(
  p_season_id bigint,
  p_gpsl_month text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_label text;
  v_candidates jsonb;
  v_team jsonb;
  v_team_id bigint;
BEGIN
  SELECT label INTO v_label FROM public.competition_seasons WHERE id = p_season_id;

  SELECT coalesce(jsonb_agg(to_jsonb(s)), '[]'::jsonb)
  INTO v_candidates
  FROM public.competition_player_month_stats_public s
  WHERE s.season_id = p_season_id
    AND s.gpsl_month = p_gpsl_month
    AND s.division = 'superleague'
    AND s.appearances >= 2;

  v_team := public.competition_pick_period_team(v_candidates);
  IF v_team IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_valid_xi', 'gpsl_month', p_gpsl_month);
  END IF;

  v_team_id := public.competition_store_period_team(
    p_season_id, v_label, p_gpsl_month, 'month', 'superleague', v_team
  );

  RETURN jsonb_build_object(
    'ok', true,
    'gpsl_month', p_gpsl_month,
    'team_id', v_team_id,
    'formation_id', v_team ->> 'formation_id'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_compute_team_of_season(p_season_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_label text;
  v_candidates jsonb;
  v_team jsonb;
  v_team_id bigint;
BEGIN
  SELECT label INTO v_label FROM public.competition_seasons WHERE id = p_season_id;

  SELECT coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
  INTO v_candidates
  FROM (
    SELECT
      a.player_id,
      a.club_short_name,
      a.player_position,
      a.stat_role,
      a.appearances,
      a.goals,
      a.assists,
      a.avg_rating,
      a.clean_sheets,
      public.competition_player_selection_score(
        a.stat_role,
        a.player_position,
        a.appearances,
        a.goals,
        a.assists,
        a.avg_rating,
        a.clean_sheets
      ) AS selection_score
    FROM public.competition_player_season_archive a
    WHERE a.season_id = p_season_id
      AND a.division = 'superleague'
      AND a.appearances >= 5
  ) x;

  v_team := public.competition_pick_period_team(v_candidates);
  IF v_team IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_valid_xi');
  END IF;

  v_team_id := public.competition_store_period_team(
    p_season_id, v_label, NULL, 'season', 'superleague', v_team
  );

  RETURN jsonb_build_object(
    'ok', true,
    'team_id', v_team_id,
    'formation_id', v_team ->> 'formation_id'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_compute_championship_player_of_season(p_season_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_label text;
  v_winner record;
BEGIN
  SELECT label INTO v_label FROM public.competition_seasons WHERE id = p_season_id;

  DELETE FROM public.competition_season_award
  WHERE season_id = p_season_id
    AND award_type = 'championship_player_of_season';

  SELECT
    a.player_id,
    a.club_short_name,
    a.division,
    public.competition_player_selection_score(
      a.stat_role,
      a.player_position,
      a.appearances,
      a.goals,
      a.assists,
      a.avg_rating,
      a.clean_sheets
    ) AS selection_score,
    a.goals,
    a.assists,
    a.avg_rating,
    a.appearances
  INTO v_winner
  FROM public.competition_player_season_archive a
  WHERE a.season_id = p_season_id
    AND a.division IN ('championship_a', 'championship_b')
    AND a.appearances >= 5
  ORDER BY
    public.competition_player_selection_score(
      a.stat_role, a.player_position, a.appearances, a.goals, a.assists, a.avg_rating, a.clean_sheets
    ) DESC,
    a.goals DESC,
    a.assists DESC
  LIMIT 1;

  IF NOT FOUND OR coalesce(v_winner.selection_score, 0) <= 0 THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_eligible_player');
  END IF;

  INSERT INTO public.competition_season_award (
    season_id, season_label, award_type, player_id, club_short_name, stat_value, detail
  )
  VALUES (
    p_season_id,
    v_label,
    'championship_player_of_season',
    v_winner.player_id,
    v_winner.club_short_name,
    v_winner.selection_score,
    jsonb_build_object(
      'division', v_winner.division,
      'goals', v_winner.goals,
      'assists', v_winner.assists,
      'avg_rating', v_winner.avg_rating,
      'appearances', v_winner.appearances
    )
  );

  RETURN jsonb_build_object(
    'ok', true,
    'player_id', v_winner.player_id,
    'club_short_name', v_winner.club_short_name,
    'division', v_winner.division
  );
END;
$function$;

-- Process all locked months without a TOTM job
CREATE OR REPLACE FUNCTION public.competition_process_month_team_awards(p_season_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cal record;
  v_results jsonb := '[]'::jsonb;
  v_res jsonb;
BEGIN
  FOR v_cal IN
    SELECT c.gpsl_month
    FROM public.competition_season_calendar c
    WHERE c.season_id = p_season_id
      AND c.gpsl_month IS NOT NULL
      AND c.lock_at IS NOT NULL
      AND c.lock_at <= now()
      AND NOT EXISTS (
        SELECT 1
        FROM public.competition_season_calendar_jobs j
        WHERE j.season_id = p_season_id
          AND j.job_key = 'team_of_month:' || c.gpsl_month
      )
    ORDER BY public.competition_gpsl_month_sort(c.gpsl_month)
  LOOP
    v_res := public.competition_compute_team_of_month(p_season_id, v_cal.gpsl_month);

    INSERT INTO public.competition_season_calendar_jobs (
      season_id, job_key, gpsl_month, result
    )
    VALUES (
      p_season_id,
      'team_of_month:' || v_cal.gpsl_month,
      v_cal.gpsl_month,
      coalesce(v_res, '{}'::jsonb)
    )
    ON CONFLICT (season_id, job_key) DO UPDATE
      SET result = excluded.result,
          gpsl_month = excluded.gpsl_month,
          ran_at = now();

    v_results := v_results || jsonb_build_array(
      jsonb_build_object('gpsl_month', v_cal.gpsl_month, 'result', v_res)
    );
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'processed', v_results);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public views
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_season_awards_public
WITH (security_invoker = false)
AS
SELECT
  a.season_id,
  a.season_label,
  a.award_type,
  a.gpsl_month,
  a.player_id,
  p."Name" AS player_name,
  a.club_short_name,
  c."Club" AS club_name,
  a.stat_value,
  a.detail,
  a.awarded_at
FROM public.competition_season_award a
JOIN public."Players" p ON p."Konami_ID"::text = a.player_id
JOIN public."Clubs" c ON c."ShortName" = a.club_short_name;

CREATE OR REPLACE VIEW public.competition_period_team_public
WITH (security_invoker = false)
AS
SELECT
  t.id AS team_id,
  t.season_id,
  t.season_label,
  t.gpsl_month,
  t.period_kind,
  t.division_scope,
  t.formation_id,
  t.computed_at,
  m.pitch_slot,
  m.slot_label,
  m.player_id,
  p."Name" AS player_name,
  m.club_short_name,
  c."Club" AS club_name,
  p."Position" AS player_position,
  m.selection_score,
  m.appearances,
  m.goals,
  m.assists,
  m.avg_rating,
  m.clean_sheets
FROM public.competition_period_team t
JOIN public.competition_period_team_member m ON m.team_id = t.id
JOIN public."Players" p ON p."Konami_ID"::text = m.player_id
JOIN public."Clubs" c ON c."ShortName" = m.club_short_name;

GRANT SELECT ON public.competition_period_team_public TO authenticated, anon;

-- ---------------------------------------------------------------------------
-- Season archive awards tail (call from competition_admin_archive_season)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_finalize_season_player_awards(
  p_season_id bigint,
  p_season_label text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_ballon record;
  v_boot record;
  v_play record;
  v_potm record;
  v_glove record;
  v_ballon_id text := null;
  v_tots jsonb;
  v_champ jsonb;
BEGIN
  DELETE FROM public.competition_season_award
  WHERE season_id = p_season_id
    AND award_type IN (
      'ballon_dor',
      'golden_boot',
      'golden_playmaker',
      'golden_glove',
      'season_potm',
      'championship_player_of_season',
      'team_of_season'
    );

  SELECT a.*
  INTO v_ballon
  FROM public.competition_player_season_archive a
  WHERE a.season_id = p_season_id
    AND a.division = 'superleague'
    AND a.appearances >= 5
  ORDER BY a.ballon_points DESC, a.goals DESC, a.assists DESC
  LIMIT 1;

  IF FOUND AND v_ballon.ballon_points > 0 THEN
    INSERT INTO public.competition_season_award (
      season_id, season_label, award_type, player_id, club_short_name,
      stat_value, detail
    )
    VALUES (
      p_season_id, p_season_label, 'ballon_dor',
      v_ballon.player_id, v_ballon.club_short_name,
      v_ballon.ballon_points,
      jsonb_build_object(
        'goals', v_ballon.goals,
        'assists', v_ballon.assists,
        'potm', v_ballon.potm_awards,
        'clean_sheets', v_ballon.clean_sheets,
        'avg_rating', v_ballon.avg_rating,
        'stat_role', v_ballon.stat_role,
        'division', v_ballon.division
      )
    );
    v_ballon_id := v_ballon.player_id;
  END IF;

  SELECT a.* INTO v_boot
  FROM public.competition_player_season_archive a
  WHERE a.season_id = p_season_id AND a.goals > 0
  ORDER BY a.goals DESC, a.assists DESC LIMIT 1;
  IF FOUND THEN
    INSERT INTO public.competition_season_award (
      season_id, season_label, award_type, player_id, club_short_name, stat_value
    ) VALUES (
      p_season_id, p_season_label, 'golden_boot',
      v_boot.player_id, v_boot.club_short_name, v_boot.goals
    );
  END IF;

  SELECT a.* INTO v_play
  FROM public.competition_player_season_archive a
  WHERE a.season_id = p_season_id AND a.assists > 0
  ORDER BY a.assists DESC, a.goals DESC LIMIT 1;
  IF FOUND THEN
    INSERT INTO public.competition_season_award (
      season_id, season_label, award_type, player_id, club_short_name, stat_value
    ) VALUES (
      p_season_id, p_season_label, 'golden_playmaker',
      v_play.player_id, v_play.club_short_name, v_play.assists
    );
  END IF;

  SELECT a.* INTO v_potm
  FROM public.competition_player_season_archive a
  WHERE a.season_id = p_season_id AND a.potm_awards > 0
  ORDER BY a.potm_awards DESC, a.goals DESC LIMIT 1;
  IF FOUND THEN
    INSERT INTO public.competition_season_award (
      season_id, season_label, award_type, player_id, club_short_name, stat_value
    ) VALUES (
      p_season_id, p_season_label, 'season_potm',
      v_potm.player_id, v_potm.club_short_name, v_potm.potm_awards
    );
  END IF;

  SELECT a.* INTO v_glove
  FROM public.competition_player_season_archive a
  WHERE a.season_id = p_season_id
    AND a.stat_role = 'goalkeeper'
    AND a.clean_sheets > 0
  ORDER BY a.clean_sheets DESC, a.avg_rating DESC NULLS LAST LIMIT 1;
  IF FOUND THEN
    INSERT INTO public.competition_season_award (
      season_id, season_label, award_type, player_id, club_short_name, stat_value
    ) VALUES (
      p_season_id, p_season_label, 'golden_glove',
      v_glove.player_id, v_glove.club_short_name, v_glove.clean_sheets
    );
  END IF;

  v_tots := public.competition_compute_team_of_season(p_season_id);
  v_champ := public.competition_compute_championship_player_of_season(p_season_id);

  RETURN jsonb_build_object(
    'team_of_season', v_tots,
    'championship_player_of_season', v_champ,
    'ballon_dor_player_id', v_ballon_id
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.competition_finalize_season_player_awards(bigint, text) TO authenticated;

GRANT EXECUTE ON FUNCTION public.competition_compute_team_of_month(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_process_month_team_awards(bigint) TO authenticated;

-- ---------------------------------------------------------------------------
-- Calendar month tick — compute TOTM when a GPSL month locks
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_calendar_month_tick()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_month text;
  v_month_sort smallint;
  v_august_sort constant smallint := public.competition_gpsl_month_sort('august');
  v_job_id bigint;
  v_enforcement jsonb;
  v_totm jsonb;
  v_out jsonb;
BEGIN
  SELECT id
  INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true
    AND status = 'active'
  ORDER BY id DESC
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_active_season');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.competition_season_calendar_config c
    WHERE c.season_id = v_season_id
  ) THEN
    RETURN jsonb_build_object(
      'ok', false,
      'reason', 'no_calendar',
      'season_id', v_season_id
    );
  END IF;

  v_month := public.competition_active_gpsl_month(v_season_id, now());
  v_month_sort := public.competition_gpsl_month_sort(v_month);

  v_out := jsonb_build_object(
    'ok', true,
    'season_id', v_season_id,
    'gpsl_month', v_month,
    'calendar_phase', CASE
      WHEN v_month IS NULL THEN 'between_months'
      ELSE 'in_month'
    END
  );

  v_totm := public.competition_process_month_team_awards(v_season_id);
  v_out := v_out || jsonb_build_object('team_of_month', v_totm);

  IF v_month IS NULL OR v_month_sort IS NULL OR v_month_sort < v_august_sort THEN
    RETURN v_out || jsonb_build_object(
      'squad_minimum_august', jsonb_build_object('skipped', true, 'reason', 'before_august')
    );
  END IF;

  INSERT INTO public.competition_season_calendar_jobs (
    season_id, job_key, gpsl_month, result
  )
  VALUES (
    v_season_id,
    'squad_minimum_august',
    v_month,
    jsonb_build_object('status', 'running')
  )
  ON CONFLICT (season_id, job_key) DO NOTHING
  RETURNING id INTO v_job_id;

  IF v_job_id IS NULL THEN
    RETURN v_out || jsonb_build_object(
      'squad_minimum_august', jsonb_build_object('skipped', true, 'reason', 'already_ran')
    );
  END IF;

  v_enforcement := public.competition_enforce_squad_minimum_august(v_season_id);

  UPDATE public.competition_season_calendar_jobs
  SET result = v_enforcement,
      gpsl_month = v_month,
      ran_at = now()
  WHERE id = v_job_id;

  RETURN v_out || jsonb_build_object('squad_minimum_august', v_enforcement);
END;
$function$;
