-- =============================================================================
-- Cup targets: alternative route for manager targets + club season expectations
--
-- A cup target only rescues a SLIGHT league miss:
--   • Club: performance band 'slight' + any club cup target met → on target
--     (no board fine / forced listing; counts as met for manager deal rules).
--     'bad' / 'abysmal' are never rescued. Stadium fill is unchanged (league only).
--   • Manager: league target missed by ≤ manager_cup_rescue_places (default 2)
--     places, not relegated, and the rule's cup target met → counts as a hit.
--     avoid_relegation misses are never rescued.
--
-- Cups: league_cup, super8, plate, shield, bowl. Stages: r16, qf, sf, final, win
-- (counted back from the final, so they work whatever the bracket size).
-- A cup target is ignored if that cup wasn't drawn this season or the club
-- wasn't in it (e.g. Super8 not qualified, Plate/Shield/Bowl off).
--
-- Club cup targets are set by prestige rank on Admin → Club attendance & prestige.
-- Manager cup targets are set per rule on Admin → Manager contract targets.
--
-- Run after season_expectation_outcomes_refine_20260924.sql. Safe re-run.
-- =============================================================================

ALTER TABLE public.global_settings
  ADD COLUMN IF NOT EXISTS manager_cup_rescue_places smallint NOT NULL DEFAULT 2;

-- ---------------------------------------------------------------------------
-- Manager rule: optional cup target
-- ---------------------------------------------------------------------------
ALTER TABLE public.manager_rating_targets
  ADD COLUMN IF NOT EXISTS cup_code text,
  ADD COLUMN IF NOT EXISTS cup_stage text;

ALTER TABLE public.manager_rating_targets
  DROP CONSTRAINT IF EXISTS manager_rating_targets_cup_check;
ALTER TABLE public.manager_rating_targets
  ADD CONSTRAINT manager_rating_targets_cup_check CHECK (
    (cup_code IS NULL AND cup_stage IS NULL)
    OR (
      cup_code IN ('league_cup', 'super8', 'plate', 'shield', 'bowl')
      AND cup_stage IN ('r16', 'qf', 'sf', 'final', 'win')
    )
  );

-- ---------------------------------------------------------------------------
-- Club cup targets by prestige rank
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.club_prestige_cup_targets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  min_rank smallint NOT NULL CHECK (min_rank >= 1),
  max_rank smallint NOT NULL,
  cup_code text NOT NULL CHECK (cup_code IN ('league_cup', 'super8', 'plate', 'shield', 'bowl')),
  cup_stage text NOT NULL CHECK (cup_stage IN ('r16', 'qf', 'sf', 'final', 'win')),
  label text,
  sort_order smallint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT club_prestige_cup_targets_rank_check CHECK (max_rank >= min_rank)
);

ALTER TABLE public.club_prestige_cup_targets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_prestige_cup_targets_select ON public.club_prestige_cup_targets;
CREATE POLICY club_prestige_cup_targets_select
  ON public.club_prestige_cup_targets FOR SELECT TO authenticated USING (true);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.competition_cup_stage_level(p_stage text)
RETURNS int
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE lower(btrim(coalesce(p_stage, '')))
    WHEN 'r16' THEN 1
    WHEN 'qf' THEN 2
    WHEN 'sf' THEN 3
    WHEN 'final' THEN 4
    WHEN 'win' THEN 5
    ELSE NULL
  END;
$$;

CREATE OR REPLACE FUNCTION public.competition_cup_target_label(p_cup_code text, p_stage text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE lower(btrim(coalesce(p_stage, '')))
      WHEN 'win' THEN 'Win the '
      WHEN 'final' THEN 'Reach the final of the '
      WHEN 'sf' THEN 'Reach the semi-final of the '
      WHEN 'qf' THEN 'Reach the quarter-final of the '
      WHEN 'r16' THEN 'Reach the last 16 of the '
      ELSE ''
    END
    || CASE lower(btrim(coalesce(p_cup_code, '')))
      WHEN 'league_cup' THEN 'League Cup'
      WHEN 'super8' THEN 'Super8'
      WHEN 'plate' THEN 'Plate'
      WHEN 'shield' THEN 'Shield'
      WHEN 'bowl' THEN 'Bowl'
      ELSE coalesce(p_cup_code, 'cup')
    END;
$$;

-- Level reached: 5 won, 4 final, 3 SF, 2 QF, 1 last 16, 0 earlier exit.
-- NULL = cup not drawn this season or club not in it.
CREATE OR REPLACE FUNCTION public.competition_club_cup_level_reached(
  p_season_id bigint,
  p_club_short_name text,
  p_cup_code text
)
RETURNS int
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_total int;
  v_club_max int;
  v_won boolean;
  v_diff int;
BEGIN
  SELECT max(n.round_no) INTO v_total
  FROM public.competition_cup_bracket_nodes n
  WHERE n.season_id = p_season_id AND n.cup_code = p_cup_code;

  IF v_total IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT max(n.round_no) INTO v_club_max
  FROM public.competition_cup_bracket_nodes n
  WHERE n.season_id = p_season_id
    AND n.cup_code = p_cup_code
    AND (n.home_club_short_name = p_club_short_name OR n.away_club_short_name = p_club_short_name);

  IF v_club_max IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.competition_cup_bracket_nodes n
    WHERE n.season_id = p_season_id
      AND n.cup_code = p_cup_code
      AND n.round_no = v_total
      AND n.winner_club_short_name = p_club_short_name
  ) INTO v_won;

  IF v_won THEN
    RETURN 5;
  END IF;

  v_diff := v_total - v_club_max;
  RETURN CASE v_diff
    WHEN 0 THEN 4
    WHEN 1 THEN 3
    WHEN 2 THEN 2
    WHEN 3 THEN 1
    ELSE 0
  END;
END;
$function$;

-- TRUE met / FALSE not met / NULL not applicable (cup not drawn / club not in it)
CREATE OR REPLACE FUNCTION public.competition_cup_target_met(
  p_season_id bigint,
  p_club_short_name text,
  p_cup_code text,
  p_stage text
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE
    WHEN p_cup_code IS NULL OR p_stage IS NULL THEN NULL
    ELSE public.competition_club_cup_level_reached(p_season_id, p_club_short_name, p_cup_code)
         >= public.competition_cup_stage_level(p_stage)
  END;
$$;

CREATE OR REPLACE FUNCTION public.competition_club_prestige_rank_for_season(
  p_club_short_name text,
  p_season_id bigint
)
RETURNS smallint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(
    (SELECT s.prestige_rank FROM public.competition_club_prestige_snapshot s
     WHERE s.season_id = p_season_id AND s.club_short_name = p_club_short_name),
    (SELECT c.prestige_rank FROM public.competition_club_prestige_computed() c
     WHERE c.club_short_name = p_club_short_name)
  );
$$;

-- Club cup targets for a season with status
CREATE OR REPLACE FUNCTION public.club_cup_target_status(
  p_club_short_name text,
  p_season_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_rank smallint;
  v_targets jsonb := '[]'::jsonb;
  v_any_met boolean := false;
  v_any_applicable boolean := false;
  v_t record;
  v_met boolean;
BEGIN
  v_rank := public.competition_club_prestige_rank_for_season(p_club_short_name, p_season_id);

  IF v_rank IS NOT NULL THEN
    FOR v_t IN
      SELECT * FROM public.club_prestige_cup_targets t
      WHERE v_rank BETWEEN t.min_rank AND t.max_rank
      ORDER BY t.sort_order, t.id
    LOOP
      v_met := public.competition_cup_target_met(p_season_id, p_club_short_name, v_t.cup_code, v_t.cup_stage);
      IF v_met IS NOT NULL THEN
        v_any_applicable := true;
      END IF;
      IF v_met IS TRUE THEN
        v_any_met := true;
      END IF;
      v_targets := v_targets || jsonb_build_array(jsonb_build_object(
        'cup_code', v_t.cup_code,
        'cup_stage', v_t.cup_stage,
        'label', coalesce(nullif(btrim(v_t.label), ''),
                          public.competition_cup_target_label(v_t.cup_code, v_t.cup_stage)),
        'applicable', v_met IS NOT NULL,
        'met', v_met
      ));
    END LOOP;
  END IF;

  RETURN jsonb_build_object(
    'club', p_club_short_name,
    'season_id', p_season_id,
    'prestige_rank', v_rank,
    'targets', v_targets,
    'applicable', v_any_applicable,
    'met', v_any_met
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_expectation_cup_rescued(
  p_club_short_name text,
  p_season_id bigint
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.club_expectation_band_for_season(p_club_short_name, p_season_id) = 'slight'
     AND coalesce((public.club_cup_target_status(p_club_short_name, p_season_id)->>'met')::boolean, false);
$$;

-- Missed = off target in the league AND not rescued by a cup target
CREATE OR REPLACE FUNCTION public.club_expectation_missed_for_season(
  p_club_short_name text,
  p_season_id bigint
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.club_expectation_band_for_season(p_club_short_name, p_season_id)
           IS DISTINCT FROM 'on_target'
     AND NOT coalesce(public.club_expectation_cup_rescued(p_club_short_name, p_season_id), false);
$$;

-- ---------------------------------------------------------------------------
-- Manager: league target OR (slight miss + rule's cup target)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.manager_target_met_with_cup(
  p_target public.manager_rating_targets,
  p_actual_position smallint,
  p_division text,
  p_club_short_name text,
  p_season_id bigint
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_met boolean;
  v_places int;
  v_slight boolean := false;
BEGIN
  v_met := public.manager_target_met(p_target, p_actual_position, p_division);
  IF v_met IS NOT FALSE THEN
    RETURN v_met;
  END IF;

  IF p_target.cup_code IS NULL OR p_target.cup_stage IS NULL THEN
    RETURN false;
  END IF;

  -- Relegated from the Super League is never a slight miss
  IF p_division = 'superleague' AND p_actual_position >= 18 THEN
    RETURN false;
  END IF;

  SELECT coalesce(manager_cup_rescue_places, 2) INTO v_places
  FROM public.global_settings WHERE id = 1;
  v_places := coalesce(v_places, 2);

  IF p_target.target_kind = 'max_position' THEN
    v_slight := p_actual_position <= p_target.target_value + v_places;
  ELSIF p_target.target_kind = 'promotion' THEN
    v_slight := p_actual_position <= 2 + v_places;
  ELSE
    v_slight := false;
  END IF;

  IF NOT v_slight THEN
    RETURN false;
  END IF;

  RETURN coalesce(
    public.competition_cup_target_met(p_season_id, p_club_short_name, p_target.cup_code, p_target.cup_stage),
    false
  );
END;
$function$;

DO $inject_mgr$
DECLARE
  v_def text;
  v_old text := 'v_met := public.manager_target_met(v_target, v_pos, v_division);';
  v_new text := 'v_met := public.manager_target_met_with_cup(v_target, v_pos, v_division, v_mgr.contracted_club, v_season.id);';
BEGIN
  SELECT pg_get_functiondef('public.manager_process_season_end()'::regprocedure) INTO v_def;
  IF position(v_new IN v_def) > 0 THEN
    RAISE NOTICE 'manager_process_season_end already uses cup targets';
  ELSIF position(v_old IN v_def) = 0 THEN
    RAISE EXCEPTION 'manager_process_season_end: expected target check not found — cup rescue not applied';
  ELSE
    EXECUTE replace(v_def, v_old, v_new);
  END IF;
END;
$inject_mgr$;

-- ---------------------------------------------------------------------------
-- Club season-end processing: skip fine/listing when rescued by cup
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.club_underperformance_process_club(
  p_club_short_name text,
  p_season_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  v_tier text;
  v_metrics jsonb;
  v_band text;
  v_player_id text;
  v_listing_id bigint;
  v_fine numeric := 0;
BEGIN
  v_tier := public.competition_club_tier(p_club_short_name);
  v_band := public.club_expectation_band_for_season(p_club_short_name, p_season_id);

  IF v_band IS NOT DISTINCT FROM 'on_target' THEN
    RETURN jsonb_build_object(
      'club', p_club_short_name, 'tier', v_tier, 'skipped', 'on_target'
    );
  END IF;

  IF public.club_expectation_cup_rescued(p_club_short_name, p_season_id) THEN
    RETURN jsonb_build_object(
      'club', p_club_short_name, 'tier', v_tier, 'band', v_band,
      'skipped', 'rescued_by_cup_target'
    );
  END IF;

  BEGIN
    v_fine := public.board_fine_owner_personal_pct(
      p_club_short_name,
      25,
      format('Board fine — club expectation %s', v_band),
      p_season_id,
      jsonb_build_object('performance_band', v_band, 'tier', v_tier)
    );
  EXCEPTION WHEN OTHERS THEN
    v_fine := 0;
  END;

  BEGIN
    v_metrics := public.competition_stadium_season_metrics(
      p_club_short_name, p_season_id, NULL
    );
  EXCEPTION WHEN OTHERS THEN
    v_metrics := jsonb_build_object('performance_band', v_band);
  END;

  v_player_id := public.club_underperformance_pick_player(
    p_club_short_name, v_tier, v_band
  );

  IF v_player_id IS NULL THEN
    RETURN jsonb_build_object(
      'club', p_club_short_name,
      'tier', v_tier,
      'band', v_band,
      'board_fine', v_fine,
      'skipped', 'no_eligible_player'
    );
  END IF;

  v_listing_id := public.club_underperformance_create_listing(
    p_club_short_name,
    v_player_id,
    p_season_id,
    v_tier,
    coalesce(v_metrics, '{}'::jsonb) || jsonb_build_object('performance_band', v_band)
  );

  IF v_listing_id IS NULL THEN
    RETURN jsonb_build_object(
      'club', p_club_short_name,
      'tier', v_tier,
      'band', v_band,
      'board_fine', v_fine,
      'skipped', 'listing_exists'
    );
  END IF;

  BEGIN
    PERFORM public.owner_inbox_notify_underperformance_transfer(
      p_club_short_name,
      v_player_id,
      v_listing_id,
      v_tier,
      coalesce(v_metrics, '{}'::jsonb)
        || jsonb_build_object('season_id', p_season_id, 'performance_band', v_band)
    );
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  RETURN jsonb_build_object(
    'club', p_club_short_name,
    'tier', v_tier,
    'band', v_band,
    'player_id', v_player_id,
    'listing_id', v_listing_id,
    'board_fine', v_fine,
    'performance_band', v_band
  );
END;
$fn$;

-- ---------------------------------------------------------------------------
-- Admin RPCs
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_set_manager_target_cup(
  p_id int,
  p_cup_code text,
  p_cup_stage text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cup text := nullif(btrim(coalesce(p_cup_code, '')), '');
  v_stage text := nullif(btrim(coalesce(p_cup_stage, '')), '');
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  IF (v_cup IS NULL) <> (v_stage IS NULL) THEN
    RAISE EXCEPTION 'Choose both a cup and a stage, or neither';
  END IF;

  UPDATE public.manager_rating_targets
  SET cup_code = v_cup, cup_stage = v_stage, updated_at = now()
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Target rule not found';
  END IF;
  RETURN jsonb_build_object('ok', true, 'id', p_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_set_manager_cup_rescue_places(p_places int)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  IF p_places IS NULL OR p_places < 0 OR p_places > 10 THEN
    RAISE EXCEPTION 'Places must be 0–10';
  END IF;
  UPDATE public.global_settings
  SET manager_cup_rescue_places = p_places, updated_at = now()
  WHERE id = 1;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_upsert_club_cup_target(p_payload jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint := nullif(p_payload->>'id', '')::bigint;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_id IS NOT NULL THEN
    UPDATE public.club_prestige_cup_targets
    SET min_rank = (p_payload->>'min_rank')::smallint,
        max_rank = (p_payload->>'max_rank')::smallint,
        cup_code = p_payload->>'cup_code',
        cup_stage = p_payload->>'cup_stage',
        label = nullif(btrim(coalesce(p_payload->>'label', '')), ''),
        sort_order = coalesce((p_payload->>'sort_order')::smallint, 0),
        updated_at = now()
    WHERE id = v_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Cup target not found';
    END IF;
  ELSE
    INSERT INTO public.club_prestige_cup_targets (
      min_rank, max_rank, cup_code, cup_stage, label, sort_order
    )
    VALUES (
      (p_payload->>'min_rank')::smallint,
      (p_payload->>'max_rank')::smallint,
      p_payload->>'cup_code',
      p_payload->>'cup_stage',
      nullif(btrim(coalesce(p_payload->>'label', '')), ''),
      coalesce((p_payload->>'sort_order')::smallint, 0)
    )
    RETURNING id INTO v_id;
  END IF;

  RETURN jsonb_build_object('ok', true, 'id', v_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_delete_club_cup_target(p_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  DELETE FROM public.club_prestige_cup_targets WHERE id = p_id;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.competition_cup_stage_level(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_cup_target_label(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_club_cup_level_reached(bigint, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_cup_target_met(bigint, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_club_prestige_rank_for_season(text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_cup_target_status(text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_expectation_cup_rescued(text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_expectation_missed_for_season(text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.manager_target_met_with_cup(public.manager_rating_targets, smallint, text, text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_manager_target_cup(int, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_manager_cup_rescue_places(int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_upsert_club_cup_target(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_club_cup_target(bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';
