-- =============================================================================
-- Emergency loans (injury / suspension shortfall)
--
-- When from August onward a club’s AVAILABLE players (not injured, not
-- suspended) drop below the 24 minimum, the owner may loan free agents
-- rated ≤66 for ₿2.5m (paid to central bank).
--
-- Duration (half-season):
--   Taken Aug–Dec  → returns end of December
--   Taken Jan–May  → returns end of May
--
-- Squad space:
--   Under 28 → fill empty slots
--   At 28    → allow one emergency overflow (28+1) only
--
-- Run once in Supabase SQL Editor. Safe re-run.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.club_emergency_loans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName") ON DELETE CASCADE,
  player_id text NOT NULL,
  loan_fee numeric NOT NULL DEFAULT 2500000,
  started_gpsl_month text NOT NULL,
  ends_gpsl_month text NOT NULL
    CHECK (ends_gpsl_month IN ('december', 'may')),
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'completed', 'cancelled')),
  loan_ledger_id bigint,
  overflow_slot boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (season_id, player_id)
);

CREATE INDEX IF NOT EXISTS club_emergency_loans_club_active_idx
  ON public.club_emergency_loans (club_short_name, season_id)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS club_emergency_loans_ends_idx
  ON public.club_emergency_loans (season_id, ends_gpsl_month)
  WHERE status = 'active';

ALTER TABLE public.club_emergency_loans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_emergency_loans_select ON public.club_emergency_loans;
CREATE POLICY club_emergency_loans_select ON public.club_emergency_loans
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS club_emergency_loans_admin ON public.club_emergency_loans;
CREATE POLICY club_emergency_loans_admin ON public.club_emergency_loans
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.club_emergency_loans TO authenticated;

CREATE OR REPLACE FUNCTION public.emergency_loan_fee_amount()
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$ SELECT 2500000::numeric; $$;

CREATE OR REPLACE FUNCTION public.emergency_loan_max_rating()
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$ SELECT 66::numeric; $$;

-- ---------------------------------------------------------------------------
-- Half-season window helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.emergency_loan_window_end_month(p_month text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE lower(btrim(coalesce(p_month, '')))
    WHEN 'august' THEN 'december'
    WHEN 'september' THEN 'december'
    WHEN 'october' THEN 'december'
    WHEN 'november' THEN 'december'
    WHEN 'december' THEN 'december'
    WHEN 'january' THEN 'may'
    WHEN 'february' THEN 'may'
    WHEN 'march' THEN 'may'
    WHEN 'april' THEN 'may'
    WHEN 'may' THEN 'may'
    ELSE NULL
  END;
$$;

CREATE OR REPLACE FUNCTION public.emergency_loan_window_open(p_month text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT public.emergency_loan_window_end_month(p_month) IS NOT NULL;
$$;

-- ---------------------------------------------------------------------------
-- Available (fit) players — not out injured, not suspended
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_player_is_currently_unavailable(p_player_id text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.competition_player_injuries i
    WHERE i.player_id = p_player_id
      AND i.status = 'active'
  )
  OR EXISTS (
    SELECT 1
    FROM public.competition_player_suspensions s
    WHERE s.player_id = p_player_id
      AND s.status = 'active'
      AND EXISTS (
        SELECT 1
        FROM public.competition_player_suspension_matches sm
        WHERE sm.suspension_id = s.id
          AND sm.served = false
      )
  );
$$;

CREATE OR REPLACE FUNCTION public.club_available_player_count(p_club_short_name text)
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT count(*)::int
  FROM public."Players" p
  WHERE p."Contracted_Team" = btrim(p_club_short_name)
    AND NOT public.club_player_is_currently_unavailable(p."Konami_ID"::text);
$$;

CREATE OR REPLACE FUNCTION public.club_active_emergency_loan_count(p_club_short_name text)
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT count(*)::int
  FROM public.club_emergency_loans l
  JOIN public.competition_seasons s ON s.id = l.season_id
  WHERE l.club_short_name = btrim(p_club_short_name)
    AND l.status = 'active'
    AND s.is_current = true;
$$;

-- ---------------------------------------------------------------------------
-- Complete / expire helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.emergency_loan_complete_one(p_loan_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_loan public.club_emergency_loans%rowtype;
  v_player public."Players"%rowtype;
BEGIN
  SELECT * INTO v_loan
  FROM public.club_emergency_loans
  WHERE id = p_loan_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;

  IF v_loan.status <> 'active' THEN
    RETURN jsonb_build_object('ok', true, 'already_done', true, 'loan_id', p_loan_id);
  END IF;

  SELECT * INTO v_player
  FROM public."Players"
  WHERE "Konami_ID"::text = v_loan.player_id
  FOR UPDATE;

  IF FOUND
     AND public.player_contracted_club_key(v_player."Contracted_Team") = v_loan.club_short_name THEN
    UPDATE public."Players"
    SET
      "Contracted_Team" = NULL,
      contract_seasons_remaining = 0,
      contract_wage = 0,
      "Season_Signed" = NULL
    WHERE "Konami_ID"::text = v_loan.player_id;
  END IF;

  UPDATE public.club_emergency_loans
  SET status = 'completed',
      completed_at = now()
  WHERE id = p_loan_id;

  RETURN jsonb_build_object(
    'ok', true,
    'loan_id', p_loan_id,
    'player_id', v_loan.player_id,
    'club_short_name', v_loan.club_short_name
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_emergency_loans_expire_due(
  p_season_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint := p_season_id;
  v_month text;
  v_month_sort int;
  v_row record;
  v_done int := 0;
BEGIN
  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_season');
  END IF;

  v_month := public.competition_active_gpsl_month(v_season_id, now());
  v_month_sort := public.competition_gpsl_month_sort(v_month);

  FOR v_row IN
    SELECT l.id, l.ends_gpsl_month
    FROM public.club_emergency_loans l
    WHERE l.season_id = v_season_id
      AND l.status = 'active'
  LOOP
    -- Expire once the calendar has moved past the end month
    -- (Dec loans expire from January; May loans expire from playoffs / June)
    IF v_month_sort IS NULL
       OR v_month_sort > public.competition_gpsl_month_sort(v_row.ends_gpsl_month) THEN
      PERFORM public.emergency_loan_complete_one(v_row.id);
      v_done := v_done + 1;
    END IF;
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'expired', v_done, 'active_month', v_month);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Status / eligibility
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_emergency_loan_status(
  p_club_short_name text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := nullif(btrim(coalesce(p_club_short_name, public.my_club_shortname())), '');
  v_season_id bigint;
  v_month text;
  v_registered int;
  v_available int;
  v_min int := public.squad_minimum_size();
  v_max int := public.squad_max_size();
  v_need int;
  v_active_loans int;
  v_overflow_used int;
  v_slots int := 0;
  v_ends text;
  v_fee numeric := public.emergency_loan_fee_amount();
  v_balance numeric;
  v_window_open boolean;
BEGIN
  PERFORM public.club_emergency_loans_expire_due(NULL);

  IF v_club IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_club', 'eligible', false);
  END IF;

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true
  ORDER BY id DESC
  LIMIT 1;

  v_month := public.competition_active_gpsl_month(v_season_id, now());
  v_window_open := public.emergency_loan_window_open(v_month);
  v_ends := public.emergency_loan_window_end_month(v_month);

  v_registered := public.club_registered_squad_count(v_club);
  v_available := public.club_available_player_count(v_club);
  v_need := greatest(v_min - v_available, 0);

  SELECT count(*)::int, count(*) FILTER (WHERE overflow_slot)::int
  INTO v_active_loans, v_overflow_used
  FROM public.club_emergency_loans l
  WHERE l.season_id = v_season_id
    AND l.club_short_name = v_club
    AND l.status = 'active';

  IF v_window_open AND v_need > 0 THEN
    IF v_registered < v_max THEN
      v_slots := least(v_need, v_max - v_registered);
    ELSIF v_registered = v_max AND v_overflow_used = 0 THEN
      v_slots := least(v_need, 1);
    ELSIF v_registered = v_max + 1 AND v_overflow_used > 0 THEN
      v_slots := 0;
    ELSE
      v_slots := 0;
    END IF;
  END IF;

  SELECT balance INTO v_balance
  FROM public."Club_Finances"
  WHERE club_name = v_club;

  RETURN jsonb_build_object(
    'ok', true,
    'club_short_name', v_club,
    'season_id', v_season_id,
    'active_gpsl_month', v_month,
    'window_open', v_window_open,
    'ends_gpsl_month', v_ends,
    'min_squad', v_min,
    'max_squad', v_max,
    'registered', v_registered,
    'available', v_available,
    'need', v_need,
    'slots_available', v_slots,
    'eligible', v_window_open AND v_slots > 0,
    'active_emergency_loans', v_active_loans,
    'overflow_slot_used', v_overflow_used > 0,
    'loan_fee', v_fee,
    'max_rating', public.emergency_loan_max_rating(),
    'balance', coalesce(v_balance, 0),
    'can_afford', coalesce(v_balance, 0) >= v_fee
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_emergency_loan_candidates(
  p_limit int DEFAULT 40
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_limit int := greatest(1, least(100, coalesce(p_limit, 40)));
  v_max_rating numeric := public.emergency_loan_max_rating();
BEGIN
  IF v_club IS NULL OR btrim(v_club) = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  RETURN coalesce((
    SELECT jsonb_agg(row_to_json(x) ORDER BY x.rating DESC, x.name)
    FROM (
      SELECT
        p."Konami_ID"::text AS player_id,
        p."Name" AS name,
        p."Position" AS position,
        p."Nation" AS nation,
        p."Age" AS age,
        public.player_rating_as_numeric(p."Rating"::text) AS rating
      FROM public."Players" p
      WHERE (p."Contracted_Team" IS NULL OR btrim(p."Contracted_Team") = '')
        AND coalesce(p.pesdb_unavailable, false) = false
        AND public.player_rating_as_numeric(p."Rating"::text) IS NOT NULL
        AND public.player_rating_as_numeric(p."Rating"::text) <= v_max_rating
        AND NOT EXISTS (
          SELECT 1 FROM public.club_emergency_loans l
          WHERE l.player_id = p."Konami_ID"::text
            AND l.status = 'active'
        )
      ORDER BY random()
      LIMIT v_limit
    ) x
  ), '[]'::jsonb);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Take emergency loan
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_emergency_loan_take(p_player_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_pid text := btrim(p_player_id);
  v_status jsonb;
  v_player public."Players"%rowtype;
  v_season_id bigint;
  v_month text;
  v_ends text;
  v_fee numeric := public.emergency_loan_fee_amount();
  v_max_rating numeric := public.emergency_loan_max_rating();
  v_rating numeric;
  v_wage numeric;
  v_ledger_id bigint;
  v_loan_id bigint;
  v_registered int;
  v_overflow boolean := false;
  v_season_label text;
BEGIN
  IF v_club IS NULL OR btrim(v_club) = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;
  IF v_pid IS NULL OR v_pid = '' THEN
    RAISE EXCEPTION 'Player is required';
  END IF;

  PERFORM public.club_emergency_loans_expire_due(NULL);
  v_status := public.club_emergency_loan_status(v_club);

  IF NOT coalesce((v_status->>'eligible')::boolean, false) THEN
    RAISE EXCEPTION 'Emergency loan not available (need fit players below min 24 from August, with a free/overflow slot)';
  END IF;
  IF NOT coalesce((v_status->>'can_afford')::boolean, false) THEN
    RAISE EXCEPTION 'Insufficient balance for emergency loan fee (need %)', v_fee;
  END IF;

  v_season_id := (v_status->>'season_id')::bigint;
  v_month := v_status->>'active_gpsl_month';
  v_ends := v_status->>'ends_gpsl_month';
  IF v_ends IS NULL THEN
    RAISE EXCEPTION 'Emergency loans are not available in the current GPSL month';
  END IF;

  SELECT * INTO v_player
  FROM public."Players"
  WHERE "Konami_ID"::text = v_pid
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Player not found';
  END IF;
  IF v_player."Contracted_Team" IS NOT NULL AND btrim(v_player."Contracted_Team") <> '' THEN
    RAISE EXCEPTION 'Player is not a free agent';
  END IF;
  IF coalesce(v_player.pesdb_unavailable, false) THEN
    RAISE EXCEPTION 'Player is unavailable (legacy / PESDB)';
  END IF;

  v_rating := public.player_rating_as_numeric(v_player."Rating"::text);
  IF v_rating IS NULL OR v_rating > v_max_rating THEN
    RAISE EXCEPTION 'Emergency loan players must be rated % or lower', v_max_rating;
  END IF;

  v_registered := public.club_registered_squad_count(v_club);
  IF v_registered >= public.squad_max_size() THEN
    IF v_registered > public.squad_max_size() THEN
      RAISE EXCEPTION 'Squad already over maximum — cannot take another emergency loan';
    END IF;
    IF coalesce((v_status->>'overflow_slot_used')::boolean, false) THEN
      RAISE EXCEPTION 'Emergency overflow slot (28+1) already used';
    END IF;
    v_overflow := true;
  END IF;

  -- Lock finances
  PERFORM 1 FROM public."Club_Finances" WHERE club_name = v_club FOR UPDATE;

  v_season_label := public.current_gpsl_season_label();
  v_wage := public.calculate_player_wage_for_club(v_pid, v_club);

  UPDATE public."Players"
  SET
    "Contracted_Team" = v_club,
    "Season_Signed" = v_season_label,
    contract_seasons_remaining = 1,
    contract_wage = round(coalesce(v_wage, 0), 0),
    foreign_contract_club = NULL,
    foreign_contract_sold_season_id = NULL,
    foreign_contract_unlock_season_label = NULL,
    foreign_contract_lock_kind = NULL
  WHERE "Konami_ID"::text = v_pid;

  v_ledger_id := public.post_club_ledger(
    v_club,
    'emergency_loan_fee',
    -abs(v_fee),
    format('Emergency loan fee — %s (until end of %s)', coalesce(v_player."Name", v_pid), initcap(v_ends)),
    jsonb_build_object(
      'player_id', v_pid,
      'season_id', v_season_id,
      'kind', 'emergency_loan',
      'ends_gpsl_month', v_ends,
      'overflow_slot', v_overflow
    ),
    v_season_id,
    NULL,
    true,
    true
  );

  INSERT INTO public.club_emergency_loans (
    season_id,
    club_short_name,
    player_id,
    loan_fee,
    started_gpsl_month,
    ends_gpsl_month,
    status,
    loan_ledger_id,
    overflow_slot
  )
  VALUES (
    v_season_id,
    v_club,
    v_pid,
    v_fee,
    v_month,
    v_ends,
    'active',
    v_ledger_id,
    v_overflow
  )
  RETURNING id INTO v_loan_id;

  -- Do NOT run standard overflow release for the allowed 28+1 emergency slot.
  IF NOT v_overflow THEN
    -- Still under/at 28 after this signing; no release needed.
    NULL;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'loan_id', v_loan_id,
    'player_id', v_pid,
    'player_name', v_player."Name",
    'club_short_name', v_club,
    'loan_fee', v_fee,
    'ends_gpsl_month', v_ends,
    'overflow_slot', v_overflow,
    'status', public.club_emergency_loan_status(v_club)
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Overflow: allow 29 only when the extra is an active emergency overflow loan
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.enforce_squad_overflow_after_signing(
  p_club_short_name text,
  p_new_player_id text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club     text := btrim(p_club_short_name);
  v_total    int;
  v_release  text;
  v_player   public."Players"%rowtype;
  v_interest int;
  v_teams    text[];
  v_team     text;
  v_result   jsonb;
  v_emg_overflow int;
BEGIN
  v_total := public.club_squad_player_count(v_club);

  IF v_total <= public.squad_max_size() THEN
    RETURN jsonb_build_object('released', false, 'squad_total', v_total);
  END IF;

  -- Permit a single emergency-loan overflow (28+1)
  IF v_total = public.squad_max_size() + 1 THEN
    SELECT count(*)::int INTO v_emg_overflow
    FROM public.club_emergency_loans l
    JOIN public.competition_seasons s ON s.id = l.season_id
    WHERE l.club_short_name = v_club
      AND l.status = 'active'
      AND l.overflow_slot = true
      AND s.is_current = true;

    IF v_emg_overflow >= 1 THEN
      RETURN jsonb_build_object(
        'released', false,
        'squad_total', v_total,
        'emergency_overflow', true
      );
    END IF;
  END IF;

  v_release := public.pick_squad_overflow_release_player(v_club, p_new_player_id);

  IF v_release IS NULL THEN
    RAISE EXCEPTION
      'Squad has % players (max %) but no player could be selected for overflow release',
      v_total, public.squad_max_size();
  END IF;

  SELECT * INTO v_player
  FROM public."Players" p
  WHERE p."Konami_ID"::text = v_release;

  SELECT coalesce(c.foreign_interest_remaining, 0)
  INTO v_interest
  FROM public."Clubs" c
  WHERE c."ShortName" = v_club;

  IF coalesce(v_interest, 0) > 0 THEN
    v_teams := public.sync_club_foreign_tracking(v_club);
    v_team := v_teams[1];

    IF v_team IS NULL OR btrim(v_team) = '' THEN
      v_result := public.club_release_player_mv_overflow(v_club, v_release);
      v_result := v_result || jsonb_build_object(
        'released', true,
        'squad_total_before', v_total,
        'reason', 'no_tracking_team'
      );
    ELSE
      v_result := public.club_release_player_foreign_overflow(v_club, v_release, v_team);
      v_result := v_result || jsonb_build_object(
        'released', true,
        'squad_total_before', v_total
      );
    END IF;
  ELSE
    v_result := public.club_release_player_mv_overflow(v_club, v_release);
    v_result := v_result || jsonb_build_object(
      'released', true,
      'squad_total_before', v_total
    );
  END IF;

  RETURN v_result;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.emergency_loan_fee_amount() TO authenticated;
GRANT EXECUTE ON FUNCTION public.emergency_loan_max_rating() TO authenticated;
GRANT EXECUTE ON FUNCTION public.emergency_loan_window_end_month(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.emergency_loan_window_open(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_player_is_currently_unavailable(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_available_player_count(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_active_emergency_loan_count(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.emergency_loan_complete_one(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_emergency_loans_expire_due(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_emergency_loan_status(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_emergency_loan_candidates(int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_emergency_loan_take(text) TO authenticated;

-- Allow ledger type via durable helper (keeps full catalogue)
DO $$
BEGIN
  IF to_regprocedure('public.gpsl_ledger_ensure_entry_types(text[])') IS NOT NULL THEN
    PERFORM public.gpsl_ledger_ensure_entry_types(ARRAY['emergency_loan_fee']);
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
