-- =============================================================================
-- FFP EOS: ₿50M fine + MV releases + same-club season lock + buy embargo
--
-- Rules (Close Finances, after wages / maintenance / debt interest):
--   1) Trigger when Club_Finances.balance <= −₿100,000,000
--   2) Flat ₿50M eos_ffp_charge to central bank
--   3) While balance still <= −₿99,999,999, release highest-MV players @ MV
--      (free agent / draft) until balance > −₿99,999,999
--   4) Released players cannot rejoin that club for the following GPSL season
--   5) Buy embargo for one transfer window — the next window after Close Finances;
--      if the window is already open, skip that one and ban the following.
--      Selling / outbound listings remain allowed.
--
-- Run after stadium_maintenance_eos_and_season1_backfill.sql (or any Close Finances
-- that calls competition_post_eos_ffp_charges). Safe re-run.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Bank defaults: ₿50M fine, −₿100M trigger
-- ---------------------------------------------------------------------------

ALTER TABLE public.gpsl_bank_account
  ADD COLUMN IF NOT EXISTS eos_ffp_debt_threshold numeric(14, 2) NOT NULL DEFAULT 100000000,
  ADD COLUMN IF NOT EXISTS eos_ffp_flat_fine numeric(14, 2) NOT NULL DEFAULT 50000000,
  ADD COLUMN IF NOT EXISTS eos_ffp_clear_threshold numeric(14, 2) NOT NULL DEFAULT 99999999;

UPDATE public.gpsl_bank_account
SET eos_ffp_flat_fine = 50000000,
    eos_ffp_debt_threshold = coalesce(eos_ffp_debt_threshold, 100000000),
    eos_ffp_clear_threshold = coalesce(eos_ffp_clear_threshold, 99999999)
WHERE id = 1;

COMMENT ON COLUMN public.gpsl_bank_account.eos_ffp_debt_threshold IS
  'FFP triggers when balance <= -threshold (default ₿100M).';
COMMENT ON COLUMN public.gpsl_bank_account.eos_ffp_flat_fine IS
  'Flat FFP fine charged to central bank (default ₿50M).';
COMMENT ON COLUMN public.gpsl_bank_account.eos_ffp_clear_threshold IS
  'After fine, release MV until balance > -clear_threshold (default ₿99,999,999).';

-- ---------------------------------------------------------------------------
-- Same-club rejoin ban (following season only)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.player_club_rejoin_blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id text NOT NULL,
  club_short_name text NOT NULL,
  released_season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  blocked_season_id bigint REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  reason text NOT NULL DEFAULT 'ffp_eos_release',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT player_club_rejoin_blocks_unique
    UNIQUE (player_id, club_short_name, released_season_id)
);

CREATE INDEX IF NOT EXISTS player_club_rejoin_blocks_lookup_idx
  ON public.player_club_rejoin_blocks (player_id, club_short_name);

COMMENT ON TABLE public.player_club_rejoin_blocks IS
  'Player cannot rejoin this club during blocked_season_id (following season after FFP release).';

ALTER TABLE public.player_club_rejoin_blocks ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.player_club_rejoin_resolve_blocked_season(
  p_released_season_id bigint
)
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT s.id
  FROM public.competition_seasons s
  WHERE s.id > p_released_season_id
  ORDER BY s.id ASC
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.player_club_rejoin_block_record(
  p_player_id text,
  p_club_short_name text,
  p_released_season_id bigint,
  p_reason text DEFAULT 'ffp_eos_release'
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_pid text := btrim(coalesce(p_player_id, ''));
  v_club text;
  v_blocked bigint;
BEGIN
  IF v_pid = '' OR p_released_season_id IS NULL THEN
    RETURN;
  END IF;

  SELECT c."ShortName" INTO v_club
  FROM public."Clubs" c
  WHERE upper(c."ShortName") = upper(btrim(coalesce(p_club_short_name, '')))
  LIMIT 1;

  IF v_club IS NULL THEN
    v_club := btrim(p_club_short_name);
  END IF;

  IF v_club IS NULL OR v_club = '' THEN
    RETURN;
  END IF;

  v_blocked := public.player_club_rejoin_resolve_blocked_season(p_released_season_id);

  INSERT INTO public.player_club_rejoin_blocks (
    player_id, club_short_name, released_season_id, blocked_season_id, reason
  )
  VALUES (
    v_pid, v_club, p_released_season_id, v_blocked, coalesce(nullif(btrim(p_reason), ''), 'ffp_eos_release')
  )
  ON CONFLICT (player_id, club_short_name, released_season_id)
  DO UPDATE SET
    blocked_season_id = coalesce(
      excluded.blocked_season_id,
      public.player_club_rejoin_blocks.blocked_season_id
    ),
    reason = excluded.reason;
END;
$function$;

CREATE OR REPLACE FUNCTION public.player_club_rejoin_is_blocked(
  p_player_id text,
  p_club_short_name text,
  p_season_id bigint DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_pid text := btrim(coalesce(p_player_id, ''));
  v_club text := upper(btrim(coalesce(p_club_short_name, '')));
  v_season bigint := p_season_id;
  v_row record;
  v_blocked bigint;
BEGIN
  IF v_pid = '' OR v_club = '' THEN
    RETURN false;
  END IF;

  IF v_season IS NULL THEN
    SELECT id INTO v_season
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  IF v_season IS NULL THEN
    RETURN false;
  END IF;

  FOR v_row IN
    SELECT *
    FROM public.player_club_rejoin_blocks b
    WHERE b.player_id = v_pid
      AND upper(b.club_short_name) = v_club
  LOOP
    v_blocked := v_row.blocked_season_id;
    IF v_blocked IS NULL THEN
      v_blocked := public.player_club_rejoin_resolve_blocked_season(v_row.released_season_id);
      IF v_blocked IS NOT NULL THEN
        UPDATE public.player_club_rejoin_blocks
        SET blocked_season_id = v_blocked
        WHERE id = v_row.id;
      END IF;
    END IF;

    IF v_blocked IS NOT NULL AND v_blocked = v_season THEN
      RETURN true;
    END IF;
  END LOOP;

  RETURN false;
END;
$function$;

-- ---------------------------------------------------------------------------
-- One-window buy embargo
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.club_transfer_buy_embargoes (
  club_short_name text PRIMARY KEY,
  source_season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  phase text NOT NULL
    CHECK (phase IN ('skip_current', 'armed', 'active', 'done')),
  reason text NOT NULL DEFAULT 'ffp_eos',
  created_at timestamptz NOT NULL DEFAULT now(),
  activated_at timestamptz,
  completed_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS club_transfer_buy_embargoes_phase_idx
  ON public.club_transfer_buy_embargoes (phase)
  WHERE phase IN ('skip_current', 'armed', 'active');

COMMENT ON TABLE public.club_transfer_buy_embargoes IS
  'FFP buy ban: skip_current (window was open) → armed → active for one open window → done.';

ALTER TABLE public.club_transfer_buy_embargoes ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.club_transfer_buy_embargo_active(p_club_short_name text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.club_transfer_buy_embargoes e
    WHERE upper(e.club_short_name) = upper(btrim(coalesce(p_club_short_name, '')))
      AND e.phase = 'active'
  );
$$;

CREATE OR REPLACE FUNCTION public.assert_club_may_sign_player(
  p_club_short_name text,
  p_player_id text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF public.player_club_rejoin_is_blocked(p_player_id, p_club_short_name) THEN
    RAISE EXCEPTION
      'Player cannot rejoin % this season (FFP release lock)',
      btrim(p_club_short_name);
  END IF;

  IF public.club_transfer_buy_embargo_active(p_club_short_name) THEN
    RAISE EXCEPTION
      '% is under a transfer buy embargo (FFP) and cannot sign players this window',
      btrim(p_club_short_name);
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.trg_players_ffp_rejoin_and_embargo()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_new_club text := btrim(coalesce(NEW."Contracted_Team"::text, ''));
  v_old_club text := btrim(coalesce(OLD."Contracted_Team"::text, ''));
BEGIN
  IF v_new_club = '' OR v_new_club IS NOT DISTINCT FROM v_old_club THEN
    RETURN NEW;
  END IF;

  PERFORM public.assert_club_may_sign_player(v_new_club, NEW."Konami_ID"::text);
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_players_ffp_rejoin_and_embargo ON public."Players";
CREATE TRIGGER trg_players_ffp_rejoin_and_embargo
  BEFORE UPDATE OF "Contracted_Team" ON public."Players"
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_players_ffp_rejoin_and_embargo();

CREATE OR REPLACE FUNCTION public.club_transfer_buy_embargo_ensure(
  p_club_short_name text,
  p_season_id bigint,
  p_reason text DEFAULT 'ffp_eos'
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_open boolean := false;
  v_phase text;
BEGIN
  SELECT c."ShortName" INTO v_club
  FROM public."Clubs" c
  WHERE upper(c."ShortName") = upper(btrim(coalesce(p_club_short_name, '')))
  LIMIT 1;

  IF v_club IS NULL THEN
    v_club := btrim(p_club_short_name);
  END IF;

  IF v_club IS NULL OR v_club = '' OR p_season_id IS NULL THEN
    RETURN NULL;
  END IF;

  -- Already have an unfinished embargo for this club — keep it
  IF EXISTS (
    SELECT 1 FROM public.club_transfer_buy_embargoes e
    WHERE upper(e.club_short_name) = upper(v_club)
      AND e.phase IN ('skip_current', 'armed', 'active')
  ) THEN
    SELECT e.phase INTO v_phase
    FROM public.club_transfer_buy_embargoes e
    WHERE upper(e.club_short_name) = upper(v_club)
      AND e.phase IN ('skip_current', 'armed', 'active')
    LIMIT 1;
    RETURN v_phase;
  END IF;

  SELECT coalesce(g.transfer_window_open, false) INTO v_open
  FROM public.global_settings g
  WHERE g.id = 1;

  v_phase := CASE WHEN v_open THEN 'skip_current' ELSE 'armed' END;

  INSERT INTO public.club_transfer_buy_embargoes (
    club_short_name, source_season_id, phase, reason, metadata
  )
  VALUES (
    v_club,
    p_season_id,
    v_phase,
    coalesce(nullif(btrim(p_reason), ''), 'ffp_eos'),
    jsonb_build_object(
      'window_open_at_create', v_open,
      'created_by', 'competition_post_eos_ffp_charges'
    )
  )
  ON CONFLICT (club_short_name) DO UPDATE
  SET source_season_id = CASE
        WHEN club_transfer_buy_embargoes.phase = 'done'
             AND club_transfer_buy_embargoes.source_season_id = excluded.source_season_id
          THEN club_transfer_buy_embargoes.source_season_id
        WHEN club_transfer_buy_embargoes.phase IN ('skip_current', 'armed', 'active')
          THEN club_transfer_buy_embargoes.source_season_id
        ELSE excluded.source_season_id
      END,
      phase = CASE
        WHEN club_transfer_buy_embargoes.phase IN ('skip_current', 'armed', 'active')
          THEN club_transfer_buy_embargoes.phase
        WHEN club_transfer_buy_embargoes.phase = 'done'
             AND club_transfer_buy_embargoes.source_season_id = excluded.source_season_id
          THEN 'done'
        ELSE excluded.phase
      END,
      reason = excluded.reason,
      completed_at = CASE
        WHEN club_transfer_buy_embargoes.phase = 'done'
             AND club_transfer_buy_embargoes.source_season_id = excluded.source_season_id
          THEN club_transfer_buy_embargoes.completed_at
        WHEN club_transfer_buy_embargoes.phase IN ('skip_current', 'armed', 'active')
          THEN club_transfer_buy_embargoes.completed_at
        ELSE NULL
      END,
      activated_at = CASE
        WHEN club_transfer_buy_embargoes.phase = 'active'
          THEN club_transfer_buy_embargoes.activated_at
        ELSE club_transfer_buy_embargoes.activated_at
      END,
      metadata = club_transfer_buy_embargoes.metadata || excluded.metadata;

  RETURN v_phase;
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_transfer_buy_embargo_on_window_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF TG_OP <> 'UPDATE'
     OR NEW.transfer_window_open IS NOT DISTINCT FROM OLD.transfer_window_open THEN
    RETURN NEW;
  END IF;

  -- Window opens: armed → active (this is the banned window)
  IF NEW.transfer_window_open IS TRUE AND OLD.transfer_window_open IS NOT TRUE THEN
    UPDATE public.club_transfer_buy_embargoes
    SET phase = 'active',
        activated_at = now()
    WHERE phase = 'armed';
  END IF;

  -- Window closes:
  --   skip_current → armed (current open was skipped; next open is banned)
  --   active → done (banned window finished)
  IF NEW.transfer_window_open IS NOT TRUE AND OLD.transfer_window_open IS TRUE THEN
    UPDATE public.club_transfer_buy_embargoes
    SET phase = 'armed'
    WHERE phase = 'skip_current';

    UPDATE public.club_transfer_buy_embargoes
    SET phase = 'done',
        completed_at = now()
    WHERE phase = 'active';
  END IF;

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_club_transfer_buy_embargo_window ON public.global_settings;
CREATE TRIGGER trg_club_transfer_buy_embargo_window
  AFTER UPDATE OF transfer_window_open ON public.global_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.club_transfer_buy_embargo_on_window_change();

CREATE OR REPLACE FUNCTION public.trg_player_transfer_bids_ffp_buy_embargo()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_bidder text := btrim(coalesce(NEW.bidder_club_id::text, ''));
BEGIN
  IF v_bidder = '' THEN
    RETURN NEW;
  END IF;

  IF public.club_transfer_buy_embargo_active(v_bidder) THEN
    RAISE EXCEPTION
      '% is under a transfer buy embargo (FFP) and cannot bid or sign this window',
      v_bidder;
  END IF;

  -- Same-club FFP rejoin lock (draft / direct bids on free agents)
  IF NEW.player_id IS NOT NULL
     AND public.player_club_rejoin_is_blocked(NEW.player_id::text, v_bidder) THEN
    RAISE EXCEPTION
      'Cannot bid: player cannot rejoin % this season (FFP release lock)',
      v_bidder;
  END IF;

  IF NEW.direct_bid_id IS NOT NULL
     AND public.player_club_rejoin_is_blocked(NEW.direct_bid_id::text, v_bidder) THEN
    RAISE EXCEPTION
      'Cannot bid: player cannot rejoin % this season (FFP release lock)',
      v_bidder;
  END IF;

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_player_transfer_bids_ffp_buy_embargo ON public."Player_Transfer_Bids";
CREATE TRIGGER trg_player_transfer_bids_ffp_buy_embargo
  BEFORE INSERT ON public."Player_Transfer_Bids"
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_player_transfer_bids_ffp_buy_embargo();

-- ---------------------------------------------------------------------------
-- Release one player @ MV for FFP (FA / draft; no paid-up lock; no £10m fine)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_release_player_ffp_eos(
  p_club_short_name text,
  p_player_id text,
  p_season_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := btrim(p_club_short_name);
  v_pid text := btrim(p_player_id);
  v_player public."Players"%rowtype;
  v_fee numeric;
  v_bal numeric;
  v_history_id bigint;
BEGIN
  SELECT *
  INTO v_player
  FROM public."Players"
  WHERE "Konami_ID"::text = v_pid
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Player not found';
  END IF;

  IF public.player_contracted_club_key(v_player."Contracted_Team") IS DISTINCT FROM v_club THEN
    RAISE EXCEPTION 'Player is not at club %', v_club;
  END IF;

  v_fee := greatest(coalesce(v_player.market_value::numeric, 0), 0);
  IF v_fee <= 0 THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'zero_mv', 'player_id', v_pid);
  END IF;

  UPDATE public."Player_Transfer_Listings" l
  SET status = 'Closed',
      transfer_completed = false,
      winning_bid = null,
      winning_club = null
  WHERE l.player_id::text = v_pid
    AND l.seller_club_id = v_club
    AND l.status IN ('Active', 'Review', 'Seller Review');

  UPDATE public."Player_Transfer_Bids" b
  SET status = 'rejected'
  WHERE b.is_direct = true
    AND b.listing_id IS NULL
    AND lower(coalesce(b.status::text, '')) = 'active'
    AND (
      (b.player_id IS NOT NULL AND btrim(b.player_id::text) = v_pid)
      OR (b.direct_bid_id IS NOT NULL AND btrim(b.direct_bid_id::text) = v_pid)
    );

  SELECT balance INTO v_bal
  FROM public."Club_Finances"
  WHERE club_name = v_club
  FOR UPDATE;

  IF v_bal IS NULL THEN
    RAISE EXCEPTION 'Club finances not found for %', v_club;
  END IF;

  PERFORM public.ensure_foreign_buyer_club();
  PERFORM public.player_release_from_club(v_pid);
  PERFORM public.player_club_rejoin_block_record(v_pid, v_club, p_season_id, 'ffp_eos_release');

  UPDATE public."Club_Finances"
  SET balance = v_bal + v_fee
  WHERE club_name = v_club;

  INSERT INTO public."Transfer_History" (
    player_id,
    seller_club_id,
    buyer_club_id,
    fee,
    agent_fee,
    transfer_time,
    listing_id,
    foreign_buyer_name,
    transfer_sale_note
  )
  VALUES (
    v_player."Konami_ID",
    v_club,
    'FOREIGN',
    v_fee,
    0,
    now(),
    NULL,
    'FFP release (market value)',
    'ffp_eos_release'
  )
  RETURNING id INTO v_history_id;

  -- Balance already applied; ledger only (same pattern as squad overflow)
  PERFORM public.post_club_ledger(
    v_club,
    'transfer_foreign_sale',
    v_fee,
    format('FFP release: %s', coalesce(v_player."Name", v_pid)),
    jsonb_build_object(
      'transfer_history_id', v_history_id,
      'player_id', v_pid,
      'transfer_sale_note', 'ffp_eos_release',
      'season_id', p_season_id
    ),
    p_season_id,
    NULL,
    false,
    false
  );

  RETURN jsonb_build_object(
    'ok', true,
    'player_id', v_pid,
    'player_name', v_player."Name",
    'rating', v_player."Rating",
    'fee', v_fee,
    'balance_after', v_bal + v_fee,
    'history_id', v_history_id
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- FFP orchestrator
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_post_eos_ffp_charges(p_season_id bigint)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club record;
  v_paid int := 0;
  v_threshold numeric;
  v_fine numeric;
  v_clear numeric;
  v_bal numeric;
  v_player record;
  v_rel jsonb;
  v_released jsonb := '[]'::jsonb;
  v_release_n int;
  v_embargo_phase text;
  v_already_fined boolean;
BEGIN
  IF p_season_id IS NULL THEN
    RETURN 0;
  END IF;

  SELECT
    greatest(coalesce(b.eos_ffp_debt_threshold, 100000000), 0),
    greatest(coalesce(b.eos_ffp_flat_fine, 50000000), 0),
    greatest(coalesce(b.eos_ffp_clear_threshold, 99999999), 0)
  INTO v_threshold, v_fine, v_clear
  FROM public.gpsl_bank_account b
  WHERE b.id = 1;

  v_threshold := coalesce(v_threshold, 100000000);
  v_fine := coalesce(v_fine, 50000000);
  v_clear := coalesce(v_clear, 99999999);

  FOR v_club IN
    SELECT f.club_name AS club_short_name, f.balance
    FROM public."Club_Finances" f
    JOIN public.competition_club_seasons ccs
      ON ccs.club_short_name = f.club_name
     AND ccs.season_id = p_season_id
     AND ccs.division IN ('superleague', 'championship_a', 'championship_b')
    WHERE f.club_name <> 'FOREIGN'
  LOOP
    v_already_fined := EXISTS (
      SELECT 1 FROM public.competition_season_charge_paid
      WHERE season_id = p_season_id
        AND club_short_name = v_club.club_short_name
        AND charge_type = 'eos_ffp_charge'
    );

    -- Fresh snapshot (wages / maintenance / debt may have just posted)
    SELECT balance INTO v_bal
    FROM public."Club_Finances"
    WHERE club_name = v_club.club_short_name
    FOR UPDATE;

    IF v_bal IS NULL THEN
      CONTINUE;
    END IF;

    -- New breach: must be at/below −threshold. Re-runs only continue if fine already posted.
    IF NOT v_already_fined THEN
      IF v_bal > -v_threshold THEN
        CONTINUE;
      END IF;

      IF v_fine > 0 THEN
        PERFORM public.competition_post_club_charge(
          p_season_id,
          v_club.club_short_name,
          'eos_ffp_charge',
          v_fine,
          format(
            'FFP charge — balance ₿%s at/below −₿%s threshold',
            to_char(v_bal, 'FM999,999,999,999'),
            to_char(v_threshold, 'FM999,999,999,999')
          ),
          jsonb_build_object(
            'balance_snapshot', v_bal,
            'threshold', v_threshold,
            'flat_fine', v_fine,
            'clear_threshold', v_clear
          )
        );
      ELSE
        -- Record a zero-amount marker so releases/embargo stay idempotent
        INSERT INTO public.competition_season_charge_paid (
          season_id, club_short_name, charge_type, amount, metadata
        ) VALUES (
          p_season_id, v_club.club_short_name, 'eos_ffp_charge', 0,
          jsonb_build_object('threshold', v_threshold, 'flat_fine', 0)
        )
        ON CONFLICT DO NOTHING;
      END IF;

      SELECT balance INTO v_bal
      FROM public."Club_Finances"
      WHERE club_name = v_club.club_short_name;
    END IF;

    -- Re-run safety: if fine already posted and books are clear enough, only
    -- ensure embargo once for this season (do not re-arm later seasons).
    IF v_already_fined AND v_bal > -v_clear THEN
      IF NOT EXISTS (
        SELECT 1 FROM public.club_transfer_buy_embargoes e
        WHERE upper(e.club_short_name) = upper(v_club.club_short_name)
          AND e.source_season_id = p_season_id
      ) THEN
        PERFORM public.club_transfer_buy_embargo_ensure(
          v_club.club_short_name, p_season_id, 'ffp_eos'
        );
      END IF;
      CONTINUE;
    END IF;

    -- MV releases until balance > −clear_threshold
    v_released := '[]'::jsonb;
    v_release_n := 0;

    WHILE v_bal <= -v_clear LOOP
      SELECT p."Konami_ID"::text AS player_id,
             greatest(coalesce(p.market_value::numeric, 0), 0) AS mv
      INTO v_player
      FROM public."Players" p
      WHERE public.player_contracted_club_key(p."Contracted_Team") = v_club.club_short_name
        AND greatest(coalesce(p.market_value::numeric, 0), 0) > 0
      ORDER BY greatest(coalesce(p.market_value::numeric, 0), 0) DESC,
               p."Konami_ID"
      LIMIT 1;

      IF v_player.player_id IS NULL THEN
        EXIT;
      END IF;

      v_rel := public.club_release_player_ffp_eos(
        v_club.club_short_name,
        v_player.player_id,
        p_season_id
      );

      IF coalesce((v_rel->>'ok')::boolean, false) THEN
        v_released := v_released || jsonb_build_array(v_rel);
        v_release_n := v_release_n + 1;
      ELSE
        EXIT;
      END IF;

      SELECT balance INTO v_bal
      FROM public."Club_Finances"
      WHERE club_name = v_club.club_short_name;
    END LOOP;

    v_embargo_phase := public.club_transfer_buy_embargo_ensure(
      v_club.club_short_name,
      p_season_id,
      'ffp_eos'
    );

    UPDATE public.competition_season_charge_paid
    SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
      'releases', v_released,
      'release_count', v_release_n,
      'balance_after', v_bal,
      'clear_threshold', v_clear,
      'embargo_phase', v_embargo_phase
    )
    WHERE season_id = p_season_id
      AND club_short_name = v_club.club_short_name
      AND charge_type = 'eos_ffp_charge';

    v_paid := v_paid + 1;
  END LOOP;

  RETURN v_paid;
END;
$function$;

-- Close Finances return payload: include note that FFP now does releases
CREATE OR REPLACE FUNCTION public.competition_admin_close_finances(
  p_season_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_wages jsonb;
  v_maint int := 0;
  v_debt int := 0;
  v_ffp int := 0;
  v_credit int := 0;
  v_finance_archived int := 0;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No current season';
  END IF;

  v_wages := public.competition_admin_post_season_wage_bills(v_season_id);

  IF to_regprocedure('public.competition_post_infra_maintenance(bigint)') IS NOT NULL THEN
    v_maint := public.competition_post_infra_maintenance(v_season_id);
  END IF;

  v_debt := public.competition_post_eos_debt_interest(v_season_id);
  v_ffp := public.competition_post_eos_ffp_charges(v_season_id);
  v_credit := public.competition_post_eos_balance_interest(v_season_id);

  IF to_regprocedure('public.competition_archive_club_finances_for_season(bigint)') IS NOT NULL THEN
    v_finance_archived := public.competition_archive_club_finances_for_season(v_season_id);
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'season_id', v_season_id,
    'wages', v_wages,
    'infra_maintenance_clubs', v_maint,
    'debt_interest_clubs', v_debt,
    'ffp_clubs', v_ffp,
    'balance_interest_clubs', v_credit,
    'finance_archive_clubs', v_finance_archived,
    'ffp_note', '₿50M fine + MV releases until above −₿99,999,999 + next-window buy embargo'
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.player_club_rejoin_resolve_blocked_season(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.player_club_rejoin_block_record(text, text, bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.player_club_rejoin_is_blocked(text, text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assert_club_may_sign_player(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_transfer_buy_embargo_active(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_transfer_buy_embargo_ensure(text, bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_release_player_ffp_eos(text, text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_post_eos_ffp_charges(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_close_finances(bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';
