-- =============================================================================
-- GPFL v2 — core upgrades: deadlines, chips, transfer hits, bench order,
-- player cards (ownership / FDR / next fixtures / form) and effective XI
-- with auto-subs.
--
-- Run AFTER:
--   gpfl_fantasy_league_20260817.sql
--   gpfl_formations_positions_20260817.sql
--   gpfl_pool_club_owner_20260817.sql
--   gpfl_contracted_only_pool_20260817.sql
--   gpfl_owned_clubs_only_20260817.sql
--   gpfl_rebase_budget_after_change_20260817.sql
--
-- This file contains NO scoring / set_xi / add_player changes — those live in
-- gpfl_v2_scoring_transfers_20260818.sql (run that second).
--
-- Play-money only. Never touches competition_finance_ledger or club balances.
-- Safe re-run.
-- =============================================================================

SET statement_timeout = '180s';

-- ---------------------------------------------------------------------------
-- 1. Settings: hits, deadline mode, chips
-- ---------------------------------------------------------------------------
ALTER TABLE public.gpfl_settings
  ADD COLUMN IF NOT EXISTS transfer_hit_points numeric NOT NULL DEFAULT -4,
  ADD COLUMN IF NOT EXISTS deadline_mode text NOT NULL DEFAULT 'month_unlock',
  ADD COLUMN IF NOT EXISTS chips_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS chip_wildcard_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS chip_triple_captain_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS chip_bench_boost_enabled boolean NOT NULL DEFAULT true;

UPDATE public.gpfl_settings
SET deadline_mode = 'month_unlock'
WHERE id = 1
  AND coalesce(deadline_mode, '') NOT IN ('month_unlock', 'none');

DO $do$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.gpfl_settings'::regclass
      AND conname = 'gpfl_settings_deadline_mode_check'
  ) THEN
    ALTER TABLE public.gpfl_settings
      ADD CONSTRAINT gpfl_settings_deadline_mode_check
      CHECK (deadline_mode IN ('month_unlock', 'none'));
  END IF;
END
$do$;

COMMENT ON COLUMN public.gpfl_settings.transfer_hit_points IS
  'Points charged per transfer beyond the free allowance (stored negative, e.g. -4).';
COMMENT ON COLUMN public.gpfl_settings.deadline_mode IS
  'month_unlock = squad locked while a GPSL month is live; none = always editable.';

-- ---------------------------------------------------------------------------
-- 2. Entries: chips, hits, provisional points
-- ---------------------------------------------------------------------------
ALTER TABLE public.gpfl_entries
  ADD COLUMN IF NOT EXISTS chip_wildcard_available boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS chip_triple_captain_available boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS chip_bench_boost_available boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS active_chip text,
  ADD COLUMN IF NOT EXISTS active_chip_month text,
  ADD COLUMN IF NOT EXISTS transfer_hits_season int NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS transfers_made_month int NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS provisional_points numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS provisional_month text;

UPDATE public.gpfl_entries
SET active_chip = NULL
WHERE active_chip IS NOT NULL
  AND lower(btrim(active_chip)) NOT IN ('wildcard', 'triple_captain', 'bench_boost');

DO $do$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.gpfl_entries'::regclass
      AND conname = 'gpfl_entries_active_chip_check'
  ) THEN
    ALTER TABLE public.gpfl_entries
      ADD CONSTRAINT gpfl_entries_active_chip_check
      CHECK (active_chip IS NULL OR active_chip IN ('wildcard', 'triple_captain', 'bench_boost'));
  END IF;
END
$do$;

-- ---------------------------------------------------------------------------
-- 3. Squad: bench order (1 = first sub)
-- ---------------------------------------------------------------------------
ALTER TABLE public.gpfl_squad_players
  ADD COLUMN IF NOT EXISTS bench_order smallint;

COMMENT ON COLUMN public.gpfl_squad_players.bench_order IS
  'Auto-sub priority for non-starters. 1 = first off the bench.';

-- ---------------------------------------------------------------------------
-- 4. Transfer log
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.gpfl_transfers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gpfl_season_id bigint NOT NULL REFERENCES public.gpfl_seasons (id) ON DELETE CASCADE,
  entry_id bigint NOT NULL REFERENCES public.gpfl_entries (id) ON DELETE CASCADE,
  player_in text,
  player_out text,
  gpsl_month text,
  is_hit boolean NOT NULL DEFAULT false,
  hit_points numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS gpfl_transfers_entry_month_idx
  ON public.gpfl_transfers (entry_id, gpsl_month);

CREATE INDEX IF NOT EXISTS gpfl_transfers_season_month_idx
  ON public.gpfl_transfers (gpfl_season_id, gpsl_month);

ALTER TABLE public.gpfl_transfers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS gpfl_transfers_read ON public.gpfl_transfers;
CREATE POLICY gpfl_transfers_read ON public.gpfl_transfers
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.gpfl_entries e
      WHERE e.id = entry_id
        AND (e.owner_id = auth.uid() OR public.is_gpsl_admin())
    )
  );

COMMENT ON TABLE public.gpfl_transfers IS
  'GPFL transfer log. hit_points is stored negative when the move costs points.';

-- ---------------------------------------------------------------------------
-- 5. Month points: hits, chip, provisional, auto-sub log
-- ---------------------------------------------------------------------------
ALTER TABLE public.gpfl_entry_month_points
  ADD COLUMN IF NOT EXISTS hit_points numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chip_used text,
  ADD COLUMN IF NOT EXISTS is_provisional boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS auto_sub_log jsonb NOT NULL DEFAULT '[]'::jsonb;

-- ---------------------------------------------------------------------------
-- 6a. Deadline helpers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.gpfl_editing_open(
  p_competition_season_id bigint DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_mode text;
  v_comp_id bigint := p_competition_season_id;
  v_active text;
BEGIN
  SELECT coalesce(s.deadline_mode, 'month_unlock') INTO v_mode
  FROM public.gpfl_settings s WHERE s.id = 1;

  IF coalesce(v_mode, 'month_unlock') = 'none' THEN
    RETURN true;
  END IF;

  IF v_comp_id IS NULL THEN
    SELECT gs.competition_season_id INTO v_comp_id
    FROM public.gpfl_seasons gs
    JOIN public.competition_seasons cs ON cs.id = gs.competition_season_id
    WHERE cs.is_current = true
    ORDER BY gs.id DESC
    LIMIT 1;
  END IF;

  IF v_comp_id IS NULL THEN
    SELECT cs.id INTO v_comp_id
    FROM public.competition_seasons cs
    WHERE cs.is_current = true
    ORDER BY cs.id DESC
    LIMIT 1;
  END IF;

  IF v_comp_id IS NULL THEN
    RETURN true;
  END IF;

  v_active := public.competition_active_gpsl_month(v_comp_id, now());

  -- A live (unlocked) GPSL month means the fantasy deadline has passed.
  RETURN v_active IS NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpfl_target_month(
  p_competition_season_id bigint DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_comp_id bigint := p_competition_season_id;
  v_month text;
BEGIN
  IF v_comp_id IS NULL THEN
    SELECT gs.competition_season_id INTO v_comp_id
    FROM public.gpfl_seasons gs
    JOIN public.competition_seasons cs ON cs.id = gs.competition_season_id
    WHERE cs.is_current = true
    ORDER BY gs.id DESC
    LIMIT 1;
  END IF;

  IF v_comp_id IS NULL THEN
    SELECT cs.id INTO v_comp_id
    FROM public.competition_seasons cs
    WHERE cs.is_current = true
    ORDER BY cs.id DESC
    LIMIT 1;
  END IF;

  IF v_comp_id IS NULL THEN
    RETURN NULL;
  END IF;

  v_month := public.competition_active_gpsl_month(v_comp_id, now());

  IF v_month IS NULL THEN
    SELECT c.gpsl_month INTO v_month
    FROM public.competition_season_calendar c
    WHERE c.season_id = v_comp_id
      AND c.unlock_at > now()
    ORDER BY c.sort_order
    LIMIT 1;
  END IF;

  IF v_month IS NULL THEN
    SELECT c.gpsl_month INTO v_month
    FROM public.competition_season_calendar c
    WHERE c.season_id = v_comp_id
      AND c.lock_at <= now()
    ORDER BY c.sort_order DESC
    LIMIT 1;
  END IF;

  RETURN lower(nullif(btrim(coalesce(v_month, '')), ''));
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpfl_assert_editing_open(p_entry public.gpfl_entries)
RETURNS void
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_comp_id bigint;
BEGIN
  -- Still building the initial squad: always editable.
  IF p_entry.id IS NULL OR coalesce(p_entry.status, 'building') = 'building' THEN
    RETURN;
  END IF;

  SELECT gs.competition_season_id INTO v_comp_id
  FROM public.gpfl_seasons gs
  WHERE gs.id = p_entry.gpfl_season_id;

  IF NOT public.gpfl_editing_open(v_comp_id) THEN
    RAISE EXCEPTION 'GPFL deadline passed — the GPSL month is live. Squad changes reopen when the month locks.';
  END IF;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.gpfl_editing_open(bigint) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.gpfl_target_month(bigint) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.gpfl_assert_editing_open(public.gpfl_entries) TO authenticated;

-- ---------------------------------------------------------------------------
-- 6b. Ownership
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.gpfl_ownership_pct(
  p_gpfl_season_id bigint,
  p_player_id text
)
RETURNS numeric
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH pool AS (
    SELECT e.id
    FROM public.gpfl_entries e
    WHERE e.gpfl_season_id = p_gpfl_season_id
      AND e.status IN ('building', 'active')
  ),
  owners AS (
    SELECT count(DISTINCT sp.entry_id)::numeric AS n
    FROM public.gpfl_squad_players sp
    JOIN pool ON pool.id = sp.entry_id
    WHERE sp.player_id = p_player_id
      AND sp.slot_status = 'active'
  )
  SELECT CASE
    WHEN (SELECT count(*) FROM pool) = 0 THEN 0
    ELSE round(
      ((SELECT n FROM owners) * 100.0) / (SELECT count(*)::numeric FROM pool),
      1
    )
  END;
$$;

GRANT EXECUTE ON FUNCTION public.gpfl_ownership_pct(bigint, text) TO authenticated, anon;

-- ---------------------------------------------------------------------------
-- 6c. Fixture difficulty (1 = easiest, 5 = hardest)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.gpfl_fdr_from_table_pos(p_pos int)
RETURNS int
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN p_pos IS NULL THEN 3
    WHEN p_pos <= 4 THEN 5
    WHEN p_pos <= 8 THEN 4
    WHEN p_pos <= 12 THEN 3
    WHEN p_pos <= 16 THEN 2
    ELSE 1
  END;
$$;

GRANT EXECUTE ON FUNCTION public.gpfl_fdr_from_table_pos(int) TO authenticated, anon;

-- ---------------------------------------------------------------------------
-- 6d. Next fixtures for a player (with opponent + FDR)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.gpfl_player_next_fixtures(
  p_player_id text,
  p_limit int DEFAULT 5
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cfg public.gpfl_settings%rowtype;
  v_gs_id bigint := public.gpfl_current_season_id();
  v_comp_id bigint;
  v_club text;
  v_rows jsonb;
  v_lim int := greatest(1, least(coalesce(p_limit, 5), 10));
BEGIN
  SELECT * INTO v_cfg FROM public.gpfl_settings WHERE id = 1;

  IF v_gs_id IS NOT NULL THEN
    SELECT gs.competition_season_id INTO v_comp_id
    FROM public.gpfl_seasons gs WHERE gs.id = v_gs_id;
  END IF;

  IF v_comp_id IS NULL THEN
    SELECT cs.id INTO v_comp_id
    FROM public.competition_seasons cs
    WHERE cs.is_current = true
    ORDER BY cs.id DESC
    LIMIT 1;
  END IF;

  IF v_comp_id IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  SELECT p."Contracted_Team" INTO v_club
  FROM public."Players" p
  WHERE p."Konami_ID"::text = p_player_id
  LIMIT 1;

  IF v_club IS NULL OR btrim(v_club) = '' THEN
    RETURN '[]'::jsonb;
  END IF;

  SELECT coalesce(jsonb_agg(to_jsonb(r) ORDER BY r.month_sort, r.matchday), '[]'::jsonb)
  INTO v_rows
  FROM (
    SELECT
      f.id AS fixture_id,
      f.gpsl_month,
      coalesce(public.competition_gpsl_month_sort(f.gpsl_month), 99) AS month_sort,
      f.matchday,
      f.division,
      (f.home_club_short_name = v_club) AS is_home,
      CASE
        WHEN f.home_club_short_name = v_club THEN f.away_club_short_name
        ELSE f.home_club_short_name
      END AS opponent_short_name,
      coalesce(
        nullif(btrim(c."Club"), ''),
        CASE
          WHEN f.home_club_short_name = v_club THEN f.away_club_short_name
          ELSE f.home_club_short_name
        END
      ) AS opponent_name,
      public.competition_club_table_position(
        f.season_id,
        f.division,
        CASE
          WHEN f.home_club_short_name = v_club THEN f.away_club_short_name
          ELSE f.home_club_short_name
        END
      ) AS opponent_position,
      public.gpfl_fdr_from_table_pos(
        public.competition_club_table_position(
          f.season_id,
          f.division,
          CASE
            WHEN f.home_club_short_name = v_club THEN f.away_club_short_name
            ELSE f.home_club_short_name
          END
        )
      ) AS fdr
    FROM public.competition_fixtures f
    LEFT JOIN public."Clubs" c
      ON c."ShortName" = CASE
        WHEN f.home_club_short_name = v_club THEN f.away_club_short_name
        ELSE f.home_club_short_name
      END
    WHERE f.season_id = v_comp_id
      AND f.status = 'scheduled'
      AND f.competition_type = ANY (v_cfg.competition_types)
      AND (f.home_club_short_name = v_club OR f.away_club_short_name = v_club)
    ORDER BY coalesce(public.competition_gpsl_month_sort(f.gpsl_month), 99), f.matchday
    LIMIT v_lim
  ) r;

  RETURN v_rows;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.gpfl_player_next_fixtures(text, int) TO authenticated, anon;

-- ---------------------------------------------------------------------------
-- 6e. Appearances / points for a player in a GPSL month
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.gpfl_player_month_apps(
  p_gpfl_season_id bigint,
  p_player_id text,
  p_gpsl_month text
)
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT count(*)::int
  FROM public.gpfl_seasons gs
  CROSS JOIN public.gpfl_settings s
  JOIN public.competition_fixtures f
    ON f.season_id = gs.competition_season_id
  JOIN public.competition_match_player_stats m
    ON m.fixture_id = f.id
   AND m.player_id = p_player_id
  WHERE gs.id = p_gpfl_season_id
    AND s.id = 1
    AND f.status = 'played'
    AND f.competition_type = ANY (s.competition_types)
    AND lower(coalesce(f.gpsl_month, '')) = lower(btrim(coalesce(p_gpsl_month, '')))
    AND coalesce(m.appeared, true) = true;
$$;

CREATE OR REPLACE FUNCTION public.gpfl_player_month_points(
  p_gpfl_season_id bigint,
  p_player_id text,
  p_gpsl_month text
)
RETURNS numeric
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(sum(pfp.points), 0)::numeric
  FROM public.gpfl_player_fixture_points pfp
  LEFT JOIN public.competition_fixtures f ON f.id = pfp.fixture_id
  WHERE pfp.gpfl_season_id = p_gpfl_season_id
    AND pfp.player_id = p_player_id
    AND lower(coalesce(pfp.gpsl_month, f.gpsl_month, '')) = lower(btrim(coalesce(p_gpsl_month, '')));
$$;

GRANT EXECUTE ON FUNCTION public.gpfl_player_month_apps(bigint, text, text) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.gpfl_player_month_points(bigint, text, text) TO authenticated, anon;

-- ---------------------------------------------------------------------------
-- 6f. Player card
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.gpfl_player_card(p_player_id text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cfg public.gpfl_settings%rowtype;
  v_gs_id bigint := public.gpfl_current_season_id();
  v_comp_id bigint;
  v_price public.gpfl_player_prices%rowtype;
  v_name text;
  v_club text;
  v_club_name text;
  v_position text;
  v_position_group text;
  v_division text;
  v_apps int := 0;
  v_goals int := 0;
  v_assists int := 0;
  v_potm int := 0;
  v_total numeric := 0;
  v_form jsonb := '[]'::jsonb;
  v_next jsonb := '[]'::jsonb;
  v_own numeric := 0;
BEGIN
  IF p_player_id IS NULL OR btrim(p_player_id) = '' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'player_id_required');
  END IF;

  SELECT * INTO v_cfg FROM public.gpfl_settings WHERE id = 1;

  IF v_gs_id IS NOT NULL THEN
    SELECT gs.competition_season_id INTO v_comp_id
    FROM public.gpfl_seasons gs WHERE gs.id = v_gs_id;

    SELECT * INTO v_price
    FROM public.gpfl_player_prices pp
    WHERE pp.gpfl_season_id = v_gs_id AND pp.player_id = p_player_id;
  END IF;

  IF v_comp_id IS NULL THEN
    SELECT cs.id INTO v_comp_id
    FROM public.competition_seasons cs
    WHERE cs.is_current = true
    ORDER BY cs.id DESC
    LIMIT 1;
  END IF;

  SELECT
    coalesce(nullif(btrim(p."Name"), ''), v_price.player_name),
    p."Contracted_Team",
    coalesce(nullif(btrim(p."Position"::text), ''), v_price.position)
  INTO v_name, v_club, v_position
  FROM public."Players" p
  WHERE p."Konami_ID"::text = p_player_id
  LIMIT 1;

  v_name := coalesce(v_name, v_price.player_name, p_player_id);
  v_club := coalesce(nullif(btrim(coalesce(v_club, '')), ''), v_price.club_short_name);
  v_position := coalesce(v_position, v_price.position);
  v_position_group := coalesce(v_price.position_group, public.gpfl_position_group(v_position));

  SELECT coalesce(nullif(btrim(c."Club"), ''), v_club) INTO v_club_name
  FROM public."Clubs" c
  WHERE c."ShortName" = v_club
  LIMIT 1;

  IF v_comp_id IS NOT NULL AND v_club IS NOT NULL THEN
    SELECT ccs.division INTO v_division
    FROM public.competition_club_seasons ccs
    WHERE ccs.season_id = v_comp_id AND ccs.club_short_name = v_club
    LIMIT 1;
  END IF;
  v_division := coalesce(v_division, v_price.division);

  IF v_comp_id IS NOT NULL THEN
    SELECT
      count(*) FILTER (WHERE coalesce(m.appeared, true))::int,
      coalesce(sum(m.goals), 0)::int,
      coalesce(sum(m.assists), 0)::int,
      count(*) FILTER (WHERE coalesce(m.is_player_of_match, false))::int
    INTO v_apps, v_goals, v_assists, v_potm
    FROM public.competition_match_player_stats m
    JOIN public.competition_fixtures f ON f.id = m.fixture_id
    WHERE m.player_id = p_player_id
      AND f.season_id = v_comp_id
      AND f.status = 'played'
      AND f.competition_type = ANY (v_cfg.competition_types);
  END IF;

  IF v_gs_id IS NOT NULL THEN
    SELECT coalesce(sum(pfp.points), 0) INTO v_total
    FROM public.gpfl_player_fixture_points pfp
    WHERE pfp.gpfl_season_id = v_gs_id
      AND pfp.player_id = p_player_id;

    SELECT coalesce(jsonb_agg(to_jsonb(f2) ORDER BY f2.month_sort), '[]'::jsonb)
    INTO v_form
    FROM (
      SELECT *
      FROM (
        SELECT
          lower(coalesce(pfp.gpsl_month, fx.gpsl_month)) AS gpsl_month,
          coalesce(
            public.competition_gpsl_month_sort(lower(coalesce(pfp.gpsl_month, fx.gpsl_month))),
            99
          ) AS month_sort,
          round(sum(pfp.points), 2) AS points,
          count(*)::int AS fixtures
        FROM public.gpfl_player_fixture_points pfp
        LEFT JOIN public.competition_fixtures fx ON fx.id = pfp.fixture_id
        WHERE pfp.gpfl_season_id = v_gs_id
          AND pfp.player_id = p_player_id
          AND coalesce(pfp.gpsl_month, fx.gpsl_month) IS NOT NULL
        GROUP BY 1, 2
        ORDER BY 2 DESC
        LIMIT 5
      ) last5
    ) f2;

    v_own := public.gpfl_ownership_pct(v_gs_id, p_player_id);
  END IF;

  v_next := public.gpfl_player_next_fixtures(p_player_id, 5);

  RETURN jsonb_build_object(
    'ok', true,
    'player_id', p_player_id,
    'player_name', v_name,
    'club_short_name', v_club,
    'club_name', v_club_name,
    'division', v_division,
    'position', v_position,
    'position_group', v_position_group,
    'price', v_price.price,
    'market_value_raw', v_price.market_value_raw,
    'eligible', coalesce(v_price.eligible, false),
    'ownership_pct', coalesce(v_own, 0),
    'apps', coalesce(v_apps, 0),
    'goals', coalesce(v_goals, 0),
    'assists', coalesce(v_assists, 0),
    'potm', coalesce(v_potm, 0),
    'total_points', coalesce(v_total, 0),
    'form', v_form,
    'next_fixtures', v_next
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.gpfl_player_card(text) TO authenticated, anon;

-- ---------------------------------------------------------------------------
-- 6g. Effective XI (auto-subs, bench boost, captaincy by slot)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.gpfl_effective_xi(
  p_entry_id bigint,
  p_gpsl_month text
)
RETURNS TABLE (
  player_id text,
  position_group text,
  pitch_slot text,
  is_captain boolean,
  is_bench boolean,
  bench_order smallint,
  apps int,
  base_points numeric,
  multiplier numeric,
  points numeric,
  replaced_player_id text
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
#variable_conflict use_column
DECLARE
  v_cfg public.gpfl_settings%rowtype;
  v_entry public.gpfl_entries%rowtype;
  v_gs_id bigint;
  v_month text := lower(btrim(coalesce(p_gpsl_month, '')));
  v_chip text;
  v_bench_boost boolean := false;
  v_triple boolean := false;
  v_cap_mult numeric;
  v_used text[] := ARRAY[]::text[];
  v_starter record;
  v_sub record;
  v_sub_id text;
  v_sub_order smallint;
  v_apps int;
  v_pid text;
  v_group text;
  v_replaced text;
  v_bench_order smallint;
  v_base numeric;
  v_mult numeric;
BEGIN
  IF v_month = '' THEN
    RETURN;
  END IF;

  SELECT * INTO v_cfg FROM public.gpfl_settings WHERE id = 1;

  SELECT * INTO v_entry
  FROM public.gpfl_entries e
  WHERE e.id = p_entry_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  v_gs_id := v_entry.gpfl_season_id;

  IF coalesce(v_cfg.chips_enabled, true)
     AND v_entry.active_chip IS NOT NULL
     AND (
       v_entry.active_chip_month IS NULL
       OR lower(btrim(v_entry.active_chip_month)) = v_month
     )
  THEN
    v_chip := lower(btrim(v_entry.active_chip));
  END IF;

  v_bench_boost := coalesce(v_chip, '') = 'bench_boost'
    AND coalesce(v_cfg.chip_bench_boost_enabled, true);
  v_triple := coalesce(v_chip, '') = 'triple_captain'
    AND coalesce(v_cfg.chip_triple_captain_enabled, true);

  v_cap_mult := CASE
    WHEN v_triple THEN greatest(3, coalesce(v_cfg.captain_multiplier, 2))
    ELSE greatest(1, coalesce(v_cfg.captain_multiplier, 2))
  END;

  FOR v_starter IN
    SELECT
      sp.player_id AS pid,
      sp.position_group AS pgroup,
      sp.pitch_slot AS slot,
      sp.is_captain AS cap,
      coalesce(fs.sort_order, 99) AS sort_order
    FROM public.gpfl_squad_players sp
    LEFT JOIN public.gpfl_formation_slots fs
      ON fs.formation_id = v_entry.formation_id
     AND fs.slot_id = sp.pitch_slot
    WHERE sp.entry_id = p_entry_id
      AND sp.slot_status = 'active'
      AND sp.is_starter = true
    ORDER BY coalesce(fs.sort_order, 99), sp.player_id
  LOOP
    v_pid := v_starter.pid;
    v_group := v_starter.pgroup;
    v_replaced := NULL;
    v_bench_order := NULL;
    v_used := v_used || v_starter.pid;

    v_apps := public.gpfl_player_month_apps(v_gs_id, v_starter.pid, v_month);

    -- Auto-sub: a blank starter is replaced by the highest-priority bench
    -- player of the same position group who actually played.
    IF NOT v_bench_boost AND coalesce(v_apps, 0) = 0 THEN
      v_sub_id := NULL;
      v_sub_order := NULL;

      SELECT sp.player_id, sp.bench_order
      INTO v_sub_id, v_sub_order
      FROM public.gpfl_squad_players sp
      WHERE sp.entry_id = p_entry_id
        AND sp.slot_status = 'active'
        AND sp.is_starter = false
        AND sp.position_group = v_group
        AND NOT (sp.player_id = ANY (v_used))
        AND public.gpfl_player_month_apps(v_gs_id, sp.player_id, v_month) > 0
      ORDER BY coalesce(sp.bench_order, 99), sp.player_id
      LIMIT 1;

      IF v_sub_id IS NOT NULL THEN
        v_replaced := v_pid;
        v_pid := v_sub_id;
        v_bench_order := v_sub_order;
        v_used := v_used || v_sub_id;
        v_apps := public.gpfl_player_month_apps(v_gs_id, v_pid, v_month);
      END IF;
    END IF;

    v_base := public.gpfl_player_month_points(v_gs_id, v_pid, v_month);
    -- Captaincy belongs to the slot: an auto-sub inherits the armband.
    v_mult := CASE WHEN coalesce(v_starter.cap, false) THEN v_cap_mult ELSE 1 END;

    player_id := v_pid;
    position_group := v_group;
    pitch_slot := v_starter.slot;
    is_captain := coalesce(v_starter.cap, false);
    is_bench := false;
    bench_order := v_bench_order;
    apps := coalesce(v_apps, 0);
    base_points := coalesce(v_base, 0);
    multiplier := v_mult;
    points := round(coalesce(v_base, 0) * v_mult, 2);
    replaced_player_id := v_replaced;
    RETURN NEXT;
  END LOOP;

  -- Bench boost: every remaining active bench player scores too.
  IF v_bench_boost THEN
    FOR v_sub IN
      SELECT sp.player_id AS pid, sp.position_group AS pgroup, sp.bench_order AS border
      FROM public.gpfl_squad_players sp
      WHERE sp.entry_id = p_entry_id
        AND sp.slot_status = 'active'
        AND sp.is_starter = false
        AND NOT (sp.player_id = ANY (v_used))
      ORDER BY coalesce(sp.bench_order, 99), sp.player_id
    LOOP
      v_used := v_used || v_sub.pid;
      v_base := public.gpfl_player_month_points(v_gs_id, v_sub.pid, v_month);

      player_id := v_sub.pid;
      position_group := v_sub.pgroup;
      pitch_slot := NULL;
      is_captain := false;
      is_bench := true;
      bench_order := v_sub.border;
      apps := public.gpfl_player_month_apps(v_gs_id, v_sub.pid, v_month);
      base_points := coalesce(v_base, 0);
      multiplier := 1;
      points := round(coalesce(v_base, 0), 2);
      replaced_player_id := NULL;
      RETURN NEXT;
    END LOOP;
  END IF;

  RETURN;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.gpfl_effective_xi(bigint, text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 6h. Play a chip
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.gpfl_play_chip(p_chip text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_cfg public.gpfl_settings%rowtype;
  v_gs_id bigint;
  v_comp_id bigint;
  v_entry public.gpfl_entries%rowtype;
  v_chip text := lower(btrim(coalesce(p_chip, '')));
  v_month text;
  v_available boolean;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

  IF v_chip NOT IN ('wildcard', 'triple_captain', 'bench_boost') THEN
    RAISE EXCEPTION 'Unknown chip %', coalesce(p_chip, '(null)');
  END IF;

  SELECT * INTO v_cfg FROM public.gpfl_settings WHERE id = 1;
  IF NOT coalesce(v_cfg.enabled, true) THEN RAISE EXCEPTION 'GPFL disabled'; END IF;
  IF NOT coalesce(v_cfg.chips_enabled, true) THEN RAISE EXCEPTION 'Chips are disabled'; END IF;

  IF v_chip = 'wildcard' AND NOT coalesce(v_cfg.chip_wildcard_enabled, true) THEN
    RAISE EXCEPTION 'Wildcard is disabled';
  END IF;
  IF v_chip = 'triple_captain' AND NOT coalesce(v_cfg.chip_triple_captain_enabled, true) THEN
    RAISE EXCEPTION 'Triple Captain is disabled';
  END IF;
  IF v_chip = 'bench_boost' AND NOT coalesce(v_cfg.chip_bench_boost_enabled, true) THEN
    RAISE EXCEPTION 'Bench Boost is disabled';
  END IF;

  v_gs_id := public.gpfl_current_season_id();
  IF v_gs_id IS NULL THEN RAISE EXCEPTION 'No GPFL season'; END IF;

  SELECT gs.competition_season_id INTO v_comp_id
  FROM public.gpfl_seasons gs WHERE gs.id = v_gs_id;

  SELECT * INTO v_entry
  FROM public.gpfl_entries e
  WHERE e.gpfl_season_id = v_gs_id
    AND e.owner_id = v_uid
    AND e.status IN ('building', 'active');
  IF NOT FOUND THEN RAISE EXCEPTION 'Join GPFL first'; END IF;

  PERFORM public.gpfl_assert_editing_open(v_entry);

  v_available := CASE v_chip
    WHEN 'wildcard' THEN coalesce(v_entry.chip_wildcard_available, true)
    WHEN 'triple_captain' THEN coalesce(v_entry.chip_triple_captain_available, true)
    ELSE coalesce(v_entry.chip_bench_boost_available, true)
  END;

  IF NOT v_available THEN
    RAISE EXCEPTION 'You have already used your % chip this season', replace(v_chip, '_', ' ');
  END IF;

  v_month := coalesce(public.gpfl_target_month(v_comp_id), 'august');

  IF v_entry.active_chip IS NOT NULL
     AND lower(btrim(coalesce(v_entry.active_chip_month, v_month))) = v_month
     AND lower(btrim(v_entry.active_chip)) <> v_chip
  THEN
    RAISE EXCEPTION 'Chip % is already active for %', replace(v_entry.active_chip, '_', ' '), v_month;
  END IF;

  UPDATE public.gpfl_entries e
  SET active_chip = v_chip,
      active_chip_month = v_month,
      chip_wildcard_available = CASE WHEN v_chip = 'wildcard' THEN false ELSE e.chip_wildcard_available END,
      chip_triple_captain_available = CASE WHEN v_chip = 'triple_captain' THEN false ELSE e.chip_triple_captain_available END,
      chip_bench_boost_available = CASE WHEN v_chip = 'bench_boost' THEN false ELSE e.chip_bench_boost_available END
  WHERE e.id = v_entry.id;

  RETURN public.gpfl_my_entry();
END;
$function$;

GRANT EXECUTE ON FUNCTION public.gpfl_play_chip(text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 7. Admin settings: accept the new fields
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_gpfl_settings_set(p_settings jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_div text[];
  v_ctypes text[];
  v_old_budget numeric;
  v_new_budget numeric;
  v_mode text;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  IF p_settings IS NULL OR jsonb_typeof(p_settings) <> 'object' THEN
    RAISE EXCEPTION 'p_settings must be a JSON object';
  END IF;

  SELECT budget INTO v_old_budget FROM public.gpfl_settings WHERE id = 1;

  IF p_settings ? 'divisions' AND jsonb_typeof(p_settings->'divisions') = 'array' THEN
    SELECT array_agg(x) INTO v_div
    FROM jsonb_array_elements_text(p_settings->'divisions') t(x);
  END IF;
  IF p_settings ? 'competition_types' AND jsonb_typeof(p_settings->'competition_types') = 'array' THEN
    SELECT array_agg(x) INTO v_ctypes
    FROM jsonb_array_elements_text(p_settings->'competition_types') t(x);
  END IF;

  v_mode := lower(btrim(coalesce(p_settings->>'deadline_mode', '')));
  IF v_mode NOT IN ('month_unlock', 'none') THEN
    v_mode := NULL;
  END IF;

  UPDATE public.gpfl_settings SET
    enabled = coalesce((p_settings->>'enabled')::boolean, enabled),
    opt_in_only = coalesce((p_settings->>'opt_in_only')::boolean, opt_in_only),
    budget = greatest(1000000, coalesce((p_settings->>'budget')::numeric, budget)),
    squad_size = greatest(11, least(20, coalesce((p_settings->>'squad_size')::int, squad_size))),
    starters = greatest(11, least(11, coalesce((p_settings->>'starters')::int, starters))),
    max_per_club = greatest(1, least(5, coalesce((p_settings->>'max_per_club')::int, max_per_club))),
    slot_gk = greatest(1, least(3, coalesce((p_settings->>'slot_gk')::int, slot_gk))),
    slot_def = greatest(3, least(6, coalesce((p_settings->>'slot_def')::int, slot_def))),
    slot_mid = greatest(3, least(6, coalesce((p_settings->>'slot_mid')::int, slot_mid))),
    slot_fwd = greatest(1, least(4, coalesce((p_settings->>'slot_fwd')::int, slot_fwd))),
    price_round_to = greatest(100000, coalesce((p_settings->>'price_round_to')::numeric, price_round_to)),
    price_floor = greatest(0, coalesce((p_settings->>'price_floor')::numeric, price_floor)),
    free_transfers_per_month = greatest(0, least(15, coalesce((p_settings->>'free_transfers_per_month')::int, free_transfers_per_month))),
    divisions = coalesce(v_div, divisions),
    competition_types = coalesce(v_ctypes, competition_types),
    require_stats_to_score = coalesce((p_settings->>'require_stats_to_score')::boolean, require_stats_to_score),
    pts_appear = coalesce((p_settings->>'pts_appear')::numeric, pts_appear),
    pts_goal_gk = coalesce((p_settings->>'pts_goal_gk')::numeric, pts_goal_gk),
    pts_goal_def = coalesce((p_settings->>'pts_goal_def')::numeric, pts_goal_def),
    pts_goal_mid = coalesce((p_settings->>'pts_goal_mid')::numeric, pts_goal_mid),
    pts_goal_fwd = coalesce((p_settings->>'pts_goal_fwd')::numeric, pts_goal_fwd),
    pts_assist = coalesce((p_settings->>'pts_assist')::numeric, pts_assist),
    pts_cs_gk = coalesce((p_settings->>'pts_cs_gk')::numeric, pts_cs_gk),
    pts_cs_def = coalesce((p_settings->>'pts_cs_def')::numeric, pts_cs_def),
    pts_cs_mid = coalesce((p_settings->>'pts_cs_mid')::numeric, pts_cs_mid),
    pts_cs_fwd = coalesce((p_settings->>'pts_cs_fwd')::numeric, pts_cs_fwd),
    pts_yellow = coalesce((p_settings->>'pts_yellow')::numeric, pts_yellow),
    pts_red = coalesce((p_settings->>'pts_red')::numeric, pts_red),
    pts_potm = coalesce((p_settings->>'pts_potm')::numeric, pts_potm),
    captain_multiplier = greatest(1, coalesce((p_settings->>'captain_multiplier')::numeric, captain_multiplier)),
    transfer_hit_points = CASE
      WHEN p_settings ? 'transfer_hit_points'
        THEN -abs(coalesce((p_settings->>'transfer_hit_points')::numeric, transfer_hit_points))
      ELSE transfer_hit_points
    END,
    deadline_mode = coalesce(v_mode, deadline_mode),
    chips_enabled = coalesce((p_settings->>'chips_enabled')::boolean, chips_enabled),
    chip_wildcard_enabled = coalesce((p_settings->>'chip_wildcard_enabled')::boolean, chip_wildcard_enabled),
    chip_triple_captain_enabled = coalesce((p_settings->>'chip_triple_captain_enabled')::boolean, chip_triple_captain_enabled),
    chip_bench_boost_enabled = coalesce((p_settings->>'chip_bench_boost_enabled')::boolean, chip_bench_boost_enabled),
    updated_at = now(),
    updated_by = auth.uid()
  WHERE id = 1;

  -- Keep slot totals consistent with squad_size
  UPDATE public.gpfl_settings
  SET squad_size = slot_gk + slot_def + slot_mid + slot_fwd
  WHERE id = 1;

  SELECT budget INTO v_new_budget FROM public.gpfl_settings WHERE id = 1;

  IF v_new_budget IS DISTINCT FROM v_old_budget THEN
    PERFORM public.gpfl_rebase_entry_budgets(NULL);
  END IF;

  RETURN public.gpfl_settings_get();
END;
$function$;

GRANT EXECUTE ON FUNCTION public.admin_gpfl_settings_set(jsonb) TO authenticated;

-- ---------------------------------------------------------------------------
-- Backfill: give every non-starter a bench order so auto-subs are deterministic
-- ---------------------------------------------------------------------------
WITH ranked AS (
  SELECT
    sp.id,
    row_number() OVER (
      PARTITION BY sp.entry_id
      ORDER BY
        CASE sp.position_group WHEN 'gk' THEN 1 WHEN 'def' THEN 2 WHEN 'mid' THEN 3 ELSE 4 END,
        sp.id
    )::smallint AS rn
  FROM public.gpfl_squad_players sp
  WHERE sp.slot_status = 'active'
    AND sp.is_starter = false
    AND sp.bench_order IS NULL
)
UPDATE public.gpfl_squad_players sp
SET bench_order = ranked.rn
FROM ranked
WHERE ranked.id = sp.id;

NOTIFY pgrst, 'reload schema';
