-- =============================================================================
-- GPSL Sport — paired story packs + cooldown picker
--
-- • Packs keep headline/subhead/body glued (never mix across packs)
-- • Same pack cannot appear twice in one edition (exclude list)
-- • Packs used in the last N published editions are deprioritised (cooldown)
-- • Seeded from gpsl_sport_templates_FEEDBACK.csv (human-voice variants)
--
-- Safe re-run.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.gpsl_sport_template_packs (
  pack_id text PRIMARY KEY,
  scenario text NOT NULL,
  headline text NOT NULL,
  subhead text NOT NULL DEFAULT '',
  body text NOT NULL,
  priority smallint NOT NULL DEFAULT 5,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS gpsl_sport_template_packs_scenario_idx
  ON public.gpsl_sport_template_packs (scenario)
  WHERE active;

CREATE TABLE IF NOT EXISTS public.gpsl_sport_template_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  edition_id bigint REFERENCES public.gpsl_sport_editions (id) ON DELETE CASCADE,
  season_id bigint,
  gpsl_month text,
  scenario text NOT NULL,
  pack_id text NOT NULL REFERENCES public.gpsl_sport_template_packs (pack_id),
  slot text NOT NULL DEFAULT 'lead',
  used_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS gpsl_sport_template_usage_recent_idx
  ON public.gpsl_sport_template_usage (scenario, used_at DESC);

COMMENT ON TABLE public.gpsl_sport_template_packs IS
  'Paired GPSL Sport copy packs (headline+subhead+body) for random selection.';
COMMENT ON TABLE public.gpsl_sport_template_usage IS
  'Tracks which packs appeared in which editions for cooldown / no-repeat.';

-- Refresh seed from FEEDBACK CSV (replace all seeded packs)
DELETE FROM public.gpsl_sport_template_usage
WHERE pack_id IN (SELECT pack_id FROM public.gpsl_sport_template_packs);

DELETE FROM public.gpsl_sport_template_packs;

INSERT INTO public.gpsl_sport_template_packs (
  pack_id, scenario, headline, subhead, body, priority
) VALUES
  ('cup_chat_groups', 'cup_upset', E'GIANT-KILLING ALERT — {{WINNER}} KO {{LOSER}}', E'Replay this one in the group chats for weeks', E'The cups delivered again. {{WINNER}} sent {{LOSER}} packing {{SCORE}} and the favourites'' fans will be muting notifications until Friday. That is knockout football, full stop.', 10),
  ('cup_earthquake', 'cup_upset', E'CUP EARTHQUAKE: {{WINNER}} DUMP {{LOSER}} OUT', E'{{SCORE}} and the favourites are gone', E'Knockout football does not care about prestige. {{WINNER}} knocked {{LOSER}} out {{SCORE}} and that is the whole story. No rematch. No soft landing. Just the exit door.', 10),
  ('cup_folklore', 'cup_upset', E'{{WINNER}} WRITE {{MONTH}} CUP FOLKLORE', E'{{LOSER}} out — {{SCORE}} will linger', E'Years from now someone will still quote this. {{WINNER}} beat {{LOSER}} {{SCORE}} when nobody outside their chat group believed it. Cup nights do not get much cleaner than that.', 10),
  ('cup_no_mercy', 'cup_upset', E'NO MERCY IN THE CUPS: {{WINNER}} END {{LOSER}}', E'{{DIVISION}} tie settled the hard way', E'{{LOSER}} can call it a bad day. {{WINNER}} will call it a scalp. {{SCORE}} and out — the GPSL cup does not do consolation prizes.', 10),
  ('cup_other_ideas', 'cup_upset', E'{{LOSER}} TURNED UP FOR A ROUTINE NIGHT. {{WINNER}} HAD OTHER IDEAS.', E'Giant-killing chapter written in {{DIVISION}}', E'{{LOSER}} expected progress. {{WINNER}} expected a fight — and won it {{SCORE}}. Cups are cruel like that. One slip, and you are writing next season''s excuses.', 10),
  ('cup_paper_team', 'cup_upset', E'PAPER FAVOURITES {{LOSER}} RIPPED UP BY {{WINNER}}', E'{{SCORE}} — the cup does not read prestige tables', E'On paper this was {{LOSER}}''s night. On the pitch it was {{WINNER}}''s. {{SCORE}} later, the underdogs are still in and the big boys are clearing their calendar.', 10),
  ('press_ambition_gap', 'manager_pressure', E'{{WINNER}}: AMBITION UP HERE — RESULTS DOWN THERE', E'{{DIVISION}} position {{POSITION}} with {{POINTS}} points', E'Something is off at {{WINNER}}. The squad says top half. The table says {{POSITION}} on {{POINTS}}. {{MONTH}} did not fix it. If anything, it turned the whispers into open chat.', 10),
  ('press_board_watching', 'manager_pressure', E'BOARD WATCHING: {{WINNER}} FAIL THEIR OWN STANDARD', E'{{MONTH}} another month of drift', E'Nobody is sacking anyone at breakfast. But {{WINNER}} after {{MONTH}} — {{POINTS}} points, {{POSITION}} in {{DIVISION}} — is the sort of stretch where every training ground rumour gets oxygen.', 10),
  ('press_disconnect', 'manager_pressure', E'BOARDROOM VS PITCH: {{WINNER}} LOOK LOST', E'{{DIVISION}} campaign drifting off course', E'There is a gap at {{WINNER}} between what the board expects and what {{MONTH}} delivered. Fans see it. Rivals smell it. {{POINTS}} points will not quiet either camp.', 10),
  ('press_exit_links', 'manager_pressure', E'EXIT LINKS ALREADY — {{WINNER}} FLOUNDERING', E'Prestige club stuck in the pack', E'When the rumour mill starts naming {{WINNER}} players for the door, you know the month went badly. {{POINTS}} points will not calm anyone. The dugout needs a response before the next GPSL month writes the next chapter.', 10),
  ('press_heat_rising', 'manager_pressure', E'HEAT RISING AT {{WINNER}} AFTER ANOTHER POOR {{MONTH}}', E'{{POINTS}} points is not what this club was built for', E'{{WINNER}} are not mid-table furniture. Sitting on {{POINTS}} points after {{MONTH}} has the inbox restless and the board quieter than usual — which is never a good sign. The manager still has time. Not forever.', 10),
  ('press_microscope', 'manager_pressure', E'{{WINNER}} UNDER THE MICROSCOPE', E'Patience wearing thin after {{MONTH}}', E'Every dropped point at {{WINNER}} gets dissected now. That is the cost of being a big club in a bad run. {{MONTH}} left them on {{POINTS}} — and the microscope is not going away.', 10),
  ('press_not_good_enough', 'manager_pressure', E'NOT GOOD ENOUGH — {{WINNER}} OWNERS KNOW IT', E'{{POSITION}} in the table is the loudest stat', E'You can dress {{MONTH}} up however you like. {{WINNER}} are {{POSITION}} with {{POINTS}} points. For a club of this stature, that sentence does the damage on its own.', 10),
  ('press_questions', 'manager_pressure', E'SERIOUS QUESTIONS AT {{WINNER}}', E'A club this size should not look this stuck', E'Strip out the spin and you are left with this: {{WINNER}} are underwhelming. {{MONTH}} added more of the same. {{POINTS}} points is a number that follows you into the next fixtures whether you like it or not.', 10),
  ('poor_expectation', 'poor_start', E'EXPECTATION VS REALITY: {{WINNER}} STUCK IN {{MONTH}}', E'Medium-club ambitions look a long way off', E'{{WINNER}} do not need to win the league. They do need to look like a side with a plan. {{POINTS}} points after {{MONTH}} is not that look. The next stretch matters more than the press notes.', 10),
  ('poor_grind', 'poor_start', E'ANOTHER GRINDING MONTH FOR {{WINNER}}', E'{{POINTS}} points — the slow start continues', E'No crisis banners yet. Just a nagging feeling at {{WINNER}} that this season is starting wrong. {{MONTH}} added another quiet disappointment. At some point quiet becomes loud.', 10),
  ('poor_need_spark', 'poor_start', E'{{WINNER}} STILL WAITING FOR A SPARK', E'{{MONTH}} came and went without a lift', E'Every side hits a flat patch. {{WINNER}}''s problem is the patch arrived early. {{POINTS}} points is survivable — if {{MONTH}} is the floor, not the ceiling.', 10),
  ('poor_off_pace', 'poor_start', E'{{WINNER}} ALREADY OFF THE PACE IN {{DIVISION}}', E'Squad value not showing up in the points column', E'{{WINNER}} were meant to be in the mix. Right now they are chasing it. {{MONTH}} did not light the fuse — and rivals who were supposed to be looking up at them have already moved on.', 10),
  ('poor_paper_wrong', 'poor_start', E'ON PAPER {{WINNER}} SHOULD BE HIGHER — THEY ARE NOT', E'{{DIVISION}} table telling an awkward truth', E'Ratings. Manager. Pre-season chat. All of it said {{WINNER}} would be fine. The table says {{POINTS}}. {{MONTH}} was another month where the paper version of this club failed to show up.', 10),
  ('poor_promise_gap', 'poor_start', E'{{WINNER}} PROMISED MUCH — {{MONTH}} SAID OTHERWISE', E'Already adrift of where they hoped to be', E'Pre-season chat around {{WINNER}} was hopeful. {{MONTH}} was not. {{POINTS}} points later, the gap between plan and reality is the story — and patience in this league is not endless.', 10),
  ('round_had_it_all', 'roundup', E'{{MONTH}} HAD A BIT OF EVERYTHING', E'Shocks', E'From odd scorelines to familiar grind, {{MONTH}} covered the GPSL spectrum. Clubs reset, points still matter, and pride is never far behind. See you when the next month locks.', 5),
  ('round_leaders_grip', 'roundup', E'LEADERS TIGHTEN THE SCREWS AS {{MONTH}} CLOSES', E'Chase pack still in touch — just', E'{{MONTH}} belonged to the sides who kept winning the ugly ones. The table looks clearer than it did four weeks ago — clearer, not decided. That is usually when the GPSL gets spicy.', 5),
  ('round_noise', 'roundup', E'NOISE', E'The league kept moving whether anyone liked it or not', E'Ignore the noise for a second and look at the table — that is {{MONTH}}''s real headline. Everything else was colour. GPSL Sport will unpack the next chapter when the calendar says so.', 5),
  ('round_reset', 'roundup', E'{{MONTH}} DONE — EVERYONE RESETS', E'GPSL Sport''s monthly sweep', E'Another GPSL month in the books. Some owners will sleep well. Others will open the squad screen first thing. {{MONTH}} changed enough to matter and left enough undecided to keep Friday interesting.', 5),
  ('round_still_racing', 'roundup', E'STILL RACING AFTER {{MONTH}}', E'No clean narratives — just a live league', E'If you wanted a tidy story from {{MONTH}}, you came to the wrong league. Results scrambled the picture again. That is fine. Messy months make better seasons.', 5),
  ('round_wide_open', 'roundup', E'{{MONTH}} GPSL ROUND-UP: TABLE STILL WIDE OPEN', E'Fixtures', E'{{MONTH}} is filed. SuperLeague and the Championships all shifted again, owners argued with calendars and the inbox did what the inbox does. GPSL Sport will be back next edition — the race is nowhere near done.', 5),
  ('shock_experts_wrong', 'shock_result', E'THE TIPSTERS WERE WRONG — {{WINNER}} BEAT {{LOSER}}', E'{{MONTH}} reminder: GPSL does not do tidy favourites', E'If you had {{LOSER}} pencilled in for three points, join the club. {{WINNER}} had other ideas and the board read {{SCORE}}. {{DIVISION}} will be talking about it all week.', 10),
  ('shock_inbox_alight', 'shock_result', E'INBOX ALIGHT: {{WINNER}} DUMP {{LOSER}} {{SCORE}}', E'{{MONTH}}''s loudest scoreline so far', E'You could feel this one land. {{WINNER}} beat {{LOSER}} {{SCORE}} and suddenly every owner had an opinion. Prestige said one thing. The scoreboard said another. That''s the GPSL.', 10),
  ('shock_no_alibi', 'shock_result', E'NO ALIBIS FOR {{LOSER}} AFTER {{SCORE}} TO {{WINNER}}', E'{{DIVISION}} shock that needs no spin', E'{{LOSER}} can talk about bad luck if they want. The rest of the league saw {{WINNER}} win {{SCORE}} and move on. In {{MONTH}}, that is the story that stuck.', 10),
  ('shock_owners_fuming', 'shock_result', E'{{WINNER_OWNER}}''S {{WINNER}} LEAVE {{LOSER_OWNER}} FUMING', E'{{SCORE}} and a long night for the favourites', E'Credit where it''s due: {{WINNER_OWNER}}''s {{WINNER}} turned up. {{LOSER_OWNER}}''s {{LOSER}} did not. {{SCORE}} in {{DIVISION}}, and the inbox was brutal before full-time had even settled.', 10),
  ('shock_quiet_kill', 'shock_result', E'{{WINNER}} DO A QUIET NUMBER ON {{LOSER}}', E'{{SCORE}} — not flashy. Just finished.', E'Not every upset is a carnival. {{WINNER}} just got the job done {{SCORE}} against {{LOSER}} and left {{DIVISION}} looking over its shoulder. Sometimes the calm ones hurt more.', 10),
  ('shock_ruin_night', 'shock_result', E'{{WINNER}} RUIN {{LOSER}}''S NIGHT — {{SCORE}}', E'{{DIVISION}} form guide in the bin after this one', E'Nobody had {{WINNER}} down for this. {{LOSER}} looked favourite on paper and still walked into a {{SCORE}} mess in {{DIVISION}}. One bad night, and the group chats were already rewriting the table.', 10),
  ('shock_script_ripped', 'shock_result', E'{{LOSER}} FOLLOW THE SCRIPT — THEN {{WINNER}} RIP IT UP', E'{{SCORE}} in {{DIVISION}} — the upset of {{MONTH}}', E'{{LOSER}} were supposed to take care of business. Instead {{WINNER}} nicked a {{SCORE}} that will follow them into next month. No need for poetry — the table just got interesting.', 10),
  ('shock_table_tilt', 'shock_result', E'{{DIVISION}} TILTS AS {{WINNER}} FLOOR {{LOSER}}', E'{{SCORE}} changes the mood of the month', E'One result. Different mood. {{WINNER}}''s {{SCORE}} over {{LOSER}} did not just fill a column — it made the {{DIVISION}} race look open again. {{MONTH}} needed a jolt. It got one.', 10);

CREATE OR REPLACE FUNCTION public.gpsl_sport_compose_story_from_packs(
  p_scenario text,
  p_seed text,
  p_vars jsonb,
  p_season_id bigint DEFAULT NULL,
  p_exclude_pack_ids text[] DEFAULT '{}',
  p_cooldown_editions int DEFAULT 3
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_candidates text[];
  v_cooled text[];
  v_pick text;
  v_row public.gpsl_sport_template_packs;
  v_cooldown int := greatest(coalesce(p_cooldown_editions, 3), 0);
  v_exclude text[] := coalesce(p_exclude_pack_ids, '{}');
BEGIN
  IF coalesce(nullif(btrim(p_scenario), ''), '') = '' THEN
    RETURN NULL;
  END IF;

  IF to_regclass('public.gpsl_sport_template_packs') IS NULL THEN
    RETURN NULL;
  END IF;

  -- Packs used in the last N published editions for this scenario
  IF v_cooldown > 0
     AND to_regclass('public.gpsl_sport_template_usage') IS NOT NULL
     AND to_regclass('public.gpsl_sport_editions') IS NOT NULL THEN
    SELECT coalesce(array_agg(DISTINCT u.pack_id), '{}')
    INTO v_cooled
    FROM public.gpsl_sport_template_usage u
    WHERE u.scenario = p_scenario
      AND u.edition_id IN (
        SELECT e.id
        FROM public.gpsl_sport_editions e
        ORDER BY e.published_at DESC NULLS LAST, e.id DESC
        LIMIT v_cooldown
      );
  ELSE
    v_cooled := '{}';
  END IF;

  SELECT coalesce(array_agg(p.pack_id ORDER BY p.priority DESC, p.pack_id), '{}')
  INTO v_candidates
  FROM public.gpsl_sport_template_packs p
  WHERE p.active
    AND p.scenario = p_scenario
    AND NOT (p.pack_id = ANY (v_exclude))
    AND NOT (p.pack_id = ANY (v_cooled));

  -- Soft fallback: ignore cooldown if it wiped the bank
  IF coalesce(array_length(v_candidates, 1), 0) = 0 THEN
    SELECT coalesce(array_agg(p.pack_id ORDER BY p.priority DESC, p.pack_id), '{}')
    INTO v_candidates
    FROM public.gpsl_sport_template_packs p
    WHERE p.active
      AND p.scenario = p_scenario
      AND NOT (p.pack_id = ANY (v_exclude));
  END IF;

  IF coalesce(array_length(v_candidates, 1), 0) = 0 THEN
    RETURN NULL;
  END IF;

  v_pick := v_candidates[
    1 + (abs(hashtext(coalesce(p_seed, p_scenario))) % array_length(v_candidates, 1))
  ];

  SELECT * INTO v_row
  FROM public.gpsl_sport_template_packs p
  WHERE p.pack_id = v_pick;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  RETURN jsonb_build_object(
    'pack_id', v_row.pack_id,
    'scenario', v_row.scenario,
    'headline', public.gpsl_sport_apply_template(v_row.headline, p_vars),
    'subhead', public.gpsl_sport_apply_template(v_row.subhead, p_vars),
    'body', public.gpsl_sport_apply_template(v_row.body, p_vars)
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpsl_sport_record_pack_usage(
  p_edition_id bigint,
  p_season_id bigint,
  p_gpsl_month text,
  p_scenario text,
  p_pack_id text,
  p_slot text DEFAULT 'lead'
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF p_edition_id IS NULL OR coalesce(nullif(btrim(p_pack_id), ''), '') IS NULL THEN
    RETURN;
  END IF;
  IF to_regclass('public.gpsl_sport_template_usage') IS NULL THEN
    RETURN;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.gpsl_sport_template_packs p WHERE p.pack_id = p_pack_id
  ) THEN
    RETURN;
  END IF;

  INSERT INTO public.gpsl_sport_template_usage (
    edition_id, season_id, gpsl_month, scenario, pack_id, slot
  ) VALUES (
    p_edition_id, p_season_id, lower(nullif(btrim(p_gpsl_month), '')),
    coalesce(nullif(btrim(p_scenario), ''), 'unknown'),
    p_pack_id,
    coalesce(nullif(btrim(p_slot), ''), 'lead')
  );
END;
$function$;

GRANT SELECT ON public.gpsl_sport_template_packs TO authenticated;
GRANT SELECT ON public.gpsl_sport_template_usage TO authenticated;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_compose_story_from_packs(text, text, jsonb, bigint, text[], int)
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_record_pack_usage(bigint, bigint, text, text, text, text)
  TO authenticated, service_role;
