-- =============================================================================
-- GPSL Sport — weekly newspaper (Phase 1)
-- Run after competition_real_world_calendar.sql, competition_club_stadium_attendance.sql
-- Safe to re-run (CREATE OR REPLACE / IF NOT EXISTS).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.gpsl_sport_editions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  gpsl_month text NOT NULL,
  edition_label text NOT NULL,
  published_at timestamptz NOT NULL DEFAULT now(),
  story_type text NOT NULL,
  front_page jsonb NOT NULL,
  back_page jsonb NOT NULL DEFAULT '{}'::jsonb,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT gpsl_sport_editions_season_month_unique UNIQUE (season_id, gpsl_month)
);

CREATE INDEX IF NOT EXISTS gpsl_sport_editions_season_published_idx
  ON public.gpsl_sport_editions (season_id, published_at DESC);

CREATE TABLE IF NOT EXISTS public.gpsl_sport_reads (
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  edition_id bigint NOT NULL REFERENCES public.gpsl_sport_editions (id) ON DELETE CASCADE,
  read_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_id, edition_id)
);

COMMENT ON TABLE public.gpsl_sport_editions IS
  'League newspaper edition per GPSL month (generated when month locks).';
COMMENT ON TABLE public.gpsl_sport_reads IS
  'Per-owner read state for GPSL Sport editions.';

ALTER TABLE public.gpsl_sport_editions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gpsl_sport_reads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated read sport editions" ON public.gpsl_sport_editions;
CREATE POLICY "Authenticated read sport editions"
  ON public.gpsl_sport_editions FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Owners read own sport reads" ON public.gpsl_sport_reads;
CREATE POLICY "Owners read own sport reads"
  ON public.gpsl_sport_reads FOR SELECT TO authenticated USING (owner_id = auth.uid());

DROP POLICY IF EXISTS "Owners insert own sport reads" ON public.gpsl_sport_reads;
CREATE POLICY "Owners insert own sport reads"
  ON public.gpsl_sport_reads FOR INSERT TO authenticated WITH CHECK (owner_id = auth.uid());

DROP POLICY IF EXISTS "Owners update own sport reads" ON public.gpsl_sport_reads;
CREATE POLICY "Owners update own sport reads"
  ON public.gpsl_sport_reads FOR UPDATE TO authenticated
  USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());

GRANT SELECT ON public.gpsl_sport_editions TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.gpsl_sport_reads TO authenticated;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.gpsl_sport_club_display_name(p_short text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(
    (SELECT c."Club" FROM public."Clubs" c WHERE c."ShortName" = nullif(btrim(p_short), '') LIMIT 1),
    nullif(btrim(p_short), '')
  );
$$;

CREATE OR REPLACE FUNCTION public.gpsl_sport_format_fee(p_fee numeric)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN p_fee IS NULL OR p_fee < 1 THEN 'undisclosed'
    WHEN p_fee >= 1000000 THEN '₿' || trim(to_char(round(p_fee / 1000000.0, 1), 'FM999,999,990.0')) || 'm'
    WHEN p_fee >= 1000 THEN '₿' || trim(to_char(round(p_fee / 1000.0, 0), 'FM999,999,990')) || 'k'
    ELSE '₿' || trim(to_char(p_fee, 'FM999,999,990'))
  END;
$$;

CREATE OR REPLACE FUNCTION public.gpsl_sport_pick_template(p_seed text, p_templates text[])
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT p_templates[
    1 + (abs(hashtext(coalesce(p_seed, ''))) % greatest(array_length(p_templates, 1), 1))
  ];
$$;

CREATE OR REPLACE FUNCTION public.gpsl_sport_apply_template(p_tpl text, p_vars jsonb)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $function$
DECLARE
  v_out text := coalesce(p_tpl, '');
  v_key text;
  v_val text;
BEGIN
  FOR v_key, v_val IN SELECT * FROM jsonb_each_text(coalesce(p_vars, '{}'::jsonb))
  LOOP
    v_out := replace(v_out, '{{' || upper(v_key) || '}}', coalesce(v_val, ''));
  END LOOP;
  RETURN v_out;
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpsl_sport_fixture_division_label(
  p_division text,
  p_cup_code text,
  p_competition_type text
)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN coalesce(p_competition_type, 'league') = 'cup' OR p_cup_code IS NOT NULL THEN
      CASE p_cup_code
        WHEN 'super8' THEN 'Super8'
        WHEN 'plate' THEN 'Plate'
        WHEN 'shield' THEN 'Shield'
        WHEN 'bowl' THEN 'Bowl'
        WHEN 'league_cup' THEN 'League Cup'
        ELSE initcap(replace(coalesce(p_cup_code, 'cup'), '_', ' '))
      END
    WHEN p_division = 'superleague' THEN 'SuperLeague'
    WHEN p_division = 'championship_a' THEN 'Championship A'
    WHEN p_division = 'championship_b' THEN 'Championship B'
    ELSE coalesce(initcap(replace(coalesce(p_division, 'league'), '_', ' ')), 'League')
  END;
$$;

-- ---------------------------------------------------------------------------
-- Generate one edition for a closed GPSL month
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.gpsl_sport_generate_edition(
  p_season_id bigint,
  p_gpsl_month text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_existing bigint;
  v_month_label text;
  v_club_count int;
  v_story_type text := 'roundup';
  v_story_score numeric := 0;
  v_seed text;
  v_vars jsonb;
  v_headline text;
  v_subhead text;
  v_lead text;
  v_stories jsonb := '[]'::jsonb;
  v_front jsonb;
  v_back jsonb := jsonb_build_object('enabled', false);
  v_f record;
  v_u record;
  v_winner text;
  v_loser text;
  v_winner_name text;
  v_loser_name text;
  v_score text;
  v_division text;
  v_tpl text;
  v_headlines text[];
  v_bodies text[];
  v_subheads text[];
  v_win int;
  v_lose int;
  v_gap int;
  v_shock numeric;
  v_cal record;
  v_transfer record;
  v_transfer_stories jsonb := '[]'::jsonb;
  v_player_name text;
  v_player_rating int;
  v_goals int;
  v_assists int;
  v_seller_name text;
  v_buyer_name text;
  v_fee text;
  v_i int := 0;
BEGIN
  IF p_season_id IS NULL OR p_gpsl_month IS NULL OR btrim(p_gpsl_month) = '' THEN
    RETURN NULL;
  END IF;

  SELECT e.id INTO v_existing
  FROM public.gpsl_sport_editions e
  WHERE e.season_id = p_season_id AND e.gpsl_month = p_gpsl_month;

  IF v_existing IS NOT NULL THEN
    RETURN v_existing;
  END IF;

  v_month_label := public.competition_gpsl_month_label(p_gpsl_month);

  SELECT count(DISTINCT ccs.club_short_name)::int INTO v_club_count
  FROM public.competition_club_seasons ccs
  WHERE ccs.season_id = p_season_id;

  -- Best shock result in the month
  FOR v_f IN
    SELECT
      f.id,
      f.home_club_short_name,
      f.away_club_short_name,
      f.home_goals,
      f.away_goals,
      f.division,
      f.cup_code,
      f.competition_type,
      ph.prestige_rank AS home_prestige,
      pa.prestige_rank AS away_prestige
    FROM public.competition_fixtures f
    LEFT JOIN public.competition_club_prestige_public ph
      ON ph.club_short_name = f.home_club_short_name
    LEFT JOIN public.competition_club_prestige_public pa
      ON pa.club_short_name = f.away_club_short_name
    WHERE f.season_id = p_season_id
      AND f.gpsl_month = p_gpsl_month
      AND f.status = 'played'
      AND f.home_goals IS NOT NULL
      AND f.away_goals IS NOT NULL
  LOOP
    IF v_f.home_goals > v_f.away_goals THEN
      v_winner := v_f.home_club_short_name;
      v_loser := v_f.away_club_short_name;
      v_win := v_f.home_goals;
      v_lose := v_f.away_goals;
      v_gap := coalesce(v_f.away_prestige, 99) - coalesce(v_f.home_prestige, 99);
    ELSIF v_f.away_goals > v_f.home_goals THEN
      v_winner := v_f.away_club_short_name;
      v_loser := v_f.home_club_short_name;
      v_win := v_f.away_goals;
      v_lose := v_f.home_goals;
      v_gap := coalesce(v_f.home_prestige, 99) - coalesce(v_f.away_prestige, 99);
    ELSE
      CONTINUE;
    END IF;

    v_shock := greatest(0, v_gap) * greatest(1, v_win - v_lose + 1);
    IF coalesce(v_f.competition_type, 'league') = 'cup' OR v_f.cup_code IS NOT NULL THEN
      v_shock := v_shock + 5;
    END IF;

    IF v_shock > v_story_score THEN
      v_story_score := v_shock;
      v_story_type := CASE
        WHEN coalesce(v_f.competition_type, 'league') = 'cup' OR v_f.cup_code IS NOT NULL THEN 'cup_upset'
        ELSE 'shock_result'
      END;
      v_winner_name := public.gpsl_sport_club_display_name(v_winner);
      v_loser_name := public.gpsl_sport_club_display_name(v_loser);
      v_score := v_win::text || '–' || v_lose::text;
      v_division := public.gpsl_sport_fixture_division_label(v_f.division, v_f.cup_code, v_f.competition_type);
    END IF;
  END LOOP;

  -- Underperformance / manager pressure
  FOR v_u IN
    SELECT
      s.club_short_name,
      s.table_position,
      s.division,
      s.pts,
      p.prestige_rank,
      public.competition_club_tier(s.club_short_name) AS tier,
      public.competition_club_baseline_expected_position(
        p.prestige_rank,
        greatest(v_club_count, 1)::smallint
      ) AS expected_pos
    FROM public.competition_standings_public s
    LEFT JOIN public.competition_club_prestige_public p
      ON p.club_short_name = s.club_short_name
    WHERE s.season_id = p_season_id
      AND s.division IN ('superleague', 'championship_a', 'championship_b')
  LOOP
    IF v_u.tier NOT IN ('big', 'medium') OR v_u.table_position IS NULL OR v_u.expected_pos IS NULL THEN
      CONTINUE;
    END IF;

    v_shock := (v_u.table_position - v_u.expected_pos)::numeric
      * CASE v_u.tier WHEN 'big' THEN 2.5 WHEN 'medium' THEN 1.5 ELSE 0 END;

    IF v_shock > v_story_score THEN
      v_story_score := v_shock;
      v_story_type := CASE WHEN v_u.tier = 'big' THEN 'manager_pressure' ELSE 'poor_start' END;
      v_winner := v_u.club_short_name;
      v_winner_name := public.gpsl_sport_club_display_name(v_u.club_short_name);
      v_loser := NULL;
      v_loser_name := NULL;
      v_score := coalesce(v_u.pts::text, '0') || ' pts';
      v_division := public.gpsl_sport_fixture_division_label(v_u.division, NULL, 'league');
    END IF;
  END LOOP;

  v_seed := p_season_id::text || ':' || p_gpsl_month || ':' || v_story_type;
  v_vars := jsonb_build_object(
    'winner', coalesce(v_winner_name, 'GPSL'),
    'loser', coalesce(v_loser_name, ''),
    'score', coalesce(v_score, ''),
    'division', coalesce(v_division, 'League'),
    'month', v_month_label
  );

  IF v_story_type = 'shock_result' THEN
    v_headlines := ARRAY[
      '{{WINNER}} STUN {{LOSER}} IN {{DIVISION}} SHOCKER',
      'DRAMA IN {{DIVISION}}: {{WINNER}} TOPPLE {{LOSER}} {{SCORE}}',
      '{{LOSER}} LEFT REELING AFTER {{WINNER}} PULL OFF MAJOR UPSET',
      'FORM GUIDE TORN UP AS {{WINNER}} BEAT {{LOSER}}',
      'EXPERTS WRONG AGAIN — {{WINNER}} SEE OFF {{LOSER}}'
    ];
    v_subheads := ARRAY[
      'Result sends ripples through the {{DIVISION}} table',
      'Owners'' group chat erupts after {{SCORE}} scoreline',
      'Pre-match favourites {{LOSER}} left searching for answers'
    ];
    v_bodies := ARRAY[
      E'In the standout result of {{MONTH}}, {{WINNER}} claimed a {{SCORE}} victory over {{LOSER}} that few saw coming.\n\nPundits had written off the winners before a ball was kicked, but the GPSL never follows the script. {{LOSER}} must regroup quickly with the table tightening.',
      E'{{WINNER}} produced the performance of the GPSL month so far, dismantling {{LOSER}} {{SCORE}} in {{DIVISION}} action.\n\nThe losers'' manager faces awkward questions as expectation and reality drift further apart.',
      E'It was the kind of night that defines a season: {{WINNER}} ruthless, {{LOSER}} ragged, the scoreboard reading {{SCORE}} when the virtual whistle blew.'
    ];
  ELSIF v_story_type = 'cup_upset' THEN
    v_headlines := ARRAY[
      'CUP EARTHQUAKE: {{WINNER}} DUMP {{LOSER}} OUT',
      '{{WINNER}} WRITE {{DIVISION}} HEADLINES WITH {{SCORE}} WIN',
      'GIANT-KILLING ALERT AS {{WINNER}} KO {{LOSER}}'
    ];
    v_subheads := ARRAY[
      'Knockout football at its cruellest for {{LOSER}}',
      '{{DIVISION}} tie will be replayed in chat groups for weeks'
    ];
    v_bodies := ARRAY[
      E'Cup football delivered again as {{WINNER}} knocked out {{LOSER}} {{SCORE}} in the {{DIVISION}}.\n\nThe favourites crumbled under pressure and the underdogs march on.',
      E'{{LOSER}} arrived expecting routine progress. {{WINNER}} had other ideas, winning {{SCORE}} in a tie that will live long in GPSL folklore.'
    ];
  ELSIF v_story_type = 'manager_pressure' THEN
    v_headlines := ARRAY[
      '{{WINNER}} IN CRISIS AFTER DISAPPOINTING {{MONTH}}',
      'MANAGER UNDER PRESSURE AT {{WINNER}}',
      '{{WINNER}} FAIL TO MEET STATURE — BOARD WATCHING',
      'BIG CLUB {{WINNER}} FLOUNDERING BELOW EXPECTATION'
    ];
    v_subheads := ARRAY[
      'Prestige club sitting well below where history says they should be',
      'Stars already linked with exits as results disappoint'
    ];
    v_bodies := ARRAY[
      E'{{WINNER}} head into the next GPSL month with serious questions to answer. A club of their stature expected to be pushing the top of {{DIVISION}}, not lingering in the pack on {{POINTS}} points.\n\nWhispers in the inbox suggest players are already circling the exit door. The manager''s job is not under immediate threat — but the temperature is rising.',
      E'There is a growing disconnect at {{WINNER}} between boardroom ambition and on-pitch delivery. {{MONTH}} results left fans fuming and rivals sensing blood.\n\nUnless form turns quickly, the GPSL rumour mill will have a field day.'
    ];
    v_vars := v_vars || jsonb_build_object(
      'winner', v_winner_name,
      'points', coalesce(v_u.pts::text, '0'),
      'position', coalesce(v_u.table_position::text, '')
    );
  ELSIF v_story_type = 'poor_start' THEN
    v_headlines := ARRAY[
      '{{WINNER}} MAKE POOR START TO GPSL SEASON',
      '{{WINNER}} ALREADY OFF THE PACE IN {{DIVISION}}',
      'EXPECTATION VS REALITY: {{WINNER}} STRUGGLE IN {{MONTH}}'
    ];
    v_subheads := ARRAY[
      'Medium-club ambitions look a long way off on current form',
      'Squad value not translating to league points'
    ];
    v_bodies := ARRAY[
      E'{{WINNER}} promised much in pre-season but {{MONTH}} told a different story. Sitting on {{POINTS}} points, they are already adrift of where their manager rating suggested they should be.\n\nPatience is a virtue in the GPSL — but not an unlimited one.',
      E'Another frustrating month for {{WINNER}}, whose {{DIVISION}} campaign has failed to ignite. Rivals who were supposed to be behind them on paper have pulled clear.'
    ];
    v_vars := v_vars || jsonb_build_object(
      'winner', v_winner_name,
      'points', coalesce(v_u.pts::text, '0'),
      'position', coalesce(v_u.table_position::text, '')
    );
  ELSE
    v_story_type := 'roundup';
    v_headlines := ARRAY[
      '{{MONTH}} GPSL ROUND-UP: TABLE STILL WIDE OPEN',
      'ANOTHER DRAMATIC MONTH IN GPSL FOOTBALL',
      'LEAGUE LEADERS TIGHTEN GRIP AS {{MONTH}} CLOSES'
    ];
    v_subheads := ARRAY[
      'Fixtures, fines and inbox drama across the league',
      'GPSL Sport reviews the month that was'
    ];
    v_bodies := ARRAY[
      E'{{MONTH}} is in the books and the GPSL rolls on. Results across SuperLeague and the Championships reshaped the table while owners battled scheduling, transfers and the inbox.\n\nGPSL Sport will be back next Friday with another edition.',
      E'From shock scorelines to late check-ins, {{MONTH}} had it all. Clubs reset for the next GPSL month with points on the line and pride at stake.'
    ];
    v_vars := jsonb_build_object('month', v_month_label, 'division', 'GPSL');
  END IF;

  v_headline := public.gpsl_sport_apply_template(
    public.gpsl_sport_pick_template(v_seed || ':h', v_headlines),
    v_vars
  );
  v_subhead := public.gpsl_sport_apply_template(
    public.gpsl_sport_pick_template(v_seed || ':s', v_subheads),
    v_vars
  );
  v_lead := public.gpsl_sport_apply_template(
    public.gpsl_sport_pick_template(v_seed || ':b', v_bodies),
    v_vars
  );

  -- Secondary stories from other played fixtures (max 3)
  FOR v_f IN
    SELECT
      f.home_club_short_name,
      f.away_club_short_name,
      f.home_goals,
      f.away_goals,
      f.division,
      f.cup_code,
      f.competition_type
    FROM public.competition_fixtures f
    WHERE f.season_id = p_season_id
      AND f.gpsl_month = p_gpsl_month
      AND f.status = 'played'
    ORDER BY (coalesce(f.home_goals, 0) + coalesce(f.away_goals, 0)) DESC, f.id
    LIMIT 4
  LOOP
    IF jsonb_array_length(v_stories) >= 3 THEN
      EXIT;
    END IF;
    v_division := public.gpsl_sport_fixture_division_label(v_f.division, v_f.cup_code, v_f.competition_type);
    v_stories := v_stories || jsonb_build_array(
      jsonb_build_object(
        'kicker', v_division,
        'headline', public.gpsl_sport_club_display_name(v_f.home_club_short_name)
          || ' ' || coalesce(v_f.home_goals, 0)::text || '–' || coalesce(v_f.away_goals, 0)::text
          || ' ' || public.gpsl_sport_club_display_name(v_f.away_club_short_name),
        'body', format(
          'Full-time in %s. Another result on a busy %s matchday.',
          v_division,
          v_month_label
        )
      )
    );
  END LOOP;

  v_front := jsonb_build_object(
    'masthead', 'GPSL Sport',
    'edition_label', v_month_label,
    'gpsl_month', p_gpsl_month,
    'headline', v_headline,
    'subhead', v_subhead,
    'lead_paragraph', v_lead,
    'stories', v_stories,
    'story_type', v_story_type
  );

  -- Back page: transfers in the GPSL month window
  SELECT c.unlock_at, c.lock_at INTO v_cal
  FROM public.competition_season_calendar c
  WHERE c.season_id = p_season_id AND c.gpsl_month = p_gpsl_month;

  IF v_cal.unlock_at IS NOT NULL AND v_cal.lock_at IS NOT NULL THEN
    FOR v_transfer IN
      SELECT
        h.id,
        h.player_id,
        h.seller_club_id,
        h.buyer_club_id,
        h.fee,
        h.transfer_time,
        p."Name" AS player_name,
        nullif(btrim(p."Rating"::text), '')::int AS rating
      FROM public."Transfer_History" h
      LEFT JOIN public."Players" p ON p."Konami_ID"::text = h.player_id::text
      WHERE h.transfer_time >= v_cal.unlock_at
        AND h.transfer_time < v_cal.lock_at
        AND coalesce(h.buyer_club_id, '') <> ''
        AND h.buyer_club_id <> 'FOREIGN'
        AND coalesce(h.fee, 0) > 0
      ORDER BY h.fee DESC NULLS LAST, h.transfer_time DESC
      LIMIT 9
    LOOP
      v_i := v_i + 1;
      v_player_name := coalesce(v_transfer.player_name, 'Unknown player');
      v_player_rating := coalesce(v_transfer.rating, 0);
      v_seller_name := public.gpsl_sport_club_display_name(v_transfer.seller_club_id);
      v_buyer_name := public.gpsl_sport_club_display_name(v_transfer.buyer_club_id);
      v_fee := public.gpsl_sport_format_fee(v_transfer.fee);

      SELECT coalesce(ps.goals, 0), coalesce(ps.assists, 0)
      INTO v_goals, v_assists
      FROM public.competition_player_season_stats_public ps
      WHERE ps.player_id = v_transfer.player_id::text
        AND ps.club_short_name = v_transfer.seller_club_id
      LIMIT 1;

      IF v_i = 1 THEN
        v_tpl := public.gpsl_sport_pick_template(
          v_seed || ':xfer',
          ARRAY[
            E'{{BUYER}} SPLASH {{FEE}} ON {{PLAYER}} — CAN HE BE THE SAVIOUR?',
            E'BLOCKBUSTER DEAL: {{PLAYER}} HEADS TO {{BUYER}} FOR {{FEE}}',
            E'{{BUYER}} BREAK TRANSFER RECORD WITH {{FEE}} MOVE FOR {{PLAYER}}'
          ]
        );
        v_back := jsonb_build_object(
          'enabled', true,
          'page_title', 'Transfer special',
          'lead', jsonb_build_object(
            'headline', public.gpsl_sport_apply_template(v_tpl, jsonb_build_object(
              'buyer', v_buyer_name,
              'seller', v_seller_name,
              'player', v_player_name,
              'fee', v_fee,
              'rating', v_player_rating::text
            )),
            'body', format(
              E'%s completed the signing of %s (rated %s) from %s for %s in %s.\n\nThe player contributed %s goals and %s assists for his former club this season. Supporters hope he can transform a squad that has been crying out for quality — critics say the fee is a gamble the board may live to regret.',
              v_buyer_name,
              v_player_name,
              v_player_rating,
              v_seller_name,
              v_fee,
              v_month_label,
              coalesce(v_goals, 0),
              coalesce(v_assists, 0)
            ),
            'player_id', v_transfer.player_id,
            'fee', v_transfer.fee
          ),
          'stories', '[]'::jsonb
        );
      ELSE
        v_transfer_stories := v_transfer_stories || jsonb_build_array(
          jsonb_build_object(
            'headline', v_buyer_name || ' sign ' || v_player_name || ' (' || v_fee || ')',
            'body', format(
              'Rated %s. Arrives from %s with %s goals in GPSL competition this season.',
              v_player_rating,
              v_seller_name,
              coalesce(v_goals, 0)
            )
          )
        );
      END IF;
    END LOOP;

    IF (v_back->>'enabled')::boolean IS TRUE THEN
      v_back := v_back || jsonb_build_object('stories', v_transfer_stories);
    END IF;
  END IF;

  INSERT INTO public.gpsl_sport_editions (
    season_id, gpsl_month, edition_label, story_type, front_page, back_page, detail
  )
  VALUES (
    p_season_id,
    p_gpsl_month,
    v_month_label,
    v_story_type,
    v_front,
    v_back,
    jsonb_build_object('story_score', v_story_score, 'generated_at', now())
  )
  RETURNING id INTO v_existing;

  RETURN v_existing;
END;
$function$;

-- Process locked months without an edition
CREATE OR REPLACE FUNCTION public.gpsl_sport_process_pending_editions(p_season_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cal record;
  v_job_key text;
  v_id bigint;
  v_results jsonb := '[]'::jsonb;
BEGIN
  IF p_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_season');
  END IF;

  FOR v_cal IN
    SELECT c.gpsl_month
    FROM public.competition_season_calendar c
    WHERE c.season_id = p_season_id
      AND c.gpsl_month IS NOT NULL
      AND c.lock_at IS NOT NULL
      AND c.lock_at <= now()
    ORDER BY public.competition_gpsl_month_sort(c.gpsl_month)
  LOOP
    v_job_key := 'gpsl_sport:' || v_cal.gpsl_month;

    IF EXISTS (
      SELECT 1 FROM public.competition_season_calendar_jobs j
      WHERE j.season_id = p_season_id AND j.job_key = v_job_key
    ) THEN
      CONTINUE;
    END IF;

    v_id := public.gpsl_sport_generate_edition(p_season_id, v_cal.gpsl_month);

    INSERT INTO public.competition_season_calendar_jobs (
      season_id, job_key, gpsl_month, result
    )
    VALUES (
      p_season_id,
      v_job_key,
      v_cal.gpsl_month,
      jsonb_build_object('edition_id', v_id, 'ok', v_id IS NOT NULL)
    )
    ON CONFLICT (season_id, job_key) DO UPDATE
      SET result = excluded.result,
          gpsl_month = excluded.gpsl_month,
          ran_at = now();

    v_results := v_results || jsonb_build_array(
      jsonb_build_object('gpsl_month', v_cal.gpsl_month, 'edition_id', v_id)
    );
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'processed', v_results);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Owner RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.gpsl_sport_nav_state()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_edition public.gpsl_sport_editions;
  v_unread boolean := false;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;

  SELECT e.* INTO v_edition
  FROM public.gpsl_sport_editions e
  JOIN public.competition_seasons s ON s.id = e.season_id AND s.is_current = true
  ORDER BY e.published_at DESC
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', true, 'has_edition', false);
  END IF;

  SELECT NOT EXISTS (
    SELECT 1 FROM public.gpsl_sport_reads r
    WHERE r.owner_id = v_uid AND r.edition_id = v_edition.id
  ) INTO v_unread;

  RETURN jsonb_build_object(
    'ok', true,
    'has_edition', true,
    'edition_id', v_edition.id,
    'edition_label', v_edition.edition_label,
    'headline', v_edition.front_page->>'headline',
    'unread', v_unread
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpsl_sport_get_edition(p_edition_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_edition public.gpsl_sport_editions;
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;

  SELECT * INTO v_edition FROM public.gpsl_sport_editions WHERE id = p_edition_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'edition', jsonb_build_object(
      'id', v_edition.id,
      'edition_label', v_edition.edition_label,
      'gpsl_month', v_edition.gpsl_month,
      'published_at', v_edition.published_at,
      'story_type', v_edition.story_type,
      'front_page', v_edition.front_page,
      'back_page', v_edition.back_page
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpsl_sport_mark_read(p_edition_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.gpsl_sport_editions WHERE id = p_edition_id) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;

  INSERT INTO public.gpsl_sport_reads (owner_id, edition_id)
  VALUES (v_uid, p_edition_id)
  ON CONFLICT (owner_id, edition_id) DO UPDATE SET read_at = now();

  RETURN jsonb_build_object('ok', true);
END;
$function$;

-- Admin / testing: generate for a specific month immediately
CREATE OR REPLACE FUNCTION public.gpsl_sport_admin_generate_month(p_gpsl_month text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_id bigint;
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true AND status = 'active'
  LIMIT 1;

  v_id := public.gpsl_sport_generate_edition(v_season_id, p_gpsl_month);

  RETURN jsonb_build_object('ok', true, 'edition_id', v_id, 'gpsl_month', p_gpsl_month);
END;
$function$;

GRANT EXECUTE ON FUNCTION public.gpsl_sport_nav_state() TO authenticated;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_get_edition(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_mark_read(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_generate_edition(bigint, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_process_pending_editions(bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_admin_generate_month(text) TO authenticated;

-- ---------------------------------------------------------------------------
-- Hook into calendar month tick (extends free_tier_cron_throttle version)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_calendar_month_tick()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_month text;
  v_month_sort smallint;
  v_august_sort constant smallint := public.competition_gpsl_month_sort('august');
  v_job_id bigint;
  v_enforcement jsonb;
  v_totm jsonb;
  v_sched_fines jsonb;
  v_response_fines jsonb;
  v_sport jsonb;
  v_out jsonb;
  v_last_scheduling timestamptz;
  v_run_scheduling boolean := false;
BEGIN
  SELECT id
  INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true
    AND status = 'active'
  ORDER BY id DESC
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_active_season');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.competition_season_calendar_config c
    WHERE c.season_id = v_season_id
  ) THEN
    RETURN jsonb_build_object(
      'ok', false,
      'reason', 'no_calendar',
      'season_id', v_season_id
    );
  END IF;

  v_month := public.competition_active_gpsl_month(v_season_id, now());
  v_month_sort := public.competition_gpsl_month_sort(v_month);

  v_out := jsonb_build_object(
    'ok', true,
    'season_id', v_season_id,
    'gpsl_month', v_month,
    'calendar_phase', CASE
      WHEN v_month IS NULL THEN 'between_months'
      ELSE 'in_month'
    END
  );

  IF to_regprocedure('public.competition_process_month_team_awards(bigint)') IS NOT NULL THEN
    v_totm := public.competition_process_month_team_awards(v_season_id);
    v_out := v_out || jsonb_build_object('team_of_month', v_totm);
  END IF;

  IF to_regprocedure('public.gpsl_sport_process_pending_editions(bigint)') IS NOT NULL THEN
    v_sport := public.gpsl_sport_process_pending_editions(v_season_id);
    v_out := v_out || jsonb_build_object('gpsl_sport', v_sport);
  END IF;

  SELECT j.ran_at
  INTO v_last_scheduling
  FROM public.competition_season_calendar_jobs j
  WHERE j.season_id = v_season_id
    AND j.job_key = 'scheduling_enforcement_throttle'
  LIMIT 1;

  v_run_scheduling :=
    v_last_scheduling IS NULL
    OR v_last_scheduling < now() - interval '5 minutes';

  IF v_run_scheduling THEN
    v_response_fines := public.competition_process_scheduling_response_deadlines(v_season_id);
    v_out := v_out || jsonb_build_object('scheduling_response_deadlines', v_response_fines);

    v_sched_fines := public.competition_process_scheduling_arrangement_fines(v_season_id);
    v_out := v_out || jsonb_build_object('scheduling_arrangement_fines', v_sched_fines);

    INSERT INTO public.competition_season_calendar_jobs (
      season_id, job_key, gpsl_month, result
    )
    VALUES (
      v_season_id,
      'scheduling_enforcement_throttle',
      coalesce(v_month, 'none'),
      jsonb_build_object('ok', true, 'ran_at', now())
    )
    ON CONFLICT (season_id, job_key) DO UPDATE
      SET result = excluded.result,
          gpsl_month = excluded.gpsl_month,
          ran_at = now();
  ELSE
    v_out := v_out || jsonb_build_object(
      'scheduling_response_deadlines', jsonb_build_object('skipped', true, 'reason', 'throttled'),
      'scheduling_arrangement_fines', jsonb_build_object('skipped', true, 'reason', 'throttled')
    );
  END IF;

  IF v_month IS NULL OR v_month_sort IS NULL OR v_month_sort < v_august_sort THEN
    RETURN v_out || jsonb_build_object(
      'squad_minimum_august', jsonb_build_object('skipped', true, 'reason', 'before_august')
    );
  END IF;

  INSERT INTO public.competition_season_calendar_jobs (
    season_id, job_key, gpsl_month, result
  )
  VALUES (
    v_season_id,
    'squad_minimum_august',
    v_month,
    jsonb_build_object('status', 'running')
  )
  ON CONFLICT (season_id, job_key) DO NOTHING
  RETURNING id INTO v_job_id;

  IF v_job_id IS NULL THEN
    RETURN v_out || jsonb_build_object(
      'squad_minimum_august', jsonb_build_object('skipped', true, 'reason', 'already_ran')
    );
  END IF;

  v_enforcement := public.competition_enforce_squad_minimum_august(v_season_id);

  UPDATE public.competition_season_calendar_jobs
  SET result = v_enforcement,
      gpsl_month = v_month,
      ran_at = now()
  WHERE id = v_job_id;

  RETURN v_out || jsonb_build_object('squad_minimum_august', v_enforcement);
END;
$function$;

NOTIFY pgrst, 'reload schema';
