-- =============================================================================
-- GPSL Sport — force-rebuild August (or any locked in-season month)
--
-- 1. Run the FULL file first: gpsl_sport_inseason_rich_edition.sql
-- 2. Diagnose (optional):
--    SELECT public.competition_admin_gpsl_sport_diagnose('august', NULL);
-- 3. Force rebuild:
--    SELECT public.competition_admin_regenerate_gpsl_sport('august', NULL);
-- =============================================================================
