-- =============================================================================
-- GPSL Sport — owner monthly club news comments
-- Owners draft up to 50 words in Club Details; on GPSL month lock the draft is
-- archived and cleared, then appears in the NEXT month's GPSL Sport edition.
-- Run after gpsl_sport_inseason_rich_edition.sql (then re-run rich edition patch
-- or this file — it replaces capture + process hooks).
-- =============================================================================

ALTER TABLE public."Clubs"
  ADD COLUMN IF NOT EXISTS sport_comment_draft text;

COMMENT ON COLUMN public."Clubs".sport_comment_draft IS
  'Owner draft for GPSL Sport club news (max 50 words). Archived and cleared when the GPSL month locks.';

CREATE TABLE IF NOT EXISTS public.gpsl_sport_owner_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL,
  source_gpsl_month text NOT NULL,
  comment_text text NOT NULL,
  owner_tag text NOT NULL DEFAULT '',
  captured_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT gpsl_sport_owner_comments_unique
    UNIQUE (season_id, club_short_name, source_gpsl_month)
);

CREATE INDEX IF NOT EXISTS gpsl_sport_owner_comments_season_month_idx
  ON public.gpsl_sport_owner_comments (season_id, source_gpsl_month);

ALTER TABLE public.gpsl_sport_owner_comments ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.gpsl_sport_owner_comments IS
  'Archived owner club-news comments captured at GPSL month lock for the following Sport edition.';

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_sport_comment_word_count(p_text text)
RETURNS int
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN p_text IS NULL OR btrim(p_text) = '' THEN 0
    ELSE coalesce(
      array_length(
        regexp_split_to_array(btrim(regexp_replace(p_text, '\s+', ' ', 'g')), '\s'),
        1
      ),
      0
    )
  END;
$$;

CREATE OR REPLACE FUNCTION public.gpsl_sport_previous_gpsl_month(p_month text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE public.competition_gpsl_month_sort(lower(btrim(p_month)))
    WHEN 2 THEN 'august'
    WHEN 3 THEN 'september'
    WHEN 4 THEN 'october'
    WHEN 5 THEN 'november'
    WHEN 6 THEN 'december'
    WHEN 7 THEN 'january'
    WHEN 8 THEN 'february'
    WHEN 9 THEN 'march'
    WHEN 10 THEN 'april'
    WHEN 1 THEN 'july'
    ELSE NULL
  END;
$$;

CREATE OR REPLACE FUNCTION public.gpsl_sport_fetch_club_news(
  p_season_id bigint,
  p_edition_gpsl_month text
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_prev_month text;
BEGIN
  v_prev_month := public.gpsl_sport_previous_gpsl_month(p_edition_gpsl_month);
  IF v_prev_month IS NULL OR p_season_id IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  RETURN coalesce((
    SELECT jsonb_agg(row_data ORDER BY row_data->>'club_short')
    FROM (
      SELECT jsonb_build_object(
        'club_short', oc.club_short_name,
        'club_name', public.gpsl_sport_club_display_name(oc.club_short_name),
        'owner', oc.owner_tag,
        'comment', oc.comment_text,
        'source_gpsl_month', oc.source_gpsl_month,
        'source_month_label', public.competition_gpsl_month_label(oc.source_gpsl_month)
      ) AS row_data
      FROM public.gpsl_sport_owner_comments oc
      WHERE oc.season_id = p_season_id
        AND oc.source_gpsl_month = v_prev_month
    ) q
  ), '[]'::jsonb);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Owner RPCs (Club Details)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_sport_comment_get()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_short text;
  v_draft text;
  v_words int;
BEGIN
  SELECT c."ShortName", c.sport_comment_draft
  INTO v_short, v_draft
  FROM public."Clubs" c
  WHERE c.owner_id = auth.uid()
  LIMIT 1;

  IF v_short IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_club');
  END IF;

  v_draft := nullif(btrim(coalesce(v_draft, '')), '');
  v_words := public.club_sport_comment_word_count(v_draft);

  RETURN jsonb_build_object(
    'ok', true,
    'club_short_name', v_short,
    'draft', v_draft,
    'word_count', v_words,
    'max_words', 50,
    'has_draft', v_draft IS NOT NULL
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_sport_comment_set(p_comment text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_short text;
  v_clean text;
  v_words int;
BEGIN
  SELECT c."ShortName" INTO v_short
  FROM public."Clubs" c
  WHERE c.owner_id = auth.uid()
  LIMIT 1;

  IF v_short IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_club');
  END IF;

  v_clean := nullif(btrim(regexp_replace(coalesce(p_comment, ''), '\s+', ' ', 'g')), '');

  IF v_clean IS NOT NULL THEN
    v_words := public.club_sport_comment_word_count(v_clean);
    IF v_words > 50 THEN
      RETURN jsonb_build_object(
        'ok', false,
        'reason', 'too_long',
        'word_count', v_words,
        'max_words', 50
      );
    END IF;
    IF length(v_clean) > 500 THEN
      RETURN jsonb_build_object('ok', false, 'reason', 'too_long', 'max_chars', 500);
    END IF;
  END IF;

  UPDATE public."Clubs" c
  SET sport_comment_draft = v_clean
  WHERE c."ShortName" = v_short
    AND c.owner_id = auth.uid();

  RETURN jsonb_build_object(
    'ok', true,
    'club_short_name', v_short,
    'draft', v_clean,
    'word_count', coalesce(public.club_sport_comment_word_count(v_clean), 0),
    'max_words', 50,
    'has_draft', v_clean IS NOT NULL
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Month lock: archive drafts for the month that just locked
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.gpsl_sport_capture_owner_comments(
  p_season_id bigint,
  p_gpsl_month text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_month text := lower(btrim(p_gpsl_month));
  v_captured int := 0;
BEGIN
  IF p_season_id IS NULL OR v_month IS NULL OR v_month = '' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'invalid_args');
  END IF;

  WITH drafts AS (
    SELECT
      c."ShortName" AS club_short_name,
      btrim(c.sport_comment_draft) AS comment_text,
      coalesce(
        nullif(btrim(c.owner), ''),
        nullif(btrim(public.owner_registry_resolve_tag(c.owner_id)), ''),
        'Club owner'
      ) AS owner_tag
    FROM public."Clubs" c
    WHERE c.owner_id IS NOT NULL
      AND btrim(coalesce(c.sport_comment_draft, '')) <> ''
  ),
  inserted AS (
    INSERT INTO public.gpsl_sport_owner_comments (
      season_id,
      club_short_name,
      source_gpsl_month,
      comment_text,
      owner_tag
    )
    SELECT
      p_season_id,
      d.club_short_name,
      v_month,
      d.comment_text,
      d.owner_tag
    FROM drafts d
    ON CONFLICT (season_id, club_short_name, source_gpsl_month) DO NOTHING
    RETURNING club_short_name
  )
  SELECT count(*)::int INTO v_captured FROM inserted;

  UPDATE public."Clubs" c
  SET sport_comment_draft = NULL
  WHERE btrim(coalesce(c.sport_comment_draft, '')) <> '';

  RETURN jsonb_build_object(
    'ok', true,
    'gpsl_month', v_month,
    'captured', v_captured
  );
END;
$function$;

-- Capture before generating each pending Sport edition
CREATE OR REPLACE FUNCTION public.gpsl_sport_process_pending_editions(p_season_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cal record;
  v_win record;
  v_job_key text;
  v_id bigint;
  v_results jsonb := '[]'::jsonb;
  v_capture jsonb;
BEGIN
  IF p_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_season');
  END IF;

  FOR v_cal IN
    SELECT c.gpsl_month
    FROM public.competition_season_calendar c
    WHERE c.season_id = p_season_id
      AND c.gpsl_month IS NOT NULL
      AND c.lock_at IS NOT NULL
      AND c.lock_at <= now()
    ORDER BY public.competition_gpsl_month_sort(c.gpsl_month)
  LOOP
    v_job_key := 'gpsl_sport:' || v_cal.gpsl_month;
    IF EXISTS (
      SELECT 1 FROM public.competition_season_calendar_jobs j
      WHERE j.season_id = p_season_id AND j.job_key = v_job_key
    ) THEN
      CONTINUE;
    END IF;

    IF to_regprocedure('public.gpsl_sport_capture_owner_comments(bigint,text)') IS NOT NULL THEN
      v_capture := public.gpsl_sport_capture_owner_comments(p_season_id, v_cal.gpsl_month);
    END IF;

    v_id := public.gpsl_sport_generate_edition(p_season_id, v_cal.gpsl_month);

    INSERT INTO public.competition_season_calendar_jobs (
      season_id, job_key, gpsl_month, result
    )
    VALUES (
      p_season_id, v_job_key, v_cal.gpsl_month,
      jsonb_build_object(
        'edition_id', v_id,
        'ok', v_id IS NOT NULL,
        'owner_comments', coalesce(v_capture, '{}'::jsonb)
      )
    )
    ON CONFLICT (season_id, job_key) DO UPDATE
      SET result = excluded.result, gpsl_month = excluded.gpsl_month, ran_at = now();

    v_results := v_results || jsonb_build_array(
      jsonb_build_object('gpsl_month', v_cal.gpsl_month, 'edition_id', v_id)
    );
  END LOOP;

  SELECT * INTO v_win FROM public.gpsl_sport_preseason_window(p_season_id);

  IF FOUND AND now() < v_win.august_start THEN
    IF coalesce(v_win.include_june, false) AND now() >= v_win.publish_june_at THEN
      v_job_key := 'gpsl_sport:june';
      IF NOT EXISTS (
        SELECT 1 FROM public.competition_season_calendar_jobs j
        WHERE j.season_id = p_season_id AND j.job_key = v_job_key
      ) THEN
        v_id := public.gpsl_sport_generate_edition(p_season_id, 'june');
        INSERT INTO public.competition_season_calendar_jobs (
          season_id, job_key, gpsl_month, result
        )
        VALUES (
          p_season_id, v_job_key, 'june',
          jsonb_build_object('edition_id', v_id, 'ok', v_id IS NOT NULL)
        )
        ON CONFLICT (season_id, job_key) DO UPDATE
          SET result = excluded.result, gpsl_month = excluded.gpsl_month, ran_at = now();
        v_results := v_results || jsonb_build_array(
          jsonb_build_object('gpsl_month', 'june', 'edition_id', v_id)
        );
      END IF;
    END IF;

    IF coalesce(v_win.include_july, false) AND now() >= v_win.publish_july_at THEN
      v_job_key := 'gpsl_sport:july';
      IF NOT EXISTS (
        SELECT 1 FROM public.competition_season_calendar_jobs j
        WHERE j.season_id = p_season_id AND j.job_key = v_job_key
      ) THEN
        v_id := public.gpsl_sport_generate_edition(p_season_id, 'july');
        INSERT INTO public.competition_season_calendar_jobs (
          season_id, job_key, gpsl_month, result
        )
        VALUES (
          p_season_id, v_job_key, 'july',
          jsonb_build_object('edition_id', v_id, 'ok', v_id IS NOT NULL)
        )
        ON CONFLICT (season_id, job_key) DO UPDATE
          SET result = excluded.result, gpsl_month = excluded.gpsl_month, ran_at = now();
        v_results := v_results || jsonb_build_array(
          jsonb_build_object('gpsl_month', 'july', 'edition_id', v_id)
        );
      END IF;
    END IF;
  END IF;

  RETURN jsonb_build_object('ok', true, 'processed', v_results);
END;
$function$;

GRANT EXECUTE ON FUNCTION public.club_sport_comment_get() TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_sport_comment_set(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_capture_owner_comments(bigint, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_fetch_club_news(bigint, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_process_pending_editions(bigint) TO service_role;

-- Ensure comments are captured on admin early month-end even if Sport job already ran.
CREATE OR REPLACE FUNCTION public.competition_run_month_lock_jobs(
  p_season_id bigint,
  p_force_scheduling boolean DEFAULT false,
  p_locked_gpsl_month text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_out jsonb := jsonb_build_object('ok', true, 'season_id', p_season_id);
  v_totm jsonb;
  v_sport jsonb;
  v_tv jsonb;
  v_response_track jsonb;
  v_sched_fines jsonb;
  v_response_fines jsonb;
  v_checkin_fines jsonb;
  v_last_scheduling timestamptz;
  v_run_scheduling boolean := false;
BEGIN
  IF p_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_season');
  END IF;

  IF p_locked_gpsl_month IS NOT NULL
    AND btrim(p_locked_gpsl_month) <> ''
    AND to_regprocedure('public.gpsl_sport_capture_owner_comments(bigint,text)') IS NOT NULL THEN
    v_out := v_out || jsonb_build_object(
      'gpsl_sport_owner_comments',
      public.gpsl_sport_capture_owner_comments(p_season_id, p_locked_gpsl_month)
    );
  END IF;

  IF to_regprocedure('public.competition_process_month_team_awards(bigint)') IS NOT NULL THEN
    v_totm := public.competition_process_month_team_awards(p_season_id);
    v_out := v_out || jsonb_build_object('team_of_month', v_totm);
  END IF;

  IF to_regprocedure('public.gpsl_sport_process_pending_editions(bigint)') IS NOT NULL THEN
    BEGIN
      v_sport := public.gpsl_sport_process_pending_editions(p_season_id);
      v_out := v_out || jsonb_build_object('gpsl_sport', v_sport);
    EXCEPTION
      WHEN OTHERS THEN
        v_out := v_out || jsonb_build_object(
          'gpsl_sport', jsonb_build_object('ok', false, 'error', SQLERRM)
        );
    END;
  END IF;

  IF to_regprocedure('public.competition_tv_process_month_lock_selections(bigint,text)') IS NOT NULL THEN
    v_tv := public.competition_tv_process_month_lock_selections(p_season_id, p_locked_gpsl_month);
    v_out := v_out || jsonb_build_object('tv_selection', v_tv);
  END IF;

  IF p_force_scheduling THEN
    v_run_scheduling := true;
  ELSE
    SELECT j.ran_at
    INTO v_last_scheduling
    FROM public.competition_season_calendar_jobs j
    WHERE j.season_id = p_season_id
      AND j.job_key = 'scheduling_enforcement_throttle'
    LIMIT 1;

    v_run_scheduling :=
      v_last_scheduling IS NULL
      OR v_last_scheduling < now() - interval '5 minutes';
  END IF;

  IF v_run_scheduling THEN
    IF to_regprocedure('public.competition_process_scheduling_response_deadlines(bigint)') IS NOT NULL THEN
      v_response_track := public.competition_process_scheduling_response_deadlines(p_season_id);
      v_out := v_out || jsonb_build_object('scheduling_response_deadlines', v_response_track);
    END IF;

    IF to_regprocedure('public.competition_process_scheduling_arrangement_fines(bigint)') IS NOT NULL THEN
      v_sched_fines := public.competition_process_scheduling_arrangement_fines(p_season_id);
      v_out := v_out || jsonb_build_object('scheduling_arrangement_fines', v_sched_fines);
    END IF;

    IF to_regprocedure('public.competition_process_scheduling_response_fines(bigint)') IS NOT NULL THEN
      v_response_fines := public.competition_process_scheduling_response_fines(p_season_id);
      v_out := v_out || jsonb_build_object('scheduling_response_fines', v_response_fines);
    END IF;

    IF to_regprocedure('public.competition_process_scheduling_checkin_fines(bigint)') IS NOT NULL THEN
      v_checkin_fines := public.competition_process_scheduling_checkin_fines(p_season_id);
      v_out := v_out || jsonb_build_object('scheduling_checkin_fines', v_checkin_fines);
    END IF;

    INSERT INTO public.competition_season_calendar_jobs (
      season_id, job_key, gpsl_month, result
    )
    VALUES (
      p_season_id,
      'scheduling_enforcement_throttle',
      coalesce(public.competition_active_gpsl_month(p_season_id, now()), 'none'),
      jsonb_build_object('ok', true, 'ran_at', now(), 'forced', p_force_scheduling)
    )
    ON CONFLICT (season_id, job_key) DO UPDATE
      SET result = excluded.result,
          gpsl_month = excluded.gpsl_month,
          ran_at = now();
  ELSE
    v_out := v_out || jsonb_build_object(
      'scheduling', jsonb_build_object('skipped', true, 'reason', 'throttled')
    );
  END IF;

  RETURN v_out;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.competition_run_month_lock_jobs(bigint, boolean, text) TO service_role;

NOTIFY pgrst, 'reload schema';
