-- =============================================================================
-- DEPRECATED — do not run this file after gpsl_sport_inseason_rich_edition.sql
--
-- This patch previously replaced gpsl_sport_generate_inseason_edition with the
-- legacy bare-bones generator and would UNDO the rich August–April edition.
-- The v_u bug is not present in gpsl_sport_build_inseason_month_content.
--
-- Use instead:
--   1. supabase/sql/patches/gpsl_sport_inseason_rich_edition.sql
--   2. supabase/sql/patches/gpsl_sport_inseason_refresh.sql  (rebuild existing months)
-- =============================================================================
