-- =============================================================================
-- Staff alerts (admins + mods) — e.g. new GPSL join
--
-- • gpsl_staff_alerts / gpsl_staff_alert_reads
-- • gpsl_staff_alert_notify_member_joined — called from discord-join-complete
-- • Also posts to Discord #gpsl-notifications when feed enqueue exists
--
-- Safe re-run.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.is_gpsl_admin_or_mod()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.is_gpsl_admin()
    OR (
      to_regclass('public.gpsl_site_mods') IS NOT NULL
      AND EXISTS (
        SELECT 1 FROM public.gpsl_site_mods m WHERE m.user_id = auth.uid()
      )
    );
$$;

GRANT EXECUTE ON FUNCTION public.is_gpsl_admin_or_mod() TO authenticated, service_role;

CREATE TABLE IF NOT EXISTS public.gpsl_staff_alerts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_type text NOT NULL,
  title text NOT NULL,
  body text,
  action_href text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS gpsl_staff_alerts_created_at_idx
  ON public.gpsl_staff_alerts (created_at DESC);

CREATE INDEX IF NOT EXISTS gpsl_staff_alerts_type_idx
  ON public.gpsl_staff_alerts (alert_type, created_at DESC);

CREATE TABLE IF NOT EXISTS public.gpsl_staff_alert_reads (
  alert_id bigint NOT NULL REFERENCES public.gpsl_staff_alerts (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  read_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (alert_id, user_id)
);

CREATE INDEX IF NOT EXISTS gpsl_staff_alert_reads_user_idx
  ON public.gpsl_staff_alert_reads (user_id, read_at DESC);

COMMENT ON TABLE public.gpsl_staff_alerts IS
  'In-app alerts for league admins and site mods (e.g. new member joined).';

ALTER TABLE public.gpsl_staff_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gpsl_staff_alert_reads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS gpsl_staff_alerts_select_staff ON public.gpsl_staff_alerts;
CREATE POLICY gpsl_staff_alerts_select_staff ON public.gpsl_staff_alerts
  FOR SELECT TO authenticated
  USING (public.is_gpsl_admin_or_mod());

DROP POLICY IF EXISTS gpsl_staff_alert_reads_select_own ON public.gpsl_staff_alert_reads;
CREATE POLICY gpsl_staff_alert_reads_select_own ON public.gpsl_staff_alert_reads
  FOR SELECT TO authenticated
  USING (user_id = auth.uid() AND public.is_gpsl_admin_or_mod());

DROP POLICY IF EXISTS gpsl_staff_alert_reads_insert_own ON public.gpsl_staff_alert_reads;
CREATE POLICY gpsl_staff_alert_reads_insert_own ON public.gpsl_staff_alert_reads
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() AND public.is_gpsl_admin_or_mod());

GRANT SELECT ON public.gpsl_staff_alerts TO authenticated;
GRANT SELECT, INSERT ON public.gpsl_staff_alert_reads TO authenticated;
GRANT ALL ON public.gpsl_staff_alerts TO service_role;
GRANT ALL ON public.gpsl_staff_alert_reads TO service_role;

CREATE OR REPLACE FUNCTION public.gpsl_staff_alert_create(
  p_alert_type text,
  p_title text,
  p_body text DEFAULT NULL,
  p_action_href text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb,
  p_dedupe_key text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint;
  v_meta jsonb := coalesce(p_metadata, '{}'::jsonb);
BEGIN
  IF nullif(btrim(p_alert_type), '') IS NULL OR nullif(btrim(p_title), '') IS NULL THEN
    RETURN NULL;
  END IF;

  IF p_dedupe_key IS NOT NULL THEN
    v_meta := v_meta || jsonb_build_object('dedupe_key', p_dedupe_key);
    SELECT a.id INTO v_id
    FROM public.gpsl_staff_alerts a
    WHERE a.metadata ->> 'dedupe_key' = p_dedupe_key
    LIMIT 1;
    IF v_id IS NOT NULL THEN
      RETURN v_id;
    END IF;
  END IF;

  INSERT INTO public.gpsl_staff_alerts (
    alert_type, title, body, action_href, metadata
  )
  VALUES (
    btrim(p_alert_type),
    btrim(p_title),
    nullif(btrim(coalesce(p_body, '')), ''),
    nullif(btrim(coalesce(p_action_href, '')), ''),
    v_meta
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpsl_staff_alert_notify_member_joined(
  p_owner_id uuid,
  p_email text DEFAULT NULL,
  p_owner_tag text DEFAULT NULL,
  p_discord_user_id text DEFAULT NULL,
  p_discord_username text DEFAULT NULL,
  p_discord_joined_at timestamptz DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint;
  v_tag text := coalesce(nullif(btrim(p_owner_tag), ''), '—');
  v_email text := coalesce(nullif(btrim(p_email), ''), '—');
  v_discord text := coalesce(nullif(btrim(p_discord_username), ''), nullif(btrim(p_discord_user_id), ''), '—');
  v_joined text;
  v_body text;
  v_headline text;
BEGIN
  IF p_owner_id IS NULL THEN
    RETURN NULL;
  END IF;

  v_joined := CASE
    WHEN p_discord_joined_at IS NOT NULL THEN
      to_char(p_discord_joined_at AT TIME ZONE 'Europe/London', 'Dy DD Mon YYYY HH24:MI')
    ELSE 'unknown'
  END;

  v_headline := format('New GPSL member: %s', v_tag);
  v_body := format(
    E'Owner tag: %s\nEmail: %s\nDiscord: %s\nDiscord server joined: %s (UK)\n\nThey are on the waiting list.',
    v_tag,
    v_email,
    v_discord,
    v_joined
  );

  v_id := public.gpsl_staff_alert_create(
    'member_joined',
    v_headline,
    v_body,
    'admin_owners_waiting_list.html',
    jsonb_build_object(
      'owner_id', p_owner_id,
      'email', p_email,
      'owner_tag', p_owner_tag,
      'discord_user_id', p_discord_user_id,
      'discord_username', p_discord_username,
      'discord_joined_at', p_discord_joined_at
    ),
    'member_joined:' || p_owner_id::text
  );

  -- Discord #gpsl-notifications (best-effort)
  BEGIN
    IF to_regprocedure(
      'public.gpsl_discord_feed_enqueue_notification(text,text,text,integer,text,jsonb)'
    ) IS NOT NULL THEN
      PERFORM public.gpsl_discord_feed_enqueue_notification(
        'notification',
        '🆕 ' || v_headline,
        v_body,
        5763719, -- green-ish
        'member_joined:' || p_owner_id::text,
        jsonb_build_object(
          'owner_id', p_owner_id,
          'owner_tag', p_owner_tag,
          'kind', 'member_joined',
          'channel', 'notifications'
        )
      );
    END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'member_joined Discord enqueue failed: %', SQLERRM;
  END;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpsl_staff_alerts_unread_count()
RETURNS integer
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_n integer := 0;
BEGIN
  IF v_uid IS NULL OR NOT public.is_gpsl_admin_or_mod() THEN
    RETURN 0;
  END IF;

  SELECT count(*)::integer INTO v_n
  FROM public.gpsl_staff_alerts a
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.gpsl_staff_alert_reads r
    WHERE r.alert_id = a.id AND r.user_id = v_uid
  );

  RETURN coalesce(v_n, 0);
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpsl_staff_alerts_list(p_limit int DEFAULT 50)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL OR NOT public.is_gpsl_admin_or_mod() THEN
    RAISE EXCEPTION 'Admin or mod only';
  END IF;

  RETURN coalesce(
    (
      SELECT jsonb_agg(to_jsonb(x) ORDER BY x.created_at DESC)
      FROM (
        SELECT
          a.id,
          a.alert_type,
          a.title,
          a.body,
          a.action_href,
          a.metadata,
          a.created_at,
          (r.read_at IS NOT NULL) AS is_read,
          r.read_at
        FROM public.gpsl_staff_alerts a
        LEFT JOIN public.gpsl_staff_alert_reads r
          ON r.alert_id = a.id AND r.user_id = v_uid
        ORDER BY a.created_at DESC
        LIMIT greatest(1, least(coalesce(p_limit, 50), 200))
      ) x
    ),
    '[]'::jsonb
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpsl_staff_alert_mark_read(p_alert_id bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL OR NOT public.is_gpsl_admin_or_mod() THEN
    RAISE EXCEPTION 'Admin or mod only';
  END IF;
  IF p_alert_id IS NULL THEN
    RETURN false;
  END IF;

  INSERT INTO public.gpsl_staff_alert_reads (alert_id, user_id)
  VALUES (p_alert_id, v_uid)
  ON CONFLICT (alert_id, user_id) DO NOTHING;

  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpsl_staff_alerts_mark_all_read()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_n integer := 0;
BEGIN
  IF v_uid IS NULL OR NOT public.is_gpsl_admin_or_mod() THEN
    RAISE EXCEPTION 'Admin or mod only';
  END IF;

  INSERT INTO public.gpsl_staff_alert_reads (alert_id, user_id)
  SELECT a.id, v_uid
  FROM public.gpsl_staff_alerts a
  WHERE NOT EXISTS (
    SELECT 1 FROM public.gpsl_staff_alert_reads r
    WHERE r.alert_id = a.id AND r.user_id = v_uid
  )
  ON CONFLICT (alert_id, user_id) DO NOTHING;

  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.gpsl_staff_alert_create(text, text, text, text, jsonb, text)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.gpsl_staff_alert_notify_member_joined(uuid, text, text, text, text, timestamptz)
  TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.gpsl_staff_alerts_unread_count() TO authenticated;
GRANT EXECUTE ON FUNCTION public.gpsl_staff_alerts_list(int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.gpsl_staff_alert_mark_read(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.gpsl_staff_alerts_mark_all_read() TO authenticated;

NOTIFY pgrst, 'reload schema';
