-- =============================================================================
-- GPSL waiting list — members without a club, queue ordering, admin controls
-- Run after: owner_detach_archive.sql, owner_onboarding_club_auction.sql,
--            admin_assign_club_owner.sql, admin_owner_set_tag.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------

ALTER TABLE public.gpsl_owner_registry
  DROP CONSTRAINT IF EXISTS gpsl_owner_registry_status_check;

ALTER TABLE public.gpsl_owner_registry
  ADD CONSTRAINT gpsl_owner_registry_status_check
  CHECK (status IN (
    'active',
    'member',
    'awaiting_club_auction',
    'on_absence',
    'on_break',
    'archived'
  ));

ALTER TABLE public.gpsl_owner_registry
  ADD COLUMN IF NOT EXISTS waiting_list_tier text
    CHECK (waiting_list_tier IS NULL OR waiting_list_tier IN ('standard', 'returning', 'new')),
  ADD COLUMN IF NOT EXISTS waiting_list_admin_sort integer,
  ADD COLUMN IF NOT EXISTS waiting_list_use_admin_sort boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS returned_to_list_at timestamptz,
  ADD COLUMN IF NOT EXISTS absence_note text;

COMMENT ON COLUMN public.gpsl_owner_registry.waiting_list_tier IS
  'standard = on list before a returner left; returning = ex-owner back on list; new = fresh admin add (bottom tier).';
COMMENT ON COLUMN public.gpsl_owner_registry.waiting_list_admin_sort IS
  'Lower values sort earlier when waiting_list_use_admin_sort is true.';
COMMENT ON COLUMN public.gpsl_owner_registry.waiting_list_use_admin_sort IS
  'When false, order within tier uses auth.users.created_at.';

-- Migrate legacy on_break → member (returning tier)
UPDATE public.gpsl_owner_registry r
SET status = 'member',
    waiting_list_tier = coalesce(r.waiting_list_tier, 'returning'),
    returned_to_list_at = coalesce(r.returned_to_list_at, r.status_changed_at)
WHERE r.status = 'on_break'
  AND NOT EXISTS (SELECT 1 FROM public."Clubs" c WHERE c.owner_id = r.owner_id);

-- Temporary club caretaker (long leave) — separate from waiting list
CREATE TABLE IF NOT EXISTS public.gpsl_club_caretaker (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName") ON DELETE CASCADE,
  primary_owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  caretaker_owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  starts_at timestamptz NOT NULL DEFAULT now(),
  ends_at timestamptz,
  note text,
  ended_at timestamptz,
  ended_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT gpsl_club_caretaker_distinct_owners CHECK (primary_owner_id <> caretaker_owner_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS gpsl_club_caretaker_one_active_idx
  ON public.gpsl_club_caretaker (club_short_name)
  WHERE ended_at IS NULL;

CREATE INDEX IF NOT EXISTS gpsl_club_caretaker_primary_idx
  ON public.gpsl_club_caretaker (primary_owner_id)
  WHERE ended_at IS NULL;

ALTER TABLE public.gpsl_club_caretaker ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS gpsl_club_caretaker_admin ON public.gpsl_club_caretaker;
CREATE POLICY gpsl_club_caretaker_admin ON public.gpsl_club_caretaker
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS gpsl_club_caretaker_self_select ON public.gpsl_club_caretaker;
CREATE POLICY gpsl_club_caretaker_self_select ON public.gpsl_club_caretaker
  FOR SELECT TO authenticated
  USING (
    primary_owner_id = auth.uid()
    OR caretaker_owner_id = auth.uid()
    OR public.is_gpsl_admin()
  );

-- ---------------------------------------------------------------------------
-- Sort helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.waiting_list_tier_rank(p_tier text)
RETURNS integer
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE coalesce(p_tier, 'standard')
    WHEN 'standard' THEN 1
    WHEN 'returning' THEN 2
    WHEN 'new' THEN 3
    ELSE 4
  END;
$$;

CREATE OR REPLACE FUNCTION public.waiting_list_on_list_status(p_status text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT coalesce(p_status, '') IN ('member', 'on_absence');
$$;

CREATE OR REPLACE FUNCTION public.waiting_list_account_created_at(p_owner_id uuid)
RETURNS timestamptz
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT u.created_at
  FROM auth.users u
  WHERE u.id = p_owner_id;
$$;

CREATE OR REPLACE FUNCTION public.waiting_list_clear_sort_flags()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  UPDATE public.gpsl_owner_registry r
  SET waiting_list_admin_sort = NULL,
      waiting_list_use_admin_sort = false
  WHERE public.waiting_list_on_list_status(r.status);
END;
$function$;

CREATE OR REPLACE FUNCTION public.waiting_list_rebuild_admin_sort()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_row record;
  v_sort int := 0;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  FOR v_row IN
    SELECT r.owner_id
    FROM public.gpsl_owner_registry r
    JOIN auth.users u ON u.id = r.owner_id
    WHERE public.waiting_list_on_list_status(r.status)
      AND NOT EXISTS (SELECT 1 FROM public."Clubs" c WHERE c.owner_id = r.owner_id)
    ORDER BY
      public.waiting_list_tier_rank(r.waiting_list_tier),
      CASE WHEN r.waiting_list_use_admin_sort AND r.waiting_list_admin_sort IS NOT NULL
        THEN r.waiting_list_admin_sort END NULLS LAST,
      u.created_at,
      r.owner_id
  LOOP
    v_sort := v_sort + 1000;
    UPDATE public.gpsl_owner_registry
    SET waiting_list_admin_sort = v_sort,
        waiting_list_use_admin_sort = true
    WHERE owner_id = v_row.owner_id;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.waiting_list_enqueue_new(p_owner_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  UPDATE public.gpsl_owner_registry
  SET status = 'member',
      waiting_list_tier = 'new',
      waiting_list_admin_sort = NULL,
      waiting_list_use_admin_sort = false,
      returned_to_list_at = NULL,
      absence_note = NULL,
      status_changed_at = now()
  WHERE owner_id = p_owner_id;

  IF NOT FOUND THEN
    INSERT INTO public.gpsl_owner_registry (
      owner_id, status, waiting_list_tier, status_changed_at
    )
    VALUES (p_owner_id, 'member', 'new', now());
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.waiting_list_enqueue_returning(p_owner_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  -- Everyone already waiting becomes "standard" (ahead of returners, above fresh joins).
  UPDATE public.gpsl_owner_registry
  SET waiting_list_tier = 'standard'
  WHERE public.waiting_list_on_list_status(status)
    AND waiting_list_tier = 'new'
    AND owner_id <> p_owner_id;

  UPDATE public.gpsl_owner_registry
  SET status = 'member',
      waiting_list_tier = 'returning',
      waiting_list_admin_sort = NULL,
      waiting_list_use_admin_sort = false,
      returned_to_list_at = now(),
      absence_note = NULL,
      status_changed_at = now()
  WHERE owner_id = p_owner_id;

  IF NOT FOUND THEN
    INSERT INTO public.gpsl_owner_registry (
      owner_id, status, waiting_list_tier, returned_to_list_at, status_changed_at
    )
    VALUES (p_owner_id, 'member', 'returning', now(), now());
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.waiting_list_leave_list(p_owner_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  UPDATE public.gpsl_owner_registry
  SET waiting_list_tier = NULL,
      waiting_list_admin_sort = NULL,
      waiting_list_use_admin_sort = false,
      returned_to_list_at = NULL,
      absence_note = NULL
  WHERE owner_id = p_owner_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Ordered list (internal)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.waiting_list_ordered_rows(p_include_email boolean DEFAULT false)
RETURNS TABLE (
  owner_id uuid,
  position int,
  owner_tag text,
  registry_status text,
  waiting_list_tier text,
  account_created_at timestamptz,
  email text,
  last_club_short_name text,
  absence_note text,
  returned_to_list_at timestamptz,
  pending_starting_balance numeric
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  RETURN QUERY
  WITH base AS (
    SELECT
      r.owner_id,
      coalesce(nullif(btrim(public.owner_registry_resolve_tag(r.owner_id)), ''), '—') AS owner_tag,
      r.status AS registry_status,
      r.waiting_list_tier,
      u.created_at AS account_created_at,
      CASE WHEN p_include_email THEN u.email::text ELSE NULL END AS email,
      r.last_club_short_name,
      r.absence_note,
      r.returned_to_list_at,
      r.pending_starting_balance
    FROM public.gpsl_owner_registry r
    JOIN auth.users u ON u.id = r.owner_id
    WHERE public.waiting_list_on_list_status(r.status)
      AND NOT EXISTS (SELECT 1 FROM public."Clubs" c WHERE c.owner_id = r.owner_id)
  ),
  ranked AS (
    SELECT
      b.*,
      row_number() OVER (
        ORDER BY
          public.waiting_list_tier_rank(b.waiting_list_tier),
          CASE
            WHEN EXISTS (
              SELECT 1 FROM public.gpsl_owner_registry r2
              WHERE r2.owner_id = b.owner_id
                AND r2.waiting_list_use_admin_sort
                AND r2.waiting_list_admin_sort IS NOT NULL
            ) THEN (
              SELECT r2.waiting_list_admin_sort
              FROM public.gpsl_owner_registry r2
              WHERE r2.owner_id = b.owner_id
            )
          END NULLS LAST,
          b.account_created_at,
          b.owner_id
      )::int AS position
    FROM base b
  )
  SELECT
    ranked.owner_id,
    ranked.position,
    ranked.owner_tag,
    ranked.registry_status,
    ranked.waiting_list_tier,
    ranked.account_created_at,
    ranked.email,
    ranked.last_club_short_name,
    ranked.absence_note,
    ranked.returned_to_list_at,
    ranked.pending_starting_balance
  FROM ranked
  ORDER BY ranked.position;
END;
$function$;

CREATE OR REPLACE FUNCTION public.waiting_list_public()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_rows jsonb;
  v_total int;
  v_self_pos int;
BEGIN
  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'position', w.position,
      'owner_tag', w.owner_tag,
      'status', w.registry_status
    )
    ORDER BY w.position
  ), '[]'::jsonb)
  INTO v_rows
  FROM public.waiting_list_ordered_rows(false) w;

  SELECT count(*)::int INTO v_total FROM public.waiting_list_ordered_rows(false);

  SELECT w.position INTO v_self_pos
  FROM public.waiting_list_ordered_rows(false) w
  WHERE w.owner_id = auth.uid();

  RETURN jsonb_build_object(
    'total', coalesce(v_total, 0),
    'rows', v_rows,
    'my_position', v_self_pos
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.waiting_list_admin()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_waiting jsonb;
  v_other jsonb;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'position', w.position,
      'owner_id', w.owner_id,
      'email', w.email,
      'owner_tag', w.owner_tag,
      'status', w.registry_status,
      'tier', w.waiting_list_tier,
      'account_created_at', w.account_created_at,
      'last_club_short_name', w.last_club_short_name,
      'absence_note', w.absence_note,
      'returned_to_list_at', w.returned_to_list_at,
      'pending_starting_balance', w.pending_starting_balance,
      'use_admin_sort', (
        SELECT r.waiting_list_use_admin_sort
        FROM public.gpsl_owner_registry r
        WHERE r.owner_id = w.owner_id
      )
    )
    ORDER BY w.position
  ), '[]'::jsonb)
  INTO v_waiting
  FROM public.waiting_list_ordered_rows(true) w;

  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'owner_id', r.owner_id,
      'email', u.email,
      'owner_tag', public.owner_registry_resolve_tag(r.owner_id),
      'status', r.status,
      'last_club_short_name', r.last_club_short_name
    )
    ORDER BY u.email
  ), '[]'::jsonb)
  INTO v_other
  FROM public.gpsl_owner_registry r
  JOIN auth.users u ON u.id = r.owner_id
  WHERE r.status = 'awaiting_club_auction'
    AND NOT EXISTS (SELECT 1 FROM public."Clubs" c WHERE c.owner_id = r.owner_id);

  RETURN jsonb_build_object(
    'waiting', v_waiting,
    'invited_to_auction', v_other
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Admin actions
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.admin_waiting_list_add_member(p_owner_email text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_user_id uuid;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT u.id INTO v_user_id
  FROM auth.users u
  WHERE lower(u.email) = lower(btrim(p_owner_email))
  LIMIT 1;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No auth user with email %', p_owner_email;
  END IF;

  IF EXISTS (SELECT 1 FROM public."Clubs" c WHERE c.owner_id = v_user_id) THEN
    RAISE EXCEPTION 'User already has a club';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.gpsl_owner_registry r
    WHERE r.owner_id = v_user_id AND r.status = 'archived'
  ) THEN
    RAISE EXCEPTION 'User is archived — unarchive first';
  END IF;

  PERFORM public.waiting_list_enqueue_new(v_user_id);

  RETURN jsonb_build_object(
    'ok', true,
    'owner_id', v_user_id,
    'email', p_owner_email,
    'status', 'member',
    'tier', 'new'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_waiting_list_move(
  p_owner_id uuid,
  p_direction integer
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_ids uuid[];
  v_idx int;
  v_swap int;
  v_tmp uuid;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_direction NOT IN (-1, 1) THEN
    RAISE EXCEPTION 'direction must be -1 or 1';
  END IF;

  SELECT array_agg(w.owner_id ORDER BY w.position)
  INTO v_ids
  FROM public.waiting_list_ordered_rows(false) w;

  IF v_ids IS NULL OR array_length(v_ids, 1) IS NULL THEN
    RAISE EXCEPTION 'Waiting list is empty';
  END IF;

  SELECT ord INTO v_idx
  FROM unnest(v_ids) WITH ORDINALITY AS t(owner_id, ord)
  WHERE owner_id = p_owner_id;

  IF v_idx IS NULL THEN
    RAISE EXCEPTION 'Owner is not on the waiting list';
  END IF;

  v_swap := v_idx + p_direction;
  IF v_swap < 1 OR v_swap > array_length(v_ids, 1) THEN
    RETURN jsonb_build_object('ok', true, 'moved', false, 'reason', 'already_at_edge');
  END IF;

  v_tmp := v_ids[v_idx];
  v_ids[v_idx] := v_ids[v_swap];
  v_ids[v_swap] := v_tmp;

  FOR v_idx IN 1..array_length(v_ids, 1)
  LOOP
    UPDATE public.gpsl_owner_registry
    SET waiting_list_admin_sort = v_idx * 1000,
        waiting_list_use_admin_sort = true
    WHERE owner_id = v_ids[v_idx];
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'moved', true);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_waiting_list_restore_join_order()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  PERFORM public.waiting_list_clear_sort_flags();

  RETURN jsonb_build_object('ok', true);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_waiting_list_set_absence(
  p_owner_email text,
  p_on_absence boolean,
  p_note text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_user_id uuid;
  v_status text;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT u.id INTO v_user_id
  FROM auth.users u
  WHERE lower(u.email) = lower(btrim(p_owner_email))
  LIMIT 1;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No auth user with email %', p_owner_email;
  END IF;

  v_status := CASE WHEN p_on_absence THEN 'on_absence' ELSE 'member' END;

  UPDATE public.gpsl_owner_registry
  SET status = v_status,
      absence_note = CASE WHEN p_on_absence THEN nullif(btrim(p_note), '') ELSE NULL END,
      status_changed_at = now()
  WHERE owner_id = v_user_id
    AND (public.waiting_list_on_list_status(status) OR status IN ('member', 'on_absence'));

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Owner is not on the waiting list';
  END IF;

  RETURN jsonb_build_object('ok', true, 'status', v_status);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_waiting_list_invite_auction(
  p_owner_email text,
  p_starting_balance numeric DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_user_id uuid;
  v_starting numeric;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  v_starting := greatest(coalesce(p_starting_balance, public.club_auction_default_starting_balance()), 0);

  SELECT u.id INTO v_user_id
  FROM auth.users u
  WHERE lower(u.email) = lower(btrim(p_owner_email))
  LIMIT 1;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No auth user with email %', p_owner_email;
  END IF;

  IF EXISTS (SELECT 1 FROM public."Clubs" c WHERE c.owner_id = v_user_id) THEN
    RAISE EXCEPTION 'Owner already has a club';
  END IF;

  UPDATE public.gpsl_owner_registry
  SET status = 'awaiting_club_auction',
      pending_starting_balance = v_starting,
      waiting_list_tier = NULL,
      waiting_list_admin_sort = NULL,
      waiting_list_use_admin_sort = false,
      absence_note = NULL,
      status_changed_at = now()
  WHERE owner_id = v_user_id;

  IF NOT FOUND THEN
    INSERT INTO public.gpsl_owner_registry (
      owner_id, status, pending_starting_balance, status_changed_at
    )
    VALUES (v_user_id, 'awaiting_club_auction', v_starting, now());
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'owner_id', v_user_id,
    'status', 'awaiting_club_auction',
    'pending_starting_balance', v_starting
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_waiting_list_assign_club(
  p_owner_email text,
  p_club_short_name text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_result jsonb;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  v_result := public.admin_assign_club_owner(p_owner_email, p_club_short_name);

  PERFORM public.waiting_list_leave_list((v_result->>'user_id')::uuid);

  RETURN v_result || jsonb_build_object('via', 'waiting_list_direct_assign');
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_club_caretaker_start(
  p_club_short_name text,
  p_caretaker_email text,
  p_ends_at timestamptz DEFAULT NULL,
  p_note text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := upper(btrim(p_club_short_name));
  v_caretaker uuid;
  v_primary uuid;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT c.owner_id INTO v_primary
  FROM public."Clubs" c
  WHERE c."ShortName" = v_club;

  IF v_primary IS NULL THEN
    RAISE EXCEPTION 'Club % not found or has no owner', v_club;
  END IF;

  SELECT u.id INTO v_caretaker
  FROM auth.users u
  WHERE lower(u.email) = lower(btrim(p_caretaker_email))
  LIMIT 1;

  IF v_caretaker IS NULL THEN
    RAISE EXCEPTION 'No auth user %', p_caretaker_email;
  END IF;

  UPDATE public.gpsl_club_caretaker
  SET ended_at = now(), ended_by = 'ADMIN_REPLACE'
  WHERE club_short_name = v_club AND ended_at IS NULL;

  INSERT INTO public.gpsl_club_caretaker (
    club_short_name, primary_owner_id, caretaker_owner_id, ends_at, note
  )
  VALUES (v_club, v_primary, v_caretaker, p_ends_at, nullif(btrim(p_note), ''));

  RETURN jsonb_build_object(
    'ok', true,
    'club_short_name', v_club,
    'primary_owner_id', v_primary,
    'caretaker_owner_id', v_caretaker,
    'ends_at', p_ends_at
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_club_caretaker_end(p_club_short_name text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := upper(btrim(p_club_short_name));
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  UPDATE public.gpsl_club_caretaker
  SET ended_at = now(), ended_by = 'ADMIN'
  WHERE club_short_name = v_club AND ended_at IS NULL;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No active caretaker for %', v_club;
  END IF;

  RETURN jsonb_build_object('ok', true, 'club_short_name', v_club);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Lifecycle hooks (detach, unarchive, register)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.admin_owner_detach_core(
  p_owner_id uuid,
  p_status text,
  p_note text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_club_name text;
  v_tag text;
  v_nation text;
  v_email text;
  v_final_status text;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_status NOT IN ('archived', 'member') THEN
    RAISE EXCEPTION 'Invalid detach status % (use archived or member)', p_status;
  END IF;

  SELECT c."ShortName", c."Club", nullif(btrim(c.owner), '')
  INTO v_club, v_club_name, v_tag
  FROM public."Clubs" c
  WHERE c.owner_id = p_owner_id
  LIMIT 1;

  IF v_club IS NULL THEN
    RAISE EXCEPTION 'Owner is not linked to any club';
  END IF;

  SELECT ion.nation_code INTO v_nation
  FROM public.international_owner_nations ion
  WHERE ion.club_short_name = v_club AND ion.is_active = true
  LIMIT 1;

  IF v_tag IS NULL THEN
    SELECT coalesce(nullif(btrim(r.owner_tag), ''), v_club)
    INTO v_tag
    FROM public.competition_owner_season_ranking r
    WHERE r.owner_id = p_owner_id
    ORDER BY r.season_id DESC
    LIMIT 1;
  END IF;

  SELECT u.email INTO v_email FROM auth.users u WHERE u.id = p_owner_id;

  UPDATE public."Clubs"
  SET owner_id = NULL, owner = NULL
  WHERE owner_id = p_owner_id;

  UPDATE public.international_owner_nations
  SET is_active = false, released_at = now()
  WHERE club_short_name = v_club AND is_active = true;

  UPDATE public.gpsl_club_caretaker
  SET ended_at = now(), ended_by = 'OWNER_DETACHED'
  WHERE club_short_name = v_club AND ended_at IS NULL;

  v_final_status := p_status;

  IF p_status = 'archived' THEN
    INSERT INTO public.gpsl_owner_registry (
      owner_id, status, owner_tag, last_club_short_name, last_nation_code,
      status_note, status_changed_at
    )
    VALUES (
      p_owner_id, 'archived', v_tag, v_club, v_nation,
      nullif(btrim(p_note), ''), now()
    )
    ON CONFLICT (owner_id) DO UPDATE
    SET status = 'archived',
        owner_tag = coalesce(excluded.owner_tag, gpsl_owner_registry.owner_tag),
        last_club_short_name = excluded.last_club_short_name,
        last_nation_code = excluded.last_nation_code,
        status_note = coalesce(excluded.status_note, gpsl_owner_registry.status_note),
        waiting_list_tier = NULL,
        waiting_list_admin_sort = NULL,
        waiting_list_use_admin_sort = false,
        returned_to_list_at = NULL,
        absence_note = NULL,
        status_changed_at = now();

    PERFORM public.waiting_list_leave_list(p_owner_id);
  ELSE
    INSERT INTO public.gpsl_owner_registry (
      owner_id, status, owner_tag, last_club_short_name, last_nation_code,
      status_note, status_changed_at
    )
    VALUES (
      p_owner_id, 'member', v_tag, v_club, v_nation,
      nullif(btrim(p_note), ''), now()
    )
    ON CONFLICT (owner_id) DO UPDATE
    SET owner_tag = coalesce(excluded.owner_tag, gpsl_owner_registry.owner_tag),
        last_club_short_name = excluded.last_club_short_name,
        last_nation_code = excluded.last_nation_code,
        status_note = coalesce(excluded.status_note, gpsl_owner_registry.status_note);

    PERFORM public.waiting_list_enqueue_returning(p_owner_id);
  END IF;

  RETURN jsonb_build_object(
    'owner_id', p_owner_id,
    'email', v_email,
    'status', v_final_status,
    'club_short_name', v_club,
    'club_name', v_club_name,
    'owner_tag', v_tag,
    'nation_code', v_nation
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_owner_remove_from_club(p_owner_email text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_user_id uuid;
BEGIN
  SELECT u.id INTO v_user_id
  FROM auth.users u
  WHERE lower(u.email) = lower(btrim(p_owner_email))
  LIMIT 1;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No auth user with email %', p_owner_email;
  END IF;

  RETURN public.admin_owner_detach_core(v_user_id, 'member', NULL);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_owner_unarchive(p_owner_email text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_user_id uuid;
  v_row public.gpsl_owner_registry%rowtype;
  v_email text;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT u.id INTO v_user_id
  FROM auth.users u
  WHERE lower(u.email) = lower(btrim(p_owner_email))
  LIMIT 1;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No auth user with email %', p_owner_email;
  END IF;

  SELECT * INTO v_row FROM public.gpsl_owner_registry WHERE owner_id = v_user_id;

  IF NOT FOUND OR v_row.status <> 'archived' THEN
    RAISE EXCEPTION 'Owner is not archived';
  END IF;

  IF EXISTS (SELECT 1 FROM public."Clubs" c WHERE c.owner_id = v_user_id) THEN
    RAISE EXCEPTION 'Owner is still linked to a club';
  END IF;

  PERFORM public.waiting_list_enqueue_returning(v_user_id);

  SELECT u.email INTO v_email FROM auth.users u WHERE u.id = v_user_id;

  RETURN jsonb_build_object(
    'owner_id', v_user_id,
    'email', v_email,
    'status', 'member',
    'tier', 'returning',
    'owner_tag', v_row.owner_tag,
    'last_club_short_name', v_row.last_club_short_name
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_owner_register_for_club_auction(
  p_owner_email text,
  p_starting_balance numeric DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  PERFORM public.admin_waiting_list_add_member(p_owner_email);

  RETURN jsonb_build_object(
    'ok', true,
    'email', p_owner_email,
    'status', 'member',
    'note', 'Added to bottom of waiting list. Invite to club auction when ready.'
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Self registry
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.owner_registry_get_self()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_row public.gpsl_owner_registry%rowtype;
  v_has_club boolean;
  v_tag text;
  v_pos int;
  v_total int;
  v_caretaker boolean;
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN jsonb_build_object('authenticated', false);
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public."Clubs" c WHERE c.owner_id = auth.uid()
  ) INTO v_has_club;

  SELECT EXISTS (
    SELECT 1 FROM public.gpsl_club_caretaker ct
    WHERE ct.caretaker_owner_id = auth.uid() AND ct.ended_at IS NULL
  ) INTO v_caretaker;

  SELECT * INTO v_row
  FROM public.gpsl_owner_registry
  WHERE owner_id = auth.uid();

  v_tag := public.owner_registry_resolve_tag(auth.uid());

  SELECT w.position INTO v_pos
  FROM public.waiting_list_ordered_rows(false) w
  WHERE w.owner_id = auth.uid();

  SELECT count(*)::int INTO v_total
  FROM public.waiting_list_ordered_rows(false);

  RETURN jsonb_build_object(
    'authenticated', true,
    'has_club', v_has_club,
    'status', v_row.status,
    'owner_tag', v_tag,
    'pending_starting_balance', coalesce(v_row.pending_starting_balance, 0),
    'needs_club_auction',
      NOT v_has_club
      AND coalesce(v_row.status, '') = 'awaiting_club_auction',
    'is_member',
      NOT v_has_club
      AND public.waiting_list_on_list_status(coalesce(v_row.status, '')),
    'is_archived', coalesce(v_row.status, '') = 'archived',
    'is_caretaker', v_caretaker,
    'waiting_list_position', v_pos,
    'waiting_list_total', coalesce(v_total, 0)
  );
END;
$function$;

-- Clear waiting-list fields when linking a club directly
CREATE OR REPLACE FUNCTION public.admin_assign_club_owner(
  p_owner_email text,
  p_club_short_name text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_email text := lower(trim(p_owner_email));
  v_short text := upper(trim(p_club_short_name));
  v_user_id uuid;
  v_club_name text;
  v_replaced_previous boolean := false;
  v_registry_status text;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_email IS NULL OR v_email = '' THEN
    RAISE EXCEPTION 'Owner email is required';
  END IF;

  IF v_short IS NULL OR v_short = '' THEN
    RAISE EXCEPTION 'Club ShortName is required';
  END IF;

  SELECT u.id INTO v_user_id
  FROM auth.users u
  WHERE lower(u.email) = v_email
  LIMIT 1;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No auth user with email %', p_owner_email;
  END IF;

  SELECT r.status INTO v_registry_status
  FROM public.gpsl_owner_registry r
  WHERE r.owner_id = v_user_id;

  IF v_registry_status = 'archived' THEN
    RAISE EXCEPTION 'Owner is archived — unarchive before linking to a club';
  END IF;

  SELECT c."Club" INTO v_club_name
  FROM public."Clubs" c
  WHERE c."ShortName" = v_short;

  IF v_club_name IS NULL THEN
    RAISE EXCEPTION 'Club ShortName % not found', v_short;
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM public."Clubs" c
    WHERE c."ShortName" = v_short
      AND c.owner_id IS NOT NULL
      AND c.owner_id <> v_user_id
  ) INTO v_replaced_previous;

  UPDATE public."Clubs"
  SET owner_id = NULL, owner = NULL
  WHERE owner_id = v_user_id
    AND "ShortName" <> v_short;

  UPDATE public."Clubs"
  SET owner_id = v_user_id
  WHERE "ShortName" = v_short;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Failed to update club %', v_short;
  END IF;

  INSERT INTO public.gpsl_owner_registry (owner_id, status, last_club_short_name, status_changed_at)
  VALUES (v_user_id, 'active', v_short, now())
  ON CONFLICT (owner_id) DO UPDATE
  SET status = 'active',
      last_club_short_name = v_short,
      status_note = NULL,
      waiting_list_tier = NULL,
      waiting_list_admin_sort = NULL,
      waiting_list_use_admin_sort = false,
      returned_to_list_at = NULL,
      absence_note = NULL,
      status_changed_at = now();

  PERFORM public.waiting_list_leave_list(v_user_id);

  RETURN jsonb_build_object(
    'user_id', v_user_id,
    'email', p_owner_email,
    'club_short_name', v_short,
    'club_name', v_club_name,
    'replaced_previous_owner', v_replaced_previous
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

GRANT EXECUTE ON FUNCTION public.waiting_list_public() TO authenticated;
GRANT EXECUTE ON FUNCTION public.waiting_list_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_waiting_list_add_member(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_waiting_list_move(uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_waiting_list_restore_join_order() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_waiting_list_set_absence(text, boolean, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_waiting_list_invite_auction(text, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_waiting_list_assign_club(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_club_caretaker_start(text, text, timestamptz, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_club_caretaker_end(text) TO authenticated;

NOTIFY pgrst, 'reload schema';
