-- =============================================================================
-- GPSL Bookies (play-money only)
--
-- Rules:
--   窶｢ Max stake 竄ｿ1,000 per bet
--   窶｢ One bet per owner per selection (market option)
--   窶｢ Team odds: owner rank if available, else club prestige rank
--   窶｢ Player odds: in-game stats (club-contracted players only)
--
-- Ledger:
--   bookies_expenditure  窶・stake (negative)
--   bookies_income       窶・winnings (positive)
--   Descriptions name the individual bet
--
-- Safe re-run.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Ledger entry types
-- ---------------------------------------------------------------------------
DO $ledger_types$
DECLARE
  v_list text;
BEGIN
  SELECT string_agg(quote_literal(t), ', ' ORDER BY t)
  INTO v_list
  FROM (
    SELECT DISTINCT entry_type AS t
    FROM public.competition_finance_ledger
    WHERE entry_type IS NOT NULL
    UNION
    SELECT unnest(ARRAY[
      'bookies_expenditure',
      'bookies_income'
    ])
  ) s;

  ALTER TABLE public.competition_finance_ledger
    DROP CONSTRAINT IF EXISTS competition_finance_ledger_entry_type_check;

  EXECUTE format(
    'ALTER TABLE public.competition_finance_ledger
       ADD CONSTRAINT competition_finance_ledger_entry_type_check
       CHECK (entry_type IN (%s))',
    v_list
  );
END;
$ledger_types$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bookies_markets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  market_code text NOT NULL,
  title text NOT NULL,
  market_kind text NOT NULL CHECK (market_kind IN ('club', 'player')),
  status text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'closed', 'settled', 'void')),
  result_selection_key text,
  opens_at timestamptz NOT NULL DEFAULT now(),
  closes_at timestamptz,
  settled_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bookies_markets_season_code UNIQUE (season_id, market_code)
);

CREATE TABLE IF NOT EXISTS public.bookies_selections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  market_id bigint NOT NULL REFERENCES public.bookies_markets (id) ON DELETE CASCADE,
  selection_key text NOT NULL,
  label text NOT NULL,
  odds_decimal numeric(10, 2) NOT NULL CHECK (odds_decimal >= 1.01),
  sort_order int NOT NULL DEFAULT 0,
  weight numeric NOT NULL DEFAULT 1,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bookies_selections_market_key UNIQUE (market_id, selection_key)
);

CREATE TABLE IF NOT EXISTS public.bookies_bets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  market_id bigint NOT NULL REFERENCES public.bookies_markets (id) ON DELETE CASCADE,
  selection_id bigint NOT NULL REFERENCES public.bookies_selections (id) ON DELETE RESTRICT,
  owner_id uuid NOT NULL,
  club_short_name text NOT NULL,
  stake numeric(12, 2) NOT NULL CHECK (stake > 0 AND stake <= 1000),
  odds_decimal numeric(10, 2) NOT NULL,
  potential_return numeric(14, 2) NOT NULL,
  status text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'won', 'lost', 'void', 'refunded')),
  placed_at timestamptz NOT NULL DEFAULT now(),
  settled_at timestamptz,
  ledger_stake_id bigint,
  ledger_payout_id bigint,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT bookies_bets_once_per_option UNIQUE (owner_id, market_id, selection_id)
);

CREATE INDEX IF NOT EXISTS bookies_markets_season_status_idx
  ON public.bookies_markets (season_id, status);
CREATE INDEX IF NOT EXISTS bookies_selections_market_idx
  ON public.bookies_selections (market_id);
CREATE INDEX IF NOT EXISTS bookies_bets_owner_idx
  ON public.bookies_bets (owner_id, season_id);
CREATE INDEX IF NOT EXISTS bookies_bets_market_idx
  ON public.bookies_bets (market_id, status);

ALTER TABLE public.bookies_markets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookies_selections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookies_bets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bookies_markets_read ON public.bookies_markets;
CREATE POLICY bookies_markets_read ON public.bookies_markets
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS bookies_selections_read ON public.bookies_selections;
CREATE POLICY bookies_selections_read ON public.bookies_selections
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS bookies_bets_read_own ON public.bookies_bets;
CREATE POLICY bookies_bets_read_own ON public.bookies_bets
  FOR SELECT TO authenticated
  USING (owner_id = auth.uid() OR public.is_gpsl_admin());

GRANT SELECT ON public.bookies_markets TO authenticated;
GRANT SELECT ON public.bookies_selections TO authenticated;
GRANT SELECT ON public.bookies_bets TO authenticated;

-- ---------------------------------------------------------------------------
-- Views
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.bookies_markets_public
WITH (security_invoker = true)
AS
SELECT
  m.id,
  m.season_id,
  m.market_code,
  m.title,
  m.market_kind,
  m.status,
  m.result_selection_key,
  m.opens_at,
  m.closes_at,
  m.settled_at,
  m.metadata,
  (SELECT count(*)::int FROM public.bookies_selections s WHERE s.market_id = m.id) AS selection_count
FROM public.bookies_markets m;

CREATE OR REPLACE VIEW public.bookies_selections_public
WITH (security_invoker = true)
AS
SELECT
  s.id,
  s.market_id,
  m.season_id,
  m.market_code,
  m.title AS market_title,
  m.market_kind,
  m.status AS market_status,
  s.selection_key,
  s.label,
  s.odds_decimal,
  s.sort_order,
  s.weight,
  s.metadata
FROM public.bookies_selections s
JOIN public.bookies_markets m ON m.id = s.market_id;

CREATE OR REPLACE VIEW public.bookies_my_bets_public
WITH (security_invoker = true)
AS
SELECT
  b.id,
  b.season_id,
  b.market_id,
  b.selection_id,
  b.owner_id,
  b.club_short_name,
  b.stake,
  b.odds_decimal,
  b.potential_return,
  b.status,
  b.placed_at,
  b.settled_at,
  m.market_code,
  m.title AS market_title,
  m.market_kind,
  s.selection_key,
  s.label AS selection_label
FROM public.bookies_bets b
JOIN public.bookies_markets m ON m.id = b.market_id
JOIN public.bookies_selections s ON s.id = b.selection_id
WHERE b.owner_id = auth.uid() OR public.is_gpsl_admin();

GRANT SELECT ON public.bookies_markets_public TO authenticated;
GRANT SELECT ON public.bookies_selections_public TO authenticated;
GRANT SELECT ON public.bookies_my_bets_public TO authenticated;

CREATE OR REPLACE FUNCTION public.bookies_player_rating_num(p_rating text)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT coalesce(
    nullif(regexp_replace(coalesce(p_rating, ''), '[^0-9.].*', ''), '')::numeric,
    70::numeric
  );
$$;

CREATE OR REPLACE FUNCTION public.bookies_club_strength(p_club_short_name text)
RETURNS numeric
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_owner_rank int;
  v_club_rank int;
  v_rank int;
  v_n int := 40;
BEGIN
  SELECT r.rank_position::int INTO v_owner_rank
  FROM public.competition_owner_ranking_rolling4_public r
  WHERE r.club_short_name = p_club_short_name
  ORDER BY r.rank_position
  LIMIT 1;

  SELECT p.prestige_rank::int INTO v_club_rank
  FROM public.competition_club_prestige_public p
  WHERE p.club_short_name = p_club_short_name
  LIMIT 1;

  v_rank := coalesce(v_owner_rank, v_club_rank, 25);
  SELECT greatest(coalesce(max(prestige_rank), 40), 10)::int INTO v_n
  FROM public.competition_club_prestige_public;

  RETURN greatest(1::numeric, (v_n + 1 - least(v_rank, v_n))::numeric);
END;
$function$;

CREATE OR REPLACE FUNCTION public.bookies_apply_odds_from_weights(p_market_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_sum numeric;
  v_margin numeric := 0.08;
BEGIN
  SELECT coalesce(sum(greatest(weight, 0.25)), 0) INTO v_sum
  FROM public.bookies_selections
  WHERE market_id = p_market_id;

  IF v_sum <= 0 THEN
    UPDATE public.bookies_selections
    SET odds_decimal = 10.00
    WHERE market_id = p_market_id;
    RETURN;
  END IF;

  UPDATE public.bookies_selections s
  SET odds_decimal = least(
        101.00,
        greatest(
          1.20,
          round(
            ((v_sum / greatest(s.weight, 0.25)) * (1.0 + v_margin))::numeric,
            2
          )
        )
      )
  WHERE s.market_id = p_market_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Open / refresh season markets
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_bookies_open_markets(
  p_season_id bigint DEFAULT NULL,
  p_refresh boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint := p_season_id;
  v_market_id bigint;
  v_code text;
  v_title text;
  v_kind text;
  v_created int := 0;
  v_refreshed int := 0;
  v_sel int := 0;
  r record;
  v_div text;
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;
  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No season';
  END IF;

  -- Market catalogue
  FOR r IN
    SELECT * FROM (VALUES
      ('league_sl_champion', 'Super League champion', 'club', 'superleague'),
      ('league_ch_a_champion', 'Championship A champion', 'club', 'championship_a'),
      ('league_ch_b_champion', 'Championship B champion', 'club', 'championship_b'),
      ('cup_league_cup', 'League Cup winner', 'club', NULL),
      ('cup_super8', 'Super 8 winner', 'club', NULL),
      ('cup_plate', 'Plate winner', 'club', NULL),
      ('cup_shield', 'Shield winner', 'club', NULL),
      ('cup_bowl', 'Bowl winner', 'club', NULL),
      ('scorer_overall', 'Top scorer (all divisions)', 'player', NULL),
      ('scorer_league_cup', 'League Cup top scorer', 'player', NULL),
      ('scorer_prestige', 'Prestige cups top scorer', 'player', NULL),
      ('scorer_world_cup', 'World Cup top scorer', 'player', NULL)
    ) AS t(code, title, kind, division)
  LOOP
    v_code := r.code;
    v_title := r.title;
    v_kind := r.kind;
    v_div := r.division;

    SELECT id INTO v_market_id
    FROM public.bookies_markets
    WHERE season_id = v_season_id AND market_code = v_code;

    IF v_market_id IS NULL THEN
      INSERT INTO public.bookies_markets (season_id, market_code, title, market_kind, status, metadata)
      VALUES (
        v_season_id, v_code, v_title, v_kind, 'open',
        jsonb_build_object('division', v_div, 'play_money_only', true)
      )
      RETURNING id INTO v_market_id;
      v_created := v_created + 1;
    ELSIF coalesce(p_refresh, false) THEN
      IF EXISTS (
        SELECT 1 FROM public.bookies_markets m
        WHERE m.id = v_market_id AND m.status = 'settled'
      ) THEN
        CONTINUE;
      END IF;
      DELETE FROM public.bookies_selections WHERE market_id = v_market_id;
      UPDATE public.bookies_markets
      SET title = v_title, market_kind = v_kind, updated_at = now(),
          metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('division', v_div)
      WHERE id = v_market_id;
      v_refreshed := v_refreshed + 1;
    ELSE
      CONTINUE;
    END IF;

    IF v_kind = 'club' THEN
      IF v_div IS NOT NULL THEN
        INSERT INTO public.bookies_selections (market_id, selection_key, label, odds_decimal, sort_order, weight, metadata)
        SELECT
          v_market_id,
          ccs.club_short_name,
          coalesce(c."Club", ccs.club_short_name),
          10.00,
          row_number() OVER (ORDER BY public.bookies_club_strength(ccs.club_short_name) DESC, ccs.club_short_name)::int,
          public.bookies_club_strength(ccs.club_short_name),
          jsonb_build_object('division', v_div)
        FROM public.competition_club_seasons ccs
        LEFT JOIN public."Clubs" c ON c."ShortName" = ccs.club_short_name
        WHERE ccs.season_id = v_season_id
          AND ccs.division = v_div;
      ELSE
        -- Cup markets: all clubs in active season leagues
        INSERT INTO public.bookies_selections (market_id, selection_key, label, odds_decimal, sort_order, weight, metadata)
        SELECT
          v_market_id,
          ccs.club_short_name,
          coalesce(c."Club", ccs.club_short_name),
          10.00,
          row_number() OVER (ORDER BY public.bookies_club_strength(ccs.club_short_name) DESC, ccs.club_short_name)::int,
          public.bookies_club_strength(ccs.club_short_name),
          jsonb_build_object('cup', true)
        FROM public.competition_club_seasons ccs
        LEFT JOIN public."Clubs" c ON c."ShortName" = ccs.club_short_name
        WHERE ccs.season_id = v_season_id
          AND ccs.division IN ('superleague', 'championship_a', 'championship_b');
      END IF;
    ELSE
      -- Player scorer markets (club-contracted only)
      IF v_code = 'scorer_overall' THEN
        INSERT INTO public.bookies_selections (market_id, selection_key, label, odds_decimal, sort_order, weight, metadata)
        SELECT
          v_market_id,
          x.player_id,
          x.player_name || ' (' || coalesce(x.club_short_name, '?') || ')',
          10.00,
          row_number() OVER (ORDER BY x.w DESC, x.player_name)::int,
          x.w,
          jsonb_build_object('club', x.club_short_name, 'goals', x.goals)
        FROM (
          SELECT
            p."Konami_ID"::text AS player_id,
            p."Name" AS player_name,
            public.player_contracted_club_key(p."Contracted_Team") AS club_short_name,
            coalesce(st.goals, 0) AS goals,
            greatest(0.5, coalesce(st.goals, 0)::numeric * 3 + coalesce(st.appearances, 0)::numeric * 0.15
              + public.bookies_player_rating_num(p."Rating"::text) / 40.0) AS w
          FROM public."Players" p
          LEFT JOIN public.competition_player_season_stats_public st
            ON st.player_id = p."Konami_ID"::text
           AND st.season_id = v_season_id
          WHERE public.player_contracted_club_key(p."Contracted_Team") IS NOT NULL AND btrim(public.player_contracted_club_key(p."Contracted_Team")) <> ''
            AND EXISTS (
              SELECT 1 FROM public."Clubs" c WHERE c."ShortName" = public.player_contracted_club_key(p."Contracted_Team")
            )
          ORDER BY w DESC, p."Name"
          LIMIT 40
        ) x;
      ELSIF v_code = 'scorer_league_cup' THEN
        INSERT INTO public.bookies_selections (market_id, selection_key, label, odds_decimal, sort_order, weight, metadata)
        SELECT
          v_market_id,
          x.player_id,
          x.player_name || ' (' || coalesce(x.club_short_name, '?') || ')',
          10.00,
          row_number() OVER (ORDER BY x.w DESC, x.player_name)::int,
          x.w,
          jsonb_build_object('club', x.club_short_name, 'cup_goals', x.goals)
        FROM (
          SELECT
            m.player_id,
            max(p."Name") AS player_name,
            max(m.club_short_name) AS club_short_name,
            coalesce(sum(m.goals), 0)::int AS goals,
            greatest(
              0.5,
              coalesce(sum(m.goals), 0)::numeric * 4
                + public.bookies_player_rating_num(max(p."Rating"::text)) / 50.0
            ) AS w
          FROM public.competition_match_player_stats m
          JOIN public.competition_fixtures f ON f.id = m.fixture_id
          JOIN public."Players" p ON p."Konami_ID"::text = m.player_id
          WHERE m.season_id = v_season_id
            AND f.status = 'played'
            AND f.competition_type = 'cup'
            AND lower(coalesce(f.cup_code, '')) = 'league_cup'
            AND public.player_contracted_club_key(p."Contracted_Team") IS NOT NULL AND btrim(public.player_contracted_club_key(p."Contracted_Team")) <> ''
          GROUP BY m.player_id
          ORDER BY w DESC
          LIMIT 40
        ) x;
        -- Fallback if no cup goals yet: rating-based pool
        IF (SELECT count(*) FROM public.bookies_selections WHERE market_id = v_market_id) = 0 THEN
          INSERT INTO public.bookies_selections (market_id, selection_key, label, odds_decimal, sort_order, weight, metadata)
          SELECT
            v_market_id,
            p."Konami_ID"::text,
            p."Name" || ' (' || public.player_contracted_club_key(p."Contracted_Team") || ')',
            10.00,
            row_number() OVER (ORDER BY public.bookies_player_rating_num(p."Rating"::text) DESC, p."Name")::int,
            greatest(0.5, public.bookies_player_rating_num(p."Rating"::text) / 40.0),
            jsonb_build_object('club', public.player_contracted_club_key(p."Contracted_Team"), 'fallback', true)
          FROM public."Players" p
          WHERE public.player_contracted_club_key(p."Contracted_Team") IS NOT NULL AND btrim(public.player_contracted_club_key(p."Contracted_Team")) <> ''
            AND EXISTS (SELECT 1 FROM public."Clubs" c WHERE c."ShortName" = public.player_contracted_club_key(p."Contracted_Team"))
          ORDER BY public.bookies_player_rating_num(p."Rating"::text) DESC
          LIMIT 40;
        END IF;
      ELSIF v_code = 'scorer_prestige' THEN
        INSERT INTO public.bookies_selections (market_id, selection_key, label, odds_decimal, sort_order, weight, metadata)
        SELECT
          v_market_id,
          x.player_id,
          x.player_name || ' (' || coalesce(x.club_short_name, '?') || ')',
          10.00,
          row_number() OVER (ORDER BY x.w DESC, x.player_name)::int,
          x.w,
          jsonb_build_object('club', x.club_short_name, 'prestige_goals', x.goals)
        FROM (
          SELECT
            m.player_id,
            max(p."Name") AS player_name,
            max(m.club_short_name) AS club_short_name,
            coalesce(sum(m.goals), 0)::int AS goals,
            greatest(
              0.5,
              coalesce(sum(m.goals), 0)::numeric * 4
                + public.bookies_player_rating_num(max(p."Rating"::text)) / 50.0
            ) AS w
          FROM public.competition_match_player_stats m
          JOIN public.competition_fixtures f ON f.id = m.fixture_id
          JOIN public."Players" p ON p."Konami_ID"::text = m.player_id
          WHERE m.season_id = v_season_id
            AND f.status = 'played'
            AND f.competition_type = 'cup'
            AND lower(coalesce(f.cup_code, '')) IN ('super8', 'plate', 'shield', 'bowl')
            AND public.player_contracted_club_key(p."Contracted_Team") IS NOT NULL AND btrim(public.player_contracted_club_key(p."Contracted_Team")) <> ''
          GROUP BY m.player_id
          ORDER BY w DESC
          LIMIT 40
        ) x;
        IF (SELECT count(*) FROM public.bookies_selections WHERE market_id = v_market_id) = 0 THEN
          INSERT INTO public.bookies_selections (market_id, selection_key, label, odds_decimal, sort_order, weight, metadata)
          SELECT
            v_market_id,
            p."Konami_ID"::text,
            p."Name" || ' (' || public.player_contracted_club_key(p."Contracted_Team") || ')',
            10.00,
            row_number() OVER (ORDER BY public.bookies_player_rating_num(p."Rating"::text) DESC, p."Name")::int,
            greatest(0.5, public.bookies_player_rating_num(p."Rating"::text) / 40.0),
            jsonb_build_object('club', public.player_contracted_club_key(p."Contracted_Team"), 'fallback', true)
          FROM public."Players" p
          WHERE public.player_contracted_club_key(p."Contracted_Team") IS NOT NULL AND btrim(public.player_contracted_club_key(p."Contracted_Team")) <> ''
            AND EXISTS (SELECT 1 FROM public."Clubs" c WHERE c."ShortName" = public.player_contracted_club_key(p."Contracted_Team"))
          ORDER BY public.bookies_player_rating_num(p."Rating"::text) DESC
          LIMIT 40;
        END IF;
      ELSIF v_code = 'scorer_world_cup' THEN
        INSERT INTO public.bookies_selections (market_id, selection_key, label, odds_decimal, sort_order, weight, metadata)
        SELECT
          v_market_id,
          p."Konami_ID"::text,
          p."Name" || ' (' || public.player_contracted_club_key(p."Contracted_Team") || ')',
          10.00,
          row_number() OVER (
            ORDER BY coalesce(ipc.goals, 0) DESC,
                     public.bookies_player_rating_num(p."Rating"::text) DESC,
                     p."Name"
          )::int,
          greatest(
            0.5,
            coalesce(ipc.goals, 0)::numeric * 2
              + coalesce(ipc.caps, 0)::numeric * 0.05
              + public.bookies_player_rating_num(p."Rating"::text) / 50.0
          ),
          jsonb_build_object(
            'club', public.player_contracted_club_key(p."Contracted_Team"),
            'intl_goals', coalesce(ipc.goals, 0),
            'caps', coalesce(ipc.caps, 0)
          )
        FROM public."Players" p
        LEFT JOIN public.international_player_career ipc
          ON ipc.player_id = p."Konami_ID"::text
        WHERE public.player_contracted_club_key(p."Contracted_Team") IS NOT NULL AND btrim(public.player_contracted_club_key(p."Contracted_Team")) <> ''
          AND EXISTS (SELECT 1 FROM public."Clubs" c WHERE c."ShortName" = public.player_contracted_club_key(p."Contracted_Team"))
        ORDER BY coalesce(ipc.goals, 0) DESC, public.bookies_player_rating_num(p."Rating"::text) DESC
        LIMIT 40;
      END IF;
    END IF;

    PERFORM public.bookies_apply_odds_from_weights(v_market_id);
    SELECT count(*) INTO v_sel FROM public.bookies_selections WHERE market_id = v_market_id;
  END LOOP;

  RETURN jsonb_build_object(
    'ok', true,
    'season_id', v_season_id,
    'created_markets', v_created,
    'refreshed_markets', v_refreshed,
    'note', 'Play-money only. Max 竄ｿ1,000 / one bet per selection.'
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Place bet
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.bookies_place_bet(
  p_selection_id bigint,
  p_stake numeric
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_club text;
  v_sel public.bookies_selections%rowtype;
  v_mkt public.bookies_markets%rowtype;
  v_stake numeric := round(coalesce(p_stake, 0)::numeric, 2);
  v_bet_id bigint;
  v_ledger bigint;
  v_ret numeric;
  v_desc text;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  v_club := public.my_club_shortname();
  IF v_club IS NULL OR btrim(v_club) = '' THEN
    RAISE EXCEPTION 'No club linked to your account';
  END IF;

  IF v_stake IS NULL OR v_stake <= 0 THEN
    RAISE EXCEPTION 'Stake must be greater than zero';
  END IF;
  IF v_stake > 1000 THEN
    RAISE EXCEPTION 'Maximum stake is 竄ｿ1,000 per bet';
  END IF;

  SELECT * INTO v_sel FROM public.bookies_selections WHERE id = p_selection_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Selection not found';
  END IF;

  SELECT * INTO v_mkt FROM public.bookies_markets WHERE id = v_sel.market_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Market not found';
  END IF;

  IF v_mkt.status <> 'open' THEN
    RAISE EXCEPTION 'Market is not open for betting';
  END IF;
  IF v_mkt.closes_at IS NOT NULL AND v_mkt.closes_at <= now() THEN
    RAISE EXCEPTION 'Market betting window has closed';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.bookies_bets b
    WHERE b.owner_id = v_uid
      AND b.market_id = v_mkt.id
      AND b.selection_id = v_sel.id
  ) THEN
    RAISE EXCEPTION 'You already have a bet on this option (one per selection)';
  END IF;

  v_ret := round(v_stake * v_sel.odds_decimal, 2);
  v_desc := format(
    'Bookies stake: %s 窶・%s @ %s (stake 竄ｿ%s)',
    v_mkt.title,
    v_sel.label,
    to_char(v_sel.odds_decimal, 'FM999999990.00'),
    to_char(v_stake, 'FM999999990.00')
  );

  v_ledger := public.post_club_ledger(
    v_club,
    'bookies_expenditure',
    -abs(v_stake),
    v_desc,
    jsonb_build_object(
      'bookies', true,
      'market_id', v_mkt.id,
      'selection_id', v_sel.id,
      'market_code', v_mkt.market_code,
      'odds', v_sel.odds_decimal,
      'stake', v_stake
    ),
    v_mkt.season_id,
    NULL,
    false,
    true
  );

  INSERT INTO public.bookies_bets (
    season_id, market_id, selection_id, owner_id, club_short_name,
    stake, odds_decimal, potential_return, status, ledger_stake_id, metadata
  )
  VALUES (
    v_mkt.season_id, v_mkt.id, v_sel.id, v_uid, v_club,
    v_stake, v_sel.odds_decimal, v_ret, 'open', v_ledger,
    jsonb_build_object('selection_label', v_sel.label, 'market_title', v_mkt.title)
  )
  RETURNING id INTO v_bet_id;

  RETURN jsonb_build_object(
    'ok', true,
    'bet_id', v_bet_id,
    'stake', v_stake,
    'odds', v_sel.odds_decimal,
    'potential_return', v_ret,
    'ledger_id', v_ledger
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Settle market
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.bookies_settle_market(
  p_market_id bigint,
  p_result_selection_key text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_mkt public.bookies_markets%rowtype;
  v_bet record;
  v_won int := 0;
  v_lost int := 0;
  v_paid numeric := 0;
  v_ledger bigint;
  v_desc text;
  v_key text := btrim(coalesce(p_result_selection_key, ''));
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_key = '' THEN
    RAISE EXCEPTION 'Result selection key required';
  END IF;

  SELECT * INTO v_mkt FROM public.bookies_markets WHERE id = p_market_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Market not found';
  END IF;
  IF v_mkt.status = 'settled' THEN
    RETURN jsonb_build_object('ok', true, 'already_settled', true, 'market_id', p_market_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.bookies_selections
    WHERE market_id = p_market_id AND selection_key = v_key
  ) THEN
    RAISE EXCEPTION 'Result key % is not a selection on this market', v_key;
  END IF;

  FOR v_bet IN
    SELECT b.*, s.label AS sel_label, s.selection_key
    FROM public.bookies_bets b
    JOIN public.bookies_selections s ON s.id = b.selection_id
    WHERE b.market_id = p_market_id AND b.status = 'open'
    ORDER BY b.id
    FOR UPDATE OF b
  LOOP
    IF v_bet.selection_key = v_key THEN
      v_desc := format(
        'Bookies win: %s 窶・%s @ %s (stake 竄ｿ%s, return 竄ｿ%s)',
        v_mkt.title,
        v_bet.sel_label,
        to_char(v_bet.odds_decimal, 'FM999999990.00'),
        to_char(v_bet.stake, 'FM999999990.00'),
        to_char(v_bet.potential_return, 'FM999999990.00')
      );
      v_ledger := public.post_club_ledger(
        v_bet.club_short_name,
        'bookies_income',
        abs(v_bet.potential_return),
        v_desc,
        jsonb_build_object(
          'bookies', true,
          'bet_id', v_bet.id,
          'market_id', v_mkt.id,
          'won', true
        ),
        v_mkt.season_id,
        NULL,
        false,
        true
      );
      UPDATE public.bookies_bets
      SET status = 'won',
          settled_at = now(),
          ledger_payout_id = v_ledger
      WHERE id = v_bet.id;
      v_won := v_won + 1;
      v_paid := v_paid + v_bet.potential_return;
    ELSE
      UPDATE public.bookies_bets
      SET status = 'lost', settled_at = now()
      WHERE id = v_bet.id;
      v_lost := v_lost + 1;
    END IF;
  END LOOP;

  UPDATE public.bookies_markets
  SET status = 'settled',
      result_selection_key = v_key,
      settled_at = now(),
      updated_at = now()
  WHERE id = p_market_id;

  RETURN jsonb_build_object(
    'ok', true,
    'market_id', p_market_id,
    'result', v_key,
    'won', v_won,
    'lost', v_lost,
    'paid_out', v_paid
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_bookies_close_market(p_market_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  UPDATE public.bookies_markets
  SET status = 'closed', closes_at = coalesce(closes_at, now()), updated_at = now()
  WHERE id = p_market_id AND status = 'open';

  RETURN jsonb_build_object('ok', true, 'market_id', p_market_id);
END;
$function$;

GRANT EXECUTE ON FUNCTION public.bookies_player_rating_num(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.bookies_club_strength(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.bookies_apply_odds_from_weights(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_bookies_open_markets(bigint, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.bookies_place_bet(bigint, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.bookies_settle_market(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_bookies_close_market(bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';
