-- =============================================================================
-- World Cup competition engine
--
-- Cycle admin, seeded pot draws, qual/finals fixtures, standings updates,
-- best-third qualification, knockout progression, post-WC re-selection.
--
-- Run once in Supabase SQL Editor. Safe re-run.
-- Prerequisite: competition_international.sql (+ seed_rank / career patches).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Schema extensions on international_fixtures
-- ---------------------------------------------------------------------------

ALTER TABLE public.international_fixtures
  ADD COLUMN IF NOT EXISTS match_no smallint;

ALTER TABLE public.international_fixtures
  ADD COLUMN IF NOT EXISTS gpsl_month text;

ALTER TABLE public.international_fixtures
  ADD COLUMN IF NOT EXISTS week_in_month smallint;

ALTER TABLE public.international_fixtures
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'scheduled';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'international_fixtures_status_chk'
  ) THEN
    ALTER TABLE public.international_fixtures
      ADD CONSTRAINT international_fixtures_status_chk
      CHECK (status IN ('scheduled', 'played', 'void'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS international_fixtures_cycle_phase_idx
  ON public.international_fixtures (cycle_id, phase, match_no);

CREATE INDEX IF NOT EXISTS international_fixtures_season_idx
  ON public.international_fixtures (season_id)
  WHERE season_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS international_fixtures_nations_idx
  ON public.international_fixtures (home_nation, away_nation);

-- ---------------------------------------------------------------------------
-- Result submissions (mirror club pattern; keyed by nation owners)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_result_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fixture_id bigint NOT NULL REFERENCES public.international_fixtures (id) ON DELETE CASCADE,
  submitted_by_nation text NOT NULL REFERENCES public.international_nations (code),
  home_goals smallint NOT NULL CHECK (home_goals >= 0),
  away_goals smallint NOT NULL CHECK (away_goals >= 0),
  home_goals_et smallint,
  away_goals_et smallint,
  home_pens smallint,
  away_pens smallint,
  player_stats jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'confirmed', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);

CREATE INDEX IF NOT EXISTS international_result_submissions_fixture_idx
  ON public.international_result_submissions (fixture_id, status);

ALTER TABLE public.international_result_submissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS international_result_submissions_read ON public.international_result_submissions;
CREATE POLICY international_result_submissions_read
  ON public.international_result_submissions
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS international_result_submissions_admin ON public.international_result_submissions;
CREATE POLICY international_result_submissions_admin
  ON public.international_result_submissions
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.international_result_submissions TO authenticated;

-- ---------------------------------------------------------------------------
-- Nation matchday default squad / formations (per nation, like club)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_matchday_squad (
  nation_code text NOT NULL PRIMARY KEY
    REFERENCES public.international_nations (code) ON DELETE CASCADE,
  pitch_layout jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.international_matchday_squad_player (
  nation_code text NOT NULL
    REFERENCES public.international_matchday_squad (nation_code) ON DELETE CASCADE,
  player_id text NOT NULL,
  slot_kind text NOT NULL,
  pitch_slot text,
  sort_order smallint NOT NULL DEFAULT 0,
  CONSTRAINT international_matchday_squad_player_kind_chk
    CHECK (slot_kind IN ('pitch', 'bench', 'reserve')),
  CONSTRAINT international_matchday_squad_player_pitch_chk
    CHECK (
      (slot_kind = 'pitch' AND pitch_slot IS NOT NULL)
      OR (slot_kind <> 'pitch' AND pitch_slot IS NULL)
    ),
  CONSTRAINT international_matchday_squad_player_unique UNIQUE (nation_code, player_id),
  CONSTRAINT international_matchday_squad_pitch_slot_unique UNIQUE (nation_code, pitch_slot)
);

CREATE INDEX IF NOT EXISTS international_matchday_squad_player_nation_idx
  ON public.international_matchday_squad_player (nation_code, slot_kind, sort_order);

ALTER TABLE public.international_matchday_squad ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_matchday_squad_player ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS international_matchday_squad_read ON public.international_matchday_squad;
CREATE POLICY international_matchday_squad_read ON public.international_matchday_squad
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS international_matchday_squad_owner ON public.international_matchday_squad;
CREATE POLICY international_matchday_squad_owner ON public.international_matchday_squad
  FOR ALL TO authenticated
  USING (nation_code = public.international_my_nation_code() OR public.is_gpsl_admin())
  WITH CHECK (nation_code = public.international_my_nation_code() OR public.is_gpsl_admin());

DROP POLICY IF EXISTS international_matchday_squad_player_read ON public.international_matchday_squad_player;
CREATE POLICY international_matchday_squad_player_read ON public.international_matchday_squad_player
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS international_matchday_squad_player_owner ON public.international_matchday_squad_player;
CREATE POLICY international_matchday_squad_player_owner ON public.international_matchday_squad_player
  FOR ALL TO authenticated
  USING (nation_code = public.international_my_nation_code() OR public.is_gpsl_admin())
  WITH CHECK (nation_code = public.international_my_nation_code() OR public.is_gpsl_admin());

GRANT SELECT ON public.international_matchday_squad TO authenticated;
GRANT SELECT ON public.international_matchday_squad_player TO authenticated;

-- ---------------------------------------------------------------------------
-- Fixture schedule (propose / accept kickoff between nation owners)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_fixture_schedule (
  fixture_id bigint PRIMARY KEY
    REFERENCES public.international_fixtures (id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'unscheduled'
    CHECK (status IN ('unscheduled', 'negotiating', 'agreed')),
  home_proposal_count smallint NOT NULL DEFAULT 0,
  away_proposal_count smallint NOT NULL DEFAULT 0,
  agreed_kickoff_at timestamptz,
  pending_proposal_id bigint,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.international_fixture_schedule_proposal (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fixture_id bigint NOT NULL
    REFERENCES public.international_fixtures (id) ON DELETE CASCADE,
  proposed_by_nation text NOT NULL REFERENCES public.international_nations (code),
  kickoff_at timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted', 'superseded', 'withdrawn')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS international_fixture_schedule_proposal_fix_idx
  ON public.international_fixture_schedule_proposal (fixture_id, status);

ALTER TABLE public.international_fixture_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_fixture_schedule_proposal ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS international_fixture_schedule_read ON public.international_fixture_schedule;
CREATE POLICY international_fixture_schedule_read ON public.international_fixture_schedule
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS international_fixture_schedule_admin ON public.international_fixture_schedule;
CREATE POLICY international_fixture_schedule_admin ON public.international_fixture_schedule
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin()) WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS international_fixture_schedule_proposal_read
  ON public.international_fixture_schedule_proposal;
CREATE POLICY international_fixture_schedule_proposal_read
  ON public.international_fixture_schedule_proposal
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS international_fixture_schedule_proposal_admin
  ON public.international_fixture_schedule_proposal;
CREATE POLICY international_fixture_schedule_proposal_admin
  ON public.international_fixture_schedule_proposal
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin()) WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.international_fixture_schedule TO authenticated;
GRANT SELECT ON public.international_fixture_schedule_proposal TO authenticated;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.international_club_for_nation(p_nation text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT o.club_short_name
  FROM public.international_owner_nations o
  WHERE o.nation_code = upper(btrim(p_nation))
    AND o.is_active = true
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.international_assert_cycle_admin(p_cycle_id bigint)
RETURNS public.international_wc_cycles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cycle public.international_wc_cycles;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_cycle
  FROM public.international_wc_cycles
  WHERE id = p_cycle_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'World Cup cycle % not found', p_cycle_id;
  END IF;

  RETURN v_cycle;
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_shuffle_text_array(p_arr text[])
RETURNS text[]
LANGUAGE plpgsql
VOLATILE
AS $function$
DECLARE
  v_i int;
  v_j int;
  v_tmp text;
  v_arr text[] := p_arr;
BEGIN
  IF v_arr IS NULL OR array_length(v_arr, 1) IS NULL THEN
    RETURN v_arr;
  END IF;
  FOR v_i IN REVERSE array_length(v_arr, 1)..2 LOOP
    v_j := 1 + floor(random() * v_i)::int;
    v_tmp := v_arr[v_i];
    v_arr[v_i] := v_arr[v_j];
    v_arr[v_j] := v_tmp;
  END LOOP;
  RETURN v_arr;
END;
$function$;

-- Map qual match_no 1..10 onto GPSL months (spread through a season)
CREATE OR REPLACE FUNCTION public.international_qual_match_calendar(p_match_no integer)
RETURNS TABLE (gpsl_month text, week_in_month smallint)
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT
    CASE
      WHEN p_match_no BETWEEN 1 AND 2 THEN 'august'
      WHEN p_match_no BETWEEN 3 AND 4 THEN 'october'
      WHEN p_match_no BETWEEN 5 AND 6 THEN 'november'
      WHEN p_match_no BETWEEN 7 AND 8 THEN 'february'
      WHEN p_match_no BETWEEN 9 AND 10 THEN 'april'
      ELSE 'may'
    END,
    CASE
      WHEN p_match_no IN (1, 3, 5, 7, 9) THEN 1::smallint
      ELSE 3::smallint
    END;
$$;

-- ---------------------------------------------------------------------------
-- Cycle admin
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.international_admin_create_wc_cycle(
  p_label text,
  p_qual_season_id_1 bigint,
  p_qual_season_id_2 bigint,
  p_finals_after_season_id bigint,
  p_cycle_no smallint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_no smallint;
  v_id bigint;
  v_label text := nullif(btrim(p_label), '');
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_label IS NULL THEN
    RAISE EXCEPTION 'Label required';
  END IF;

  IF p_qual_season_id_1 IS NULL OR p_qual_season_id_2 IS NULL OR p_finals_after_season_id IS NULL THEN
    RAISE EXCEPTION 'Qualifying season 1, season 2, and finals-after season are required';
  END IF;

  IF p_qual_season_id_1 = p_qual_season_id_2 THEN
    RAISE EXCEPTION 'Qualifying seasons must be different';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.competition_seasons WHERE id = p_qual_season_id_1) THEN
    RAISE EXCEPTION 'Qualifying season 1 not found';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.competition_seasons WHERE id = p_qual_season_id_2) THEN
    RAISE EXCEPTION 'Qualifying season 2 not found';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.competition_seasons WHERE id = p_finals_after_season_id) THEN
    RAISE EXCEPTION 'Finals-after season not found';
  END IF;

  IF p_cycle_no IS NOT NULL THEN
    v_no := p_cycle_no;
  ELSE
    SELECT coalesce(max(cycle_no), 0) + 1 INTO v_no FROM public.international_wc_cycles;
  END IF;

  INSERT INTO public.international_wc_cycles (
    cycle_no, label, qual_season_id_1, qual_season_id_2, finals_after_season_id, status
  )
  VALUES (
    v_no, v_label, p_qual_season_id_1, p_qual_season_id_2, p_finals_after_season_id, 'setup'
  )
  RETURNING id INTO v_id;

  RETURN jsonb_build_object(
    'ok', true,
    'cycle_id', v_id,
    'cycle_no', v_no,
    'label', v_label,
    'status', 'setup'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_admin_update_wc_cycle(
  p_cycle_id bigint,
  p_label text DEFAULT NULL,
  p_qual_season_id_1 bigint DEFAULT NULL,
  p_qual_season_id_2 bigint DEFAULT NULL,
  p_finals_after_season_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cycle public.international_wc_cycles;
BEGIN
  v_cycle := public.international_assert_cycle_admin(p_cycle_id);

  IF v_cycle.status NOT IN ('setup', 'qualifying') THEN
    RAISE EXCEPTION 'Can only edit seasons/label while cycle is setup or qualifying';
  END IF;

  UPDATE public.international_wc_cycles
  SET label = coalesce(nullif(btrim(p_label), ''), label),
      qual_season_id_1 = coalesce(p_qual_season_id_1, qual_season_id_1),
      qual_season_id_2 = coalesce(p_qual_season_id_2, qual_season_id_2),
      finals_after_season_id = coalesce(p_finals_after_season_id, finals_after_season_id)
  WHERE id = p_cycle_id
  RETURNING * INTO v_cycle;

  RETURN jsonb_build_object(
    'ok', true,
    'cycle_id', v_cycle.id,
    'cycle_no', v_cycle.cycle_no,
    'label', v_cycle.label,
    'status', v_cycle.status
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_admin_set_wc_cycle_status(
  p_cycle_id bigint,
  p_status text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cycle public.international_wc_cycles;
  v_status text := lower(btrim(p_status));
BEGIN
  v_cycle := public.international_assert_cycle_admin(p_cycle_id);

  IF v_status NOT IN ('setup', 'qualifying', 'finals', 'complete') THEN
    RAISE EXCEPTION 'Invalid status';
  END IF;

  -- Soft guards (admin can still force via known transitions)
  IF v_cycle.status = 'setup' AND v_status = 'qualifying' THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.international_qual_groups g WHERE g.cycle_id = p_cycle_id
    ) THEN
      RAISE EXCEPTION 'Draw qualifying groups before starting qualifying';
    END IF;
  ELSIF v_cycle.status = 'qualifying' AND v_status = 'finals' THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.international_finals_groups g WHERE g.cycle_id = p_cycle_id
    ) THEN
      RAISE EXCEPTION 'Draw finals groups (after qualification) before starting finals';
    END IF;
  ELSIF v_status = 'complete' THEN
    -- allow from finals
    NULL;
  END IF;

  UPDATE public.international_wc_cycles
  SET status = v_status
  WHERE id = p_cycle_id
  RETURNING * INTO v_cycle;

  RETURN jsonb_build_object(
    'ok', true,
    'cycle_id', v_cycle.id,
    'status', v_cycle.status
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Qualifying draw — pots by seed_rank (1–12, 13–24, …), one from each pot per group
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.international_admin_draw_qual_groups(p_cycle_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cycle public.international_wc_cycles;
  v_nations text[];
  v_pot text[];
  v_groups text[] := ARRAY['A','B','C','D','E','F','G','H','I','J','K','L'];
  v_group_ids bigint[] := ARRAY[]::bigint[];
  v_gid bigint;
  v_i int;
  v_pot_no int;
  v_code text;
BEGIN
  v_cycle := public.international_assert_cycle_admin(p_cycle_id);

  IF v_cycle.status NOT IN ('setup', 'qualifying') THEN
    RAISE EXCEPTION 'Qualifying draw only allowed in setup/qualifying';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.international_fixtures f
    WHERE f.cycle_id = p_cycle_id AND f.phase = 'qualifying' AND f.played = true
  ) THEN
    RAISE EXCEPTION 'Cannot re-draw: qualifying fixtures already played';
  END IF;

  -- 60 owner-assigned active nations, ordered by seed strength
  SELECT array_agg(x.code ORDER BY x.seed_rank, x.code)
  INTO v_nations
  FROM (
    SELECT n.code, n.seed_rank
    FROM public.international_owner_nations o
    JOIN public.international_nations n ON n.code = o.nation_code
    WHERE o.is_active = true
      AND n.active = true
    ORDER BY n.seed_rank ASC, n.code ASC
    LIMIT 60
  ) x;

  IF v_nations IS NULL OR array_length(v_nations, 1) <> 60 THEN
    RAISE EXCEPTION
      'Need exactly 60 active owner nations for qualifying draw (have %)',
      coalesce(array_length(v_nations, 1), 0);
  END IF;

  -- Clear previous draw + unplayed fixtures for this cycle (qual only)
  DELETE FROM public.international_fixtures
  WHERE cycle_id = p_cycle_id AND phase = 'qualifying';

  DELETE FROM public.international_qual_group_members m
  USING public.international_qual_groups g
  WHERE m.group_id = g.id AND g.cycle_id = p_cycle_id;

  DELETE FROM public.international_qual_groups WHERE cycle_id = p_cycle_id;

  FOREACH v_code IN ARRAY v_groups LOOP
    INSERT INTO public.international_qual_groups (cycle_id, group_code)
    VALUES (p_cycle_id, v_code)
    RETURNING id INTO v_gid;
    v_group_ids := v_group_ids || v_gid;
  END LOOP;

  -- Pot 1..5: shuffle each pot, assign index i → group i
  FOR v_pot_no IN 1..5 LOOP
    v_pot := v_nations[((v_pot_no - 1) * 12 + 1):(v_pot_no * 12)];
    v_pot := public.international_shuffle_text_array(v_pot);
    FOR v_i IN 1..12 LOOP
      INSERT INTO public.international_qual_group_members (group_id, nation_code)
      VALUES (v_group_ids[v_i], v_pot[v_i]);
    END LOOP;
  END LOOP;

  IF v_cycle.status = 'setup' THEN
    UPDATE public.international_wc_cycles SET status = 'qualifying' WHERE id = p_cycle_id;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'cycle_id', p_cycle_id,
    'groups', 12,
    'nations', 60,
    'status', 'qualifying'
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Qualifying fixtures — double round-robin per group of 5 (10 matchdays)
-- Matchdays 1–5 → qual season 1; 6–10 → qual season 2
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.international_generate_qual_fixtures(p_cycle_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cycle public.international_wc_cycles;
  v_group record;
  v_teams text[];
  v_n int;
  v_slots text[];
  v_round int;
  v_match_no int;
  v_i int;
  v_a text;
  v_b text;
  v_home text;
  v_away text;
  v_tmp text;
  v_cal record;
  v_season_id bigint;
  v_inserted bigint := 0;
  v_first_leg boolean;
  v_fid bigint;
BEGIN
  v_cycle := public.international_assert_cycle_admin(p_cycle_id);

  IF v_cycle.qual_season_id_1 IS NULL OR v_cycle.qual_season_id_2 IS NULL THEN
    RAISE EXCEPTION 'Set both qualifying seasons on the cycle first';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.international_qual_groups g WHERE g.cycle_id = p_cycle_id
  ) THEN
    RAISE EXCEPTION 'Draw qualifying groups first';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.international_fixtures f
    WHERE f.cycle_id = p_cycle_id AND f.phase = 'qualifying' AND f.played = true
  ) THEN
    RAISE EXCEPTION 'Cannot regenerate: qualifying fixtures already played';
  END IF;

  DELETE FROM public.international_fixtures
  WHERE cycle_id = p_cycle_id AND phase = 'qualifying';

  FOR v_group IN
    SELECT g.id, g.group_code
    FROM public.international_qual_groups g
    WHERE g.cycle_id = p_cycle_id
    ORDER BY g.group_code
  LOOP
    SELECT array_agg(m.nation_code ORDER BY m.nation_code)
    INTO v_teams
    FROM public.international_qual_group_members m
    WHERE m.group_id = v_group.id;

    v_n := coalesce(array_length(v_teams, 1), 0);
    IF v_n <> 5 THEN
      RAISE EXCEPTION 'Group % must have 5 nations (has %)', v_group.group_code, v_n;
    END IF;

    FOR v_first_leg IN SELECT true UNION ALL SELECT false LOOP
      v_slots := v_teams || ARRAY[NULL::text];
      FOR v_round IN 1..5 LOOP
        v_match_no := CASE WHEN v_first_leg THEN v_round ELSE v_round + 5 END;
        v_season_id := CASE
          WHEN v_match_no <= 5 THEN v_cycle.qual_season_id_1
          ELSE v_cycle.qual_season_id_2
        END;
        SELECT * INTO v_cal FROM public.international_qual_match_calendar(v_match_no);

        FOR v_i IN 1..3 LOOP
          v_a := v_slots[v_i];
          v_b := v_slots[7 - v_i];
          IF v_a IS NULL OR v_b IS NULL THEN
            CONTINUE;
          END IF;

          IF (v_round % 2) = 1 THEN
            v_home := v_a;
            v_away := v_b;
          ELSE
            v_home := v_b;
            v_away := v_a;
          END IF;

          IF NOT v_first_leg THEN
            v_tmp := v_home;
            v_home := v_away;
            v_away := v_tmp;
          END IF;

          INSERT INTO public.international_fixtures (
            cycle_id, season_id, phase, group_id,
            home_nation, away_nation, match_no,
            gpsl_month, week_in_month, status, played
          )
          VALUES (
            p_cycle_id, v_season_id, 'qualifying', v_group.id,
            v_home, v_away, v_match_no,
            v_cal.gpsl_month, v_cal.week_in_month, 'scheduled', false
          )
          RETURNING id INTO v_fid;

          INSERT INTO public.international_fixture_schedule (fixture_id, status)
          VALUES (v_fid, 'unscheduled')
          ON CONFLICT (fixture_id) DO NOTHING;

          v_inserted := v_inserted + 1;
        END LOOP;

        v_tmp := v_slots[6];
        FOR v_i IN REVERSE 6..3 LOOP
          v_slots[v_i] := v_slots[v_i - 1];
        END LOOP;
        v_slots[2] := v_tmp;
      END LOOP;
    END LOOP;
  END LOOP;

  IF v_cycle.status = 'setup' THEN
    UPDATE public.international_wc_cycles SET status = 'qualifying' WHERE id = p_cycle_id;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'cycle_id', p_cycle_id,
    'fixtures', v_inserted,
    'per_group', 20,
    'matchdays', 10
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Standings: recompute one group from played fixtures
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.international_recompute_group_standings(
  p_group_id bigint,
  p_phase text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_nation text;
BEGIN
  IF p_phase = 'qualifying' THEN
    UPDATE public.international_qual_group_members m
    SET played = 0, won = 0, drawn = 0, lost = 0,
        goals_for = 0, goals_against = 0, points = 0
    WHERE m.group_id = p_group_id;

    FOR v_nation IN
      SELECT nation_code FROM public.international_qual_group_members WHERE group_id = p_group_id
    LOOP
      UPDATE public.international_qual_group_members m
      SET
        played = s.played,
        won = s.won,
        drawn = s.drawn,
        lost = s.lost,
        goals_for = s.gf,
        goals_against = s.ga,
        points = s.pts
      FROM (
        SELECT
          count(*)::smallint AS played,
          count(*) FILTER (WHERE
            (f.home_nation = v_nation AND f.home_goals > f.away_goals)
            OR (f.away_nation = v_nation AND f.away_goals > f.home_goals)
          )::smallint AS won,
          count(*) FILTER (WHERE f.home_goals = f.away_goals)::smallint AS drawn,
          count(*) FILTER (WHERE
            (f.home_nation = v_nation AND f.home_goals < f.away_goals)
            OR (f.away_nation = v_nation AND f.away_goals < f.home_goals)
          )::smallint AS lost,
          coalesce(sum(CASE WHEN f.home_nation = v_nation THEN f.home_goals ELSE f.away_goals END), 0)::smallint AS gf,
          coalesce(sum(CASE WHEN f.home_nation = v_nation THEN f.away_goals ELSE f.home_goals END), 0)::smallint AS ga,
          (
            3 * count(*) FILTER (WHERE
              (f.home_nation = v_nation AND f.home_goals > f.away_goals)
              OR (f.away_nation = v_nation AND f.away_goals > f.home_goals)
            )
            + count(*) FILTER (WHERE f.home_goals = f.away_goals)
          )::smallint AS pts
        FROM public.international_fixtures f
        WHERE f.group_id = p_group_id
          AND f.phase = 'qualifying'
          AND f.played = true
          AND (f.home_nation = v_nation OR f.away_nation = v_nation)
      ) s
      WHERE m.group_id = p_group_id AND m.nation_code = v_nation;
    END LOOP;

  ELSIF p_phase = 'finals_group' THEN
    UPDATE public.international_finals_group_members m
    SET played = 0, won = 0, drawn = 0, lost = 0,
        goals_for = 0, goals_against = 0, points = 0
    WHERE m.group_id = p_group_id;

    FOR v_nation IN
      SELECT nation_code FROM public.international_finals_group_members WHERE group_id = p_group_id
    LOOP
      UPDATE public.international_finals_group_members m
      SET
        played = s.played,
        won = s.won,
        drawn = s.drawn,
        lost = s.lost,
        goals_for = s.gf,
        goals_against = s.ga,
        points = s.pts
      FROM (
        SELECT
          count(*)::smallint AS played,
          count(*) FILTER (WHERE
            (f.home_nation = v_nation AND f.home_goals > f.away_goals)
            OR (f.away_nation = v_nation AND f.away_goals > f.home_goals)
          )::smallint AS won,
          count(*) FILTER (WHERE f.home_goals = f.away_goals)::smallint AS drawn,
          count(*) FILTER (WHERE
            (f.home_nation = v_nation AND f.home_goals < f.away_goals)
            OR (f.away_nation = v_nation AND f.away_goals < f.home_goals)
          )::smallint AS lost,
          coalesce(sum(CASE WHEN f.home_nation = v_nation THEN f.home_goals ELSE f.away_goals END), 0)::smallint AS gf,
          coalesce(sum(CASE WHEN f.home_nation = v_nation THEN f.away_goals ELSE f.home_goals END), 0)::smallint AS ga,
          (
            3 * count(*) FILTER (WHERE
              (f.home_nation = v_nation AND f.home_goals > f.away_goals)
              OR (f.away_nation = v_nation AND f.away_goals > f.home_goals)
            )
            + count(*) FILTER (WHERE f.home_goals = f.away_goals)
          )::smallint AS pts
        FROM public.international_fixtures f
        WHERE f.group_id = p_group_id
          AND f.phase = 'finals_group'
          AND f.played = true
          AND (f.home_nation = v_nation OR f.away_nation = v_nation)
      ) s
      WHERE m.group_id = p_group_id AND m.nation_code = v_nation;
    END LOOP;
  END IF;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.international_shuffle_text_array(text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_qual_match_calendar(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_assert_cycle_admin(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_admin_create_wc_cycle(text, bigint, bigint, bigint, smallint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_admin_update_wc_cycle(bigint, text, bigint, bigint, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_admin_set_wc_cycle_status(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_admin_draw_qual_groups(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_generate_qual_fixtures(bigint) TO authenticated;
