-- =============================================================================
-- Manager career history + stint tracking (clubs, fees, trophies during tenure)
-- Also helps sack rehire blocks by preserving signed/sacked club links.
-- Run after manager_sack_rehire_block.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.manager_club_stints (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manager_id bigint NOT NULL REFERENCES public."Managers" (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName") ON DELETE CASCADE,
  season_id bigint REFERENCES public.competition_seasons (id) ON DELETE SET NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  start_fee numeric(14, 2),
  end_fee numeric(14, 2),
  start_kind text NOT NULL DEFAULT 'assign'
    CHECK (start_kind IN ('draft', 'market', 'assign', 'admin')),
  end_kind text
    CHECK (end_kind IS NULL OR end_kind IN ('sack', 'transfer', 'expire', 'admin', 'release')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS manager_club_stints_manager_idx
  ON public.manager_club_stints (manager_id, started_at DESC);

CREATE INDEX IF NOT EXISTS manager_club_stints_club_idx
  ON public.manager_club_stints (club_short_name, started_at DESC);

CREATE INDEX IF NOT EXISTS manager_club_stints_open_idx
  ON public.manager_club_stints (manager_id)
  WHERE ended_at IS NULL;

COMMENT ON TABLE public.manager_club_stints IS
  'Manager employment history at clubs (draft/market/admin start; sack/transfer/expire end).';

ALTER TABLE public.manager_club_stints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS manager_club_stints_select ON public.manager_club_stints;
CREATE POLICY manager_club_stints_select ON public.manager_club_stints
  FOR SELECT TO authenticated USING (true);

CREATE OR REPLACE FUNCTION public.manager_club_short_canonical(p_club text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT c."ShortName"
  FROM public."Clubs" c
  WHERE upper(c."ShortName") = upper(btrim(coalesce(p_club, '')))
  LIMIT 1;
$$;

-- ---------------------------------------------------------------------------
-- Open / close stints
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.manager_stint_open(
  p_manager_id bigint,
  p_club_short text,
  p_fee numeric DEFAULT NULL,
  p_kind text DEFAULT 'assign',
  p_season_id bigint DEFAULT NULL,
  p_started_at timestamptz DEFAULT now()
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_season_id bigint := p_season_id;
  v_kind text := coalesce(nullif(btrim(p_kind), ''), 'assign');
  v_id bigint;
BEGIN
  SELECT c."ShortName" INTO v_club
  FROM public."Clubs" c
  WHERE upper(c."ShortName") = upper(btrim(coalesce(p_club_short, '')))
  LIMIT 1;

  IF p_manager_id IS NULL OR v_club IS NULL THEN
    RETURN NULL;
  END IF;

  IF v_kind NOT IN ('draft', 'market', 'assign', 'admin') THEN
    v_kind := 'assign';
  END IF;

  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  -- Close any open stints first (should be rare)
  UPDATE public.manager_club_stints
  SET ended_at = coalesce(p_started_at, now()),
      end_kind = coalesce(end_kind, 'release')
  WHERE manager_id = p_manager_id
    AND ended_at IS NULL;

  INSERT INTO public.manager_club_stints (
    manager_id,
    club_short_name,
    season_id,
    started_at,
    start_fee,
    start_kind
  )
  VALUES (
    p_manager_id,
    v_club,
    v_season_id,
    coalesce(p_started_at, now()),
    p_fee,
    v_kind
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.manager_stint_close(
  p_manager_id bigint,
  p_club_short text DEFAULT NULL,
  p_fee numeric DEFAULT NULL,
  p_kind text DEFAULT 'release',
  p_ended_at timestamptz DEFAULT now()
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_kind text := coalesce(nullif(btrim(p_kind), ''), 'release');
  v_id bigint;
BEGIN
  IF p_manager_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT c."ShortName" INTO v_club
  FROM public."Clubs" c
  WHERE upper(c."ShortName") = upper(btrim(coalesce(p_club_short, '')))
  LIMIT 1;

  IF v_kind NOT IN ('sack', 'transfer', 'expire', 'admin', 'release') THEN
    v_kind := 'release';
  END IF;

  SELECT s.id INTO v_id
  FROM public.manager_club_stints s
  WHERE s.manager_id = p_manager_id
    AND s.ended_at IS NULL
    AND (v_club IS NULL OR upper(s.club_short_name) = upper(v_club))
  ORDER BY s.started_at DESC
  LIMIT 1
  FOR UPDATE;

  IF v_id IS NULL THEN
    RETURN NULL;
  END IF;

  UPDATE public.manager_club_stints
  SET ended_at = coalesce(p_ended_at, now()),
      end_fee = p_fee,
      end_kind = v_kind
  WHERE id = v_id;

  RETURN v_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Hook into assign / release (compatible with existing call shapes)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.manager_assign_to_club(
  p_manager_id bigint,
  p_club_short text,
  p_seasons smallint DEFAULT 2,
  p_fee numeric DEFAULT NULL,
  p_buyer_pays boolean DEFAULT true,
  p_ledger_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_mgr public."Managers"%rowtype;
  v_existing bigint;
  v_balance numeric;
  v_fee numeric;
  v_season_id bigint;
  v_wage bigint;
  v_meta jsonb;
  v_kind text := 'assign';
BEGIN
  SELECT * INTO v_mgr FROM public."Managers" WHERE id = p_manager_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Manager not found';
  END IF;

  IF v_mgr.contracted_club IS NOT NULL AND btrim(v_mgr.contracted_club) <> '' THEN
    RAISE EXCEPTION 'Manager already contracted to %', v_mgr.contracted_club;
  END IF;

  IF NOT coalesce((p_ledger_metadata->>'skip_sack_block')::boolean, false)
    AND NOT (
      auth.uid() IS NOT NULL
      AND public.is_gpsl_admin()
    ) THEN
    PERFORM public.manager_assert_not_sack_blocked(p_club_short, p_manager_id);
  END IF;

  SELECT m.id INTO v_existing
  FROM public."Managers" m
  WHERE m.contracted_club = p_club_short
  LIMIT 1;

  IF v_existing IS NOT NULL THEN
    RAISE EXCEPTION 'Club already has a manager signed';
  END IF;

  v_fee := coalesce(p_fee, v_mgr.market_value::numeric);

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true
  ORDER BY id DESC
  LIMIT 1;

  IF p_buyer_pays AND v_fee > 0 THEN
    SELECT balance INTO v_balance
    FROM public."Club_Finances"
    WHERE club_name = p_club_short
    FOR UPDATE;

    IF v_balance IS NULL THEN
      RAISE EXCEPTION 'Club finances not found for %', p_club_short;
    END IF;
    IF v_balance < v_fee THEN
      RAISE EXCEPTION 'Insufficient balance (need %, have %)', v_fee, v_balance;
    END IF;

    v_meta := coalesce(p_ledger_metadata, '{}'::jsonb)
      || jsonb_build_object('manager_id', p_manager_id, 'kind', 'manager');

    PERFORM public.post_club_ledger(
      p_club_short,
      'contract_signing_offer',
      -abs(v_fee),
      format('Manager signing — %s', v_mgr.name),
      v_meta,
      v_season_id,
      NULL,
      true,
      true
    );
  END IF;

  v_wage := public.manager_weekly_wage_for(v_mgr.market_value);

  UPDATE public."Managers"
  SET contracted_club = p_club_short,
      contract_seasons_remaining = greatest(coalesce(p_seasons, 2), 1),
      weekly_wage = v_wage,
      signed_season_id = v_season_id,
      updated_at = now()
  WHERE id = p_manager_id;

  PERFORM public.manager_sync_club_rating(p_club_short);

  UPDATE public."Manager_Transfer_Listings"
  SET status = 'Closed',
      transfer_completed = true,
      updated_at = now()
  WHERE manager_id = p_manager_id
    AND listing_type = 'draft'
    AND status = 'Active';

  IF coalesce((p_ledger_metadata->>'manager_draft')::boolean, false)
    OR coalesce(p_ledger_metadata->>'manager_draft', '') IN ('true', 't', '1') THEN
    v_kind := 'draft';
  ELSIF coalesce(p_ledger_metadata->>'source', '') = 'market' THEN
    v_kind := 'market';
  ELSIF coalesce(p_ledger_metadata->>'source', '') = 'admin' THEN
    v_kind := 'admin';
  END IF;

  PERFORM public.manager_stint_open(
    p_manager_id,
    p_club_short,
    v_fee,
    v_kind,
    v_season_id,
    now()
  );

  IF to_regprocedure('public.owner_inbox_notify_season_expectations(text)') IS NOT NULL THEN
    PERFORM public.owner_inbox_notify_season_expectations(p_club_short);
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'manager_id', p_manager_id,
    'club', p_club_short,
    'fee', v_fee,
    'seasons', greatest(coalesce(p_seasons, 2), 1),
    'weekly_wage', v_wage
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.manager_release_from_club(
  p_manager_id bigint,
  p_payout_club text DEFAULT NULL,
  p_payout_amount numeric DEFAULT NULL,
  p_ledger_type text DEFAULT 'transfer_sale',
  p_description text DEFAULT NULL,
  p_metadata jsonb DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_mgr public."Managers"%rowtype;
  v_club text;
  v_payout numeric;
  v_desc text;
  v_meta jsonb;
  v_end_kind text := 'release';
BEGIN
  SELECT * INTO v_mgr FROM public."Managers" WHERE id = p_manager_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Manager not found';
  END IF;

  v_club := v_mgr.contracted_club;
  IF v_club IS NULL OR btrim(v_club) = '' THEN
    RAISE EXCEPTION 'Manager is a free agent';
  END IF;

  v_payout := coalesce(p_payout_amount, v_mgr.market_value::numeric);
  v_desc := coalesce(nullif(btrim(p_description), ''), format('Manager release — %s', v_mgr.name));
  v_meta := coalesce(p_metadata, '{}'::jsonb) || jsonb_build_object('manager_id', p_manager_id, 'kind', 'manager');

  IF p_payout_club IS NOT NULL AND v_payout > 0 THEN
    PERFORM public.post_club_ledger(
      p_payout_club,
      p_ledger_type,
      abs(v_payout),
      v_desc,
      v_meta
    );
  END IF;

  IF coalesce((p_metadata->>'manager_sack')::boolean, false)
    OR coalesce(p_metadata->>'manager_sack', '') IN ('true', 't', '1')
    OR v_desc ILIKE 'Manager sack%' THEN
    v_end_kind := 'sack';
  ELSIF p_ledger_type = 'transfer_sale' THEN
    v_end_kind := 'transfer';
  END IF;

  PERFORM public.manager_stint_close(
    p_manager_id,
    v_club,
    CASE WHEN v_end_kind = 'sack' THEN v_payout ELSE NULL END,
    v_end_kind,
    now()
  );

  -- Keep signed_season_id for history
  UPDATE public."Managers"
  SET contracted_club = NULL,
      contract_seasons_remaining = 0,
      weekly_wage = 0,
      updated_at = now()
  WHERE id = p_manager_id;

  UPDATE public."Clubs"
  SET manager_id = NULL,
      manager_rating = NULL
  WHERE "ShortName" = v_club;

  UPDATE public."Manager_Transfer_Listings"
  SET status = 'Cancelled', updated_at = now()
  WHERE manager_id = p_manager_id AND status = 'Active';

  RETURN jsonb_build_object(
    'ok', true,
    'manager_id', p_manager_id,
    'former_club', v_club,
    'payout', v_payout
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Backfill stints + sack blocks from ledger / listings
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.manager_stints_backfill(
  p_dry_run boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_events jsonb := '[]'::jsonb;
  v_inserted int := 0;
  v_row record;
  v_open_id bigint;
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  DROP TABLE IF EXISTS tmp_manager_stint_events;
  CREATE TEMP TABLE tmp_manager_stint_events ON COMMIT DROP AS
  WITH signing AS (
    SELECT
      nullif(l.metadata->>'manager_id', '')::bigint AS manager_id,
      upper(l.club_short_name) AS club_short_name,
      l.created_at AS event_at,
      abs(l.amount) AS fee,
      CASE
        WHEN coalesce(l.metadata->>'manager_draft', '') IN ('true', 't', '1') THEN 'draft'
        ELSE 'assign'
      END AS kind,
      'start'::text AS direction,
      l.season_id
    FROM public.competition_finance_ledger l
    WHERE l.entry_type = 'contract_signing_offer'
      AND l.amount < 0
      AND nullif(l.metadata->>'manager_id', '') ~ '^[0-9]+$'
  ),
  endings AS (
    SELECT
      nullif(l.metadata->>'manager_id', '')::bigint AS manager_id,
      upper(l.club_short_name) AS club_short_name,
      l.created_at AS event_at,
      abs(l.amount) AS fee,
      CASE
        WHEN coalesce(l.metadata->>'manager_sack', '') IN ('true', 't', '1')
          OR l.description ILIKE 'Manager sack%' THEN 'sack'
        ELSE 'release'
      END AS kind,
      'end'::text AS direction,
      l.season_id
    FROM public.competition_finance_ledger l
    WHERE l.entry_type = 'contract_release_comp'
      AND l.amount > 0
      AND (
        coalesce(l.metadata->>'kind', '') = 'manager'
        OR coalesce(l.metadata->>'manager_sack', '') IN ('true', 't', '1')
        OR l.description ILIKE 'Manager sack%'
        OR l.description ILIKE 'Manager release%'
      )
      AND nullif(l.metadata->>'manager_id', '') ~ '^[0-9]+$'
  ),
  listings AS (
    SELECT
      l.manager_id,
      upper(l.current_highest_bidder) AS club_short_name,
      l.updated_at AS event_at,
      coalesce(l.current_highest_bid, 0) AS fee,
      CASE WHEN l.listing_type = 'draft' THEN 'draft' ELSE 'market' END AS kind,
      'start'::text AS direction,
      NULL::bigint AS season_id
    FROM public."Manager_Transfer_Listings" l
    WHERE l.transfer_completed = true
      AND l.manager_id IS NOT NULL
      AND nullif(btrim(l.current_highest_bidder), '') IS NOT NULL
  )
  SELECT * FROM signing
  UNION ALL
  SELECT * FROM endings
  UNION ALL
  SELECT * FROM listings;

  SELECT coalesce(
    jsonb_agg(
      jsonb_build_object(
        'manager_id', e.manager_id,
        'club', e.club_short_name,
        'at', e.event_at,
        'kind', e.kind,
        'direction', e.direction,
        'fee', e.fee
      )
      ORDER BY e.manager_id, e.event_at
    ),
    '[]'::jsonb
  )
  INTO v_events
  FROM tmp_manager_stint_events e
  WHERE e.manager_id IS NOT NULL;

  IF p_dry_run THEN
    RETURN jsonb_build_object(
      'ok', true,
      'dry_run', true,
      'event_count', jsonb_array_length(v_events),
      'events', v_events
    );
  END IF;

  -- Replay chronologically per manager
  FOR v_row IN
    SELECT *
    FROM tmp_manager_stint_events
    WHERE manager_id IS NOT NULL
      AND club_short_name IS NOT NULL
    ORDER BY manager_id, event_at, direction DESC -- start before end when same timestamp
  LOOP
    IF v_row.direction = 'start' THEN
      -- Skip duplicate open identical open at same club if already open
      SELECT id INTO v_open_id
      FROM public.manager_club_stints
      WHERE manager_id = v_row.manager_id
        AND ended_at IS NULL
        AND upper(club_short_name) = v_row.club_short_name
      LIMIT 1;

      IF v_open_id IS NULL THEN
        PERFORM public.manager_stint_open(
          v_row.manager_id,
          v_row.club_short_name,
          v_row.fee,
          v_row.kind,
          v_row.season_id,
          v_row.event_at
        );
        v_inserted := v_inserted + 1;
      END IF;
    ELSE
      PERFORM public.manager_stint_close(
        v_row.manager_id,
        v_row.club_short_name,
        v_row.fee,
        v_row.kind,
        v_row.event_at
      );
    END IF;
  END LOOP;

  -- Open stints for managers still contracted with no open row
  INSERT INTO public.manager_club_stints (
    manager_id, club_short_name, season_id, started_at, start_fee, start_kind
  )
  SELECT
    m.id,
    public.manager_club_short_canonical(m.contracted_club),
    m.signed_season_id,
    coalesce(m.updated_at, now()),
    m.market_value::numeric,
    'assign'
  FROM public."Managers" m
  WHERE m.contracted_club IS NOT NULL
    AND btrim(m.contracted_club) <> ''
    AND public.manager_club_short_canonical(m.contracted_club) IS NOT NULL
    AND NOT EXISTS (
      SELECT 1 FROM public.manager_club_stints s
      WHERE s.manager_id = m.id AND s.ended_at IS NULL
    );

  -- Ensure sack blocks for ended-with-sack stints this season
  INSERT INTO public.manager_club_sack_blocks (
    season_id, club_short_name, manager_id, sacked_at
  )
  SELECT
    coalesce(
      s.season_id,
      (SELECT id FROM public.competition_seasons WHERE is_current = true ORDER BY id DESC LIMIT 1)
    ),
    public.manager_club_short_canonical(s.club_short_name),
    s.manager_id,
    coalesce(s.ended_at, now())
  FROM public.manager_club_stints s
  WHERE s.end_kind = 'sack'
    AND s.ended_at IS NOT NULL
    AND public.manager_club_short_canonical(s.club_short_name) IS NOT NULL
  ON CONFLICT (season_id, club_short_name, manager_id) DO NOTHING;

  RETURN jsonb_build_object(
    'ok', true,
    'dry_run', false,
    'event_count', jsonb_array_length(v_events),
    'stints_opened', v_inserted
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Career bundle for manager_career.html
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.manager_career_bundle(p_manager_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_mgr public."Managers"%rowtype;
  v_stints jsonb := '[]'::jsonb;
  v_transfers jsonb := '[]'::jsonb;
  v_trophies jsonb := '[]'::jsonb;
BEGIN
  IF p_manager_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'invalid_args');
  END IF;

  SELECT * INTO v_mgr FROM public."Managers" WHERE id = p_manager_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;

  SELECT coalesce(jsonb_agg(row_data ORDER BY sort_at DESC), '[]'::jsonb)
  INTO v_stints
  FROM (
    SELECT
      jsonb_build_object(
        'club_short', s.club_short_name,
        'club_name', coalesce(
          (SELECT c."Club" FROM public."Clubs" c WHERE c."ShortName" = s.club_short_name),
          s.club_short_name
        ),
        'season_id', s.season_id,
        'season_label', coalesce(se.label, 'Season'),
        'started_at', s.started_at,
        'ended_at', s.ended_at,
        'start_fee', s.start_fee,
        'end_fee', s.end_fee,
        'start_kind', s.start_kind,
        'end_kind', s.end_kind,
        'is_current', s.ended_at IS NULL
      ) AS row_data,
      s.started_at AS sort_at
    FROM public.manager_club_stints s
    LEFT JOIN public.competition_seasons se ON se.id = s.season_id
    WHERE s.manager_id = p_manager_id
  ) q;

  SELECT coalesce(jsonb_agg(row_data ORDER BY sort_at DESC), '[]'::jsonb)
  INTO v_transfers
  FROM (
    SELECT
      jsonb_build_object(
        'at', l.updated_at,
        'from_club', l.seller_club_id,
        'to_club', l.current_highest_bidder,
        'fee', l.current_highest_bid,
        'listing_type', l.listing_type,
        'deal_kind', CASE
          WHEN l.listing_type = 'draft' THEN 'draft'
          ELSE 'market'
        END
      ) AS row_data,
      l.updated_at AS sort_at
    FROM public."Manager_Transfer_Listings" l
    WHERE l.manager_id = p_manager_id
      AND l.transfer_completed = true
    UNION ALL
    SELECT
      jsonb_build_object(
        'at', l.created_at,
        'from_club', NULL,
        'to_club', l.club_short_name,
        'fee', abs(l.amount),
        'listing_type', 'ledger',
        'deal_kind', CASE
          WHEN coalesce(l.metadata->>'manager_draft', '') IN ('true', 't', '1') THEN 'draft'
          ELSE 'assign'
        END
      ) AS row_data,
      l.created_at AS sort_at
    FROM public.competition_finance_ledger l
    WHERE l.entry_type = 'contract_signing_offer'
      AND nullif(l.metadata->>'manager_id', '')::bigint = p_manager_id
  ) q;

  -- Trophies won by clubs while this manager was in charge (archived seasons)
  SELECT coalesce(jsonb_agg(row_data ORDER BY sort_key DESC), '[]'::jsonb)
  INTO v_trophies
  FROM (
    SELECT
      jsonb_build_object(
        'honour_type', 'league_champion',
        'honour_label', CASE a.division
          WHEN 'superleague' THEN 'SuperLeague champions'
          WHEN 'championship_a' THEN 'Championship A champions'
          WHEN 'championship_b' THEN 'Championship B champions'
          ELSE 'League champions'
        END,
        'season_label', a.season_label,
        'club_short', a.club_short_name,
        'club_name', a.club_short_name,
        'division', a.division
      ) AS row_data,
      a.season_label AS sort_key
    FROM public.competition_club_season_archive a
    JOIN public.manager_club_stints s
      ON upper(s.club_short_name) = upper(a.club_short_name)
     AND s.manager_id = p_manager_id
     AND a.final_position = 1
     AND (s.season_id IS NULL OR a.season_id IS NULL OR s.season_id = a.season_id)
    UNION ALL
    SELECT
      jsonb_build_object(
        'honour_type', 'cup_winner',
        'honour_label', CASE w.cup_code
          WHEN 'league_cup' THEN 'League Cup winners'
          WHEN 'super8' THEN 'Super8 winners'
          WHEN 'plate' THEN 'Plate winners'
          WHEN 'shield' THEN 'Shield winners'
          WHEN 'bowl' THEN 'Bowl winners'
          WHEN 'spoon' THEN 'Bowl winners'
          ELSE initcap(replace(w.cup_code, '_', ' ')) || ' winners'
        END,
        'season_label', w.season_label,
        'club_short', w.winner_club_short_name,
        'club_name', w.winner_club_short_name,
        'cup_code', w.cup_code
      ) AS row_data,
      w.season_label AS sort_key
    FROM public.competition_cup_season_winner w
    JOIN public.manager_club_stints s
      ON upper(s.club_short_name) = upper(w.winner_club_short_name)
     AND s.manager_id = p_manager_id
     AND (s.season_id IS NULL OR s.season_id = w.season_id)
  ) q;

  RETURN jsonb_build_object(
    'ok', true,
    'manager', jsonb_build_object(
      'id', v_mgr.id,
      'name', v_mgr.name,
      'slug', v_mgr.slug,
      'nation', v_mgr.nation,
      'rating', v_mgr.rating,
      'age', v_mgr.age,
      'market_value', v_mgr.market_value,
      'contracted_club', v_mgr.contracted_club,
      'weekly_wage', v_mgr.weekly_wage,
      'contract_seasons_remaining', v_mgr.contract_seasons_remaining
    ),
    'stints', coalesce(v_stints, '[]'::jsonb),
    'transfers', coalesce(v_transfers, '[]'::jsonb),
    'trophies', coalesce(v_trophies, '[]'::jsonb)
  );
END;
$function$;

-- Apply historical backfill once
SELECT public.manager_stints_backfill(false);
-- Refresh sack blocks from ledger again
SELECT public.manager_sack_blocks_backfill(NULL::bigint, false);

GRANT SELECT ON public.manager_club_stints TO authenticated;
GRANT EXECUTE ON FUNCTION public.manager_stints_backfill(boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.manager_career_bundle(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.manager_assign_to_club(
  bigint, text, smallint, numeric, boolean, jsonb
) TO authenticated;

NOTIFY pgrst, 'reload schema';
