-- =============================================================================
-- Block clubs from re-signing a manager they sacked in the same GPSL season.
-- Run after manager_sack_finance_line.sql and managers_draft_vacancy_guard.sql.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.manager_club_sack_blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName") ON DELETE CASCADE,
  manager_id bigint NOT NULL REFERENCES public."Managers" (id) ON DELETE CASCADE,
  sacked_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT manager_club_sack_blocks_unique
    UNIQUE (season_id, club_short_name, manager_id)
);

CREATE INDEX IF NOT EXISTS manager_club_sack_blocks_club_season_idx
  ON public.manager_club_sack_blocks (season_id, club_short_name);

COMMENT ON TABLE public.manager_club_sack_blocks IS
  'Club cannot re-sign this manager until the next GPSL season (after mid-season sack).';

ALTER TABLE public.manager_club_sack_blocks ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.manager_club_sack_block_record(
  p_club_short text,
  p_manager_id bigint,
  p_season_id bigint DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint := p_season_id;
BEGIN
  IF p_club_short IS NULL OR btrim(p_club_short) = '' OR p_manager_id IS NULL THEN
    RETURN;
  END IF;

  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  IF v_season_id IS NULL THEN
    RETURN;
  END IF;

  INSERT INTO public.manager_club_sack_blocks (
    season_id,
    club_short_name,
    manager_id,
    sacked_at
  )
  VALUES (v_season_id, p_club_short, p_manager_id, now())
  ON CONFLICT (season_id, club_short_name, manager_id)
  DO UPDATE SET sacked_at = excluded.sacked_at;
END;
$function$;

CREATE OR REPLACE FUNCTION public.manager_assert_not_sack_blocked(
  p_club_short text,
  p_manager_id bigint
)
RETURNS void
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF p_club_short IS NULL OR btrim(p_club_short) = '' OR p_manager_id IS NULL THEN
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.manager_club_sack_blocks b
    JOIN public.competition_seasons s
      ON s.id = b.season_id
     AND s.is_current = true
    WHERE b.club_short_name = p_club_short
      AND b.manager_id = p_manager_id
  ) THEN
    RAISE EXCEPTION
      'You cannot re-sign a manager you sacked this season — try again next season';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_sacked_manager_ids()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_ids jsonb;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  SELECT coalesce(jsonb_agg(b.manager_id ORDER BY b.manager_id), '[]'::jsonb)
  INTO v_ids
  FROM public.manager_club_sack_blocks b
  JOIN public.competition_seasons s
    ON s.id = b.season_id
   AND s.is_current = true
  WHERE b.club_short_name = v_club;

  RETURN coalesce(v_ids, '[]'::jsonb);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Record block on sack
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.manager_sack()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_mgr public."Managers"%rowtype;
  v_payout numeric;
  v_sacks smallint;
  v_season_id bigint;
  v_result jsonb;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  v_club := public.my_club_shortname();
  IF v_club IS NULL THEN
    RAISE EXCEPTION 'No club linked to your account';
  END IF;

  SELECT manager_sacks_remaining INTO v_sacks
  FROM public."Clubs"
  WHERE "ShortName" = v_club
  FOR UPDATE;

  IF coalesce(v_sacks, 0) < 1 THEN
    RAISE EXCEPTION 'Manager sack already used this season';
  END IF;

  SELECT * INTO v_mgr
  FROM public."Managers"
  WHERE contracted_club = v_club
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No manager signed at your club';
  END IF;

  v_payout := round(greatest(v_mgr.market_value, 0)::numeric / 2.0, 0);

  UPDATE public."Clubs"
  SET manager_sacks_remaining = 0
  WHERE "ShortName" = v_club;

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true
  ORDER BY id DESC
  LIMIT 1;

  v_result := public.manager_release_from_club(
    v_mgr.id,
    v_club,
    v_payout,
    'contract_release_comp',
    format('Manager sack — %s (half MV)', v_mgr.name),
    jsonb_build_object('manager_sack', true, 'gpsl_month', 'january')
  );

  PERFORM public.manager_club_sack_block_record(v_club, v_mgr.id, v_season_id);

  RETURN v_result;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Enforce on assignment (draft settlement, market, admin bypass)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.manager_assign_to_club(
  p_manager_id bigint,
  p_club_short text,
  p_seasons smallint DEFAULT 2,
  p_fee numeric DEFAULT NULL,
  p_buyer_pays boolean DEFAULT true,
  p_ledger_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_mgr public."Managers"%rowtype;
  v_existing bigint;
  v_balance numeric;
  v_fee numeric;
  v_season_id bigint;
  v_wage bigint;
  v_meta jsonb;
BEGIN
  SELECT * INTO v_mgr FROM public."Managers" WHERE id = p_manager_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Manager not found';
  END IF;

  IF v_mgr.contracted_club IS NOT NULL AND btrim(v_mgr.contracted_club) <> '' THEN
    RAISE EXCEPTION 'Manager already contracted to %', v_mgr.contracted_club;
  END IF;

  IF NOT coalesce((p_ledger_metadata->>'skip_sack_block')::boolean, false)
    AND NOT (
      auth.uid() IS NOT NULL
      AND public.is_gpsl_admin()
    ) THEN
    PERFORM public.manager_assert_not_sack_blocked(p_club_short, p_manager_id);
  END IF;

  SELECT m.id INTO v_existing
  FROM public."Managers" m
  WHERE m.contracted_club = p_club_short
  LIMIT 1;

  IF v_existing IS NOT NULL THEN
    RAISE EXCEPTION 'Club already has a manager signed';
  END IF;

  v_fee := coalesce(p_fee, v_mgr.market_value::numeric);

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true
  ORDER BY id DESC
  LIMIT 1;

  IF p_buyer_pays AND v_fee > 0 THEN
    SELECT balance INTO v_balance
    FROM public."Club_Finances"
    WHERE club_name = p_club_short
    FOR UPDATE;

    IF v_balance IS NULL THEN
      RAISE EXCEPTION 'Club finances not found for %', p_club_short;
    END IF;
    IF v_balance < v_fee THEN
      RAISE EXCEPTION 'Insufficient balance (need %, have %)', v_fee, v_balance;
    END IF;

    v_meta := coalesce(p_ledger_metadata, '{}'::jsonb)
      || jsonb_build_object('manager_id', p_manager_id, 'kind', 'manager');

    PERFORM public.post_club_ledger(
      p_club_short,
      'contract_signing_offer',
      -abs(v_fee),
      format('Manager signing — %s', v_mgr.name),
      v_meta,
      v_season_id,
      NULL,
      true,
      true
    );
  END IF;

  v_wage := public.manager_weekly_wage_for(v_mgr.market_value);

  UPDATE public."Managers"
  SET contracted_club = p_club_short,
      contract_seasons_remaining = greatest(coalesce(p_seasons, 2), 1),
      weekly_wage = v_wage,
      signed_season_id = v_season_id,
      updated_at = now()
  WHERE id = p_manager_id;

  PERFORM public.manager_sync_club_rating(p_club_short);

  UPDATE public."Manager_Transfer_Listings"
  SET status = 'Closed',
      transfer_completed = true,
      updated_at = now()
  WHERE manager_id = p_manager_id
    AND listing_type = 'draft'
    AND status = 'Active';

  IF to_regprocedure('public.owner_inbox_notify_season_expectations(text)') IS NOT NULL THEN
    PERFORM public.owner_inbox_notify_season_expectations(p_club_short);
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'manager_id', p_manager_id,
    'club', p_club_short,
    'fee', v_fee,
    'seasons', greatest(coalesce(p_seasons, 2), 1),
    'weekly_wage', v_wage
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Enforce on manager draft bids (trigger)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.trg_manager_transfer_bids_draft_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_enabled boolean;
  v_start   timestamptz;
  v_finish  timestamptz;
  v_is_draft boolean;
  v_other_mid bigint;
BEGIN
  v_is_draft := (
    COALESCE(NEW.is_first_draft_bid, false)
    OR COALESCE(NEW.is_draft_join, false)
    OR (
      NEW.listing_id IS NOT NULL
      AND EXISTS (
        SELECT 1 FROM public."Manager_Transfer_Listings" l
        WHERE l.id = NEW.listing_id AND l.listing_type = 'draft'
      )
    )
  );

  IF NOT v_is_draft THEN
    RETURN NEW;
  END IF;

  SELECT manager_draft_auction_enabled, draft_auction_start_time, draft_random_finish_time
  INTO v_enabled, v_start, v_finish
  FROM public.global_settings
  WHERE id = 1;

  IF NOT COALESCE(v_enabled, false) THEN
    RAISE EXCEPTION 'Manager draft auction is not enabled';
  END IF;

  IF v_start IS NOT NULL AND now() < v_start THEN
    RAISE EXCEPTION 'Manager draft auction has not started yet';
  END IF;

  IF v_start IS NOT NULL AND v_finish IS NULL THEN
    v_finish := v_start + interval '23 hours 59 minutes 59 seconds';
  END IF;

  IF v_finish IS NOT NULL AND now() >= v_finish THEN
    RAISE EXCEPTION 'Manager draft bidding has closed';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public."Managers" m
    WHERE m.contracted_club = NEW.bidder_club_id
  ) OR EXISTS (
    SELECT 1
    FROM public."Clubs" c
    WHERE c."ShortName" = NEW.bidder_club_id
      AND c.manager_id IS NOT NULL
  ) THEN
    RAISE EXCEPTION
      'Your club already has a manager — sack them before bidding in the manager draft auction';
  END IF;

  PERFORM public.manager_assert_not_sack_blocked(NEW.bidder_club_id, NEW.manager_id);

  SELECT l.manager_id INTO v_other_mid
  FROM public."Manager_Transfer_Listings" l
  WHERE l.listing_type = 'draft'
    AND l.status = 'Active'
    AND l.manager_id <> NEW.manager_id
    AND l.current_highest_bidder = NEW.bidder_club_id
  LIMIT 1;

  IF v_other_mid IS NOT NULL THEN
    RAISE EXCEPTION 'You may only hold the highest bid on one manager draft auction at a time';
  END IF;

  RETURN NEW;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Enforce on standard manager market bids
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.manager_place_bid(
  p_listing_id bigint,
  p_amount numeric
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_listing public."Manager_Transfer_Listings"%rowtype;
  v_mgr public."Managers"%rowtype;
  v_balance numeric;
  v_min numeric;
  v_high numeric;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  v_club := public.my_club_shortname();
  IF v_club IS NULL THEN
    RAISE EXCEPTION 'No club linked to your account';
  END IF;

  SELECT * INTO v_listing
  FROM public."Manager_Transfer_Listings"
  WHERE id = p_listing_id
  FOR UPDATE;

  IF NOT FOUND OR v_listing.status <> 'Active' THEN
    RAISE EXCEPTION 'Listing not open';
  END IF;

  IF v_listing.end_time IS NOT NULL AND v_listing.end_time < now() THEN
    RAISE EXCEPTION 'Listing has expired';
  END IF;

  IF v_listing.seller_club_id IS NOT DISTINCT FROM v_club THEN
    RAISE EXCEPTION 'Cannot bid on your own listing';
  END IF;

  SELECT * INTO v_mgr FROM public."Managers" WHERE id = v_listing.manager_id;

  PERFORM public.manager_assert_not_sack_blocked(v_club, v_listing.manager_id);

  IF EXISTS (
    SELECT 1 FROM public."Managers" m WHERE m.contracted_club = v_club
  ) THEN
    RAISE EXCEPTION 'Your club already has a manager';
  END IF;

  v_high := coalesce(v_listing.current_highest_bid, 0);
  v_min := greatest(v_listing.market_value::numeric, v_high + 500000);

  IF p_amount < v_min THEN
    RAISE EXCEPTION 'Bid must be at least %', v_min;
  END IF;

  SELECT balance INTO v_balance
  FROM public."Club_Finances"
  WHERE club_name = v_club;

  IF coalesce(v_balance, 0) < p_amount THEN
    RAISE EXCEPTION 'Insufficient balance';
  END IF;

  INSERT INTO public."Manager_Transfer_Bids" (
    listing_id, manager_id, bidder_club_id, bid_amount, is_direct
  )
  VALUES (p_listing_id, v_listing.manager_id, v_club, p_amount, true);

  UPDATE public."Manager_Transfer_Listings"
  SET current_highest_bid = p_amount,
      current_highest_bidder = v_club,
      updated_at = now()
  WHERE id = p_listing_id;

  RETURN jsonb_build_object('ok', true, 'bid', p_amount, 'listing_id', p_listing_id);
END;
$function$;

-- Backfill blocks from existing manager sack ledger rows this season
INSERT INTO public.manager_club_sack_blocks (
  season_id,
  club_short_name,
  manager_id,
  sacked_at
)
SELECT
  coalesce(
    l.season_id,
    (SELECT id FROM public.competition_seasons WHERE is_current = true ORDER BY id DESC LIMIT 1)
  ),
  l.club_short_name,
  (l.metadata->>'manager_id')::bigint,
  l.created_at
FROM public.competition_finance_ledger l
WHERE l.entry_type = 'contract_release_comp'
  AND l.amount > 0
  AND coalesce(l.metadata->>'manager_sack', '') IN ('true', 't', '1')
  AND coalesce(l.metadata->>'kind', '') = 'manager'
  AND nullif(l.metadata->>'manager_id', '') ~ '^[0-9]+$'
  AND l.club_short_name IS NOT NULL
ON CONFLICT (season_id, club_short_name, manager_id) DO NOTHING;

GRANT EXECUTE ON FUNCTION public.club_sacked_manager_ids() TO authenticated;
GRANT EXECUTE ON FUNCTION public.manager_sack() TO authenticated;
GRANT EXECUTE ON FUNCTION public.manager_assign_to_club(
  bigint, text, smallint, numeric, boolean, jsonb
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.manager_place_bid(bigint, numeric) TO authenticated;

NOTIFY pgrst, 'reload schema';
