-- =============================================================================
-- GPSL Manager of the Month (club manager, not owner).
-- Best league record in a GPSL month → award on manager profile.
-- Wired into month-lock tables stage via competition_admin_run_month_lock_jobs wrap.
-- Safe to re-run.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.competition_manager_month_award (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  season_label text NOT NULL,
  gpsl_month text NOT NULL,
  manager_id bigint NOT NULL REFERENCES public."Managers" (id),
  manager_name text NOT NULL,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  played smallint NOT NULL DEFAULT 0,
  won smallint NOT NULL DEFAULT 0,
  drawn smallint NOT NULL DEFAULT 0,
  lost smallint NOT NULL DEFAULT 0,
  gf smallint NOT NULL DEFAULT 0,
  ga smallint NOT NULL DEFAULT 0,
  pts smallint NOT NULL DEFAULT 0,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_manager_month_award_unique UNIQUE (season_id, gpsl_month)
);

CREATE INDEX IF NOT EXISTS competition_manager_month_award_manager_idx
  ON public.competition_manager_month_award (manager_id, season_id DESC);

ALTER TABLE public.competition_manager_month_award ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_manager_month_award_select ON public.competition_manager_month_award;
CREATE POLICY competition_manager_month_award_select ON public.competition_manager_month_award
  FOR SELECT TO authenticated, anon USING (true);

DROP POLICY IF EXISTS competition_manager_month_award_admin ON public.competition_manager_month_award;
CREATE POLICY competition_manager_month_award_admin ON public.competition_manager_month_award
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP VIEW IF EXISTS public.competition_manager_month_awards_public;
CREATE VIEW public.competition_manager_month_awards_public
WITH (security_invoker = false)
AS
SELECT
  a.id,
  a.season_id,
  a.season_label,
  a.gpsl_month,
  a.manager_id,
  a.manager_name,
  a.club_short_name,
  c."Club" AS club_name,
  a.played,
  a.won,
  a.drawn,
  a.lost,
  a.gf,
  a.ga,
  a.pts,
  a.detail,
  a.created_at
FROM public.competition_manager_month_award a
LEFT JOIN public."Clubs" c ON c."ShortName" = a.club_short_name;

GRANT SELECT ON public.competition_manager_month_awards_public TO authenticated;
GRANT SELECT ON public.competition_manager_month_awards_public TO anon;

CREATE OR REPLACE FUNCTION public.competition_compute_manager_of_month(
  p_season_id bigint,
  p_gpsl_month text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_month text := lower(nullif(btrim(coalesce(p_gpsl_month, '')), ''));
  v_season_label text;
  v_best record;
  v_manager_id bigint;
  v_manager_name text;
BEGIN
  IF p_season_id IS NULL OR v_month IS NULL OR v_month = 'playoffs' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'bad_args');
  END IF;

  SELECT s.label INTO v_season_label
  FROM public.competition_seasons s
  WHERE s.id = p_season_id;

  WITH club_month AS (
    SELECT
      x.club_short_name,
      count(*)::smallint AS played,
      count(*) FILTER (WHERE x.pts = 3)::smallint AS won,
      count(*) FILTER (WHERE x.pts = 1)::smallint AS drawn,
      count(*) FILTER (WHERE x.pts = 0)::smallint AS lost,
      coalesce(sum(x.gf), 0)::smallint AS gf,
      coalesce(sum(x.ga), 0)::smallint AS ga,
      coalesce(sum(x.pts), 0)::smallint AS pts
    FROM (
      SELECT
        f.home_club_short_name AS club_short_name,
        coalesce(f.home_goals, 0) AS gf,
        coalesce(f.away_goals, 0) AS ga,
        CASE
          WHEN f.home_goals > f.away_goals THEN 3
          WHEN f.home_goals = f.away_goals THEN 1
          ELSE 0
        END AS pts
      FROM public.competition_fixtures f
      WHERE f.season_id = p_season_id
        AND f.gpsl_month = v_month
        AND f.competition_type = 'league'
        AND f.status = 'played'
        AND f.home_goals IS NOT NULL
        AND f.away_goals IS NOT NULL
      UNION ALL
      SELECT
        f.away_club_short_name,
        coalesce(f.away_goals, 0),
        coalesce(f.home_goals, 0),
        CASE
          WHEN f.away_goals > f.home_goals THEN 3
          WHEN f.away_goals = f.home_goals THEN 1
          ELSE 0
        END
      FROM public.competition_fixtures f
      WHERE f.season_id = p_season_id
        AND f.gpsl_month = v_month
        AND f.competition_type = 'league'
        AND f.status = 'played'
        AND f.home_goals IS NOT NULL
        AND f.away_goals IS NOT NULL
    ) x
    GROUP BY x.club_short_name
    HAVING count(*) > 0
  )
  SELECT *
  INTO v_best
  FROM club_month cm
  ORDER BY cm.pts DESC, (cm.gf - cm.ga) DESC, cm.gf DESC, cm.club_short_name
  LIMIT 1;

  IF v_best.club_short_name IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_fixtures');
  END IF;

  SELECT c.manager_id, m.name
  INTO v_manager_id, v_manager_name
  FROM public."Clubs" c
  LEFT JOIN public."Managers" m ON m.id = c.manager_id
  WHERE c."ShortName" = v_best.club_short_name;

  IF v_manager_id IS NULL THEN
    RETURN jsonb_build_object(
      'ok', false,
      'reason', 'no_manager',
      'club_short_name', v_best.club_short_name,
      'pts', v_best.pts
    );
  END IF;

  INSERT INTO public.competition_manager_month_award (
    season_id, season_label, gpsl_month,
    manager_id, manager_name, club_short_name,
    played, won, drawn, lost, gf, ga, pts, detail
  )
  VALUES (
    p_season_id,
    coalesce(v_season_label, 'Season'),
    v_month,
    v_manager_id,
    coalesce(v_manager_name, 'Manager'),
    v_best.club_short_name,
    v_best.played,
    v_best.won,
    v_best.drawn,
    v_best.lost,
    v_best.gf,
    v_best.ga,
    v_best.pts,
    jsonb_build_object('gd', v_best.gf - v_best.ga)
  )
  ON CONFLICT (season_id, gpsl_month) DO UPDATE SET
    manager_id = EXCLUDED.manager_id,
    manager_name = EXCLUDED.manager_name,
    club_short_name = EXCLUDED.club_short_name,
    played = EXCLUDED.played,
    won = EXCLUDED.won,
    drawn = EXCLUDED.drawn,
    lost = EXCLUDED.lost,
    gf = EXCLUDED.gf,
    ga = EXCLUDED.ga,
    pts = EXCLUDED.pts,
    detail = EXCLUDED.detail,
    season_label = EXCLUDED.season_label;

  RETURN jsonb_build_object(
    'ok', true,
    'gpsl_month', v_month,
    'manager_id', v_manager_id,
    'manager_name', v_manager_name,
    'club_short_name', v_best.club_short_name,
    'pts', v_best.pts,
    'record', format('%s-%s-%s', v_best.won, v_best.drawn, v_best.lost)
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.competition_compute_manager_of_month(bigint, text)
  TO authenticated;

-- Hook MotM into admin month-lock after tables (alongside stadium sync wrap if present)
CREATE OR REPLACE FUNCTION public.competition_admin_run_month_lock_jobs(
  p_season_id bigint DEFAULT NULL,
  p_gpsl_month text DEFAULT NULL,
  p_force_scheduling boolean DEFAULT true,
  p_stage text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_out jsonb;
  v_stage text := lower(nullif(btrim(coalesce(p_stage, '')), ''));
  v_stadium_clubs int;
  v_motm jsonb;
  v_month text := nullif(lower(btrim(coalesce(p_gpsl_month, ''))), '');
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  PERFORM set_config('statement_timeout', '240s', true);

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true AND status = 'active'
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_active_season');
  END IF;

  v_out := public.competition_run_month_lock_jobs(
    v_season_id,
    coalesce(p_force_scheduling, true),
    p_gpsl_month,
    p_stage
  );

  -- Stadium fill (if staged runner did not already)
  IF NOT (v_out ? 'stadium_fill_sync')
     AND (
       v_stage IS NULL
       OR v_stage IN ('all', 'tables', 'league_tables', 'stadium', 'attendance')
     )
  THEN
    BEGIN
      IF to_regprocedure('public.competition_stadium_sync_all_clubs(bigint)') IS NOT NULL THEN
        v_stadium_clubs := public.competition_stadium_sync_all_clubs(v_season_id);
        v_out := v_out || jsonb_build_object(
          'stadium_fill_sync',
          jsonb_build_object('ok', true, 'clubs', v_stadium_clubs)
        );
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        v_out := v_out || jsonb_build_object(
          'stadium_fill_sync',
          jsonb_build_object('ok', false, 'error', SQLERRM)
        );
    END;
  END IF;

  -- Manager of the Month after tables / full run
  IF v_stage IS NULL
     OR v_stage IN ('all', 'tables', 'league_tables', 'motm', 'manager_of_month')
  THEN
    BEGIN
      IF v_month IS NULL THEN
        SELECT c.gpsl_month INTO v_month
        FROM public.competition_season_calendar c
        WHERE c.season_id = v_season_id
          AND c.gpsl_month IS NOT NULL
          AND c.gpsl_month <> 'playoffs'
          AND c.lock_at IS NOT NULL
          AND c.lock_at <= now()
        ORDER BY c.lock_at DESC
        LIMIT 1;
      END IF;

      IF v_month IS NOT NULL THEN
        v_motm := public.competition_compute_manager_of_month(v_season_id, v_month);
        v_out := v_out || jsonb_build_object('manager_of_month', v_motm);
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        v_out := v_out || jsonb_build_object(
          'manager_of_month',
          jsonb_build_object('ok', false, 'error', SQLERRM)
        );
    END;
  END IF;

  RETURN v_out;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.competition_admin_run_month_lock_jobs(bigint, text, boolean, text)
  TO authenticated;

NOTIFY pgrst, 'reload schema';
