-- =============================================================================
-- Match scheduling — Phase 2 (check-in, reschedule, emergency drop, forfeits)
-- Run after match_scheduling_phase1.sql (+ context fix if applied)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_fixtures
  ADD COLUMN IF NOT EXISTS is_forfeit boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS forfeit_loser_club text REFERENCES public."Clubs" ("ShortName");

CREATE TABLE IF NOT EXISTS public.competition_fixture_checkin (
  fixture_id bigint NOT NULL REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  checked_in_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (fixture_id, club_short_name)
);

CREATE TABLE IF NOT EXISTS public.competition_club_month_reschedule_use (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  gpsl_month text NOT NULL,
  fixture_id bigint NOT NULL REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  used_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_club_month_reschedule_unique
    UNIQUE (season_id, club_short_name, gpsl_month)
);

CREATE TABLE IF NOT EXISTS public.competition_club_emergency_drop_use (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  fixture_id bigint NOT NULL REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  used_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS competition_club_emergency_drop_season_club_idx
  ON public.competition_club_emergency_drop_use (season_id, club_short_name);

-- Fine tariffs (₿5m no-show, ₿3m unauthorized forfeit)
INSERT INTO public.competition_fine_tariff (
  code, label, category, direction, amount, amount_mode, sort_order, is_active
)
VALUES
  ('match_agreed_no_show', 'No-show at agreed kick-off', 'matchday', 'fine', 5000000, 'fixed', 60, true),
  ('match_unauthorized_forfeit', 'Unauthorized match forfeit', 'matchday', 'fine', 3000000, 'fixed', 61, true)
ON CONFLICT (code) DO UPDATE SET
  label = EXCLUDED.label,
  amount = EXCLUDED.amount,
  is_active = true;

-- Inbox types
ALTER TABLE public.competition_inbox
  DROP CONSTRAINT IF EXISTS competition_inbox_message_type_check;

ALTER TABLE public.competition_inbox
  ADD CONSTRAINT competition_inbox_message_type_check
  CHECK (
    message_type IN (
      'welcome_gpsl',
      'result_submitted',
      'result_to_confirm',
      'result_rejected',
      'result_confirmed',
      'transfer_signed',
      'transfer_sold',
      'transfer_upcoming',
      'draft_scheduled',
      'fine_applied',
      'points_deduction',
      'nation_pick_turn',
      'nation_selection_open',
      'season_expectations',
      'season_overview',
      'player_awards',
      'monthly_fixtures',
      'match_time_proposed',
      'match_time_countered',
      'match_time_accepted',
      'match_rescheduled',
      'match_emergency_drop',
      'match_forfeit_applied',
      'match_checkin_open'
    )
  );

-- ---------------------------------------------------------------------------
-- Constants / helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.match_schedule_checkin_minutes()
RETURNS integer
LANGUAGE sql
IMMUTABLE
AS $$ SELECT 10; $$;

CREATE OR REPLACE FUNCTION public.match_schedule_block_minutes()
RETURNS integer
LANGUAGE sql
IMMUTABLE
AS $$ SELECT 30; $$;

CREATE OR REPLACE FUNCTION public.match_schedule_agreed_kickoff(p_fixture_id bigint)
RETURNS timestamptz
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT sch.agreed_kickoff_at
  FROM public.competition_fixture_schedule sch
  WHERE sch.fixture_id = p_fixture_id
    AND sch.status = 'agreed';
$$;

CREATE OR REPLACE FUNCTION public.match_schedule_fixture_checkins(p_fixture_id bigint)
RETURNS TABLE (club_short_name text, checked_in_at timestamptz)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT c.club_short_name, c.checked_in_at
  FROM public.competition_fixture_checkin c
  WHERE c.fixture_id = p_fixture_id;
$$;

CREATE OR REPLACE FUNCTION public.match_schedule_emergency_drops_used(
  p_season_id bigint,
  p_club_short_name text
)
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT count(*)::integer
  FROM public.competition_club_emergency_drop_use e
  WHERE e.season_id = p_season_id
    AND e.club_short_name = p_club_short_name;
$$;

CREATE OR REPLACE FUNCTION public.match_schedule_reschedule_used_this_month(
  p_season_id bigint,
  p_club_short_name text,
  p_gpsl_month text
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.competition_club_month_reschedule_use r
    WHERE r.season_id = p_season_id
      AND r.club_short_name = p_club_short_name
      AND r.gpsl_month = p_gpsl_month
  );
$$;

CREATE OR REPLACE FUNCTION public.match_schedule_reset_to_unscheduled(p_fixture_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  UPDATE public.competition_fixture_schedule
  SET
    status = 'unscheduled',
    agreed_kickoff_at = NULL,
    pending_proposal_id = NULL,
    updated_at = now()
  WHERE fixture_id = p_fixture_id;

  DELETE FROM public.competition_fixture_checkin
  WHERE fixture_id = p_fixture_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Forfeit (3–0, no stats, cup advance, fine)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fixture_apply_forfeit(
  p_fixture_id bigint,
  p_loser_club text,
  p_tariff_code text,
  p_reason text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_home_goals smallint;
  v_away_goals smallint;
  v_winner text;
  v_title text;
  v_body text;
BEGIN
  SELECT * INTO v_fixture
  FROM public.competition_fixtures
  WHERE id = p_fixture_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  IF v_fixture.status = 'played' THEN
    RETURN;
  END IF;

  IF p_loser_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name) THEN
    RAISE EXCEPTION 'Loser must be a club in this fixture';
  END IF;

  v_winner := CASE
    WHEN p_loser_club = v_fixture.home_club_short_name THEN v_fixture.away_club_short_name
    ELSE v_fixture.home_club_short_name
  END;

  IF v_winner = v_fixture.home_club_short_name THEN
    v_home_goals := 3;
    v_away_goals := 0;
  ELSE
    v_home_goals := 0;
    v_away_goals := 3;
  END IF;

  UPDATE public.competition_result_submissions
  SET status = 'rejected',
      reject_reason = 'Superseded by forfeit',
      responded_at = now()
  WHERE fixture_id = p_fixture_id
    AND status = 'pending';

  UPDATE public.competition_fixtures
  SET
    home_goals = v_home_goals,
    away_goals = v_away_goals,
    status = 'played',
    is_forfeit = true,
    forfeit_loser_club = p_loser_club
  WHERE id = p_fixture_id;

  PERFORM public.competition_apply_club_fine_tariff(
    p_loser_club,
    p_tariff_code,
    NULL,
    coalesce(p_reason, 'Match forfeit'),
    p_fixture_id,
    v_fixture.season_id
  );

  IF v_fixture.competition_type = 'cup' THEN
    PERFORM public.competition_cup_on_fixture_played(p_fixture_id);
  ELSIF v_fixture.competition_type = 'league' THEN
    PERFORM public.competition_try_pay_league_division_prizes(
      v_fixture.season_id,
      v_fixture.division
    );
  END IF;

  v_title := 'Match forfeited';
  v_body := format(
    '%s forfeited 3–0. %s',
    p_loser_club,
    coalesce(p_reason, '')
  );

  PERFORM public.owner_inbox_send(
    'match_forfeit_applied', v_title, v_body,
    v_fixture.home_club_short_name, NULL, p_fixture_id,
    NULL, NULL, NULL,
    'fixture_schedule.html?fixture=' || p_fixture_id::text,
    'forfeit:' || p_fixture_id::text || ':home',
    v_fixture.gpsl_month, v_fixture.season_id, NULL
  );
  PERFORM public.owner_inbox_send(
    'match_forfeit_applied', v_title, v_body,
    v_fixture.away_club_short_name, NULL, p_fixture_id,
    NULL, NULL, NULL,
    'fixture_schedule.html?fixture=' || p_fixture_id::text,
    'forfeit:' || p_fixture_id::text || ':away',
    v_fixture.gpsl_month, v_fixture.season_id, NULL
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Check-in resolution (no-show after window)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fixture_try_checkin_forfeit(p_fixture_id bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_kickoff timestamptz;
  v_window_end timestamptz;
  v_home_in boolean;
  v_away_in boolean;
  v_loser text;
BEGIN
  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND OR v_fixture.status <> 'scheduled' THEN
    RETURN false;
  END IF;

  v_kickoff := public.match_schedule_agreed_kickoff(p_fixture_id);
  IF v_kickoff IS NULL THEN
    RETURN false;
  END IF;

  v_window_end := v_kickoff + (public.match_schedule_checkin_minutes() || ' minutes')::interval;
  IF now() < v_window_end THEN
    RETURN false;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.competition_fixture_checkin c
    WHERE c.fixture_id = p_fixture_id
      AND c.club_short_name = v_fixture.home_club_short_name
  ) INTO v_home_in;

  SELECT EXISTS (
    SELECT 1 FROM public.competition_fixture_checkin c
    WHERE c.fixture_id = p_fixture_id
      AND c.club_short_name = v_fixture.away_club_short_name
  ) INTO v_away_in;

  IF v_home_in AND v_away_in THEN
    RETURN false;
  END IF;

  IF v_home_in AND NOT v_away_in THEN
    v_loser := v_fixture.away_club_short_name;
  ELSIF v_away_in AND NOT v_home_in THEN
    v_loser := v_fixture.home_club_short_name;
  ELSE
    RETURN false;
  END IF;

  PERFORM public.fixture_apply_forfeit(
    p_fixture_id,
    v_loser,
    'match_agreed_no_show',
    'No check-in during the agreed kick-off window'
  );

  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.match_schedule_assert_ready_to_play(p_fixture_id bigint)
RETURNS void
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_kickoff timestamptz;
  v_block_end timestamptz;
  v_home_in boolean;
  v_away_in boolean;
BEGIN
  IF public.is_gpsl_admin() THEN
    RETURN;
  END IF;

  PERFORM public.fixture_try_checkin_forfeit(p_fixture_id);

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF v_fixture.status = 'played' THEN
    RAISE EXCEPTION 'This fixture has already been played';
  END IF;

  v_kickoff := public.match_schedule_agreed_kickoff(p_fixture_id);
  IF v_kickoff IS NULL THEN
    RAISE EXCEPTION 'Kick-off time must be agreed before entering a result';
  END IF;

  v_block_end := v_kickoff + (public.match_schedule_block_minutes() || ' minutes')::interval;

  IF now() < v_kickoff THEN
    RAISE EXCEPTION 'Result entry opens at the agreed kick-off (%)',
      public.match_schedule_format_kickoff_uk(v_kickoff);
  END IF;

  IF now() >= v_block_end THEN
    RAISE EXCEPTION 'The 30-minute match block has ended for this kick-off';
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.competition_fixture_checkin c
    WHERE c.fixture_id = p_fixture_id
      AND c.club_short_name = v_fixture.home_club_short_name
  ) INTO v_home_in;

  SELECT EXISTS (
    SELECT 1 FROM public.competition_fixture_checkin c
    WHERE c.fixture_id = p_fixture_id
      AND c.club_short_name = v_fixture.away_club_short_name
  ) INTO v_away_in;

  IF NOT v_home_in OR NOT v_away_in THEN
    RAISE EXCEPTION 'Both clubs must check in before entering a result';
  END IF;
END;
$function$;

-- Guard result submission
CREATE OR REPLACE FUNCTION public.match_schedule_result_submission_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  PERFORM public.match_schedule_assert_ready_to_play(NEW.fixture_id);
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS match_schedule_result_submission_guard_trg
  ON public.competition_result_submissions;

CREATE TRIGGER match_schedule_result_submission_guard_trg
  BEFORE INSERT ON public.competition_result_submissions
  FOR EACH ROW
  EXECUTE FUNCTION public.match_schedule_result_submission_guard();

-- ---------------------------------------------------------------------------
-- Owner RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fixture_check_in(p_fixture_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_fixture public.competition_fixtures;
  v_kickoff timestamptz;
  v_window_end timestamptz;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  IF v_fixture.status <> 'scheduled' THEN
    RAISE EXCEPTION 'Fixture is not open for check-in';
  END IF;

  IF v_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name) THEN
    RAISE EXCEPTION 'Your club is not in this fixture';
  END IF;

  v_kickoff := public.match_schedule_agreed_kickoff(p_fixture_id);
  IF v_kickoff IS NULL THEN
    RAISE EXCEPTION 'Kick-off time is not agreed yet';
  END IF;

  v_window_end := v_kickoff + (public.match_schedule_checkin_minutes() || ' minutes')::interval;

  IF now() < v_kickoff THEN
    RAISE EXCEPTION 'Check-in opens at %', public.match_schedule_format_kickoff_uk(v_kickoff);
  END IF;

  IF now() >= v_window_end THEN
  PERFORM public.fixture_try_checkin_forfeit(p_fixture_id);
    RAISE EXCEPTION 'Check-in window has closed';
  END IF;

  INSERT INTO public.competition_fixture_checkin (fixture_id, club_short_name)
  VALUES (p_fixture_id, v_club)
  ON CONFLICT (fixture_id, club_short_name) DO NOTHING;

  RETURN jsonb_build_object('ok', true, 'checked_in_at', now());
END;
$function$;

CREATE OR REPLACE FUNCTION public.fixture_voluntary_reschedule_drop(p_fixture_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_fixture public.competition_fixtures;
  v_kickoff timestamptz;
  v_opponent text;
  v_title text;
  v_body text;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND OR v_fixture.status <> 'scheduled' THEN
    RAISE EXCEPTION 'Fixture not open for reschedule';
  END IF;

  IF v_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name) THEN
    RAISE EXCEPTION 'Your club is not in this fixture';
  END IF;

  v_kickoff := public.match_schedule_agreed_kickoff(p_fixture_id);
  IF v_kickoff IS NULL THEN
    RAISE EXCEPTION 'No agreed kick-off to drop';
  END IF;

  IF now() > v_kickoff - interval '24 hours' THEN
    RAISE EXCEPTION 'Within 24 hours of kick-off — use emergency drop instead';
  END IF;

  IF public.match_schedule_reschedule_used_this_month(
    v_fixture.season_id, v_club, v_fixture.gpsl_month
  ) THEN
    RAISE EXCEPTION 'You have already used your reschedule allowance for GPSL %',
      public.competition_gpsl_month_label(v_fixture.gpsl_month);
  END IF;

  INSERT INTO public.competition_club_month_reschedule_use (
    season_id, club_short_name, gpsl_month, fixture_id
  )
  VALUES (v_fixture.season_id, v_club, v_fixture.gpsl_month, p_fixture_id);

  PERFORM public.match_schedule_reset_to_unscheduled(p_fixture_id);

  v_opponent := public.competition_fixture_opponent(p_fixture_id, v_club);
  v_title := 'Match returned to scheduling';
  v_body := v_club || ' dropped the agreed time (24h+ notice). Propose a new kick-off on the schedule page.';

  PERFORM public.owner_inbox_send(
    'match_rescheduled', v_title, v_body,
    v_opponent, NULL, p_fixture_id,
    NULL, NULL, NULL,
    'fixture_schedule.html?fixture=' || p_fixture_id::text,
    'reschedule:' || p_fixture_id::text || ':' || v_club,
    v_fixture.gpsl_month, v_fixture.season_id, NULL
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.fixture_emergency_drop(p_fixture_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_fixture public.competition_fixtures;
  v_kickoff timestamptz;
  v_opponent text;
  v_used integer;
  v_title text;
  v_body text;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND OR v_fixture.status <> 'scheduled' THEN
    RAISE EXCEPTION 'Fixture not open';
  END IF;

  IF v_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name) THEN
    RAISE EXCEPTION 'Your club is not in this fixture';
  END IF;

  v_kickoff := public.match_schedule_agreed_kickoff(p_fixture_id);
  IF v_kickoff IS NULL THEN
    RAISE EXCEPTION 'No agreed kick-off';
  END IF;

  IF now() >= v_kickoff THEN
    RAISE EXCEPTION 'Kick-off has passed — check-in / forfeit rules apply';
  END IF;

  IF now() <= v_kickoff - interval '24 hours' THEN
    RAISE EXCEPTION 'More than 24 hours before kick-off — use voluntary reschedule instead';
  END IF;

  v_used := public.match_schedule_emergency_drops_used(v_fixture.season_id, v_club);
  IF v_used >= 2 THEN
    PERFORM public.fixture_apply_forfeit(
      p_fixture_id,
      v_club,
      'match_unauthorized_forfeit',
      'Emergency drops exhausted — late unavailable'
    );
    RETURN;
  END IF;

  INSERT INTO public.competition_club_emergency_drop_use (
    season_id, club_short_name, fixture_id
  )
  VALUES (v_fixture.season_id, v_club, p_fixture_id);

  PERFORM public.match_schedule_reset_to_unscheduled(p_fixture_id);

  v_opponent := public.competition_fixture_opponent(p_fixture_id, v_club);
  v_title := 'Emergency drop — reschedule needed';
  v_body := v_club || ' used an emergency drop (<24h). The match is back on the schedule page.';

  PERFORM public.owner_inbox_send(
    'match_emergency_drop', v_title, v_body,
    v_opponent, NULL, p_fixture_id,
    NULL, NULL, NULL,
    'fixture_schedule.html?fixture=' || p_fixture_id::text,
    'emergency:' || p_fixture_id::text || ':' || v_club,
    v_fixture.gpsl_month, v_fixture.season_id, NULL
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Holiday booking — block mid-month / after month opens
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_holiday_book(
  p_start_date date,
  p_end_date date
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_season_id bigint;
  v_starts timestamptz;
  v_ends timestamptz;
  v_days integer;
  v_used integer;
  v_max integer := public.club_holiday_max_days_per_season();
  v_id bigint;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  IF p_start_date IS NULL OR p_end_date IS NULL THEN
    RAISE EXCEPTION 'Start and end dates are required';
  END IF;

  IF p_end_date < p_start_date THEN
    RAISE EXCEPTION 'End date must be on or after start date';
  END IF;

  SELECT s.id INTO v_season_id
  FROM public.competition_seasons s
  WHERE s.is_current = true
    AND s.status = 'active'
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No active competition season';
  END IF;

  v_starts := (p_start_date::timestamp AT TIME ZONE 'Europe/London');
  v_ends := ((p_end_date + 1)::timestamp AT TIME ZONE 'Europe/London');
  v_days := public.club_holiday_inclusive_days(v_starts, v_ends);

  IF v_days > v_max THEN
    RAISE EXCEPTION 'A single booking cannot exceed % days', v_max;
  END IF;

  v_used := public.club_holiday_days_used(v_season_id, v_club);
  IF v_used + v_days > v_max THEN
    RAISE EXCEPTION 'Only % days of holiday per season (% used, % requested)',
      v_max, v_used, v_days;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.competition_season_calendar cal
    WHERE cal.season_id = v_season_id
      AND cal.unlock_at < v_ends
      AND cal.lock_at > v_starts
      AND now() >= cal.unlock_at
  ) THEN
    RAISE EXCEPTION 'Cannot book holiday for a GPSL month that has already started (Fri 19:00 UK)';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.club_owner_holidays h
    WHERE h.season_id = v_season_id
      AND h.club_short_name = v_club
      AND h.starts_at < v_ends
      AND h.ends_at > v_starts
  ) THEN
    RAISE EXCEPTION 'Holiday overlaps an existing booking for this season';
  END IF;

  IF v_ends <= now() THEN
    RAISE EXCEPTION 'Holiday must end in the future';
  END IF;

  INSERT INTO public.club_owner_holidays (
    season_id,
    club_short_name,
    owner_id,
    starts_at,
    ends_at,
    day_count
  )
  VALUES (
    v_season_id,
    v_club,
    auth.uid(),
    v_starts,
    v_ends,
    v_days::smallint
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Extend fixture context (Phase 2 fields)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.match_schedule_fixture_context(p_fixture_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_fixture public.competition_fixtures;
  v_schedule public.competition_fixture_schedule;
  v_schedule_found boolean := false;
  v_pending public.competition_fixture_schedule_proposal;
  v_role text;
  v_home text;
  v_away text;
  v_unlock timestamptz;
  v_lock timestamptz;
  v_slots jsonb;
  v_status text;
  v_agreed timestamptz;
  v_home_count smallint;
  v_away_count smallint;
  v_discord_hint boolean;
  v_pending_id bigint;
  v_kickoff timestamptz;
  v_home_in boolean := false;
  v_away_in boolean := false;
  v_my_in boolean := false;
  v_emergency_used integer;
  v_reschedule_used boolean;
BEGIN
  v_club := public.my_club_shortname();

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  IF NOT public.is_gpsl_admin()
     AND v_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name)
  THEN
    RAISE EXCEPTION 'You are not in this fixture';
  END IF;

  PERFORM public.fixture_try_checkin_forfeit(p_fixture_id);

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;

  v_home := v_fixture.home_club_short_name;
  v_away := v_fixture.away_club_short_name;

  IF v_club = v_home THEN v_role := 'home';
  ELSIF v_club = v_away THEN v_role := 'away';
  ELSE v_role := 'admin';
  END IF;

  SELECT * INTO v_schedule FROM public.competition_fixture_schedule WHERE fixture_id = p_fixture_id;
  v_schedule_found := FOUND;

  IF v_schedule_found THEN
    v_status := v_schedule.status;
    v_agreed := v_schedule.agreed_kickoff_at;
    v_home_count := v_schedule.home_proposal_count;
    v_away_count := v_schedule.away_proposal_count;
    v_discord_hint := v_schedule.discord_hint_shown;
    v_pending_id := v_schedule.pending_proposal_id;
  ELSE
    v_status := 'unscheduled';
    v_agreed := NULL;
    v_home_count := 0;
    v_away_count := 0;
    v_discord_hint := false;
    v_pending_id := NULL;
  END IF;

  IF v_pending_id IS NOT NULL THEN
    SELECT * INTO v_pending
    FROM public.competition_fixture_schedule_proposal
    WHERE id = v_pending_id;
  END IF;

  SELECT w.unlock_at, w.lock_at INTO v_unlock, v_lock
  FROM public.match_schedule_fixture_month_window(p_fixture_id) w;

  SELECT COALESCE(jsonb_agg(
    jsonb_build_object('iso_dow', s.iso_dow, 'hour', s.slot_minute / 60, 'minute', s.slot_minute % 60)
    ORDER BY s.iso_dow, s.slot_minute
  ), '[]'::jsonb)
  INTO v_slots
  FROM public.club_owner_availability_slot s
  WHERE s.season_id = v_fixture.season_id AND s.club_short_name = v_club;

  v_kickoff := v_agreed;
  IF v_kickoff IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1 FROM public.competition_fixture_checkin c
      WHERE c.fixture_id = p_fixture_id AND c.club_short_name = v_home
    ) INTO v_home_in;
    SELECT EXISTS (
      SELECT 1 FROM public.competition_fixture_checkin c
      WHERE c.fixture_id = p_fixture_id AND c.club_short_name = v_away
    ) INTO v_away_in;
    IF v_club IS NOT NULL THEN
      SELECT EXISTS (
        SELECT 1 FROM public.competition_fixture_checkin c
        WHERE c.fixture_id = p_fixture_id AND c.club_short_name = v_club
      ) INTO v_my_in;
    END IF;
  END IF;

  v_emergency_used := public.match_schedule_emergency_drops_used(v_fixture.season_id, v_club);
  v_reschedule_used := public.match_schedule_reschedule_used_this_month(
    v_fixture.season_id, v_club, v_fixture.gpsl_month
  );

  RETURN jsonb_build_object(
    'fixture', jsonb_build_object(
      'id', v_fixture.id,
      'gpsl_month', v_fixture.gpsl_month,
      'home_club_short_name', v_home,
      'away_club_short_name', v_away,
      'status', v_fixture.status,
      'competition_type', v_fixture.competition_type,
      'is_forfeit', v_fixture.is_forfeit
    ),
    'schedule', jsonb_build_object(
      'status', v_status,
      'agreed_kickoff_at', v_agreed,
      'home_proposal_count', v_home_count,
      'away_proposal_count', v_away_count,
      'discord_hint_shown', v_discord_hint
    ),
    'pending_proposal', CASE WHEN v_pending.id IS NULL THEN NULL ELSE jsonb_build_object(
      'id', v_pending.id,
      'proposed_by_club_short_name', v_pending.proposed_by_club_short_name,
      'kickoff_at', v_pending.kickoff_at
    ) END,
    'my_role', v_role,
    'month_window', jsonb_build_object('unlock_at', v_unlock, 'lock_at', v_lock),
    'my_timezone', public.match_schedule_club_timezone(v_club),
    'home_timezone', public.match_schedule_club_timezone(v_home),
    'away_timezone', public.match_schedule_club_timezone(v_away),
    'my_weekly_slots', v_slots,
    'intersection_slots', (
      SELECT COALESCE(jsonb_agg(i.kickoff_at ORDER BY i.kickoff_at), '[]'::jsonb)
      FROM public.match_schedule_intersection_slots(p_fixture_id) i
    ),
    'can_propose_first', (v_role = 'home' AND v_status = 'unscheduled' AND v_fixture.status = 'scheduled'),
    'can_respond', (
      v_pending.id IS NOT NULL
      AND v_pending.proposed_by_club_short_name <> v_club
      AND v_status = 'negotiating'
    ),
    'checkin', jsonb_build_object(
      'home_checked_in', v_home_in,
      'away_checked_in', v_away_in,
      'my_checked_in', v_my_in,
      'window_opens_at', v_kickoff,
      'window_closes_at', CASE WHEN v_kickoff IS NULL THEN NULL
        ELSE v_kickoff + (public.match_schedule_checkin_minutes() || ' minutes')::interval END,
      'play_block_ends_at', CASE WHEN v_kickoff IS NULL THEN NULL
        ELSE v_kickoff + (public.match_schedule_block_minutes() || ' minutes')::interval END,
      'can_check_in', (
        v_fixture.status = 'scheduled'
        AND v_kickoff IS NOT NULL
        AND now() >= v_kickoff
        AND now() < v_kickoff + (public.match_schedule_checkin_minutes() || ' minutes')::interval
        AND NOT v_my_in
      ),
      'can_play', (
        v_fixture.status = 'scheduled'
        AND v_kickoff IS NOT NULL
        AND v_home_in AND v_away_in
        AND now() >= v_kickoff
        AND now() < v_kickoff + (public.match_schedule_block_minutes() || ' minutes')::interval
      )
    ),
    'allowances', jsonb_build_object(
      'emergency_drops_used', v_emergency_used,
      'emergency_drops_remaining', greatest(0, 2 - v_emergency_used),
      'reschedule_used_this_month', v_reschedule_used,
      'can_voluntary_drop', (
        v_fixture.status = 'scheduled'
        AND v_kickoff IS NOT NULL
        AND now() <= v_kickoff - interval '24 hours'
        AND NOT v_reschedule_used
      ),
      'can_emergency_drop', (
        v_fixture.status = 'scheduled'
        AND v_kickoff IS NOT NULL
        AND now() < v_kickoff
        AND now() > v_kickoff - interval '24 hours'
      )
    )
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Fixtures public view — check-in flags + forfeit
-- ---------------------------------------------------------------------------

DROP VIEW IF EXISTS public.competition_cup_qualified_public;
DROP VIEW IF EXISTS public.competition_cup_bracket_public;
DROP VIEW IF EXISTS public.competition_fixtures_public;

CREATE VIEW public.competition_fixtures_public
WITH (security_invoker = false)
AS
SELECT
  f.id,
  f.season_id,
  f.division,
  f.competition_type,
  f.cup_code,
  f.cup_round,
  f.cup_match,
  f.matchday,
  f.gpsl_month,
  f.week_in_month,
  f.home_club_short_name,
  hc."Club" AS home_club_name,
  f.away_club_short_name,
  ac."Club" AS away_club_name,
  f.weather,
  f.pitch_condition,
  f.kit_season,
  public.competition_club_continent(f.home_club_short_name) AS home_continent,
  f.home_goals,
  f.away_goals,
  f.status,
  f.is_forfeit,
  sub.submission_id,
  sub.submission_status,
  sub.submitted_by_club,
  sub.proposed_home_goals,
  sub.proposed_away_goals,
  sub.proposed_et_home_goals,
  sub.proposed_et_away_goals,
  sub.proposed_pen_winner_club,
  COALESCE(sch.status, 'unscheduled') AS schedule_status,
  sch.agreed_kickoff_at,
  sch.pending_proposal_id AS schedule_pending_proposal_id,
  sch.home_proposal_count AS schedule_home_proposal_count,
  sch.away_proposal_count AS schedule_away_proposal_count,
  COALESCE(sch.discord_hint_shown, false) AS schedule_discord_hint,
  chk.home_checked_in,
  chk.away_checked_in
FROM public.competition_fixtures f
JOIN public.competition_seasons s ON s.id = f.season_id
JOIN public."Clubs" hc ON hc."ShortName" = f.home_club_short_name
JOIN public."Clubs" ac ON ac."ShortName" = f.away_club_short_name
LEFT JOIN public.competition_fixture_schedule sch ON sch.fixture_id = f.id
LEFT JOIN LATERAL (
  SELECT
    EXISTS (
      SELECT 1 FROM public.competition_fixture_checkin c
      WHERE c.fixture_id = f.id AND c.club_short_name = f.home_club_short_name
    ) AS home_checked_in,
    EXISTS (
      SELECT 1 FROM public.competition_fixture_checkin c
      WHERE c.fixture_id = f.id AND c.club_short_name = f.away_club_short_name
    ) AS away_checked_in
) chk ON true
LEFT JOIN LATERAL (
  SELECT
    rs.id AS submission_id,
    rs.status AS submission_status,
    rs.submitted_by_club,
    rs.home_goals AS proposed_home_goals,
    rs.away_goals AS proposed_away_goals,
    rs.et_home_goals AS proposed_et_home_goals,
    rs.et_away_goals AS proposed_et_away_goals,
    rs.pen_winner_club_short_name AS proposed_pen_winner_club
  FROM public.competition_result_submissions rs
  WHERE rs.fixture_id = f.id
    AND rs.status = 'pending'
    AND (
      public.is_gpsl_admin()
      OR public.my_club_shortname() = f.home_club_short_name
      OR public.my_club_shortname() = f.away_club_short_name
    )
  LIMIT 1
) sub ON true
WHERE s.status = 'active' AND s.is_current = true;

CREATE VIEW public.competition_cup_bracket_public
WITH (security_invoker = false)
AS
SELECT
  n.id, n.season_id, n.cup_code, n.round_no, n.match_no,
  n.home_club_short_name, hc."Club" AS home_club_name,
  n.away_club_short_name, ac."Club" AS away_club_name,
  n.winner_club_short_name, wc."Club" AS winner_club_name,
  n.fixture_id, f.status AS fixture_status, f.home_goals, f.away_goals,
  n.child_node_id, n.child_slot
FROM public.competition_cup_bracket_nodes n
JOIN public.competition_seasons s ON s.id = n.season_id
LEFT JOIN public."Clubs" hc ON hc."ShortName" = n.home_club_short_name
LEFT JOIN public."Clubs" ac ON ac."ShortName" = n.away_club_short_name
LEFT JOIN public."Clubs" wc ON wc."ShortName" = n.winner_club_short_name
LEFT JOIN public.competition_fixtures f ON f.id = n.fixture_id
WHERE s.status = 'active' AND s.is_current = true;

CREATE VIEW public.competition_cup_qualified_public
WITH (security_invoker = false)
AS
SELECT s.id AS season_id, cup.cup_code, q.club_short_name
FROM public.competition_seasons s
CROSS JOIN (VALUES ('super8'), ('plate'), ('shield'), ('spoon'), ('league_cup')) AS cup(cup_code)
CROSS JOIN LATERAL unnest(public.competition_qualify_cup_clubs(s.id, cup.cup_code)) AS q(club_short_name)
WHERE s.is_current = true AND s.status = 'active';

-- RLS check-in read
ALTER TABLE public.competition_fixture_checkin ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_fixture_checkin_select ON public.competition_fixture_checkin;
CREATE POLICY competition_fixture_checkin_select ON public.competition_fixture_checkin
  FOR SELECT TO authenticated
  USING (
    public.is_gpsl_admin()
    OR EXISTS (
      SELECT 1 FROM public.competition_fixtures fx
      WHERE fx.id = fixture_id
        AND public.my_club_shortname() IN (fx.home_club_short_name, fx.away_club_short_name)
    )
  );

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

GRANT SELECT ON public.competition_fixtures_public TO authenticated;
GRANT SELECT ON public.competition_fixtures_public TO anon;
GRANT SELECT ON public.competition_cup_bracket_public TO authenticated;
GRANT SELECT ON public.competition_cup_qualified_public TO authenticated;
GRANT SELECT ON public.competition_fixture_checkin TO authenticated;

GRANT EXECUTE ON FUNCTION public.fixture_check_in(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fixture_voluntary_reschedule_drop(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fixture_emergency_drop(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.match_schedule_assert_ready_to_play(bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';
