-- =============================================================================
-- Match scheduling — Phase 1 (availability, propose / counter / accept)
-- Run after: competition_real_world_calendar.sql, club_owner_holidays.sql,
--            competition_continental_conditions.sql (fixtures public view),
--            owner_inbox_fine_fix.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Owner timezone (display; slots stored/compared in UK / UTC)
-- ---------------------------------------------------------------------------

ALTER TABLE public."Clubs"
  ADD COLUMN IF NOT EXISTS owner_timezone text NOT NULL DEFAULT 'Europe/London';

-- ---------------------------------------------------------------------------
-- Weekly availability (30-minute blocks, UK wall-clock iso_dow + minute)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.club_owner_availability_slot (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  iso_dow smallint NOT NULL CHECK (iso_dow BETWEEN 1 AND 7),
  slot_minute smallint NOT NULL CHECK (
    slot_minute >= 0
    AND slot_minute <= 1410
    AND slot_minute % 30 = 0
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT club_owner_availability_slot_unique
    UNIQUE (season_id, club_short_name, iso_dow, slot_minute)
);

CREATE INDEX IF NOT EXISTS club_owner_availability_slot_club_idx
  ON public.club_owner_availability_slot (season_id, club_short_name);

-- One-off unavailable blocks (absences) within the season
CREATE TABLE IF NOT EXISTS public.club_owner_availability_unavailable (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT club_owner_availability_unavailable_window CHECK (ends_at > starts_at)
);

CREATE INDEX IF NOT EXISTS club_owner_availability_unavail_club_idx
  ON public.club_owner_availability_unavailable (season_id, club_short_name);

-- ---------------------------------------------------------------------------
-- Fixture schedule state
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_fixture_schedule (
  fixture_id bigint PRIMARY KEY REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'unscheduled' CHECK (
    status IN ('unscheduled', 'negotiating', 'agreed')
  ),
  home_proposal_count smallint NOT NULL DEFAULT 0 CHECK (home_proposal_count >= 0),
  away_proposal_count smallint NOT NULL DEFAULT 0 CHECK (away_proposal_count >= 0),
  agreed_kickoff_at timestamptz,
  pending_proposal_id bigint,
  discord_hint_shown boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.competition_fixture_schedule_proposal (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fixture_id bigint NOT NULL REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  proposed_by_club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  kickoff_at timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'accepted', 'superseded', 'withdrawn')
  ),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS competition_fixture_schedule_proposal_fixture_idx
  ON public.competition_fixture_schedule_proposal (fixture_id, created_at DESC);

ALTER TABLE public.competition_fixture_schedule
  DROP CONSTRAINT IF EXISTS competition_fixture_schedule_pending_fk;

ALTER TABLE public.competition_fixture_schedule
  ADD CONSTRAINT competition_fixture_schedule_pending_fk
  FOREIGN KEY (pending_proposal_id)
  REFERENCES public.competition_fixture_schedule_proposal (id)
  ON DELETE SET NULL;

-- Inbox link to pending proposal
ALTER TABLE public.competition_inbox
  ADD COLUMN IF NOT EXISTS schedule_proposal_id bigint
  REFERENCES public.competition_fixture_schedule_proposal (id) ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- Inbox message types
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_inbox
  DROP CONSTRAINT IF EXISTS competition_inbox_message_type_check;

ALTER TABLE public.competition_inbox
  ADD CONSTRAINT competition_inbox_message_type_check
  CHECK (
    message_type IN (
      'welcome_gpsl',
      'result_submitted',
      'result_to_confirm',
      'result_rejected',
      'result_confirmed',
      'transfer_signed',
      'transfer_sold',
      'transfer_upcoming',
      'draft_scheduled',
      'fine_applied',
      'points_deduction',
      'nation_pick_turn',
      'nation_selection_open',
      'season_expectations',
      'season_overview',
      'player_awards',
      'monthly_fixtures',
      'match_time_proposed',
      'match_time_countered',
      'match_time_accepted'
    )
  );

CREATE OR REPLACE FUNCTION public.owner_inbox_send(
  p_message_type text,
  p_title text,
  p_body text,
  p_recipient_club text DEFAULT NULL,
  p_owner_id uuid DEFAULT NULL,
  p_fixture_id bigint DEFAULT NULL,
  p_submission_id bigint DEFAULT NULL,
  p_transfer_history_id bigint DEFAULT NULL,
  p_transfer_listing_id bigint DEFAULT NULL,
  p_action_href text DEFAULT NULL,
  p_dedupe_key text DEFAULT NULL,
  p_gpsl_month text DEFAULT NULL,
  p_season_id bigint DEFAULT NULL,
  p_schedule_proposal_id bigint DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint;
  v_club text := nullif(btrim(p_recipient_club), '');
BEGIN
  IF v_club IS NULL AND p_owner_id IS NULL THEN
    RETURN NULL;
  END IF;
  IF v_club = 'FOREIGN' THEN
    RETURN NULL;
  END IF;

  IF p_dedupe_key IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.competition_inbox i WHERE i.dedupe_key = p_dedupe_key
  ) THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.competition_inbox (
    recipient_club_short_name, owner_id, message_type,
    fixture_id, submission_id, transfer_history_id, transfer_listing_id,
    title, body, action_href, dedupe_key, gpsl_month, season_id,
    schedule_proposal_id
  )
  VALUES (
    v_club, p_owner_id, p_message_type,
    p_fixture_id, p_submission_id, p_transfer_history_id, p_transfer_listing_id,
    p_title, p_body, p_action_href, p_dedupe_key, p_gpsl_month, p_season_id,
    p_schedule_proposal_id
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.match_schedule_format_kickoff_uk(p_kickoff timestamptz)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT to_char(p_kickoff AT TIME ZONE 'Europe/London', 'Dy DD Mon YYYY HH24:MI') || ' UK';
$$;

CREATE OR REPLACE FUNCTION public.match_schedule_kickoff_is_slot(p_kickoff timestamptz)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT
    EXTRACT(MINUTE FROM p_kickoff AT TIME ZONE 'Europe/London')::integer % 30 = 0
    AND EXTRACT(SECOND FROM p_kickoff) = 0;
$$;

CREATE OR REPLACE FUNCTION public.match_schedule_club_timezone(p_club text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(NULLIF(btrim(c.owner_timezone), ''), 'Europe/London')
  FROM public."Clubs" c
  WHERE c."ShortName" = p_club;
$$;

CREATE OR REPLACE FUNCTION public.match_schedule_fixture_month_window(p_fixture_id bigint)
RETURNS TABLE (unlock_at timestamptz, lock_at timestamptz, gpsl_month text)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
BEGIN
  SELECT * INTO v_fixture
  FROM public.competition_fixtures f
  WHERE f.id = p_fixture_id;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT m.unlock_at, m.lock_at, m.gpsl_month
  FROM public.competition_season_calendar m
  WHERE m.season_id = v_fixture.season_id
    AND m.gpsl_month = v_fixture.gpsl_month;
END;
$function$;

CREATE OR REPLACE FUNCTION public.match_schedule_club_available_at(
  p_season_id bigint,
  p_club_short_name text,
  p_kickoff timestamptz
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_local timestamp;
  v_isodow smallint;
  v_slot_minute smallint;
BEGIN
  IF p_club_short_name IS NULL OR btrim(p_club_short_name) = '' THEN
    RETURN false;
  END IF;

  IF NOT public.match_schedule_kickoff_is_slot(p_kickoff) THEN
    RETURN false;
  END IF;

  v_local := p_kickoff AT TIME ZONE 'Europe/London';
  v_isodow := EXTRACT(ISODOW FROM v_local)::smallint;
  v_slot_minute := (
    EXTRACT(HOUR FROM v_local) * 60 + EXTRACT(MINUTE FROM v_local)
  )::smallint;

  IF NOT EXISTS (
    SELECT 1
    FROM public.club_owner_availability_slot s
    WHERE s.season_id = p_season_id
      AND s.club_short_name = p_club_short_name
      AND s.iso_dow = v_isodow
      AND s.slot_minute = v_slot_minute
  ) THEN
    RETURN false;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.club_owner_holidays h
    WHERE h.season_id = p_season_id
      AND h.club_short_name = p_club_short_name
      AND p_kickoff >= h.starts_at
      AND p_kickoff < h.ends_at
  ) THEN
    RETURN false;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.club_owner_availability_unavailable u
    WHERE u.season_id = p_season_id
      AND u.club_short_name = p_club_short_name
      AND p_kickoff >= u.starts_at
      AND p_kickoff < u.ends_at
  ) THEN
    RETURN false;
  END IF;

  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.match_schedule_assert_kickoff_valid(
  p_fixture_id bigint,
  p_kickoff timestamptz
)
RETURNS public.competition_fixtures
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_unlock timestamptz;
  v_lock timestamptz;
BEGIN
  SELECT * INTO v_fixture
  FROM public.competition_fixtures f
  WHERE f.id = p_fixture_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  IF v_fixture.status <> 'scheduled' THEN
    RAISE EXCEPTION 'Fixture is not open for scheduling';
  END IF;

  IF NOT public.match_schedule_kickoff_is_slot(p_kickoff) THEN
    RAISE EXCEPTION 'Kick-off must be on a 30-minute boundary (UK time)';
  END IF;

  SELECT w.unlock_at, w.lock_at
  INTO v_unlock, v_lock
  FROM public.match_schedule_fixture_month_window(p_fixture_id) w;

  IF v_unlock IS NULL THEN
    RAISE EXCEPTION 'No GPSL month window for this fixture';
  END IF;

  IF p_kickoff < v_unlock OR p_kickoff + interval '30 minutes' > v_lock THEN
    RAISE EXCEPTION 'Kick-off must fall within the GPSL month window (% – % UK)',
      public.match_schedule_format_kickoff_uk(v_unlock),
      public.match_schedule_format_kickoff_uk(v_lock);
  END IF;

  IF NOT public.match_schedule_club_available_at(v_fixture.season_id, v_fixture.home_club_short_name, p_kickoff) THEN
    RAISE EXCEPTION 'Home club is not available at that time';
  END IF;

  IF NOT public.match_schedule_club_available_at(v_fixture.season_id, v_fixture.away_club_short_name, p_kickoff) THEN
    RAISE EXCEPTION 'Away club is not available at that time';
  END IF;

  RETURN v_fixture;
END;
$function$;

CREATE OR REPLACE FUNCTION public.match_schedule_ensure_row(p_fixture_id bigint)
RETURNS public.competition_fixture_schedule
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_row public.competition_fixture_schedule;
BEGIN
  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  INSERT INTO public.competition_fixture_schedule (fixture_id, season_id, status)
  VALUES (p_fixture_id, v_fixture.season_id, 'unscheduled')
  ON CONFLICT (fixture_id) DO NOTHING;

  SELECT * INTO v_row
  FROM public.competition_fixture_schedule
  WHERE fixture_id = p_fixture_id;

  RETURN v_row;
END;
$function$;

CREATE OR REPLACE FUNCTION public.match_schedule_intersection_slots(p_fixture_id bigint)
RETURNS TABLE (kickoff_at timestamptz)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_unlock timestamptz;
  v_lock timestamptz;
  v_cursor timestamptz;
BEGIN
  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT w.unlock_at, w.lock_at INTO v_unlock, v_lock
  FROM public.match_schedule_fixture_month_window(p_fixture_id) w;

  IF v_unlock IS NULL THEN
    RETURN;
  END IF;

  v_cursor := v_unlock;
  WHILE v_cursor + interval '30 minutes' <= v_lock LOOP
    IF public.match_schedule_club_available_at(v_fixture.season_id, v_fixture.home_club_short_name, v_cursor)
       AND public.match_schedule_club_available_at(v_fixture.season_id, v_fixture.away_club_short_name, v_cursor)
    THEN
      kickoff_at := v_cursor;
      RETURN NEXT;
    END IF;
    v_cursor := v_cursor + interval '30 minutes';
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.match_schedule_notify_pair(
  p_fixture public.competition_fixtures,
  p_message_type text,
  p_title text,
  p_body text,
  p_proposal_id bigint,
  p_dedupe_suffix text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_href text;
BEGIN
  v_href := 'fixture_schedule.html?fixture=' || p_fixture.id::text;

  PERFORM public.owner_inbox_send(
    p_message_type,
    p_title,
    p_body,
    p_fixture.home_club_short_name,
    NULL,
    p_fixture.id,
    NULL, NULL, NULL,
    v_href,
    'schedule:' || p_fixture.id::text || ':' || p_dedupe_suffix || ':home',
    p_fixture.gpsl_month,
    p_fixture.season_id,
    p_proposal_id
  );

  PERFORM public.owner_inbox_send(
    p_message_type,
    p_title,
    p_body,
    p_fixture.away_club_short_name,
    NULL,
    p_fixture.id,
    NULL, NULL, NULL,
    v_href,
    'schedule:' || p_fixture.id::text || ':' || p_dedupe_suffix || ':away',
    p_fixture.gpsl_month,
    p_fixture.season_id,
    p_proposal_id
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Owner RPCs — availability
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_owner_timezone_set(p_timezone text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  IF p_timezone IS NULL OR btrim(p_timezone) = '' THEN
    RAISE EXCEPTION 'Timezone is required';
  END IF;

  UPDATE public."Clubs"
  SET owner_timezone = btrim(p_timezone)
  WHERE "ShortName" = v_club
    AND owner_id = auth.uid();
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_availability_save_weekly(p_slots jsonb)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_season_id bigint;
  v_slot jsonb;
  v_isodow smallint;
  v_minute smallint;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT s.id INTO v_season_id
  FROM public.competition_seasons s
  WHERE s.is_current = true AND s.status = 'active'
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No active competition season';
  END IF;

  IF p_slots IS NULL OR jsonb_typeof(p_slots) <> 'array' THEN
    RAISE EXCEPTION 'Slots must be a JSON array';
  END IF;

  DELETE FROM public.club_owner_availability_slot
  WHERE season_id = v_season_id
    AND club_short_name = v_club;

  FOR v_slot IN SELECT * FROM jsonb_array_elements(p_slots)
  LOOP
    v_isodow := (v_slot->>'iso_dow')::smallint;
    v_minute := (
      COALESCE((v_slot->>'hour')::integer, 0) * 60
      + COALESCE((v_slot->>'minute')::integer, 0)
    )::smallint;

    IF v_isodow IS NULL OR v_isodow < 1 OR v_isodow > 7 THEN
      RAISE EXCEPTION 'Invalid iso_dow in slot';
    END IF;

    IF v_minute % 30 <> 0 OR v_minute < 0 OR v_minute > 1410 THEN
      RAISE EXCEPTION 'Invalid time in slot (30-minute blocks only)';
    END IF;

    INSERT INTO public.club_owner_availability_slot (
      season_id, club_short_name, owner_id, iso_dow, slot_minute
    )
    VALUES (v_season_id, v_club, auth.uid(), v_isodow, v_minute);
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_availability_add_unavailable(
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_note text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_season_id bigint;
  v_id bigint;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  IF p_starts_at IS NULL OR p_ends_at IS NULL OR p_ends_at <= p_starts_at THEN
    RAISE EXCEPTION 'Invalid unavailable window';
  END IF;

  SELECT s.id INTO v_season_id
  FROM public.competition_seasons s
  WHERE s.is_current = true AND s.status = 'active'
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No active competition season';
  END IF;

  INSERT INTO public.club_owner_availability_unavailable (
    season_id, club_short_name, owner_id, starts_at, ends_at, note
  )
  VALUES (v_season_id, v_club, auth.uid(), p_starts_at, p_ends_at, nullif(btrim(p_note), ''))
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_availability_remove_unavailable(p_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  DELETE FROM public.club_owner_availability_unavailable u
  WHERE u.id = p_id
    AND u.club_short_name = v_club
    AND u.owner_id = auth.uid();
END;
$function$;

-- ---------------------------------------------------------------------------
-- Schedule RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fixture_schedule_propose(
  p_fixture_id bigint,
  p_kickoff_at timestamptz
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_fixture public.competition_fixtures;
  v_schedule public.competition_fixture_schedule;
  v_proposal_id bigint;
  v_title text;
  v_body text;
  v_fmt text;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  v_fixture := public.match_schedule_assert_kickoff_valid(p_fixture_id, p_kickoff_at);
  v_schedule := public.match_schedule_ensure_row(p_fixture_id);

  IF v_schedule.status = 'agreed' THEN
    RAISE EXCEPTION 'Kick-off is already agreed for this fixture';
  END IF;

  IF v_schedule.status = 'unscheduled' THEN
    IF v_club <> v_fixture.home_club_short_name THEN
      RAISE EXCEPTION 'Home club must propose the first kick-off time';
    END IF;
  ELSE
    IF v_schedule.pending_proposal_id IS NULL THEN
      RAISE EXCEPTION 'No pending proposal to respond to';
    END IF;

    IF EXISTS (
      SELECT 1
      FROM public.competition_fixture_schedule_proposal p
      WHERE p.id = v_schedule.pending_proposal_id
        AND p.proposed_by_club_short_name = v_club
    ) THEN
      RAISE EXCEPTION 'Wait for your opponent to respond to your proposal';
    END IF;
  END IF;

  IF v_schedule.pending_proposal_id IS NOT NULL THEN
    UPDATE public.competition_fixture_schedule_proposal
    SET status = 'superseded'
    WHERE id = v_schedule.pending_proposal_id
      AND status = 'pending';
  END IF;

  INSERT INTO public.competition_fixture_schedule_proposal (
    fixture_id, proposed_by_club_short_name, kickoff_at, status
  )
  VALUES (p_fixture_id, v_club, p_kickoff_at, 'pending')
  RETURNING id INTO v_proposal_id;

  UPDATE public.competition_fixture_schedule
  SET
    status = 'negotiating',
    pending_proposal_id = v_proposal_id,
    home_proposal_count = home_proposal_count + CASE WHEN v_club = v_fixture.home_club_short_name THEN 1 ELSE 0 END,
    away_proposal_count = away_proposal_count + CASE WHEN v_club = v_fixture.away_club_short_name THEN 1 ELSE 0 END,
    discord_hint_shown = (
      (home_proposal_count + CASE WHEN v_club = v_fixture.home_club_short_name THEN 1 ELSE 0 END) >= 2
      AND (away_proposal_count + CASE WHEN v_club = v_fixture.away_club_short_name THEN 1 ELSE 0 END) >= 2
    ),
    updated_at = now()
  WHERE fixture_id = p_fixture_id;

  v_fmt := public.match_schedule_format_kickoff_uk(p_kickoff_at);
  v_title := CASE
    WHEN v_schedule.status = 'unscheduled' THEN 'Match time proposed'
    ELSE 'Counter-proposal received'
  END;
  v_body := v_club || ' proposed ' || v_fmt || E'.\nOpen Schedule to accept or suggest another time.';

  PERFORM public.match_schedule_notify_pair(
    v_fixture,
    CASE WHEN v_schedule.status = 'unscheduled' THEN 'match_time_proposed' ELSE 'match_time_countered' END,
    v_title,
    v_body,
    v_proposal_id,
    'prop:' || v_proposal_id::text
  );

  RETURN v_proposal_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fixture_schedule_accept(p_proposal_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_proposal public.competition_fixture_schedule_proposal;
  v_fixture public.competition_fixtures;
  v_opponent text;
  v_fmt text;
  v_body text;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_proposal
  FROM public.competition_fixture_schedule_proposal p
  WHERE p.id = p_proposal_id
    AND p.status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Proposal not found or no longer pending';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_proposal.fixture_id;
  v_opponent := public.competition_fixture_opponent(v_proposal.fixture_id, v_club);

  IF v_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name) THEN
    RAISE EXCEPTION 'You are not in this fixture';
  END IF;

  IF v_proposal.proposed_by_club_short_name = v_club THEN
    RAISE EXCEPTION 'You cannot accept your own proposal';
  END IF;

  PERFORM public.match_schedule_assert_kickoff_valid(v_proposal.fixture_id, v_proposal.kickoff_at);

  UPDATE public.competition_fixture_schedule_proposal
  SET status = 'accepted'
  WHERE id = p_proposal_id;

  UPDATE public.competition_fixture_schedule_proposal
  SET status = 'superseded'
  WHERE fixture_id = v_proposal.fixture_id
    AND status = 'pending'
    AND id <> p_proposal_id;

  UPDATE public.competition_fixture_schedule
  SET
    status = 'agreed',
    agreed_kickoff_at = v_proposal.kickoff_at,
    pending_proposal_id = NULL,
    updated_at = now()
  WHERE fixture_id = v_proposal.fixture_id;

  v_fmt := public.match_schedule_format_kickoff_uk(v_proposal.kickoff_at);
  v_body := 'Kick-off agreed: ' || v_fmt || E'.\nBoth clubs confirmed this time.';

  PERFORM public.match_schedule_notify_pair(
    v_fixture,
    'match_time_accepted',
    'Match time agreed',
    v_body,
    p_proposal_id,
    'accept:' || p_proposal_id::text
  );
END;
$function$;

-- Combined context for UI
CREATE OR REPLACE FUNCTION public.match_schedule_fixture_context(p_fixture_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_fixture public.competition_fixtures;
  v_schedule public.competition_fixture_schedule;
  v_schedule_found boolean := false;
  v_pending public.competition_fixture_schedule_proposal;
  v_role text;
  v_home text;
  v_away text;
  v_unlock timestamptz;
  v_lock timestamptz;
  v_slots jsonb;
  v_status text;
  v_agreed timestamptz;
  v_home_count smallint;
  v_away_count smallint;
  v_discord_hint boolean;
  v_pending_id bigint;
BEGIN
  v_club := public.my_club_shortname();

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  IF NOT public.is_gpsl_admin()
     AND v_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name)
  THEN
    RAISE EXCEPTION 'You are not in this fixture';
  END IF;

  v_home := v_fixture.home_club_short_name;
  v_away := v_fixture.away_club_short_name;

  IF v_club = v_home THEN
    v_role := 'home';
  ELSIF v_club = v_away THEN
    v_role := 'away';
  ELSE
    v_role := 'admin';
  END IF;

  SELECT * INTO v_schedule
  FROM public.competition_fixture_schedule
  WHERE fixture_id = p_fixture_id;

  v_schedule_found := FOUND;

  IF v_schedule_found THEN
    v_status := v_schedule.status;
    v_agreed := v_schedule.agreed_kickoff_at;
    v_home_count := v_schedule.home_proposal_count;
    v_away_count := v_schedule.away_proposal_count;
    v_discord_hint := v_schedule.discord_hint_shown;
    v_pending_id := v_schedule.pending_proposal_id;
  ELSE
    v_status := 'unscheduled';
    v_agreed := NULL;
    v_home_count := 0;
    v_away_count := 0;
    v_discord_hint := false;
    v_pending_id := NULL;
  END IF;

  IF v_pending_id IS NOT NULL THEN

    SELECT * INTO v_pending
    FROM public.competition_fixture_schedule_proposal
    WHERE id = v_pending_id;
  END IF;

  SELECT w.unlock_at, w.lock_at INTO v_unlock, v_lock
  FROM public.match_schedule_fixture_month_window(p_fixture_id) w;

  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'iso_dow', s.iso_dow,
      'hour', s.slot_minute / 60,
      'minute', s.slot_minute % 60
    )
    ORDER BY s.iso_dow, s.slot_minute
  ), '[]'::jsonb)
  INTO v_slots
  FROM public.club_owner_availability_slot s
  WHERE s.season_id = v_fixture.season_id
    AND s.club_short_name = v_club;

  RETURN jsonb_build_object(
    'fixture', jsonb_build_object(
      'id', v_fixture.id,
      'gpsl_month', v_fixture.gpsl_month,
      'home_club_short_name', v_home,
      'away_club_short_name', v_away,
      'status', v_fixture.status,
      'competition_type', v_fixture.competition_type
    ),
    'schedule', jsonb_build_object(
      'status', v_status,
      'agreed_kickoff_at', v_agreed,
      'home_proposal_count', v_home_count,
      'away_proposal_count', v_away_count,
      'discord_hint_shown', v_discord_hint
    ),
    'pending_proposal', CASE WHEN v_pending.id IS NULL THEN NULL ELSE jsonb_build_object(
      'id', v_pending.id,
      'proposed_by_club_short_name', v_pending.proposed_by_club_short_name,
      'kickoff_at', v_pending.kickoff_at
    ) END,
    'my_role', v_role,
    'month_window', jsonb_build_object('unlock_at', v_unlock, 'lock_at', v_lock),
    'my_timezone', public.match_schedule_club_timezone(v_club),
    'home_timezone', public.match_schedule_club_timezone(v_home),
    'away_timezone', public.match_schedule_club_timezone(v_away),
    'my_weekly_slots', v_slots,
    'intersection_slots', (
      SELECT COALESCE(jsonb_agg(i.kickoff_at ORDER BY i.kickoff_at), '[]'::jsonb)
      FROM public.match_schedule_intersection_slots(p_fixture_id) i
    ),
    'can_propose_first', (v_role = 'home' AND v_status = 'unscheduled'),
    'can_respond', (
      v_pending.id IS NOT NULL
      AND v_pending.proposed_by_club_short_name <> v_club
      AND v_status = 'negotiating'
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_availability_context()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_season_id bigint;
  v_tz text;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT s.id INTO v_season_id
  FROM public.competition_seasons s
  WHERE s.is_current = true AND s.status = 'active'
  LIMIT 1;

  v_tz := public.match_schedule_club_timezone(v_club);

  RETURN jsonb_build_object(
    'club_short_name', v_club,
    'season_id', v_season_id,
    'timezone', v_tz,
    'weekly_slots', (
      SELECT COALESCE(jsonb_agg(
        jsonb_build_object(
          'iso_dow', s.iso_dow,
          'hour', s.slot_minute / 60,
          'minute', s.slot_minute % 60
        )
        ORDER BY s.iso_dow, s.slot_minute
      ), '[]'::jsonb)
      FROM public.club_owner_availability_slot s
      WHERE s.season_id = v_season_id AND s.club_short_name = v_club
    ),
    'unavailable', (
      SELECT COALESCE(jsonb_agg(
        jsonb_build_object(
          'id', u.id,
          'starts_at', u.starts_at,
          'ends_at', u.ends_at,
          'note', u.note
        )
        ORDER BY u.starts_at
      ), '[]'::jsonb)
      FROM public.club_owner_availability_unavailable u
      WHERE u.season_id = v_season_id AND u.club_short_name = v_club
    ),
    'holidays', (
      SELECT COALESCE(jsonb_agg(
        jsonb_build_object(
          'id', h.id,
          'starts_at', h.starts_at,
          'ends_at', h.ends_at,
          'day_count', h.day_count
        )
        ORDER BY h.starts_at
      ), '[]'::jsonb)
      FROM public.club_owner_holidays h
      WHERE h.season_id = v_season_id AND h.club_short_name = v_club
    )
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public views
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.club_owner_availability_public
WITH (security_invoker = false)
AS
SELECT
  s.id,
  s.season_id,
  s.club_short_name,
  s.iso_dow,
  s.slot_minute,
  (s.slot_minute / 60)::smallint AS slot_hour,
  (s.slot_minute % 60)::smallint AS slot_minute_of_hour
FROM public.club_owner_availability_slot s
JOIN public.competition_seasons seas ON seas.id = s.season_id
WHERE seas.is_current = true
  AND seas.status = 'active'
  AND s.club_short_name = public.my_club_shortname();

CREATE OR REPLACE VIEW public.club_owner_availability_unavailable_public
WITH (security_invoker = false)
AS
SELECT
  u.id,
  u.season_id,
  u.club_short_name,
  u.starts_at,
  u.ends_at,
  u.note,
  u.created_at
FROM public.club_owner_availability_unavailable u
JOIN public.competition_seasons seas ON seas.id = u.season_id
WHERE seas.is_current = true
  AND seas.status = 'active'
  AND u.club_short_name = public.my_club_shortname();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.club_owner_availability_slot ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.club_owner_availability_unavailable ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_fixture_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_fixture_schedule_proposal ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_owner_availability_slot_select ON public.club_owner_availability_slot;
CREATE POLICY club_owner_availability_slot_select ON public.club_owner_availability_slot
  FOR SELECT TO authenticated
  USING (club_short_name = public.my_club_shortname() OR public.is_gpsl_admin());

DROP POLICY IF EXISTS club_owner_availability_unavail_select ON public.club_owner_availability_unavailable;
CREATE POLICY club_owner_availability_unavail_select ON public.club_owner_availability_unavailable
  FOR SELECT TO authenticated
  USING (club_short_name = public.my_club_shortname() OR public.is_gpsl_admin());

DROP POLICY IF EXISTS competition_fixture_schedule_select ON public.competition_fixture_schedule;
CREATE POLICY competition_fixture_schedule_select ON public.competition_fixture_schedule
  FOR SELECT TO authenticated
  USING (
    public.is_gpsl_admin()
    OR EXISTS (
      SELECT 1 FROM public.competition_fixtures f
      WHERE f.id = fixture_id
        AND public.my_club_shortname() IN (f.home_club_short_name, f.away_club_short_name)
    )
  );

DROP POLICY IF EXISTS competition_fixture_schedule_proposal_select ON public.competition_fixture_schedule_proposal;
CREATE POLICY competition_fixture_schedule_proposal_select ON public.competition_fixture_schedule_proposal
  FOR SELECT TO authenticated
  USING (
    public.is_gpsl_admin()
    OR EXISTS (
      SELECT 1 FROM public.competition_fixtures f
      WHERE f.id = fixture_id
        AND public.my_club_shortname() IN (f.home_club_short_name, f.away_club_short_name)
    )
  );

-- ---------------------------------------------------------------------------
-- Extend fixtures public view with schedule columns
-- ---------------------------------------------------------------------------

DROP VIEW IF EXISTS public.competition_cup_qualified_public;
DROP VIEW IF EXISTS public.competition_cup_bracket_public;
DROP VIEW IF EXISTS public.competition_fixtures_public;

CREATE VIEW public.competition_fixtures_public
WITH (security_invoker = false)
AS
SELECT
  f.id,
  f.season_id,
  f.division,
  f.competition_type,
  f.cup_code,
  f.cup_round,
  f.cup_match,
  f.matchday,
  f.gpsl_month,
  f.week_in_month,
  f.home_club_short_name,
  hc."Club" AS home_club_name,
  f.away_club_short_name,
  ac."Club" AS away_club_name,
  f.weather,
  f.pitch_condition,
  f.kit_season,
  public.competition_club_continent(f.home_club_short_name) AS home_continent,
  f.home_goals,
  f.away_goals,
  f.status,
  sub.submission_id,
  sub.submission_status,
  sub.submitted_by_club,
  sub.proposed_home_goals,
  sub.proposed_away_goals,
  sub.proposed_et_home_goals,
  sub.proposed_et_away_goals,
  sub.proposed_pen_winner_club,
  COALESCE(sch.status, 'unscheduled') AS schedule_status,
  sch.agreed_kickoff_at,
  sch.pending_proposal_id AS schedule_pending_proposal_id,
  sch.home_proposal_count AS schedule_home_proposal_count,
  sch.away_proposal_count AS schedule_away_proposal_count,
  COALESCE(sch.discord_hint_shown, false) AS schedule_discord_hint
FROM public.competition_fixtures f
JOIN public.competition_seasons s ON s.id = f.season_id
JOIN public."Clubs" hc ON hc."ShortName" = f.home_club_short_name
JOIN public."Clubs" ac ON ac."ShortName" = f.away_club_short_name
LEFT JOIN public.competition_fixture_schedule sch ON sch.fixture_id = f.id
LEFT JOIN LATERAL (
  SELECT
    rs.id AS submission_id,
    rs.status AS submission_status,
    rs.submitted_by_club,
    rs.home_goals AS proposed_home_goals,
    rs.away_goals AS proposed_away_goals,
    rs.et_home_goals AS proposed_et_home_goals,
    rs.et_away_goals AS proposed_et_away_goals,
    rs.pen_winner_club_short_name AS proposed_pen_winner_club
  FROM public.competition_result_submissions rs
  WHERE rs.fixture_id = f.id
    AND rs.status = 'pending'
    AND (
      public.is_gpsl_admin()
      OR public.my_club_shortname() = f.home_club_short_name
      OR public.my_club_shortname() = f.away_club_short_name
    )
  LIMIT 1
) sub ON true
WHERE s.status = 'active' AND s.is_current = true;

CREATE VIEW public.competition_cup_bracket_public
WITH (security_invoker = false)
AS
SELECT
  n.id,
  n.season_id,
  n.cup_code,
  n.round_no,
  n.match_no,
  n.cup_leg,
  n.leg1_node_id,
  sch.round_label,
  sch.gpsl_month AS round_gpsl_month,
  n.home_club_short_name,
  hc."Club" AS home_club_name,
  n.away_club_short_name,
  ac."Club" AS away_club_name,
  n.winner_club_short_name,
  wc."Club" AS winner_club_name,
  n.fixture_id,
  f.status AS fixture_status,
  f.home_goals,
  f.away_goals,
  f.gpsl_month AS fixture_gpsl_month,
  f.weather,
  f.pitch_condition,
  f.kit_season,
  public.competition_club_continent(n.home_club_short_name) AS home_continent,
  n.child_node_id,
  n.child_slot
FROM public.competition_cup_bracket_nodes n
JOIN public.competition_seasons s ON s.id = n.season_id
LEFT JOIN public.competition_cup_round_schedule sch
  ON sch.cup_code = n.cup_code
 AND sch.round_no = n.round_no
 AND sch.cup_leg = coalesce(n.cup_leg, 1)
LEFT JOIN public."Clubs" hc ON hc."ShortName" = n.home_club_short_name
LEFT JOIN public."Clubs" ac ON ac."ShortName" = n.away_club_short_name
LEFT JOIN public."Clubs" wc ON wc."ShortName" = n.winner_club_short_name
LEFT JOIN public.competition_fixtures f ON f.id = n.fixture_id
WHERE s.status = 'active' AND s.is_current = true;

CREATE VIEW public.competition_cup_qualified_public
WITH (security_invoker = false)
AS
SELECT
  s.id AS season_id,
  cup.cup_code,
  q.club_short_name
FROM public.competition_seasons s
CROSS JOIN (
  VALUES ('super8'), ('plate'), ('shield'), ('spoon'), ('league_cup')
) AS cup(cup_code)
CROSS JOIN LATERAL unnest(public.competition_qualify_cup_clubs(s.id, cup.cup_code)) AS q(club_short_name)
WHERE s.is_current = true AND s.status = 'active';

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

GRANT SELECT ON public.club_owner_availability_public TO authenticated;
GRANT SELECT ON public.club_owner_availability_unavailable_public TO authenticated;
GRANT SELECT ON public.competition_fixtures_public TO authenticated;
GRANT SELECT ON public.competition_fixtures_public TO anon;
GRANT SELECT ON public.competition_cup_bracket_public TO authenticated;
GRANT SELECT ON public.competition_cup_bracket_public TO anon;
GRANT SELECT ON public.competition_cup_qualified_public TO authenticated;

GRANT EXECUTE ON FUNCTION public.club_owner_timezone_set(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_availability_save_weekly(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_availability_add_unavailable(timestamptz, timestamptz, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_availability_remove_unavailable(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_availability_context() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fixture_schedule_propose(bigint, timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fixture_schedule_accept(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.match_schedule_fixture_context(bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';
