-- =============================================================================
-- Specialist consultant identity
-- Format: "{Medical Group} - Specialist Consultant {Full Name}"
-- ~20 medical groups + hundreds of names (reuses medical_staff_random_name pools)
-- Assigned randomly when a consult is granted; stored on the consult / prize metadata.
-- Safe re-run.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.medical_consultancy_groups (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true
);

INSERT INTO public.medical_consultancy_groups (group_name) VALUES
  ('Harley Medical Group'),
  ('HealthAssured Medical Group'),
  ('Premier Sports Medicine'),
  ('Apex Performance Clinic'),
  ('Summit Orthopaedics'),
  ('Vitalis Sports Health'),
  ('Northbridge Medical Partners'),
  ('Sterling Physio Collective'),
  ('Crown Recovery Centre'),
  ('Atlas Joint & Muscle'),
  ('Meridian Elite Care'),
  ('Oakwood Sports Clinic'),
  ('Lakeside Rehabilitation Group'),
  ('Beacon Football Medicine'),
  ('Horizon Soft Tissue Unit'),
  ('Castle Gate Medical'),
  ('Riverside Athletic Health'),
  ('Phoenix Recovery Partners'),
  ('Silverstone Sports Clinic'),
  ('Unity Performance Medicine')
ON CONFLICT (group_name) DO NOTHING;

-- Random identity: group + consultant person name
CREATE OR REPLACE FUNCTION public.medical_random_consultancy_identity()
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SET search_path = public
AS $function$
DECLARE
  v_group text;
  v_person text;
  v_gender text;
BEGIN
  SELECT g.group_name INTO v_group
  FROM public.medical_consultancy_groups g
  WHERE g.is_active
  ORDER BY random()
  LIMIT 1;

  IF v_group IS NULL THEN
    v_group := 'Harley Medical Group';
  END IF;

  v_gender := CASE WHEN random() < 0.5 THEN 'female' ELSE 'male' END;

  IF to_regprocedure('public.medical_staff_random_name(text)') IS NOT NULL THEN
    v_person := public.medical_staff_random_name(v_gender);
  ELSE
    v_person := CASE v_gender
      WHEN 'female' THEN 'Helen Roberts'
      ELSE 'Tim Robins'
    END;
  END IF;

  RETURN jsonb_build_object(
    'group_name', v_group,
    'consultant_name', v_person,
    'label', v_group || ' - Specialist Consultant ' || v_person
  );
END;
$function$;

-- Named vault consults (each chip / −2 specialist token is a row)
CREATE TABLE IF NOT EXISTS public.club_medical_consults (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_short_name text NOT NULL,
  matches_removed int NOT NULL CHECK (matches_removed IN (2, 4, 6, 8, 10)),
  status text NOT NULL DEFAULT 'available'
    CHECK (status IN ('available', 'consumed')),
  group_name text NOT NULL,
  consultant_name text NOT NULL,
  label text NOT NULL,
  inventory_id bigint REFERENCES public.club_prize_inventory (id) ON DELETE SET NULL,
  source text,
  created_at timestamptz NOT NULL DEFAULT now(),
  consumed_at timestamptz
);

CREATE INDEX IF NOT EXISTS club_medical_consults_club_avail_idx
  ON public.club_medical_consults (club_short_name, status, matches_removed DESC, id);

ALTER TABLE public.club_medical_consults ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_medical_consults_select_own ON public.club_medical_consults;
CREATE POLICY club_medical_consults_select_own
  ON public.club_medical_consults FOR SELECT TO authenticated
  USING (
    club_short_name = public.my_club_shortname()
    OR public.is_gpsl_admin()
  );

GRANT SELECT ON TABLE public.club_medical_consults TO authenticated;
GRANT SELECT ON TABLE public.medical_consultancy_groups TO authenticated;

CREATE OR REPLACE FUNCTION public.medical_create_named_consult(
  p_club text,
  p_matches int,
  p_source text DEFAULT NULL,
  p_inventory_id bigint DEFAULT NULL,
  p_identity jsonb DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := nullif(btrim(p_club), '');
  v_id bigint;
  v_ident jsonb;
  v_matches int := coalesce(p_matches, 2);
BEGIN
  IF v_club IS NULL THEN RAISE EXCEPTION 'Club required'; END IF;
  IF v_matches NOT IN (2, 4, 6, 8, 10) THEN
    RAISE EXCEPTION 'Invalid consult strength %', v_matches;
  END IF;

  IF p_identity IS NOT NULL
     AND coalesce(nullif(p_identity->>'label', ''), '') <> '' THEN
    v_ident := p_identity;
  ELSE
    v_ident := public.medical_random_consultancy_identity();
  END IF;

  INSERT INTO public.club_medical_consults (
    club_short_name, matches_removed, status,
    group_name, consultant_name, label,
    inventory_id, source
  )
  VALUES (
    v_club, v_matches, 'available',
    coalesce(v_ident->>'group_name', 'Harley Medical Group'),
    coalesce(v_ident->>'consultant_name', 'Helen Roberts'),
    coalesce(
      v_ident->>'label',
      (v_ident->>'group_name') || ' - Specialist Consultant ' || (v_ident->>'consultant_name')
    ),
    p_inventory_id,
    p_source
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

-- Stamp prize medical tokens with consultancy identity + linked consult row
CREATE OR REPLACE FUNCTION public.prize_grant_inventory_item(
  p_club text,
  p_prize_type text,
  p_param_int int,
  p_source text DEFAULT NULL,
  p_season_id bigint DEFAULT NULL,
  p_window_phase text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint;
  v_club text := btrim(p_club);
  v_meta jsonb := coalesce(p_metadata, '{}'::jsonb);
  v_ident jsonb;
  v_consult_id bigint;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'Club required';
  END IF;

  IF p_prize_type NOT IN ('medical_token', 'fee_discount', 'appeal_card', 'draft_token') THEN
    RAISE EXCEPTION 'Invalid prize type %', p_prize_type;
  END IF;

  IF p_prize_type = 'medical_token' THEN
    v_ident := public.medical_random_consultancy_identity();
    v_meta := v_meta || jsonb_build_object(
      'matches_removed', p_param_int,
      'group_name', v_ident->>'group_name',
      'consultant_name', v_ident->>'consultant_name',
      'label', v_ident->>'label',
      'consultancy_label', v_ident->>'label'
    );
  END IF;

  INSERT INTO public.club_prize_inventory (
    club_short_name, prize_type, param_int, source, season_id, window_phase, metadata
  )
  VALUES (
    v_club,
    p_prize_type,
    CASE
      WHEN p_prize_type IN ('appeal_card', 'draft_token') THEN NULL
      ELSE p_param_int
    END,
    p_source,
    p_season_id,
    p_window_phase,
    v_meta
  )
  RETURNING id INTO v_id;

  IF p_prize_type = 'medical_token' THEN
    v_consult_id := public.medical_create_named_consult(
      v_club, p_param_int, coalesce(p_source, 'prize'), v_id, v_ident
    );
    UPDATE public.club_prize_inventory
    SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('consult_id', v_consult_id)
    WHERE id = v_id;
  END IF;

  RETURN v_id;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.prize_grant_inventory_item(text, text, int, text, bigint, text, jsonb) TO authenticated;

-- Grant vault consults as named rows (and keep specialist_tokens count in sync)
CREATE OR REPLACE FUNCTION public.medical_grant_specialist_tokens(
  p_club text,
  p_tokens int DEFAULT 1
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := nullif(btrim(p_club), '');
  v_n int := greatest(coalesce(p_tokens, 0), 0);
  v_row public.club_medical_centre;
  v_i int;
  v_ids bigint[] := ARRAY[]::bigint[];
  v_id bigint;
  v_room int;
BEGIN
  IF NOT public.is_gpsl_admin()
     AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  IF v_club IS NULL THEN RAISE EXCEPTION 'Club required'; END IF;
  IF v_n <= 0 THEN RAISE EXCEPTION 'Token count must be > 0'; END IF;

  v_row := public.medical_ensure_centre(v_club);
  v_room := greatest(0, 20 - coalesce(v_row.specialist_tokens, 0));
  v_n := least(v_n, v_room);
  IF v_n <= 0 THEN
    RETURN jsonb_build_object(
      'ok', true,
      'club_short_name', v_club,
      'specialist_tokens', v_row.specialist_tokens,
      'granted', 0,
      'max_specialist_tokens', 20,
      'consult_ids', '[]'::jsonb
    );
  END IF;

  FOR v_i IN 1..v_n LOOP
    v_id := public.medical_create_named_consult(v_club, 2, 'specialist_vault', NULL);
    v_ids := v_ids || v_id;
  END LOOP;

  UPDATE public.club_medical_centre
  SET specialist_tokens = least(20, specialist_tokens + v_n),
      updated_at = now()
  WHERE club_short_name = v_club
  RETURNING * INTO v_row;

  RETURN jsonb_build_object(
    'ok', true,
    'club_short_name', v_club,
    'specialist_tokens', v_row.specialist_tokens,
    'granted', v_n,
    'max_specialist_tokens', 20,
    'consult_ids', to_jsonb(v_ids)
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.medical_grant_specialist_tokens(text, int) TO authenticated;

-- Backfill named vault consults for existing specialist_tokens without rows
CREATE OR REPLACE FUNCTION public.medical_sync_named_consults(p_club text DEFAULT NULL)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  r record;
  v_have int;
  v_need int;
  v_created int := 0;
  v_i int;
BEGIN
  FOR r IN
    SELECT c.club_short_name, c.specialist_tokens
    FROM public.club_medical_centre c
    WHERE p_club IS NULL OR c.club_short_name = upper(trim(p_club))
  LOOP
    SELECT count(*)::int INTO v_have
    FROM public.club_medical_consults x
    WHERE x.club_short_name = r.club_short_name
      AND x.status = 'available'
      AND x.inventory_id IS NULL;

    v_need := greatest(0, coalesce(r.specialist_tokens, 0) - v_have);
    FOR v_i IN 1..v_need LOOP
      PERFORM public.medical_create_named_consult(r.club_short_name, 2, 'backfill_vault', NULL);
      v_created := v_created + 1;
    END LOOP;
  END LOOP;
  RETURN v_created;
END;
$function$;

-- Unified available consults (prize + vault) with display labels
CREATE OR REPLACE FUNCTION public.medical_list_available_consults(p_club text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := coalesce(nullif(btrim(p_club), ''), public.my_club_shortname());
  v_out jsonb;
BEGIN
  IF v_club IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  PERFORM public.medical_sync_named_consults(v_club);

  SELECT coalesce(jsonb_agg(row_to_json(x)::jsonb ORDER BY x.matches_removed DESC, x.id), '[]'::jsonb)
  INTO v_out
  FROM (
    SELECT
      c.id AS consult_id,
      c.matches_removed AS param_int,
      c.matches_removed,
      c.inventory_id,
      c.group_name,
      c.consultant_name,
      c.label,
      c.label AS consultancy_label,
      CASE WHEN c.inventory_id IS NULL THEN 'vault' ELSE 'prize' END AS kind,
      c.status
    FROM public.club_medical_consults c
    WHERE c.club_short_name = v_club
      AND c.status = 'available'
  ) x;

  RETURN coalesce(v_out, '[]'::jsonb);
END;
$function$;

CREATE OR REPLACE FUNCTION public.medical_room_prize_tokens(p_club text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  RETURN public.medical_list_available_consults(p_club);
END;
$function$;

-- Apply: support p_consult_id; consume named consult; stamp identity on use
CREATE OR REPLACE FUNCTION public.medical_apply_specialist_token(
  p_injury_id bigint,
  p_inventory_id bigint DEFAULT NULL,
  p_prefer_specialist boolean DEFAULT false,
  p_consult_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_inj public.competition_player_injuries%rowtype;
  v_remove int := 2;
  v_applied int := 0;
  v_tokens int;
  v_inv public.club_prize_inventory%rowtype;
  v_use_inventory boolean := false;
  v_consult public.club_medical_consults%rowtype;
  v_label text;
BEGIN
  IF v_club IS NULL THEN RAISE EXCEPTION 'No club linked to this account'; END IF;
  IF NOT public.medical_club_has_doctor(v_club) THEN
    RAISE EXCEPTION 'A club doctor is required before using specialist consultants';
  END IF;

  SELECT * INTO v_inj
  FROM public.competition_player_injuries
  WHERE id = p_injury_id
  FOR UPDATE;

  IF NOT FOUND OR v_inj.club_short_name IS DISTINCT FROM v_club THEN
    RAISE EXCEPTION 'Injury not found for your club';
  END IF;
  IF v_inj.status <> 'active' THEN
    RAISE EXCEPTION 'Injury is not active';
  END IF;
  IF EXISTS (SELECT 1 FROM public.club_medical_token_use WHERE injury_id = p_injury_id) THEN
    RAISE EXCEPTION 'A specialist consult was already used on this injury';
  END IF;

  PERFORM public.medical_ensure_centre(v_club);
  PERFORM public.medical_sync_named_consults(v_club);

  IF p_consult_id IS NOT NULL THEN
    SELECT * INTO v_consult
    FROM public.club_medical_consults
    WHERE id = p_consult_id
    FOR UPDATE;

    IF NOT FOUND OR v_consult.club_short_name IS DISTINCT FROM v_club THEN
      RAISE EXCEPTION 'Consult not found';
    END IF;
    IF v_consult.status <> 'available' THEN
      RAISE EXCEPTION 'Consult not available';
    END IF;

    v_remove := v_consult.matches_removed;
    v_label := v_consult.label;
    p_inventory_id := v_consult.inventory_id;
    IF p_inventory_id IS NOT NULL THEN
      v_use_inventory := true;
    END IF;
  ELSIF p_inventory_id IS NOT NULL THEN
    SELECT * INTO v_consult
    FROM public.club_medical_consults
    WHERE inventory_id = p_inventory_id
      AND status = 'available'
    ORDER BY id
    LIMIT 1
    FOR UPDATE;

    IF FOUND THEN
      p_consult_id := v_consult.id;
      v_remove := v_consult.matches_removed;
      v_label := v_consult.label;
      v_use_inventory := true;
    ELSE
      SELECT * INTO v_inv
      FROM public.club_prize_inventory
      WHERE id = p_inventory_id
      FOR UPDATE;
      IF NOT FOUND OR v_inv.club_short_name IS DISTINCT FROM v_club THEN
        RAISE EXCEPTION 'Medical token not found';
      END IF;
      IF v_inv.prize_type <> 'medical_token' OR v_inv.status <> 'available' THEN
        RAISE EXCEPTION 'Medical token not available';
      END IF;
      v_remove := v_inv.param_int;
      v_use_inventory := true;
      v_label := coalesce(v_inv.metadata->>'label', v_inv.metadata->>'consultancy_label');
    END IF;
  ELSIF coalesce(p_prefer_specialist, false) THEN
    SELECT * INTO v_consult
    FROM public.club_medical_consults
    WHERE club_short_name = v_club
      AND status = 'available'
      AND inventory_id IS NULL
    ORDER BY id
    LIMIT 1
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'No specialist tokens available';
    END IF;
    p_consult_id := v_consult.id;
    v_remove := v_consult.matches_removed;
    v_label := v_consult.label;
  ELSE
    -- Prefer strongest available named consult (prize or vault)
    SELECT * INTO v_consult
    FROM public.club_medical_consults
    WHERE club_short_name = v_club
      AND status = 'available'
    ORDER BY matches_removed DESC, id
    LIMIT 1
    FOR UPDATE;

    IF FOUND THEN
      p_consult_id := v_consult.id;
      v_remove := v_consult.matches_removed;
      v_label := v_consult.label;
      p_inventory_id := v_consult.inventory_id;
      v_use_inventory := (v_consult.inventory_id IS NOT NULL);
    ELSE
      RAISE EXCEPTION 'No specialist tokens available';
    END IF;
  END IF;

  IF coalesce(v_inj.matches_out_remaining, 0) > 0 THEN
    v_applied := least(v_remove, v_inj.matches_out_remaining);
    UPDATE public.competition_player_injuries
    SET matches_out_remaining = matches_out_remaining - v_applied
    WHERE id = p_injury_id;
  ELSIF coalesce(v_inj.recovery_remaining, 0) > 0 THEN
    v_applied := least(v_remove, v_inj.recovery_remaining);
    UPDATE public.competition_player_injuries
    SET recovery_remaining = recovery_remaining - v_applied
    WHERE id = p_injury_id;
  ELSE
    RAISE EXCEPTION 'Nothing left to shorten on this injury';
  END IF;

  UPDATE public.competition_player_injuries i
  SET status = 'recovered',
      recovered_at = coalesce(i.recovered_at, now())
  WHERE i.id = p_injury_id
    AND coalesce(i.matches_out_remaining, 0) <= 0
    AND coalesce(i.recovery_remaining, 0) <= 0;

  INSERT INTO public.club_medical_token_use (club_short_name, injury_id, matches_removed)
  VALUES (v_club, p_injury_id, v_applied);

  IF p_consult_id IS NOT NULL THEN
    UPDATE public.club_medical_consults
    SET status = 'consumed',
        consumed_at = now()
    WHERE id = p_consult_id;
  END IF;

  IF v_use_inventory AND p_inventory_id IS NOT NULL THEN
    UPDATE public.club_prize_inventory
    SET status = 'consumed',
        consumed_at = now(),
        updated_at = now(),
        metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
          'injury_id', p_injury_id,
          'matches_removed', v_applied,
          'label', v_label
        )
    WHERE id = p_inventory_id;
  ELSIF p_consult_id IS NOT NULL AND NOT v_use_inventory THEN
    UPDATE public.club_medical_centre
    SET specialist_tokens = greatest(0, specialist_tokens - 1),
        updated_at = now()
    WHERE club_short_name = v_club;
  END IF;

  IF to_regprocedure('public.competition_injury_assign_fixtures(bigint)') IS NOT NULL THEN
    PERFORM public.competition_injury_assign_fixtures(p_injury_id);
  END IF;

  SELECT specialist_tokens INTO v_tokens
  FROM public.club_medical_centre
  WHERE club_short_name = v_club;

  RETURN jsonb_build_object(
    'ok', true,
    'matches_removed', v_applied,
    'token_tier', v_remove,
    'inventory_id', p_inventory_id,
    'consult_id', p_consult_id,
    'label', v_label,
    'tokens_left', coalesce(v_tokens, 0)
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.medical_random_consultancy_identity() TO authenticated;
GRANT EXECUTE ON FUNCTION public.medical_create_named_consult(text, int, text, bigint, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.medical_sync_named_consults(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.medical_list_available_consults(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.medical_room_prize_tokens(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.medical_apply_specialist_token(bigint, bigint, boolean, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.medical_apply_specialist_token(bigint, bigint, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.medical_apply_specialist_token(bigint, bigint) TO authenticated;

-- Backfill all clubs once
SELECT public.medical_sync_named_consults(NULL);

-- Backfill labels on existing available prize medical tokens missing identity
DO $$
DECLARE
  r record;
  v_ident jsonb;
  v_cid bigint;
BEGIN
  FOR r IN
    SELECT i.id, i.club_short_name, i.param_int, i.source, i.metadata
    FROM public.club_prize_inventory i
    WHERE i.prize_type = 'medical_token'
      AND i.status = 'available'
      AND coalesce(nullif(i.metadata->>'label', ''), '') = ''
  LOOP
    v_ident := public.medical_random_consultancy_identity();
    UPDATE public.club_prize_inventory
    SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
      'group_name', v_ident->>'group_name',
      'consultant_name', v_ident->>'consultant_name',
      'label', v_ident->>'label',
      'consultancy_label', v_ident->>'label',
      'matches_removed', r.param_int
    )
    WHERE id = r.id;

    IF NOT EXISTS (
      SELECT 1 FROM public.club_medical_consults c WHERE c.inventory_id = r.id
    ) THEN
      v_cid := public.medical_create_named_consult(
        r.club_short_name, r.param_int, coalesce(r.source, 'prize_backfill'), r.id, v_ident
      );

      UPDATE public.club_prize_inventory
      SET metadata = metadata || jsonb_build_object('consult_id', v_cid)
      WHERE id = r.id;
    END IF;
  END LOOP;
END $$;

NOTIFY pgrst, 'reload schema';
