-- =============================================================================
-- GPSL Natter — owner monthly social posts (X-like feed, original branding)
-- One post per club per GPSL month; 1000 chars; optional image (Storage).
-- Feeds GPSL Sport Club news for the FOLLOWING month (always one month behind).
-- Run after gpsl_sport_owner_comments.sql / gpsl_sport_inseason_rich_edition.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.natter_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  gpsl_month text NOT NULL,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName") ON DELETE CASCADE,
  owner_id uuid NOT NULL,
  owner_tag text NOT NULL DEFAULT '',
  body text NOT NULL,
  image_path text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT natter_posts_month_check CHECK (
    gpsl_month IN (
      'august', 'september', 'october', 'november', 'december',
      'january', 'february', 'march', 'april', 'may', 'june', 'july'
    )
  ),
  CONSTRAINT natter_posts_body_len CHECK (char_length(body) >= 1 AND char_length(body) <= 1000),
  CONSTRAINT natter_posts_unique UNIQUE (season_id, gpsl_month, club_short_name)
);

CREATE INDEX IF NOT EXISTS natter_posts_season_month_idx
  ON public.natter_posts (season_id, gpsl_month, created_at DESC);

CREATE INDEX IF NOT EXISTS natter_posts_club_idx
  ON public.natter_posts (club_short_name, created_at DESC);

COMMENT ON TABLE public.natter_posts IS
  'Natter: one-and-done monthly owner posts. Appear in next GPSL Sport Club news.';

ALTER TABLE public.natter_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS natter_posts_select ON public.natter_posts;
CREATE POLICY natter_posts_select ON public.natter_posts
  FOR SELECT TO authenticated USING (true);

-- Storage bucket for optional images (run once; ignore if bucket already exists)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'natter-media',
  'natter-media',
  true,
  3145728,
  ARRAY['image/jpeg', 'image/png', 'image/webp']::text[]
)
ON CONFLICT (id) DO UPDATE
SET public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

DROP POLICY IF EXISTS natter_media_public_read ON storage.objects;
CREATE POLICY natter_media_public_read ON storage.objects
  FOR SELECT TO authenticated, anon
  USING (bucket_id = 'natter-media');

DROP POLICY IF EXISTS natter_media_owner_insert ON storage.objects;
CREATE POLICY natter_media_owner_insert ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'natter-media'
    AND (storage.foldername(name))[1] = coalesce(public.my_club_shortname(), '')
  );

DROP POLICY IF EXISTS natter_media_owner_update ON storage.objects;
CREATE POLICY natter_media_owner_update ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'natter-media'
    AND (storage.foldername(name))[1] = coalesce(public.my_club_shortname(), '')
  )
  WITH CHECK (
    bucket_id = 'natter-media'
    AND (storage.foldername(name))[1] = coalesce(public.my_club_shortname(), '')
  );

DROP POLICY IF EXISTS natter_media_owner_delete ON storage.objects;
CREATE POLICY natter_media_owner_delete ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'natter-media'
    AND (storage.foldername(name))[1] = coalesce(public.my_club_shortname(), '')
  );

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.natter_club_display_name(p_club_short text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(
    nullif(btrim(c."Club"), ''),
    p_club_short
  )
  FROM public."Clubs" c
  WHERE c."ShortName" = p_club_short
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.natter_compose_open()
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_status text;
  v_month text;
BEGIN
  SELECT s.id, s.status
  INTO v_season_id, v_status
  FROM public.competition_seasons s
  WHERE s.is_current = true
  ORDER BY s.id DESC
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RETURN false;
  END IF;

  -- Pre-season: allow a June/July style post keyed to a synthetic window when needed
  IF lower(coalesce(v_status, '')) = 'preseason' THEN
    RETURN true;
  END IF;

  v_month := public.competition_active_gpsl_month(v_season_id, now());
  RETURN v_month IS NOT NULL AND btrim(v_month) <> '';
END;
$function$;

CREATE OR REPLACE FUNCTION public.natter_active_month_context()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_status text;
  v_label text;
  v_month text;
BEGIN
  SELECT s.id, s.status, s.label
  INTO v_season_id, v_status, v_label
  FROM public.competition_seasons s
  WHERE s.is_current = true
  ORDER BY s.id DESC
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_season');
  END IF;

  IF lower(coalesce(v_status, '')) = 'preseason' THEN
    v_month := 'july';
  ELSE
    v_month := public.competition_active_gpsl_month(v_season_id, now());
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'season_id', v_season_id,
    'season_label', v_label,
    'season_status', v_status,
    'gpsl_month', v_month,
    'month_label', CASE WHEN v_month IS NULL THEN NULL ELSE public.competition_gpsl_month_label(v_month) END,
    'compose_open', public.natter_compose_open() AND v_month IS NOT NULL
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.natter_get_compose_state()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_club_name text;
  v_ctx jsonb;
  v_posted boolean := false;
  v_post jsonb;
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;

  SELECT c."ShortName", c."Club"
  INTO v_club, v_club_name
  FROM public."Clubs" c
  WHERE c.owner_id = auth.uid()
  LIMIT 1;

  v_ctx := public.natter_active_month_context();

  IF v_club IS NOT NULL
    AND (v_ctx->>'ok')::boolean
    AND nullif(v_ctx->>'gpsl_month', '') IS NOT NULL THEN
    SELECT true,
           jsonb_build_object(
             'id', p.id,
             'body', p.body,
             'image_path', p.image_path,
             'created_at', p.created_at
           )
    INTO v_posted, v_post
    FROM public.natter_posts p
    WHERE p.season_id = (v_ctx->>'season_id')::bigint
      AND p.gpsl_month = v_ctx->>'gpsl_month'
      AND p.club_short_name = v_club
    LIMIT 1;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'club_short_name', v_club,
    'club_name', coalesce(v_club_name, v_club),
    'context', v_ctx,
    'already_posted', coalesce(v_posted, false),
    'my_post', v_post,
    'max_chars', 1000,
    'can_compose', (
      v_club IS NOT NULL
      AND coalesce((v_ctx->>'compose_open')::boolean, false)
      AND NOT coalesce(v_posted, false)
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.natter_create_post(
  p_body text,
  p_image_path text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_club text;
  v_club_name text;
  v_tag text;
  v_ctx jsonb;
  v_month text;
  v_season_id bigint;
  v_body text;
  v_image text;
  v_id bigint;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;

  SELECT c."ShortName", c."Club",
         coalesce(
           nullif(btrim(c.owner), ''),
           nullif(btrim(public.owner_registry_resolve_tag(c.owner_id)), ''),
           ''
         )
  INTO v_club, v_club_name, v_tag
  FROM public."Clubs" c
  WHERE c.owner_id = v_uid
  LIMIT 1;

  IF v_club IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_club');
  END IF;

  v_ctx := public.natter_active_month_context();
  IF NOT coalesce((v_ctx->>'compose_open')::boolean, false) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'window_closed');
  END IF;

  v_month := nullif(v_ctx->>'gpsl_month', '');
  v_season_id := nullif(v_ctx->>'season_id', '')::bigint;
  IF v_month IS NULL OR v_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_active_month');
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.natter_posts p
    WHERE p.season_id = v_season_id
      AND p.gpsl_month = v_month
      AND p.club_short_name = v_club
  ) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'already_posted');
  END IF;

  v_body := nullif(btrim(coalesce(p_body, '')), '');
  IF v_body IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'empty');
  END IF;
  IF char_length(v_body) > 1000 THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'too_long', 'max_chars', 1000);
  END IF;

  v_image := nullif(btrim(coalesce(p_image_path, '')), '');
  IF v_image IS NOT NULL AND split_part(v_image, '/', 1) IS DISTINCT FROM v_club THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'invalid_image_path');
  END IF;

  INSERT INTO public.natter_posts (
    season_id, gpsl_month, club_short_name, owner_id, owner_tag, body, image_path
  )
  VALUES (
    v_season_id, v_month, v_club, v_uid, coalesce(v_tag, ''), v_body, v_image
  )
  RETURNING id INTO v_id;

  RETURN jsonb_build_object(
    'ok', true,
    'id', v_id,
    'club_short_name', v_club,
    'club_name', coalesce(v_club_name, v_club),
    'gpsl_month', v_month,
    'month_label', public.competition_gpsl_month_label(v_month),
    'body', v_body,
    'image_path', v_image
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.natter_list_months(p_season_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint := p_season_id;
BEGIN
  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_season');
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'season_id', v_season_id,
    'months', coalesce((
      SELECT jsonb_agg(
        jsonb_build_object(
          'gpsl_month', q.gpsl_month,
          'month_label', public.competition_gpsl_month_label(q.gpsl_month),
          'post_count', q.post_count,
          'sort_key', public.competition_gpsl_month_sort(q.gpsl_month)
        )
        ORDER BY public.competition_gpsl_month_sort(q.gpsl_month) DESC NULLS LAST
      )
      FROM (
        SELECT p.gpsl_month, count(*)::int AS post_count
        FROM public.natter_posts p
        WHERE p.season_id = v_season_id
        GROUP BY p.gpsl_month
      ) q
    ), '[]'::jsonb)
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.natter_list_posts(
  p_season_id bigint DEFAULT NULL,
  p_gpsl_month text DEFAULT NULL,
  p_limit int DEFAULT 100
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint := p_season_id;
  v_month text := lower(nullif(btrim(coalesce(p_gpsl_month, '')), ''));
  v_lim int := greatest(1, least(coalesce(p_limit, 100), 200));
BEGIN
  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_season', 'posts', '[]'::jsonb);
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'season_id', v_season_id,
    'gpsl_month', v_month,
    'posts', coalesce((
      SELECT jsonb_agg(row_data ORDER BY sort_at DESC)
      FROM (
        SELECT
          jsonb_build_object(
            'id', p.id,
            'season_id', p.season_id,
            'gpsl_month', p.gpsl_month,
            'month_label', public.competition_gpsl_month_label(p.gpsl_month),
            'club_short', p.club_short_name,
            'club_name', public.natter_club_display_name(p.club_short_name),
            'owner_tag', p.owner_tag,
            'body', p.body,
            'image_path', p.image_path,
            'created_at', p.created_at
          ) AS row_data,
          p.created_at AS sort_at
        FROM public.natter_posts p
        WHERE p.season_id = v_season_id
          AND (v_month IS NULL OR p.gpsl_month = v_month)
        ORDER BY p.created_at DESC
        LIMIT v_lim
      ) q
    ), '[]'::jsonb)
  );
END;
$function$;

-- GPSL Sport Club news: prefer Natter (prior month), fallback to legacy sport comments
CREATE OR REPLACE FUNCTION public.gpsl_sport_fetch_club_news(
  p_season_id bigint,
  p_edition_gpsl_month text
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_prev_month text;
  v_natter jsonb;
BEGIN
  v_prev_month := public.gpsl_sport_previous_gpsl_month(p_edition_gpsl_month);
  IF v_prev_month IS NULL OR p_season_id IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  SELECT coalesce(jsonb_agg(row_data ORDER BY row_data->>'club_name'), '[]'::jsonb)
  INTO v_natter
  FROM (
    SELECT jsonb_build_object(
      'club_short', p.club_short_name,
      'club_name', public.natter_club_display_name(p.club_short_name),
      'owner', coalesce(nullif(btrim(p.owner_tag), ''), 'Club owner'),
      'comment', p.body,
      'image_path', p.image_path,
      'source', 'natter',
      'source_gpsl_month', p.gpsl_month,
      'source_month_label', public.competition_gpsl_month_label(p.gpsl_month)
    ) AS row_data
    FROM public.natter_posts p
    WHERE p.season_id = p_season_id
      AND p.gpsl_month = v_prev_month
  ) q;

  IF jsonb_array_length(v_natter) > 0 THEN
    RETURN v_natter;
  END IF;

  -- Legacy fallback (Club Details drafts captured at month lock)
  RETURN coalesce((
    SELECT jsonb_agg(row_data ORDER BY row_data->>'club_name')
    FROM (
      SELECT jsonb_build_object(
        'club_short', oc.club_short_name,
        'club_name', public.natter_club_display_name(oc.club_short_name),
        'owner', oc.owner_tag,
        'comment', oc.comment_text,
        'source', 'legacy_sport_comment',
        'source_gpsl_month', oc.source_gpsl_month,
        'source_month_label', public.competition_gpsl_month_label(oc.source_gpsl_month)
      ) AS row_data
      FROM public.gpsl_sport_owner_comments oc
      WHERE oc.season_id = p_season_id
        AND oc.source_gpsl_month = v_prev_month
    ) q
  ), '[]'::jsonb);
END;
$function$;

GRANT SELECT ON public.natter_posts TO authenticated;
GRANT EXECUTE ON FUNCTION public.natter_active_month_context() TO authenticated;
GRANT EXECUTE ON FUNCTION public.natter_get_compose_state() TO authenticated;
GRANT EXECUTE ON FUNCTION public.natter_create_post(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.natter_list_months(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.natter_list_posts(bigint, text, int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_fetch_club_news(bigint, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_fetch_club_news(bigint, text) TO authenticated;

NOTIFY pgrst, 'reload schema';
