-- =============================================================================
-- Natter reactions — club owners can react with a fixed emoji set
-- One reaction per owner per post (tap same = clear, different = switch).
-- Run after natter_platform.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.natter_reactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES public.natter_posts (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL,
  emoji text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT natter_reactions_emoji_check CHECK (
    emoji IN ('👍', '😂', '🔥', '⚽', '👏', '❤️')
  ),
  CONSTRAINT natter_reactions_unique UNIQUE (post_id, owner_id)
);

CREATE INDEX IF NOT EXISTS natter_reactions_post_idx
  ON public.natter_reactions (post_id);

COMMENT ON TABLE public.natter_reactions IS
  'Natter: one emoji reaction per club owner per post.';

ALTER TABLE public.natter_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS natter_reactions_select ON public.natter_reactions;
CREATE POLICY natter_reactions_select ON public.natter_reactions
  FOR SELECT TO authenticated USING (true);

CREATE OR REPLACE FUNCTION public.natter_reaction_counts(p_post_id bigint)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(jsonb_agg(
    jsonb_build_object('emoji', q.emoji, 'count', q.cnt)
    ORDER BY q.cnt DESC, q.emoji
  ), '[]'::jsonb)
  FROM (
    SELECT r.emoji, count(*)::int AS cnt
    FROM public.natter_reactions r
    WHERE r.post_id = p_post_id
    GROUP BY r.emoji
  ) q;
$$;

CREATE OR REPLACE FUNCTION public.natter_react(
  p_post_id bigint,
  p_emoji text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_club text;
  v_emoji text := nullif(btrim(coalesce(p_emoji, '')), '');
  v_existing text;
  v_cleared boolean := false;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;

  IF p_post_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'bad_post');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.natter_posts p WHERE p.id = p_post_id) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
  END IF;

  SELECT c."ShortName"
  INTO v_club
  FROM public."Clubs" c
  WHERE c.owner_id = v_uid
  LIMIT 1;

  IF v_club IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_club');
  END IF;

  IF v_emoji IS NULL OR v_emoji NOT IN ('👍', '😂', '🔥', '⚽', '👏', '❤️') THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'bad_emoji');
  END IF;

  SELECT r.emoji INTO v_existing
  FROM public.natter_reactions r
  WHERE r.post_id = p_post_id
    AND r.owner_id = v_uid
  LIMIT 1;

  IF v_existing IS NOT NULL AND v_existing = v_emoji THEN
    DELETE FROM public.natter_reactions
    WHERE post_id = p_post_id AND owner_id = v_uid;
    v_cleared := true;
  ELSIF v_existing IS NOT NULL THEN
    UPDATE public.natter_reactions
    SET emoji = v_emoji, updated_at = now()
    WHERE post_id = p_post_id AND owner_id = v_uid;
  ELSE
    INSERT INTO public.natter_reactions (post_id, owner_id, emoji)
    VALUES (p_post_id, v_uid, v_emoji);
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'post_id', p_post_id,
    'cleared', v_cleared,
    'my_reaction', CASE WHEN v_cleared THEN NULL ELSE v_emoji END,
    'reactions', public.natter_reaction_counts(p_post_id)
  );
END;
$function$;

-- Enrich list posts with reaction summary + caller's reaction
CREATE OR REPLACE FUNCTION public.natter_list_posts(
  p_season_id bigint DEFAULT NULL,
  p_gpsl_month text DEFAULT NULL,
  p_limit int DEFAULT 100
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint := p_season_id;
  v_month text := lower(nullif(btrim(coalesce(p_gpsl_month, '')), ''));
  v_lim int := greatest(1, least(coalesce(p_limit, 100), 200));
  v_uid uuid := auth.uid();
  v_can_react boolean := false;
BEGIN
  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_season', 'posts', '[]'::jsonb);
  END IF;

  IF v_uid IS NOT NULL THEN
    v_can_react := EXISTS (
      SELECT 1 FROM public."Clubs" c WHERE c.owner_id = v_uid LIMIT 1
    );
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'season_id', v_season_id,
    'gpsl_month', v_month,
    'can_react', v_can_react,
    'reaction_emojis', '["👍","😂","🔥","⚽","👏","❤️"]'::jsonb,
    'posts', coalesce((
      SELECT jsonb_agg(row_data ORDER BY sort_at DESC)
      FROM (
        SELECT
          jsonb_build_object(
            'id', p.id,
            'season_id', p.season_id,
            'gpsl_month', p.gpsl_month,
            'month_label', public.competition_gpsl_month_label(p.gpsl_month),
            'club_short', p.club_short_name,
            'club_name', public.natter_club_display_name(p.club_short_name),
            'owner_tag', p.owner_tag,
            'body', p.body,
            'image_path', p.image_path,
            'created_at', p.created_at,
            'reactions', public.natter_reaction_counts(p.id),
            'my_reaction', (
              SELECT r.emoji
              FROM public.natter_reactions r
              WHERE r.post_id = p.id
                AND r.owner_id = v_uid
              LIMIT 1
            )
          ) AS row_data,
          p.created_at AS sort_at
        FROM public.natter_posts p
        WHERE p.season_id = v_season_id
          AND (v_month IS NULL OR p.gpsl_month = v_month)
        ORDER BY p.created_at DESC
        LIMIT v_lim
      ) q
    ), '[]'::jsonb)
  );
END;
$function$;

GRANT SELECT ON public.natter_reactions TO authenticated;
GRANT EXECUTE ON FUNCTION public.natter_react(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.natter_reaction_counts(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.natter_list_posts(bigint, text, int) TO authenticated;

NOTIFY pgrst, 'reload schema';
