-- =============================================================================
-- "One of our Own" — homegrown star draw (once per club, at club formation)
-- =============================================================================
-- Each selected club is drawn a random FREE-AGENT player that:
--   * matches the club's Nation (home grown), and
--   * has a base Rating of 79 or higher.
-- The draw acts as a real transfer:
--   * player_assign_to_club()  → contract (3 seasons), wage, Season_Signed, squad overflow
--   * Transfer_History row     → shows in Transfer Centre / Season transfers
--   * post_club_ledger()       → debits the club the market value (may go negative),
--                                credits the GPSL Central Bank (bank leg)
-- A club can only ever receive this ONCE (enforced by unique club_short_name).
--
-- Requires: squad_composition_rules.sql (normalize_nation_key),
--           squad_overflow_enforcement.sql (player_assign_to_club),
--           central_bank_phase1.sql (post_club_ledger).
-- Run once in the Supabase SQL Editor.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.club_one_of_our_own_draws (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_short_name text NOT NULL UNIQUE REFERENCES public."Clubs" ("ShortName"),
  player_id text NOT NULL,
  fee numeric(14, 2) NOT NULL DEFAULT 0,
  season_id bigint REFERENCES public.competition_seasons (id),
  transfer_history_id bigint,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.club_one_of_our_own_draws ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_one_of_our_own_draws_select ON public.club_one_of_our_own_draws;
CREATE POLICY club_one_of_our_own_draws_select ON public.club_one_of_our_own_draws
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS club_one_of_our_own_draws_admin ON public.club_one_of_our_own_draws;
CREATE POLICY club_one_of_our_own_draws_admin ON public.club_one_of_our_own_draws
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.club_one_of_our_own_draws TO authenticated;

-- ---------------------------------------------------------------------------
-- Admin overview: every club + nation, whether it already has its draw,
-- and how many eligible free agents currently exist for it.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.competition_admin_one_of_our_own_overview()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  RETURN coalesce((
    SELECT jsonb_agg(
      jsonb_build_object(
        'short_name', c."ShortName",
        'club', c."Club",
        'nation', c."Nation",
        'already_drawn', (d.id IS NOT NULL),
        'drawn_player_id', d.player_id,
        'drawn_player_name', dp."Name",
        'drawn_fee', d.fee,
        'eligible_count', (
          SELECT count(*)
          FROM public."Players" p
          WHERE (p."Contracted_Team" IS NULL OR btrim(p."Contracted_Team") = '')
            AND public.normalize_nation_key(p."Nation") = public.normalize_nation_key(c."Nation")
            AND public.normalize_nation_key(p."Nation") <> ''
            AND btrim(p."Rating"::text) <> ''
            AND btrim(p."Rating"::text)::numeric >= 79
        )
      )
      ORDER BY c."Club"
    )
    FROM public."Clubs" c
    LEFT JOIN public.club_one_of_our_own_draws d ON d.club_short_name = c."ShortName"
    LEFT JOIN public."Players" dp ON dp."Konami_ID"::text = d.player_id
    WHERE c."ShortName" <> 'FOREIGN'
  ), '[]'::jsonb);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Admin draw: for each selected club, draw + sign a random eligible free agent.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.competition_admin_draw_one_of_our_own(
  p_club_short_names text[]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_club text;
  v_nation text;
  v_player_id text;
  v_player_name text;
  v_fee numeric;
  v_history_id bigint;
  v_results jsonb := '[]'::jsonb;
  v_drawn int := 0;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_club_short_names IS NULL OR array_length(p_club_short_names, 1) IS NULL THEN
    RAISE EXCEPTION 'Select at least one club';
  END IF;

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true AND status = 'active'
  ORDER BY id DESC
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No active competition season — start a season before drawing';
  END IF;

  FOREACH v_club IN ARRAY p_club_short_names
  LOOP
    v_club := btrim(v_club);
    CONTINUE WHEN v_club = '';

    -- Once-ever guard.
    IF EXISTS (
      SELECT 1 FROM public.club_one_of_our_own_draws d
      WHERE d.club_short_name = v_club
    ) THEN
      v_results := v_results || jsonb_build_object('club', v_club, 'status', 'skipped_already');
      CONTINUE;
    END IF;

    SELECT c."Nation" INTO v_nation
    FROM public."Clubs" c
    WHERE c."ShortName" = v_club;

    IF NOT FOUND THEN
      v_results := v_results || jsonb_build_object('club', v_club, 'status', 'club_not_found');
      CONTINUE;
    END IF;

    -- Random eligible free agent: home grown (Nation match) + Rating >= 79.
    SELECT
      p."Konami_ID"::text,
      p."Name",
      round(coalesce(nullif(btrim(p.market_value::text), '')::numeric, 0))
    INTO v_player_id, v_player_name, v_fee
    FROM public."Players" p
    WHERE (p."Contracted_Team" IS NULL OR btrim(p."Contracted_Team") = '')
      AND public.normalize_nation_key(p."Nation") = public.normalize_nation_key(v_nation)
      AND public.normalize_nation_key(p."Nation") <> ''
      AND btrim(p."Rating"::text) <> ''
      AND btrim(p."Rating"::text)::numeric >= 79
    ORDER BY random()
    LIMIT 1;

    IF NOT FOUND THEN
      v_results := v_results || jsonb_build_object(
        'club', v_club, 'status', 'no_eligible_player', 'nation', v_nation
      );
      CONTINUE;
    END IF;

    -- Per-club subtransaction: any failure rolls back just this club.
    BEGIN
      -- Explicit 3-arg form (NULL wage = auto-calculate) avoids the
      -- ambiguity between the 2-arg and 3-arg overloads.
      PERFORM public.player_assign_to_club(v_player_id, v_club, NULL::numeric);

      INSERT INTO public."Transfer_History" (
        player_id, seller_club_id, buyer_club_id, fee, agent_fee, transfer_time, listing_id
      )
      VALUES (
        v_player_id, NULL, v_club, v_fee, 0, now(), NULL
      )
      RETURNING id INTO v_history_id;

      -- Debit club market value (balance may go negative), credit central bank.
      PERFORM public.post_club_ledger(
        v_club,
        'transfer_purchase',
        -v_fee,
        'One of our Own draw: ' || coalesce(v_player_name, v_player_id),
        jsonb_build_object(
          'transfer_history_id', v_history_id,
          'player_id', v_player_id,
          'one_of_our_own', true
        ),
        v_season_id,
        NULL,
        true,   -- bank leg: credit GPSL Central Bank reserves
        true    -- apply balance (no affordability gate)
      );

      INSERT INTO public.club_one_of_our_own_draws (
        club_short_name, player_id, fee, season_id, transfer_history_id
      )
      VALUES (
        v_club, v_player_id, v_fee, v_season_id, v_history_id
      );

      v_drawn := v_drawn + 1;
      v_results := v_results || jsonb_build_object(
        'club', v_club,
        'status', 'drawn',
        'player_id', v_player_id,
        'player_name', v_player_name,
        'fee', v_fee,
        'nation', v_nation
      );
    EXCEPTION WHEN OTHERS THEN
      v_results := v_results || jsonb_build_object(
        'club', v_club, 'status', 'error', 'message', SQLERRM
      );
    END;
  END LOOP;

  RETURN jsonb_build_object(
    'ok', true,
    'season_id', v_season_id,
    'drawn', v_drawn,
    'results', v_results
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.competition_admin_one_of_our_own_overview() TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_draw_one_of_our_own(text[]) TO authenticated;

NOTIFY pgrst, 'reload schema';
