-- =============================================================================
-- Owner inbox — extended notification types + hooks
-- Run after competition_phase3_matchday.sql and transfer_inbox_notifications.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Schema extensions
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_inbox
  ADD COLUMN IF NOT EXISTS action_href text,
  ADD COLUMN IF NOT EXISTS dedupe_key text,
  ADD COLUMN IF NOT EXISTS gpsl_month text,
  ADD COLUMN IF NOT EXISTS season_id bigint REFERENCES public.competition_seasons (id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES auth.users (id) ON DELETE CASCADE;

ALTER TABLE public.competition_inbox
  ALTER COLUMN recipient_club_short_name DROP NOT NULL;

ALTER TABLE public.competition_inbox
  DROP CONSTRAINT IF EXISTS competition_inbox_recipient_or_owner_check;

ALTER TABLE public.competition_inbox
  ADD CONSTRAINT competition_inbox_recipient_or_owner_check
  CHECK (
    recipient_club_short_name IS NOT NULL
    OR owner_id IS NOT NULL
  );

CREATE UNIQUE INDEX IF NOT EXISTS competition_inbox_dedupe_idx
  ON public.competition_inbox (dedupe_key)
  WHERE dedupe_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS competition_inbox_owner_unread_idx
  ON public.competition_inbox (owner_id)
  WHERE read_at IS NULL AND owner_id IS NOT NULL;

ALTER TABLE public.competition_inbox
  DROP CONSTRAINT IF EXISTS competition_inbox_message_type_check;

ALTER TABLE public.competition_inbox
  ADD CONSTRAINT competition_inbox_message_type_check
  CHECK (
    message_type IN (
      'welcome_gpsl',
      'result_submitted',
      'result_to_confirm',
      'result_rejected',
      'result_confirmed',
      'transfer_signed',
      'transfer_sold',
      'transfer_upcoming',
      'draft_scheduled',
      'fine_applied',
      'points_deduction',
      'nation_pick_turn',
      'nation_selection_open',
      'season_expectations',
      'season_overview',
      'player_awards',
      'monthly_fixtures'
    )
  );

-- Manual league points adjustments (deductions / additions)
CREATE TABLE IF NOT EXISTS public.competition_league_points_adjustments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  points_delta smallint NOT NULL,
  reason text NOT NULL,
  applied_by text NOT NULL DEFAULT 'ADMIN',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS competition_league_points_adj_season_club_idx
  ON public.competition_league_points_adjustments (season_id, club_short_name);

ALTER TABLE public.competition_league_points_adjustments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_points_adj_select ON public.competition_league_points_adjustments;
CREATE POLICY competition_points_adj_select ON public.competition_league_points_adjustments
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_points_adj_admin ON public.competition_league_points_adjustments;
CREATE POLICY competition_points_adj_admin ON public.competition_league_points_adjustments
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

-- Standings: include manual point adjustments
CREATE OR REPLACE VIEW public.competition_standings_public
WITH (security_invoker = false)
AS
WITH active_season AS (
  SELECT id
  FROM public.competition_seasons
  WHERE is_current = true AND status = 'active'
  LIMIT 1
),
registered AS (
  SELECT
    ccs.season_id,
    ccs.division,
    ccs.club_short_name,
    c."Club" AS club_name
  FROM public.competition_club_seasons ccs
  JOIN public."Clubs" c ON c."ShortName" = ccs.club_short_name
  JOIN active_season s ON s.id = ccs.season_id
  WHERE ccs.division IN ('superleague', 'championship_a', 'championship_b')
),
played AS (
  SELECT f.*
  FROM public.competition_fixtures f
  JOIN active_season s ON s.id = f.season_id
  WHERE f.competition_type = 'league'
    AND f.status = 'played'
    AND f.home_goals IS NOT NULL
    AND f.away_goals IS NOT NULL
),
home_apps AS (
  SELECT
    season_id, division, home_club_short_name AS club_short_name, matchday,
    1 AS mp,
    CASE WHEN home_goals > away_goals THEN 1 ELSE 0 END AS w,
    CASE WHEN home_goals = away_goals THEN 1 ELSE 0 END AS d,
    CASE WHEN home_goals < away_goals THEN 1 ELSE 0 END AS l,
    home_goals AS gf, away_goals AS ga,
    CASE WHEN home_goals > away_goals THEN 'W' WHEN home_goals = away_goals THEN 'D' ELSE 'L' END AS result_char
  FROM played
),
away_apps AS (
  SELECT
    season_id, division, away_club_short_name AS club_short_name, matchday,
    1 AS mp,
    CASE WHEN away_goals > home_goals THEN 1 ELSE 0 END AS w,
    CASE WHEN away_goals = home_goals THEN 1 ELSE 0 END AS d,
    CASE WHEN away_goals < home_goals THEN 1 ELSE 0 END AS l,
    away_goals AS gf, home_goals AS ga,
    CASE WHEN away_goals > home_goals THEN 'W' WHEN away_goals = home_goals THEN 'D' ELSE 'L' END AS result_char
  FROM played
),
all_apps AS (
  SELECT * FROM home_apps UNION ALL SELECT * FROM away_apps
),
totals AS (
  SELECT
    season_id, division, club_short_name,
    sum(mp)::int AS mp, sum(w)::int AS w, sum(d)::int AS d, sum(l)::int AS l,
    sum(gf)::int AS gf, sum(ga)::int AS ga, sum(gf) - sum(ga) AS gd,
    sum(w) * 3 + sum(d) AS pts
  FROM all_apps
  GROUP BY season_id, division, club_short_name
),
point_adj AS (
  SELECT a.season_id, a.club_short_name, sum(a.points_delta)::int AS adj_pts
  FROM public.competition_league_points_adjustments a
  JOIN active_season s ON s.id = a.season_id
  GROUP BY a.season_id, a.club_short_name
),
form_strings AS (
  SELECT
    r.season_id, r.division, r.club_short_name,
    (
      SELECT string_agg(x.result_char, '' ORDER BY x.matchday)
      FROM (
        SELECT a2.result_char, a2.matchday
        FROM all_apps a2
        WHERE a2.season_id = r.season_id
          AND a2.division = r.division
          AND a2.club_short_name = r.club_short_name
        ORDER BY a2.matchday DESC
        LIMIT 10
      ) x
    ) AS form_last10
  FROM registered r
),
combined AS (
  SELECT
    r.season_id, r.division, r.club_short_name, r.club_name,
    coalesce(t.mp, 0) AS mp, coalesce(t.w, 0) AS w, coalesce(t.d, 0) AS d,
    coalesce(t.l, 0) AS l, coalesce(t.gf, 0) AS gf, coalesce(t.ga, 0) AS ga,
    coalesce(t.gd, 0) AS gd,
    coalesce(t.pts, 0) + coalesce(pa.adj_pts, 0) AS pts,
    coalesce(f.form_last10, '') AS form_last10
  FROM registered r
  LEFT JOIN totals t
    ON t.season_id = r.season_id AND t.division = r.division AND t.club_short_name = r.club_short_name
  LEFT JOIN point_adj pa
    ON pa.season_id = r.season_id AND pa.club_short_name = r.club_short_name
  LEFT JOIN form_strings f
    ON f.season_id = r.season_id AND f.division = r.division AND f.club_short_name = r.club_short_name
)
SELECT
  season_id, division, club_short_name, club_name,
  row_number() OVER (
    PARTITION BY season_id, division
    ORDER BY pts DESC, gd DESC, gf DESC, club_name ASC
  )::int AS table_position,
  mp, w, d, l, gf, ga, gd, pts, form_last10
FROM combined;

GRANT SELECT ON public.competition_standings_public TO authenticated;
GRANT SELECT ON public.competition_standings_public TO anon;

-- ---------------------------------------------------------------------------
-- RLS: club OR owner-scoped inbox
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS competition_inbox_select ON public.competition_inbox;
CREATE POLICY competition_inbox_select ON public.competition_inbox
  FOR SELECT TO authenticated
  USING (
    recipient_club_short_name = public.my_club_shortname()
    OR owner_id = auth.uid()
    OR public.is_gpsl_admin()
  );

DROP POLICY IF EXISTS competition_inbox_update ON public.competition_inbox;
CREATE POLICY competition_inbox_update ON public.competition_inbox
  FOR UPDATE TO authenticated
  USING (
    recipient_club_short_name = public.my_club_shortname()
    OR owner_id = auth.uid()
  )
  WITH CHECK (
    recipient_club_short_name = public.my_club_shortname()
    OR owner_id = auth.uid()
  );

-- ---------------------------------------------------------------------------
-- Core send helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.owner_inbox_send(
  p_message_type text,
  p_title text,
  p_body text,
  p_recipient_club text DEFAULT NULL,
  p_owner_id uuid DEFAULT NULL,
  p_fixture_id bigint DEFAULT NULL,
  p_submission_id bigint DEFAULT NULL,
  p_transfer_history_id bigint DEFAULT NULL,
  p_transfer_listing_id bigint DEFAULT NULL,
  p_action_href text DEFAULT NULL,
  p_dedupe_key text DEFAULT NULL,
  p_gpsl_month text DEFAULT NULL,
  p_season_id bigint DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint;
  v_club text := nullif(btrim(p_recipient_club), '');
BEGIN
  IF v_club IS NULL AND p_owner_id IS NULL THEN
    RETURN NULL;
  END IF;

  IF v_club = 'FOREIGN' THEN
    RETURN NULL;
  END IF;

  IF p_dedupe_key IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.competition_inbox i WHERE i.dedupe_key = p_dedupe_key
  ) THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.competition_inbox (
    recipient_club_short_name, owner_id, message_type,
    fixture_id, submission_id, transfer_history_id, transfer_listing_id,
    title, body, action_href, dedupe_key, gpsl_month, season_id
  )
  VALUES (
    v_club, p_owner_id, p_message_type,
    p_fixture_id, p_submission_id, p_transfer_history_id, p_transfer_listing_id,
    p_title, p_body, p_action_href, p_dedupe_key, p_gpsl_month, p_season_id
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_inbox_notify(
  p_recipient_club text,
  p_message_type text,
  p_fixture_id bigint,
  p_submission_id bigint,
  p_title text,
  p_body text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  RETURN public.owner_inbox_send(
    p_message_type,
    p_title,
    p_body,
    p_recipient_club,
    NULL,
    p_fixture_id,
    p_submission_id
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_inbox_mark_read(p_inbox_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  UPDATE public.competition_inbox
  SET read_at = now()
  WHERE id = p_inbox_id
    AND read_at IS NULL
    AND (
      recipient_club_short_name = public.my_club_shortname()
      OR owner_id = auth.uid()
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.owner_inbox_notify_all_clubs(
  p_message_type text,
  p_title text,
  p_body text,
  p_action_href text DEFAULT NULL,
  p_dedupe_key text DEFAULT NULL,
  p_season_id bigint DEFAULT NULL
)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club record;
  v_count int := 0;
BEGIN
  FOR v_club IN
    SELECT c."ShortName" AS short_name
    FROM public."Clubs" c
    WHERE c.owner_id IS NOT NULL
    ORDER BY c."ShortName"
  LOOP
    IF public.owner_inbox_send(
      p_message_type, p_title, p_body, v_club.short_name, NULL,
      NULL, NULL, NULL, NULL, p_action_href,
      CASE WHEN p_dedupe_key IS NOT NULL THEN p_dedupe_key || ':' || v_club.short_name ELSE NULL END,
      NULL, p_season_id
    ) IS NOT NULL THEN
      v_count := v_count + 1;
    END IF;
  END LOOP;
  RETURN v_count;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Welcome / learning GPSL
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.owner_inbox_send_welcome(uuid, text);

CREATE OR REPLACE FUNCTION public.owner_inbox_send_welcome(
  p_owner_id uuid,
  p_club_short_name text DEFAULT NULL,
  p_created_at timestamptz DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club_name text;
  v_body text;
  v_id bigint;
  v_dedupe text;
BEGIN
  IF p_club_short_name IS NOT NULL THEN
    SELECT c."Club" INTO v_club_name FROM public."Clubs" c WHERE c."ShortName" = p_club_short_name;
    v_body := format(
      E'Welcome to GPSL — you are now linked to %s.\n\nRead Learning GPSL for navigation, auctions, contracts, matchday, and club expectations.',
      coalesce(v_club_name, p_club_short_name)
    );
    v_dedupe := 'welcome:' || upper(trim(p_club_short_name));

    IF EXISTS (SELECT 1 FROM public.competition_inbox i WHERE i.dedupe_key = v_dedupe) THEN
      RETURN NULL;
    END IF;

    INSERT INTO public.competition_inbox (
      recipient_club_short_name, owner_id, message_type,
      title, body, action_href, dedupe_key, created_at
    )
    VALUES (
      upper(trim(p_club_short_name)),
      NULL,
      'welcome_gpsl',
      'Welcome to GPSL',
      v_body,
      'learning_gpsl.html',
      v_dedupe,
      coalesce(p_created_at, now())
    )
    RETURNING id INTO v_id;

    RETURN v_id;
  END IF;

  v_body := E'Welcome to GPSL.\n\nYou are registered for the club auction. Read Learning GPSL while you wait — it covers navigation, auctions, contracts, and what is expected of owners.';
  v_dedupe := 'welcome:owner:' || p_owner_id::text;

  IF EXISTS (SELECT 1 FROM public.competition_inbox i WHERE i.dedupe_key = v_dedupe) THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.competition_inbox (
    recipient_club_short_name, owner_id, message_type,
    title, body, action_href, dedupe_key, created_at
  )
  VALUES (
    NULL,
    p_owner_id,
    'welcome_gpsl',
    'Welcome to GPSL',
    v_body,
    'learning_gpsl.html',
    v_dedupe,
    coalesce(p_created_at, now())
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Result submitted (trigger — submitter acknowledgement)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.trg_result_submission_notify_submitter()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_home_name text;
  v_away_name text;
  v_label text;
BEGIN
  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = NEW.fixture_id;
  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  v_label := CASE
    WHEN v_fixture.competition_type = 'cup' THEN public.competition_cup_fixture_label(v_fixture)
    ELSE format('GPSL %s', coalesce(public.competition_gpsl_month_label(v_fixture.gpsl_month), v_fixture.gpsl_month, 'month'))
  END;

  PERFORM public.owner_inbox_send(
    'result_submitted',
    format('Result submitted: %s vs %s', v_home_name, v_away_name),
    format(
      E'%s — you submitted %s %s–%s %s.\nWaiting for your opponent to confirm or reject.',
      v_label, v_home_name, NEW.home_goals, NEW.away_goals, v_away_name
    ),
    NEW.submitted_by_club,
    NULL,
    NEW.fixture_id,
    NEW.id,
    NULL, NULL,
    'matchday.html?fixture=' || NEW.fixture_id::text,
    'result_submitted:' || NEW.id::text,
    v_fixture.gpsl_month,
    v_fixture.season_id
  );

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS result_submission_notify_submitter ON public.competition_result_submissions;
CREATE TRIGGER result_submission_notify_submitter
  AFTER INSERT ON public.competition_result_submissions
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_result_submission_notify_submitter();

-- ---------------------------------------------------------------------------
-- Fines (trigger)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.trg_fine_applied_inbox_notify()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_title text;
  v_body text;
  v_amount text;
BEGIN
  v_amount := public.transfer_format_money(NEW.amount);
  v_title := CASE
    WHEN NEW.direction = 'fine' THEN 'Fine applied'
    ELSE 'Compensation credited'
  END;
  v_body := concat_ws(
    E'\n',
    NEW.description,
    CASE WHEN NEW.direction = 'fine' THEN 'Amount: ' || v_amount ELSE 'Credit: ' || v_amount END,
    CASE WHEN NEW.note IS NOT NULL AND btrim(NEW.note) <> '' THEN 'Note: ' || NEW.note ELSE NULL END
  );

  PERFORM public.owner_inbox_send(
    'fine_applied',
    v_title,
    v_body,
    NEW.club_short_name,
    NULL,
    NEW.fixture_id,
    NULL, NULL, NULL,
    'finances.html',
    'fine:' || NEW.id::text,
    NULL,
    NEW.season_id
  );

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS fine_applied_inbox_notify ON public.competition_fine_applied;
CREATE TRIGGER fine_applied_inbox_notify
  AFTER INSERT ON public.competition_fine_applied
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_fine_applied_inbox_notify();

-- ---------------------------------------------------------------------------
-- Points deduction (admin RPC)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_admin_adjust_league_points(
  p_club_short_name text,
  p_points_delta smallint,
  p_reason text,
  p_season_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_club text := upper(btrim(p_club_short_name));
  v_adj_id bigint;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_points_delta IS NULL OR p_points_delta = 0 THEN
    RAISE EXCEPTION 'points_delta must be non-zero';
  END IF;

  IF p_reason IS NULL OR btrim(p_reason) = '' THEN
    RAISE EXCEPTION 'reason is required';
  END IF;

  v_season_id := p_season_id;
  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id FROM public.competition_seasons WHERE is_current = true LIMIT 1;
  END IF;

  INSERT INTO public.competition_league_points_adjustments (
    season_id, club_short_name, points_delta, reason
  )
  VALUES (v_season_id, v_club, p_points_delta, btrim(p_reason))
  RETURNING id INTO v_adj_id;

  PERFORM public.owner_inbox_send(
    'points_deduction',
    CASE WHEN p_points_delta < 0 THEN 'League points deduction' ELSE 'League points adjustment' END,
    format(
      E'%s point(s) %s.\nReason: %s',
      abs(p_points_delta),
      CASE WHEN p_points_delta < 0 THEN 'deducted' ELSE 'added' END,
      btrim(p_reason)
    ),
    v_club,
    NULL,
    NULL, NULL, NULL, NULL,
    'progress.html',
    'points_adj:' || v_adj_id::text,
    NULL,
    v_season_id
  );

  RETURN jsonb_build_object('ok', true, 'adjustment_id', v_adj_id, 'club', v_club, 'delta', p_points_delta);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Nation selection notifications
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.owner_inbox_notify_nation_pick_turn(p_pick_rank smallint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club record;
BEGIN
  FOR v_club IN
    SELECT d.club_short_name, d.pick_order
    FROM public.international_owner_draft_order() d
    WHERE d.pick_order = p_pick_rank
  LOOP
    PERFORM public.owner_inbox_send(
      'nation_pick_turn',
      'Your turn — pick a nation',
      format(
        E'Nation selection: you are pick #%s of %s.\nChoose your national team on the Nation selection page.',
        p_pick_rank,
        (SELECT count(*)::integer FROM public.international_owner_draft_order())
      ),
      v_club.club_short_name,
      NULL,
      NULL, NULL, NULL, NULL,
      'nation_select.html',
      'nation_pick:' || p_pick_rank::text || ':' || v_club.club_short_name,
      NULL, NULL
    );
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_admin_open_selection(p_phase text)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint;
  v_phase text := coalesce(nullif(btrim(p_phase), ''), 'initial');
  v_club record;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_phase NOT IN ('initial', 'post_world_cup') THEN
    RAISE EXCEPTION 'Invalid phase';
  END IF;

  UPDATE public.international_selection_windows
  SET is_open = false, closes_at = coalesce(closes_at, now())
  WHERE is_open = true;

  INSERT INTO public.international_selection_windows (phase, is_open, opens_at, current_pick_rank)
  VALUES (v_phase, true, now(), 1)
  RETURNING id INTO v_id;

  FOR v_club IN
    SELECT c."ShortName" AS short_name
    FROM public."Clubs" c
    WHERE c.owner_id IS NOT NULL
  LOOP
    PERFORM public.owner_inbox_send(
      'nation_selection_open',
      'Nation selection is open',
      E'The international nation draft has started. Owners will pick in ranking order — you will receive a message when it is your turn.',
      v_club.short_name,
      NULL,
      NULL, NULL, NULL, NULL,
      'nation_select.html',
      'nation_open:' || v_id::text || ':' || v_club.short_name,
      NULL, NULL
    );
  END LOOP;

  PERFORM public.owner_inbox_notify_nation_pick_turn(1);

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_claim_nation(p_nation_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_window record;
  v_my_pick smallint;
  v_current_pick smallint;
  v_nation text := btrim(upper(p_nation_code));
  v_cycle_id bigint;
  v_next_pick smallint;
  v_nation_name text;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to your account';
  END IF;

  SELECT * INTO v_window
  FROM public.international_selection_windows
  WHERE is_open = true
  ORDER BY id DESC
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nation selection is not open';
  END IF;

  SELECT pick_order INTO v_my_pick
  FROM public.international_owner_draft_order()
  WHERE club_short_name = v_club;

  IF v_my_pick IS NULL THEN
    RAISE EXCEPTION 'Your club is not in the owner draft order';
  END IF;

  v_current_pick := v_window.current_pick_rank;

  IF v_my_pick <> v_current_pick THEN
    RAISE EXCEPTION 'Not your pick yet (currently pick #% — you are #%).', v_current_pick, v_my_pick;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.international_nations n
    WHERE n.code = v_nation AND n.active = true
  ) THEN
    RAISE EXCEPTION 'Nation not found';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.international_owner_nations ion
    WHERE ion.nation_code = v_nation AND ion.is_active = true
  ) THEN
    RAISE EXCEPTION 'Nation already taken';
  END IF;

  IF to_regprocedure('public.international_nation_pool_is_selectable(text)') IS NOT NULL
     AND NOT public.international_nation_pool_is_selectable(v_nation) THEN
    RAISE EXCEPTION 'This nation cannot be selected — GPDB pool too small for a squad or GPSL club';
  END IF;

  SELECT n.name INTO v_nation_name FROM public.international_nations n WHERE n.code = v_nation;

  SELECT id INTO v_cycle_id FROM public.international_wc_cycles ORDER BY cycle_no DESC LIMIT 1;

  UPDATE public.international_owner_nations
  SET is_active = false, released_at = now()
  WHERE club_short_name = v_club AND is_active = true;

  INSERT INTO public.international_owner_nations (
    club_short_name, nation_code, cycle_id, selection_phase, is_active, locked_until_cycle_id
  )
  VALUES (v_club, v_nation, v_cycle_id, v_window.phase, true, v_cycle_id);

  SELECT coalesce(min(pick_order), 61)::smallint INTO v_next_pick
  FROM public.international_owner_draft_order() d
  WHERE NOT EXISTS (
    SELECT 1 FROM public.international_owner_nations ion
    WHERE ion.club_short_name = d.club_short_name AND ion.is_active = true
  );

  IF v_next_pick >= 61 THEN
    UPDATE public.international_selection_windows
    SET is_open = false, closes_at = now()
    WHERE id = v_window.id;
  ELSE
    UPDATE public.international_selection_windows
    SET current_pick_rank = v_next_pick
    WHERE id = v_window.id;
    PERFORM public.owner_inbox_notify_nation_pick_turn(v_next_pick);
  END IF;

  RETURN jsonb_build_object(
    'club', v_club,
    'nation', v_nation,
    'nation_name', v_nation_name,
    'pick', v_my_pick,
    'next_pick', v_next_pick
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Draft / transfer window upcoming (global_settings trigger)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.owner_inbox_notify_draft_schedule_from_settings(
  p_old public.global_settings,
  p_new public.global_settings
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_start text;
  v_start_changed boolean;
  v_player_on boolean;
  v_manager_on boolean;
  v_player_notify boolean;
  v_manager_notify boolean;
  v_dedupe_ts text;
BEGIN
  IF p_new.draft_auction_start_time IS NULL THEN
    RETURN;
  END IF;

  v_start_changed := p_new.draft_auction_start_time IS DISTINCT FROM p_old.draft_auction_start_time;
  v_player_on := coalesce(p_new.draft_auction_enabled, false);
  v_manager_on := coalesce(p_new.manager_draft_auction_enabled, false);

  v_player_notify := v_player_on
    AND (
      v_start_changed
      OR (v_player_on AND NOT coalesce(p_old.draft_auction_enabled, false))
    );

  v_manager_notify := v_manager_on
    AND (
      v_start_changed
      OR (v_manager_on AND NOT coalesce(p_old.manager_draft_auction_enabled, false))
    );

  IF NOT v_player_notify AND NOT v_manager_notify THEN
    RETURN;
  END IF;

  v_start := to_char(p_new.draft_auction_start_time AT TIME ZONE 'Europe/London', 'Dy DD Mon YYYY HH24:MI');
  v_dedupe_ts := floor(extract(epoch FROM coalesce(p_new.updated_at, now())))::text;

  IF v_player_notify THEN
    PERFORM public.owner_inbox_notify_all_clubs(
      'draft_scheduled',
      'Player draft auction scheduled',
      format(
        E'Player draft auction opens %s (UK).\nBidding closes at a secret random time — the countdown on the draft auction page never shows the exact moment in advance.\nCheck GPDB and Draft Auction.',
        v_start
      ),
      'draftauction.html',
      'draft_scheduled:player:' || p_new.draft_auction_start_time::text || ':' || v_dedupe_ts,
      NULL
    );
  END IF;

  IF v_manager_notify THEN
    PERFORM public.owner_inbox_notify_all_clubs(
      'draft_scheduled',
      'Manager draft auction scheduled',
      format(
        E'Manager draft auction opens %s (UK).\nBidding closes at a secret random time — the countdown on MGDB never shows the exact moment in advance.\nCheck MGDB and Manager Draft Auction.',
        v_start
      ),
      'manager_draftauction.html',
      'draft_scheduled:manager:' || p_new.draft_auction_start_time::text || ':' || v_dedupe_ts,
      NULL
    );
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.trg_global_settings_inbox_notify()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  PERFORM public.owner_inbox_notify_draft_schedule_from_settings(OLD, NEW);

  IF NEW.transfer_window_open IS TRUE AND coalesce(OLD.transfer_window_open, false) IS FALSE THEN
    PERFORM public.owner_inbox_notify_all_clubs(
      'transfer_upcoming',
      'Transfer window is open',
      E'The transfer window is now open. List players, make offers, and watch the transfer market.',
      'transfer_center.html',
      'transfer_window_open:' || to_char(now(), 'YYYYMMDD'),
      NULL
    );
  END IF;

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS global_settings_inbox_notify ON public.global_settings;
CREATE TRIGGER global_settings_inbox_notify
  AFTER UPDATE ON public.global_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_global_settings_inbox_notify();

-- ---------------------------------------------------------------------------
-- Season expectations (when manager signed)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.owner_inbox_notify_season_expectations(p_club_short_name text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_mgr public."Managers"%rowtype;
  v_division text;
  v_target public.manager_rating_targets;
  v_fill numeric;
  v_target_fill numeric;
  v_body text;
BEGIN
  SELECT * INTO v_mgr
  FROM public."Managers" m
  WHERE m.contracted_club = p_club_short_name
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT ccs.division INTO v_division
  FROM public.competition_club_seasons ccs
  JOIN public.competition_seasons s ON s.id = ccs.season_id AND s.is_current = true
  WHERE ccs.club_short_name = p_club_short_name
  LIMIT 1;

  v_target := public.manager_target_for(v_mgr.rating, coalesce(v_division, 'championship_a'));

  SELECT c.stadium_display_fill_pct, c.stadium_fill_target_pct
  INTO v_fill, v_target_fill
  FROM public."Clubs" c
  WHERE c."ShortName" = p_club_short_name;

  v_body := concat_ws(
    E'\n',
    format('Manager: %s (rating %s, %s season(s) remaining)', v_mgr.name, v_mgr.rating, v_mgr.contract_seasons_remaining),
    CASE
      WHEN v_target.label IS NOT NULL AND btrim(v_target.label) <> '' THEN
        format('League target: %s — meet this to retain your manager at season end.', v_target.label)
      WHEN v_target.id IS NOT NULL THEN
        format('League target: %s in %s to retain your manager at season end.',
          v_target.target_kind, coalesce(v_division, 'your division'))
      ELSE 'League target: meet your division finish band to retain your manager.'
    END,
    format('Stadium: maintain strong attendance — current fill %s%%, season target %s%%. Poor performance reduces gate fill and can trigger penalties.',
      coalesce(round(v_fill)::text, '?'), coalesce(round(v_target_fill)::text, '100')),
    E'See Stadium and Club Details for full expectations.'
  );

  PERFORM public.owner_inbox_send(
    'season_expectations',
    'Season expectations',
    v_body,
    p_club_short_name,
    NULL,
    NULL, NULL, NULL, NULL,
    'stadium.html',
    'season_expectations:' || p_club_short_name || ':' || v_mgr.id::text,
    NULL, NULL
  );
END;
$function$;

-- manager_assign_to_club: canonical definition in managers_system.sql (dedupe patch drops stale overloads).

-- ---------------------------------------------------------------------------
-- Monthly fixture preview
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.owner_inbox_build_month_preview_body(
  p_club_short_name text,
  p_season_id bigint,
  p_gpsl_month text
)
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture record;
  v_opp text;
  v_opp_name text;
  v_lines text[] := ARRAY[]::text[];
  v_line text;
  v_standing record;
  v_mgr_name text;
  v_scorers text;
  v_assisters text;
  v_threats text;
  v_month_label text;
BEGIN
  v_month_label := coalesce(public.competition_gpsl_month_label(p_gpsl_month), p_gpsl_month);

  FOR v_fixture IN
    SELECT f.*
    FROM public.competition_fixtures f
    WHERE f.season_id = p_season_id
      AND f.gpsl_month = p_gpsl_month
      AND f.status = 'scheduled'
      AND p_club_short_name IN (f.home_club_short_name, f.away_club_short_name)
    ORDER BY f.week_in_month, f.id
  LOOP
    v_opp := CASE
      WHEN v_fixture.home_club_short_name = p_club_short_name THEN v_fixture.away_club_short_name
      ELSE v_fixture.home_club_short_name
    END;

    SELECT c."Club" INTO v_opp_name FROM public."Clubs" c WHERE c."ShortName" = v_opp;

    SELECT s.table_position, s.w, s.d, s.l, s.pts, s.form_last10
    INTO v_standing
    FROM public.competition_standings_public s
    WHERE s.season_id = p_season_id AND s.club_short_name = v_opp;

    SELECT m.name INTO v_mgr_name
    FROM public."Managers" m
    WHERE m.contracted_club = v_opp
    LIMIT 1;

    SELECT string_agg(x.nm || ' (' || x.g::text || ')', ', ' ORDER BY x.g DESC, x.nm)
    INTO v_scorers
    FROM (
      SELECT p."Name" AS nm, coalesce(ps.goals, 0) AS g
      FROM public."Players" p
      LEFT JOIN public.competition_player_season_stats_public ps
        ON ps.player_id = p."Konami_ID"::text AND ps.club_short_name = v_opp
      WHERE p."Contracted_Team" = v_opp AND coalesce(ps.goals, 0) > 0
      ORDER BY coalesce(ps.goals, 0) DESC, p."Name"
      LIMIT 3
    ) x;

    SELECT string_agg(x.nm || ' (' || x.a::text || ')', ', ' ORDER BY x.a DESC, x.nm)
    INTO v_assisters
    FROM (
      SELECT p."Name" AS nm, coalesce(ps.assists, 0) AS a
      FROM public."Players" p
      LEFT JOIN public.competition_player_season_stats_public ps
        ON ps.player_id = p."Konami_ID"::text AND ps.club_short_name = v_opp
      WHERE p."Contracted_Team" = v_opp AND coalesce(ps.assists, 0) > 0
      ORDER BY coalesce(ps.assists, 0) DESC, p."Name"
      LIMIT 2
    ) x;

    SELECT string_agg(x.nm, ', ' ORDER BY x.r DESC)
    INTO v_threats
    FROM (
      SELECT p."Name" AS nm,
        coalesce(nullif(btrim(p."Rating"::text), '')::int, 0) AS r
      FROM public."Players" p
      WHERE p."Contracted_Team" = v_opp
      ORDER BY coalesce(nullif(btrim(p."Rating"::text), '')::int, 0) DESC, p."Name"
      LIMIT 3
    ) x;

    v_line := format(
      E'• %s %s (%s)\n  Opponent record: %sW-%sD-%sL, %s pts, pos %s. Form: %s\n  Manager: %s\n  Top rated: %s\n  Goal threats: %s\n  Top assists: %s',
      CASE WHEN v_fixture.home_club_short_name = p_club_short_name THEN 'Home vs' ELSE 'Away at' END,
      coalesce(v_opp_name, v_opp),
      CASE WHEN v_fixture.competition_type = 'cup' THEN coalesce(v_fixture.cup_code, 'cup') ELSE 'league' END,
      coalesce(v_standing.w::text, '0'),
      coalesce(v_standing.d::text, '0'),
      coalesce(v_standing.l::text, '0'),
      coalesce(v_standing.pts::text, '0'),
      coalesce(v_standing.table_position::text, '—'),
      coalesce(nullif(v_standing.form_last10, ''), '—'),
      coalesce(v_mgr_name, 'TBC'),
      coalesce(v_threats, '—'),
      coalesce(v_scorers, '—'),
      coalesce(v_assisters, '—')
    );

    v_lines := array_append(v_lines, v_line);
  END LOOP;

  IF coalesce(array_length(v_lines, 1), 0) = 0 THEN
    RETURN 'No scheduled fixtures in ' || v_month_label || '.';
  END IF;

  RETURN array_to_string(v_lines, E'\n\n');
END;
$function$;

CREATE OR REPLACE FUNCTION public.owner_inbox_notify_monthly_fixtures(
  p_season_id bigint DEFAULT NULL,
  p_gpsl_month text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_month text;
  v_club record;
  v_body text;
  v_count int := 0;
  v_label text;
BEGIN
  v_season_id := p_season_id;
  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id FROM public.competition_seasons WHERE is_current = true AND status = 'active' LIMIT 1;
  END IF;

  v_month := p_gpsl_month;
  IF v_month IS NULL THEN
    v_month := public.competition_active_gpsl_month(v_season_id, now());
  END IF;

  IF v_season_id IS NULL OR v_month IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_active_month');
  END IF;

  v_label := coalesce(public.competition_gpsl_month_label(v_month), v_month);

  FOR v_club IN
    SELECT c."ShortName" AS short_name
    FROM public."Clubs" c
    WHERE c.owner_id IS NOT NULL
      AND EXISTS (
        SELECT 1 FROM public.competition_fixtures f
        WHERE f.season_id = v_season_id
          AND f.gpsl_month = v_month
          AND f.status = 'scheduled'
          AND c."ShortName" IN (f.home_club_short_name, f.away_club_short_name)
      )
  LOOP
    v_body := public.owner_inbox_build_month_preview_body(v_club.short_name, v_season_id, v_month);

    IF public.owner_inbox_send(
      'monthly_fixtures',
      format('GPSL %s — your matches', v_label),
      v_body,
      v_club.short_name,
      NULL,
      NULL, NULL, NULL, NULL,
      'fixtures.html',
      format('month_preview:%s:%s:%s', v_season_id, v_month, v_club.short_name),
      v_month,
      v_season_id
    ) IS NOT NULL THEN
      v_count := v_count + 1;
    END IF;
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'season_id', v_season_id, 'gpsl_month', v_month, 'notified', v_count);
END;
$function$;

CREATE OR REPLACE FUNCTION public.owner_inbox_tick_monthly_notifications()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_month_row record;
BEGIN
  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true AND status = 'active'
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_active_season');
  END IF;

  SELECT m.gpsl_month, m.unlock_at
  INTO v_month_row
  FROM public.competition_season_calendar m
  WHERE m.season_id = v_season_id
    AND now() >= m.unlock_at
    AND now() < m.lock_at
  ORDER BY m.sort_order
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_active_calendar_month');
  END IF;

  RETURN public.owner_inbox_notify_monthly_fixtures(v_season_id, v_month_row.gpsl_month);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Season archive: player awards + season overview per club
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.owner_inbox_notify_club_season_archive(
  p_season_id bigint,
  p_season_label text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club record;
  v_award record;
  v_mgr public."Managers"%rowtype;
  v_star text;
  v_award_lines text[] := ARRAY[]::text[];
  v_overview text;
  v_pos int;
  v_div text;
BEGIN
  FOR v_club IN
    SELECT
      a.club_short_name,
      a.division,
      a.final_position,
      a.pts,
      a.won AS w,
      a.drawn AS d,
      a.lost AS l,
      c."Club" AS club_name
    FROM public.competition_club_season_archive a
    JOIN public."Clubs" c ON c."ShortName" = a.club_short_name
  WHERE a.season_id = p_season_id
      AND EXISTS (SELECT 1 FROM public."Clubs" cx WHERE cx."ShortName" = a.club_short_name AND cx.owner_id IS NOT NULL)
  LOOP
    v_award_lines := ARRAY[]::text[];

    FOR v_award IN
      SELECT aw.award_type, aw.stat_value, aw.detail, p."Name" AS player_name
      FROM public.competition_season_award aw
      LEFT JOIN public."Players" p ON p."Konami_ID"::text = aw.player_id
      WHERE aw.season_id = p_season_id
        AND aw.club_short_name = v_club.club_short_name
      ORDER BY aw.award_type
    LOOP
      v_award_lines := array_append(
        v_award_lines,
        format('%s: %s (%s)', replace(v_award.award_type, '_', ' '), v_award.player_name, v_award.stat_value)
      );
    END LOOP;

    IF coalesce(array_length(v_award_lines, 1), 0) > 0 THEN
      PERFORM public.owner_inbox_send(
        'player_awards',
        format('Season awards — %s', p_season_label),
        array_to_string(v_award_lines, E'\n'),
        v_club.club_short_name,
        NULL,
        NULL, NULL, NULL, NULL,
        'history.html',
        format('awards:%s:%s', p_season_id, v_club.club_short_name),
        NULL,
        p_season_id
      );
    END IF;

    SELECT * INTO v_mgr FROM public."Managers" m WHERE m.contracted_club = v_club.club_short_name LIMIT 1;

    SELECT p."Name" INTO v_star
    FROM public.competition_player_season_archive ps
    JOIN public."Players" p ON p."Konami_ID"::text = ps.player_id
    WHERE ps.season_id = p_season_id AND ps.club_short_name = v_club.club_short_name
    ORDER BY ps.ballon_points DESC, ps.goals DESC
    LIMIT 1;

    v_overview := concat_ws(
      E'\n',
      format('Final league position: %s in %s (%s pts, %sW-%sD-%sL)',
        v_club.final_position, v_club.division, v_club.pts, v_club.w, v_club.d, v_club.l),
      CASE
        WHEN v_mgr.id IS NOT NULL THEN format('Manager: %s — %s season(s) on contract', v_mgr.name, v_mgr.contract_seasons_remaining)
        ELSE 'Manager: none signed'
      END,
      CASE WHEN v_star IS NOT NULL THEN 'Star player: ' || v_star ELSE NULL END,
      'See Club History and Owner Rankings for the full season breakdown.'
    );

    PERFORM public.owner_inbox_send(
      'season_overview',
      format('Season overview — %s', p_season_label),
      v_overview,
      v_club.club_short_name,
      NULL,
      NULL, NULL, NULL, NULL,
      'history.html',
      format('season_overview:%s:%s', p_season_id, v_club.club_short_name),
      NULL,
      p_season_id
    );
  END LOOP;
END;
$function$;

-- Wrapper: archive season then notify all owners (awards + overview)
CREATE OR REPLACE FUNCTION public.competition_admin_archive_season_with_inbox(p_season_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_result jsonb;
  v_season_id bigint;
  v_label text;
BEGIN
  v_result := public.competition_admin_archive_season(p_season_id);
  v_season_id := (v_result ->> 'season_id')::bigint;
  v_label := v_result ->> 'season_label';

  IF v_season_id IS NOT NULL THEN
    PERFORM public.owner_inbox_notify_club_season_archive(v_season_id, coalesce(v_label, 'Season'));
  END IF;

  RETURN v_result;
END;
$function$;

-- Manager season-end notifications (call after manager_process_season_end)
CREATE OR REPLACE FUNCTION public.owner_inbox_notify_manager_season_end(p_results jsonb)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_row jsonb;
  v_club text;
  v_action text;
  v_body text;
BEGIN
  IF p_results IS NULL OR jsonb_typeof(p_results) <> 'array' THEN
    RETURN;
  END IF;

  FOR v_row IN SELECT * FROM jsonb_array_elements(p_results)
  LOOP
    v_club := v_row ->> 'club';
    v_action := v_row ->> 'action';
    IF v_club IS NULL OR v_club = '' THEN
      CONTINUE;
    END IF;

    v_body := CASE v_action
      WHEN 'renewed' THEN format('Your manager met the league target (finished %s). Contract renewed for 2 seasons.', v_row ->> 'position')
      WHEN 'released' THEN format('Your manager missed the league target (finished %s). They have been released; your club received market-value compensation.', v_row ->> 'position')
      WHEN 'contract_expired' THEN 'Your manager contract expired and they have left the club.'
      ELSE format('Manager review: %s', v_action)
    END;

    PERFORM public.owner_inbox_send(
      'season_overview',
      CASE v_action
        WHEN 'renewed' THEN 'Manager retained'
        WHEN 'released' THEN 'Manager released'
        ELSE 'Manager update'
      END,
      v_body,
      v_club,
      NULL,
      NULL, NULL, NULL, NULL,
      'club_details.html',
      format('mgr_end:%s:%s', v_club, v_action),
      NULL, NULL
    );
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.manager_process_season_end_with_inbox()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_result jsonb;
BEGIN
  v_result := public.manager_process_season_end();
  PERFORM public.owner_inbox_notify_manager_season_end(v_result -> 'results');
  RETURN v_result;
END;
$function$;

-- Welcome on club link / auction registration
CREATE OR REPLACE FUNCTION public.admin_assign_club_owner(
  p_owner_email text,
  p_club_short_name text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_email text := lower(trim(p_owner_email));
  v_short text := upper(trim(p_club_short_name));
  v_user_id uuid;
  v_club_name text;
  v_replaced_previous boolean := false;
  v_registry_status text;
  v_displaced uuid;
  v_old_club text;
  v_tag text;
  v_result jsonb;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_email IS NULL OR v_email = '' THEN
    RAISE EXCEPTION 'Owner email is required';
  END IF;

  IF v_short IS NULL OR v_short = '' THEN
    RAISE EXCEPTION 'Club ShortName is required';
  END IF;

  SELECT u.id INTO v_user_id
  FROM auth.users u
  WHERE lower(u.email) = v_email
  LIMIT 1;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No auth user with email %', p_owner_email;
  END IF;

  SELECT r.status INTO v_registry_status
  FROM public.gpsl_owner_registry r
  WHERE r.owner_id = v_user_id;

  IF v_registry_status = 'archived' THEN
    RAISE EXCEPTION 'Owner is archived — unarchive before linking to a club';
  END IF;

  SELECT c."Club" INTO v_club_name
  FROM public."Clubs" c
  WHERE c."ShortName" = v_short;

  IF v_club_name IS NULL THEN
    RAISE EXCEPTION 'Club ShortName % not found', v_short;
  END IF;

  SELECT c.owner_id INTO v_displaced
  FROM public."Clubs" c
  WHERE c."ShortName" = v_short
    AND c.owner_id IS NOT NULL
    AND c.owner_id <> v_user_id
  LIMIT 1;

  IF v_displaced IS NOT NULL THEN
    v_replaced_previous := true;
    PERFORM public.admin_owner_detach_core(v_displaced, 'on_break', 'Displaced by admin club link');
  END IF;

  SELECT c."ShortName", nullif(btrim(c.owner), '')
  INTO v_old_club, v_tag
  FROM public."Clubs" c
  WHERE c.owner_id = v_user_id
    AND c."ShortName" <> v_short
  LIMIT 1;

  IF v_old_club IS NOT NULL THEN
    PERFORM public.admin_club_vacate(v_old_club);
  END IF;

  UPDATE public."Clubs"
  SET owner_id = v_user_id,
      owner = coalesce(v_tag, owner)
  WHERE "ShortName" = v_short;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Failed to update club %', v_short;
  END IF;

  INSERT INTO public.gpsl_owner_registry (owner_id, status, owner_tag, last_club_short_name, status_changed_at)
  VALUES (v_user_id, 'active', v_tag, v_short, now())
  ON CONFLICT (owner_id) DO UPDATE
  SET status = 'active',
      owner_tag = coalesce(excluded.owner_tag, gpsl_owner_registry.owner_tag),
      last_club_short_name = v_short,
      status_note = NULL,
      status_changed_at = now();

  PERFORM public.owner_inbox_send_welcome(v_user_id, v_short);

  v_result := jsonb_build_object(
    'user_id', v_user_id,
    'email', p_owner_email,
    'club_short_name', v_short,
    'club_name', v_club_name,
    'replaced_previous_owner', v_replaced_previous,
    'from_club_short_name', v_old_club
  );

  RETURN v_result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_owner_register_for_club_auction(
  p_owner_email text,
  p_starting_balance numeric DEFAULT 600000000
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_email text := lower(trim(p_owner_email));
  v_user_id uuid;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT u.id INTO v_user_id
  FROM auth.users u
  WHERE lower(u.email) = v_email
  LIMIT 1;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No auth user with email %', p_owner_email;
  END IF;

  IF EXISTS (SELECT 1 FROM public."Clubs" c WHERE c.owner_id = v_user_id) THEN
    RAISE EXCEPTION 'Owner already has a club';
  END IF;

  INSERT INTO public.gpsl_owner_registry (
    owner_id, status, pending_starting_balance, status_changed_at
  )
  VALUES (
    v_user_id,
    'awaiting_club_auction',
    greatest(coalesce(p_starting_balance, 600000000), 0),
    now()
  )
  ON CONFLICT (owner_id) DO UPDATE
  SET status = 'awaiting_club_auction',
      pending_starting_balance = greatest(
        coalesce(excluded.pending_starting_balance, 600000000),
        coalesce(gpsl_owner_registry.pending_starting_balance, 0)
      ),
      status_changed_at = now()
  WHERE gpsl_owner_registry.status <> 'archived';

  PERFORM public.owner_inbox_send_welcome(v_user_id, NULL);

  RETURN jsonb_build_object(
    'ok', true,
    'owner_id', v_user_id,
    'email', p_owner_email,
    'status', 'awaiting_club_auction',
    'pending_starting_balance', greatest(coalesce(p_starting_balance, 600000000), 0)
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.owner_inbox_send(text, text, text, text, uuid, bigint, bigint, bigint, bigint, text, text, text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owner_inbox_send_welcome(uuid, text, timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owner_inbox_notify_all_clubs(text, text, text, text, text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owner_inbox_notify_monthly_fixtures(bigint, smallint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owner_inbox_tick_monthly_notifications() TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_archive_season_with_inbox(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_adjust_league_points(text, smallint, text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.manager_process_season_end_with_inbox() TO authenticated;

NOTIFY pgrst, 'reload schema';
