-- =============================================================================
-- Owners Shop: personal wallet + admin catalogue + buy → club inventory
--
-- • owner_wallets / owner_finance_ledger — personal ₿ (not Club_Finances)
-- • owners_shop_sections / owners_shop_items — admin-configurable shelf
-- • owners_shop_buy — debit owner, grant club_prize_inventory via prize_grant
--
-- Run in Supabase SQL Editor. Safe re-run.
-- Prerequisites: gpsl_owner_registry, club_prize_inventory, prize_grant_inventory_item,
--                is_gpsl_admin(), my_club_shortname()
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Owner wallet + ledger
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.owner_wallets (
  owner_id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  balance numeric(14, 2) NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.owner_finance_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  entry_type text NOT NULL,
  amount numeric(14, 2) NOT NULL,
  description text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  season_id bigint REFERENCES public.competition_seasons (id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS owner_finance_ledger_owner_created_idx
  ON public.owner_finance_ledger (owner_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS owner_finance_ledger_type_idx
  ON public.owner_finance_ledger (entry_type);

ALTER TABLE public.owner_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owner_finance_ledger ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS owner_wallets_select_self_or_admin ON public.owner_wallets;
CREATE POLICY owner_wallets_select_self_or_admin ON public.owner_wallets
  FOR SELECT TO authenticated
  USING (owner_id = auth.uid() OR public.is_gpsl_admin());

DROP POLICY IF EXISTS owner_finance_ledger_select_self_or_admin ON public.owner_finance_ledger;
CREATE POLICY owner_finance_ledger_select_self_or_admin ON public.owner_finance_ledger
  FOR SELECT TO authenticated
  USING (owner_id = auth.uid() OR public.is_gpsl_admin());

CREATE OR REPLACE FUNCTION public.owner_wallet_ensure(p_owner_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF p_owner_id IS NULL THEN
    RAISE EXCEPTION 'Owner required';
  END IF;
  INSERT INTO public.owner_wallets (owner_id, balance)
  VALUES (p_owner_id, 0)
  ON CONFLICT (owner_id) DO NOTHING;
END;
$function$;

-- Internal poster (shop buy, admin adjust, future bookies/GPFL). Not granted to clients.
CREATE OR REPLACE FUNCTION public._post_owner_ledger_internal(
  p_owner_id uuid,
  p_entry_type text,
  p_amount numeric,
  p_description text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb,
  p_season_id bigint DEFAULT NULL,
  p_apply_balance boolean DEFAULT true
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_amt numeric(14, 2);
  v_ledger_id bigint;
  v_season_id bigint := p_season_id;
BEGIN
  IF p_owner_id IS NULL THEN
    RAISE EXCEPTION 'Owner required';
  END IF;
  IF p_entry_type IS NULL OR btrim(p_entry_type) = '' THEN
    RAISE EXCEPTION 'entry_type required';
  END IF;

  v_amt := round(coalesce(p_amount, 0)::numeric, 2);
  IF v_amt = 0 THEN
    RAISE EXCEPTION 'Ledger amount cannot be zero';
  END IF;

  PERFORM public.owner_wallet_ensure(p_owner_id);

  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  INSERT INTO public.owner_finance_ledger (
    owner_id, entry_type, amount, description, metadata, season_id
  )
  VALUES (
    p_owner_id,
    btrim(p_entry_type),
    v_amt,
    nullif(btrim(coalesce(p_description, '')), ''),
    coalesce(p_metadata, '{}'::jsonb),
    v_season_id
  )
  RETURNING id INTO v_ledger_id;

  IF coalesce(p_apply_balance, true) THEN
    UPDATE public.owner_wallets
    SET
      balance = round(balance + v_amt, 2),
      updated_at = now()
    WHERE owner_id = p_owner_id;
  END IF;

  RETURN v_ledger_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.owner_wallet_get_self()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_bal numeric(14, 2);
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not signed in';
  END IF;
  PERFORM public.owner_wallet_ensure(v_uid);
  SELECT balance INTO v_bal FROM public.owner_wallets WHERE owner_id = v_uid;
  RETURN jsonb_build_object(
    'owner_id', v_uid,
    'balance', coalesce(v_bal, 0)
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_owner_wallet_adjust(
  p_owner_id uuid,
  p_amount numeric,
  p_description text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_amt numeric(14, 2);
  v_ledger_id bigint;
  v_bal numeric(14, 2);
  v_type text;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  IF p_owner_id IS NULL THEN
    RAISE EXCEPTION 'Owner required';
  END IF;

  v_amt := round(coalesce(p_amount, 0)::numeric, 2);
  IF v_amt = 0 THEN
    RAISE EXCEPTION 'Amount cannot be zero';
  END IF;

  v_type := CASE WHEN v_amt > 0 THEN 'admin_credit' ELSE 'admin_debit' END;
  v_ledger_id := public._post_owner_ledger_internal(
    p_owner_id,
    v_type,
    v_amt,
    coalesce(nullif(btrim(coalesce(p_description, '')), ''), 'Admin wallet adjustment'),
    jsonb_build_object('source', 'admin_owner_wallet_adjust')
  );

  SELECT balance INTO v_bal FROM public.owner_wallets WHERE owner_id = p_owner_id;
  RETURN jsonb_build_object(
    'ok', true,
    'ledger_id', v_ledger_id,
    'balance', coalesce(v_bal, 0)
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Shop catalogue
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.owners_shop_sections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  label text NOT NULL,
  kicker text,
  intro text,
  theme_key text NOT NULL DEFAULT 'default'
    CHECK (theme_key IN ('medical', 'discipline', 'default', 'coming')),
  sort_order int NOT NULL DEFAULT 100,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.owners_shop_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id bigint NOT NULL REFERENCES public.owners_shop_sections (id) ON DELETE CASCADE,
  sku_code text NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  price numeric(14, 2) NOT NULL CHECK (price >= 0),
  prize_type text NOT NULL
    CHECK (prize_type IN ('medical_token', 'fee_discount', 'appeal_card', 'draft_token')),
  param_int int,
  quantity_granted int NOT NULL DEFAULT 1 CHECK (quantity_granted >= 1 AND quantity_granted <= 20),
  badge_label text,
  sort_order int NOT NULL DEFAULT 100,
  is_active boolean NOT NULL DEFAULT true,
  is_featured boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT owners_shop_items_param_check CHECK (
    (prize_type = 'medical_token' AND param_int IN (2, 4, 6, 8, 10))
    OR (prize_type = 'fee_discount' AND param_int > 0 AND param_int <= 50)
    OR (prize_type = 'appeal_card' AND param_int IS NULL)
    OR (prize_type = 'draft_token' AND (param_int IS NULL OR param_int > 0))
  )
);

CREATE INDEX IF NOT EXISTS owners_shop_items_section_sort_idx
  ON public.owners_shop_items (section_id, sort_order, id);

ALTER TABLE public.owners_shop_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owners_shop_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS owners_shop_sections_select_active ON public.owners_shop_sections;
CREATE POLICY owners_shop_sections_select_active ON public.owners_shop_sections
  FOR SELECT TO authenticated
  USING (is_active OR public.is_gpsl_admin());

DROP POLICY IF EXISTS owners_shop_items_select_active ON public.owners_shop_items;
CREATE POLICY owners_shop_items_select_active ON public.owners_shop_items
  FOR SELECT TO authenticated
  USING (is_active OR public.is_gpsl_admin());

INSERT INTO public.owners_shop_sections (code, label, kicker, intro, theme_key, sort_order, is_active)
VALUES
  (
    'medical',
    'Medical bay',
    'Treatment centre stock',
    'Specialist consult tokens for the Medical Room. One consult per injury; tier shortens recovery by that many matches.',
    'medical',
    10,
    true
  ),
  (
    'discipline',
    'Discipline desk',
    'Match officials corridor',
    'Appeal cards for suspension reviews. Stock sits on the club until you lodge an appeal from the discipline flow.',
    'discipline',
    20,
    true
  ),
  (
    'coming',
    'More aisles later',
    'Stadium concourse',
    'Fee-discount tokens, draft boosts, and other owner-funded club stock can land here without touching club books as income.',
    'coming',
    90,
    true
  )
ON CONFLICT (code) DO UPDATE SET
  label = EXCLUDED.label,
  kicker = EXCLUDED.kicker,
  intro = EXCLUDED.intro,
  theme_key = EXCLUDED.theme_key,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

INSERT INTO public.owners_shop_items (
  section_id, sku_code, title, description, price, prize_type, param_int,
  quantity_granted, badge_label, sort_order, is_active, is_featured
)
SELECT s.id, v.sku, v.title, v.descr, v.price, v.ptype, v.pint, v.qty, v.badge, v.sort, true, v.feat
FROM public.owners_shop_sections s
JOIN (
  VALUES
    ('medical', 'med_consult_2',  'Consult −2',  'Shorten assessed injury by 2 matches.',  250::numeric, 'medical_token', 2,  1, '−2',  10, false),
    ('medical', 'med_consult_4',  'Consult −4',  'Shorten assessed injury by 4 matches.',  500::numeric, 'medical_token', 4,  1, '−4',  20, false),
    ('medical', 'med_consult_6',  'Consult −6',  'Shorten assessed injury by 6 matches.',  900::numeric, 'medical_token', 6,  1, '−6',  30, false),
    ('medical', 'med_consult_8',  'Consult −8',  'Shorten assessed injury by 8 matches.', 1400::numeric, 'medical_token', 8,  1, '−8',  40, true),
    ('medical', 'med_consult_10', 'Consult −10', 'Maximum specialist recovery cut.',     2000::numeric, 'medical_token', 10, 1, '−10', 50, true),
    ('discipline', 'appeal_card_1', 'Appeal card', 'One suspension appeal attempt for this club.', 1500::numeric, 'appeal_card', NULL::int, 1, '1×', 10, false),
    ('discipline', 'appeal_pack_3', 'Appeal pack', 'Three appeal cards — slight pack discount.', 4000::numeric, 'appeal_card', NULL::int, 3, '3×', 20, false)
) AS v(sec, sku, title, descr, price, ptype, pint, qty, badge, sort, feat)
  ON s.code = v.sec
ON CONFLICT (sku_code) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  prize_type = EXCLUDED.prize_type,
  param_int = EXCLUDED.param_int,
  quantity_granted = EXCLUDED.quantity_granted,
  badge_label = EXCLUDED.badge_label,
  sort_order = EXCLUDED.sort_order,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();

-- ---------------------------------------------------------------------------
-- Catalogue read
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.owners_shop_catalogue(p_include_inactive boolean DEFAULT false)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_admin boolean := coalesce(public.is_gpsl_admin(), false);
  v_inc boolean := coalesce(p_include_inactive, false) AND v_admin;
BEGIN
  RETURN coalesce((
    SELECT jsonb_agg(
      jsonb_build_object(
        'id', s.id,
        'code', s.code,
        'label', s.label,
        'kicker', s.kicker,
        'intro', s.intro,
        'theme_key', s.theme_key,
        'sort_order', s.sort_order,
        'is_active', s.is_active,
        'items', coalesce((
          SELECT jsonb_agg(
            jsonb_build_object(
              'id', i.id,
              'sku_code', i.sku_code,
              'title', i.title,
              'description', i.description,
              'price', i.price,
              'prize_type', i.prize_type,
              'param_int', i.param_int,
              'quantity_granted', i.quantity_granted,
              'badge_label', i.badge_label,
              'sort_order', i.sort_order,
              'is_active', i.is_active,
              'is_featured', i.is_featured
            )
            ORDER BY i.sort_order, i.id
          )
          FROM public.owners_shop_items i
          WHERE i.section_id = s.id
            AND (v_inc OR i.is_active)
        ), '[]'::jsonb)
      )
      ORDER BY s.sort_order, s.id
    )
    FROM public.owners_shop_sections s
    WHERE v_inc OR s.is_active
  ), '[]'::jsonb);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Admin CRUD
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_owners_shop_save_section(
  p_id bigint DEFAULT NULL,
  p_code text DEFAULT NULL,
  p_label text DEFAULT NULL,
  p_kicker text DEFAULT NULL,
  p_intro text DEFAULT NULL,
  p_theme_key text DEFAULT 'default',
  p_sort_order int DEFAULT 100,
  p_is_active boolean DEFAULT true
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint := p_id;
  v_code text := lower(btrim(coalesce(p_code, '')));
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  IF v_code = '' OR nullif(btrim(coalesce(p_label, '')), '') IS NULL THEN
    RAISE EXCEPTION 'code and label required';
  END IF;

  IF v_id IS NULL THEN
    INSERT INTO public.owners_shop_sections (
      code, label, kicker, intro, theme_key, sort_order, is_active
    )
    VALUES (
      v_code,
      btrim(p_label),
      nullif(btrim(coalesce(p_kicker, '')), ''),
      nullif(btrim(coalesce(p_intro, '')), ''),
      coalesce(nullif(btrim(coalesce(p_theme_key, '')), ''), 'default'),
      coalesce(p_sort_order, 100),
      coalesce(p_is_active, true)
    )
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.owners_shop_sections
    SET
      code = v_code,
      label = btrim(p_label),
      kicker = nullif(btrim(coalesce(p_kicker, '')), ''),
      intro = nullif(btrim(coalesce(p_intro, '')), ''),
      theme_key = coalesce(nullif(btrim(coalesce(p_theme_key, '')), ''), 'default'),
      sort_order = coalesce(p_sort_order, 100),
      is_active = coalesce(p_is_active, true),
      updated_at = now()
    WHERE id = v_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Section % not found', v_id;
    END IF;
  END IF;

  RETURN jsonb_build_object('ok', true, 'id', v_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_owners_shop_save_item(
  p_id bigint DEFAULT NULL,
  p_section_id bigint DEFAULT NULL,
  p_sku_code text DEFAULT NULL,
  p_title text DEFAULT NULL,
  p_description text DEFAULT NULL,
  p_price numeric DEFAULT NULL,
  p_prize_type text DEFAULT NULL,
  p_param_int int DEFAULT NULL,
  p_quantity_granted int DEFAULT 1,
  p_badge_label text DEFAULT NULL,
  p_sort_order int DEFAULT 100,
  p_is_active boolean DEFAULT true,
  p_is_featured boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint := p_id;
  v_sku text := lower(btrim(coalesce(p_sku_code, '')));
  v_ptype text := lower(btrim(coalesce(p_prize_type, '')));
  v_price numeric(14, 2);
  v_pint int := p_param_int;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  IF p_section_id IS NULL OR v_sku = '' OR nullif(btrim(coalesce(p_title, '')), '') IS NULL THEN
    RAISE EXCEPTION 'section_id, sku_code and title required';
  END IF;
  IF v_ptype NOT IN ('medical_token', 'fee_discount', 'appeal_card', 'draft_token') THEN
    RAISE EXCEPTION 'Invalid prize_type';
  END IF;

  v_price := round(coalesce(p_price, 0)::numeric, 2);
  IF v_price < 0 THEN
    RAISE EXCEPTION 'Price cannot be negative';
  END IF;

  IF v_ptype = 'appeal_card' THEN
    v_pint := NULL;
  END IF;

  IF v_id IS NULL THEN
    INSERT INTO public.owners_shop_items (
      section_id, sku_code, title, description, price, prize_type, param_int,
      quantity_granted, badge_label, sort_order, is_active, is_featured
    )
    VALUES (
      p_section_id,
      v_sku,
      btrim(p_title),
      nullif(btrim(coalesce(p_description, '')), ''),
      v_price,
      v_ptype,
      v_pint,
      greatest(1, least(20, coalesce(p_quantity_granted, 1))),
      nullif(btrim(coalesce(p_badge_label, '')), ''),
      coalesce(p_sort_order, 100),
      coalesce(p_is_active, true),
      coalesce(p_is_featured, false)
    )
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.owners_shop_items
    SET
      section_id = p_section_id,
      sku_code = v_sku,
      title = btrim(p_title),
      description = nullif(btrim(coalesce(p_description, '')), ''),
      price = v_price,
      prize_type = v_ptype,
      param_int = v_pint,
      quantity_granted = greatest(1, least(20, coalesce(p_quantity_granted, 1))),
      badge_label = nullif(btrim(coalesce(p_badge_label, '')), ''),
      sort_order = coalesce(p_sort_order, 100),
      is_active = coalesce(p_is_active, true),
      is_featured = coalesce(p_is_featured, false),
      updated_at = now()
    WHERE id = v_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Item % not found', v_id;
    END IF;
  END IF;

  RETURN jsonb_build_object('ok', true, 'id', v_id);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Buy + club stock
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.owners_shop_buy(p_item_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_club text;
  v_item public.owners_shop_items%ROWTYPE;
  v_bal numeric(14, 2);
  v_ledger_id bigint;
  v_inv_ids bigint[] := ARRAY[]::bigint[];
  v_inv_id bigint;
  v_i int;
  v_season_id bigint;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not signed in';
  END IF;
  IF p_item_id IS NULL THEN
    RAISE EXCEPTION 'Item required';
  END IF;

  SELECT * INTO v_item
  FROM public.owners_shop_items
  WHERE id = p_item_id AND is_active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Item not available';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.owners_shop_sections s
    WHERE s.id = v_item.section_id AND s.is_active = true
  ) THEN
    RAISE EXCEPTION 'Section not available';
  END IF;

  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked — shop purchases stock on your current club';
  END IF;

  PERFORM public.owner_wallet_ensure(v_uid);

  SELECT balance INTO v_bal
  FROM public.owner_wallets
  WHERE owner_id = v_uid
  FOR UPDATE;

  IF coalesce(v_bal, 0) < v_item.price THEN
    RAISE EXCEPTION 'Insufficient owner balance (need %, have %)',
      v_item.price, coalesce(v_bal, 0);
  END IF;

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true
  ORDER BY id DESC
  LIMIT 1;

  v_ledger_id := public._post_owner_ledger_internal(
    v_uid,
    'shop_purchase',
    -abs(v_item.price),
    format('Owners Shop — %s → %s', v_item.title, v_club),
    jsonb_build_object(
      'source', 'owners_shop_buy',
      'item_id', v_item.id,
      'sku_code', v_item.sku_code,
      'club_short_name', v_club,
      'prize_type', v_item.prize_type,
      'param_int', v_item.param_int,
      'quantity_granted', v_item.quantity_granted
    ),
    v_season_id
  );

  FOR v_i IN 1..v_item.quantity_granted LOOP
    v_inv_id := public.prize_grant_inventory_item(
      v_club,
      v_item.prize_type,
      v_item.param_int,
      'owners_shop',
      v_season_id,
      NULL,
      jsonb_build_object(
        'shop_item_id', v_item.id,
        'sku_code', v_item.sku_code,
        'owner_id', v_uid,
        'ledger_id', v_ledger_id
      )
    );
    v_inv_ids := array_append(v_inv_ids, v_inv_id);
  END LOOP;

  SELECT balance INTO v_bal FROM public.owner_wallets WHERE owner_id = v_uid;

  RETURN jsonb_build_object(
    'ok', true,
    'ledger_id', v_ledger_id,
    'inventory_ids', to_jsonb(v_inv_ids),
    'club_short_name', v_club,
    'balance', coalesce(v_bal, 0),
    'item_title', v_item.title,
    'quantity', v_item.quantity_granted
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.owners_shop_club_stock(p_club text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := nullif(btrim(coalesce(p_club, '')), '');
BEGIN
  IF v_club IS NULL THEN
    v_club := public.my_club_shortname();
  END IF;
  IF v_club IS NULL OR v_club = '' THEN
    RETURN '[]'::jsonb;
  END IF;
  IF NOT public.is_gpsl_admin()
     AND v_club IS DISTINCT FROM public.my_club_shortname() THEN
    RAISE EXCEPTION 'Not allowed';
  END IF;

  RETURN coalesce((
    SELECT jsonb_agg(jsonb_build_object(
      'prize_type', x.prize_type,
      'param_int', x.param_int,
      'qty', x.qty
    ) ORDER BY x.prize_type, x.param_int NULLS LAST)
    FROM (
      SELECT prize_type, param_int, count(*)::int AS qty
      FROM public.club_prize_inventory
      WHERE club_short_name = v_club
        AND status = 'available'
        AND prize_type IN ('medical_token', 'appeal_card', 'fee_discount', 'draft_token')
      GROUP BY prize_type, param_int
    ) x
  ), '[]'::jsonb);
END;
$function$;

REVOKE ALL ON FUNCTION public._post_owner_ledger_internal(uuid, text, numeric, text, jsonb, bigint, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.owner_wallet_ensure(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owner_wallet_get_self() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_owner_wallet_adjust(uuid, numeric, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owners_shop_catalogue(boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_owners_shop_save_section(bigint, text, text, text, text, text, int, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_owners_shop_save_item(bigint, bigint, text, text, text, numeric, text, int, int, text, int, boolean, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owners_shop_buy(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owners_shop_club_stock(text) TO authenticated;

COMMENT ON TABLE public.owner_wallets IS
  'Personal owner balance (Bookies / GPFL / shop). Separate from Club_Finances.';
COMMENT ON TABLE public.owners_shop_items IS
  'Admin-configurable Owners Shop catalogue; buys debit owner_wallets and grant club_prize_inventory.';
