-- =============================================================================
-- Pre-club holidays (waiting list / club auction invitees)
--
--   Owners without a club can note upcoming holidays on Owner details
--   (awaiting_club.html). Optional — NOT part of the auction onboarding gate.
--
--   When the owner is assigned a club (Clubs.owner_id set), future pre-club
--   holidays are copied into club_owner_holidays for the current season
--   (active / preseason) and removed from this table. Rows that clash with
--   an existing club booking are skipped (left here for admin to see).
--
-- Safe re-run.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.gpsl_preclub_holidays (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  day_count smallint NOT NULL CHECK (day_count >= 1 AND day_count <= 14),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT gpsl_preclub_holidays_window CHECK (ends_at > starts_at)
);

CREATE INDEX IF NOT EXISTS gpsl_preclub_holidays_owner_idx
  ON public.gpsl_preclub_holidays (owner_id, starts_at);

ALTER TABLE public.gpsl_preclub_holidays ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.gpsl_preclub_holidays FROM anon, authenticated;

-- ---------------------------------------------------------------------------
-- Owner: list / book / cancel
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.owner_preclub_holiday_list()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'max_days', public.club_holiday_max_days_per_season(),
    'holidays', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', h.id,
        'starts_at', h.starts_at,
        'ends_at', h.ends_at,
        'day_count', h.day_count
      ) ORDER BY h.starts_at)
      FROM public.gpsl_preclub_holidays h
      WHERE h.owner_id = auth.uid()
        AND h.ends_at > now()
    ), '[]'::jsonb)
  );
$$;

CREATE OR REPLACE FUNCTION public.owner_preclub_holiday_book(
  p_start_date date,
  p_end_date date
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_starts timestamptz;
  v_ends timestamptz;
  v_days int;
  v_used int;
  v_max int := public.club_holiday_max_days_per_season();
  v_id bigint;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF public.my_club_shortname() IS NOT NULL THEN
    RAISE EXCEPTION 'You have a club — book holidays on Club details instead';
  END IF;
  IF p_start_date IS NULL OR p_end_date IS NULL THEN
    RAISE EXCEPTION 'Start and end dates are required';
  END IF;
  IF p_end_date < p_start_date THEN
    RAISE EXCEPTION 'End date must be on or after start date';
  END IF;

  v_starts := (p_start_date::timestamp AT TIME ZONE 'Europe/London');
  v_ends := ((p_end_date + 1)::timestamp AT TIME ZONE 'Europe/London');
  v_days := public.club_holiday_inclusive_days(v_starts, v_ends);

  IF v_ends <= now() THEN
    RAISE EXCEPTION 'Holiday must end in the future';
  END IF;
  IF v_days > v_max THEN
    RAISE EXCEPTION 'A single booking cannot exceed % days', v_max;
  END IF;

  SELECT coalesce(sum(day_count), 0)::int INTO v_used
  FROM public.gpsl_preclub_holidays
  WHERE owner_id = auth.uid() AND ends_at > now();

  IF v_used + v_days > v_max THEN
    RAISE EXCEPTION 'Only % days of holiday per season (% booked, % requested)',
      v_max, v_used, v_days;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.gpsl_preclub_holidays h
    WHERE h.owner_id = auth.uid()
      AND h.starts_at < v_ends
      AND h.ends_at > v_starts
  ) THEN
    RAISE EXCEPTION 'Holiday overlaps one you already booked';
  END IF;

  INSERT INTO public.gpsl_preclub_holidays (owner_id, starts_at, ends_at, day_count)
  VALUES (auth.uid(), v_starts, v_ends, v_days::smallint)
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.owner_preclub_holiday_cancel(p_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  DELETE FROM public.gpsl_preclub_holidays
  WHERE id = p_id AND owner_id = auth.uid();
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Holiday not found';
  END IF;
END;
$function$;

REVOKE ALL ON FUNCTION public.owner_preclub_holiday_list() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.owner_preclub_holiday_book(date, date) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.owner_preclub_holiday_cancel(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.owner_preclub_holiday_list() TO authenticated;
GRANT EXECUTE ON FUNCTION public.owner_preclub_holiday_book(date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owner_preclub_holiday_cancel(bigint) TO authenticated;

-- ---------------------------------------------------------------------------
-- On club assignment: move future pre-club holidays onto the club
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.gpsl_preclub_holidays_transfer_trg()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  r record;
BEGIN
  IF NEW.owner_id IS NULL OR NEW.owner_id IS NOT DISTINCT FROM OLD.owner_id THEN
    RETURN NEW;
  END IF;

  SELECT s.id INTO v_season_id
  FROM public.competition_seasons s
  WHERE s.is_current = true
    AND s.status IN ('active', 'preseason')
  ORDER BY s.id DESC
  LIMIT 1;

  IF v_season_id IS NULL THEN
    SELECT s.id INTO v_season_id
    FROM public.competition_seasons s
    WHERE s.status = 'preseason'
    ORDER BY s.id DESC
    LIMIT 1;
  END IF;

  IF v_season_id IS NULL THEN
    RETURN NEW;
  END IF;

  FOR r IN
    SELECT * FROM public.gpsl_preclub_holidays
    WHERE owner_id = NEW.owner_id AND ends_at > now()
    ORDER BY starts_at
  LOOP
    IF EXISTS (
      SELECT 1 FROM public.club_owner_holidays h
      WHERE h.season_id = v_season_id
        AND h.club_short_name = NEW."ShortName"
        AND h.starts_at < r.ends_at
        AND h.ends_at > r.starts_at
    ) THEN
      CONTINUE;
    END IF;

    BEGIN
      INSERT INTO public.club_owner_holidays (
        season_id, club_short_name, owner_id, starts_at, ends_at, day_count
      ) VALUES (
        v_season_id, NEW."ShortName", NEW.owner_id, r.starts_at, r.ends_at, r.day_count
      );
      DELETE FROM public.gpsl_preclub_holidays WHERE id = r.id;
    EXCEPTION WHEN OTHERS THEN
      NULL;
    END;
  END LOOP;

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_preclub_holidays_transfer ON public."Clubs";
CREATE TRIGGER trg_preclub_holidays_transfer
  AFTER UPDATE OF owner_id ON public."Clubs"
  FOR EACH ROW
  EXECUTE FUNCTION public.gpsl_preclub_holidays_transfer_trg();

-- Admin view on Owner holidays page can read these later if needed
CREATE OR REPLACE FUNCTION public.admin_preclub_holiday_list()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE WHEN NOT public.is_gpsl_admin_or_mod() THEN NULL ELSE coalesce((
    SELECT jsonb_agg(jsonb_build_object(
      'id', h.id,
      'owner_id', h.owner_id,
      'owner_tag', public.owner_registry_resolve_tag(h.owner_id),
      'starts_at', h.starts_at,
      'ends_at', h.ends_at,
      'day_count', h.day_count
    ) ORDER BY h.starts_at)
    FROM public.gpsl_preclub_holidays h
    WHERE h.ends_at > now()
  ), '[]'::jsonb) END;
$$;

REVOKE ALL ON FUNCTION public.admin_preclub_holiday_list() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_preclub_holiday_list() TO authenticated;

NOTIFY pgrst, 'reload schema';
