-- =============================================================================
-- Blind Gauntlet special auction
-- Phase 1 (15m) → reveal (5m) → Phase 2 (10m)
-- Fees: Mid £500k / Bottom £1m (P1) · Top advances · P2 entry £3m · winner pays bid
-- Optional prize pack: medical / fee discount / appeal / draft tokens
-- Safe re-run.
-- =============================================================================

-- Widen auction_type
ALTER TABLE public.special_auctions
  DROP CONSTRAINT IF EXISTS special_auctions_auction_type_check;

ALTER TABLE public.special_auctions
  ADD CONSTRAINT special_auctions_auction_type_check
  CHECK (auction_type IN ('lowest_unique', 'snap', 'blind_gauntlet'));

ALTER TABLE public.special_auctions
  ADD COLUMN IF NOT EXISTS gauntlet_phase text
    CHECK (gauntlet_phase IS NULL OR gauntlet_phase IN (
      'phase1', 'reveal', 'phase2', 'complete', 'failed'
    )),
  ADD COLUMN IF NOT EXISTS gauntlet_phase1_end_at timestamptz,
  ADD COLUMN IF NOT EXISTS gauntlet_reveal_end_at timestamptz,
  ADD COLUMN IF NOT EXISTS gauntlet_phase2_end_at timestamptz,
  ADD COLUMN IF NOT EXISTS gauntlet_prize_pack jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS public.special_auction_gauntlet_bids (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_id bigint NOT NULL REFERENCES public.special_auctions (id) ON DELETE CASCADE,
  club_id text NOT NULL,
  owner_id uuid NOT NULL,
  phase smallint NOT NULL CHECK (phase IN (1, 2)),
  bid_amount numeric NOT NULL CHECK (bid_amount > 0),
  bid_time timestamptz NOT NULL DEFAULT now(),
  tier text CHECK (tier IS NULL OR tier IN ('top', 'middle', 'bottom')),
  phase1_fee numeric NOT NULL DEFAULT 0,
  phase2_fee numeric NOT NULL DEFAULT 0,
  is_winner boolean NOT NULL DEFAULT false,
  UNIQUE (auction_id, club_id, phase)
);

CREATE INDEX IF NOT EXISTS special_auction_gauntlet_bids_auction_idx
  ON public.special_auction_gauntlet_bids (auction_id, phase);

ALTER TABLE public.special_auction_gauntlet_bids ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS special_auction_gauntlet_bids_select ON public.special_auction_gauntlet_bids;
CREATE POLICY special_auction_gauntlet_bids_select
  ON public.special_auction_gauntlet_bids FOR SELECT TO authenticated
  USING (
    public.is_gpsl_admin()
    OR club_id = public.my_club_shortname()
    OR EXISTS (
      SELECT 1 FROM public.special_auctions a
      WHERE a.id = auction_id
        AND a.status IN ('settled', 'revealed')
        AND a.gauntlet_phase IN ('complete', 'failed')
    )
  );

DROP POLICY IF EXISTS special_auction_gauntlet_bids_insert ON public.special_auction_gauntlet_bids;
CREATE POLICY special_auction_gauntlet_bids_insert
  ON public.special_auction_gauntlet_bids FOR INSERT TO authenticated
  WITH CHECK (club_id = public.my_club_shortname() AND owner_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Prepare timings from start_time (15 + 5 + 10 = 30 minutes)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.special_auction_gauntlet_prepare(p_auction_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  a public.special_auctions%rowtype;
  v_start timestamptz;
BEGIN
  SELECT * INTO a FROM public.special_auctions WHERE id = p_auction_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Auction not found';
  END IF;
  IF a.auction_type <> 'blind_gauntlet' THEN
    RAISE EXCEPTION 'Not a Blind Gauntlet auction';
  END IF;

  v_start := a.start_time;

  UPDATE public.special_auctions
  SET
    gauntlet_phase = coalesce(gauntlet_phase, 'phase1'),
    gauntlet_phase1_end_at = v_start + interval '15 minutes',
    gauntlet_reveal_end_at = v_start + interval '20 minutes',
    gauntlet_phase2_end_at = v_start + interval '30 minutes',
    end_time = v_start + interval '30 minutes',
    updated_at = now()
  WHERE id = p_auction_id
  RETURNING * INTO a;

  RETURN jsonb_build_object(
    'ok', true,
    'auction_id', a.id,
    'phase1_end', a.gauntlet_phase1_end_at,
    'reveal_end', a.gauntlet_reveal_end_at,
    'phase2_end', a.gauntlet_phase2_end_at
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Tier assignment after Phase 1
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.special_auction_gauntlet_assign_tiers(p_auction_id bigint)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_n int;
  v_top int;
  v_bottom int;
  v_middle int;
  r record;
  v_rank int := 0;
  v_tier text;
  v_fee numeric;
  v_assigned int := 0;
BEGIN
  SELECT count(*)::int INTO v_n
  FROM public.special_auction_gauntlet_bids
  WHERE auction_id = p_auction_id AND phase = 1;

  IF v_n = 0 THEN
    RETURN 0;
  END IF;

  v_top := greatest(1, ceil(v_n * 0.25)::int);
  v_bottom := greatest(0, floor(v_n * 0.25)::int);
  IF v_top + v_bottom > v_n THEN
    v_bottom := greatest(0, v_n - v_top);
  END IF;
  v_middle := v_n - v_top - v_bottom;

  FOR r IN
    SELECT id, club_id
    FROM public.special_auction_gauntlet_bids
    WHERE auction_id = p_auction_id AND phase = 1
    ORDER BY bid_amount DESC, bid_time ASC, id ASC
  LOOP
    v_rank := v_rank + 1;
    IF v_rank <= v_top THEN
      v_tier := 'top';
      v_fee := 0;
    ELSIF v_rank <= v_top + v_middle THEN
      v_tier := 'middle';
      v_fee := 500000;
    ELSE
      v_tier := 'bottom';
      v_fee := 1000000;
    END IF;

    UPDATE public.special_auction_gauntlet_bids
    SET tier = v_tier, phase1_fee = v_fee
    WHERE id = r.id;

    IF v_fee > 0 THEN
      PERFORM public.post_special_auction_ledger_line(
        r.club_id,
        'special_auction_fee',
        -abs(v_fee),
        format('Blind Gauntlet Phase 1 fee (%s tier)', v_tier),
        p_auction_id,
        true,
        jsonb_build_object(
          'ledger_role', format('gauntlet_p1_%s_%s', v_tier, r.club_id),
          'gauntlet_tier', v_tier,
          'phase', 1
        )
      );
    END IF;

    BEGIN
      PERFORM public.owner_inbox_send(
        'special_auction_scheduled',
        format('Blind Gauntlet — you finished %s tier', initcap(v_tier)),
        CASE v_tier
          WHEN 'top' THEN
            E'You finished in the Top tier (top 25%).\nYou advance to Phase 2.\nPhase 1 fee: ₿0.\nYour Phase 2 bid must be ≥ your Phase 1 bid.'
          WHEN 'middle' THEN
            E'You finished in the Middle tier.\nYou are eliminated.\nPhase 1 fee charged: ₿500,000 (non-refundable).'
          ELSE
            E'You finished in the Bottom tier.\nYou are eliminated.\nPhase 1 fee charged: ₿1,000,000 (non-refundable).'
        END,
        r.club_id,
        NULL, NULL, NULL, NULL, NULL,
        'special_auction.html',
        format('gauntlet_tier:%s:%s', p_auction_id, r.club_id),
        NULL, NULL
      );
    EXCEPTION WHEN others THEN
      NULL;
    END;

    v_assigned := v_assigned + 1;
  END LOOP;

  RETURN v_assigned;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Grant optional prize pack to winner
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.special_auction_gauntlet_grant_pack(
  p_club text,
  p_pack jsonb,
  p_auction_id bigint,
  p_season_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_granted jsonb := '[]'::jsonb;
  v_med int;
  v_disc int;
  v_appeals int;
  v_drafts int;
  v_id bigint;
  v_i int;
  v_season bigint := p_season_id;
BEGIN
  IF p_pack IS NULL OR p_pack = '{}'::jsonb THEN
    RETURN jsonb_build_object('granted', v_granted);
  END IF;

  IF v_season IS NULL THEN
    SELECT id INTO v_season
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  IF to_regprocedure('public.prize_grant_inventory_item(text,text,int,text,bigint,text,jsonb)') IS NULL THEN
    RETURN jsonb_build_object('granted', v_granted, 'note', 'prize inventory not installed');
  END IF;

  FOR v_med IN
    SELECT jsonb_array_elements_text(coalesce(p_pack->'medical_tokens', '[]'::jsonb))::int
  LOOP
    IF v_med IN (2, 4, 6, 8, 10) THEN
      v_id := public.prize_grant_inventory_item(
        p_club, 'medical_token', v_med,
        'blind_gauntlet', v_season, NULL,
        jsonb_build_object('auction_id', p_auction_id)
      );
      v_granted := v_granted || jsonb_build_array(jsonb_build_object('type', 'medical_token', 'param', v_med, 'id', v_id));
    END IF;
  END LOOP;

  FOR v_disc IN
    SELECT jsonb_array_elements_text(coalesce(p_pack->'fee_discounts', '[]'::jsonb))::int
  LOOP
    IF v_disc > 0 AND v_disc <= 50 THEN
      v_id := public.prize_grant_inventory_item(
        p_club, 'fee_discount', v_disc,
        'blind_gauntlet', v_season, NULL,
        jsonb_build_object('auction_id', p_auction_id)
      );
      v_granted := v_granted || jsonb_build_array(jsonb_build_object('type', 'fee_discount', 'param', v_disc, 'id', v_id));
    END IF;
  END LOOP;

  v_appeals := coalesce((p_pack->>'appeal_cards')::int, 0);
  FOR v_i IN 1..greatest(v_appeals, 0) LOOP
    v_id := public.prize_grant_inventory_item(
      p_club, 'appeal_card', NULL,
      'blind_gauntlet', v_season, NULL,
      jsonb_build_object('auction_id', p_auction_id)
    );
    v_granted := v_granted || jsonb_build_array(jsonb_build_object('type', 'appeal_card', 'id', v_id));
  END LOOP;

  v_drafts := coalesce((p_pack->>'draft_tokens')::int, 0);
  FOR v_i IN 1..greatest(v_drafts, 0) LOOP
    BEGIN
      v_id := public.prize_grant_inventory_item(
        p_club, 'draft_token', NULL,
        'blind_gauntlet', v_season, NULL,
        jsonb_build_object('auction_id', p_auction_id)
      );
      v_granted := v_granted || jsonb_build_array(jsonb_build_object('type', 'draft_token', 'id', v_id));
    EXCEPTION WHEN others THEN
      NULL;
    END;
  END LOOP;

  RETURN jsonb_build_object('granted', v_granted);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Settle Phase 2
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.special_auction_gauntlet_settle(p_auction_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  a public.special_auctions%rowtype;
  v_win record;
  v_pack jsonb;
  v_body text;
BEGIN
  SELECT * INTO a FROM public.special_auctions WHERE id = p_auction_id FOR UPDATE;
  IF NOT FOUND OR a.auction_type <> 'blind_gauntlet' THEN
    RAISE EXCEPTION 'Blind Gauntlet auction not found';
  END IF;

  IF a.status = 'settled' THEN
    RETURN jsonb_build_object('ok', true, 'already_settled', true);
  END IF;

  SELECT b.* INTO v_win
  FROM public.special_auction_gauntlet_bids b
  WHERE b.auction_id = p_auction_id AND b.phase = 2
  ORDER BY b.bid_amount DESC, b.bid_time ASC, b.id ASC
  LIMIT 1;

  IF NOT FOUND THEN
    UPDATE public.special_auctions
    SET status = 'settled',
        gauntlet_phase = 'failed',
        updated_at = now()
    WHERE id = p_auction_id;

    BEGIN
      PERFORM public.owner_inbox_notify_all_clubs(
        'special_auction_scheduled',
        format('Blind Gauntlet failed — %s', a.title),
        'No Phase 2 bids were submitted. Auction ended with no winner.',
        'special_auction.html',
        format('gauntlet_failed:%s', p_auction_id),
        NULL
      );
    EXCEPTION WHEN others THEN
      NULL;
    END;

    RETURN jsonb_build_object('ok', true, 'failed', true, 'reason', 'no_phase2_bids');
  END IF;

  UPDATE public.special_auction_gauntlet_bids
  SET is_winner = (id = v_win.id)
  WHERE auction_id = p_auction_id AND phase = 2;

  -- Charge winning bid amount (P2 fee already charged on submit)
  PERFORM public.post_special_auction_ledger_line(
    v_win.club_id,
    'special_auction_fee',
    -abs(v_win.bid_amount),
    format('Blind Gauntlet winning bid — %s', a.title),
    p_auction_id,
    true,
    jsonb_build_object(
      'ledger_role', 'gauntlet_win_bid',
      'phase', 2,
      'bid_amount', v_win.bid_amount
    )
  );

  UPDATE public.special_auctions
  SET
    status = 'settled',
    gauntlet_phase = 'complete',
    winning_club_id = v_win.club_id,
    winning_amount = v_win.bid_amount,
    updated_at = now()
  WHERE id = p_auction_id
  RETURNING * INTO a;

  -- Award player/cash prize via existing helper when available
  BEGIN
    PERFORM public.special_auction_award_prize(a, v_win.club_id, v_win.bid_amount);
  EXCEPTION WHEN others THEN
    NULL;
  END;

  v_pack := public.special_auction_gauntlet_grant_pack(
    v_win.club_id,
    coalesce(a.gauntlet_prize_pack, '{}'::jsonb),
    p_auction_id,
    NULL
  );

  SELECT string_agg(
    format('%s: ₿%s%s', b.club_id, to_char(b.bid_amount, 'FM999,999,999,999'),
      CASE WHEN b.is_winner THEN ' ★' ELSE '' END),
    E'\n' ORDER BY b.bid_amount DESC, b.bid_time ASC
  )
  INTO v_body
  FROM public.special_auction_gauntlet_bids b
  WHERE b.auction_id = p_auction_id AND b.phase = 2;

  v_body := format(
    E'%s won Blind Gauntlet with ₿%s.\n\nPhase 2 bids:\n%s\n\nPhase 1 bids:\n%s',
    v_win.club_id,
    to_char(v_win.bid_amount, 'FM999,999,999,999'),
    coalesce(v_body, '—'),
    coalesce((
      SELECT string_agg(
        format('%s: ₿%s (%s)', b.club_id, to_char(b.bid_amount, 'FM999,999,999,999'), coalesce(b.tier, '?')),
        E'\n' ORDER BY b.bid_amount DESC, b.bid_time ASC
      )
      FROM public.special_auction_gauntlet_bids b
      WHERE b.auction_id = p_auction_id AND b.phase = 1
    ), '—')
  );

  BEGIN
    PERFORM public.owner_inbox_notify_all_clubs(
      'special_auction_scheduled',
      format('Blind Gauntlet result — %s', a.title),
      v_body,
      'special_auction.html',
      format('gauntlet_result:%s', p_auction_id),
      NULL
    );
  EXCEPTION WHEN others THEN
    NULL;
  END;

  RETURN jsonb_build_object(
    'ok', true,
    'winning_club_id', v_win.club_id,
    'winning_amount', v_win.bid_amount,
    'pack', v_pack
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Tick: advance phases / settle
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.special_auction_gauntlet_tick(p_auction_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  a public.special_auctions%rowtype;
  v_n int;
  v_results jsonb := '[]'::jsonb;
BEGIN
  FOR a IN
    SELECT *
    FROM public.special_auctions
    WHERE auction_type = 'blind_gauntlet'
      AND status IN ('scheduled', 'active')
      AND (p_auction_id IS NULL OR id = p_auction_id)
    ORDER BY id
    FOR UPDATE
  LOOP
    -- Ensure timings
    IF a.gauntlet_phase1_end_at IS NULL THEN
      PERFORM public.special_auction_gauntlet_prepare(a.id);
      SELECT * INTO a FROM public.special_auctions WHERE id = a.id;
    END IF;

    IF a.status = 'scheduled' AND a.start_time <= now() THEN
      UPDATE public.special_auctions
      SET status = 'active', gauntlet_phase = 'phase1', updated_at = now()
      WHERE id = a.id;
      a.status := 'active';
      a.gauntlet_phase := 'phase1';
    END IF;

    IF a.status <> 'active' THEN
      CONTINUE;
    END IF;

    -- Phase 1 → reveal
    IF coalesce(a.gauntlet_phase, 'phase1') = 'phase1'
       AND now() >= a.gauntlet_phase1_end_at THEN
      SELECT count(*)::int INTO v_n
      FROM public.special_auction_gauntlet_bids
      WHERE auction_id = a.id AND phase = 1;

      IF v_n = 0 THEN
        UPDATE public.special_auctions
        SET status = 'settled', gauntlet_phase = 'failed', updated_at = now()
        WHERE id = a.id;
        v_results := v_results || jsonb_build_array(
          jsonb_build_object('auction_id', a.id, 'event', 'failed_no_bids')
        );
        CONTINUE;
      END IF;

      PERFORM public.special_auction_gauntlet_assign_tiers(a.id);
      UPDATE public.special_auctions
      SET gauntlet_phase = 'reveal', updated_at = now()
      WHERE id = a.id;
      v_results := v_results || jsonb_build_array(
        jsonb_build_object('auction_id', a.id, 'event', 'reveal', 'phase1_bids', v_n)
      );
      a.gauntlet_phase := 'reveal';
    END IF;

    -- Reveal → phase 2
    IF a.gauntlet_phase = 'reveal' AND now() >= a.gauntlet_reveal_end_at THEN
      UPDATE public.special_auctions
      SET gauntlet_phase = 'phase2', updated_at = now()
      WHERE id = a.id;
      v_results := v_results || jsonb_build_array(
        jsonb_build_object('auction_id', a.id, 'event', 'phase2_open')
      );
      a.gauntlet_phase := 'phase2';
    END IF;

    -- Phase 2 → settle
    IF a.gauntlet_phase = 'phase2' AND now() >= a.gauntlet_phase2_end_at THEN
      v_results := v_results || jsonb_build_array(
        public.special_auction_gauntlet_settle(a.id) || jsonb_build_object('event', 'settled')
      );
    END IF;
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'events', v_results);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Submit bid
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.special_auction_submit_gauntlet_bid(
  p_auction_id bigint,
  p_amount numeric
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  a public.special_auctions%rowtype;
  v_club text := public.my_club_shortname();
  v_amount numeric;
  v_phase1 numeric;
  v_bal numeric;
  v_id bigint;
BEGIN
  IF v_club IS NULL THEN
    RAISE EXCEPTION 'No club linked';
  END IF;

  PERFORM public.special_auction_gauntlet_tick(p_auction_id);

  SELECT * INTO a FROM public.special_auctions WHERE id = p_auction_id FOR UPDATE;
  IF NOT FOUND OR a.auction_type <> 'blind_gauntlet' THEN
    RAISE EXCEPTION 'Blind Gauntlet auction not found';
  END IF;

  IF a.status <> 'active' THEN
    RAISE EXCEPTION 'Auction is not open for bidding (status=%)', a.status;
  END IF;

  v_amount := public.round_bid_to_million(p_amount);
  IF v_amount IS NULL OR v_amount <= 0 THEN
    RAISE EXCEPTION 'Invalid bid amount';
  END IF;

  IF a.gauntlet_phase = 'phase1' THEN
    IF now() >= a.gauntlet_phase1_end_at THEN
      RAISE EXCEPTION 'Phase 1 has closed';
    END IF;
    IF EXISTS (
      SELECT 1 FROM public.special_auction_gauntlet_bids
      WHERE auction_id = p_auction_id AND club_id = v_club AND phase = 1
    ) THEN
      RAISE EXCEPTION 'You already submitted a Phase 1 bid';
    END IF;

    INSERT INTO public.special_auction_gauntlet_bids (
      auction_id, club_id, owner_id, phase, bid_amount
    )
    VALUES (p_auction_id, v_club, auth.uid(), 1, v_amount)
    RETURNING id INTO v_id;

    RETURN jsonb_build_object(
      'ok', true,
      'phase', 1,
      'bid_id', v_id,
      'bid_amount', v_amount,
      'note', 'Phase 1 bid locked as your Phase 2 minimum. Amount not charged yet.'
    );
  END IF;

  IF a.gauntlet_phase = 'phase2' THEN
    IF now() >= a.gauntlet_phase2_end_at THEN
      RAISE EXCEPTION 'Phase 2 has closed';
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM public.special_auction_gauntlet_bids
      WHERE auction_id = p_auction_id AND club_id = v_club AND phase = 1 AND tier = 'top'
    ) THEN
      RAISE EXCEPTION 'Only Top tier advances to Phase 2';
    END IF;

    SELECT bid_amount INTO v_phase1
    FROM public.special_auction_gauntlet_bids
    WHERE auction_id = p_auction_id AND club_id = v_club AND phase = 1;

    IF v_phase1 IS NULL THEN
      RAISE EXCEPTION 'No Phase 1 bid found for your club';
    END IF;

    IF v_amount < v_phase1 THEN
      RAISE EXCEPTION 'Phase 2 bid must be ≥ your Phase 1 bid (₿%)',
        to_char(v_phase1, 'FM999,999,999,999');
    END IF;

    IF EXISTS (
      SELECT 1 FROM public.special_auction_gauntlet_bids
      WHERE auction_id = p_auction_id AND club_id = v_club AND phase = 2
    ) THEN
      RAISE EXCEPTION 'You already submitted a Phase 2 bid';
    END IF;

    SELECT coalesce(balance, 0) INTO v_bal
    FROM public."Club_Finances"
    WHERE club_name = v_club
    FOR UPDATE;

    IF coalesce(v_bal, 0) < 3000000 THEN
      RAISE EXCEPTION 'Need ₿3,000,000 available for the Phase 2 entry fee';
    END IF;

    -- Charge £3m immediately
    PERFORM public.post_special_auction_ledger_line(
      v_club,
      'special_auction_fee',
      -3000000,
      format('Blind Gauntlet Phase 2 entry fee — %s', a.title),
      p_auction_id,
      true,
      jsonb_build_object(
        'ledger_role', format('gauntlet_p2_fee_%s', v_club),
        'phase', 2
      )
    );

    INSERT INTO public.special_auction_gauntlet_bids (
      auction_id, club_id, owner_id, phase, bid_amount, tier, phase2_fee
    )
    VALUES (p_auction_id, v_club, auth.uid(), 2, v_amount, 'top', 3000000)
    RETURNING id INTO v_id;

    RETURN jsonb_build_object(
      'ok', true,
      'phase', 2,
      'bid_id', v_id,
      'bid_amount', v_amount,
      'phase2_fee', 3000000,
      'note', 'Phase 2 entry fee ₿3,000,000 charged. Bid amount charged only if you win.'
    );
  END IF;

  RAISE EXCEPTION 'Bidding is closed during the % phase', coalesce(a.gauntlet_phase, 'unknown');
END;
$function$;

-- ---------------------------------------------------------------------------
-- Owner state
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.special_auction_gauntlet_owner_state(p_auction_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  a public.special_auctions%rowtype;
  v_club text := public.my_club_shortname();
  v_p1 public.special_auction_gauntlet_bids%rowtype;
  v_p2 public.special_auction_gauntlet_bids%rowtype;
  v_phase2_bids jsonb := '[]'::jsonb;
  v_phase1_bids jsonb := '[]'::jsonb;
  v_reveal boolean := false;
BEGIN
  PERFORM public.special_auction_gauntlet_tick(p_auction_id);

  SELECT * INTO a FROM public.special_auctions WHERE id = p_auction_id;
  IF NOT FOUND OR a.auction_type <> 'blind_gauntlet' THEN
    RAISE EXCEPTION 'Blind Gauntlet auction not found';
  END IF;

  SELECT * INTO v_p1
  FROM public.special_auction_gauntlet_bids
  WHERE auction_id = p_auction_id AND club_id = v_club AND phase = 1;

  SELECT * INTO v_p2
  FROM public.special_auction_gauntlet_bids
  WHERE auction_id = p_auction_id AND club_id = v_club AND phase = 2;

  v_reveal := a.gauntlet_phase IN ('complete', 'failed') OR a.status = 'settled';

  IF v_reveal THEN
    SELECT coalesce(jsonb_agg(
      jsonb_build_object(
        'club_id', b.club_id,
        'bid_amount', b.bid_amount,
        'bid_time', b.bid_time,
        'is_winner', b.is_winner
      )
      ORDER BY b.bid_amount DESC, b.bid_time ASC
    ), '[]'::jsonb)
    INTO v_phase2_bids
    FROM public.special_auction_gauntlet_bids b
    WHERE b.auction_id = p_auction_id AND b.phase = 2;

    SELECT coalesce(jsonb_agg(
      jsonb_build_object(
        'club_id', b.club_id,
        'bid_amount', b.bid_amount,
        'bid_time', b.bid_time,
        'tier', b.tier,
        'phase1_fee', b.phase1_fee
      )
      ORDER BY b.bid_amount DESC, b.bid_time ASC
    ), '[]'::jsonb)
    INTO v_phase1_bids
    FROM public.special_auction_gauntlet_bids b
    WHERE b.auction_id = p_auction_id AND b.phase = 1;
  END IF;

  RETURN jsonb_build_object(
    'auction_id', a.id,
    'title', a.title,
    'status', a.status,
    'gauntlet_phase', a.gauntlet_phase,
    'start_time', a.start_time,
    'phase1_end_at', a.gauntlet_phase1_end_at,
    'reveal_end_at', a.gauntlet_reveal_end_at,
    'phase2_end_at', a.gauntlet_phase2_end_at,
    'prize_type', a.prize_type,
    'prize_player_id', a.prize_player_id,
    'known_player_id', a.known_player_id,
    'prize_cash_amount', a.prize_cash_amount,
    'prize_discount_label', a.prize_discount_label,
    'player_mode', a.player_mode,
    'gauntlet_prize_pack', a.gauntlet_prize_pack,
    'winning_club_id', a.winning_club_id,
    'winning_amount', a.winning_amount,
    'my_club', v_club,
    'my_phase1', CASE WHEN v_p1.id IS NULL THEN NULL ELSE jsonb_build_object(
      'bid_amount', v_p1.bid_amount,
      'tier', v_p1.tier,
      'phase1_fee', v_p1.phase1_fee,
      'bid_time', v_p1.bid_time
    ) END,
    'my_phase2', CASE WHEN v_p2.id IS NULL THEN NULL ELSE jsonb_build_object(
      'bid_amount', v_p2.bid_amount,
      'phase2_fee', v_p2.phase2_fee,
      'is_winner', v_p2.is_winner,
      'bid_time', v_p2.bid_time
    ) END,
    'can_bid_phase1', a.status = 'active' AND a.gauntlet_phase = 'phase1'
      AND now() < a.gauntlet_phase1_end_at AND v_p1.id IS NULL,
    'can_bid_phase2', a.status = 'active' AND a.gauntlet_phase = 'phase2'
      AND now() < a.gauntlet_phase2_end_at
      AND v_p1.tier = 'top' AND v_p2.id IS NULL,
    'phase2_min', v_p1.bid_amount,
    'revealed', v_reveal,
    'phase1_bids', v_phase1_bids,
    'phase2_bids', v_phase2_bids
  );
END;
$function$;

-- Wire tick into promote (lightweight append via new function called from admin/owner)
CREATE OR REPLACE FUNCTION public.special_auction_promote_scheduled()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_count integer;
BEGIN
  UPDATE public.special_auctions
  SET status = 'active',
      updated_at = now()
  WHERE status = 'scheduled'
    AND start_time <= now()
    AND end_time > now();

  GET DIAGNOSTICS v_count = ROW_COUNT;

  BEGIN
    PERFORM public.special_auction_gauntlet_tick(NULL);
  EXCEPTION WHEN others THEN
    NULL;
  END;

  RETURN coalesce(v_count, 0);
END;
$function$;

GRANT EXECUTE ON FUNCTION public.special_auction_gauntlet_prepare(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.special_auction_gauntlet_tick(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.special_auction_submit_gauntlet_bid(bigint, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.special_auction_gauntlet_owner_state(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.special_auction_gauntlet_settle(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.special_auction_promote_scheduled() TO authenticated;

NOTIFY pgrst, 'reload schema';
