-- =============================================================================
-- Squad minimum (24) — August enforcement, fines, and season loans
-- Run once after squad_composition_rules.sql + competition_fines.sql
--       (+ central_bank_model_a_flows.sql if using bank legs).
-- =============================================================================
-- Rules:
--   * Minimum 24 registered players by start of GPSL August.
--   * No penalties before August.
--   * Per missing player at August enforcement: ₿5m fine + random HG free agent
--     (rating ≤ 72) on season loan + ₿5m loan fee.
--   * Season loans terminable when squad > 24; 50% loan fee refunded (not fines).
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.club_squad_minimum_enforcement (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName") ON DELETE CASCADE,
  squad_count int NOT NULL,
  shortfall int NOT NULL CHECK (shortfall > 0),
  fine_per_player numeric NOT NULL DEFAULT 5000000,
  loan_fee_per_player numeric NOT NULL DEFAULT 5000000,
  total_fine numeric NOT NULL,
  total_loan_fee numeric NOT NULL DEFAULT 0,
  loans_granted int NOT NULL DEFAULT 0,
  enforced_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (season_id, club_short_name)
);

CREATE TABLE IF NOT EXISTS public.club_season_loans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName") ON DELETE CASCADE,
  player_id text NOT NULL,
  loan_fee numeric NOT NULL DEFAULT 5000000,
  fine_amount numeric NOT NULL DEFAULT 5000000,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'terminated')),
  loan_ledger_id bigint,
  fine_ledger_id bigint,
  refund_ledger_id bigint,
  refund_amount numeric,
  terminated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_id, player_id),
  UNIQUE (season_id, club_short_name, player_id)
);

CREATE INDEX IF NOT EXISTS club_season_loans_club_active_idx
  ON public.club_season_loans (club_short_name, season_id)
  WHERE status = 'active';

ALTER TABLE public.club_squad_minimum_enforcement ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.club_season_loans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_squad_minimum_enforcement_select ON public.club_squad_minimum_enforcement;
CREATE POLICY club_squad_minimum_enforcement_select ON public.club_squad_minimum_enforcement
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS club_season_loans_select ON public.club_season_loans;
CREATE POLICY club_season_loans_select ON public.club_season_loans
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS club_squad_minimum_enforcement_admin ON public.club_squad_minimum_enforcement;
CREATE POLICY club_squad_minimum_enforcement_admin ON public.club_squad_minimum_enforcement
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS club_season_loans_admin ON public.club_season_loans;
CREATE POLICY club_season_loans_admin ON public.club_season_loans
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.club_squad_minimum_enforcement TO authenticated;
GRANT SELECT ON public.club_season_loans TO authenticated;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.squad_minimum_size()
RETURNS int
LANGUAGE sql
IMMUTABLE
AS $$ SELECT 24; $$;

CREATE OR REPLACE FUNCTION public.squad_minimum_fine_amount()
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$ SELECT 5000000::numeric; $$;

CREATE OR REPLACE FUNCTION public.squad_minimum_loan_fee_amount()
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$ SELECT 5000000::numeric; $$;

CREATE OR REPLACE FUNCTION public.club_registered_squad_count(p_club_short_name text)
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT count(*)::int
  FROM public."Players" p
  WHERE p."Contracted_Team" = btrim(p_club_short_name);
$$;

CREATE OR REPLACE FUNCTION public.club_squad_minimum_shortfall(p_club_short_name text)
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT greatest(
    public.squad_minimum_size()
      - public.club_registered_squad_count(p_club_short_name),
    0
  );
$$;

CREATE OR REPLACE FUNCTION public.squad_minimum_punishments_active(p_season_id bigint DEFAULT NULL)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint := p_season_id;
  v_month text;
BEGIN
  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  IF v_season_id IS NULL THEN
    RETURN false;
  END IF;

  v_month := public.competition_active_gpsl_month(v_season_id, now());
  IF v_month IS NULL THEN
    RETURN false;
  END IF;

  RETURN public.competition_gpsl_month_sort(v_month)
    >= public.competition_gpsl_month_sort('august');
END;
$function$;

CREATE OR REPLACE FUNCTION public.draw_season_loan_player(
  p_club_short_name text,
  p_season_id bigint,
  p_exclude_player_ids text[] DEFAULT ARRAY[]::text[]
)
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := btrim(p_club_short_name);
  v_club_nation text;
  v_player_id text;
BEGIN
  SELECT c."Nation"
  INTO v_club_nation
  FROM public."Clubs" c
  WHERE c."ShortName" = v_club;

  SELECT p."Konami_ID"::text
  INTO v_player_id
  FROM public."Players" p
  WHERE (p."Contracted_Team" IS NULL OR btrim(p."Contracted_Team") = '')
    AND public.normalize_nation_key(p."Nation") = public.normalize_nation_key(v_club_nation)
    AND public.normalize_nation_key(p."Nation") <> ''
    AND btrim(coalesce(p."Rating"::text, '')) <> ''
    AND btrim(p."Rating"::text)::numeric <= 72
    AND NOT (p."Konami_ID"::text = ANY (coalesce(p_exclude_player_ids, ARRAY[]::text[])))
    AND NOT EXISTS (
      SELECT 1
      FROM public.club_season_loans l
      WHERE l.season_id = p_season_id
        AND l.player_id = p."Konami_ID"::text
        AND l.status = 'active'
    )
  ORDER BY random()
  LIMIT 1;

  RETURN v_player_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.assign_player_season_loan(
  p_player_id text,
  p_club_short_name text,
  p_season_id bigint,
  p_loan_fee numeric DEFAULT NULL,
  p_fine_amount numeric DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := btrim(p_club_short_name);
  v_pid text := btrim(p_player_id);
  v_player public."Players"%rowtype;
  v_loan_fee numeric := coalesce(p_loan_fee, public.squad_minimum_loan_fee_amount());
  v_fine_amount numeric := coalesce(p_fine_amount, public.squad_minimum_fine_amount());
  v_season_label text;
  v_wage numeric;
  v_loan_id bigint;
  v_ledger_id bigint;
  v_balance numeric;
BEGIN
  IF v_pid = '' OR v_club = '' THEN
    RAISE EXCEPTION 'Player and club are required';
  END IF;

  SELECT * INTO v_player
  FROM public."Players"
  WHERE "Konami_ID"::text = v_pid
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Player not found';
  END IF;

  IF v_player."Contracted_Team" IS NOT NULL AND btrim(v_player."Contracted_Team") <> '' THEN
    RAISE EXCEPTION 'Player is not a free agent';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public."Players" p
    JOIN public."Clubs" c ON c."ShortName" = v_club
    WHERE p."Konami_ID"::text = v_pid
      AND public.normalize_nation_key(p."Nation") = public.normalize_nation_key(c."Nation")
      AND public.normalize_nation_key(p."Nation") <> ''
  ) THEN
    RAISE EXCEPTION 'Season loan draw must be home-grown to the club nation';
  END IF;

  IF btrim(coalesce(v_player."Rating"::text, '')) = ''
     OR btrim(v_player."Rating"::text)::numeric > 72 THEN
    RAISE EXCEPTION 'Season loan draw must be rating 72 or lower';
  END IF;

  SELECT balance INTO v_balance
  FROM public."Club_Finances"
  WHERE club_name = v_club
  FOR UPDATE;

  IF v_balance IS NULL THEN
    RAISE EXCEPTION 'Club finances not found for %', v_club;
  END IF;
  IF v_balance < v_loan_fee THEN
    RAISE EXCEPTION 'Insufficient balance for season loan fee (need %, have %)', v_loan_fee, v_balance;
  END IF;

  v_season_label := public.current_gpsl_season_label();
  v_wage := public.calculate_player_wage_for_club(v_pid, v_club);

  UPDATE public."Players"
  SET
    "Contracted_Team" = v_club,
    "Season_Signed" = v_season_label,
    contract_seasons_remaining = 1,
    contract_wage = round(coalesce(v_wage, 0), 0),
    foreign_contract_club = NULL,
    foreign_contract_sold_season_id = NULL,
    foreign_contract_unlock_season_label = NULL,
    foreign_contract_lock_kind = NULL
  WHERE "Konami_ID"::text = v_pid;

  v_ledger_id := public.post_club_ledger(
    v_club,
    'season_loan_fee',
    -abs(v_loan_fee),
    format('Season loan fee — %s', coalesce(v_player."Name", v_pid)),
    jsonb_build_object(
      'player_id', v_pid,
      'season_id', p_season_id,
      'kind', 'season_loan'
    ),
    p_season_id,
    NULL,
    true,
    true
  );

  INSERT INTO public.club_season_loans (
    season_id,
    club_short_name,
    player_id,
    loan_fee,
    fine_amount,
    status,
    loan_ledger_id
  )
  VALUES (
    p_season_id,
    v_club,
    v_pid,
    v_loan_fee,
    v_fine_amount,
    'active',
    v_ledger_id
  )
  RETURNING id INTO v_loan_id;

  RETURN jsonb_build_object(
    'ok', true,
    'loan_id', v_loan_id,
    'player_id', v_pid,
    'player_name', v_player."Name",
    'loan_fee', v_loan_fee
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- August enforcement (per club)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_enforce_squad_minimum(
  p_club_short_name text,
  p_season_id bigint DEFAULT NULL,
  p_force boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := btrim(p_club_short_name);
  v_season_id bigint := p_season_id;
  v_count int;
  v_shortfall int;
  v_i int;
  v_player_id text;
  v_exclude text[] := ARRAY[]::text[];
  v_fine_result jsonb;
  v_loan_result jsonb;
  v_loans int := 0;
  v_fine_total numeric := 0;
  v_loan_total numeric := 0;
  v_loan_errors text[] := ARRAY[]::text[];
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'Club required';
  END IF;

  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No current season';
  END IF;

  IF NOT p_force AND NOT public.squad_minimum_punishments_active(v_season_id) THEN
    RETURN jsonb_build_object(
      'ok', false,
      'reason', 'before_august',
      'club', v_club
    );
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.club_squad_minimum_enforcement e
    WHERE e.season_id = v_season_id
      AND e.club_short_name = v_club
  ) THEN
    RETURN jsonb_build_object(
      'ok', true,
      'already_enforced', true,
      'club', v_club
    );
  END IF;

  v_count := public.club_registered_squad_count(v_club);
  v_shortfall := greatest(public.squad_minimum_size() - v_count, 0);

  IF v_shortfall <= 0 THEN
    RETURN jsonb_build_object(
      'ok', true,
      'club', v_club,
      'squad_count', v_count,
      'shortfall', 0,
      'enforced', false
    );
  END IF;

  FOR v_i IN 1..v_shortfall LOOP
    v_fine_result := public.competition_apply_club_fine_tariff(
      v_club,
      'breach_squad_24_min',
      NULL,
      format('Below minimum squad at August (%s of %s missing)', v_i, v_shortfall),
      NULL,
      v_season_id
    );
    v_fine_total := v_fine_total + public.squad_minimum_fine_amount();

    v_player_id := public.draw_season_loan_player(v_club, v_season_id, v_exclude);

    IF v_player_id IS NULL THEN
      v_loan_errors := array_append(
        v_loan_errors,
        format('No eligible home-grown free agent (≤72) for loan %s/%s', v_i, v_shortfall)
      );
      CONTINUE;
    END IF;

    BEGIN
      v_loan_result := public.assign_player_season_loan(
        v_player_id,
        v_club,
        v_season_id,
        public.squad_minimum_loan_fee_amount(),
        public.squad_minimum_fine_amount()
      );
      v_loans := v_loans + 1;
      v_loan_total := v_loan_total + public.squad_minimum_loan_fee_amount();
      v_exclude := array_append(v_exclude, v_player_id);
    EXCEPTION
      WHEN OTHERS THEN
        v_loan_errors := array_append(
          v_loan_errors,
          format('Loan %s/%s failed for %s: %s', v_i, v_shortfall, v_player_id, SQLERRM)
        );
    END;
  END LOOP;

  INSERT INTO public.club_squad_minimum_enforcement (
    season_id,
    club_short_name,
    squad_count,
    shortfall,
    fine_per_player,
    loan_fee_per_player,
    total_fine,
    total_loan_fee,
    loans_granted,
    metadata
  )
  VALUES (
    v_season_id,
    v_club,
    v_count,
    v_shortfall,
    public.squad_minimum_fine_amount(),
    public.squad_minimum_loan_fee_amount(),
    v_fine_total,
    v_loan_total,
    v_loans,
    jsonb_build_object('loan_errors', to_jsonb(v_loan_errors))
  );

  RETURN jsonb_build_object(
    'ok', true,
    'club', v_club,
    'squad_count', v_count,
    'shortfall', v_shortfall,
    'fines_applied', v_shortfall,
    'total_fine', v_fine_total,
    'loans_granted', v_loans,
    'total_loan_fee', v_loan_total,
    'loan_errors', to_jsonb(v_loan_errors)
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_enforce_squad_minimum_august(
  p_season_id bigint DEFAULT NULL,
  p_force boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint := p_season_id;
  v_club text;
  v_results jsonb := '[]'::jsonb;
  v_row jsonb;
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.is_gpsl_admin() AND NOT p_force THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  END IF;

  IF NOT p_force AND NOT public.squad_minimum_punishments_active(v_season_id) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'before_august');
  END IF;

  FOR v_club IN
    SELECT c."ShortName"
    FROM public."Clubs" c
    WHERE c."ShortName" <> 'FOREIGN'
    ORDER BY c."ShortName"
  LOOP
    v_row := public.club_enforce_squad_minimum(v_club, v_season_id, true);
    v_results := v_results || jsonb_build_array(v_row);
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'season_id', v_season_id, 'clubs', v_results);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Owner: terminate season loan when squad > minimum
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.player_terminate_season_loan(p_player_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_pid text := btrim(p_player_id);
  v_player public."Players"%rowtype;
  v_loan public.club_season_loans%rowtype;
  v_count int;
  v_refund numeric;
  v_ledger_id bigint;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  v_club := public.my_club_shortname();
  IF v_club IS NULL OR btrim(v_club) = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT *
  INTO v_loan
  FROM public.club_season_loans l
  WHERE l.player_id = v_pid
    AND l.club_short_name = v_club
    AND l.status = 'active'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No active season loan for this player at your club';
  END IF;

  v_count := public.club_registered_squad_count(v_club);
  IF v_count <= public.squad_minimum_size() THEN
    RAISE EXCEPTION
      'Cannot terminate season loan — squad must be above % players (currently %)',
      public.squad_minimum_size(),
      v_count;
  END IF;

  SELECT * INTO v_player
  FROM public."Players"
  WHERE "Konami_ID"::text = v_pid
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Player not found';
  END IF;

  IF public.player_contracted_club_key(v_player."Contracted_Team") IS DISTINCT FROM v_club THEN
    RAISE EXCEPTION 'Player is not at your club';
  END IF;

  v_refund := round(v_loan.loan_fee * 0.5, 0);

  UPDATE public."Players"
  SET
    "Contracted_Team" = NULL,
    contract_seasons_remaining = 0,
    contract_wage = 0,
    "Season_Signed" = NULL
  WHERE "Konami_ID"::text = v_pid;

  IF v_refund > 0 THEN
    v_ledger_id := public.post_club_ledger(
      v_club,
      'season_loan_refund',
      abs(v_refund),
      format('Season loan refund (50%%) — %s', coalesce(v_player."Name", v_pid)),
      jsonb_build_object(
        'player_id', v_pid,
        'loan_id', v_loan.id,
        'kind', 'season_loan'
      ),
      v_loan.season_id,
      NULL,
      true,
      true
    );
  END IF;

  UPDATE public.club_season_loans
  SET
    status = 'terminated',
    refund_amount = v_refund,
    refund_ledger_id = v_ledger_id,
    terminated_at = now()
  WHERE id = v_loan.id;

  RETURN jsonb_build_object(
    'ok', true,
    'player_id', v_pid,
    'player_name', v_player."Name",
    'refund', v_refund,
    'loan_id', v_loan.id
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Status RPC for Squad UI
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_squad_minimum_status(p_club_short_name text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := btrim(p_club_short_name);
  v_season_id bigint;
  v_count int;
  v_shortfall int;
  v_enforced record;
  v_active_loans int;
  v_punishments boolean;
BEGIN
  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true
  ORDER BY id DESC
  LIMIT 1;

  v_count := public.club_registered_squad_count(v_club);
  v_shortfall := greatest(public.squad_minimum_size() - v_count, 0);
  v_punishments := public.squad_minimum_punishments_active(v_season_id);

  SELECT *
  INTO v_enforced
  FROM public.club_squad_minimum_enforcement e
  WHERE e.season_id = v_season_id
    AND e.club_short_name = v_club;

  SELECT count(*)::int
  INTO v_active_loans
  FROM public.club_season_loans l
  WHERE l.season_id = v_season_id
    AND l.club_short_name = v_club
    AND l.status = 'active';

  RETURN jsonb_build_object(
    'club_short_name', v_club,
    'season_id', v_season_id,
    'min_squad', public.squad_minimum_size(),
    'max_squad', 28,
    'total', v_count,
    'shortfall', CASE WHEN v_punishments THEN v_shortfall ELSE greatest(v_shortfall, 0) END,
    'shortfall_if_august', v_shortfall,
    'punishments_active', v_punishments,
    'august_enforced', (v_enforced.id IS NOT NULL),
    'enforcement', CASE
      WHEN v_enforced.id IS NULL THEN NULL
      ELSE jsonb_build_object(
        'shortfall', v_enforced.shortfall,
        'total_fine', v_enforced.total_fine,
        'total_loan_fee', v_enforced.total_loan_fee,
        'loans_granted', v_enforced.loans_granted,
        'enforced_at', v_enforced.enforced_at
      )
    END,
    'active_season_loans', v_active_loans,
    'can_terminate_loans', v_count > public.squad_minimum_size()
  );
END;
$function$;

-- Extend composition check (informational minimum)
CREATE OR REPLACE FUNCTION public.check_club_squad_composition(p_club_short_name text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club_nation text;
  v_total int;
  v_hg int;
  v_u21 int;
  v_issues text[] := ARRAY[]::text[];
  v_min_status jsonb;
  v_punishments boolean;
BEGIN
  SELECT c."Nation" INTO v_club_nation
  FROM public."Clubs" c
  WHERE c."ShortName" = p_club_short_name;

  SELECT
    count(*)::int,
    count(*) FILTER (
      WHERE public.normalize_nation_key(p."Nation") = public.normalize_nation_key(v_club_nation)
        AND public.normalize_nation_key(p."Nation") <> ''
    )::int,
    count(*) FILTER (
      WHERE p."Age" IS NOT NULL
        AND btrim(p."Age"::text) <> ''
        AND btrim(p."Age"::text)::numeric <= 21
    )::int
  INTO v_total, v_hg, v_u21
  FROM public."Players" p
  WHERE p."Contracted_Team" = p_club_short_name;

  v_min_status := public.club_squad_minimum_status(p_club_short_name);
  v_punishments := coalesce((v_min_status->>'punishments_active')::boolean, false);

  IF v_total > 28 THEN
    v_issues := array_append(v_issues, format('Squad has %s players (max 28)', v_total));
  END IF;

  IF v_punishments AND v_total < public.squad_minimum_size() THEN
    v_issues := array_append(
      v_issues,
      format(
        'Squad has %s players — minimum %s required from August',
        v_total,
        public.squad_minimum_size()
      )
    );
  ELSIF NOT v_punishments AND v_total < public.squad_minimum_size() THEN
  -- informational only before August; no issue pushed until August
    NULL;
  END IF;

  IF v_hg < 8 THEN
    v_issues := array_append(
      v_issues,
      format('Home-grown %s — minimum 8 required (Nation must match club %s; more allowed)', v_hg, coalesce(v_club_nation, '?'))
    );
  END IF;

  IF v_u21 < 5 THEN
    v_issues := array_append(v_issues, format('Under-21 %s — minimum 5 required (age 21 or younger; more allowed)', v_u21));
  END IF;

  RETURN jsonb_build_object(
    'club_short_name', p_club_short_name,
    'club_nation', v_club_nation,
    'total', coalesce(v_total, 0),
    'home_grown', coalesce(v_hg, 0),
    'under_21', coalesce(v_u21, 0),
    'min_home_grown', 8,
    'min_under_21', 5,
    'min_squad', public.squad_minimum_size(),
    'max_squad', 28,
    'minimum_status', v_min_status,
    'compliant', coalesce(array_length(v_issues, 1), 0) = 0,
    'issues', to_jsonb(v_issues)
  );
END;
$function$;

-- Ledger entry types for season loan fees / refunds
ALTER TABLE public.competition_finance_ledger
  DROP CONSTRAINT IF EXISTS competition_finance_ledger_entry_type_check;

ALTER TABLE public.competition_finance_ledger
  ADD CONSTRAINT competition_finance_ledger_entry_type_check
  CHECK (
    entry_type IN (
      'gate_league_home',
      'gate_cup_share',
      'prize',
      'prize_league',
      'prize_cup',
      'prize_challenge',
      'tv_revenue',
      'gov_hg_subsidy',
      'gov_youth_subsidy',
      'gov_bnb_subsidy',
      'gov_fine_compensation',
      'gov_emergency_tax',
      'gov_income_tax',
      'wage_squad',
      'wage_renewal_34plus',
      'wage_star_tax',
      'adjustment',
      'admin_one_off_injection',
      'admin_purchase_payment',
      'transfer_sale',
      'transfer_purchase',
      'transfer_agent_fee',
      'transfer_foreign_sale',
      'transfer_overflow_release',
      'loan_drawdown',
      'loan_repayment_principal',
      'loan_interest_payment',
      'infra_maintenance',
      'infra_purchase',
      'infra_expansion',
      'infra_expansion_refund',
      'infra_expansion_penalty',
      'contract_release_comp',
      'contract_release_comp_received',
      'contract_termination',
      'contract_signing_offer',
      'staff_manager_salary',
      'eos_debt_interest',
      'eos_ffp_charge',
      'eos_balance_interest',
      'eos_injection',
      'special_auction_fee',
      'special_auction_prize',
      'season_loan_fee',
      'season_loan_refund'
    )
  );

GRANT EXECUTE ON FUNCTION public.club_registered_squad_count(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_squad_minimum_shortfall(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_squad_minimum_status(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.player_terminate_season_loan(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_enforce_squad_minimum_august(bigint, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_enforce_squad_minimum(text, bigint, boolean) TO authenticated;

NOTIFY pgrst, 'reload schema';
