-- =============================================================================
-- Squad minimum August — auto-run on GPSL month rollover (via transfer engine cron)
-- Run once after squad_minimum_august.sql + club_auction_auto_settle.sql
--       (or any deploy that includes transferengine_run_report).
-- =============================================================================
-- Flow: GitHub Actions (every minute) → Edge Function transferengine_run
--       → transferengine_run_report() → competition_calendar_month_tick()
--       → competition_enforce_squad_minimum_august() when August unlocks.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.competition_season_calendar_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  job_key text NOT NULL,
  gpsl_month text,
  result jsonb NOT NULL DEFAULT '{}'::jsonb,
  ran_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_id, job_key)
);

CREATE INDEX IF NOT EXISTS competition_season_calendar_jobs_season_idx
  ON public.competition_season_calendar_jobs (season_id, job_key);

ALTER TABLE public.competition_season_calendar_jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_season_calendar_jobs_select
  ON public.competition_season_calendar_jobs;
CREATE POLICY competition_season_calendar_jobs_select
  ON public.competition_season_calendar_jobs
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS competition_season_calendar_jobs_admin
  ON public.competition_season_calendar_jobs;
CREATE POLICY competition_season_calendar_jobs_admin
  ON public.competition_season_calendar_jobs
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.competition_season_calendar_jobs TO authenticated;

-- ---------------------------------------------------------------------------
-- Month rollover tick (idempotent; safe to call every cron minute)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_calendar_month_tick()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_month text;
  v_month_sort smallint;
  v_august_sort constant smallint := public.competition_gpsl_month_sort('august');
  v_job_id bigint;
  v_enforcement jsonb;
  v_out jsonb;
BEGIN
  SELECT id
  INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true
    AND status = 'active'
  ORDER BY id DESC
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'no_active_season');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.competition_season_calendar_config c
    WHERE c.season_id = v_season_id
  ) THEN
    RETURN jsonb_build_object(
      'ok', false,
      'reason', 'no_calendar',
      'season_id', v_season_id
    );
  END IF;

  v_month := public.competition_active_gpsl_month(v_season_id, now());
  v_month_sort := public.competition_gpsl_month_sort(v_month);

  v_out := jsonb_build_object(
    'ok', true,
    'season_id', v_season_id,
    'gpsl_month', v_month,
    'calendar_phase', CASE
      WHEN v_month IS NULL THEN 'between_months'
      ELSE 'in_month'
    END
  );

  IF v_month IS NULL OR v_month_sort IS NULL OR v_month_sort < v_august_sort THEN
    RETURN v_out || jsonb_build_object(
      'squad_minimum_august', jsonb_build_object('skipped', true, 'reason', 'before_august')
    );
  END IF;

  INSERT INTO public.competition_season_calendar_jobs (
    season_id, job_key, gpsl_month, result
  )
  VALUES (
    v_season_id,
    'squad_minimum_august',
    v_month,
    jsonb_build_object('status', 'running')
  )
  ON CONFLICT (season_id, job_key) DO NOTHING
  RETURNING id INTO v_job_id;

  IF v_job_id IS NULL THEN
    RETURN v_out || jsonb_build_object(
      'squad_minimum_august', jsonb_build_object('skipped', true, 'reason', 'already_ran')
    );
  END IF;

  v_enforcement := public.competition_enforce_squad_minimum_august(v_season_id);

  UPDATE public.competition_season_calendar_jobs
  SET result = v_enforcement,
      gpsl_month = v_month,
      ran_at = now()
  WHERE id = v_job_id;

  RETURN v_out || jsonb_build_object('squad_minimum_august', v_enforcement);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Transfer engine report — include calendar month tick (August squad minimum)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.transferengine_run_report()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_settings record;
  v_stuck int;
  v_draft_before int;
  v_draft_after int;
  v_mgr_draft_before int;
  v_mgr_draft_after int;
  v_club_before int;
  v_club_after int;
  v_blocked boolean;
  v_finish_passed boolean;
  v_calendar jsonb;
BEGIN
  SELECT
    draft_auction_enabled,
    manager_draft_auction_enabled,
    club_auction_enabled,
    draft_random_finish_time
  INTO v_settings
  FROM global_settings
  WHERE id = 1;

  v_finish_passed :=
    v_settings.draft_random_finish_time IS NOT NULL
    AND now() >= v_settings.draft_random_finish_time;

  v_blocked := public.transferengine_standard_listings_block_draft_settlement(
    now(),
    v_settings.draft_random_finish_time
  );

  SELECT count(*)::int
  INTO v_stuck
  FROM "Player_Transfer_Listings" l
  WHERE l.status = 'Active'
    AND l.listing_type IS DISTINCT FROM 'draft'
    AND l.end_time <= now();

  SELECT count(*)::int
  INTO v_draft_before
  FROM "Player_Transfer_Listings" l
  WHERE l.listing_type = 'draft'
    AND l.status = 'Active';

  SELECT count(*)::int
  INTO v_mgr_draft_before
  FROM public."Manager_Transfer_Listings" l
  WHERE l.listing_type = 'draft'
    AND l.status = 'Active';

  SELECT count(*)::int
  INTO v_club_before
  FROM public."Club_Auction_Listings" l
  WHERE l.status = 'Active';

  PERFORM public.transferengine_run();

  SELECT count(*)::int
  INTO v_draft_after
  FROM "Player_Transfer_Listings" l
  WHERE l.listing_type = 'draft'
    AND l.status = 'Active';

  SELECT count(*)::int
  INTO v_mgr_draft_after
  FROM public."Manager_Transfer_Listings" l
  WHERE l.listing_type = 'draft'
    AND l.status = 'Active';

  SELECT count(*)::int
  INTO v_club_after
  FROM public."Club_Auction_Listings" l
  WHERE l.status = 'Active';

  v_calendar := public.competition_calendar_month_tick();

  RETURN jsonb_build_object(
    'ok', true,
    'note', 'transferengine_run() returns void — blank in SQL Editor is normal',
    'ran_at', now(),
    'draft_auction_enabled', COALESCE(v_settings.draft_auction_enabled, false),
    'manager_draft_auction_enabled', COALESCE(v_settings.manager_draft_auction_enabled, false),
    'club_auction_enabled', COALESCE(v_settings.club_auction_enabled, false),
    'draft_random_finish_time', v_settings.draft_random_finish_time,
    'secret_finish_passed', v_finish_passed,
    'blocked_by_7pm_transfer_list', v_blocked,
    'stuck_standard_before', v_stuck,
    'active_draft_before', v_draft_before,
    'active_draft_after', v_draft_after,
    'draft_settled_count', v_draft_before - v_draft_after,
    'active_manager_draft_before', v_mgr_draft_before,
    'active_manager_draft_after', v_mgr_draft_after,
    'manager_draft_settled_count', v_mgr_draft_before - v_mgr_draft_after,
    'active_club_auction_before', v_club_before,
    'active_club_auction_after', v_club_after,
    'club_auction_settled_count', v_club_before - v_club_after,
    'calendar_month_tick', v_calendar,
    'draft_by_status', (
      SELECT coalesce(jsonb_object_agg(status, cnt), '{}'::jsonb)
      FROM (
        SELECT l.status, count(*)::int AS cnt
        FROM "Player_Transfer_Listings" l
        WHERE l.listing_type = 'draft'
        GROUP BY l.status
      ) s
    ),
    'manager_draft_by_status', (
      SELECT coalesce(jsonb_object_agg(status, cnt), '{}'::jsonb)
      FROM (
        SELECT l.status, count(*)::int AS cnt
        FROM public."Manager_Transfer_Listings" l
        WHERE l.listing_type = 'draft'
        GROUP BY l.status
      ) s
    ),
    'club_auction_still_active', (
      SELECT coalesce(jsonb_agg(jsonb_build_object(
        'listing_id', l.id,
        'club_short_name', l.club_short_name,
        'high_bid', l.current_highest_bid,
        'leader_tag', r.owner_tag
      ) ORDER BY l.prestige_rank NULLS LAST, l.club_short_name), '[]'::jsonb)
      FROM public."Club_Auction_Listings" l
      LEFT JOIN public.gpsl_owner_registry r ON r.owner_id = l.current_highest_bidder
      WHERE l.status = 'Active'
    )
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.competition_calendar_month_tick() TO service_role;
GRANT EXECUTE ON FUNCTION public.transferengine_run() TO service_role;
GRANT EXECUTE ON FUNCTION public.transferengine_run_report() TO service_role;

NOTIFY pgrst, 'reload schema';
