-- =============================================================================
-- GPSL Central Bank — club loans (drawdown + repayment)
-- Run once after central_bank_phase1.sql (requires post_club_ledger, my_club_shortname)
-- =============================================================================

ALTER TABLE public.gpsl_bank_account
  ADD COLUMN IF NOT EXISTS loans_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS loan_min_drawdown numeric(14, 2) NOT NULL DEFAULT 1000000,
  ADD COLUMN IF NOT EXISTS loan_max_drawdown numeric(14, 2) NOT NULL DEFAULT 50000000,
  ADD COLUMN IF NOT EXISTS loan_max_outstanding_per_club numeric(14, 2) NOT NULL DEFAULT 100000000;

CREATE TABLE IF NOT EXISTS public.club_loans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id),
  principal_drawn numeric(14, 2) NOT NULL CHECK (principal_drawn > 0),
  outstanding_principal numeric(14, 2) NOT NULL CHECK (outstanding_principal >= 0),
  interest_rate_pct numeric(5, 2) NOT NULL,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'paid', 'written_off')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz,
  CONSTRAINT club_loans_outstanding_lte_drawn
    CHECK (outstanding_principal <= principal_drawn)
);

CREATE INDEX IF NOT EXISTS club_loans_club_active_idx
  ON public.club_loans (club_short_name)
  WHERE status = 'active';

CREATE OR REPLACE FUNCTION public.club_loan_outstanding_for(p_club text)
RETURNS numeric
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(sum(outstanding_principal), 0)::numeric
  FROM public.club_loans
  WHERE club_short_name = p_club AND status = 'active';
$$;

CREATE OR REPLACE FUNCTION public.club_take_loan(p_amount numeric)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_amount numeric;
  v_season_id bigint;
  v_bank record;
  v_outstanding numeric;
  v_loan_id bigint;
  v_ledger_id bigint;
  v_desc text;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to your account';
  END IF;

  v_amount := round(coalesce(p_amount, 0)::numeric, 2);
  IF v_amount <= 0 THEN
    RAISE EXCEPTION 'Loan amount must be positive';
  END IF;

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true AND status = 'active'
  ORDER BY id DESC
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No active competition season';
  END IF;

  SELECT
    loans_enabled,
    loan_min_drawdown,
    loan_max_drawdown,
    loan_max_outstanding_per_club,
    policy_interest_rate_pct
  INTO v_bank
  FROM public.gpsl_bank_account
  WHERE id = 1
  FOR UPDATE;

  IF NOT coalesce(v_bank.loans_enabled, false) THEN
    RAISE EXCEPTION 'Bank loans are currently disabled';
  END IF;

  IF v_amount < v_bank.loan_min_drawdown THEN
    RAISE EXCEPTION 'Minimum loan is %', v_bank.loan_min_drawdown;
  END IF;

  IF v_amount > v_bank.loan_max_drawdown THEN
    RAISE EXCEPTION 'Maximum per drawdown is %', v_bank.loan_max_drawdown;
  END IF;

  v_outstanding := public.club_loan_outstanding_for(v_club);

  IF v_outstanding + v_amount > v_bank.loan_max_outstanding_per_club THEN
    RAISE EXCEPTION 'Would exceed max outstanding loan (%) for your club',
      v_bank.loan_max_outstanding_per_club;
  END IF;

  INSERT INTO public.club_loans (
    club_short_name,
    season_id,
    principal_drawn,
    outstanding_principal,
    interest_rate_pct,
    status
  )
  VALUES (
    v_club,
    v_season_id,
    v_amount,
    v_amount,
    v_bank.policy_interest_rate_pct,
    'active'
  )
  RETURNING id INTO v_loan_id;

  v_desc := format('Central bank loan drawdown (loan #%s)', v_loan_id);

  v_ledger_id := public.post_club_ledger(
    v_club,
    'loan_drawdown',
    v_amount,
    v_desc,
    jsonb_build_object('loan_id', v_loan_id),
    v_season_id,
    NULL,
    true,
    true
  );

  UPDATE public.gpsl_bank_account
  SET loan_book_outstanding = loan_book_outstanding + v_amount,
      updated_at = now()
  WHERE id = 1;

  RETURN v_loan_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_repay_loan(p_amount numeric, p_loan_id bigint DEFAULT NULL)
RETURNS numeric
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_amount numeric;
  v_pay numeric;
  v_balance numeric;
  v_loan record;
  v_desc text;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to your account';
  END IF;

  v_amount := round(coalesce(p_amount, 0)::numeric, 2);
  IF v_amount <= 0 THEN
    RAISE EXCEPTION 'Repayment amount must be positive';
  END IF;

  IF p_loan_id IS NOT NULL THEN
    SELECT *
    INTO v_loan
    FROM public.club_loans
    WHERE id = p_loan_id
      AND club_short_name = v_club
      AND status = 'active'
    FOR UPDATE;
  ELSE
    SELECT *
    INTO v_loan
    FROM public.club_loans
    WHERE club_short_name = v_club
      AND status = 'active'
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE;
  END IF;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No active loan to repay';
  END IF;

  v_pay := least(v_amount, v_loan.outstanding_principal);

  SELECT balance INTO v_balance
  FROM public."Club_Finances"
  WHERE club_name = v_club;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Club_Finances row missing';
  END IF;

  IF v_balance < v_pay THEN
    RAISE EXCEPTION 'Insufficient balance to repay % (balance %)', v_pay, v_balance;
  END IF;

  v_desc := format('Loan principal repayment (loan #%s)', v_loan.id);

  PERFORM public.post_club_ledger(
    v_club,
    'loan_repayment_principal',
    -v_pay,
    v_desc,
    jsonb_build_object('loan_id', v_loan.id),
    v_loan.season_id,
    NULL,
    true,
    true
  );

  UPDATE public.club_loans
  SET outstanding_principal = outstanding_principal - v_pay,
      updated_at = now(),
      status = CASE
        WHEN outstanding_principal - v_pay <= 0 THEN 'paid'
        ELSE 'active'
      END,
      closed_at = CASE
        WHEN outstanding_principal - v_pay <= 0 THEN now()
        ELSE closed_at
      END
  WHERE id = v_loan.id;

  UPDATE public.gpsl_bank_account
  SET loan_book_outstanding = greatest(0, loan_book_outstanding - v_pay),
      reserves = reserves + v_pay,
      updated_at = now()
  WHERE id = 1;

  RETURN v_pay;
END;
$function$;

-- Owner read: active/paid loans for own club
DROP VIEW IF EXISTS public.club_loans_public;

CREATE VIEW public.club_loans_public
WITH (security_invoker = true)
AS
SELECT
  l.id,
  l.club_short_name,
  l.season_id,
  l.principal_drawn,
  l.outstanding_principal,
  l.interest_rate_pct,
  l.status,
  l.created_at,
  l.updated_at,
  l.closed_at
FROM public.club_loans l
WHERE l.club_short_name = public.my_club_shortname();

GRANT SELECT ON public.club_loans_public TO authenticated;

DROP VIEW IF EXISTS public.gpsl_bank_public;

CREATE VIEW public.gpsl_bank_public
WITH (security_invoker = false)
AS
SELECT
  display_name,
  reserves,
  loan_book_outstanding,
  policy_interest_rate_pct,
  loans_enabled,
  loan_min_drawdown,
  loan_max_drawdown,
  loan_max_outstanding_per_club,
  updated_at
FROM public.gpsl_bank_account
WHERE id = 1;

GRANT SELECT ON public.gpsl_bank_public TO authenticated;
GRANT SELECT ON public.gpsl_bank_public TO anon;

ALTER TABLE public.club_loans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_loans_select_own ON public.club_loans;
CREATE POLICY club_loans_select_own ON public.club_loans
  FOR SELECT TO authenticated
  USING (club_short_name = public.my_club_shortname());

DROP POLICY IF EXISTS club_loans_admin ON public.club_loans;
CREATE POLICY club_loans_admin ON public.club_loans
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.club_loans TO authenticated;

GRANT EXECUTE ON FUNCTION public.club_take_loan(numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_repay_loan(numeric, bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';
