-- =============================================================================
-- GPSL Central Bank — Phase 1 (Model A: bank for league flows; club↔club transfers ledgered)
-- Run once in Supabase SQL Editor after competition_phase5_finances.sql
-- =============================================================================

-- Singleton bank (treasury / loan book metadata for UI; transfers stay club↔club)
CREATE TABLE IF NOT EXISTS public.gpsl_bank_account (
  id int PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  display_name text NOT NULL DEFAULT 'GPSL Central Bank',
  reserves numeric(14, 2) NOT NULL DEFAULT 0,
  loan_book_outstanding numeric(14, 2) NOT NULL DEFAULT 0,
  policy_interest_rate_pct numeric(5, 2) NOT NULL DEFAULT 5.00,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.gpsl_bank_account (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.bank_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_type text NOT NULL,
  amount numeric(14, 2) NOT NULL CHECK (amount <> 0),
  description text NOT NULL,
  club_short_name text REFERENCES public."Clubs" ("ShortName"),
  club_ledger_id bigint,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bank_ledger_created_idx
  ON public.bank_ledger (created_at DESC);

-- Widen ledger entry types (gates + transfers + admin; loans in phase 2)
ALTER TABLE public.competition_finance_ledger
  DROP CONSTRAINT IF EXISTS competition_finance_ledger_entry_type_check;

ALTER TABLE public.competition_finance_ledger
  ADD CONSTRAINT competition_finance_ledger_entry_type_check
  CHECK (
    entry_type IN (
      'gate_league_home',
      'gate_cup_share',
      'prize',
      'adjustment',
      'admin_one_off_injection',
      'admin_purchase_payment',
      'transfer_sale',
      'transfer_purchase',
      'transfer_agent_fee',
      'transfer_foreign_sale',
      'transfer_overflow_release',
      'loan_drawdown',
      'loan_repayment_principal',
      'loan_interest_payment'
    )
  );

-- ---------------------------------------------------------------------------
-- Core poster: balance + club ledger (+ optional bank leg for subsidies/tax later)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.post_club_ledger(
  p_club_short_name text,
  p_entry_type text,
  p_amount numeric,
  p_description text,
  p_metadata jsonb DEFAULT '{}'::jsonb,
  p_season_id bigint DEFAULT NULL,
  p_fixture_id bigint DEFAULT NULL,
  p_bank_leg boolean DEFAULT false,
  p_apply_balance boolean DEFAULT true
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := btrim(p_club_short_name);
  v_season_id bigint;
  v_balance numeric;
  v_ledger_id bigint;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'Club required';
  END IF;

  IF p_amount IS NULL OR p_amount = 0 THEN
    RETURN NULL;
  END IF;

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true AND status = 'active'
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No active competition season for ledger post';
  END IF;

  IF p_apply_balance THEN
    SELECT balance INTO v_balance
    FROM public."Club_Finances"
    WHERE club_name = v_club
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Club_Finances row missing for %', v_club;
    END IF;

    UPDATE public."Club_Finances"
    SET balance = v_balance + p_amount
    WHERE club_name = v_club;
  END IF;

  INSERT INTO public.competition_finance_ledger (
    season_id,
    fixture_id,
    club_short_name,
    entry_type,
    amount,
    description,
    metadata
  )
  VALUES (
    v_season_id,
    p_fixture_id,
    v_club,
    p_entry_type,
    p_amount,
    coalesce(nullif(btrim(p_description), ''), p_entry_type),
    coalesce(p_metadata, '{}'::jsonb)
  )
  RETURNING id INTO v_ledger_id;

  IF p_bank_leg THEN
    UPDATE public.gpsl_bank_account
    SET reserves = reserves - p_amount,
        updated_at = now()
    WHERE id = 1;

    INSERT INTO public.bank_ledger (
      entry_type,
      amount,
      description,
      club_short_name,
      club_ledger_id,
      metadata
    )
    VALUES (
      p_entry_type,
      -p_amount,
      coalesce(nullif(btrim(p_description), ''), p_entry_type),
      v_club,
      v_ledger_id,
      coalesce(p_metadata, '{}'::jsonb)
    );
  END IF;

  RETURN v_ledger_id;
END;
$function$;

-- Idempotent ledger lines for a completed transfer (Model A — no bank leg)
CREATE OR REPLACE FUNCTION public.post_transfer_ledger_for_history(
  p_transfer_history_id bigint,
  p_apply_balance boolean DEFAULT true
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_h record;
  v_player_name text;
  v_desc_buy text;
  v_desc_sell text;
  v_meta jsonb;
BEGIN
  SELECT *
  INTO v_h
  FROM public."Transfer_History" h
  WHERE h.id = p_transfer_history_id;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  v_meta := jsonb_build_object(
    'transfer_history_id', v_h.id,
    'listing_id', v_h.listing_id,
    'player_id', v_h.player_id
  );

  IF EXISTS (
    SELECT 1
    FROM public.competition_finance_ledger l
    WHERE l.metadata->>'transfer_history_id' = v_h.id::text
      AND l.entry_type IN ('transfer_sale', 'transfer_purchase')
    LIMIT 1
  ) THEN
    RETURN;
  END IF;

  SELECT p."Name" INTO v_player_name
  FROM public."Players" p
  WHERE p."Konami_ID"::text = v_h.player_id::text
  LIMIT 1;

  v_player_name := coalesce(v_player_name, 'Player ' || v_h.player_id::text);

  IF v_h.buyer_club_id IS NOT NULL
     AND btrim(v_h.buyer_club_id::text) <> ''
     AND v_h.buyer_club_id <> 'FOREIGN' THEN
    v_desc_buy := 'Purchase: ' || v_player_name;
    PERFORM public.post_club_ledger(
      v_h.buyer_club_id,
      'transfer_purchase',
      -abs(v_h.fee),
      v_desc_buy,
      v_meta,
      NULL,
      NULL,
      false,
      p_apply_balance
    );
  END IF;

  IF v_h.seller_club_id IS NOT NULL AND btrim(v_h.seller_club_id::text) <> '' THEN
    v_desc_sell := 'Sale: ' || v_player_name;
    IF coalesce(v_h.transfer_sale_note, '') = 'squad_overflow' THEN
      PERFORM public.post_club_ledger(
        v_h.seller_club_id,
        CASE
          WHEN v_h.buyer_club_id = 'FOREIGN' THEN 'transfer_foreign_sale'
          ELSE 'transfer_overflow_release'
        END,
        abs(v_h.fee),
        coalesce(nullif(btrim(v_h.foreign_buyer_name), ''), v_desc_sell),
        v_meta || jsonb_build_object('transfer_sale_note', v_h.transfer_sale_note),
        NULL,
        NULL,
        false,
        p_apply_balance
      );
    ELSE
      PERFORM public.post_club_ledger(
        v_h.seller_club_id,
        'transfer_sale',
        abs(v_h.fee),
        v_desc_sell,
        v_meta,
        NULL,
        NULL,
        false,
        p_apply_balance
      );
    END IF;
  ELSIF v_h.buyer_club_id IS NOT NULL
        AND btrim(v_h.buyer_club_id::text) <> ''
        AND v_h.seller_club_id IS NULL
        AND v_h.buyer_club_id <> 'FOREIGN' THEN
    -- Draft signing (free agent): only buyer debit already posted above
    NULL;
  END IF;

  IF coalesce(v_h.agent_fee, 0) > 0 AND v_h.buyer_club_id IS NOT NULL THEN
    PERFORM public.post_club_ledger(
      v_h.buyer_club_id,
      'transfer_agent_fee',
      -abs(v_h.agent_fee),
      'Agent fee: ' || v_player_name,
      v_meta,
      NULL,
      NULL,
      false,
      p_apply_balance
    );
  END IF;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Patch transfer settlement: ledger + keep Transfer_History (avoid double balance)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.transferengine_accept_sale(p_listing_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_listing          "Player_Transfer_Listings"%rowtype;
  v_player           "Players"%rowtype;
  v_history_id       bigint;
  v_fee              numeric;
  v_buyer            text;
  v_seller           text;
BEGIN
  SELECT *
  INTO v_listing
  FROM "Player_Transfer_Listings"
  WHERE id = p_listing_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE NOTICE 'Listing % not found', p_listing_id;
    RETURN;
  END IF;

  IF v_listing.status NOT IN ('Active', 'Review') THEN
    RAISE NOTICE 'Listing % already processed', p_listing_id;
    RETURN;
  END IF;

  v_fee := v_listing.current_highest_bid;
  v_buyer := v_listing.current_highest_bidder;
  v_seller := v_listing.seller_club_id;

  IF v_buyer IS NULL OR v_fee IS NULL THEN
    RAISE NOTICE 'No winning bid for listing %', p_listing_id;
    RETURN;
  END IF;

  SELECT *
  INTO v_player
  FROM "Players"
  WHERE "Konami_ID"::text = v_listing.player_id::text
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE NOTICE 'Player not found for listing %', p_listing_id;
    RETURN;
  END IF;

  IF v_player."Contracted_Team" IS DISTINCT FROM v_seller THEN
    RAISE NOTICE 'Player no longer at selling club for listing %', p_listing_id;
    RETURN;
  END IF;

  IF public.player_signed_this_season(v_player."Season_Signed")
     AND NOT (
       coalesce(v_listing.new_owner_slot, false)
       OR coalesce(v_listing.perpetual_renew, false)
       OR coalesce(v_listing.special_rules ->> 'new_owner_list', '') = 'true'
     ) THEN
    RAISE NOTICE 'Player signed this season — sale blocked for listing %', p_listing_id;
    RETURN;
  END IF;

  PERFORM public.player_assign_to_club(v_listing.player_id::text, v_buyer);

  INSERT INTO "Transfer_History" (
    player_id,
    seller_club_id,
    buyer_club_id,
    fee,
    agent_fee,
    transfer_time,
    listing_id
  )
  VALUES (
    v_listing.player_id,
    v_seller,
    v_buyer,
    v_fee,
    0,
    now(),
    v_listing.id
  )
  RETURNING id INTO v_history_id;

  PERFORM public.post_transfer_ledger_for_history(v_history_id);

  UPDATE "Player_Transfer_Listings"
  SET status = 'Closed',
      transfer_completed = true,
      winning_bid = v_fee,
      winning_club = v_buyer
  WHERE id = v_listing.id;
END;
$function$;

-- Draft sale: ledger via post_transfer_ledger (balance via post_club_ledger inside)
CREATE OR REPLACE FUNCTION public.transferengine_accept_draft_sale(p_listing_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_listing        "Player_Transfer_Listings"%rowtype;
  v_amount         numeric;
  v_buyer          text;
  v_player         "Players"%rowtype;
  v_history_id     bigint;
BEGIN
  SELECT *
  INTO v_listing
  FROM "Player_Transfer_Listings"
  WHERE id = p_listing_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE NOTICE 'Draft listing % not found', p_listing_id;
    RETURN;
  END IF;

  IF v_listing.listing_type IS DISTINCT FROM 'draft' THEN
    RAISE NOTICE 'Listing % is not draft', p_listing_id;
    RETURN;
  END IF;

  IF v_listing.status NOT IN ('Active', 'Review') THEN
    RAISE NOTICE 'Draft listing % already processed', p_listing_id;
    RETURN;
  END IF;

  SELECT b.bid_amount, b.bidder_club_id
  INTO v_amount, v_buyer
  FROM "Player_Transfer_Bids" b
  WHERE b.is_direct = true
    AND (
      b.listing_id = v_listing.id
      OR btrim(coalesce(b.player_id, b.direct_bid_id::text, '')) = btrim(v_listing.player_id)
    )
  ORDER BY b.bid_amount DESC, b.bid_time ASC
  LIMIT 1;

  IF v_buyer IS NULL OR v_amount IS NULL THEN
    UPDATE "Player_Transfer_Listings"
    SET status = 'Closed',
        transfer_completed = false
    WHERE id = v_listing.id;
    RETURN;
  END IF;

  UPDATE "Player_Transfer_Listings"
  SET current_highest_bid = v_amount,
      current_highest_bidder = v_buyer
  WHERE id = v_listing.id;

  SELECT *
  INTO v_player
  FROM "Players"
  WHERE "Konami_ID"::text = v_listing.player_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE NOTICE 'Player not found for draft listing %', p_listing_id;
    RETURN;
  END IF;

  IF v_player."Contracted_Team" IS NOT NULL
     AND btrim(v_player."Contracted_Team") <> '' THEN
    RAISE NOTICE 'Player already contracted for draft listing %', p_listing_id;
    RETURN;
  END IF;

  PERFORM public.player_assign_to_club(v_listing.player_id, v_buyer);

  INSERT INTO "Transfer_History" (
    player_id,
    seller_club_id,
    buyer_club_id,
    fee,
    agent_fee,
    transfer_time,
    listing_id
  )
  VALUES (
    v_listing.player_id,
    NULL,
    v_buyer,
    v_amount,
    0,
    now(),
    v_listing.id
  )
  RETURNING id INTO v_history_id;

  PERFORM public.post_transfer_ledger_for_history(v_history_id);

  UPDATE "Player_Transfer_Listings"
  SET status = 'Closed',
      transfer_completed = true,
      winning_bid = v_amount,
      winning_club = v_buyer
  WHERE id = v_listing.id;
END;
$function$;

-- Backfill ledger for current-season Transfer_History (run once; does not change balances)
CREATE OR REPLACE FUNCTION public.backfill_transfer_finance_ledger()
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_start timestamptz;
  v_h record;
  v_count int := 0;
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT started_at INTO v_season_start
  FROM public.competition_seasons
  WHERE is_current = true AND status = 'active'
  LIMIT 1;

  FOR v_h IN
    SELECT h.id
    FROM public."Transfer_History" h
    WHERE v_season_start IS NULL OR h.transfer_time >= v_season_start
    ORDER BY h.transfer_time
  LOOP
    PERFORM public.post_transfer_ledger_for_history(v_h.id, false);
    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.backfill_transfer_finance_ledger() TO authenticated;

-- Public read: bank + unified activity view
CREATE OR REPLACE VIEW public.gpsl_bank_public
WITH (security_invoker = false)
AS
SELECT
  display_name,
  reserves,
  loan_book_outstanding,
  policy_interest_rate_pct,
  updated_at
FROM public.gpsl_bank_account
WHERE id = 1;

GRANT SELECT ON public.gpsl_bank_public TO authenticated;
GRANT SELECT ON public.gpsl_bank_public TO anon;

NOTIFY pgrst, 'reload schema';
