-- =============================================================================
-- Owner holiday booking — up to 14 real-world days per season (split as desired).
-- Overlapping GPSL month windows unlock early result entry for that owner's club.
-- Run once in Supabase SQL Editor (after competition_real_world_calendar.sql).
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.club_owner_holidays (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  day_count smallint NOT NULL CHECK (day_count >= 1 AND day_count <= 14),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT club_owner_holidays_window CHECK (ends_at > starts_at)
);

CREATE INDEX IF NOT EXISTS club_owner_holidays_season_club_idx
  ON public.club_owner_holidays (season_id, club_short_name);

CREATE INDEX IF NOT EXISTS club_owner_holidays_window_idx
  ON public.club_owner_holidays (club_short_name, starts_at, ends_at);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_holiday_max_days_per_season()
RETURNS integer
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT 14;
$$;

/** Inclusive calendar days in UK (start date through end date). */
CREATE OR REPLACE FUNCTION public.club_holiday_inclusive_days(
  p_starts_at timestamptz,
  p_ends_at timestamptz
)
RETURNS integer
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT GREATEST(
    1,
    (
      ((p_ends_at - interval '1 microsecond') AT TIME ZONE 'Europe/London')::date
      - (p_starts_at AT TIME ZONE 'Europe/London')::date
      + 1
    )::integer
  );
$$;

CREATE OR REPLACE FUNCTION public.club_holiday_days_used(
  p_season_id bigint,
  p_club_short_name text
)
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(sum(h.day_count), 0)::integer
  FROM public.club_owner_holidays h
  WHERE h.season_id = p_season_id
    AND h.club_short_name = p_club_short_name;
$$;

/** True when fixture month window overlaps a holiday and early play is allowed. */
CREATE OR REPLACE FUNCTION public.club_holiday_allows_fixture_early(
  p_fixture_id bigint,
  p_club_short_name text
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_unlock timestamptz;
  v_lock timestamptz;
BEGIN
  IF p_club_short_name IS NULL OR btrim(p_club_short_name) = '' THEN
    RETURN false;
  END IF;

  SELECT f.* INTO v_fixture
  FROM public.competition_fixtures f
  WHERE f.id = p_fixture_id;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  IF p_club_short_name NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name) THEN
    RETURN false;
  END IF;

  IF v_fixture.status <> 'scheduled' THEN
    RETURN false;
  END IF;

  SELECT m.unlock_at, m.lock_at
  INTO v_unlock, v_lock
  FROM public.competition_season_calendar m
  WHERE m.season_id = v_fixture.season_id
    AND m.gpsl_month = v_fixture.gpsl_month;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  IF now() >= v_lock THEN
    RETURN false;
  END IF;

  RETURN EXISTS (
    SELECT 1
    FROM public.club_owner_holidays h
    WHERE h.season_id = v_fixture.season_id
      AND h.club_short_name = p_club_short_name
      AND now() >= h.created_at
      AND now() < h.ends_at
      AND h.starts_at < v_lock
      AND h.ends_at > v_unlock
  );
END;
$function$;

-- Extend calendar guard: holiday overlap unlocks early play for submitting club.
CREATE OR REPLACE FUNCTION public.competition_assert_fixture_month_unlocked(
  p_fixture_id bigint,
  p_club_short_name text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_active text;
  v_unlock timestamptz;
  v_lock timestamptz;
  v_club text;
BEGIN
  IF public.is_gpsl_admin() THEN
    RETURN;
  END IF;

  v_club := nullif(btrim(coalesce(p_club_short_name, '')), '');

  IF v_club IS NOT NULL AND public.club_holiday_allows_fixture_early(p_fixture_id, v_club) THEN
    RETURN;
  END IF;

  SELECT f.* INTO v_fixture
  FROM public.competition_fixtures f
  WHERE f.id = p_fixture_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.competition_season_calendar_config c
    WHERE c.season_id = v_fixture.season_id
  ) THEN
    RETURN;
  END IF;

  v_active := public.competition_active_gpsl_month(v_fixture.season_id, now());

  IF v_active IS NOT NULL AND v_active = v_fixture.gpsl_month THEN
    RETURN;
  END IF;

  SELECT unlock_at, lock_at
  INTO v_unlock, v_lock
  FROM public.competition_season_calendar m
  WHERE m.season_id = v_fixture.season_id
    AND m.gpsl_month = v_fixture.gpsl_month;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No calendar window for GPSL %', public.competition_gpsl_month_label(v_fixture.gpsl_month);
  END IF;

  IF now() < v_unlock THEN
    RAISE EXCEPTION '% matches unlock at % UK (Fri 19:00 week)',
      public.competition_gpsl_month_label(v_fixture.gpsl_month),
      to_char(v_unlock AT TIME ZONE 'Europe/London', 'Dy DD Mon YYYY HH24:MI');
  END IF;

  RAISE EXCEPTION '% matches locked since % UK',
    public.competition_gpsl_month_label(v_fixture.gpsl_month),
    to_char(v_lock AT TIME ZONE 'Europe/London', 'Dy DD Mon YYYY HH24:MI');
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_result_submission_calendar_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  PERFORM public.competition_assert_fixture_month_unlocked(
    NEW.fixture_id,
    NEW.submitted_by_club
  );
  RETURN NEW;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Owner RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.club_holiday_book(
  p_start_date date,
  p_end_date date
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_season_id bigint;
  v_starts timestamptz;
  v_ends timestamptz;
  v_days integer;
  v_used integer;
  v_max integer := public.club_holiday_max_days_per_season();
  v_id bigint;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  IF p_start_date IS NULL OR p_end_date IS NULL THEN
    RAISE EXCEPTION 'Start and end dates are required';
  END IF;

  IF p_end_date < p_start_date THEN
    RAISE EXCEPTION 'End date must be on or after start date';
  END IF;

  SELECT s.id INTO v_season_id
  FROM public.competition_seasons s
  WHERE s.is_current = true
    AND s.status = 'active'
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No active competition season';
  END IF;

  v_starts := (p_start_date::timestamp AT TIME ZONE 'Europe/London');
  v_ends := ((p_end_date + 1)::timestamp AT TIME ZONE 'Europe/London');
  v_days := public.club_holiday_inclusive_days(v_starts, v_ends);

  IF v_days > v_max THEN
    RAISE EXCEPTION 'A single booking cannot exceed % days', v_max;
  END IF;

  v_used := public.club_holiday_days_used(v_season_id, v_club);
  IF v_used + v_days > v_max THEN
    RAISE EXCEPTION 'Only % days of holiday per season (% used, % requested)',
      v_max, v_used, v_days;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.club_owner_holidays h
    WHERE h.season_id = v_season_id
      AND h.club_short_name = v_club
      AND h.starts_at < v_ends
      AND h.ends_at > v_starts
  ) THEN
    RAISE EXCEPTION 'Holiday overlaps an existing booking for this season';
  END IF;

  IF v_ends <= now() THEN
    RAISE EXCEPTION 'Holiday must end in the future';
  END IF;

  INSERT INTO public.club_owner_holidays (
    season_id,
    club_short_name,
    owner_id,
    starts_at,
    ends_at,
    day_count
  )
  VALUES (
    v_season_id,
    v_club,
    auth.uid(),
    v_starts,
    v_ends,
    v_days::smallint
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.club_holiday_cancel(p_holiday_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_row public.club_owner_holidays;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_row
  FROM public.club_owner_holidays h
  WHERE h.id = p_holiday_id
    AND h.club_short_name = v_club
    AND h.owner_id = auth.uid();

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Holiday booking not found';
  END IF;

  IF v_row.starts_at <= now() THEN
    RAISE EXCEPTION 'Cannot cancel a holiday that has already started';
  END IF;

  DELETE FROM public.club_owner_holidays
  WHERE id = p_holiday_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public read (own club only)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.club_owner_holidays_public
WITH (security_invoker = false)
AS
SELECT
  h.id,
  h.season_id,
  h.club_short_name,
  h.starts_at,
  h.ends_at,
  h.day_count,
  h.created_at,
  public.club_holiday_days_used(h.season_id, h.club_short_name) AS season_days_used,
  public.club_holiday_max_days_per_season() AS season_days_allowance,
  (
    public.club_holiday_max_days_per_season()
    - public.club_holiday_days_used(h.season_id, h.club_short_name)
  ) AS season_days_remaining,
  (now() >= h.starts_at AND now() < h.ends_at) AS is_active,
  (now() < h.starts_at) AS is_upcoming,
  (now() >= h.ends_at) AS is_ended
FROM public.club_owner_holidays h
JOIN public.competition_seasons s ON s.id = h.season_id
WHERE s.is_current = true
  AND s.status = 'active'
  AND h.club_short_name = public.my_club_shortname();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.club_owner_holidays ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_owner_holidays_select ON public.club_owner_holidays;
CREATE POLICY club_owner_holidays_select ON public.club_owner_holidays
  FOR SELECT TO authenticated
  USING (club_short_name = public.my_club_shortname());

GRANT SELECT ON public.club_owner_holidays TO authenticated;
GRANT SELECT ON public.club_owner_holidays_public TO authenticated;

GRANT EXECUTE ON FUNCTION public.club_holiday_book(date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_holiday_cancel(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_holiday_days_used(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.club_holiday_allows_fixture_early(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_assert_fixture_month_unlocked(bigint, text) TO authenticated;

NOTIFY pgrst, 'reload schema';
