-- =============================================================================
-- GPSL Competition — Phase 4: match player stats (G/A/ratings/POTM) + leaderboards
-- Requires: competition_phase0–3
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Per-player lines (applied when result is confirmed)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_match_player_stats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fixture_id bigint NOT NULL REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  player_id text NOT NULL,
  appeared boolean NOT NULL DEFAULT true,
  goals smallint NOT NULL DEFAULT 0 CHECK (goals >= 0),
  assists smallint NOT NULL DEFAULT 0 CHECK (assists >= 0),
  rating numeric(4, 1) CHECK (rating IS NULL OR (rating >= 1 AND rating <= 10)),
  is_player_of_match boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_match_player_stats_unique UNIQUE (fixture_id, player_id)
);

CREATE INDEX IF NOT EXISTS competition_match_player_stats_season_player_idx
  ON public.competition_match_player_stats (season_id, player_id);

CREATE INDEX IF NOT EXISTS competition_match_player_stats_fixture_idx
  ON public.competition_match_player_stats (fixture_id);

-- Draft stats on pending submission (submitter's squad)
ALTER TABLE public.competition_result_submissions
  ADD COLUMN IF NOT EXISTS player_stats jsonb NOT NULL DEFAULT '[]'::jsonb;

-- ---------------------------------------------------------------------------
-- Apply stats when a result is confirmed
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_apply_submission_player_stats(
  p_submission_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
  v_item jsonb;
  v_player_id text;
  v_goals int;
  v_assists int;
  v_rating numeric;
  v_potm boolean;
  v_appeared boolean;
  v_team_goals int := 0;
  v_expected int;
  v_potm_count int := 0;
BEGIN
  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  DELETE FROM public.competition_match_player_stats
  WHERE fixture_id = v_sub.fixture_id;

  IF v_sub.player_stats IS NULL OR jsonb_typeof(v_sub.player_stats) <> 'array' THEN
    RETURN;
  END IF;

  IF jsonb_array_length(v_sub.player_stats) = 0 THEN
    RETURN;
  END IF;

  v_expected := CASE
    WHEN v_sub.submitted_by_club = v_fixture.home_club_short_name THEN v_sub.home_goals
    ELSE v_sub.away_goals
  END;

  FOR v_item IN SELECT value FROM jsonb_array_elements(v_sub.player_stats)
  LOOP
    v_player_id := trim(both '"' FROM (v_item ->> 'player_id'));
    v_goals := coalesce((v_item ->> 'goals')::int, 0);
    v_assists := coalesce((v_item ->> 'assists')::int, 0);
    v_rating := nullif(v_item ->> 'rating', '')::numeric;
    v_potm := coalesce((v_item ->> 'potm')::boolean, false);
    v_appeared := coalesce((v_item ->> 'appeared')::boolean, true);

    IF v_player_id IS NULL OR v_player_id = '' THEN
      CONTINUE;
    END IF;

    IF NOT v_appeared AND v_goals = 0 AND v_assists = 0 AND v_rating IS NULL AND NOT v_potm THEN
      CONTINUE;
    END IF;

    IF v_sub.submitted_by_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name) THEN
      RAISE EXCEPTION 'Invalid submitter club on submission';
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM public."Players" p
      WHERE p."Konami_ID"::text = v_player_id
        AND p."Contracted_Team" = v_sub.submitted_by_club
    ) THEN
      RAISE EXCEPTION 'Player % is not on submitter club roster', v_player_id;
    END IF;

    IF v_potm THEN
      v_potm_count := v_potm_count + 1;
    END IF;

    v_team_goals := v_team_goals + v_goals;

    INSERT INTO public.competition_match_player_stats (
      fixture_id,
      season_id,
      club_short_name,
      player_id,
      appeared,
      goals,
      assists,
      rating,
      is_player_of_match
    )
    VALUES (
      v_fixture.id,
      v_fixture.season_id,
      v_sub.submitted_by_club,
      v_player_id,
      v_appeared,
      v_goals,
      v_assists,
      v_rating,
      v_potm
    );
  END LOOP;

  IF v_potm_count > 1 THEN
    RAISE EXCEPTION 'Only one player of the match allowed';
  END IF;

  IF v_team_goals > 0 AND v_team_goals <> v_expected THEN
    RAISE EXCEPTION 'Player goals (%) must match your team score (%)', v_team_goals, v_expected;
  END IF;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Submit result (with optional player stats JSON)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_submit_result(
  p_fixture_id bigint,
  p_home_goals smallint,
  p_away_goals smallint,
  p_player_stats jsonb DEFAULT '[]'::jsonb
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_fixture public.competition_fixtures;
  v_opponent text;
  v_submission_id bigint;
  v_home_name text;
  v_away_name text;
  v_title text;
  v_body text;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  IF p_home_goals IS NULL OR p_away_goals IS NULL OR p_home_goals < 0 OR p_away_goals < 0 THEN
    RAISE EXCEPTION 'Invalid score';
  END IF;

  IF p_player_stats IS NOT NULL AND jsonb_typeof(p_player_stats) <> 'array' THEN
    RAISE EXCEPTION 'player_stats must be a JSON array';
  END IF;

  SELECT f.* INTO v_fixture
  FROM public.competition_fixtures f
  JOIN public.competition_seasons s ON s.id = f.season_id
  WHERE f.id = p_fixture_id
    AND s.is_current = true
    AND s.status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found on current season';
  END IF;

  IF v_fixture.status <> 'scheduled' THEN
    RAISE EXCEPTION 'Fixture is not open for result entry';
  END IF;

  IF v_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name) THEN
    RAISE EXCEPTION 'Your club is not in this fixture';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.competition_result_submissions s
    WHERE s.fixture_id = p_fixture_id AND s.status = 'pending'
  ) THEN
    RAISE EXCEPTION 'A result is already awaiting confirmation for this fixture';
  END IF;

  v_opponent := public.competition_fixture_opponent(p_fixture_id, v_club);

  INSERT INTO public.competition_result_submissions (
    fixture_id,
    submitted_by_club,
    home_goals,
    away_goals,
    status,
    player_stats
  )
  VALUES (
    p_fixture_id,
    v_club,
    p_home_goals,
    p_away_goals,
    'pending',
    coalesce(p_player_stats, '[]'::jsonb)
  )
  RETURNING id INTO v_submission_id;

  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  v_title := format('Confirm result: %s vs %s', v_home_name, v_away_name);
  v_body := format(
    'Matchday %s — %s submitted %s %s–%s %s. Confirm or reject.',
    v_fixture.matchday,
    v_club,
    v_home_name,
    p_home_goals,
    p_away_goals,
    v_away_name
  );

  PERFORM public.competition_inbox_notify(
    v_opponent,
    'result_to_confirm',
    p_fixture_id,
    v_submission_id,
    v_title,
    v_body
  );

  RETURN v_submission_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Confirm (apply player stats)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_confirm_result(p_submission_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
  v_opponent text;
  v_home_name text;
  v_away_name text;
BEGIN
  IF v_club IS NULL THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  v_opponent := public.competition_fixture_opponent(v_sub.fixture_id, v_club);
  IF v_opponent <> v_sub.submitted_by_club THEN
    RAISE EXCEPTION 'Only the opponent can confirm this result';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = v_sub.home_goals,
      away_goals = v_sub.away_goals,
      status = 'played'
  WHERE id = v_sub.fixture_id;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = v_club,
      responded_at = now()
  WHERE id = p_submission_id;

  UPDATE public.competition_inbox
  SET read_at = coalesce(read_at, now())
  WHERE submission_id = p_submission_id
    AND recipient_club_short_name = v_club
    AND message_type = 'result_to_confirm';

  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  PERFORM public.competition_inbox_notify(
    v_sub.submitted_by_club,
    'result_confirmed',
    v_sub.fixture_id,
    p_submission_id,
    format('Result confirmed: %s vs %s', v_home_name, v_away_name),
    format(
      'Matchday %s — %s–%s confirmed. League table and player stats updated.',
      v_fixture.matchday,
      v_sub.home_goals,
      v_sub.away_goals
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_confirm_submission(p_submission_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_sub public.competition_result_submissions;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = v_sub.home_goals,
      away_goals = v_sub.away_goals,
      status = 'played'
  WHERE id = v_sub.fixture_id;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = 'ADMIN',
      responded_at = now()
  WHERE id = p_submission_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Aggregated views (current active season, league only)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_player_season_stats_public
WITH (security_invoker = false)
AS
SELECT
  m.season_id,
  m.player_id,
  p."Name" AS player_name,
  m.club_short_name,
  c."Club" AS club_name,
  ccs.division,
  count(*) FILTER (WHERE m.appeared)::int AS appearances,
  coalesce(sum(m.goals), 0)::int AS goals,
  coalesce(sum(m.assists), 0)::int AS assists,
  round(avg(m.rating) FILTER (WHERE m.rating IS NOT NULL), 2) AS avg_rating,
  count(*) FILTER (WHERE m.is_player_of_match)::int AS potm_awards
FROM public.competition_match_player_stats m
JOIN public.competition_fixtures f ON f.id = m.fixture_id
JOIN public.competition_seasons s ON s.id = m.season_id
JOIN public."Players" p ON p."Konami_ID"::text = m.player_id
JOIN public."Clubs" c ON c."ShortName" = m.club_short_name
LEFT JOIN public.competition_club_seasons ccs
  ON ccs.season_id = m.season_id AND ccs.club_short_name = m.club_short_name
WHERE s.is_current = true
  AND s.status = 'active'
  AND f.status = 'played'
  AND f.competition_type = 'league'
GROUP BY
  m.season_id,
  m.player_id,
  p."Name",
  m.club_short_name,
  c."Club",
  ccs.division;

GRANT SELECT ON public.competition_player_season_stats_public TO authenticated;
GRANT SELECT ON public.competition_player_season_stats_public TO anon;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_match_player_stats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_match_player_stats_select ON public.competition_match_player_stats;
CREATE POLICY competition_match_player_stats_select ON public.competition_match_player_stats
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS competition_match_player_stats_admin ON public.competition_match_player_stats;
CREATE POLICY competition_match_player_stats_admin ON public.competition_match_player_stats
  FOR ALL
  TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.competition_match_player_stats TO authenticated;

GRANT EXECUTE ON FUNCTION public.competition_submit_result(bigint, smallint, smallint, jsonb) TO authenticated;
