-- =============================================================================
-- GPSL Competition — Phase 3: matchday result submit + inbox confirm/reject
-- Requires: competition_phase0–2
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Result submissions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_result_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fixture_id bigint NOT NULL REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  submitted_by_club text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  home_goals smallint NOT NULL CHECK (home_goals >= 0),
  away_goals smallint NOT NULL CHECK (away_goals >= 0),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'rejected')),
  responded_by_club text REFERENCES public."Clubs" ("ShortName"),
  reject_reason text,
  submitted_at timestamptz NOT NULL DEFAULT now(),
  responded_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS competition_result_submissions_one_pending_idx
  ON public.competition_result_submissions (fixture_id)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS competition_result_submissions_fixture_idx
  ON public.competition_result_submissions (fixture_id);

-- ---------------------------------------------------------------------------
-- Owner inbox
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_inbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  message_type text NOT NULL CHECK (
    message_type IN ('result_to_confirm', 'result_rejected', 'result_confirmed')
  ),
  fixture_id bigint REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  submission_id bigint REFERENCES public.competition_result_submissions (id) ON DELETE CASCADE,
  title text NOT NULL,
  body text NOT NULL,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS competition_inbox_recipient_unread_idx
  ON public.competition_inbox (recipient_club_short_name)
  WHERE read_at IS NULL;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_fixture_opponent(
  p_fixture_id bigint,
  p_club text
)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE
    WHEN f.home_club_short_name = p_club THEN f.away_club_short_name
    WHEN f.away_club_short_name = p_club THEN f.home_club_short_name
    ELSE NULL
  END
  FROM public.competition_fixtures f
  WHERE f.id = p_fixture_id;
$$;

CREATE OR REPLACE FUNCTION public.competition_inbox_notify(
  p_recipient_club text,
  p_message_type text,
  p_fixture_id bigint,
  p_submission_id bigint,
  p_title text,
  p_body text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint;
BEGIN
  INSERT INTO public.competition_inbox (
    recipient_club_short_name,
    message_type,
    fixture_id,
    submission_id,
    title,
    body
  )
  VALUES (
    p_recipient_club,
    p_message_type,
    p_fixture_id,
    p_submission_id,
    p_title,
    p_body
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Submit proposed result (notifies opponent)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_submit_result(
  p_fixture_id bigint,
  p_home_goals smallint,
  p_away_goals smallint
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_fixture public.competition_fixtures;
  v_opponent text;
  v_submission_id bigint;
  v_home_name text;
  v_away_name text;
  v_title text;
  v_body text;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  IF p_home_goals IS NULL OR p_away_goals IS NULL OR p_home_goals < 0 OR p_away_goals < 0 THEN
    RAISE EXCEPTION 'Invalid score';
  END IF;

  SELECT f.* INTO v_fixture
  FROM public.competition_fixtures f
  JOIN public.competition_seasons s ON s.id = f.season_id
  WHERE f.id = p_fixture_id
    AND s.is_current = true
    AND s.status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found on current season';
  END IF;

  IF v_fixture.status <> 'scheduled' THEN
    RAISE EXCEPTION 'Fixture is not open for result entry';
  END IF;

  IF v_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name) THEN
    RAISE EXCEPTION 'Your club is not in this fixture';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.competition_result_submissions s
    WHERE s.fixture_id = p_fixture_id AND s.status = 'pending'
  ) THEN
    RAISE EXCEPTION 'A result is already awaiting confirmation for this fixture';
  END IF;

  v_opponent := public.competition_fixture_opponent(p_fixture_id, v_club);
  IF v_opponent IS NULL THEN
    RAISE EXCEPTION 'Could not determine opponent';
  END IF;

  INSERT INTO public.competition_result_submissions (
    fixture_id,
    submitted_by_club,
    home_goals,
    away_goals,
    status
  )
  VALUES (p_fixture_id, v_club, p_home_goals, p_away_goals, 'pending')
  RETURNING id INTO v_submission_id;

  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  v_title := format('Confirm result: %s vs %s', v_home_name, v_away_name);
  v_body := format(
    'Matchday %s — %s submitted %s %s–%s %s. Confirm or reject.',
    v_fixture.matchday,
    v_club,
    v_home_name,
    p_home_goals,
    p_away_goals,
    v_away_name
  );

  PERFORM public.competition_inbox_notify(
    v_opponent,
    'result_to_confirm',
    p_fixture_id,
    v_submission_id,
    v_title,
    v_body
  );

  RETURN v_submission_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Opponent confirms → fixture official
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_confirm_result(p_submission_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
  v_opponent text;
  v_home_name text;
  v_away_name text;
BEGIN
  IF v_club IS NULL THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  v_opponent := public.competition_fixture_opponent(v_sub.fixture_id, v_club);
  IF v_opponent <> v_sub.submitted_by_club THEN
    RAISE EXCEPTION 'Only the opponent can confirm this result';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = v_sub.home_goals,
      away_goals = v_sub.away_goals,
      status = 'played'
  WHERE id = v_sub.fixture_id;

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = v_club,
      responded_at = now()
  WHERE id = p_submission_id;

  UPDATE public.competition_inbox
  SET read_at = coalesce(read_at, now())
  WHERE submission_id = p_submission_id
    AND recipient_club_short_name = v_club
    AND message_type = 'result_to_confirm';

  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  PERFORM public.competition_inbox_notify(
    v_sub.submitted_by_club,
    'result_confirmed',
    v_sub.fixture_id,
    p_submission_id,
    format('Result confirmed: %s vs %s', v_home_name, v_away_name),
    format(
      'Matchday %s — %s–%s confirmed and added to the table.',
      v_fixture.matchday,
      v_sub.home_goals,
      v_sub.away_goals
    )
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Opponent rejects
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_reject_result(
  p_submission_id bigint,
  p_reason text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
  v_home_name text;
  v_away_name text;
BEGIN
  IF v_club IS NULL THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  IF public.competition_fixture_opponent(v_sub.fixture_id, v_club) <> v_sub.submitted_by_club THEN
    RAISE EXCEPTION 'Only the opponent can reject this result';
  END IF;

  UPDATE public.competition_result_submissions
  SET status = 'rejected',
      responded_by_club = v_club,
      reject_reason = nullif(trim(p_reason), ''),
      responded_at = now()
  WHERE id = p_submission_id;

  UPDATE public.competition_inbox
  SET read_at = coalesce(read_at, now())
  WHERE submission_id = p_submission_id
    AND recipient_club_short_name = v_club
    AND message_type = 'result_to_confirm';

  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  PERFORM public.competition_inbox_notify(
    v_sub.submitted_by_club,
    'result_rejected',
    v_sub.fixture_id,
    p_submission_id,
    format('Result rejected: %s vs %s', v_home_name, v_away_name),
    coalesce(
      nullif(trim(p_reason), ''),
      format(
        'Matchday %s — opponent rejected %s–%s. Submit again or contact admin.',
        v_fixture.matchday,
        v_sub.home_goals,
        v_sub.away_goals
      )
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_inbox_mark_read(p_inbox_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
BEGIN
  UPDATE public.competition_inbox
  SET read_at = now()
  WHERE id = p_inbox_id
    AND recipient_club_short_name = v_club
    AND read_at IS NULL;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Updated fixtures public view (includes pending submission)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_fixtures_public
WITH (security_invoker = false)
AS
SELECT
  f.id,
  f.season_id,
  f.division,
  f.competition_type,
  f.matchday,
  f.gpsl_month,
  f.week_in_month,
  f.home_club_short_name,
  hc."Club" AS home_club_name,
  f.away_club_short_name,
  ac."Club" AS away_club_name,
  f.weather,
  f.home_goals,
  f.away_goals,
  f.status,
  sub.submission_id,
  sub.submission_status,
  sub.submitted_by_club,
  sub.proposed_home_goals,
  sub.proposed_away_goals
FROM public.competition_fixtures f
JOIN public.competition_seasons s ON s.id = f.season_id
JOIN public."Clubs" hc ON hc."ShortName" = f.home_club_short_name
JOIN public."Clubs" ac ON ac."ShortName" = f.away_club_short_name
LEFT JOIN LATERAL (
  SELECT
    rs.id AS submission_id,
    rs.status AS submission_status,
    rs.submitted_by_club,
    rs.home_goals AS proposed_home_goals,
    rs.away_goals AS proposed_away_goals
  FROM public.competition_result_submissions rs
  WHERE rs.fixture_id = f.id
    AND rs.status = 'pending'
  LIMIT 1
) sub ON true
WHERE s.status = 'active' AND s.is_current = true;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_result_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_inbox ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_result_submissions_select ON public.competition_result_submissions;
CREATE POLICY competition_result_submissions_select ON public.competition_result_submissions
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS competition_result_submissions_admin ON public.competition_result_submissions;
CREATE POLICY competition_result_submissions_admin ON public.competition_result_submissions
  FOR ALL
  TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS competition_inbox_select ON public.competition_inbox;
CREATE POLICY competition_inbox_select ON public.competition_inbox
  FOR SELECT
  TO authenticated
  USING (recipient_club_short_name = public.my_club_shortname());

DROP POLICY IF EXISTS competition_inbox_update ON public.competition_inbox;
CREATE POLICY competition_inbox_update ON public.competition_inbox
  FOR UPDATE
  TO authenticated
  USING (recipient_club_short_name = public.my_club_shortname())
  WITH CHECK (recipient_club_short_name = public.my_club_shortname());

DROP POLICY IF EXISTS competition_inbox_admin ON public.competition_inbox;
CREATE POLICY competition_inbox_admin ON public.competition_inbox
  FOR ALL
  TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.competition_result_submissions TO authenticated;
GRANT SELECT ON public.competition_inbox TO authenticated;

GRANT EXECUTE ON FUNCTION public.competition_submit_result(bigint, smallint, smallint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_confirm_result(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_reject_result(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_inbox_mark_read(bigint) TO authenticated;

-- Admin override: confirm pending or apply directly
CREATE OR REPLACE FUNCTION public.competition_admin_confirm_submission(p_submission_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_sub public.competition_result_submissions;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = v_sub.home_goals,
      away_goals = v_sub.away_goals,
      status = 'played'
  WHERE id = v_sub.fixture_id;

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = 'ADMIN',
      responded_at = now()
  WHERE id = p_submission_id;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.competition_admin_confirm_submission(bigint) TO authenticated;
