-- =============================================================================
-- GPSL Competition — Phase 5: gate receipts + finance ledger
-- Requires: competition_phase0–4
-- Spec: docs/competition-spec.md — home league 100%, cups 50/50
--
-- Gate formula (v1, tunable constants below):
--   attendance_rate = base_fill + position_boost + history_boost (capped)
--   total_gate = capacity × attendance_rate × price_per_seat
--   position: current league table_position in fixture division (default mid-table 10)
--   history: avg final_position from competition_club_season_archive (last 5 seasons; neutral if none)
-- =============================================================================

-- Allow cup fixtures later (league only generated in phase 1 today)
ALTER TABLE public.competition_fixtures
  DROP CONSTRAINT IF EXISTS competition_fixtures_competition_type_check;

ALTER TABLE public.competition_fixtures
  ADD CONSTRAINT competition_fixtures_competition_type_check
  CHECK (competition_type IN ('league', 'cup'));

-- ---------------------------------------------------------------------------
-- Season archive (5-year history for gate multiplier; fill via admin / season end)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_club_season_archive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  season_label text NOT NULL,
  division text NOT NULL CHECK (
    division IN ('superleague', 'championship_a', 'championship_b')
  ),
  final_position smallint NOT NULL CHECK (final_position >= 1 AND final_position <= 20),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_club_season_archive_unique UNIQUE (club_short_name, season_label)
);

CREATE INDEX IF NOT EXISTS competition_club_season_archive_club_idx
  ON public.competition_club_season_archive (club_short_name, created_at DESC);

-- ---------------------------------------------------------------------------
-- Ledger (gates now; prizes in phase 6+)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_finance_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  fixture_id bigint REFERENCES public.competition_fixtures (id) ON DELETE SET NULL,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  entry_type text NOT NULL CHECK (
    entry_type IN ('gate_league_home', 'gate_cup_share', 'prize', 'adjustment')
  ),
  amount numeric(14, 2) NOT NULL CHECK (amount <> 0),
  description text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_finance_ledger_fixture_unique UNIQUE (fixture_id, club_short_name, entry_type)
);

CREATE INDEX IF NOT EXISTS competition_finance_ledger_club_idx
  ON public.competition_finance_ledger (club_short_name, created_at DESC);

-- ---------------------------------------------------------------------------
-- Gate calculation helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_club_table_position(
  p_season_id bigint,
  p_division text,
  p_club_short_name text
)
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(s.table_position, 10)::int
  FROM public.competition_standings_public s
  WHERE s.season_id = p_season_id
    AND s.division = p_division
    AND s.club_short_name = p_club_short_name
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.competition_club_history_avg_position(
  p_club_short_name text,
  p_limit int DEFAULT 5
)
RETURNS numeric
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT avg(a.final_position)::numeric
  FROM (
    SELECT final_position
    FROM public.competition_club_season_archive
    WHERE club_short_name = p_club_short_name
    ORDER BY created_at DESC
    LIMIT greatest(p_limit, 1)
  ) a;
$$;

CREATE OR REPLACE FUNCTION public.competition_compute_gate_total(
  p_capacity int,
  p_table_position int,
  p_history_avg_position numeric
)
RETURNS jsonb
LANGUAGE plpgsql
IMMUTABLE
AS $function$
DECLARE
  v_capacity int := greatest(coalesce(p_capacity, 0), 0);
  v_pos int := least(greatest(coalesce(p_table_position, 10), 1), 20);
  v_hist numeric := coalesce(p_history_avg_position, 10);
  v_base_fill numeric := 0.55;
  v_position_boost numeric;
  v_history_boost numeric;
  v_fill numeric;
  v_price_per_seat numeric := 20;
  v_total numeric;
BEGIN
  v_position_boost := 0.35 * ((21 - v_pos)::numeric / 20.0);
  v_history_boost := 0.05 * ((21 - least(greatest(v_hist, 1), 20)) / 20.0);
  v_fill := least(v_base_fill + v_position_boost + v_history_boost, 0.95);
  v_total := round(v_capacity * v_fill * v_price_per_seat);

  RETURN jsonb_build_object(
    'capacity', v_capacity,
    'table_position', v_pos,
    'history_avg_position', round(v_hist, 2),
    'attendance_rate', round(v_fill, 4),
    'price_per_seat', v_price_per_seat,
    'total_gate', v_total
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_estimate_gate_for_club(
  p_club_short_name text,
  p_season_id bigint DEFAULT NULL,
  p_division text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_division text;
  v_capacity int;
  v_pos int;
  v_hist numeric;
  v_breakdown jsonb;
BEGIN
  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true AND status = 'active'
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('error', 'No active season');
  END IF;

  IF p_division IS NULL THEN
    SELECT ccs.division INTO v_division
    FROM public.competition_club_seasons ccs
    WHERE ccs.season_id = v_season_id
      AND ccs.club_short_name = p_club_short_name
    LIMIT 1;
  ELSE
    v_division := p_division;
  END IF;

  SELECT coalesce(c."Capacity", 0)::int INTO v_capacity
  FROM public."Clubs" c
  WHERE c."ShortName" = p_club_short_name;

  v_pos := public.competition_club_table_position(
    v_season_id,
    coalesce(v_division, 'superleague'),
    p_club_short_name
  );
  v_hist := public.competition_club_history_avg_position(p_club_short_name, 5);
  v_breakdown := public.competition_compute_gate_total(v_capacity, v_pos, v_hist);

  RETURN v_breakdown || jsonb_build_object(
    'club_short_name', p_club_short_name,
    'season_id', v_season_id,
    'division', v_division
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_credit_club_balance(
  p_club_short_name text,
  p_amount numeric
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_balance numeric;
BEGIN
  IF p_amount IS NULL OR p_amount = 0 THEN
    RETURN;
  END IF;

  SELECT balance INTO v_balance
  FROM public."Club_Finances"
  WHERE club_name = p_club_short_name
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Club_Finances row missing for %', p_club_short_name;
  END IF;

  UPDATE public."Club_Finances"
  SET balance = v_balance + p_amount
  WHERE club_name = p_club_short_name;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_settle_fixture_gates(p_fixture_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_capacity int;
  v_pos int;
  v_hist numeric;
  v_breakdown jsonb;
  v_total numeric;
  v_home_share numeric;
  v_away_share numeric;
  v_desc text;
  v_home_club text;
  v_away_club text;
BEGIN
  IF p_fixture_id IS NULL THEN
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.competition_finance_ledger
    WHERE fixture_id = p_fixture_id
      AND entry_type IN ('gate_league_home', 'gate_cup_share')
  ) THEN
    RETURN;
  END IF;

  SELECT * INTO v_fixture
  FROM public.competition_fixtures
  WHERE id = p_fixture_id
    AND status = 'played'
    AND home_goals IS NOT NULL
    AND away_goals IS NOT NULL;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  v_home_club := v_fixture.home_club_short_name;
  v_away_club := v_fixture.away_club_short_name;

  SELECT coalesce(c."Capacity", 0)::int INTO v_capacity
  FROM public."Clubs" c
  WHERE c."ShortName" = v_home_club;

  v_pos := public.competition_club_table_position(
    v_fixture.season_id,
    v_fixture.division,
    v_home_club
  );
  v_hist := public.competition_club_history_avg_position(v_home_club, 5);
  v_breakdown := public.competition_compute_gate_total(v_capacity, v_pos, v_hist);
  v_total := (v_breakdown ->> 'total_gate')::numeric;

  IF v_total IS NULL OR v_total <= 0 THEN
    RETURN;
  END IF;

  IF v_fixture.competition_type = 'league' THEN
    v_desc := format(
      'Gate MD%s — %s vs %s (home 100%%) · fill %s%%',
      v_fixture.matchday,
      v_home_club,
      v_away_club,
      round(((v_breakdown ->> 'attendance_rate')::numeric) * 100, 1)
    );

    PERFORM public.competition_credit_club_balance(v_home_club, v_total);

    INSERT INTO public.competition_finance_ledger (
      season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
    )
    VALUES (
      v_fixture.season_id,
      p_fixture_id,
      v_home_club,
      'gate_league_home',
      v_total,
      v_desc,
      v_breakdown
    );
  ELSIF v_fixture.competition_type = 'cup' THEN
    v_home_share := round(v_total / 2.0, 2);
    v_away_share := v_total - v_home_share;

    PERFORM public.competition_credit_club_balance(v_home_club, v_home_share);
    PERFORM public.competition_credit_club_balance(v_away_club, v_away_share);

    INSERT INTO public.competition_finance_ledger (
      season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
    )
    VALUES
      (
        v_fixture.season_id,
        p_fixture_id,
        v_home_club,
        'gate_cup_share',
        v_home_share,
        format('Cup gate MD%s — %s vs %s (50%% home share)', v_fixture.matchday, v_home_club, v_away_club),
        v_breakdown || jsonb_build_object('split', 'home')
      ),
      (
        v_fixture.season_id,
        p_fixture_id,
        v_away_club,
        'gate_cup_share',
        v_away_share,
        format('Cup gate MD%s — %s vs %s (50%% away share)', v_fixture.matchday, v_home_club, v_away_club),
        v_breakdown || jsonb_build_object('split', 'away')
      );
  END IF;
END;
$function$;

-- Admin: archive a finished season row (for 5-year gate history)
CREATE OR REPLACE FUNCTION public.competition_admin_archive_club_season(
  p_club_short_name text,
  p_season_label text,
  p_division text,
  p_final_position smallint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  INSERT INTO public.competition_club_season_archive (
    club_short_name, season_label, division, final_position
  )
  VALUES (
    upper(trim(p_club_short_name)),
    trim(p_season_label),
    p_division,
    p_final_position
  )
  ON CONFLICT (club_short_name, season_label)
  DO UPDATE SET
    division = excluded.division,
    final_position = excluded.final_position;
END;
$function$;

-- Backfill gates for played fixtures missing ledger rows (current season)
CREATE OR REPLACE FUNCTION public.competition_admin_backfill_gates(p_season_id bigint DEFAULT NULL)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_fixture record;
  v_count int := 0;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  FOR v_fixture IN
    SELECT id
    FROM public.competition_fixtures
    WHERE season_id = v_season_id
      AND status = 'played'
      AND competition_type IN ('league', 'cup')
    ORDER BY matchday, id
  LOOP
    PERFORM public.competition_settle_fixture_gates(v_fixture.id);
    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Hook gate settlement into result confirmation
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_confirm_result(p_submission_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
  v_opponent text;
  v_home_name text;
  v_away_name text;
BEGIN
  IF v_club IS NULL THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  v_opponent := public.competition_fixture_opponent(v_sub.fixture_id, v_club);
  IF v_opponent <> v_sub.submitted_by_club THEN
    RAISE EXCEPTION 'Only the opponent can confirm this result';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = v_sub.home_goals,
      away_goals = v_sub.away_goals,
      status = 'played'
  WHERE id = v_sub.fixture_id;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);
  PERFORM public.competition_settle_fixture_gates(v_sub.fixture_id);

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = v_club,
      responded_at = now()
  WHERE id = p_submission_id;

  UPDATE public.competition_inbox
  SET read_at = coalesce(read_at, now())
  WHERE submission_id = p_submission_id
    AND recipient_club_short_name = v_club
    AND message_type = 'result_to_confirm';

  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  PERFORM public.competition_inbox_notify(
    v_sub.submitted_by_club,
    'result_confirmed',
    v_sub.fixture_id,
    p_submission_id,
    format('Result confirmed: %s vs %s', v_home_name, v_away_name),
    format(
      'Matchday %s — %s–%s confirmed. Table, stats, and gate receipts updated.',
      v_fixture.matchday,
      v_sub.home_goals,
      v_sub.away_goals
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_confirm_submission(p_submission_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_sub public.competition_result_submissions;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = v_sub.home_goals,
      away_goals = v_sub.away_goals,
      status = 'played'
  WHERE id = v_sub.fixture_id;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);
  PERFORM public.competition_settle_fixture_gates(v_sub.fixture_id);

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = 'ADMIN',
      responded_at = now()
  WHERE id = p_submission_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_record_result(
  p_fixture_id bigint,
  p_home_goals smallint,
  p_away_goals smallint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_home_goals IS NULL OR p_away_goals IS NULL OR p_home_goals < 0 OR p_away_goals < 0 THEN
    RAISE EXCEPTION 'Invalid score';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = p_home_goals,
      away_goals = p_away_goals,
      status = 'played'
  WHERE id = p_fixture_id
    AND competition_type IN ('league', 'cup');

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  PERFORM public.competition_settle_fixture_gates(p_fixture_id);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public views
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_finance_ledger_public
WITH (security_invoker = false)
AS
SELECT
  l.id,
  l.season_id,
  l.fixture_id,
  l.club_short_name,
  c."Club" AS club_name,
  l.entry_type,
  l.amount,
  l.description,
  l.metadata,
  l.created_at,
  f.matchday,
  f.competition_type,
  f.home_club_short_name,
  f.away_club_short_name
FROM public.competition_finance_ledger l
JOIN public."Clubs" c ON c."ShortName" = l.club_short_name
LEFT JOIN public.competition_fixtures f ON f.id = l.fixture_id
JOIN public.competition_seasons s ON s.id = l.season_id
WHERE s.is_current = true
  AND s.status = 'active';

GRANT SELECT ON public.competition_finance_ledger_public TO authenticated;
GRANT SELECT ON public.competition_finance_ledger_public TO anon;

CREATE OR REPLACE VIEW public.competition_club_season_archive_public
WITH (security_invoker = false)
AS
SELECT
  a.club_short_name,
  c."Club" AS club_name,
  a.season_label,
  a.division,
  a.final_position,
  a.created_at
FROM public.competition_club_season_archive a
JOIN public."Clubs" c ON c."ShortName" = a.club_short_name;

GRANT SELECT ON public.competition_club_season_archive_public TO authenticated;
GRANT SELECT ON public.competition_club_season_archive_public TO anon;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_finance_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_club_season_archive ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_finance_ledger_select ON public.competition_finance_ledger;
CREATE POLICY competition_finance_ledger_select ON public.competition_finance_ledger
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_finance_ledger_admin ON public.competition_finance_ledger;
CREATE POLICY competition_finance_ledger_admin ON public.competition_finance_ledger
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS competition_club_season_archive_select ON public.competition_club_season_archive;
CREATE POLICY competition_club_season_archive_select ON public.competition_club_season_archive
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_club_season_archive_admin ON public.competition_club_season_archive;
CREATE POLICY competition_club_season_archive_admin ON public.competition_club_season_archive
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.competition_finance_ledger TO authenticated;
GRANT SELECT ON public.competition_club_season_archive TO authenticated;

GRANT EXECUTE ON FUNCTION public.competition_estimate_gate_for_club(text, bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_archive_club_season(text, text, text, smallint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_backfill_gates(bigint) TO authenticated;
