-- =============================================================================
-- GPSL — Fines & compensation (admin tariffs + instant ledger)
-- Run once after competition_wages_taxes.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Ledger type
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_finance_ledger
  DROP CONSTRAINT IF EXISTS competition_finance_ledger_entry_type_check;

ALTER TABLE public.competition_finance_ledger
  ADD CONSTRAINT competition_finance_ledger_entry_type_check
  CHECK (
    entry_type IN (
      'gate_league_home',
      'gate_cup_share',
      'prize',
      'prize_league',
      'prize_cup',
      'prize_challenge',
      'tv_revenue',
      'gov_hg_subsidy',
      'gov_youth_subsidy',
      'gov_bnb_subsidy',
      'gov_fine_compensation',
      'gov_emergency_tax',
      'gov_income_tax',
      'wage_squad',
      'wage_renewal_34plus',
      'wage_star_tax',
      'adjustment',
      'admin_one_off_injection',
      'admin_purchase_payment',
      'transfer_sale',
      'transfer_purchase',
      'transfer_agent_fee',
      'transfer_foreign_sale',
      'transfer_overflow_release',
      'loan_drawdown',
      'loan_repayment_principal',
      'loan_interest_payment',
      'infra_maintenance',
      'infra_purchase',
      'infra_expansion',
      'infra_expansion_refund',
      'infra_expansion_penalty'
    )
  );

-- ---------------------------------------------------------------------------
-- Tariff catalogue (admin-editable)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_fine_tariff (
  code text PRIMARY KEY,
  label text NOT NULL,
  category text NOT NULL DEFAULT 'matchday' CHECK (
    category IN ('matchday', 'squad', 'transfer', 'manager', 'compensation', 'other')
  ),
  direction text NOT NULL DEFAULT 'fine' CHECK (direction IN ('fine', 'compensation')),
  amount numeric(14, 2) CHECK (amount IS NULL OR amount >= 0),
  amount_mode text NOT NULL DEFAULT 'fixed' CHECK (amount_mode IN ('fixed', 'manual')),
  is_active boolean NOT NULL DEFAULT true,
  sort_order smallint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.competition_fine_applied (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint REFERENCES public.competition_seasons (id) ON DELETE SET NULL,
  tariff_code text NOT NULL REFERENCES public.competition_fine_tariff (code),
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  amount numeric(14, 2) NOT NULL CHECK (amount <> 0),
  direction text NOT NULL CHECK (direction IN ('fine', 'compensation')),
  description text NOT NULL,
  note text,
  fixture_id bigint REFERENCES public.competition_fixtures (id) ON DELETE SET NULL,
  ledger_id bigint REFERENCES public.competition_finance_ledger (id) ON DELETE SET NULL,
  applied_by text NOT NULL DEFAULT 'ADMIN',
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS competition_fine_applied_club_idx
  ON public.competition_fine_applied (club_short_name, applied_at DESC);

ALTER TABLE public.competition_fine_tariff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_fine_applied ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_fine_tariff_select ON public.competition_fine_tariff;
CREATE POLICY competition_fine_tariff_select ON public.competition_fine_tariff
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_fine_applied_select ON public.competition_fine_applied;
CREATE POLICY competition_fine_applied_select ON public.competition_fine_applied
  FOR SELECT TO authenticated USING (true);

CREATE OR REPLACE VIEW public.competition_fine_tariffs_public
WITH (security_invoker = false)
AS
SELECT
  code,
  label,
  category,
  direction,
  amount,
  amount_mode,
  is_active,
  sort_order
FROM public.competition_fine_tariff
WHERE is_active = true
ORDER BY category, sort_order, label;

GRANT SELECT ON public.competition_fine_tariffs_public TO authenticated;
GRANT SELECT ON public.competition_fine_tariffs_public TO anon;

-- ---------------------------------------------------------------------------
-- Apply fine / compensation (instant ledger)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_apply_club_fine_tariff(
  p_club_short_name text,
  p_tariff_code text,
  p_amount_override numeric DEFAULT NULL,
  p_note text DEFAULT NULL,
  p_fixture_id bigint DEFAULT NULL,
  p_season_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_tariff public.competition_fine_tariff;
  v_club text := btrim(p_club_short_name);
  v_amount numeric;
  v_ledger_amount numeric;
  v_season_id bigint;
  v_desc text;
  v_ledger_id bigint;
  v_applied_id bigint;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'Club required';
  END IF;

  SELECT * INTO v_tariff
  FROM public.competition_fine_tariff
  WHERE code = p_tariff_code AND is_active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unknown or inactive tariff: %', p_tariff_code;
  END IF;

  IF v_tariff.amount_mode = 'manual' THEN
    v_amount := p_amount_override;
    IF v_amount IS NULL OR v_amount <= 0 THEN
      RAISE EXCEPTION 'Manual amount required for %', v_tariff.label;
    END IF;
  ELSE
    v_amount := coalesce(p_amount_override, v_tariff.amount);
    IF v_amount IS NULL OR v_amount <= 0 THEN
      RAISE EXCEPTION 'Tariff % has no amount configured', v_tariff.label;
    END IF;
  END IF;

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  IF v_tariff.direction = 'fine' THEN
    v_ledger_amount := -abs(v_amount);
    PERFORM public.competition_credit_club_balance(v_club, v_ledger_amount);
    v_desc := format('Fine — %s', v_tariff.label);
  ELSE
    v_ledger_amount := abs(v_amount);
    PERFORM public.competition_credit_club_balance(v_club, v_ledger_amount);
    v_desc := format('Compensation — %s', v_tariff.label);
  END IF;

  IF p_note IS NOT NULL AND btrim(p_note) <> '' THEN
    v_desc := v_desc || ' — ' || btrim(p_note);
  END IF;

  INSERT INTO public.competition_finance_ledger (
    season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
  )
  VALUES (
    v_season_id,
    p_fixture_id,
    v_club,
    'gov_fine_compensation',
    v_ledger_amount,
    v_desc,
    jsonb_build_object(
      'tariff_code', v_tariff.code,
      'direction', v_tariff.direction,
      'category', v_tariff.category
    )
  )
  RETURNING id INTO v_ledger_id;

  INSERT INTO public.competition_fine_applied (
    season_id, tariff_code, club_short_name, amount, direction,
    description, note, fixture_id, ledger_id, applied_by
  )
  VALUES (
    v_season_id, v_tariff.code, v_club, abs(v_amount), v_tariff.direction,
    v_desc, p_note, p_fixture_id, v_ledger_id,
    CASE WHEN public.is_gpsl_admin() THEN 'ADMIN' ELSE 'SYSTEM' END
  )
  RETURNING id INTO v_applied_id;

  RETURN jsonb_build_object(
    'applied_id', v_applied_id,
    'ledger_id', v_ledger_id,
    'club_short_name', v_club,
    'tariff_code', v_tariff.code,
    'amount', abs(v_amount),
    'direction', v_tariff.direction,
    'ledger_amount', v_ledger_amount
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Admin RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_admin_save_fine_tariff(p_tariff jsonb)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_tariff IS NULL OR jsonb_typeof(p_tariff) <> 'object' THEN
    RAISE EXCEPTION 'tariff must be a JSON object';
  END IF;

  INSERT INTO public.competition_fine_tariff (
    code, label, category, direction, amount, amount_mode, is_active, sort_order
  )
  VALUES (
    p_tariff->>'code',
    p_tariff->>'label',
    coalesce(p_tariff->>'category', 'matchday'),
    coalesce(p_tariff->>'direction', 'fine'),
    nullif(p_tariff->>'amount', '')::numeric,
    coalesce(p_tariff->>'amount_mode', 'fixed'),
    coalesce((p_tariff->>'is_active')::boolean, true),
    coalesce((p_tariff->>'sort_order')::smallint, 0)
  )
  ON CONFLICT (code) DO UPDATE
  SET
    label = excluded.label,
    category = excluded.category,
    direction = excluded.direction,
    amount = excluded.amount,
    amount_mode = excluded.amount_mode,
    is_active = excluded.is_active,
    sort_order = excluded.sort_order,
    updated_at = now();
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_apply_fine(
  p_club_short_name text,
  p_tariff_code text,
  p_amount_override numeric DEFAULT NULL,
  p_note text DEFAULT NULL,
  p_fixture_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  RETURN public.competition_apply_club_fine_tariff(
    p_club_short_name,
    p_tariff_code,
    p_amount_override,
    p_note,
    p_fixture_id,
    NULL
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_seed_fine_tariffs()
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_n int;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  INSERT INTO public.competition_fine_tariff (code, label, category, direction, amount, amount_mode, sort_order)
  VALUES
    ('club_franchise', 'Club Franchise', 'other', 'fine', 175000000, 'fixed', 1),
    ('own_goal_scored', 'Deliberately scoring an own goal', 'matchday', 'fine', 10000000, 'fixed', 10),
    ('own_goal_attempt', 'Deliberately attempt to score an own goal', 'matchday', 'fine', 10000000, 'fixed', 11),
    ('engineer_opposition_chances', 'Deliberately engineer opposition chances to score', 'matchday', 'fine', 10000000, 'fixed', 12),
    ('refusing_to_participate', 'Refusing to participate', 'matchday', 'fine', 10000000, 'fixed', 13),
    ('illegal_pa_level', 'Illegal PA Level', 'matchday', 'fine', 10000000, 'fixed', 20),
    ('illegal_pa_level_sub', 'Illegal PA Level Sub', 'matchday', 'fine', 5000000, 'fixed', 21),
    ('non_display_pa_level', 'Non Display PA Level', 'matchday', 'fine', 10000000, 'fixed', 22),
    ('non_display_pa_level_sub', 'Non Display PA Level Sub', 'matchday', 'fine', 5000000, 'fixed', 23),
    ('use_of_sa', 'Use of SA', 'matchday', 'fine', 10000000, 'fixed', 24),
    ('use_of_sa_sub', 'Use of SA Sub', 'matchday', 'fine', 5000000, 'fixed', 25),
    ('time_wasting', 'Time Wasting', 'matchday', 'fine', 10000000, 'fixed', 30),
    ('showboating', 'Showboating', 'matchday', 'fine', 10000000, 'fixed', 31),
    ('playing_whilst_opponent_incapacitated', 'Playing whilst opponent is incapacitated', 'matchday', 'fine', 10000000, 'fixed', 32),
    ('ineligible_player_unused_sub', 'Ineligible Player Unused Sub', 'matchday', 'fine', 2500000, 'fixed', 40),
    ('ineligible_starts_off_by_10', 'Ineligible Player Starts - off by 10 no score', 'matchday', 'fine', 5000000, 'fixed', 41),
    ('ineligible_starts_plays_10', 'Ineligible Player Starts - plays more than 10', 'matchday', 'fine', 10000000, 'fixed', 42),
    ('ineligible_player_sub_introduced', 'Ineligible Player Sub introduced', 'matchday', 'fine', 10000000, 'fixed', 43),
    ('u21_matchday_failure', 'u21 Matchday Failure', 'matchday', 'fine', 5000000, 'fixed', 50),
    ('hg_matchday_failure', 'HG Matchday Failure', 'matchday', 'fine', 5000000, 'fixed', 51),
    ('deliberate_foul_play', 'Deliberate Foul Play', 'matchday', 'fine', 7500000, 'fixed', 52),
    ('dogso', 'DOGSO', 'matchday', 'fine', 20000000, 'fixed', 53),
    ('incorrect_matchroom_settings', 'Incorrect Matchroom Settings', 'matchday', 'fine', 2500000, 'fixed', 60),
    ('form_manipulation', 'Form Manipulation', 'matchday', 'fine', 10000000, 'fixed', 61),
    ('matchroom_not_displayed_home', 'Matchroom settings not displayed (Home)', 'matchday', 'fine', 10000000, 'fixed', 62),
    ('matchroom_not_displayed_away', 'Matchroom settings not displayed (Away)', 'matchday', 'fine', 2500000, 'fixed', 63),
    ('incorrect_readyup_sequence', 'Incorrect Readyup Sequence', 'matchday', 'fine', 2500000, 'fixed', 64),
    ('incorrect_stadium_selection', 'Incorrect Stadium Selection', 'matchday', 'fine', 2500000, 'fixed', 65),
    ('incorrect_season_selection', 'Incorrect Season Selection', 'matchday', 'fine', 2500000, 'fixed', 66),
    ('incorrect_pitch_conditions', 'Incorrect Pitch Conditions', 'matchday', 'fine', 10000000, 'fixed', 67),
    ('incorrect_weather_conditions', 'Incorrect Weather Conditions', 'matchday', 'fine', 10000000, 'fixed', 68),
    ('incorrect_club_selection', 'Incorrect Club Selection', 'matchday', 'fine', 2500000, 'fixed', 69),
    ('incorrect_kit_selection', 'Incorrect Kit Selection', 'matchday', 'fine', 2500000, 'fixed', 70),
    ('incorrect_club_name_abbr', 'Incorrect Club Name & Abbreviation', 'matchday', 'fine', 1000000, 'fixed', 71),
    ('incorrect_custom_stadium', 'Incorrect Custom Stadium Settings', 'matchday', 'fine', 1000000, 'fixed', 72),
    ('non_display_attack_defence', 'Non Display Attack/Defence Level', 'matchday', 'fine', 10000000, 'fixed', 73),
    ('non_display_scoreboard', 'Non Display Scoreboard', 'matchday', 'fine', 5000000, 'fixed', 74),
    ('non_display_sub_tactic', 'Non Display Sub Tactic', 'matchday', 'fine', 10000000, 'fixed', 75),
    ('red_blue_before_80', 'Red/Blue before 80th Minute', 'matchday', 'fine', 10000000, 'fixed', 76),
    ('red_blue_et_first_half', 'Red/Blue 1st half of extra time', 'matchday', 'fine', 10000000, 'fixed', 77),
    ('double_red_blue', 'Double Red/Blue at any point', 'matchday', 'fine', 10000000, 'fixed', 78),
    ('no_gk_fine', 'No GK Fine', 'matchday', 'fine', 5000000, 'fixed', 79),
    ('breach_squad_30_max', 'Breach of 30 Squad Limit', 'squad', 'fine', 20000000, 'fixed', 80),
    ('breach_squad_24_min', 'Breach of 24 Squad Minimum', 'squad', 'fine', 5000000, 'fixed', 81),
    ('breach_squad_28_max', 'Breach of 28 Squad Maximum', 'squad', 'fine', 5000000, 'fixed', 82),
    ('ineligible_manager', 'Ineligible Manager', 'manager', 'fine', 10000000, 'fixed', 90),
    ('incorrect_results_format', 'Incorrect Results Format', 'matchday', 'fine', 1000000, 'fixed', 91),
    ('withdraw_from_sale', 'Withdraw from Sale', 'transfer', 'fine', 30000000, 'fixed', 100),
    ('withdraw_bid', 'Withdraw bid', 'transfer', 'fine', 15000000, 'fixed', 101),
    ('incorrect_transfer_post', 'Incorrect Transfer Post', 'transfer', 'fine', 2500000, 'fixed', 102),
    ('auction_bidding_over_ratio', 'Auction Bidding Over Ratio', 'transfer', 'fine', 10000000, 'fixed', 103),
    ('illegal_match_termination', 'Illegal Match Termination', 'matchday', 'fine', 10000000, 'fixed', 104),
    ('league_compensation', 'League Compensation', 'compensation', 'compensation', 2500000, 'fixed', 200),
    ('sack_mgr', 'SACK MGR', 'manager', 'compensation', NULL, 'manual', 201),
    ('rls_mgr', 'RLS MGR', 'manager', 'compensation', NULL, 'manual', 202)
  ON CONFLICT (code) DO UPDATE
  SET
    label = excluded.label,
    category = excluded.category,
    direction = excluded.direction,
    amount = excluded.amount,
    amount_mode = excluded.amount_mode,
    sort_order = excluded.sort_order,
    updated_at = now();

  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$function$;

GRANT SELECT ON public.competition_fine_tariff TO authenticated;
GRANT SELECT ON public.competition_fine_applied TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_save_fine_tariff(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_apply_fine(text, text, numeric, text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_seed_fine_tariffs() TO authenticated;
