-- =============================================================================
-- GPSL International football — World Cup, nations, owner draft, player caps
-- Run once after competition_phase0.sql
-- v1 foundation: schema, owner nation draft, squads, cycle structure
--
-- Re-run on live DB: this file drops/recreates international_owner_draft_order
-- with the foundation return type. Run competition_owner_ranking.sql (or
-- patches/owner_ranking_owner_tag.sql) afterward to restore rolling rankings
-- and owner_tag columns. For nation-name-only fixes use
-- patches/international_nation_gpdb_names.sql instead of re-running this file.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Nations (60 FIFA-style teams)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_nations (
  code text PRIMARY KEY CHECK (code ~ '^[A-Z]{3}$'),
  name text NOT NULL,
  flag_emoji text NOT NULL DEFAULT '🏳️',
  seed_rank smallint NOT NULL CHECK (seed_rank >= 1 AND seed_rank <= 32767),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Owner rank points (admin sets; draft order = rank_points DESC, club name)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_owner_rank (
  club_short_name text PRIMARY KEY REFERENCES public."Clubs" ("ShortName") ON DELETE CASCADE,
  rank_points numeric(10, 2) NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Owner ↔ nation assignments (history kept; one active per club)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_owner_nations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName") ON DELETE CASCADE,
  nation_code text NOT NULL REFERENCES public.international_nations (code),
  cycle_id bigint,
  selection_phase text NOT NULL DEFAULT 'initial'
    CHECK (selection_phase IN ('initial', 'post_world_cup', 'admin')),
  is_active boolean NOT NULL DEFAULT true,
  locked_until_cycle_id bigint,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  released_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS international_owner_nations_one_active_club_idx
  ON public.international_owner_nations (club_short_name)
  WHERE is_active = true;

CREATE UNIQUE INDEX IF NOT EXISTS international_owner_nations_one_active_nation_idx
  ON public.international_owner_nations (nation_code)
  WHERE is_active = true;

-- ---------------------------------------------------------------------------
-- Nation selection windows (draft pick period)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_selection_windows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phase text NOT NULL CHECK (phase IN ('initial', 'post_world_cup')),
  is_open boolean NOT NULL DEFAULT false,
  opens_at timestamptz,
  closes_at timestamptz,
  current_pick_rank smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- World Cup cycles (qualifying 2 seasons → finals between S4–5, S8–9, …)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_wc_cycles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_no smallint NOT NULL UNIQUE CHECK (cycle_no >= 1),
  label text NOT NULL,
  qual_season_id_1 bigint REFERENCES public.competition_seasons (id),
  qual_season_id_2 bigint REFERENCES public.competition_seasons (id),
  finals_after_season_id bigint REFERENCES public.competition_seasons (id),
  status text NOT NULL DEFAULT 'setup'
    CHECK (status IN ('setup', 'qualifying', 'finals', 'complete')),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.international_owner_nations
  ADD COLUMN IF NOT EXISTS cycle_id bigint REFERENCES public.international_wc_cycles (id);

-- ---------------------------------------------------------------------------
-- Qualifying: 12 groups × 5 nations
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_qual_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id bigint NOT NULL REFERENCES public.international_wc_cycles (id) ON DELETE CASCADE,
  group_code text NOT NULL CHECK (group_code ~ '^[A-L]$'),
  CONSTRAINT international_qual_groups_unique UNIQUE (cycle_id, group_code)
);

CREATE TABLE IF NOT EXISTS public.international_qual_group_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.international_qual_groups (id) ON DELETE CASCADE,
  nation_code text NOT NULL REFERENCES public.international_nations (code),
  played smallint NOT NULL DEFAULT 0,
  won smallint NOT NULL DEFAULT 0,
  drawn smallint NOT NULL DEFAULT 0,
  lost smallint NOT NULL DEFAULT 0,
  goals_for smallint NOT NULL DEFAULT 0,
  goals_against smallint NOT NULL DEFAULT 0,
  points smallint NOT NULL DEFAULT 0,
  third_place_rank smallint,
  qualified boolean NOT NULL DEFAULT false,
  CONSTRAINT international_qual_group_members_unique UNIQUE (group_id, nation_code)
);

-- ---------------------------------------------------------------------------
-- Finals: 8 groups × 4 → 32 teams, top 2 per group to R16
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_finals_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id bigint NOT NULL REFERENCES public.international_wc_cycles (id) ON DELETE CASCADE,
  group_code text NOT NULL CHECK (group_code ~ '^[A-H]$'),
  CONSTRAINT international_finals_groups_unique UNIQUE (cycle_id, group_code)
);

CREATE TABLE IF NOT EXISTS public.international_finals_group_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.international_finals_groups (id) ON DELETE CASCADE,
  nation_code text NOT NULL REFERENCES public.international_nations (code),
  played smallint NOT NULL DEFAULT 0,
  won smallint NOT NULL DEFAULT 0,
  drawn smallint NOT NULL DEFAULT 0,
  lost smallint NOT NULL DEFAULT 0,
  goals_for smallint NOT NULL DEFAULT 0,
  goals_against smallint NOT NULL DEFAULT 0,
  points smallint NOT NULL DEFAULT 0,
  qualified_knockout boolean NOT NULL DEFAULT false,
  CONSTRAINT international_finals_group_members_unique UNIQUE (group_id, nation_code)
);

-- ---------------------------------------------------------------------------
-- Knockout bracket (R16 → QF → SF → Final)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_knockout_nodes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id bigint NOT NULL REFERENCES public.international_wc_cycles (id) ON DELETE CASCADE,
  stage text NOT NULL CHECK (stage IN ('r16', 'qf', 'sf', 'final')),
  match_no smallint NOT NULL,
  nation_a text REFERENCES public.international_nations (code),
  nation_b text REFERENCES public.international_nations (code),
  goals_a smallint,
  goals_b smallint,
  winner_nation text REFERENCES public.international_nations (code),
  played boolean NOT NULL DEFAULT false,
  CONSTRAINT international_knockout_nodes_unique UNIQUE (cycle_id, stage, match_no)
);

-- ---------------------------------------------------------------------------
-- International fixtures (separate from club competition_fixtures)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_fixtures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id bigint NOT NULL REFERENCES public.international_wc_cycles (id) ON DELETE CASCADE,
  season_id bigint REFERENCES public.competition_seasons (id),
  phase text NOT NULL CHECK (phase IN ('qualifying', 'finals_group', 'knockout')),
  group_id bigint,
  knockout_node_id bigint REFERENCES public.international_knockout_nodes (id),
  home_nation text NOT NULL REFERENCES public.international_nations (code),
  away_nation text NOT NULL REFERENCES public.international_nations (code),
  home_goals smallint,
  away_goals smallint,
  played boolean NOT NULL DEFAULT false,
  played_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Squad call-ups (populates national team squad view)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_squad_callups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nation_code text NOT NULL REFERENCES public.international_nations (code),
  player_id text NOT NULL,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  cycle_id bigint REFERENCES public.international_wc_cycles (id),
  called_at timestamptz NOT NULL DEFAULT now(),
  released_at timestamptz,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT international_squad_callups_unique UNIQUE (nation_code, player_id)
);

CREATE INDEX IF NOT EXISTS international_squad_callups_nation_active_idx
  ON public.international_squad_callups (nation_code)
  WHERE is_active = true;

-- ---------------------------------------------------------------------------
-- Lifetime international player stats (never reset)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_player_career (
  player_id text PRIMARY KEY,
  caps integer NOT NULL DEFAULT 0 CHECK (caps >= 0),
  goals integer NOT NULL DEFAULT 0 CHECK (goals >= 0),
  assists integer NOT NULL DEFAULT 0 CHECK (assists >= 0),
  potm integer NOT NULL DEFAULT 0 CHECK (potm >= 0),
  rating_sum numeric(12, 2) NOT NULL DEFAULT 0,
  rating_count integer NOT NULL DEFAULT 0 CHECK (rating_count >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_season_ordinal(p_season_id bigint)
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT s.rn::integer
  FROM (
    SELECT id, row_number() OVER (ORDER BY id) AS rn
    FROM public.competition_seasons
  ) s
  WHERE s.id = p_season_id;
$$;

CREATE OR REPLACE FUNCTION public.international_my_nation_code()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT ion.nation_code
  FROM public.international_owner_nations ion
  JOIN public."Clubs" c ON c."ShortName" = ion.club_short_name
  WHERE ion.is_active = true
    AND c.owner_id = auth.uid()
  LIMIT 1;
$$;

-- Foundation draft order (superseded by competition_owner_ranking.sql on live systems).
-- Drop first — return type differs after owner ranking patches (owner_id, owner_tag, …).
DROP VIEW IF EXISTS public.international_owner_rank_public;
DROP VIEW IF EXISTS public.international_selection_public;
DROP FUNCTION IF EXISTS public.international_owner_draft_order();

CREATE OR REPLACE FUNCTION public.international_owner_draft_order()
RETURNS TABLE (
  pick_order smallint,
  club_short_name text,
  club_name text,
  rank_points numeric,
  nation_code text,
  nation_name text,
  flag_emoji text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    row_number() OVER (
      ORDER BY coalesce(r.rank_points, 0) DESC, c."ShortName"
    )::smallint AS pick_order,
    c."ShortName" AS club_short_name,
    c."Club" AS club_name,
    coalesce(r.rank_points, 0) AS rank_points,
    ion.nation_code,
    n.name AS nation_name,
    n.flag_emoji
  FROM public."Clubs" c
  LEFT JOIN public.international_owner_rank r ON r.club_short_name = c."ShortName"
  LEFT JOIN public.international_owner_nations ion
    ON ion.club_short_name = c."ShortName" AND ion.is_active = true
  LEFT JOIN public.international_nations n ON n.code = ion.nation_code
  WHERE c.owner_id IS NOT NULL
  ORDER BY pick_order;
$$;

-- ---------------------------------------------------------------------------
-- Seed 60 nations
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.international_seed_nations()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_count integer := 0;
BEGIN
  IF NOT public.is_gpsl_admin() AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  INSERT INTO public.international_nations (code, name, flag_emoji, seed_rank) VALUES
    ('ARG', 'Argentina', '🇦🇷', 1),
    ('FRA', 'France', '🇫🇷', 2),
    ('BRA', 'Brazil', '🇧🇷', 3),
    ('ENG', 'England', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 4),
    ('BEL', 'Belgium', '🇧🇪', 5),
    ('POR', 'Portugal', '🇵🇹', 6),
    ('NED', 'Netherlands', '🇳🇱', 7),
    ('ESP', 'Spain', '🇪🇸', 8),
    ('ITA', 'Italy', '🇮🇹', 9),
    ('CRO', 'Croatia', '🇭🇷', 10),
    ('URU', 'Uruguay', '🇺🇾', 11),
    ('MAR', 'Morocco', '🇲🇦', 12),
    ('COL', 'Colombia', '🇨🇴', 13),
    ('GER', 'Germany', '🇩🇪', 14),
    ('MEX', 'Mexico', '🇲🇽', 15),
    ('USA', 'United States', '🇺🇸', 16),
    ('SUI', 'Switzerland', '🇨🇭', 17),
    ('JPN', 'Japan', '🇯🇵', 18),
    ('SEN', 'Senegal', '🇸🇳', 19),
    ('IRN', 'IR Iran', '🇮🇷', 20),
    ('DEN', 'Denmark', '🇩🇰', 21),
    ('KOR', 'Korea Republic', '🇰🇷', 22),
    ('AUS', 'Australia', '🇦🇺', 23),
    ('UKR', 'Ukraine', '🇺🇦', 24),
    ('TUR', 'Türkiye', '🇹🇷', 25),
    ('ECU', 'Ecuador', '🇪🇨', 26),
    ('POL', 'Poland', '🇵🇱', 27),
    ('SRB', 'Serbia', '🇷🇸', 28),
    ('WAL', 'Wales', '🏴󠁧󠁢󠁷󠁬󠁳󠁿', 29),
    ('CAN', 'Canada', '🇨🇦', 30),
    ('GHA', 'Ghana', '🇬🇭', 31),
    ('NOR', 'Norway', '🇳🇴', 32),
    ('PAR', 'Paraguay', '🇵🇾', 33),
    ('CRC', 'Costa Rica', '🇨🇷', 34),
    ('EGY', 'Egypt', '🇪🇬', 35),
    ('ALG', 'Algeria', '🇩🇿', 36),
    ('SCO', 'Scotland', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 37),
    ('AUT', 'Austria', '🇦🇹', 38),
    ('HUN', 'Hungary', '🇭🇺', 39),
    ('CZE', 'Czechia', '🇨🇿', 40),
    ('NGA', 'Nigeria', '🇳🇬', 41),
    ('PAN', 'Panama', '🇵🇦', 42),
    ('TUN', 'Tunisia', '🇹🇳', 43),
    ('PER', 'Peru', '🇵🇪', 44),
    ('CHI', 'Chile', '🇨🇱', 45),
    ('ROU', 'Romania', '🇷🇴', 46),
    ('SVK', 'Slovakia', '🇸🇰', 47),
    ('SWE', 'Sweden', '🇸🇪', 48),
    ('FIN', 'Finland', '🇫🇮', 49),
    ('IRL', 'Republic of Ireland', '🇮🇪', 50),
    ('CMR', 'Cameroon', '🇨🇲', 51),
    ('RSA', 'South Africa', '🇿🇦', 52),
    ('JAM', 'Jamaica', '🇯🇲', 53),
    ('BOL', 'Bolivia', '🇧🇴', 54),
    ('VEN', 'Venezuela', '🇻🇪', 55),
    ('IRQ', 'Iraq', '🇮🇶', 56),
    ('QAT', 'Qatar', '🇶🇦', 57),
    ('KSA', 'Saudi Arabia', '🇸🇦', 58),
    ('NZL', 'New Zealand', '🇳🇿', 59),
    ('CHN', 'China PR', '🇨🇳', 60)
  ON CONFLICT (code) DO UPDATE
  SET name = EXCLUDED.name,
      flag_emoji = EXCLUDED.flag_emoji,
      seed_rank = EXCLUDED.seed_rank,
      active = true;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_sync_owner_ranks()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_count integer := 0;
BEGIN
  IF NOT public.is_gpsl_admin() AND current_user NOT IN ('postgres', 'supabase_admin', 'service_role') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  INSERT INTO public.international_owner_rank (club_short_name, rank_points)
  SELECT c."ShortName", 0
  FROM public."Clubs" c
  WHERE c.owner_id IS NOT NULL
  ON CONFLICT (club_short_name) DO NOTHING;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_admin_set_rank_points(
  p_club text,
  p_points numeric
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  INSERT INTO public.international_owner_rank (club_short_name, rank_points, updated_at)
  VALUES (btrim(p_club), coalesce(p_points, 0), now())
  ON CONFLICT (club_short_name) DO UPDATE
  SET rank_points = EXCLUDED.rank_points,
      updated_at = now();
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_admin_assign_nation(
  p_club text,
  p_nation_code text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cycle_id bigint;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT id INTO v_cycle_id
  FROM public.international_wc_cycles
  ORDER BY cycle_no DESC
  LIMIT 1;

  UPDATE public.international_owner_nations
  SET is_active = false,
      released_at = now()
  WHERE club_short_name = btrim(p_club)
    AND is_active = true;

  UPDATE public.international_owner_nations
  SET is_active = false,
      released_at = now()
  WHERE nation_code = btrim(upper(p_nation_code))
    AND is_active = true;

  INSERT INTO public.international_owner_nations (
    club_short_name,
    nation_code,
    cycle_id,
    selection_phase,
    is_active,
    locked_until_cycle_id
  )
  VALUES (
    btrim(p_club),
    btrim(upper(p_nation_code)),
    v_cycle_id,
    'admin',
    true,
    v_cycle_id
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_admin_clear_nation_assignments()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_count integer := 0;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  UPDATE public.international_selection_windows
  SET is_open = false,
      closes_at = coalesce(closes_at, now())
  WHERE is_open = true;

  UPDATE public.international_owner_nations
  SET is_active = false,
      released_at = now()
  WHERE is_active = true;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_admin_open_selection(p_phase text)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint;
  v_phase text := coalesce(nullif(btrim(p_phase), ''), 'initial');
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_phase NOT IN ('initial', 'post_world_cup') THEN
    RAISE EXCEPTION 'Invalid phase';
  END IF;

  UPDATE public.international_selection_windows
  SET is_open = false,
      closes_at = coalesce(closes_at, now())
  WHERE is_open = true;

  INSERT INTO public.international_selection_windows (phase, is_open, opens_at, current_pick_rank)
  VALUES (v_phase, true, now(), 1)
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_admin_close_selection()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  UPDATE public.international_selection_windows
  SET is_open = false,
      closes_at = now()
  WHERE is_open = true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_claim_nation(p_nation_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_window record;
  v_my_pick smallint;
  v_current_pick smallint;
  v_nation text := btrim(upper(p_nation_code));
  v_cycle_id bigint;
  v_next_pick smallint;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to your account';
  END IF;

  SELECT * INTO v_window
  FROM public.international_selection_windows
  WHERE is_open = true
  ORDER BY id DESC
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nation selection is not open';
  END IF;

  SELECT pick_order INTO v_my_pick
  FROM public.international_owner_draft_order()
  WHERE club_short_name = v_club;

  IF v_my_pick IS NULL THEN
    RAISE EXCEPTION 'Your club is not in the owner draft order';
  END IF;

  v_current_pick := v_window.current_pick_rank;

  IF v_my_pick <> v_current_pick THEN
    RAISE EXCEPTION 'Not your pick yet (currently pick #% — you are #%).', v_current_pick, v_my_pick;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.international_nations n
    WHERE n.code = v_nation AND n.active = true
  ) THEN
    RAISE EXCEPTION 'Nation not found';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.international_owner_nations ion
    WHERE ion.nation_code = v_nation AND ion.is_active = true
  ) THEN
    RAISE EXCEPTION 'Nation already taken';
  END IF;

  SELECT id INTO v_cycle_id
  FROM public.international_wc_cycles
  ORDER BY cycle_no DESC
  LIMIT 1;

  UPDATE public.international_owner_nations
  SET is_active = false,
      released_at = now()
  WHERE club_short_name = v_club
    AND is_active = true;

  INSERT INTO public.international_owner_nations (
    club_short_name,
    nation_code,
    cycle_id,
    selection_phase,
    is_active,
    locked_until_cycle_id
  )
  VALUES (
    v_club,
    v_nation,
    v_cycle_id,
    v_window.phase,
    true,
    v_cycle_id
  );

  SELECT coalesce(min(pick_order), 61)::smallint INTO v_next_pick
  FROM public.international_owner_draft_order() d
  WHERE NOT EXISTS (
    SELECT 1 FROM public.international_owner_nations ion
    WHERE ion.club_short_name = d.club_short_name
      AND ion.is_active = true
  );

  IF v_next_pick >= 61 THEN
    UPDATE public.international_selection_windows
    SET is_open = false,
        closes_at = now()
    WHERE id = v_window.id;
  ELSE
    UPDATE public.international_selection_windows
    SET current_pick_rank = v_next_pick
    WHERE id = v_window.id;
  END IF;

  RETURN jsonb_build_object(
    'club', v_club,
    'nation', v_nation,
    'pick', v_my_pick,
    'next_pick', v_next_pick
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_call_up_player(p_player_id text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_nation text := public.international_my_nation_code();
  v_cycle_id bigint;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to your account';
  END IF;

  IF v_nation IS NULL THEN
    RAISE EXCEPTION 'You have not been assigned a national team';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public."Players" p
    WHERE p."Konami_ID"::text = btrim(p_player_id)
      AND p."Contracted_Team" = v_club
  ) THEN
    RAISE EXCEPTION 'Player not in your club squad';
  END IF;

  SELECT id INTO v_cycle_id
  FROM public.international_wc_cycles
  ORDER BY cycle_no DESC
  LIMIT 1;

  UPDATE public.international_squad_callups
  SET is_active = false,
      released_at = now()
  WHERE player_id = btrim(p_player_id)
    AND is_active = true;

  INSERT INTO public.international_squad_callups (
    nation_code,
    player_id,
    club_short_name,
    cycle_id,
    is_active
  )
  VALUES (
    v_nation,
    btrim(p_player_id),
    v_club,
    v_cycle_id,
    true
  )
  ON CONFLICT (nation_code, player_id) DO UPDATE
  SET is_active = true,
      released_at = NULL,
      called_at = now(),
      club_short_name = EXCLUDED.club_short_name,
      cycle_id = EXCLUDED.cycle_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.international_release_callup(p_player_id text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_nation text := public.international_my_nation_code();
BEGIN
  IF v_nation IS NULL THEN
    RAISE EXCEPTION 'You have not been assigned a national team';
  END IF;

  UPDATE public.international_squad_callups
  SET is_active = false,
      released_at = now()
  WHERE nation_code = v_nation
    AND player_id = btrim(p_player_id)
    AND is_active = true;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public views
-- ---------------------------------------------------------------------------

DROP VIEW IF EXISTS public.international_nations_public;
CREATE VIEW public.international_nations_public
WITH (security_invoker = false)
AS
SELECT
  n.code,
  n.name,
  n.flag_emoji,
  n.seed_rank,
  ion.club_short_name AS owner_club,
  c."Club" AS owner_club_name,
  coalesce(nullif(btrim(c.owner), ''), c."ShortName") AS owner_tag,
  (ion.id IS NOT NULL) AS is_taken
FROM public.international_nations n
LEFT JOIN public.international_owner_nations ion
  ON ion.nation_code = n.code AND ion.is_active = true
LEFT JOIN public."Clubs" c ON c."ShortName" = ion.club_short_name
WHERE n.active = true
ORDER BY n.seed_rank;

DROP VIEW IF EXISTS public.international_my_nation_public;
CREATE VIEW public.international_my_nation_public
WITH (security_invoker = true)
AS
SELECT
  n.code,
  n.name,
  n.flag_emoji,
  n.seed_rank,
  ion.club_short_name,
  ion.assigned_at,
  ion.selection_phase,
  ion.locked_until_cycle_id,
  wc.label AS cycle_label
FROM public.international_owner_nations ion
JOIN public.international_nations n ON n.code = ion.nation_code
JOIN public."Clubs" c ON c."ShortName" = ion.club_short_name
LEFT JOIN public.international_wc_cycles wc ON wc.id = ion.cycle_id
WHERE ion.is_active = true
  AND c.owner_id = auth.uid();

DROP VIEW IF EXISTS public.international_owner_rank_public;
CREATE VIEW public.international_owner_rank_public
WITH (security_invoker = false)
AS
SELECT * FROM public.international_owner_draft_order();

DROP VIEW IF EXISTS public.international_selection_public;
CREATE VIEW public.international_selection_public
WITH (security_invoker = false)
AS
SELECT
  w.id,
  w.phase,
  w.is_open,
  w.opens_at,
  w.closes_at,
  w.current_pick_rank,
  (
    SELECT d.club_short_name
    FROM public.international_owner_draft_order() d
    WHERE d.pick_order = w.current_pick_rank
    LIMIT 1
  ) AS current_pick_club,
  (
    SELECT count(*)::integer
    FROM public.international_owner_nations ion
    WHERE ion.is_active = true
  ) AS nations_assigned
FROM public.international_selection_windows w
WHERE w.is_open = true
ORDER BY w.id DESC
LIMIT 1;

DROP VIEW IF EXISTS public.international_qual_standings_public;
CREATE VIEW public.international_qual_standings_public
WITH (security_invoker = false)
AS
SELECT
  wc.cycle_no,
  wc.label AS cycle_label,
  g.group_code,
  m.nation_code,
  n.name AS nation_name,
  n.flag_emoji,
  m.played,
  m.won,
  m.drawn,
  m.lost,
  m.goals_for,
  m.goals_against,
  m.goals_for - m.goals_against AS goal_diff,
  m.points,
  m.third_place_rank,
  m.qualified
FROM public.international_qual_group_members m
JOIN public.international_qual_groups g ON g.id = m.group_id
JOIN public.international_wc_cycles wc ON wc.id = g.cycle_id
JOIN public.international_nations n ON n.code = m.nation_code
ORDER BY wc.cycle_no, g.group_code, m.points DESC, goal_diff DESC;

DROP VIEW IF EXISTS public.international_finals_standings_public;
CREATE VIEW public.international_finals_standings_public
WITH (security_invoker = false)
AS
SELECT
  wc.cycle_no,
  wc.label AS cycle_label,
  g.group_code,
  m.nation_code,
  n.name AS nation_name,
  n.flag_emoji,
  m.played,
  m.won,
  m.drawn,
  m.lost,
  m.goals_for,
  m.goals_against,
  m.goals_for - m.goals_against AS goal_diff,
  m.points,
  m.qualified_knockout
FROM public.international_finals_group_members m
JOIN public.international_finals_groups g ON g.id = m.group_id
JOIN public.international_wc_cycles wc ON wc.id = g.cycle_id
JOIN public.international_nations n ON n.code = m.nation_code
ORDER BY wc.cycle_no, g.group_code, m.points DESC, goal_diff DESC;

DROP VIEW IF EXISTS public.international_squad_public;
CREATE VIEW public.international_squad_public
WITH (security_invoker = false)
AS
SELECT
  sc.nation_code,
  n.name AS nation_name,
  n.flag_emoji,
  sc.player_id,
  p."Name" AS player_name,
  p."Position" AS player_position,
  p."Age" AS player_age,
  sc.club_short_name,
  sc.called_at,
  coalesce(ipc.caps, 0) AS intl_caps,
  coalesce(ipc.goals, 0) AS intl_goals,
  coalesce(ipc.assists, 0) AS intl_assists,
  coalesce(ipc.potm, 0) AS intl_potm,
  CASE
    WHEN coalesce(ipc.rating_count, 0) > 0
      THEN round(ipc.rating_sum / ipc.rating_count, 2)
    ELSE NULL
  END AS intl_avg_rating
FROM public.international_squad_callups sc
JOIN public.international_nations n ON n.code = sc.nation_code
LEFT JOIN public."Players" p ON p."Konami_ID"::text = sc.player_id
LEFT JOIN public.international_player_career ipc ON ipc.player_id = sc.player_id
WHERE sc.is_active = true;

DROP VIEW IF EXISTS public.international_player_career_public;
CREATE VIEW public.international_player_career_public
WITH (security_invoker = false)
AS
SELECT
  ipc.player_id,
  p."Name" AS player_name,
  ipc.caps,
  ipc.goals,
  ipc.assists,
  ipc.potm,
  CASE
    WHEN ipc.rating_count > 0 THEN round(ipc.rating_sum / ipc.rating_count, 2)
    ELSE NULL
  END AS avg_rating,
  ipc.updated_at
FROM public.international_player_career ipc
LEFT JOIN public."Players" p ON p."Konami_ID"::text = ipc.player_id;

DROP VIEW IF EXISTS public.international_wc_cycle_public;
CREATE VIEW public.international_wc_cycle_public
WITH (security_invoker = false)
AS
SELECT
  wc.id,
  wc.cycle_no,
  wc.label,
  wc.status,
  s1.label AS qual_season_1_label,
  s2.label AS qual_season_2_label,
  sf.label AS finals_after_season_label,
  public.competition_season_ordinal(wc.finals_after_season_id) AS finals_after_season_ordinal
FROM public.international_wc_cycles wc
LEFT JOIN public.competition_seasons s1 ON s1.id = wc.qual_season_id_1
LEFT JOIN public.competition_seasons s2 ON s2.id = wc.qual_season_id_2
LEFT JOIN public.competition_seasons sf ON sf.id = wc.finals_after_season_id
ORDER BY wc.cycle_no DESC;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.international_nations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_owner_rank ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_owner_nations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_selection_windows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_wc_cycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_qual_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_qual_group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_finals_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_finals_group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_knockout_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_fixtures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_squad_callups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.international_player_career ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS international_nations_read ON public.international_nations;
CREATE POLICY international_nations_read ON public.international_nations
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS international_owner_rank_read ON public.international_owner_rank;
CREATE POLICY international_owner_rank_read ON public.international_owner_rank
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS international_owner_rank_admin ON public.international_owner_rank;
CREATE POLICY international_owner_rank_admin ON public.international_owner_rank
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS international_owner_nations_read ON public.international_owner_nations;
CREATE POLICY international_owner_nations_read ON public.international_owner_nations
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS international_owner_nations_admin ON public.international_owner_nations;
CREATE POLICY international_owner_nations_admin ON public.international_owner_nations
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS international_selection_read ON public.international_selection_windows;
CREATE POLICY international_selection_read ON public.international_selection_windows
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS international_selection_admin ON public.international_selection_windows;
CREATE POLICY international_selection_admin ON public.international_selection_windows
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS international_wc_read ON public.international_wc_cycles;
CREATE POLICY international_wc_read ON public.international_wc_cycles
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS international_wc_admin ON public.international_wc_cycles;
CREATE POLICY international_wc_admin ON public.international_wc_cycles
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS international_qual_read ON public.international_qual_groups;
CREATE POLICY international_qual_read ON public.international_qual_groups
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS international_qual_admin ON public.international_qual_groups;
CREATE POLICY international_qual_admin ON public.international_qual_groups
  FOR ALL TO authenticated USING (public.is_gpsl_admin()) WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS international_qual_members_read ON public.international_qual_group_members;
CREATE POLICY international_qual_members_read ON public.international_qual_group_members
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS international_qual_members_admin ON public.international_qual_group_members;
CREATE POLICY international_qual_members_admin ON public.international_qual_group_members
  FOR ALL TO authenticated USING (public.is_gpsl_admin()) WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS international_finals_read ON public.international_finals_groups;
CREATE POLICY international_finals_read ON public.international_finals_groups
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS international_finals_admin ON public.international_finals_groups;
CREATE POLICY international_finals_admin ON public.international_finals_groups
  FOR ALL TO authenticated USING (public.is_gpsl_admin()) WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS international_finals_members_read ON public.international_finals_group_members;
CREATE POLICY international_finals_members_read ON public.international_finals_group_members
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS international_finals_members_admin ON public.international_finals_group_members;
CREATE POLICY international_finals_members_admin ON public.international_finals_group_members
  FOR ALL TO authenticated USING (public.is_gpsl_admin()) WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS international_knockout_read ON public.international_knockout_nodes;
CREATE POLICY international_knockout_read ON public.international_knockout_nodes
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS international_knockout_admin ON public.international_knockout_nodes;
CREATE POLICY international_knockout_admin ON public.international_knockout_nodes
  FOR ALL TO authenticated USING (public.is_gpsl_admin()) WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS international_fixtures_read ON public.international_fixtures;
CREATE POLICY international_fixtures_read ON public.international_fixtures
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS international_fixtures_admin ON public.international_fixtures;
CREATE POLICY international_fixtures_admin ON public.international_fixtures
  FOR ALL TO authenticated USING (public.is_gpsl_admin()) WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS international_squad_read ON public.international_squad_callups;
CREATE POLICY international_squad_read ON public.international_squad_callups
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS international_squad_owner ON public.international_squad_callups;
CREATE POLICY international_squad_owner ON public.international_squad_callups
  FOR ALL TO authenticated
  USING (
    nation_code = public.international_my_nation_code()
    OR public.is_gpsl_admin()
  )
  WITH CHECK (
    nation_code = public.international_my_nation_code()
    OR public.is_gpsl_admin()
  );

DROP POLICY IF EXISTS international_player_career_read ON public.international_player_career;
CREATE POLICY international_player_career_read ON public.international_player_career
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS international_player_career_admin ON public.international_player_career;
CREATE POLICY international_player_career_admin ON public.international_player_career
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.international_nations TO authenticated;
GRANT SELECT ON public.international_owner_rank TO authenticated;
GRANT SELECT ON public.international_owner_nations TO authenticated;
GRANT SELECT ON public.international_selection_windows TO authenticated;
GRANT SELECT ON public.international_wc_cycles TO authenticated;
GRANT SELECT ON public.international_qual_groups TO authenticated;
GRANT SELECT ON public.international_qual_group_members TO authenticated;
GRANT SELECT ON public.international_finals_groups TO authenticated;
GRANT SELECT ON public.international_finals_group_members TO authenticated;
GRANT SELECT ON public.international_knockout_nodes TO authenticated;
GRANT SELECT ON public.international_fixtures TO authenticated;
GRANT SELECT ON public.international_squad_callups TO authenticated;
GRANT SELECT ON public.international_player_career TO authenticated;

GRANT SELECT ON public.international_nations_public TO authenticated;
GRANT SELECT ON public.international_my_nation_public TO authenticated;
GRANT SELECT ON public.international_owner_rank_public TO authenticated;
GRANT SELECT ON public.international_selection_public TO authenticated;
GRANT SELECT ON public.international_qual_standings_public TO authenticated;
GRANT SELECT ON public.international_finals_standings_public TO authenticated;
GRANT SELECT ON public.international_squad_public TO authenticated;
GRANT SELECT ON public.international_player_career_public TO authenticated;
GRANT SELECT ON public.international_wc_cycle_public TO authenticated;

GRANT EXECUTE ON FUNCTION public.international_seed_nations() TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_sync_owner_ranks() TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_admin_set_rank_points(text, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_admin_assign_nation(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_admin_clear_nation_assignments() TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_admin_open_selection(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_admin_close_selection() TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_claim_nation(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_call_up_player(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.international_release_callup(text) TO authenticated;

SELECT public.international_seed_nations();
SELECT public.international_sync_owner_ranks();

NOTIFY pgrst, 'reload schema';
