-- =============================================================================
-- GPSL Competition — Phase 1: 38-match league calendar + round-robin generator
-- Requires: competition_phase0.sql
-- Spec: docs/competition-spec.md (Aug 3 + 8×4 + May 3 = 38 matchdays)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Fixtures table
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_fixtures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  division text NOT NULL CHECK (division IN ('superleague', 'championship_a', 'championship_b')),
  competition_type text NOT NULL DEFAULT 'league' CHECK (competition_type IN ('league')),
  matchday smallint NOT NULL CHECK (matchday >= 1 AND matchday <= 38),
  gpsl_month text NOT NULL CHECK (
    gpsl_month IN (
      'august', 'september', 'october', 'november', 'december',
      'january', 'february', 'march', 'april', 'may'
    )
  ),
  week_in_month smallint NOT NULL CHECK (week_in_month >= 1 AND week_in_month <= 4),
  home_club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  away_club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  weather text,
  home_goals smallint CHECK (home_goals IS NULL OR home_goals >= 0),
  away_goals smallint CHECK (away_goals IS NULL OR away_goals >= 0),
  status text NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'played', 'cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_fixtures_clubs_diff CHECK (
    home_club_short_name <> away_club_short_name
  )
  -- League pair uniqueness: see competition_fixtures_unique_league_pair_idx
  -- (partial index). Do not UNIQUE across cups on matchday alone — cups share
  -- division='cup' and matchday=round_no across cup_code.
);

CREATE INDEX IF NOT EXISTS competition_fixtures_season_div_md_idx
  ON public.competition_fixtures (season_id, division, matchday);

CREATE INDEX IF NOT EXISTS competition_fixtures_season_club_idx
  ON public.competition_fixtures (season_id, home_club_short_name, away_club_short_name);

CREATE UNIQUE INDEX IF NOT EXISTS competition_fixtures_unique_league_pair_idx
  ON public.competition_fixtures (
    season_id,
    division,
    matchday,
    home_club_short_name,
    away_club_short_name
  )
  WHERE competition_type = 'league';

-- ---------------------------------------------------------------------------
-- Calendar + weather helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_matchday_calendar(p_matchday integer)
RETURNS TABLE (gpsl_month text, week_in_month smallint)
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT
    CASE
      WHEN p_matchday <= 3 THEN 'august'
      WHEN p_matchday <= 35 THEN (
        ARRAY[
          'september', 'october', 'november', 'december',
          'january', 'february', 'march', 'april'
        ]
      )[1 + (p_matchday - 4) / 4]
      ELSE 'may'
    END,
    CASE
      WHEN p_matchday <= 3 THEN p_matchday::smallint
      WHEN p_matchday <= 35 THEN ((p_matchday - 4) % 4 + 1)::smallint
      ELSE (p_matchday - 35)::smallint
    END;
$$;

CREATE OR REPLACE FUNCTION public.competition_weather_for_month(p_month text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE p_month
    WHEN 'august' THEN 'warm'
    WHEN 'september' THEN 'mild'
    WHEN 'october' THEN 'windy'
    WHEN 'november' THEN 'wet'
    WHEN 'december' THEN 'cold'
    WHEN 'january' THEN 'freezing'
    WHEN 'february' THEN 'cold'
    WHEN 'march' THEN 'showers'
    WHEN 'april' THEN 'mild'
    WHEN 'may' THEN 'sunny'
    ELSE 'unknown'
  END;
$$;

CREATE OR REPLACE FUNCTION public.competition_assert_fixture_season(p_season_id bigint)
RETURNS public.competition_seasons
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season public.competition_seasons;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_season
  FROM public.competition_seasons
  WHERE id = p_season_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Season not found';
  END IF;

  IF v_season.status <> 'active' THEN
    RAISE EXCEPTION 'Fixtures can only be managed on an active season';
  END IF;

  RETURN v_season;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_assert_league_division(p_division text)
RETURNS void
LANGUAGE plpgsql
IMMUTABLE
AS $function$
BEGIN
  IF p_division NOT IN ('superleague', 'championship_a', 'championship_b') THEN
    RAISE EXCEPTION 'Invalid league division: %', p_division;
  END IF;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Slot assignment (table position 1–20 per division)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_set_division_slots(
  p_season_id bigint,
  p_division text,
  p_slots jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_item jsonb;
  v_pos int;
  v_club text;
  v_seen_pos int[];
  v_seen_club text[];
BEGIN
  PERFORM public.competition_assert_fixture_season(p_season_id);
  PERFORM public.competition_assert_league_division(p_division);

  IF p_slots IS NULL OR jsonb_typeof(p_slots) <> 'array' THEN
    RAISE EXCEPTION 'Slots must be a JSON array';
  END IF;

  IF jsonb_array_length(p_slots) <> 20 THEN
    RAISE EXCEPTION 'Exactly 20 slot assignments required';
  END IF;

  v_seen_pos := ARRAY[]::int[];
  v_seen_club := ARRAY[]::text[];

  UPDATE public.competition_club_seasons
  SET league_position = NULL
  WHERE season_id = p_season_id
    AND division = p_division;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_slots)
  LOOP
    v_pos := (v_item ->> 'position')::int;
    v_club := trim(both '"' FROM (v_item ->> 'club'));

    IF v_pos IS NULL OR v_pos < 1 OR v_pos > 20 THEN
      RAISE EXCEPTION 'Each slot needs position 1–20';
    END IF;

    IF v_club IS NULL OR v_club = '' THEN
      RAISE EXCEPTION 'Each slot needs a club';
    END IF;

    IF v_pos = ANY (v_seen_pos) THEN
      RAISE EXCEPTION 'Duplicate position %', v_pos;
    END IF;

    IF v_club = ANY (v_seen_club) THEN
      RAISE EXCEPTION 'Duplicate club %', v_club;
    END IF;

    v_seen_pos := v_seen_pos || v_pos;
    v_seen_club := v_seen_club || v_club;

    UPDATE public.competition_club_seasons
    SET league_position = v_pos
    WHERE season_id = p_season_id
      AND club_short_name = v_club
      AND division = p_division;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Club % is not in division % for this season', v_club, p_division;
    END IF;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_shuffle_division_slots(
  p_season_id bigint,
  p_division text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_clubs text[];
  v_slots jsonb := '[]'::jsonb;
  v_i int;
BEGIN
  PERFORM public.competition_assert_fixture_season(p_season_id);
  PERFORM public.competition_assert_league_division(p_division);

  SELECT array_agg(club_short_name ORDER BY random())
  INTO v_clubs
  FROM public.competition_club_seasons
  WHERE season_id = p_season_id
    AND division = p_division;

  IF coalesce(array_length(v_clubs, 1), 0) <> 20 THEN
    RAISE EXCEPTION 'Division must have exactly 20 clubs';
  END IF;

  FOR v_i IN 1..20
  LOOP
    v_slots := v_slots || jsonb_build_object(
      'position', v_i,
      'club', v_clubs[v_i]
    );
  END LOOP;

  PERFORM public.competition_set_division_slots(p_season_id, p_division, v_slots);

  RETURN v_slots;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Round-robin generator (38 matchdays × 10 fixtures = 380 per division)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_generate_league_fixtures(
  p_season_id bigint,
  p_division text,
  p_shuffle_slots boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_teams text[];
  v_round int;
  v_matchday int;
  v_i int;
  v_home text;
  v_away text;
  v_a text;
  v_b text;
  v_cal record;
  v_weather text;
  v_inserted bigint := 0;
  v_slots jsonb;
BEGIN
  PERFORM public.competition_assert_fixture_season(p_season_id);
  PERFORM public.competition_assert_league_division(p_division);

  IF p_shuffle_slots THEN
    PERFORM public.competition_shuffle_division_slots(p_season_id, p_division);
  END IF;

  SELECT count(*) INTO v_i
  FROM public.competition_club_seasons
  WHERE season_id = p_season_id
    AND division = p_division
    AND league_position BETWEEN 1 AND 20;

  IF v_i <> 20 THEN
    RAISE EXCEPTION 'Assign all 20 table slots before generating (have %)', v_i;
  END IF;

  SELECT array_agg(club_short_name ORDER BY league_position)
  INTO v_teams
  FROM public.competition_club_seasons
  WHERE season_id = p_season_id
    AND division = p_division;

  DELETE FROM public.competition_fixtures
  WHERE season_id = p_season_id
    AND division = p_division
    AND competition_type = 'league';

  -- First leg: matchdays 1–19
  FOR v_round IN 1..19
  LOOP
    v_matchday := v_round;
    SELECT * INTO v_cal FROM public.competition_matchday_calendar(v_matchday);
    v_weather := public.competition_weather_for_month(v_cal.gpsl_month);

    FOR v_i IN 1..10
    LOOP
      IF v_i = 1 THEN
        v_a := v_teams[1];
        v_b := v_teams[20];
      ELSE
        v_a := v_teams[v_i];
        v_b := v_teams[21 - v_i];
      END IF;

      -- Flip the home side every other matchday so no club gets long
      -- home/away runs (circle method otherwise bunches ~10 in a row).
      IF (v_round % 2) = 1 THEN
        v_home := v_a;
        v_away := v_b;
      ELSE
        v_home := v_b;
        v_away := v_a;
      END IF;

      INSERT INTO public.competition_fixtures (
        season_id, division, competition_type, matchday,
        gpsl_month, week_in_month,
        home_club_short_name, away_club_short_name, weather
      )
      VALUES (
        p_season_id, p_division, 'league', v_matchday,
        v_cal.gpsl_month, v_cal.week_in_month,
        v_home, v_away, v_weather
      );

      v_inserted := v_inserted + 1;
    END LOOP;

    v_teams := ARRAY[v_teams[1], v_teams[20]]
      || v_teams[2:19];
  END LOOP;

  -- Second leg: matchdays 20–38 (exact mirror of leg 1 — venues swapped)
  v_teams := NULL;
  SELECT array_agg(club_short_name ORDER BY league_position)
  INTO v_teams
  FROM public.competition_club_seasons
  WHERE season_id = p_season_id
    AND division = p_division;

  FOR v_round IN 1..19
  LOOP
    v_matchday := v_round + 19;
    SELECT * INTO v_cal FROM public.competition_matchday_calendar(v_matchday);
    v_weather := public.competition_weather_for_month(v_cal.gpsl_month);

    FOR v_i IN 1..10
    LOOP
      IF v_i = 1 THEN
        v_a := v_teams[1];
        v_b := v_teams[20];
      ELSE
        v_a := v_teams[v_i];
        v_b := v_teams[21 - v_i];
      END IF;

      -- Mirror of leg 1: same pairing, opposite venue for each parity.
      IF (v_round % 2) = 1 THEN
        v_home := v_b;
        v_away := v_a;
      ELSE
        v_home := v_a;
        v_away := v_b;
      END IF;

      INSERT INTO public.competition_fixtures (
        season_id, division, competition_type, matchday,
        gpsl_month, week_in_month,
        home_club_short_name, away_club_short_name, weather
      )
      VALUES (
        p_season_id, p_division, 'league', v_matchday,
        v_cal.gpsl_month, v_cal.week_in_month,
        v_home, v_away, v_weather
      );

      v_inserted := v_inserted + 1;
    END LOOP;

    v_teams := ARRAY[v_teams[1], v_teams[20]]
      || v_teams[2:19];
  END LOOP;

  RETURN jsonb_build_object(
    'division', p_division,
    'fixtures_created', v_inserted,
    'matchdays', 38
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_delete_league_fixtures(
  p_season_id bigint,
  p_division text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_deleted bigint;
BEGIN
  PERFORM public.competition_assert_fixture_season(p_season_id);
  PERFORM public.competition_assert_league_division(p_division);

  DELETE FROM public.competition_fixtures
  WHERE season_id = p_season_id
    AND division = p_division
    AND competition_type = 'league';

  GET DIAGNOSTICS v_deleted = ROW_COUNT;
  RETURN v_deleted;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public read view (current active season)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_fixtures_public
WITH (security_invoker = false)
AS
SELECT
  f.id,
  f.season_id,
  f.division,
  f.competition_type,
  f.matchday,
  f.gpsl_month,
  f.week_in_month,
  f.home_club_short_name,
  hc."Club" AS home_club_name,
  f.away_club_short_name,
  ac."Club" AS away_club_name,
  f.weather,
  f.home_goals,
  f.away_goals,
  f.status
FROM public.competition_fixtures f
JOIN public.competition_seasons s ON s.id = f.season_id
JOIN public."Clubs" hc ON hc."ShortName" = f.home_club_short_name
JOIN public."Clubs" ac ON ac."ShortName" = f.away_club_short_name
WHERE s.status = 'active' AND s.is_current = true;

GRANT SELECT ON public.competition_fixtures_public TO authenticated;
GRANT SELECT ON public.competition_fixtures_public TO anon;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_fixtures ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_fixtures_select ON public.competition_fixtures;
CREATE POLICY competition_fixtures_select ON public.competition_fixtures
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.competition_seasons s
      WHERE s.id = season_id
        AND s.status = 'active'
    )
  );

DROP POLICY IF EXISTS competition_fixtures_admin ON public.competition_fixtures;
CREATE POLICY competition_fixtures_admin ON public.competition_fixtures
  FOR ALL
  TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.competition_fixtures TO authenticated;

GRANT EXECUTE ON FUNCTION public.competition_set_division_slots(bigint, text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_shuffle_division_slots(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_generate_league_fixtures(bigint, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_delete_league_fixtures(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_matchday_calendar(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_weather_for_month(text) TO authenticated;
