-- =============================================================================
-- GPSL Owner ranking — season points, rolling 4 seasons (World Cup draft), all-time
-- Run after competition_history.sql and competition_international.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.competition_owner_season_ranking (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  season_label text NOT NULL,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  owner_id uuid,
  owner_tag text NOT NULL DEFAULT '',
  league_points numeric(8, 2) NOT NULL DEFAULT 0,
  super8_points numeric(8, 2) NOT NULL DEFAULT 0,
  plate_points numeric(8, 2) NOT NULL DEFAULT 0,
  shield_points numeric(8, 2) NOT NULL DEFAULT 0,
  spoon_points numeric(8, 2) NOT NULL DEFAULT 0,
  league_cup_points numeric(8, 2) NOT NULL DEFAULT 0,
  season_total numeric(10, 2) NOT NULL DEFAULT 0,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  computed_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_owner_season_ranking_unique UNIQUE (season_id, club_short_name)
);

CREATE INDEX IF NOT EXISTS competition_owner_season_ranking_owner_idx
  ON public.competition_owner_season_ranking (owner_id, season_id DESC);

CREATE INDEX IF NOT EXISTS competition_owner_season_ranking_season_idx
  ON public.competition_owner_season_ranking (season_id);

-- ---------------------------------------------------------------------------
-- League position points (SuperLeague only)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_owner_league_points(
  p_division text,
  p_position smallint
)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN p_division IS DISTINCT FROM 'superleague' OR p_position IS NULL THEN 0::numeric
    WHEN p_position = 1 THEN 10
    WHEN p_position = 2 THEN 8
    WHEN p_position BETWEEN 3 AND 8 THEN 5
    WHEN p_position BETWEEN 9 AND 15 THEN 3
    WHEN p_position BETWEEN 16 AND 17 THEN 2
    WHEN p_position BETWEEN 18 AND 20 THEN 0.5
    ELSE 0
  END;
$$;

-- ---------------------------------------------------------------------------
-- Cup achievement → points (best tier reached per cup per season)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_owner_cup_points(
  p_cup_code text,
  p_achievement text
)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE p_cup_code
    WHEN 'super8' THEN CASE p_achievement
      WHEN 'winner' THEN 6
      WHEN 'runner_up' THEN 4
      WHEN 'sf' THEN 3
      WHEN 'qf' THEN 2
      ELSE 0
    END
    WHEN 'plate' THEN CASE p_achievement
      WHEN 'winner' THEN 4
      WHEN 'runner_up' THEN 3
      WHEN 'sf' THEN 2
      WHEN 'qf' THEN 1
      WHEN 'r16' THEN 0.5
      ELSE 0
    END
    WHEN 'shield' THEN CASE p_achievement
      WHEN 'winner' THEN 3
      WHEN 'runner_up' THEN 2
      WHEN 'sf' THEN 1
      WHEN 'qf' THEN 0.5
      WHEN 'r16' THEN 0.25
      WHEN 'r32' THEN 0
      ELSE 0
    END
    WHEN 'spoon' THEN CASE p_achievement
      WHEN 'winner' THEN 1
      WHEN 'runner_up' THEN 0.5
      WHEN 'sf' THEN 0.25
      WHEN 'qf' THEN 0
      ELSE 0
    END
    WHEN 'league_cup' THEN CASE p_achievement
      WHEN 'winner' THEN 4.5
      WHEN 'runner_up' THEN 3
      WHEN 'sf' THEN 2
      WHEN 'qf' THEN 1
      WHEN 'r16' THEN 0.5
      WHEN 'r32' THEN 0.25
      WHEN 'r64' THEN 0
      ELSE 0
    END
    ELSE 0
  END;
$$;

CREATE OR REPLACE FUNCTION public.competition_club_cup_achievement(
  p_season_id bigint,
  p_club text,
  p_cup_code text
)
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := btrim(p_club);
  v_max_round int;
  v_winner text;
  v_runner text;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RETURN NULL;
  END IF;

  SELECT w.winner_club_short_name, w.runner_up_club_short_name
  INTO v_winner, v_runner
  FROM public.competition_cup_season_winner w
  WHERE w.season_id = p_season_id
    AND w.cup_code = p_cup_code;

  IF v_winner = v_club THEN
    RETURN 'winner';
  END IF;

  IF v_runner = v_club THEN
    RETURN 'runner_up';
  END IF;

  SELECT max(n.round_no)
  INTO v_max_round
  FROM public.competition_cup_bracket_nodes n
  WHERE n.season_id = p_season_id
    AND n.cup_code = p_cup_code
    AND (
      n.home_club_short_name = v_club
      OR n.away_club_short_name = v_club
    )
    AND (
      n.winner_club_short_name IS NOT NULL
      OR EXISTS (
        SELECT 1 FROM public.competition_fixtures f
        WHERE f.id = n.fixture_id AND f.status = 'played'
      )
    );

  IF v_max_round IS NULL THEN
    RETURN NULL;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.competition_cup_bracket_nodes n
    WHERE n.season_id = p_season_id
      AND n.cup_code = p_cup_code
      AND n.round_no = v_max_round
      AND (n.home_club_short_name = v_club OR n.away_club_short_name = v_club)
  ) THEN
    IF p_cup_code = 'league_cup' THEN
      RETURN CASE v_max_round
        WHEN 6 THEN 'runner_up'
        WHEN 5 THEN 'sf'
        WHEN 4 THEN 'qf'
        WHEN 3 THEN 'r16'
        WHEN 2 THEN 'r32'
        WHEN 1 THEN 'r64'
        ELSE NULL
      END;
    ELSIF p_cup_code = 'shield' THEN
      RETURN CASE v_max_round
        WHEN 5 THEN 'runner_up'
        WHEN 4 THEN 'sf'
        WHEN 3 THEN 'qf'
        WHEN 2 THEN 'r16'
        WHEN 1 THEN 'r32'
        ELSE NULL
      END;
    ELSIF p_cup_code = 'plate' THEN
      RETURN CASE v_max_round
        WHEN 4 THEN 'runner_up'
        WHEN 3 THEN 'sf'
        WHEN 2 THEN 'qf'
        WHEN 1 THEN 'r16'
        ELSE NULL
      END;
    ELSIF p_cup_code IN ('super8', 'spoon') THEN
      RETURN CASE v_max_round
        WHEN 3 THEN 'runner_up'
        WHEN 2 THEN 'sf'
        WHEN 1 THEN 'qf'
        ELSE NULL
      END;
    END IF;
  END IF;

  RETURN NULL;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Recompute one season (call on archive or admin refresh)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_owner_ranking_recompute_season(
  p_season_id bigint
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season record;
  v_club record;
  v_league_pts numeric;
  v_super8_pts numeric;
  v_plate_pts numeric;
  v_shield_pts numeric;
  v_spoon_pts numeric;
  v_lc_pts numeric;
  v_total numeric;
  v_ach text;
  v_detail jsonb;
  v_count int := 0;
  v_owner_id uuid;
  v_owner_tag text;
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT id, label INTO v_season
  FROM public.competition_seasons
  WHERE id = p_season_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Season not found';
  END IF;

  FOR v_club IN
    SELECT c."ShortName" AS club_short_name, c.owner_id
    FROM public."Clubs" c
    WHERE c.owner_id IS NOT NULL
  LOOP
    v_owner_id := v_club.owner_id;
    v_owner_tag := coalesce(public.owner_registry_resolve_tag(v_owner_id), '');

    SELECT coalesce(public.competition_owner_league_points(a.division, a.final_position), 0)
    INTO v_league_pts
    FROM public.competition_club_season_archive a
    WHERE a.season_id = p_season_id
      AND a.club_short_name = v_club.club_short_name;

    v_league_pts := coalesce(v_league_pts, 0);

    v_ach := public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'super8');
    v_super8_pts := coalesce(public.competition_owner_cup_points('super8', v_ach), 0);

    v_ach := public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'plate');
    v_plate_pts := coalesce(public.competition_owner_cup_points('plate', v_ach), 0);

    v_ach := public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'shield');
    v_shield_pts := coalesce(public.competition_owner_cup_points('shield', v_ach), 0);

    v_ach := public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'spoon');
    v_spoon_pts := coalesce(public.competition_owner_cup_points('spoon', v_ach), 0);

    v_ach := public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'league_cup');
    v_lc_pts := coalesce(public.competition_owner_cup_points('league_cup', v_ach), 0);

    v_total := v_league_pts + v_super8_pts + v_plate_pts + v_shield_pts + v_spoon_pts + v_lc_pts;

    v_detail := jsonb_build_object(
      'league', jsonb_build_object('points', v_league_pts),
      'super8', jsonb_build_object(
        'achievement', public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'super8'),
        'points', v_super8_pts
      ),
      'plate', jsonb_build_object(
        'achievement', public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'plate'),
        'points', v_plate_pts
      ),
      'shield', jsonb_build_object(
        'achievement', public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'shield'),
        'points', v_shield_pts
      ),
      'spoon', jsonb_build_object(
        'achievement', public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'spoon'),
        'points', v_spoon_pts
      ),
      'league_cup', jsonb_build_object(
        'achievement', public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'league_cup'),
        'points', v_lc_pts
      )
    );

    INSERT INTO public.competition_owner_season_ranking (
      season_id,
      season_label,
      club_short_name,
      owner_id,
      owner_tag,
      league_points,
      super8_points,
      plate_points,
      shield_points,
      spoon_points,
      league_cup_points,
      season_total,
      detail,
      computed_at
    )
    VALUES (
      p_season_id,
      v_season.label,
      v_club.club_short_name,
      v_owner_id,
      v_owner_tag,
      v_league_pts,
      v_super8_pts,
      v_plate_pts,
      v_shield_pts,
      v_spoon_pts,
      v_lc_pts,
      v_total,
      v_detail,
      now()
    )
    ON CONFLICT (season_id, club_short_name) DO UPDATE
    SET owner_tag = excluded.owner_tag,
        league_points = excluded.league_points,
        super8_points = excluded.super8_points,
        plate_points = excluded.plate_points,
        shield_points = excluded.shield_points,
        spoon_points = excluded.spoon_points,
        league_cup_points = excluded.league_cup_points,
        season_total = excluded.season_total,
        detail = excluded.detail,
        computed_at = now();

    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_owner_ranking_recompute_all()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  r record;
  v_total int := 0;
  v_n int;
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  FOR r IN
    SELECT id FROM public.competition_seasons
    WHERE status IN ('complete', 'active')
    ORDER BY id
  LOOP
    v_n := public.competition_owner_ranking_recompute_season(r.id);
    v_total := v_total + coalesce(v_n, 0);
  END LOOP;

  RETURN v_total;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_owner_display_name(p_owner_id uuid)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(
    nullif(btrim(public.owner_registry_resolve_tag(p_owner_id)), ''),
    'Former owner'
  );
$$;

-- ---------------------------------------------------------------------------
-- Public views
-- ---------------------------------------------------------------------------

DROP VIEW IF EXISTS public.competition_owner_ranking_rolling4_public;
CREATE VIEW public.competition_owner_ranking_rolling4_public
WITH (security_invoker = false)
AS
WITH last_four AS (
  SELECT s.season_id AS id
  FROM (
    SELECT DISTINCT season_id
    FROM public.competition_owner_season_ranking
    ORDER BY season_id DESC
    LIMIT 4
  ) s
),
totals AS (
  SELECT
    r.owner_id,
    r.club_short_name,
    sum(r.season_total) AS rolling_points,
    count(*)::integer AS seasons_count,
    jsonb_agg(
      jsonb_build_object(
        'season_label', r.season_label,
        'season_total', r.season_total
      )
      ORDER BY r.season_id
    ) AS season_breakdown
  FROM public.competition_owner_season_ranking r
  WHERE r.season_id IN (SELECT id FROM last_four)
    AND r.owner_id IS NOT NULL
  GROUP BY r.owner_id, r.club_short_name
)
SELECT
  row_number() OVER (
    ORDER BY coalesce(t.rolling_points, 0) DESC,
      public.competition_owner_display_name(c.owner_id),
      c."ShortName"
  )::smallint AS rank_position,
  c.owner_id,
  public.competition_owner_display_name(c.owner_id) AS owner_name,
  c."ShortName" AS club_short_name,
  c."Club" AS club_name,
  public.owner_registry_resolve_tag(c.owner_id) AS owner_tag,
  ion.nation_code,
  n.name AS nation_name,
  n.flag_emoji,
  round(coalesce(t.rolling_points, 0), 2) AS rolling_points,
  coalesce(t.seasons_count, 0) AS seasons_count,
  coalesce(t.season_breakdown, '[]'::jsonb) AS season_breakdown
FROM public."Clubs" c
LEFT JOIN totals t ON t.club_short_name = c."ShortName"
LEFT JOIN public.international_owner_nations ion
  ON ion.club_short_name = c."ShortName" AND ion.is_active = true
LEFT JOIN public.international_nations n ON n.code = ion.nation_code
WHERE c.owner_id IS NOT NULL
ORDER BY rank_position;

-- All-time includes club + WC points — deploy patches/owner_ranking_wc_points.sql after this file.

DROP VIEW IF EXISTS public.competition_owner_ranking_alltime_public;
CREATE VIEW public.competition_owner_ranking_alltime_public
WITH (security_invoker = false)
AS
SELECT
  row_number() OVER (
    ORDER BY sum(r.season_total) DESC, public.competition_owner_display_name(r.owner_id)
  )::integer AS rank_position,
  r.owner_id,
  public.competition_owner_display_name(r.owner_id) AS owner_name,
  round(sum(r.season_total), 2) AS club_points,
  0::numeric AS wc_points,
  round(sum(r.season_total), 2) AS total_points,
  count(DISTINCT r.season_id)::integer AS seasons_count,
  min(r.season_label) AS first_season_label,
  max(r.season_label) AS last_season_label,
  '[]'::jsonb AS wc_breakdown
FROM public.competition_owner_season_ranking r
WHERE r.owner_id IS NOT NULL
GROUP BY r.owner_id
ORDER BY rank_position;

DROP VIEW IF EXISTS public.competition_owner_season_ranking_public;
CREATE VIEW public.competition_owner_season_ranking_public
WITH (security_invoker = false)
AS
SELECT
  r.season_id,
  r.season_label,
  r.club_short_name,
  c."Club" AS club_name,
  r.owner_id,
  public.competition_owner_display_name(r.owner_id) AS owner_name,
  coalesce(
    nullif(btrim(public.owner_registry_resolve_tag(r.owner_id)), ''),
    nullif(btrim(r.owner_tag), '')
  ) AS owner_tag,
  r.league_points,
  r.super8_points,
  r.plate_points,
  r.shield_points,
  r.spoon_points,
  r.league_cup_points,
  r.season_total,
  r.detail,
  r.computed_at
FROM public.competition_owner_season_ranking r
JOIN public."Clubs" c ON c."ShortName" = r.club_short_name
ORDER BY r.season_id DESC, r.season_total DESC;

-- World Cup nation draft uses rolling 4-season points
-- Return type changed vs competition_international.sql — drop dependents first.
DROP VIEW IF EXISTS public.international_owner_rank_public;
DROP VIEW IF EXISTS public.international_selection_public;
DROP FUNCTION IF EXISTS public.international_owner_draft_order();

CREATE OR REPLACE FUNCTION public.international_owner_draft_order()
RETURNS TABLE (
  pick_order smallint,
  club_short_name text,
  club_name text,
  owner_id uuid,
  owner_name text,
  owner_tag text,
  rank_points numeric,
  nation_code text,
  nation_name text,
  flag_emoji text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    row_number() OVER (
      ORDER BY
        coalesce(r4.rolling_points, 0) DESC,
        public.competition_owner_display_name(c.owner_id),
        c."ShortName"
    )::smallint AS pick_order,
    c."ShortName" AS club_short_name,
    c."Club" AS club_name,
    c.owner_id,
    public.competition_owner_display_name(c.owner_id) AS owner_name,
    public.owner_registry_resolve_tag(c.owner_id) AS owner_tag,
    coalesce(r4.rolling_points, 0) AS rank_points,
    ion.nation_code,
    n.name AS nation_name,
    n.flag_emoji
  FROM public."Clubs" c
  LEFT JOIN public.competition_owner_ranking_rolling4_public r4
    ON r4.club_short_name = c."ShortName"
  LEFT JOIN public.international_owner_nations ion
    ON ion.club_short_name = c."ShortName" AND ion.is_active = true
  LEFT JOIN public.international_nations n ON n.code = ion.nation_code
  WHERE c.owner_id IS NOT NULL
  ORDER BY pick_order, c."ShortName";
$$;

CREATE VIEW public.international_owner_rank_public
WITH (security_invoker = false)
AS
SELECT * FROM public.international_owner_draft_order();

CREATE VIEW public.international_selection_public
WITH (security_invoker = false)
AS
SELECT
  w.id,
  w.phase,
  w.is_open,
  w.opens_at,
  w.closes_at,
  w.current_pick_rank,
  (
    SELECT d.club_short_name
    FROM public.international_owner_draft_order() d
    WHERE d.pick_order = w.current_pick_rank
    LIMIT 1
  ) AS current_pick_club,
  (
    SELECT count(*)::integer
    FROM public.international_owner_nations ion
    WHERE ion.is_active = true
  ) AS nations_assigned
FROM public.international_selection_windows w
WHERE w.is_open = true
ORDER BY w.id DESC
LIMIT 1;

ALTER TABLE public.competition_owner_season_ranking ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_owner_season_ranking_select ON public.competition_owner_season_ranking;
CREATE POLICY competition_owner_season_ranking_select ON public.competition_owner_season_ranking
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_owner_season_ranking_admin ON public.competition_owner_season_ranking;
CREATE POLICY competition_owner_season_ranking_admin ON public.competition_owner_season_ranking
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.competition_owner_season_ranking TO authenticated;
GRANT SELECT ON public.competition_owner_ranking_rolling4_public TO authenticated;
GRANT SELECT ON public.competition_owner_ranking_alltime_public TO authenticated;
GRANT SELECT ON public.competition_owner_season_ranking_public TO authenticated;
GRANT SELECT ON public.international_owner_rank_public TO authenticated;
GRANT SELECT ON public.international_selection_public TO authenticated;

GRANT EXECUTE ON FUNCTION public.competition_owner_ranking_recompute_season(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_owner_ranking_recompute_all() TO authenticated;

NOTIFY pgrst, 'reload schema';
