-- =============================================================================
-- GPSL — Club prestige ranking (5 seasons) + stadium attendance fill
-- Run after competition_history.sql and competition_owner_ranking.sql
--
-- Club rank follows the club (not the owner). Owner ranking is unchanged.
-- Stadium fill reacts to current-season delivery vs expectation.
-- Big clubs: expectation fixed by stature; manager does not lower it.
-- Medium/low clubs: top managers can inflate expectation upward only.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------

ALTER TABLE public."Clubs"
  ADD COLUMN IF NOT EXISTS manager_rating smallint CHECK (manager_rating IS NULL OR (manager_rating >= 1 AND manager_rating <= 99));

COMMENT ON COLUMN public."Clubs".manager_rating IS
  'eFootball manager rating (e.g. 87). Used for season expectation lift on medium/low clubs only.';

ALTER TABLE public.global_settings
  ADD COLUMN IF NOT EXISTS stadium_min_fill_pct numeric(5, 2) NOT NULL DEFAULT 60.00,
  ADD COLUMN IF NOT EXISTS stadium_max_fill_pct numeric(5, 2) NOT NULL DEFAULT 95.00,
  ADD COLUMN IF NOT EXISTS stadium_neutral_fill_pct numeric(5, 2) NOT NULL DEFAULT 75.00,
  ADD COLUMN IF NOT EXISTS stadium_rolling_seasons smallint NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS stadium_big_club_max_rank smallint NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS stadium_medium_club_max_rank smallint NOT NULL DEFAULT 35,
  ADD COLUMN IF NOT EXISTS stadium_capacity_prestige_weight numeric(6, 3) NOT NULL DEFAULT 0.150,
  ADD COLUMN IF NOT EXISTS stadium_capacity_prestige_ref integer NOT NULL DEFAULT 40000,
  ADD COLUMN IF NOT EXISTS stadium_big_club_sensitivity numeric(6, 3) NOT NULL DEFAULT 1.000,
  ADD COLUMN IF NOT EXISTS stadium_medium_club_sensitivity numeric(6, 3) NOT NULL DEFAULT 0.700,
  ADD COLUMN IF NOT EXISTS stadium_low_club_sensitivity numeric(6, 3) NOT NULL DEFAULT 0.500,
  ADD COLUMN IF NOT EXISTS stadium_overperform_cap numeric(6, 3) NOT NULL DEFAULT 0.500,
  ADD COLUMN IF NOT EXISTS stadium_points_gap_scale numeric(6, 3) NOT NULL DEFAULT 2.000,
  ADD COLUMN IF NOT EXISTS stadium_league_expect_weight numeric(6, 3) NOT NULL DEFAULT 0.800,
  ADD COLUMN IF NOT EXISTS stadium_cup_expect_weight numeric(6, 3) NOT NULL DEFAULT 0.200,
  ADD COLUMN IF NOT EXISTS stadium_league_perf_weight numeric(6, 3) NOT NULL DEFAULT 0.800,
  ADD COLUMN IF NOT EXISTS stadium_cup_perf_weight numeric(6, 3) NOT NULL DEFAULT 0.200,
  ADD COLUMN IF NOT EXISTS stadium_manager_lift_threshold smallint NOT NULL DEFAULT 75,
  ADD COLUMN IF NOT EXISTS stadium_manager_lift_max_rating smallint NOT NULL DEFAULT 87,
  ADD COLUMN IF NOT EXISTS stadium_manager_lift_max_positions_med numeric(5, 2) NOT NULL DEFAULT 5.00,
  ADD COLUMN IF NOT EXISTS stadium_manager_lift_max_positions_low numeric(5, 2) NOT NULL DEFAULT 8.00,
  ADD COLUMN IF NOT EXISTS stadium_expected_cup_super8_pts numeric(6, 2) NOT NULL DEFAULT 2.00,
  ADD COLUMN IF NOT EXISTS stadium_expected_cup_plate_pts numeric(6, 2) NOT NULL DEFAULT 0.50,
  ADD COLUMN IF NOT EXISTS stadium_expected_cup_shield_pts numeric(6, 2) NOT NULL DEFAULT 0.25,
  ADD COLUMN IF NOT EXISTS stadium_expected_cup_spoon_pts numeric(6, 2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS stadium_expected_cup_league_cup_pts numeric(6, 2) NOT NULL DEFAULT 0.50;

CREATE TABLE IF NOT EXISTS public.competition_club_tier_override (
  club_short_name text PRIMARY KEY REFERENCES public."Clubs" ("ShortName") ON DELETE CASCADE,
  tier_override text NOT NULL CHECK (tier_override IN ('big', 'medium', 'low')),
  notes text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.competition_club_season_ranking (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  season_label text NOT NULL,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  division text,
  final_position smallint,
  league_points numeric(8, 2) NOT NULL DEFAULT 0,
  super8_points numeric(8, 2) NOT NULL DEFAULT 0,
  plate_points numeric(8, 2) NOT NULL DEFAULT 0,
  shield_points numeric(8, 2) NOT NULL DEFAULT 0,
  spoon_points numeric(8, 2) NOT NULL DEFAULT 0,
  league_cup_points numeric(8, 2) NOT NULL DEFAULT 0,
  season_total numeric(10, 2) NOT NULL DEFAULT 0,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  computed_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_club_season_ranking_unique UNIQUE (season_id, club_short_name)
);

CREATE INDEX IF NOT EXISTS competition_club_season_ranking_club_idx
  ON public.competition_club_season_ranking (club_short_name, season_id DESC);

-- ---------------------------------------------------------------------------
-- League points (club — includes Championship scale)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_club_league_points(
  p_division text,
  p_position smallint
)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN p_position IS NULL THEN 0::numeric
    WHEN p_division = 'superleague' THEN public.competition_owner_league_points(p_division, p_position)
    WHEN p_division IN ('championship_a', 'championship_b') THEN CASE
      WHEN p_position = 1 THEN 8
      WHEN p_position = 2 THEN 6
      WHEN p_position BETWEEN 3 AND 4 THEN 4
      WHEN p_position BETWEEN 5 AND 10 THEN 2
      WHEN p_position BETWEEN 11 AND 15 THEN 1
      WHEN p_position BETWEEN 16 AND 20 THEN 0.5
      ELSE 0
    END
    ELSE 0
  END;
$$;

CREATE OR REPLACE FUNCTION public.competition_club_cup_points(
  p_cup_code text,
  p_achievement text
)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT public.competition_owner_cup_points(p_cup_code, p_achievement);
$$;

-- ---------------------------------------------------------------------------
-- Club position for a season (archive or live)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_club_season_standing(
  p_season_id bigint,
  p_club_short_name text
)
RETURNS TABLE (
  division text,
  final_position smallint
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  RETURN QUERY
  SELECT a.division, a.final_position
  FROM public.competition_club_season_archive a
  WHERE a.season_id = p_season_id
    AND a.club_short_name = p_club_short_name;

  IF FOUND THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT s.division, s.table_position::smallint
  FROM public.competition_standings_public s
  WHERE s.season_id = p_season_id
    AND s.club_short_name = p_club_short_name;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Recompute club season ranking (all clubs in season — no owner_id)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_club_ranking_recompute_season(
  p_season_id bigint
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season record;
  v_club record;
  v_division text;
  v_pos smallint;
  v_league_pts numeric;
  v_super8_pts numeric;
  v_plate_pts numeric;
  v_shield_pts numeric;
  v_spoon_pts numeric;
  v_lc_pts numeric;
  v_total numeric;
  v_ach text;
  v_detail jsonb;
  v_count int := 0;
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT id, label INTO v_season
  FROM public.competition_seasons
  WHERE id = p_season_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Season not found';
  END IF;

  FOR v_club IN
    SELECT ccs.club_short_name
    FROM public.competition_club_seasons ccs
    WHERE ccs.season_id = p_season_id
  LOOP
    SELECT cs.division, cs.final_position
    INTO v_division, v_pos
    FROM public.competition_club_season_standing(p_season_id, v_club.club_short_name) cs;

    v_league_pts := coalesce(public.competition_club_league_points(v_division, v_pos), 0);

    v_ach := public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'super8');
    v_super8_pts := coalesce(public.competition_club_cup_points('super8', v_ach), 0);

    v_ach := public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'plate');
    v_plate_pts := coalesce(public.competition_club_cup_points('plate', v_ach), 0);

    v_ach := public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'shield');
    v_shield_pts := coalesce(public.competition_club_cup_points('shield', v_ach), 0);

    v_ach := public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'spoon');
    v_spoon_pts := coalesce(public.competition_club_cup_points('spoon', v_ach), 0);

    v_ach := public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'league_cup');
    v_lc_pts := coalesce(public.competition_club_cup_points('league_cup', v_ach), 0);

    v_total := v_league_pts + v_super8_pts + v_plate_pts + v_shield_pts + v_spoon_pts + v_lc_pts;

    v_detail := jsonb_build_object(
      'division', v_division,
      'final_position', v_pos,
      'league', jsonb_build_object('points', v_league_pts),
      'super8', jsonb_build_object(
        'achievement', public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'super8'),
        'points', v_super8_pts
      ),
      'plate', jsonb_build_object(
        'achievement', public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'plate'),
        'points', v_plate_pts
      ),
      'shield', jsonb_build_object(
        'achievement', public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'shield'),
        'points', v_shield_pts
      ),
      'spoon', jsonb_build_object(
        'achievement', public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'spoon'),
        'points', v_spoon_pts
      ),
      'league_cup', jsonb_build_object(
        'achievement', public.competition_club_cup_achievement(p_season_id, v_club.club_short_name, 'league_cup'),
        'points', v_lc_pts
      )
    );

    INSERT INTO public.competition_club_season_ranking (
      season_id, season_label, club_short_name, division, final_position,
      league_points, super8_points, plate_points, shield_points, spoon_points,
      league_cup_points, season_total, detail, computed_at
    )
    VALUES (
      p_season_id, v_season.label, v_club.club_short_name, v_division, v_pos,
      v_league_pts, v_super8_pts, v_plate_pts, v_shield_pts, v_spoon_pts,
      v_lc_pts, v_total, v_detail, now()
    )
    ON CONFLICT (season_id, club_short_name) DO UPDATE
    SET season_label = excluded.season_label,
        division = excluded.division,
        final_position = excluded.final_position,
        league_points = excluded.league_points,
        super8_points = excluded.super8_points,
        plate_points = excluded.plate_points,
        shield_points = excluded.shield_points,
        spoon_points = excluded.spoon_points,
        league_cup_points = excluded.league_cup_points,
        season_total = excluded.season_total,
        detail = excluded.detail,
        computed_at = now();

    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_club_ranking_recompute_all()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  r record;
  v_total int := 0;
  v_n int;
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  FOR r IN
    SELECT id FROM public.competition_seasons
    WHERE status IN ('complete', 'active')
    ORDER BY id
  LOOP
    v_n := public.competition_club_ranking_recompute_season(r.id);
    v_total := v_total + coalesce(v_n, 0);
  END LOOP;

  RETURN v_total;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Prestige rank (rolling N seasons + capacity blend)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_club_prestige_settings()
RETURNS public.global_settings
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT * FROM public.global_settings WHERE id = 1;
$$;

DROP VIEW IF EXISTS public.competition_club_prestige_public;
CREATE VIEW public.competition_club_prestige_public
WITH (security_invoker = false)
AS
WITH cfg AS (
  SELECT * FROM public.global_settings WHERE id = 1
),
last_n AS (
  SELECT s.season_id AS id
  FROM (
    SELECT DISTINCT season_id
    FROM public.competition_club_season_ranking
    ORDER BY season_id DESC
    LIMIT (SELECT greatest(stadium_rolling_seasons, 1) FROM cfg)
  ) s
),
rolling AS (
  SELECT
    r.club_short_name,
    sum(r.season_total) AS rolling_points,
    count(*)::integer AS seasons_count
  FROM public.competition_club_season_ranking r
  WHERE r.season_id IN (SELECT id FROM last_n)
  GROUP BY r.club_short_name
),
scored AS (
  SELECT
    c."ShortName" AS club_short_name,
    c."Club" AS club_name,
    coalesce(c."Capacity", 0)::int AS capacity,
    coalesce(r.rolling_points, 0) AS rolling_points,
    coalesce(r.seasons_count, 0) AS seasons_count,
    round(
      coalesce(r.rolling_points, 0)
      + (coalesce(c."Capacity", 0)::numeric / greatest(cfg.stadium_capacity_prestige_ref, 1))
        * cfg.stadium_capacity_prestige_weight
        * greatest(coalesce(r.rolling_points, 0), 1),
      2
    ) AS composite_score
  FROM public."Clubs" c
  CROSS JOIN cfg
  LEFT JOIN rolling r ON r.club_short_name = c."ShortName"
)
SELECT
  row_number() OVER (ORDER BY s.composite_score DESC, s.club_short_name)::smallint AS prestige_rank,
  s.club_short_name,
  s.club_name,
  s.capacity,
  s.rolling_points,
  s.seasons_count,
  s.composite_score
FROM scored s
ORDER BY prestige_rank;

-- ---------------------------------------------------------------------------
-- Club tier (admin override > computed cutoffs)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_club_tier(p_club_short_name text)
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_override text;
  v_rank smallint;
  v_cfg public.global_settings;
BEGIN
  SELECT o.tier_override INTO v_override
  FROM public.competition_club_tier_override o
  WHERE o.club_short_name = p_club_short_name;

  IF v_override IS NOT NULL THEN
    RETURN v_override;
  END IF;

  SELECT * INTO v_cfg FROM public.global_settings WHERE id = 1;

  SELECT p.prestige_rank INTO v_rank
  FROM public.competition_club_prestige_public p
  WHERE p.club_short_name = p_club_short_name;

  IF v_rank IS NULL THEN
    RETURN 'low';
  END IF;

  IF v_rank <= v_cfg.stadium_big_club_max_rank THEN
    RETURN 'big';
  ELSIF v_rank <= v_cfg.stadium_medium_club_max_rank THEN
    RETURN 'medium';
  END IF;

  RETURN 'low';
END;
$function$;

-- Expected league position from prestige rank (1 = best)
CREATE OR REPLACE FUNCTION public.competition_club_baseline_expected_position(
  p_prestige_rank smallint,
  p_club_count smallint
)
RETURNS smallint
LANGUAGE plpgsql
IMMUTABLE
AS $function$
DECLARE
  v_count int := greatest(coalesce(p_club_count, 20), 1);
  v_rank int := greatest(coalesce(p_prestige_rank, v_count), 1);
  v_pct numeric;
  v_pos numeric;
BEGIN
  v_pct := (v_count - v_rank + 1)::numeric / v_count::numeric;
  v_pos := 1 + (1 - v_pct) * 19;
  RETURN greatest(1, least(20, round(v_pos)::int))::smallint;
END;
$function$;

-- Expected cup points from baseline league position + division
CREATE OR REPLACE FUNCTION public.competition_club_expected_cup_points(
  p_division text,
  p_baseline_position smallint
)
RETURNS numeric
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cfg public.global_settings;
  v_pos int := coalesce(p_baseline_position, 10);
BEGIN
  SELECT * INTO v_cfg FROM public.global_settings WHERE id = 1;

  IF p_division = 'superleague' THEN
    IF v_pos <= 8 THEN
      RETURN v_cfg.stadium_expected_cup_super8_pts;
    ELSIF v_pos <= 16 THEN
      RETURN v_cfg.stadium_expected_cup_plate_pts;
    ELSE
      RETURN v_cfg.stadium_expected_cup_shield_pts;
    END IF;
  END IF;

  IF p_division IN ('championship_a', 'championship_b') THEN
    IF v_pos <= 4 THEN
      RETURN v_cfg.stadium_expected_cup_plate_pts;
    ELSIF v_pos <= 15 THEN
      RETURN v_cfg.stadium_expected_cup_shield_pts;
    ELSE
      RETURN v_cfg.stadium_expected_cup_spoon_pts;
    END IF;
  END IF;

  RETURN v_cfg.stadium_expected_cup_league_cup_pts;
END;
$function$;

-- Live season points (no admin recompute required for current-season gate)
CREATE OR REPLACE FUNCTION public.competition_club_live_season_points(
  p_season_id bigint,
  p_club_short_name text
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_division text;
  v_pos smallint;
  v_league_pts numeric;
  v_cup_pts numeric;
  v_ach text;
BEGIN
  SELECT cs.division, cs.final_position
  INTO v_division, v_pos
  FROM public.competition_club_season_standing(p_season_id, p_club_short_name) cs;

  v_league_pts := coalesce(public.competition_club_league_points(v_division, v_pos), 0);

  v_cup_pts := 0;
  FOREACH v_ach IN ARRAY ARRAY['super8', 'plate', 'shield', 'spoon', 'league_cup'] LOOP
    v_cup_pts := v_cup_pts + coalesce(
      public.competition_club_cup_points(
        v_ach,
        public.competition_club_cup_achievement(p_season_id, p_club_short_name, v_ach)
      ),
      0
    );
  END LOOP;

  RETURN jsonb_build_object(
    'division', v_division,
    'final_position', v_pos,
    'league_points', v_league_pts,
    'cup_points', v_cup_pts,
    'season_total', v_league_pts + v_cup_pts
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Stadium fill computation
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_compute_stadium_fill(
  p_club_short_name text,
  p_season_id bigint DEFAULT NULL,
  p_division text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_cfg public.global_settings;
  v_season_id bigint;
  v_division text;
  v_capacity int;
  v_tier text;
  v_prestige_rank smallint;
  v_club_count smallint;
  v_baseline_pos smallint;
  v_expected_pos smallint;
  v_actual_pos smallint;
  v_manager_rating smallint;
  v_lift numeric;
  v_lift_max numeric;
  v_league_expected numeric;
  v_league_actual numeric;
  v_cup_expected numeric;
  v_cup_actual numeric;
  v_expected_pts numeric;
  v_actual_pts numeric;
  v_gap numeric;
  v_sensitivity numeric;
  v_fill numeric;
  v_fill_delta numeric;
  v_rank_row record;
  v_standing_division text;
BEGIN
  SELECT * INTO v_cfg FROM public.global_settings WHERE id = 1;

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true AND status = 'active'
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('error', 'No active season');
  END IF;

  IF p_division IS NULL THEN
    SELECT ccs.division INTO v_division
    FROM public.competition_club_seasons ccs
    WHERE ccs.season_id = v_season_id
      AND ccs.club_short_name = p_club_short_name
    LIMIT 1;
  ELSE
    v_division := p_division;
  END IF;

  SELECT coalesce(c."Capacity", 0)::int, c.manager_rating
  INTO v_capacity, v_manager_rating
  FROM public."Clubs" c
  WHERE c."ShortName" = p_club_short_name;

  v_tier := public.competition_club_tier(p_club_short_name);

  SELECT count(*)::smallint INTO v_club_count FROM public."Clubs";

  SELECT p.prestige_rank, p.rolling_points, p.composite_score
  INTO v_rank_row
  FROM public.competition_club_prestige_public p
  WHERE p.club_short_name = p_club_short_name;

  v_prestige_rank := coalesce(v_rank_row.prestige_rank, v_club_count);

  v_baseline_pos := public.competition_club_baseline_expected_position(
    v_prestige_rank,
    v_club_count
  );
  v_expected_pos := v_baseline_pos;

  -- Manager lift: medium/low only, upward only (never lowers big-club expectation)
  IF v_tier IN ('medium', 'low')
    AND v_manager_rating IS NOT NULL
    AND v_manager_rating > v_cfg.stadium_manager_lift_threshold
  THEN
    v_lift_max := CASE v_tier
      WHEN 'low' THEN v_cfg.stadium_manager_lift_max_positions_low
      ELSE v_cfg.stadium_manager_lift_max_positions_med
    END;

    v_lift := (
      (v_manager_rating - v_cfg.stadium_manager_lift_threshold)::numeric
      / greatest(v_cfg.stadium_manager_lift_max_rating - v_cfg.stadium_manager_lift_threshold, 1)
    ) * v_lift_max;

    v_expected_pos := greatest(
      1::smallint,
      (v_baseline_pos - round(v_lift))::smallint
    );
  END IF;

  SELECT cs.division, cs.final_position
  INTO v_standing_division, v_actual_pos
  FROM public.competition_club_season_standing(v_season_id, p_club_short_name) cs;

  v_actual_pos := coalesce(v_actual_pos, 10);

  v_league_expected := public.competition_club_league_points(
    coalesce(v_division, v_standing_division, 'superleague'),
    v_expected_pos
  );

  v_cup_expected := public.competition_club_expected_cup_points(
    coalesce(v_division, v_standing_division, 'superleague'),
    v_expected_pos
  );

  SELECT
    (live ->> 'league_points')::numeric,
    (live ->> 'cup_points')::numeric
  INTO v_league_actual, v_cup_actual
  FROM public.competition_club_live_season_points(v_season_id, p_club_short_name) live;

  v_league_actual := coalesce(v_league_actual, 0);
  v_cup_actual := coalesce(v_cup_actual, 0);

  v_expected_pts :=
    v_league_expected * v_cfg.stadium_league_expect_weight
    + v_cup_expected * v_cfg.stadium_cup_expect_weight;

  v_actual_pts :=
    v_league_actual * v_cfg.stadium_league_perf_weight
    + v_cup_actual * v_cfg.stadium_cup_perf_weight;

  v_gap := v_actual_pts - v_expected_pts;

  v_sensitivity := CASE v_tier
    WHEN 'big' THEN v_cfg.stadium_big_club_sensitivity
    WHEN 'medium' THEN v_cfg.stadium_medium_club_sensitivity
    ELSE v_cfg.stadium_low_club_sensitivity
  END;

  IF v_gap < 0 THEN
    v_fill_delta := v_gap * v_cfg.stadium_points_gap_scale * v_sensitivity;
  ELSE
    v_fill_delta := v_gap * v_cfg.stadium_points_gap_scale
      * least(v_sensitivity, v_cfg.stadium_overperform_cap);
  END IF;

  v_fill := v_cfg.stadium_neutral_fill_pct / 100.0 + v_fill_delta / 100.0;
  v_fill := greatest(v_cfg.stadium_min_fill_pct / 100.0, least(v_cfg.stadium_max_fill_pct / 100.0, v_fill));

  RETURN jsonb_build_object(
    'club_short_name', p_club_short_name,
    'season_id', v_season_id,
    'division', coalesce(v_division, v_standing_division),
    'capacity', v_capacity,
    'club_tier', v_tier,
    'prestige_rank', v_prestige_rank,
    'rolling_points', coalesce(v_rank_row.rolling_points, 0),
    'composite_score', coalesce(v_rank_row.composite_score, 0),
    'manager_rating', v_manager_rating,
    'baseline_expected_position', v_baseline_pos,
    'expected_position', v_expected_pos,
    'actual_position', v_actual_pos,
    'league_expected_points', round(v_league_expected, 2),
    'league_actual_points', round(v_league_actual, 2),
    'cup_expected_points', round(v_cup_expected, 2),
    'cup_actual_points', round(v_cup_actual, 2),
    'expected_points', round(v_expected_pts, 2),
    'actual_points', round(v_actual_pts, 2),
    'performance_gap', round(v_gap, 2),
    'tier_sensitivity', v_sensitivity,
    'attendance_rate', round(v_fill, 4),
    'min_fill_pct', v_cfg.stadium_min_fill_pct,
    'max_fill_pct', v_cfg.stadium_max_fill_pct,
    'neutral_fill_pct', v_cfg.stadium_neutral_fill_pct
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_compute_gate_total(
  p_capacity int,
  p_table_position int,
  p_history_avg_position numeric,
  p_club_short_name text DEFAULT NULL,
  p_season_id bigint DEFAULT NULL,
  p_division text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_capacity int := greatest(coalesce(p_capacity, 0), 0);
  v_price_per_seat numeric := 20;
  v_total numeric;
  v_fill jsonb;
  v_rate numeric;
BEGIN
  IF p_club_short_name IS NOT NULL AND btrim(p_club_short_name) <> '' THEN
    v_fill := public.competition_compute_stadium_fill(
      p_club_short_name,
      p_season_id,
      p_division
    );

    IF v_fill ? 'error' THEN
      -- Fallback to legacy formula if no season
      v_rate := 0.55
        + 0.35 * ((21 - least(greatest(coalesce(p_table_position, 10), 1), 20))::numeric / 20.0)
        + 0.05 * ((21 - least(greatest(coalesce(p_history_avg_position, 10), 1), 20)) / 20.0);
      v_rate := least(v_rate, 0.95);

      RETURN jsonb_build_object(
        'capacity', v_capacity,
        'table_position', p_table_position,
        'history_avg_position', round(coalesce(p_history_avg_position, 10), 2),
        'attendance_rate', round(v_rate, 4),
        'price_per_seat', v_price_per_seat,
        'total_gate', round(v_capacity * v_rate * v_price_per_seat),
        'legacy_fallback', true
      );
    END IF;

    v_rate := (v_fill ->> 'attendance_rate')::numeric;
    v_total := round(v_capacity * v_rate * v_price_per_seat);

    RETURN v_fill || jsonb_build_object(
      'table_position', (v_fill ->> 'actual_position')::int,
      'price_per_seat', v_price_per_seat,
      'total_gate', v_total
    );
  END IF;

  -- Legacy path when club not provided
  v_rate := 0.55
    + 0.35 * ((21 - least(greatest(coalesce(p_table_position, 10), 1), 20))::numeric / 20.0)
    + 0.05 * ((21 - least(greatest(coalesce(p_history_avg_position, 10), 1), 20)) / 20.0);
  v_rate := least(v_rate, 0.95);
  v_total := round(v_capacity * v_rate * v_price_per_seat);

  RETURN jsonb_build_object(
    'capacity', v_capacity,
    'table_position', p_table_position,
    'history_avg_position', round(coalesce(p_history_avg_position, 10), 2),
    'attendance_rate', round(v_rate, 4),
    'price_per_seat', v_price_per_seat,
    'total_gate', v_total,
    'legacy_fallback', true
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_estimate_gate_for_club(
  p_club_short_name text,
  p_season_id bigint DEFAULT NULL,
  p_division text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_division text;
  v_capacity int;
  v_pos int;
  v_hist numeric;
BEGIN
  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true AND status = 'active'
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  IF v_season_id IS NULL THEN
    RETURN jsonb_build_object('error', 'No active season');
  END IF;

  IF p_division IS NULL THEN
    SELECT ccs.division INTO v_division
    FROM public.competition_club_seasons ccs
    WHERE ccs.season_id = v_season_id
      AND ccs.club_short_name = p_club_short_name
    LIMIT 1;
  ELSE
    v_division := p_division;
  END IF;

  SELECT coalesce(c."Capacity", 0)::int INTO v_capacity
  FROM public."Clubs" c
  WHERE c."ShortName" = p_club_short_name;

  v_pos := public.competition_club_table_position(
    v_season_id,
    coalesce(v_division, 'superleague'),
    p_club_short_name
  );
  v_hist := public.competition_club_history_avg_position(p_club_short_name, 5);

  RETURN public.competition_compute_gate_total(
    v_capacity,
    v_pos,
    v_hist,
    p_club_short_name,
    v_season_id,
    v_division
  ) || jsonb_build_object(
    'club_short_name', p_club_short_name,
    'season_id', v_season_id,
    'division', v_division,
    'history_avg_position', round(v_hist, 2)
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Admin views + RPCs
-- ---------------------------------------------------------------------------

DROP VIEW IF EXISTS public.competition_club_attendance_admin_public;
CREATE VIEW public.competition_club_attendance_admin_public
WITH (security_invoker = false)
AS
SELECT
  p.prestige_rank,
  p.club_short_name,
  p.club_name,
  p.capacity,
  p.rolling_points,
  p.composite_score,
  public.competition_club_tier(p.club_short_name) AS effective_tier,
  o.tier_override,
  c.manager_rating,
  (fill.d ->> 'expected_points')::numeric AS expected_points,
  (fill.d ->> 'actual_points')::numeric AS actual_points,
  (fill.d ->> 'performance_gap')::numeric AS performance_gap,
  round((fill.d ->> 'attendance_rate')::numeric * 100, 1) AS fill_pct
FROM public.competition_club_prestige_public p
JOIN public."Clubs" c ON c."ShortName" = p.club_short_name
LEFT JOIN public.competition_club_tier_override o ON o.club_short_name = p.club_short_name
CROSS JOIN LATERAL (
  SELECT public.competition_compute_stadium_fill(p.club_short_name) AS d
) fill
ORDER BY p.prestige_rank;

CREATE OR REPLACE FUNCTION public.admin_update_stadium_attendance_settings(p_settings jsonb)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  UPDATE public.global_settings
  SET
    stadium_min_fill_pct = coalesce((p_settings ->> 'stadium_min_fill_pct')::numeric, stadium_min_fill_pct),
    stadium_max_fill_pct = coalesce((p_settings ->> 'stadium_max_fill_pct')::numeric, stadium_max_fill_pct),
    stadium_neutral_fill_pct = coalesce((p_settings ->> 'stadium_neutral_fill_pct')::numeric, stadium_neutral_fill_pct),
    stadium_rolling_seasons = coalesce((p_settings ->> 'stadium_rolling_seasons')::smallint, stadium_rolling_seasons),
    stadium_big_club_max_rank = coalesce((p_settings ->> 'stadium_big_club_max_rank')::smallint, stadium_big_club_max_rank),
    stadium_medium_club_max_rank = coalesce((p_settings ->> 'stadium_medium_club_max_rank')::smallint, stadium_medium_club_max_rank),
    stadium_capacity_prestige_weight = coalesce((p_settings ->> 'stadium_capacity_prestige_weight')::numeric, stadium_capacity_prestige_weight),
    stadium_capacity_prestige_ref = coalesce((p_settings ->> 'stadium_capacity_prestige_ref')::integer, stadium_capacity_prestige_ref),
    stadium_big_club_sensitivity = coalesce((p_settings ->> 'stadium_big_club_sensitivity')::numeric, stadium_big_club_sensitivity),
    stadium_medium_club_sensitivity = coalesce((p_settings ->> 'stadium_medium_club_sensitivity')::numeric, stadium_medium_club_sensitivity),
    stadium_low_club_sensitivity = coalesce((p_settings ->> 'stadium_low_club_sensitivity')::numeric, stadium_low_club_sensitivity),
    stadium_overperform_cap = coalesce((p_settings ->> 'stadium_overperform_cap')::numeric, stadium_overperform_cap),
    stadium_points_gap_scale = coalesce((p_settings ->> 'stadium_points_gap_scale')::numeric, stadium_points_gap_scale),
    stadium_league_expect_weight = coalesce((p_settings ->> 'stadium_league_expect_weight')::numeric, stadium_league_expect_weight),
    stadium_cup_expect_weight = coalesce((p_settings ->> 'stadium_cup_expect_weight')::numeric, stadium_cup_expect_weight),
    stadium_league_perf_weight = coalesce((p_settings ->> 'stadium_league_perf_weight')::numeric, stadium_league_perf_weight),
    stadium_cup_perf_weight = coalesce((p_settings ->> 'stadium_cup_perf_weight')::numeric, stadium_cup_perf_weight),
    stadium_manager_lift_threshold = coalesce((p_settings ->> 'stadium_manager_lift_threshold')::smallint, stadium_manager_lift_threshold),
    stadium_manager_lift_max_rating = coalesce((p_settings ->> 'stadium_manager_lift_max_rating')::smallint, stadium_manager_lift_max_rating),
    stadium_manager_lift_max_positions_med = coalesce((p_settings ->> 'stadium_manager_lift_max_positions_med')::numeric, stadium_manager_lift_max_positions_med),
    stadium_manager_lift_max_positions_low = coalesce((p_settings ->> 'stadium_manager_lift_max_positions_low')::numeric, stadium_manager_lift_max_positions_low),
    stadium_expected_cup_super8_pts = coalesce((p_settings ->> 'stadium_expected_cup_super8_pts')::numeric, stadium_expected_cup_super8_pts),
    stadium_expected_cup_plate_pts = coalesce((p_settings ->> 'stadium_expected_cup_plate_pts')::numeric, stadium_expected_cup_plate_pts),
    stadium_expected_cup_shield_pts = coalesce((p_settings ->> 'stadium_expected_cup_shield_pts')::numeric, stadium_expected_cup_shield_pts),
    stadium_expected_cup_spoon_pts = coalesce((p_settings ->> 'stadium_expected_cup_spoon_pts')::numeric, stadium_expected_cup_spoon_pts),
    stadium_expected_cup_league_cup_pts = coalesce((p_settings ->> 'stadium_expected_cup_league_cup_pts')::numeric, stadium_expected_cup_league_cup_pts),
    updated_at = now()
  WHERE id = 1;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_set_club_tier_override(
  p_club_short_name text,
  p_tier text DEFAULT NULL,
  p_notes text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_tier IS NULL OR btrim(p_tier) = '' OR lower(btrim(p_tier)) = 'auto' THEN
    DELETE FROM public.competition_club_tier_override
    WHERE club_short_name = p_club_short_name;
    RETURN;
  END IF;

  IF lower(btrim(p_tier)) NOT IN ('big', 'medium', 'low') THEN
    RAISE EXCEPTION 'Tier must be big, medium, low, or auto';
  END IF;

  INSERT INTO public.competition_club_tier_override (club_short_name, tier_override, notes, updated_at)
  VALUES (p_club_short_name, lower(btrim(p_tier)), p_notes, now())
  ON CONFLICT (club_short_name) DO UPDATE
  SET tier_override = excluded.tier_override,
      notes = coalesce(excluded.notes, competition_club_tier_override.notes),
      updated_at = now();
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_set_club_manager_rating(
  p_club_short_name text,
  p_rating smallint DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  UPDATE public."Clubs"
  SET manager_rating = p_rating
  WHERE "ShortName" = p_club_short_name;
END;
$function$;

-- Recreate global_settings_public (preserve existing columns + stadium attendance)
DROP VIEW IF EXISTS public.global_settings_public;

CREATE VIEW public.global_settings_public
WITH (security_invoker = false)
AS
SELECT
  id,
  transfer_window_open,
  draft_auction_enabled,
  draft_auction_start_time,
  updated_at,
  league_phase,
  wage_pct_superleague,
  wage_pct_championship,
  stadium_cost_tier1,
  stadium_cost_tier2,
  stadium_cost_tier3,
  stadium_capacity_tier_mid,
  stadium_capacity_tier_high,
  stadium_expansion_cancel_penalty,
  hg_sub_band1_max,
  hg_sub_band1_per_player,
  hg_sub_band2_max,
  hg_sub_band2_per_player,
  hg_sub_band3_per_player,
  youth_sub_band1_max,
  youth_sub_band1_per_player,
  youth_sub_band2_max,
  youth_sub_band2_per_player,
  youth_sub_band3_max,
  youth_sub_band3_per_player,
  youth_sub_band4_per_player,
  bnb_max_rating,
  bnb_min_players,
  bnb_per_player,
  tv_per_match_amount,
  tv_matches_per_month,
  tv_club_min_season,
  tv_club_max_season,
  tv_weight_top8_clash,
  tv_weight_title_race,
  tv_weight_promotion,
  tv_weight_relegation,
  tv_weight_super8,
  tv_weight_playoff,
  tv_weight_dry_spell,
  tv_weight_below_min,
  challenge_default_prize,
  challenge_period_bonus,
  wage_34plus_min_rating,
  wage_34plus_per_player,
  star_tax_min_rating,
  star_tax_per_player,
  emergency_tac_pct,
  emergency_tac_threshold,
  stadium_min_fill_pct,
  stadium_max_fill_pct,
  stadium_neutral_fill_pct,
  stadium_rolling_seasons,
  stadium_big_club_max_rank,
  stadium_medium_club_max_rank,
  stadium_capacity_prestige_weight,
  stadium_capacity_prestige_ref,
  stadium_big_club_sensitivity,
  stadium_medium_club_sensitivity,
  stadium_low_club_sensitivity,
  stadium_overperform_cap,
  stadium_points_gap_scale,
  stadium_league_expect_weight,
  stadium_cup_expect_weight,
  stadium_league_perf_weight,
  stadium_cup_perf_weight,
  stadium_manager_lift_threshold,
  stadium_manager_lift_max_rating,
  stadium_manager_lift_max_positions_med,
  stadium_manager_lift_max_positions_low,
  stadium_expected_cup_super8_pts,
  stadium_expected_cup_plate_pts,
  stadium_expected_cup_shield_pts,
  stadium_expected_cup_spoon_pts,
  stadium_expected_cup_league_cup_pts,
  (
    COALESCE(draft_auction_enabled, false)
    AND draft_auction_start_time IS NOT NULL
    AND draft_random_finish_time IS NOT NULL
    AND now() >= draft_auction_start_time
    AND now() < draft_random_finish_time
  ) AS draft_bidding_open
FROM public.global_settings;

-- RLS
ALTER TABLE public.competition_club_season_ranking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_club_tier_override ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_club_season_ranking_select ON public.competition_club_season_ranking;
CREATE POLICY competition_club_season_ranking_select ON public.competition_club_season_ranking
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_club_season_ranking_admin ON public.competition_club_season_ranking;
CREATE POLICY competition_club_season_ranking_admin ON public.competition_club_season_ranking
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS competition_club_tier_override_select ON public.competition_club_tier_override;
CREATE POLICY competition_club_tier_override_select ON public.competition_club_tier_override
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_club_tier_override_admin ON public.competition_club_tier_override;
CREATE POLICY competition_club_tier_override_admin ON public.competition_club_tier_override
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.competition_club_season_ranking TO authenticated;
GRANT SELECT ON public.competition_club_prestige_public TO authenticated;
GRANT SELECT ON public.competition_club_attendance_admin_public TO authenticated;
GRANT SELECT ON public.global_settings_public TO authenticated;
GRANT SELECT ON public.global_settings_public TO anon;

GRANT EXECUTE ON FUNCTION public.competition_club_ranking_recompute_season(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_club_ranking_recompute_all() TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_compute_stadium_fill(text, bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_stadium_attendance_settings(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_club_tier_override(text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_club_manager_rating(text, smallint) TO authenticated;

-- Gate settlement uses club prestige fill (not legacy position-only formula)
CREATE OR REPLACE FUNCTION public.competition_settle_fixture_gates(p_fixture_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_capacity int;
  v_pos int;
  v_hist numeric;
  v_breakdown jsonb;
  v_total numeric;
  v_home_share numeric;
  v_away_share numeric;
  v_desc text;
  v_home_club text;
  v_away_club text;
  v_division text;
BEGIN
  IF p_fixture_id IS NULL THEN
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.competition_finance_ledger
    WHERE fixture_id = p_fixture_id
      AND entry_type IN ('gate_league_home', 'gate_cup_share')
  ) THEN
    RETURN;
  END IF;

  SELECT * INTO v_fixture
  FROM public.competition_fixtures
  WHERE id = p_fixture_id
    AND status = 'played'
    AND home_goals IS NOT NULL
    AND away_goals IS NOT NULL;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  v_home_club := v_fixture.home_club_short_name;
  v_away_club := v_fixture.away_club_short_name;

  IF v_fixture.competition_type = 'cup' THEN
    SELECT ccs.division INTO v_division
    FROM public.competition_club_seasons ccs
    WHERE ccs.season_id = v_fixture.season_id
      AND ccs.club_short_name = v_home_club;
  ELSE
    v_division := v_fixture.division;
  END IF;

  v_division := coalesce(v_division, 'superleague');

  SELECT coalesce(c."Capacity", 0)::int INTO v_capacity
  FROM public."Clubs" c
  WHERE c."ShortName" = v_home_club;

  v_pos := public.competition_club_table_position(
    v_fixture.season_id,
    v_division,
    v_home_club
  );
  v_hist := public.competition_club_history_avg_position(v_home_club, 5);
  v_breakdown := public.competition_compute_gate_total(
    v_capacity,
    v_pos,
    v_hist,
    v_home_club,
    v_fixture.season_id,
    v_division
  );
  v_total := (v_breakdown ->> 'total_gate')::numeric;

  IF v_total IS NULL OR v_total <= 0 THEN
    RETURN;
  END IF;

  IF v_fixture.competition_type = 'league' THEN
    v_desc := format(
      'Gate MD%s — %s vs %s (home 100%%) · fill %s%%',
      v_fixture.matchday,
      v_home_club,
      v_away_club,
      round(((v_breakdown ->> 'attendance_rate')::numeric) * 100, 1)
    );

    PERFORM public.competition_credit_club_balance(v_home_club, v_total);

    INSERT INTO public.competition_finance_ledger (
      season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
    )
    VALUES (
      v_fixture.season_id,
      p_fixture_id,
      v_home_club,
      'gate_league_home',
      v_total,
      v_desc,
      v_breakdown
    );
  ELSIF v_fixture.competition_type = 'cup' THEN
    v_home_share := round(v_total / 2.0, 2);
    v_away_share := v_total - v_home_share;

    v_desc := format(
      '%s R%s — %s vs %s (50/50 gate)',
      upper(v_fixture.cup_code),
      v_fixture.cup_round,
      v_home_club,
      v_away_club
    );

    PERFORM public.competition_credit_club_balance(v_home_club, v_home_share);
    PERFORM public.competition_credit_club_balance(v_away_club, v_away_share);

    INSERT INTO public.competition_finance_ledger (
      season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
    )
    VALUES
      (
        v_fixture.season_id,
        p_fixture_id,
        v_home_club,
        'gate_cup_share',
        v_home_share,
        v_desc || ' (home)',
        v_breakdown
      ),
      (
        v_fixture.season_id,
        p_fixture_id,
        v_away_club,
        'gate_cup_share',
        v_away_share,
        v_desc || ' (away)',
        v_breakdown
      );
  END IF;
END;
$function$;

NOTIFY pgrst, 'reload schema';
