-- =============================================================================
-- GPSL real-world calendar: 1 UK week (Fri 19:00 → Fri 19:00) = 1 GPSL month
-- Run once after competition_phase1_fixtures.sql (and matchday/cup SQL applied).
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.competition_season_calendar (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  gpsl_month text NOT NULL CHECK (
    gpsl_month IN (
      'august', 'september', 'october', 'november', 'december',
      'january', 'february', 'march', 'april', 'may'
    )
  ),
  sort_order smallint NOT NULL CHECK (sort_order >= 1 AND sort_order <= 10),
  unlock_at timestamptz NOT NULL,
  lock_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_season_calendar_unique UNIQUE (season_id, gpsl_month),
  CONSTRAINT competition_season_calendar_window CHECK (lock_at > unlock_at)
);

CREATE INDEX IF NOT EXISTS competition_season_calendar_season_idx
  ON public.competition_season_calendar (season_id, sort_order);

CREATE TABLE IF NOT EXISTS public.competition_season_calendar_config (
  season_id bigint PRIMARY KEY REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  anchor_unlock_at timestamptz NOT NULL,
  timezone text NOT NULL DEFAULT 'Europe/London',
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_gpsl_month_sort(p_month text)
RETURNS smallint
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE p_month
    WHEN 'august' THEN 1
    WHEN 'september' THEN 2
    WHEN 'october' THEN 3
    WHEN 'november' THEN 4
    WHEN 'december' THEN 5
    WHEN 'january' THEN 6
    WHEN 'february' THEN 7
    WHEN 'march' THEN 8
    WHEN 'april' THEN 9
    WHEN 'may' THEN 10
    ELSE NULL
  END;
$$;

CREATE OR REPLACE FUNCTION public.competition_gpsl_month_label(p_month text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT initcap(p_month);
$$;

/** Active GPSL month for season at p_at (default now()), or NULL if none / calendar off. */
CREATE OR REPLACE FUNCTION public.competition_active_gpsl_month(
  p_season_id bigint,
  p_at timestamptz DEFAULT now()
)
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_month text;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.competition_season_calendar_config c
    WHERE c.season_id = p_season_id
  ) THEN
    RETURN NULL;
  END IF;

  SELECT m.gpsl_month INTO v_month
  FROM public.competition_season_calendar m
  WHERE m.season_id = p_season_id
    AND p_at >= m.unlock_at
    AND p_at < m.lock_at
  ORDER BY m.sort_order
  LIMIT 1;

  RETURN v_month;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_assert_fixture_month_unlocked(p_fixture_id bigint)
RETURNS void
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_active text;
  v_unlock timestamptz;
  v_lock timestamptz;
BEGIN
  IF public.is_gpsl_admin() THEN
    RETURN;
  END IF;

  SELECT f.* INTO v_fixture
  FROM public.competition_fixtures f
  WHERE f.id = p_fixture_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.competition_season_calendar_config c
    WHERE c.season_id = v_fixture.season_id
  ) THEN
    RETURN;
  END IF;

  v_active := public.competition_active_gpsl_month(v_fixture.season_id, now());

  IF v_active IS NOT NULL AND v_active = v_fixture.gpsl_month THEN
    RETURN;
  END IF;

  SELECT unlock_at, lock_at
  INTO v_unlock, v_lock
  FROM public.competition_season_calendar m
  WHERE m.season_id = v_fixture.season_id
    AND m.gpsl_month = v_fixture.gpsl_month;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No calendar window for GPSL %', public.competition_gpsl_month_label(v_fixture.gpsl_month);
  END IF;

  IF now() < v_unlock THEN
    RAISE EXCEPTION '% matches unlock at % UK (Fri 19:00 week)',
      public.competition_gpsl_month_label(v_fixture.gpsl_month),
      to_char(v_unlock AT TIME ZONE 'Europe/London', 'Dy DD Mon YYYY HH24:MI');
  END IF;

  RAISE EXCEPTION '% matches locked since % UK',
    public.competition_gpsl_month_label(v_fixture.gpsl_month),
    to_char(v_lock AT TIME ZONE 'Europe/London', 'Dy DD Mon YYYY HH24:MI');
END;
$function$;

-- Block new submissions outside the active GPSL month (confirm/reject still allowed).
CREATE OR REPLACE FUNCTION public.competition_result_submission_calendar_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  PERFORM public.competition_assert_fixture_month_unlocked(NEW.fixture_id);
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS competition_result_submission_calendar_guard
  ON public.competition_result_submissions;

CREATE TRIGGER competition_result_submission_calendar_guard
  BEFORE INSERT ON public.competition_result_submissions
  FOR EACH ROW
  EXECUTE FUNCTION public.competition_result_submission_calendar_guard();

-- ---------------------------------------------------------------------------
-- Admin: set anchor (first real-world Fri 19:00 UK = GPSL August unlock)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_admin_set_season_calendar(
  p_season_id bigint,
  p_anchor_local timestamp without time zone
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season public.competition_seasons;
  v_anchor timestamptz;
  v_months text[] := ARRAY[
    'august', 'september', 'october', 'november', 'december',
    'january', 'february', 'march', 'april', 'may'
  ];
  v_month text;
  v_i int;
  v_unlock timestamptz;
  v_lock timestamptz;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_season
  FROM public.competition_seasons
  WHERE id = p_season_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Season not found';
  END IF;

  IF p_anchor_local IS NULL THEN
    RAISE EXCEPTION 'Anchor date/time required';
  END IF;

  v_anchor := (p_anchor_local AT TIME ZONE 'Europe/London');

  IF extract(dow FROM (v_anchor AT TIME ZONE 'Europe/London'))::int <> 5 THEN
    RAISE EXCEPTION 'Anchor must be a Friday in UK time (got %)',
      to_char(v_anchor AT TIME ZONE 'Europe/London', 'Dy DD Mon YYYY');
  END IF;

  IF extract(hour FROM (v_anchor AT TIME ZONE 'Europe/London'))::int <> 19 THEN
    RAISE EXCEPTION 'Anchor must be 19:00 UK time (7pm)';
  END IF;

  DELETE FROM public.competition_season_calendar WHERE season_id = p_season_id;
  DELETE FROM public.competition_season_calendar_config WHERE season_id = p_season_id;

  INSERT INTO public.competition_season_calendar_config (season_id, anchor_unlock_at)
  VALUES (p_season_id, v_anchor);

  FOR v_i IN 1..array_length(v_months, 1) LOOP
    v_month := v_months[v_i];
    v_unlock := v_anchor + ((v_i - 1) * interval '7 days');
    v_lock := v_unlock + interval '7 days';

    INSERT INTO public.competition_season_calendar (
      season_id, gpsl_month, sort_order, unlock_at, lock_at
    )
    VALUES (p_season_id, v_month, v_i::smallint, v_unlock, v_lock);
  END LOOP;

  RETURN jsonb_build_object(
    'season_id', p_season_id,
    'anchor_uk',
    to_char(v_anchor AT TIME ZONE 'Europe/London', 'YYYY-MM-DD HH24:MI'),
    'months', 10,
    'season_ends_uk',
    to_char((v_anchor + interval '70 days') AT TIME ZONE 'Europe/London', 'YYYY-MM-DD HH24:MI')
  );
END;
$function$;

-- Shift all future month boundaries (insert break / pause).
CREATE OR REPLACE FUNCTION public.competition_admin_insert_calendar_break(
  p_season_id bigint,
  p_weeks integer DEFAULT 1
)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_weeks int;
  v_shift interval;
  v_count int;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  v_weeks := greatest(coalesce(p_weeks, 1), 1);
  v_shift := (v_weeks * interval '7 days');

  UPDATE public.competition_season_calendar m
  SET
    unlock_at = m.unlock_at + v_shift,
    lock_at = m.lock_at + v_shift
  WHERE m.season_id = p_season_id
    AND m.lock_at > now();

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_clear_season_calendar(p_season_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  DELETE FROM public.competition_season_calendar WHERE season_id = p_season_id;
  DELETE FROM public.competition_season_calendar_config WHERE season_id = p_season_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public views
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_season_calendar_public
WITH (security_invoker = false)
AS
SELECT
  m.season_id,
  s.label AS season_label,
  m.gpsl_month,
  public.competition_gpsl_month_label(m.gpsl_month) AS gpsl_month_label,
  m.sort_order,
  m.unlock_at,
  m.lock_at,
  (now() >= m.unlock_at AND now() < m.lock_at) AS is_active,
  (now() >= m.unlock_at) AS has_started,
  (now() < m.unlock_at) AS is_future,
  (now() >= m.lock_at) AS is_locked
FROM public.competition_season_calendar m
JOIN public.competition_seasons s ON s.id = m.season_id
WHERE s.is_current = true AND s.status = 'active'
ORDER BY m.sort_order;

CREATE OR REPLACE VIEW public.competition_calendar_status_public
WITH (security_invoker = false)
AS
SELECT
  s.id AS season_id,
  s.label AS season_label,
  cfg.anchor_unlock_at,
  cfg.timezone,
  EXISTS (
    SELECT 1 FROM public.competition_season_calendar_config c
    WHERE c.season_id = s.id
  ) AS calendar_configured,
  active.gpsl_month AS active_gpsl_month,
  public.competition_gpsl_month_label(active.gpsl_month) AS active_gpsl_month_label,
  active.unlock_at AS active_unlock_at,
  active.lock_at AS active_lock_at,
  nxt.gpsl_month AS next_gpsl_month,
  nxt.unlock_at AS next_unlock_at,
  CASE
    WHEN active.gpsl_month IS NOT NULL THEN 'in_month'
    WHEN NOT EXISTS (
      SELECT 1 FROM public.competition_season_calendar_config c WHERE c.season_id = s.id
    ) THEN 'pre_season'
    WHEN cfg.anchor_unlock_at IS NOT NULL AND now() < cfg.anchor_unlock_at THEN 'pre_season'
    WHEN now() >= (
      SELECT max(c2.lock_at) FROM public.competition_season_calendar c2 WHERE c2.season_id = s.id
    ) THEN 'after_season'
    ELSE 'between_months'
  END AS calendar_phase,
  CASE
    WHEN active.gpsl_month IS NOT NULL THEN
      public.competition_gpsl_month_label(active.gpsl_month)
    WHEN now() >= (
      SELECT max(c2.lock_at) FROM public.competition_season_calendar c2 WHERE c2.season_id = s.id
    ) THEN 'Post-season'
    WHEN nxt.gpsl_month IS NOT NULL THEN
      public.competition_gpsl_month_label(nxt.gpsl_month)
    ELSE 'Pre-Season'
  END AS nav_month_label
FROM public.competition_seasons s
LEFT JOIN public.competition_season_calendar_config cfg ON cfg.season_id = s.id
LEFT JOIN LATERAL (
  SELECT m.gpsl_month, m.unlock_at, m.lock_at
  FROM public.competition_season_calendar m
  WHERE m.season_id = s.id
    AND now() >= m.unlock_at
    AND now() < m.lock_at
  ORDER BY m.sort_order
  LIMIT 1
) active ON true
LEFT JOIN LATERAL (
  SELECT m.gpsl_month, m.unlock_at
  FROM public.competition_season_calendar m
  WHERE m.season_id = s.id
    AND m.unlock_at > now()
  ORDER BY m.unlock_at
  LIMIT 1
) nxt ON true
WHERE s.is_current = true AND s.status = 'active';

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_season_calendar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_season_calendar_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_season_calendar_select ON public.competition_season_calendar;
CREATE POLICY competition_season_calendar_select ON public.competition_season_calendar
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_season_calendar_admin ON public.competition_season_calendar;
CREATE POLICY competition_season_calendar_admin ON public.competition_season_calendar
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS competition_season_calendar_config_select ON public.competition_season_calendar_config;
CREATE POLICY competition_season_calendar_config_select ON public.competition_season_calendar_config
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_season_calendar_config_admin ON public.competition_season_calendar_config;
CREATE POLICY competition_season_calendar_config_admin ON public.competition_season_calendar_config
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.competition_season_calendar TO authenticated;
GRANT SELECT ON public.competition_season_calendar_config TO authenticated;
GRANT SELECT ON public.competition_season_calendar_public TO authenticated;
GRANT SELECT ON public.competition_season_calendar_public TO anon;
GRANT SELECT ON public.competition_calendar_status_public TO authenticated;
GRANT SELECT ON public.competition_calendar_status_public TO anon;

GRANT EXECUTE ON FUNCTION public.competition_admin_set_season_calendar(bigint, timestamp) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_insert_calendar_break(bigint, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_clear_season_calendar(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_active_gpsl_month(bigint, timestamptz) TO authenticated;

NOTIFY pgrst, 'reload schema';
