-- =============================================================================
-- GPSL — Season challenges (admin targets, stat triggers, instant award)
-- Run once after competition_tv_revenue.sql (player stats + ledger types).
-- =============================================================================
-- Start window: Aug–Dec (complete by mid-season). Mid window: Jan–May (EOS).
-- Each club earns prize_challenge when a target is met; first to finish all
-- challenges in a window earns the period bonus (global_settings).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Global defaults
-- ---------------------------------------------------------------------------

ALTER TABLE public.global_settings
  ADD COLUMN IF NOT EXISTS challenge_default_prize numeric(14, 2) NOT NULL DEFAULT 1000000,
  ADD COLUMN IF NOT EXISTS challenge_period_bonus numeric(14, 2) NOT NULL DEFAULT 5000000;

-- ---------------------------------------------------------------------------
-- Ledger type
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_finance_ledger
  DROP CONSTRAINT IF EXISTS competition_finance_ledger_entry_type_check;

ALTER TABLE public.competition_finance_ledger
  ADD CONSTRAINT competition_finance_ledger_entry_type_check
  CHECK (
    entry_type IN (
      'gate_league_home',
      'gate_cup_share',
      'prize',
      'prize_league',
      'prize_cup',
      'prize_challenge',
      'tv_revenue',
      'gov_hg_subsidy',
      'gov_youth_subsidy',
      'gov_bnb_subsidy',
      'adjustment',
      'admin_one_off_injection',
      'admin_purchase_payment',
      'transfer_sale',
      'transfer_purchase',
      'transfer_agent_fee',
      'transfer_foreign_sale',
      'transfer_overflow_release',
      'loan_drawdown',
      'loan_repayment_principal',
      'loan_interest_payment',
      'infra_maintenance',
      'infra_purchase',
      'infra_expansion',
      'infra_expansion_refund',
      'infra_expansion_penalty'
    )
  );

DROP VIEW IF EXISTS public.global_settings_public;

CREATE VIEW public.global_settings_public
WITH (security_invoker = false)
AS
SELECT
  id,
  transfer_window_open,
  draft_auction_enabled,
  draft_auction_start_time,
  updated_at,
  wage_pct_superleague,
  wage_pct_championship,
  stadium_cost_tier1,
  stadium_cost_tier2,
  stadium_cost_tier3,
  stadium_capacity_tier_mid,
  stadium_capacity_tier_high,
  stadium_expansion_cancel_penalty,
  hg_sub_band1_max,
  hg_sub_band1_per_player,
  hg_sub_band2_max,
  hg_sub_band2_per_player,
  hg_sub_band3_per_player,
  youth_sub_band1_max,
  youth_sub_band1_per_player,
  youth_sub_band2_max,
  youth_sub_band2_per_player,
  youth_sub_band3_max,
  youth_sub_band3_per_player,
  youth_sub_band4_per_player,
  bnb_max_rating,
  bnb_min_players,
  bnb_per_player,
  tv_per_match_amount,
  tv_matches_per_month,
  tv_club_min_season,
  tv_club_max_season,
  tv_weight_top8_clash,
  tv_weight_title_race,
  tv_weight_promotion,
  tv_weight_relegation,
  tv_weight_super8,
  tv_weight_playoff,
  tv_weight_dry_spell,
  tv_weight_below_min,
  challenge_default_prize,
  challenge_period_bonus
FROM public.global_settings;

GRANT SELECT ON public.global_settings_public TO authenticated;
GRANT SELECT ON public.global_settings_public TO anon;

-- ---------------------------------------------------------------------------
-- Challenge config + awards
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_challenge_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  window_phase text NOT NULL CHECK (window_phase IN ('start', 'mid')),
  gpsl_month_from text NOT NULL CHECK (
    gpsl_month_from IN (
      'august', 'september', 'october', 'november', 'december',
      'january', 'february', 'march', 'april', 'may'
    )
  ),
  gpsl_month_to text NOT NULL CHECK (
    gpsl_month_to IN (
      'august', 'september', 'october', 'november', 'december',
      'january', 'february', 'march', 'april', 'may'
    )
  ),
  stat_type text NOT NULL CHECK (
    stat_type IN (
      'player_max_goals',
      'player_max_assists',
      'club_wins',
      'club_goals_for',
      'club_clean_sheets',
      'club_potm_awards'
    )
  ),
  target_value int NOT NULL CHECK (target_value > 0),
  prize_amount numeric(14, 2) NOT NULL CHECK (prize_amount > 0),
  include_league boolean NOT NULL DEFAULT true,
  include_cup boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order smallint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_challenge_month_order CHECK (
    public.competition_gpsl_month_sort(gpsl_month_from)
    <= public.competition_gpsl_month_sort(gpsl_month_to)
  )
);

CREATE INDEX IF NOT EXISTS competition_challenge_config_season_idx
  ON public.competition_challenge_config (season_id, window_phase, sort_order);

CREATE TABLE IF NOT EXISTS public.competition_challenge_awarded (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  challenge_id bigint NOT NULL REFERENCES public.competition_challenge_config (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  amount numeric(14, 2) NOT NULL CHECK (amount > 0),
  stat_value int NOT NULL,
  awarded_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT competition_challenge_awarded_unique UNIQUE (challenge_id, club_short_name)
);

CREATE TABLE IF NOT EXISTS public.competition_challenge_period_bonus_awarded (
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  window_phase text NOT NULL CHECK (window_phase IN ('start', 'mid')),
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  amount numeric(14, 2) NOT NULL CHECK (amount > 0),
  awarded_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (season_id, window_phase)
);

ALTER TABLE public.competition_challenge_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_challenge_awarded ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_challenge_period_bonus_awarded ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_challenge_config_select ON public.competition_challenge_config;
CREATE POLICY competition_challenge_config_select ON public.competition_challenge_config
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_challenge_awarded_select ON public.competition_challenge_awarded;
CREATE POLICY competition_challenge_awarded_select ON public.competition_challenge_awarded
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_challenge_period_bonus_select ON public.competition_challenge_period_bonus_awarded;
CREATE POLICY competition_challenge_period_bonus_select ON public.competition_challenge_period_bonus_awarded
  FOR SELECT TO authenticated USING (true);

-- ---------------------------------------------------------------------------
-- Stat evaluation
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_challenge_comp_types(
  p_include_league boolean,
  p_include_cup boolean
)
RETURNS text[]
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT coalesce(array_agg(t), ARRAY[]::text[])
  FROM (
    SELECT 'league'::text AS t WHERE coalesce(p_include_league, true)
    UNION ALL
    SELECT 'cup'::text WHERE coalesce(p_include_cup, false)
  ) x;
$$;

CREATE OR REPLACE FUNCTION public.competition_challenge_stat_value(
  p_season_id bigint,
  p_club_short_name text,
  p_stat_type text,
  p_month_from text,
  p_month_to text,
  p_include_league boolean,
  p_include_cup boolean
)
RETURNS int
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_types text[];
  v_from_sort int;
  v_to_sort int;
  v_val int := 0;
BEGIN
  v_types := public.competition_challenge_comp_types(p_include_league, p_include_cup);
  IF v_types = ARRAY[]::text[] THEN
    RETURN 0;
  END IF;

  v_from_sort := public.competition_gpsl_month_sort(p_month_from);
  v_to_sort := public.competition_gpsl_month_sort(p_month_to);

  IF p_stat_type = 'player_max_goals' THEN
    SELECT coalesce(max(x.goals), 0)::int INTO v_val
    FROM (
      SELECT sum(m.goals)::int AS goals
      FROM public.competition_match_player_stats m
      JOIN public.competition_fixtures f ON f.id = m.fixture_id
      WHERE m.season_id = p_season_id
        AND m.club_short_name = p_club_short_name
        AND f.status = 'played'
        AND f.competition_type = ANY (v_types)
        AND public.competition_gpsl_month_sort(f.gpsl_month) BETWEEN v_from_sort AND v_to_sort
      GROUP BY m.player_id
    ) x;

  ELSIF p_stat_type = 'player_max_assists' THEN
    SELECT coalesce(max(x.assists), 0)::int INTO v_val
    FROM (
      SELECT sum(m.assists)::int AS assists
      FROM public.competition_match_player_stats m
      JOIN public.competition_fixtures f ON f.id = m.fixture_id
      WHERE m.season_id = p_season_id
        AND m.club_short_name = p_club_short_name
        AND f.status = 'played'
        AND f.competition_type = ANY (v_types)
        AND public.competition_gpsl_month_sort(f.gpsl_month) BETWEEN v_from_sort AND v_to_sort
      GROUP BY m.player_id
    ) x;

  ELSIF p_stat_type = 'club_wins' THEN
    SELECT count(*)::int INTO v_val
    FROM public.competition_fixtures f
    WHERE f.season_id = p_season_id
      AND f.status = 'played'
      AND f.competition_type = ANY (v_types)
      AND public.competition_gpsl_month_sort(f.gpsl_month) BETWEEN v_from_sort AND v_to_sort
      AND (
        (f.home_club_short_name = p_club_short_name AND f.home_goals > f.away_goals)
        OR (f.away_club_short_name = p_club_short_name AND f.away_goals > f.home_goals)
      );

  ELSIF p_stat_type = 'club_goals_for' THEN
    SELECT coalesce(sum(
      CASE
        WHEN f.home_club_short_name = p_club_short_name THEN f.home_goals
        ELSE f.away_goals
      END
    ), 0)::int INTO v_val
    FROM public.competition_fixtures f
    WHERE f.season_id = p_season_id
      AND f.status = 'played'
      AND f.competition_type = ANY (v_types)
      AND public.competition_gpsl_month_sort(f.gpsl_month) BETWEEN v_from_sort AND v_to_sort
      AND (f.home_club_short_name = p_club_short_name OR f.away_club_short_name = p_club_short_name);

  ELSIF p_stat_type = 'club_clean_sheets' THEN
    SELECT count(*)::int INTO v_val
    FROM public.competition_fixtures f
    WHERE f.season_id = p_season_id
      AND f.status = 'played'
      AND f.competition_type = ANY (v_types)
      AND public.competition_gpsl_month_sort(f.gpsl_month) BETWEEN v_from_sort AND v_to_sort
      AND (
        (f.home_club_short_name = p_club_short_name AND f.away_goals = 0)
        OR (f.away_club_short_name = p_club_short_name AND f.home_goals = 0)
      );

  ELSIF p_stat_type = 'club_potm_awards' THEN
    SELECT coalesce(count(*), 0)::int INTO v_val
    FROM public.competition_match_player_stats m
    JOIN public.competition_fixtures f ON f.id = m.fixture_id
    WHERE m.season_id = p_season_id
      AND m.club_short_name = p_club_short_name
      AND m.is_player_of_match = true
      AND f.status = 'played'
      AND f.competition_type = ANY (v_types)
      AND public.competition_gpsl_month_sort(f.gpsl_month) BETWEEN v_from_sort AND v_to_sort;

  END IF;

  RETURN coalesce(v_val, 0);
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_challenge_window_open(
  p_season_id bigint,
  p_window_phase text,
  p_gpsl_month_to text
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_active text;
  v_active_sort int;
  v_deadline_sort int;
BEGIN
  v_active := public.competition_active_gpsl_month(p_season_id, now());
  v_deadline_sort := public.competition_gpsl_month_sort(p_gpsl_month_to);

  IF v_active IS NULL THEN
    RETURN true;
  END IF;

  v_active_sort := public.competition_gpsl_month_sort(v_active);
  RETURN v_active_sort <= v_deadline_sort;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Award one challenge + period bonus
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_award_challenge(
  p_challenge_id bigint,
  p_club_short_name text,
  p_stat_value int
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_c public.competition_challenge_config;
  v_amount numeric;
BEGIN
  SELECT * INTO v_c
  FROM public.competition_challenge_config
  WHERE id = p_challenge_id
    AND is_active = true;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.competition_challenge_awarded
    WHERE challenge_id = p_challenge_id
      AND club_short_name = p_club_short_name
  ) THEN
    RETURN false;
  END IF;

  IF NOT public.competition_challenge_window_open(
    v_c.season_id, v_c.window_phase, v_c.gpsl_month_to
  ) THEN
    RETURN false;
  END IF;

  v_amount := v_c.prize_amount;
  PERFORM public.competition_credit_club_balance(p_club_short_name, v_amount);

  INSERT INTO public.competition_finance_ledger (
    season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
  )
  VALUES (
    v_c.season_id,
    NULL,
    p_club_short_name,
    'prize_challenge',
    v_amount,
    format('Challenge — %s', v_c.title),
    jsonb_build_object(
      'challenge_id', v_c.id,
      'window_phase', v_c.window_phase,
      'stat_type', v_c.stat_type,
      'target_value', v_c.target_value,
      'stat_value', p_stat_value
    )
  );

  INSERT INTO public.competition_challenge_awarded (
    season_id, challenge_id, club_short_name, amount, stat_value, metadata
  )
  VALUES (
    v_c.season_id,
    p_challenge_id,
    p_club_short_name,
    v_amount,
    p_stat_value,
    jsonb_build_object('title', v_c.title)
  );

  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_try_award_period_bonus(
  p_season_id bigint,
  p_club_short_name text,
  p_window_phase text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_total int;
  v_done int;
  v_bonus numeric;
  v_deadline text;
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.competition_challenge_period_bonus_awarded
    WHERE season_id = p_season_id
      AND window_phase = p_window_phase
  ) THEN
    RETURN false;
  END IF;

  SELECT count(*)::int INTO v_total
  FROM public.competition_challenge_config
  WHERE season_id = p_season_id
    AND window_phase = p_window_phase
    AND is_active = true;

  IF v_total = 0 THEN
    RETURN false;
  END IF;

  SELECT count(*)::int INTO v_done
  FROM public.competition_challenge_awarded a
  JOIN public.competition_challenge_config c ON c.id = a.challenge_id
  WHERE a.season_id = p_season_id
    AND a.club_short_name = p_club_short_name
    AND c.window_phase = p_window_phase
    AND c.is_active = true;

  IF v_done < v_total THEN
    RETURN false;
  END IF;

  SELECT max(c.gpsl_month_to) INTO v_deadline
  FROM public.competition_challenge_config c
  WHERE c.season_id = p_season_id
    AND c.window_phase = p_window_phase
    AND c.is_active = true;

  IF NOT public.competition_challenge_window_open(p_season_id, p_window_phase, v_deadline) THEN
    RETURN false;
  END IF;

  v_bonus := (SELECT challenge_period_bonus FROM public.global_settings WHERE id = 1);

  IF v_bonus IS NULL OR v_bonus <= 0 THEN
    RETURN false;
  END IF;

  PERFORM public.competition_credit_club_balance(p_club_short_name, v_bonus);

  INSERT INTO public.competition_finance_ledger (
    season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
  )
  VALUES (
    p_season_id,
    NULL,
    p_club_short_name,
    'prize_challenge',
    v_bonus,
    format('Challenge bonus — first to complete all %s targets', p_window_phase),
    jsonb_build_object(
      'window_phase', p_window_phase,
      'bonus', true,
      'challenges_completed', v_done
    )
  );

  INSERT INTO public.competition_challenge_period_bonus_awarded (
    season_id, window_phase, club_short_name, amount
  )
  VALUES (p_season_id, p_window_phase, p_club_short_name, v_bonus);

  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_try_award_challenges(
  p_season_id bigint,
  p_club_short_name text
)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_row public.competition_challenge_config;
  v_val int;
  v_awarded int := 0;
  v_phase text;
BEGIN
  IF p_season_id IS NULL OR p_club_short_name IS NULL OR btrim(p_club_short_name) = '' THEN
    RETURN 0;
  END IF;

  FOR v_row IN
    SELECT *
    FROM public.competition_challenge_config
    WHERE season_id = p_season_id
      AND is_active = true
    ORDER BY sort_order, id
  LOOP
    IF EXISTS (
      SELECT 1 FROM public.competition_challenge_awarded
      WHERE challenge_id = v_row.id
        AND club_short_name = p_club_short_name
    ) THEN
      CONTINUE;
    END IF;

    IF NOT public.competition_challenge_window_open(
      p_season_id, v_row.window_phase, v_row.gpsl_month_to
    ) THEN
      CONTINUE;
    END IF;

    v_val := public.competition_challenge_stat_value(
      p_season_id,
      p_club_short_name,
      v_row.stat_type,
      v_row.gpsl_month_from,
      v_row.gpsl_month_to,
      v_row.include_league,
      v_row.include_cup
    );

    IF v_val >= v_row.target_value THEN
      IF public.competition_award_challenge(v_row.id, p_club_short_name, v_val) THEN
        v_awarded := v_awarded + 1;
        PERFORM public.competition_try_award_period_bonus(
          p_season_id, p_club_short_name, v_row.window_phase
        );
      END IF;
    END IF;
  END LOOP;

  RETURN v_awarded;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public views
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_challenges_public
WITH (security_invoker = false)
AS
SELECT
  c.id,
  c.season_id,
  c.title,
  c.description,
  c.window_phase,
  c.gpsl_month_from,
  c.gpsl_month_to,
  public.competition_gpsl_month_label(c.gpsl_month_from) AS gpsl_month_from_label,
  public.competition_gpsl_month_label(c.gpsl_month_to) AS gpsl_month_to_label,
  c.stat_type,
  c.target_value,
  c.prize_amount,
  c.include_league,
  c.include_cup,
  c.is_active,
  c.sort_order
FROM public.competition_challenge_config c
JOIN public.competition_seasons s ON s.id = c.season_id
WHERE s.is_current = true;

GRANT SELECT ON public.competition_challenges_public TO authenticated;
GRANT SELECT ON public.competition_challenges_public TO anon;

CREATE OR REPLACE VIEW public.competition_challenge_awards_public
WITH (security_invoker = false)
AS
SELECT
  a.season_id,
  a.challenge_id,
  c.title AS challenge_title,
  c.window_phase,
  a.club_short_name,
  cl."Club" AS club_name,
  a.amount,
  a.stat_value,
  c.target_value,
  a.awarded_at
FROM public.competition_challenge_awarded a
JOIN public.competition_challenge_config c ON c.id = a.challenge_id
JOIN public."Clubs" cl ON cl."ShortName" = a.club_short_name;

GRANT SELECT ON public.competition_challenge_awards_public TO authenticated;
GRANT SELECT ON public.competition_challenge_awards_public TO anon;

CREATE OR REPLACE FUNCTION public.competition_challenge_club_progress(p_club_short_name text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := btrim(p_club_short_name);
  v_me text := public.my_club_shortname();
  v_season_id bigint;
  v_challenges jsonb := '[]'::jsonb;
  v_row record;
  v_val int;
  v_awarded boolean;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'Club required';
  END IF;

  IF NOT public.is_gpsl_admin() AND (v_me IS NULL OR v_me <> v_club) THEN
    RAISE EXCEPTION 'Not allowed';
  END IF;

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true
  ORDER BY id DESC
  LIMIT 1;

  FOR v_row IN
    SELECT *
    FROM public.competition_challenge_config
    WHERE season_id = v_season_id
      AND is_active = true
    ORDER BY window_phase, sort_order, id
  LOOP
    v_val := public.competition_challenge_stat_value(
      v_season_id,
      v_club,
      v_row.stat_type,
      v_row.gpsl_month_from,
      v_row.gpsl_month_to,
      v_row.include_league,
      v_row.include_cup
    );

    SELECT EXISTS (
      SELECT 1 FROM public.competition_challenge_awarded
      WHERE challenge_id = v_row.id AND club_short_name = v_club
    ) INTO v_awarded;

    v_challenges := v_challenges || jsonb_build_array(
      jsonb_build_object(
        'id', v_row.id,
        'title', v_row.title,
        'window_phase', v_row.window_phase,
        'stat_type', v_row.stat_type,
        'target_value', v_row.target_value,
        'current_value', v_val,
        'prize_amount', v_row.prize_amount,
        'awarded', v_awarded,
        'expired', NOT public.competition_challenge_window_open(
          v_season_id, v_row.window_phase, v_row.gpsl_month_to
        )
      )
    );
  END LOOP;

  RETURN jsonb_build_object(
    'season_id', v_season_id,
    'club_short_name', v_club,
    'challenges', v_challenges
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Admin RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.admin_update_challenge_settings(p_settings jsonb)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  UPDATE public.global_settings
  SET
    challenge_default_prize = coalesce((p_settings->>'challenge_default_prize')::numeric, challenge_default_prize),
    challenge_period_bonus = coalesce((p_settings->>'challenge_period_bonus')::numeric, challenge_period_bonus),
    updated_at = now()
  WHERE id = 1;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_save_challenge(p_challenge jsonb)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint;
  v_season_id bigint;
  v_default numeric;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_challenge IS NULL OR jsonb_typeof(p_challenge) <> 'object' THEN
    RAISE EXCEPTION 'challenge must be a JSON object';
  END IF;

  v_season_id := (p_challenge->>'season_id')::bigint;
  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'season_id required';
  END IF;

  v_default := (SELECT challenge_default_prize FROM public.global_settings WHERE id = 1);

  v_id := nullif(p_challenge->>'id', '')::bigint;

  IF v_id IS NOT NULL THEN
    UPDATE public.competition_challenge_config
    SET
      title = coalesce(p_challenge->>'title', title),
      description = coalesce(p_challenge->>'description', description),
      window_phase = coalesce(p_challenge->>'window_phase', window_phase),
      gpsl_month_from = coalesce(p_challenge->>'gpsl_month_from', gpsl_month_from),
      gpsl_month_to = coalesce(p_challenge->>'gpsl_month_to', gpsl_month_to),
      stat_type = coalesce(p_challenge->>'stat_type', stat_type),
      target_value = coalesce((p_challenge->>'target_value')::int, target_value),
      prize_amount = coalesce((p_challenge->>'prize_amount')::numeric, prize_amount),
      include_league = coalesce((p_challenge->>'include_league')::boolean, include_league),
      include_cup = coalesce((p_challenge->>'include_cup')::boolean, include_cup),
      is_active = coalesce((p_challenge->>'is_active')::boolean, is_active),
      sort_order = coalesce((p_challenge->>'sort_order')::smallint, sort_order),
      updated_at = now()
    WHERE id = v_id AND season_id = v_season_id;
    RETURN v_id;
  END IF;

  INSERT INTO public.competition_challenge_config (
    season_id, title, description, window_phase,
    gpsl_month_from, gpsl_month_to, stat_type, target_value, prize_amount,
    include_league, include_cup, is_active, sort_order
  )
  VALUES (
    v_season_id,
    p_challenge->>'title',
    p_challenge->>'description',
    coalesce(p_challenge->>'window_phase', 'start'),
    coalesce(p_challenge->>'gpsl_month_from', 'august'),
    coalesce(p_challenge->>'gpsl_month_to', 'december'),
    coalesce(p_challenge->>'stat_type', 'club_wins'),
    coalesce((p_challenge->>'target_value')::int, 1),
    coalesce((p_challenge->>'prize_amount')::numeric, v_default),
    coalesce((p_challenge->>'include_league')::boolean, true),
    coalesce((p_challenge->>'include_cup')::boolean, false),
    coalesce((p_challenge->>'is_active')::boolean, true),
    coalesce((p_challenge->>'sort_order')::smallint, 0)
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_delete_challenge(p_challenge_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  DELETE FROM public.competition_challenge_config WHERE id = p_challenge_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_seed_challenge_defaults(p_season_id bigint)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_default numeric;
  v_n int := 0;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    RAISE EXCEPTION 'season_id required';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.competition_challenge_config WHERE season_id = p_season_id
  ) THEN
    RAISE EXCEPTION 'Challenges already exist for this season — delete first or add manually';
  END IF;

  v_default := (SELECT challenge_default_prize FROM public.global_settings WHERE id = 1);

  INSERT INTO public.competition_challenge_config (
    season_id, title, description, window_phase, gpsl_month_from, gpsl_month_to,
    stat_type, target_value, prize_amount, sort_order
  )
  VALUES
    (p_season_id, 'Golden boot', 'Any player reaches 20 league goals', 'start', 'august', 'december', 'player_max_goals', 20, v_default, 1),
    (p_season_id, 'Winning habit', '12 league wins', 'start', 'august', 'december', 'club_wins', 12, v_default, 2),
    (p_season_id, 'Shutout specialists', '6 league clean sheets', 'start', 'august', 'december', 'club_clean_sheets', 6, v_default, 3),
    (p_season_id, 'Goals galore', '40 league goals scored', 'start', 'august', 'december', 'club_goals_for', 40, v_default, 4),
    (p_season_id, 'Star performers', '5 player-of-the-match awards', 'start', 'august', 'december', 'club_potm_awards', 5, v_default, 5),
    (p_season_id, 'Second-half scorer', 'Any player reaches 15 league goals', 'mid', 'january', 'may', 'player_max_goals', 15, v_default, 1),
    (p_season_id, 'Spring surge', '10 league wins', 'mid', 'january', 'may', 'club_wins', 10, v_default, 2),
    (p_season_id, 'Defensive wall', '5 league clean sheets', 'mid', 'january', 'may', 'club_clean_sheets', 5, v_default, 3),
    (p_season_id, 'Free scoring', '35 league goals scored', 'mid', 'january', 'may', 'club_goals_for', 35, v_default, 4),
    (p_season_id, 'Match heroes', '4 player-of-the-match awards', 'mid', 'january', 'may', 'club_potm_awards', 4, v_default, 5);

  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_recheck_challenges(p_season_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_club text;
  v_total int := 0;
  v_n int;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  FOR v_club IN
    SELECT ccs.club_short_name
    FROM public.competition_club_seasons ccs
    WHERE ccs.season_id = v_season_id
      AND ccs.division IN ('superleague', 'championship_a', 'championship_b')
  LOOP
    v_n := public.competition_try_award_challenges(v_season_id, v_club);
    v_total := v_total + v_n;
  END LOOP;

  RETURN jsonb_build_object('season_id', v_season_id, 'challenges_awarded', v_total);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Hooks: check challenges after result confirm
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_confirm_result(
  p_submission_id bigint,
  p_confirmer_player_stats jsonb DEFAULT '[]'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
  v_opponent text;
  v_home_name text;
  v_away_name text;
  v_label text;
  v_home_total smallint;
  v_away_total smallint;
  v_body text;
  v_pen_winner_name text;
  v_confirmer_expected int;
BEGIN
  IF v_club IS NULL THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  IF p_confirmer_player_stats IS NULL OR jsonb_typeof(p_confirmer_player_stats) <> 'array' THEN
    RAISE EXCEPTION 'player_stats must be a JSON array';
  END IF;

  IF jsonb_array_length(p_confirmer_player_stats) = 0 THEN
    RAISE EXCEPTION 'Enter your squad match stats (11 starters) before confirming';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  v_opponent := public.competition_fixture_opponent(v_sub.fixture_id, v_club);
  IF v_opponent <> v_sub.submitted_by_club THEN
    RAISE EXCEPTION 'Only the opponent can confirm this result';
  END IF;

  v_confirmer_expected := public.competition_expected_goals_for_club(v_fixture, v_sub, v_club);

  IF v_fixture.competition_type = 'cup' THEN
    SELECT t.home_total, t.away_total
    INTO v_home_total, v_away_total
    FROM public.competition_cup_open_play_totals(
      v_sub.home_goals, v_sub.away_goals, v_sub.et_home_goals, v_sub.et_away_goals
    ) t;

    IF public.competition_cup_winner_from_submission(
      v_sub.home_goals, v_sub.away_goals, v_sub.et_home_goals, v_sub.et_away_goals,
      v_sub.pen_winner_club_short_name,
      v_fixture.home_club_short_name, v_fixture.away_club_short_name
    ) IS NULL THEN
      RAISE EXCEPTION 'Invalid cup submission — extra time or penalties required';
    END IF;

    UPDATE public.competition_fixtures
    SET home_goals = v_home_total,
        away_goals = v_away_total,
        cup_pen_winner_club_short_name = v_sub.pen_winner_club_short_name,
        status = 'played'
    WHERE id = v_sub.fixture_id;
  ELSE
    v_home_total := v_sub.home_goals;
    v_away_total := v_sub.away_goals;

    UPDATE public.competition_fixtures
    SET home_goals = v_sub.home_goals,
        away_goals = v_sub.away_goals,
        cup_pen_winner_club_short_name = NULL,
        status = 'played'
    WHERE id = v_sub.fixture_id;
  END IF;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);

  PERFORM public.competition_apply_club_player_stats(
    v_fixture.id,
    v_fixture.season_id,
    v_club,
    p_confirmer_player_stats,
    v_confirmer_expected
  );

  PERFORM public.competition_settle_fixture_gates(v_sub.fixture_id);
  PERFORM public.competition_tv_settle_fixture(v_sub.fixture_id);

  PERFORM public.competition_try_award_challenges(v_fixture.season_id, v_fixture.home_club_short_name);
  PERFORM public.competition_try_award_challenges(v_fixture.season_id, v_fixture.away_club_short_name);

  IF v_fixture.competition_type = 'cup' THEN
    PERFORM public.competition_cup_on_fixture_played(v_sub.fixture_id);
  ELSIF v_fixture.competition_type = 'league' THEN
    PERFORM public.competition_try_pay_league_division_prizes(v_fixture.season_id, v_fixture.division);
  END IF;

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = v_club,
      responded_at = now()
  WHERE id = p_submission_id;

  UPDATE public.competition_inbox
  SET read_at = coalesce(read_at, now())
  WHERE submission_id = p_submission_id
    AND recipient_club_short_name = v_club
    AND message_type = 'result_to_confirm';

  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  v_label := CASE
    WHEN v_fixture.competition_type = 'cup' THEN public.competition_cup_fixture_label(v_fixture)
    ELSE format('Matchday %s', v_fixture.matchday)
  END;

  IF v_sub.et_home_goals IS NOT NULL THEN
    v_body := format(
      '%s — %s–%s confirmed (90 min %s–%s, after ET %s–%s).',
      v_label, v_home_total, v_away_total,
      v_sub.home_goals, v_sub.away_goals, v_sub.et_home_goals, v_sub.et_away_goals
    );
  ELSE
    v_body := format(
      '%s — %s–%s confirmed (90 min %s–%s).',
      v_label, v_home_total, v_away_total, v_sub.home_goals, v_sub.away_goals
    );
  END IF;

  IF v_sub.pen_winner_club_short_name IS NOT NULL THEN
    SELECT "Club" INTO v_pen_winner_name FROM public."Clubs" WHERE "ShortName" = v_sub.pen_winner_club_short_name;
    v_body := v_body || format(' Pens: %s won.', coalesce(v_pen_winner_name, v_sub.pen_winner_club_short_name));
  END IF;

  PERFORM public.competition_inbox_notify(
    v_sub.submitted_by_club,
    'result_confirmed',
    v_sub.fixture_id,
    p_submission_id,
    format('Result confirmed: %s vs %s', v_home_name, v_away_name),
    v_body
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_confirm_submission(p_submission_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  UPDATE public.competition_fixtures
  SET home_goals = v_sub.home_goals,
      away_goals = v_sub.away_goals,
      status = 'played'
  WHERE id = v_sub.fixture_id;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);
  PERFORM public.competition_settle_fixture_gates(v_sub.fixture_id);
  PERFORM public.competition_tv_settle_fixture(v_sub.fixture_id);

  PERFORM public.competition_try_award_challenges(v_fixture.season_id, v_fixture.home_club_short_name);
  PERFORM public.competition_try_award_challenges(v_fixture.season_id, v_fixture.away_club_short_name);

  IF v_fixture.competition_type = 'cup' THEN
    PERFORM public.competition_cup_on_fixture_played(v_sub.fixture_id);
  ELSIF v_fixture.competition_type = 'league' THEN
    PERFORM public.competition_try_pay_league_division_prizes(v_fixture.season_id, v_fixture.division);
  END IF;

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = 'ADMIN',
      responded_at = now()
  WHERE id = p_submission_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_record_result(
  p_fixture_id bigint,
  p_home_goals smallint,
  p_away_goals smallint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_home_goals IS NULL OR p_away_goals IS NULL OR p_home_goals < 0 OR p_away_goals < 0 THEN
    RAISE EXCEPTION 'Invalid score';
  END IF;

  SELECT * INTO v_fixture
  FROM public.competition_fixtures
  WHERE id = p_fixture_id
    AND competition_type IN ('league', 'cup');

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = p_home_goals,
      away_goals = p_away_goals,
      status = 'played'
  WHERE id = p_fixture_id;

  PERFORM public.competition_settle_fixture_gates(p_fixture_id);
  PERFORM public.competition_tv_settle_fixture(p_fixture_id);

  PERFORM public.competition_try_award_challenges(v_fixture.season_id, v_fixture.home_club_short_name);
  PERFORM public.competition_try_award_challenges(v_fixture.season_id, v_fixture.away_club_short_name);

  IF v_fixture.competition_type = 'cup' THEN
    PERFORM public.competition_cup_on_fixture_played(p_fixture_id);
  ELSIF v_fixture.competition_type = 'league'
    AND EXISTS (
      SELECT 1
      FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public'
        AND p.proname = 'competition_try_pay_league_division_prizes'
    ) THEN
    EXECUTE 'SELECT public.competition_try_pay_league_division_prizes($1, $2)'
    USING v_fixture.season_id, v_fixture.division;
  END IF;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.admin_update_challenge_settings(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_save_challenge(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_delete_challenge(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_seed_challenge_defaults(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_recheck_challenges(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_challenge_club_progress(text) TO authenticated;
