-- =============================================================================
-- GPSL — TV revenue (fixture selection + payout on confirm)
-- Run once after competition_phase5_finances.sql and government_subsidies.sql
-- (extends ledger entry types and recreates global_settings_public).
-- =============================================================================
-- Selects big league fixtures per GPSL month per division (default 5).
-- Both clubs receive tv_per_match_amount when a selected fixture is played.
-- Club appearances per season bounded by tv_club_min / tv_club_max (default 4–12).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Admin settings
-- ---------------------------------------------------------------------------

ALTER TABLE public.global_settings
  ADD COLUMN IF NOT EXISTS tv_per_match_amount numeric(14, 2) NOT NULL DEFAULT 1000000,
  ADD COLUMN IF NOT EXISTS tv_matches_per_month smallint NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS tv_club_min_season smallint NOT NULL DEFAULT 4,
  ADD COLUMN IF NOT EXISTS tv_club_max_season smallint NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS tv_weight_top8_clash smallint NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS tv_weight_title_race smallint NOT NULL DEFAULT 80,
  ADD COLUMN IF NOT EXISTS tv_weight_promotion smallint NOT NULL DEFAULT 70,
  ADD COLUMN IF NOT EXISTS tv_weight_relegation smallint NOT NULL DEFAULT 70,
  ADD COLUMN IF NOT EXISTS tv_weight_super8 smallint NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS tv_weight_playoff smallint NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS tv_weight_dry_spell smallint NOT NULL DEFAULT 40,
  ADD COLUMN IF NOT EXISTS tv_weight_below_min smallint NOT NULL DEFAULT 200;

DROP VIEW IF EXISTS public.global_settings_public;

CREATE VIEW public.global_settings_public
WITH (security_invoker = false)
AS
SELECT
  id,
  transfer_window_open,
  draft_auction_enabled,
  draft_auction_start_time,
  updated_at,
  wage_pct_superleague,
  wage_pct_championship,
  stadium_cost_tier1,
  stadium_cost_tier2,
  stadium_cost_tier3,
  stadium_capacity_tier_mid,
  stadium_capacity_tier_high,
  stadium_expansion_cancel_penalty,
  hg_sub_band1_max,
  hg_sub_band1_per_player,
  hg_sub_band2_max,
  hg_sub_band2_per_player,
  hg_sub_band3_per_player,
  youth_sub_band1_max,
  youth_sub_band1_per_player,
  youth_sub_band2_max,
  youth_sub_band2_per_player,
  youth_sub_band3_max,
  youth_sub_band3_per_player,
  youth_sub_band4_per_player,
  bnb_max_rating,
  bnb_min_players,
  bnb_per_player,
  tv_per_match_amount,
  tv_matches_per_month,
  tv_club_min_season,
  tv_club_max_season,
  tv_weight_top8_clash,
  tv_weight_title_race,
  tv_weight_promotion,
  tv_weight_relegation,
  tv_weight_super8,
  tv_weight_playoff,
  tv_weight_dry_spell,
  tv_weight_below_min
FROM public.global_settings;

GRANT SELECT ON public.global_settings_public TO authenticated;
GRANT SELECT ON public.global_settings_public TO anon;

-- ---------------------------------------------------------------------------
-- Ledger type
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_finance_ledger
  DROP CONSTRAINT IF EXISTS competition_finance_ledger_entry_type_check;

ALTER TABLE public.competition_finance_ledger
  ADD CONSTRAINT competition_finance_ledger_entry_type_check
  CHECK (
    entry_type IN (
      'gate_league_home',
      'gate_cup_share',
      'prize',
      'prize_league',
      'prize_cup',
      'tv_revenue',
      'gov_hg_subsidy',
      'gov_youth_subsidy',
      'gov_bnb_subsidy',
      'adjustment',
      'admin_one_off_injection',
      'admin_purchase_payment',
      'transfer_sale',
      'transfer_purchase',
      'transfer_agent_fee',
      'transfer_foreign_sale',
      'transfer_overflow_release',
      'loan_drawdown',
      'loan_repayment_principal',
      'loan_interest_payment',
      'infra_maintenance',
      'infra_purchase',
      'infra_expansion',
      'infra_expansion_refund',
      'infra_expansion_penalty'
    )
  );

-- ---------------------------------------------------------------------------
-- Selected TV fixtures
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_tv_fixture_selection (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  fixture_id bigint NOT NULL REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  division text NOT NULL CHECK (
    division IN ('superleague', 'championship_a', 'championship_b')
  ),
  gpsl_month text NOT NULL CHECK (
    gpsl_month IN (
      'august', 'september', 'october', 'november', 'december',
      'january', 'february', 'march', 'april', 'may'
    )
  ),
  tv_score numeric(12, 2) NOT NULL DEFAULT 0,
  reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
  selected_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_tv_fixture_selection_unique UNIQUE (season_id, fixture_id),
  CONSTRAINT competition_tv_fixture_selection_month_unique UNIQUE (season_id, division, gpsl_month, fixture_id)
);

CREATE INDEX IF NOT EXISTS competition_tv_fixture_selection_season_div_month_idx
  ON public.competition_tv_fixture_selection (season_id, division, gpsl_month);

ALTER TABLE public.competition_tv_fixture_selection ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_tv_fixture_selection_select ON public.competition_tv_fixture_selection;
CREATE POLICY competition_tv_fixture_selection_select ON public.competition_tv_fixture_selection
  FOR SELECT TO authenticated USING (true);

-- ---------------------------------------------------------------------------
-- Settings + helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tv_revenue_settings()
RETURNS public.global_settings
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT * FROM public.global_settings WHERE id = 1;
$$;

CREATE OR REPLACE FUNCTION public.competition_club_table_position_as_of(
  p_season_id bigint,
  p_division text,
  p_club_short_name text,
  p_before_matchday int
)
RETURNS int
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_pts int;
  v_gd int;
  v_gf int;
  v_pos int;
BEGIN
  WITH played AS (
    SELECT f.*
    FROM public.competition_fixtures f
    WHERE f.season_id = p_season_id
      AND f.division = p_division
      AND f.competition_type = 'league'
      AND f.status = 'played'
      AND f.home_goals IS NOT NULL
      AND f.away_goals IS NOT NULL
      AND f.matchday < greatest(coalesce(p_before_matchday, 1), 1)
  ),
  apps AS (
    SELECT
      home_club_short_name AS club_short_name,
      CASE WHEN home_goals > away_goals THEN 3 WHEN home_goals = away_goals THEN 1 ELSE 0 END AS pts,
      home_goals - away_goals AS gd,
      home_goals AS gf
    FROM played
    UNION ALL
    SELECT
      away_club_short_name,
      CASE WHEN away_goals > home_goals THEN 3 WHEN away_goals = home_goals THEN 1 ELSE 0 END,
      away_goals - home_goals,
      away_goals
    FROM played
  ),
  totals AS (
    SELECT
      club_short_name,
      sum(pts)::int AS pts,
      sum(gd)::int AS gd,
      sum(gf)::int AS gf
    FROM apps
    GROUP BY club_short_name
  ),
  registered AS (
    SELECT ccs.club_short_name, c."Club" AS club_name
    FROM public.competition_club_seasons ccs
    JOIN public."Clubs" c ON c."ShortName" = ccs.club_short_name
    WHERE ccs.season_id = p_season_id
      AND ccs.division = p_division
  ),
  ranked AS (
    SELECT
      r.club_short_name,
      row_number() OVER (
        ORDER BY coalesce(t.pts, 0) DESC, coalesce(t.gd, 0) DESC, coalesce(t.gf, 0) DESC, r.club_name ASC
      )::int AS table_position
    FROM registered r
    LEFT JOIN totals t ON t.club_short_name = r.club_short_name
  )
  SELECT table_position INTO v_pos
  FROM ranked
  WHERE club_short_name = p_club_short_name;

  RETURN coalesce(v_pos, 10);
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_tv_club_count_before_month(
  p_season_id bigint,
  p_division text,
  p_club_short_name text,
  p_gpsl_month text
)
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT count(*)::int
  FROM public.competition_tv_fixture_selection s
  JOIN public.competition_fixtures f ON f.id = s.fixture_id
  WHERE s.season_id = p_season_id
    AND s.division = p_division
    AND public.competition_gpsl_month_sort(s.gpsl_month) < public.competition_gpsl_month_sort(p_gpsl_month)
    AND (f.home_club_short_name = p_club_short_name OR f.away_club_short_name = p_club_short_name);
$$;

CREATE OR REPLACE FUNCTION public.competition_tv_months_since_last(
  p_season_id bigint,
  p_division text,
  p_club_short_name text,
  p_before_gpsl_month text
)
RETURNS int
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_last_month text;
  v_before_sort int;
  v_last_sort int;
BEGIN
  SELECT s.gpsl_month INTO v_last_month
  FROM public.competition_tv_fixture_selection s
  JOIN public.competition_fixtures f ON f.id = s.fixture_id
  WHERE s.season_id = p_season_id
    AND s.division = p_division
    AND public.competition_gpsl_month_sort(s.gpsl_month) < public.competition_gpsl_month_sort(p_before_gpsl_month)
    AND (f.home_club_short_name = p_club_short_name OR f.away_club_short_name = p_club_short_name)
  ORDER BY public.competition_gpsl_month_sort(s.gpsl_month) DESC
  LIMIT 1;

  IF v_last_month IS NULL THEN
    RETURN public.competition_gpsl_month_sort(p_before_gpsl_month);
  END IF;

  v_before_sort := public.competition_gpsl_month_sort(p_before_gpsl_month);
  v_last_sort := public.competition_gpsl_month_sort(v_last_month);
  RETURN greatest(v_before_sort - v_last_sort, 0);
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_tv_score_fixture(
  p_fixture_id bigint,
  p_before_matchday int,
  p_home_tv_count int,
  p_away_tv_count int,
  p_home_dry_months int,
  p_away_dry_months int
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_s public.global_settings;
  v_home_pos int;
  v_away_pos int;
  v_score numeric := 0;
  v_reasons jsonb := '[]'::jsonb;
BEGIN
  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND OR v_fixture.competition_type <> 'league' THEN
    RETURN jsonb_build_object('score', 0, 'reasons', '[]'::jsonb);
  END IF;

  v_s := public.tv_revenue_settings();

  v_home_pos := public.competition_club_table_position_as_of(
    v_fixture.season_id, v_fixture.division, v_fixture.home_club_short_name, p_before_matchday
  );
  v_away_pos := public.competition_club_table_position_as_of(
    v_fixture.season_id, v_fixture.division, v_fixture.away_club_short_name, p_before_matchday
  );

  IF v_fixture.division = 'superleague' THEN
    IF v_home_pos <= 8 AND v_away_pos <= 8 THEN
      v_score := v_score + v_s.tv_weight_top8_clash;
      v_reasons := v_reasons || jsonb_build_array('top8_clash');
    END IF;
    IF v_home_pos <= 8 OR v_away_pos <= 8 THEN
      v_score := v_score + v_s.tv_weight_super8;
      v_reasons := v_reasons || jsonb_build_array('super8_zone');
    END IF;
    IF v_home_pos <= 3 OR v_away_pos <= 3 THEN
      v_score := v_score + v_s.tv_weight_title_race;
      v_reasons := v_reasons || jsonb_build_array('title_race');
    END IF;
    IF v_home_pos >= 16 AND v_home_pos <= 17 OR v_away_pos >= 16 AND v_away_pos <= 17 THEN
      v_score := v_score + v_s.tv_weight_playoff;
      v_reasons := v_reasons || jsonb_build_array('relegation_playoff');
    END IF;
    IF v_home_pos >= 18 OR v_away_pos >= 18 THEN
      v_score := v_score + v_s.tv_weight_relegation;
      v_reasons := v_reasons || jsonb_build_array('relegation_battle');
    END IF;
  ELSE
    IF v_home_pos <= 2 OR v_away_pos <= 2 THEN
      v_score := v_score + v_s.tv_weight_promotion;
      v_reasons := v_reasons || jsonb_build_array('promotion_race');
    END IF;
    IF v_home_pos >= 18 OR v_away_pos >= 18 THEN
      v_score := v_score + v_s.tv_weight_relegation;
      v_reasons := v_reasons || jsonb_build_array('relegation_battle');
    END IF;
  END IF;

  IF p_home_dry_months >= 2 THEN
    v_score := v_score + v_s.tv_weight_dry_spell * least(p_home_dry_months, 6);
    v_reasons := v_reasons || jsonb_build_array(format('home_dry_%s_mo', p_home_dry_months));
  END IF;
  IF p_away_dry_months >= 2 THEN
    v_score := v_score + v_s.tv_weight_dry_spell * least(p_away_dry_months, 6);
    v_reasons := v_reasons || jsonb_build_array(format('away_dry_%s_mo', p_away_dry_months));
  END IF;

  IF p_home_tv_count < v_s.tv_club_min_season THEN
    v_score := v_score + v_s.tv_weight_below_min * (v_s.tv_club_min_season - p_home_tv_count);
    v_reasons := v_reasons || jsonb_build_array('home_below_min');
  END IF;
  IF p_away_tv_count < v_s.tv_club_min_season THEN
    v_score := v_score + v_s.tv_weight_below_min * (v_s.tv_club_min_season - p_away_tv_count);
    v_reasons := v_reasons || jsonb_build_array('away_below_min');
  END IF;

  IF p_home_tv_count >= v_s.tv_club_max_season THEN
    v_score := v_score - 5000;
    v_reasons := v_reasons || jsonb_build_array('home_at_max');
  END IF;
  IF p_away_tv_count >= v_s.tv_club_max_season THEN
    v_score := v_score - 5000;
    v_reasons := v_reasons || jsonb_build_array('away_at_max');
  END IF;

  RETURN jsonb_build_object(
    'score', v_score,
    'reasons', v_reasons,
    'home_position', v_home_pos,
    'away_position', v_away_pos
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Select TV fixtures for one division + month
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_tv_select_division_month(
  p_season_id bigint,
  p_division text,
  p_gpsl_month text,
  p_replace boolean DEFAULT false
)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_s public.global_settings;
  v_before_md int;
  v_pick int;
  v_selected int := 0;
  v_fixture record;
  v_scored record;
  v_home_count int;
  v_away_count int;
  v_home_dry int;
  v_away_dry int;
  v_breakdown jsonb;
  v_running_home int;
  v_running_away int;
BEGIN
  IF p_season_id IS NULL OR p_division IS NULL OR p_gpsl_month IS NULL THEN
    RETURN 0;
  END IF;

  v_s := public.tv_revenue_settings();
  v_pick := greatest(v_s.tv_matches_per_month, 0);

  IF NOT p_replace AND EXISTS (
    SELECT 1 FROM public.competition_tv_fixture_selection
    WHERE season_id = p_season_id
      AND division = p_division
      AND gpsl_month = p_gpsl_month
  ) THEN
    RETURN 0;
  END IF;

  IF p_replace THEN
    DELETE FROM public.competition_tv_fixture_selection
    WHERE season_id = p_season_id
      AND division = p_division
      AND gpsl_month = p_gpsl_month;
  END IF;

  SELECT min(f.matchday) INTO v_before_md
  FROM public.competition_fixtures f
  WHERE f.season_id = p_season_id
    AND f.division = p_division
    AND f.competition_type = 'league'
    AND f.gpsl_month = p_gpsl_month
    AND f.status <> 'cancelled';

  IF v_before_md IS NULL THEN
    RETURN 0;
  END IF;

  CREATE TEMP TABLE IF NOT EXISTS tv_month_candidates (
    fixture_id bigint PRIMARY KEY,
    home_club text NOT NULL,
    away_club text NOT NULL,
    tv_score numeric NOT NULL,
    reasons jsonb NOT NULL,
    home_tv_count int NOT NULL,
    away_tv_count int NOT NULL
  ) ON COMMIT DROP;

  TRUNCATE tv_month_candidates;

  FOR v_fixture IN
    SELECT f.id, f.home_club_short_name, f.away_club_short_name
    FROM public.competition_fixtures f
    WHERE f.season_id = p_season_id
      AND f.division = p_division
      AND f.competition_type = 'league'
      AND f.gpsl_month = p_gpsl_month
      AND f.status <> 'cancelled'
  LOOP
    v_home_count := public.competition_tv_club_count_before_month(
      p_season_id, p_division, v_fixture.home_club_short_name, p_gpsl_month
    );
    v_away_count := public.competition_tv_club_count_before_month(
      p_season_id, p_division, v_fixture.away_club_short_name, p_gpsl_month
    );
    v_home_dry := public.competition_tv_months_since_last(
      p_season_id, p_division, v_fixture.home_club_short_name, p_gpsl_month
    );
    v_away_dry := public.competition_tv_months_since_last(
      p_season_id, p_division, v_fixture.away_club_short_name, p_gpsl_month
    );

    v_breakdown := public.competition_tv_score_fixture(
      v_fixture.id,
      v_before_md,
      v_home_count,
      v_away_count,
      v_home_dry,
      v_away_dry
    );

    INSERT INTO tv_month_candidates (
      fixture_id, home_club, away_club, tv_score, reasons, home_tv_count, away_tv_count
    )
    VALUES (
      v_fixture.id,
      v_fixture.home_club_short_name,
      v_fixture.away_club_short_name,
      (v_breakdown ->> 'score')::numeric,
      coalesce(v_breakdown -> 'reasons', '[]'::jsonb),
      v_home_count,
      v_away_count
    );
  END LOOP;

  FOR v_scored IN
    SELECT *
    FROM tv_month_candidates
    ORDER BY tv_score DESC, fixture_id ASC
  LOOP
    EXIT WHEN v_selected >= v_pick;

    v_running_home := v_scored.home_tv_count + (
      SELECT count(*)::int
      FROM public.competition_tv_fixture_selection s
      JOIN public.competition_fixtures f ON f.id = s.fixture_id
      WHERE s.season_id = p_season_id
        AND s.division = p_division
        AND s.gpsl_month = p_gpsl_month
        AND (f.home_club_short_name = v_scored.home_club OR f.away_club_short_name = v_scored.home_club)
    );
    v_running_away := v_scored.away_tv_count + (
      SELECT count(*)::int
      FROM public.competition_tv_fixture_selection s
      JOIN public.competition_fixtures f ON f.id = s.fixture_id
      WHERE s.season_id = p_season_id
        AND s.division = p_division
        AND s.gpsl_month = p_gpsl_month
        AND (f.home_club_short_name = v_scored.away_club OR f.away_club_short_name = v_scored.away_club)
    );

    IF v_running_home >= v_s.tv_club_max_season AND v_running_away >= v_s.tv_club_max_season THEN
      CONTINUE;
    END IF;

    INSERT INTO public.competition_tv_fixture_selection (
      season_id, fixture_id, division, gpsl_month, tv_score, reasons
    )
    VALUES (
      p_season_id,
      v_scored.fixture_id,
      p_division,
      p_gpsl_month,
      v_scored.tv_score,
      v_scored.reasons
    )
    ON CONFLICT ON CONSTRAINT competition_tv_fixture_selection_unique DO NOTHING;

    IF FOUND THEN
      v_selected := v_selected + 1;
    END IF;
  END LOOP;

  RETURN v_selected;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_tv_select_season(
  p_season_id bigint,
  p_replace boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_div text;
  v_month text;
  v_n int;
  v_result jsonb := '{}'::jsonb;
  v_months text[] := ARRAY[
    'august', 'september', 'october', 'november', 'december',
    'january', 'february', 'march', 'april', 'may'
  ];
BEGIN
  IF p_replace THEN
    DELETE FROM public.competition_tv_fixture_selection WHERE season_id = p_season_id;
  END IF;

  FOREACH v_div IN ARRAY ARRAY['superleague', 'championship_a', 'championship_b']
  LOOP
    FOREACH v_month IN ARRAY v_months
    LOOP
      v_n := public.competition_tv_select_division_month(p_season_id, v_div, v_month, p_replace);
      v_result := v_result || jsonb_build_object(format('%s_%s', v_div, v_month), v_n);
    END LOOP;
  END LOOP;

  RETURN jsonb_build_object('season_id', p_season_id, 'selected_by_key', v_result);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Payout on played TV fixtures
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_tv_settle_fixture(p_fixture_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_amount numeric;
  v_desc text;
BEGIN
  IF p_fixture_id IS NULL THEN
    RETURN;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.competition_tv_fixture_selection WHERE fixture_id = p_fixture_id
  ) THEN
    RETURN;
  END IF;

  SELECT * INTO v_fixture
  FROM public.competition_fixtures
  WHERE id = p_fixture_id
    AND competition_type = 'league'
    AND status = 'played'
    AND home_goals IS NOT NULL
    AND away_goals IS NOT NULL;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  v_amount := (SELECT tv_per_match_amount FROM public.global_settings WHERE id = 1);

  IF v_amount IS NULL OR v_amount <= 0 THEN
    RETURN;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.competition_finance_ledger
    WHERE fixture_id = p_fixture_id
      AND club_short_name = v_fixture.home_club_short_name
      AND entry_type = 'tv_revenue'
  ) THEN
    PERFORM public.competition_credit_club_balance(v_fixture.home_club_short_name, v_amount);
    v_desc := format(
      'TV revenue MD%s — %s vs %s',
      v_fixture.matchday,
      v_fixture.home_club_short_name,
      v_fixture.away_club_short_name
    );
    INSERT INTO public.competition_finance_ledger (
      season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
    )
    VALUES (
      v_fixture.season_id,
      p_fixture_id,
      v_fixture.home_club_short_name,
      'tv_revenue',
      v_amount,
      v_desc,
      jsonb_build_object('gpsl_month', v_fixture.gpsl_month, 'role', 'home')
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.competition_finance_ledger
    WHERE fixture_id = p_fixture_id
      AND club_short_name = v_fixture.away_club_short_name
      AND entry_type = 'tv_revenue'
  ) THEN
    PERFORM public.competition_credit_club_balance(v_fixture.away_club_short_name, v_amount);
    v_desc := format(
      'TV revenue MD%s — %s vs %s',
      v_fixture.matchday,
      v_fixture.home_club_short_name,
      v_fixture.away_club_short_name
    );
    INSERT INTO public.competition_finance_ledger (
      season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
    )
    VALUES (
      v_fixture.season_id,
      p_fixture_id,
      v_fixture.away_club_short_name,
      'tv_revenue',
      v_amount,
      v_desc,
      jsonb_build_object('gpsl_month', v_fixture.gpsl_month, 'role', 'away')
    );
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_backfill_tv_revenue(p_season_id bigint DEFAULT NULL)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_fixture_id bigint;
  v_count int := 0;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  FOR v_fixture_id IN
    SELECT s.fixture_id
    FROM public.competition_tv_fixture_selection s
    JOIN public.competition_fixtures f ON f.id = s.fixture_id
    WHERE f.season_id = v_season_id
      AND f.status = 'played'
  LOOP
    PERFORM public.competition_tv_settle_fixture(v_fixture_id);
    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Club preview (pending + season tally)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_tv_club_preview(p_club_short_name text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := btrim(p_club_short_name);
  v_me text := public.my_club_shortname();
  v_season_id bigint;
  v_division text;
  v_s public.global_settings;
  v_selected int;
  v_pending int;
  v_pending_amount numeric;
  v_paid_amount numeric;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'Club required';
  END IF;

  IF NOT public.is_gpsl_admin() AND (v_me IS NULL OR v_me <> v_club) THEN
    RAISE EXCEPTION 'Not allowed to preview TV revenue for this club';
  END IF;

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true
  ORDER BY id DESC
  LIMIT 1;

  SELECT ccs.division INTO v_division
  FROM public.competition_club_seasons ccs
  WHERE ccs.season_id = v_season_id
    AND ccs.club_short_name = v_club;

  v_s := public.tv_revenue_settings();

  SELECT count(*)::int INTO v_selected
  FROM public.competition_tv_fixture_selection s
  JOIN public.competition_fixtures f ON f.id = s.fixture_id
  WHERE f.season_id = v_season_id
    AND (f.home_club_short_name = v_club OR f.away_club_short_name = v_club);

  SELECT count(*)::int, coalesce(sum(v_s.tv_per_match_amount), 0)
  INTO v_pending, v_pending_amount
  FROM public.competition_tv_fixture_selection s
  JOIN public.competition_fixtures f ON f.id = s.fixture_id
  WHERE f.season_id = v_season_id
    AND f.status = 'scheduled'
    AND (f.home_club_short_name = v_club OR f.away_club_short_name = v_club);

  SELECT coalesce(sum(l.amount), 0) INTO v_paid_amount
  FROM public.competition_finance_ledger l
  WHERE l.season_id = v_season_id
    AND l.club_short_name = v_club
    AND l.entry_type = 'tv_revenue';

  RETURN jsonb_build_object(
    'season_id', v_season_id,
    'division', v_division,
    'selected_count', v_selected,
    'pending_count', v_pending,
    'pending_amount', v_pending_amount,
    'paid_amount', v_paid_amount,
    'per_match_amount', v_s.tv_per_match_amount,
    'club_min', v_s.tv_club_min_season,
    'club_max', v_s.tv_club_max_season
  );
END;
$function$;

CREATE OR REPLACE VIEW public.competition_tv_fixtures_public
WITH (security_invoker = false)
AS
SELECT
  s.season_id,
  s.fixture_id,
  s.division,
  s.gpsl_month,
  public.competition_gpsl_month_label(s.gpsl_month) AS gpsl_month_label,
  s.tv_score,
  s.reasons,
  s.selected_at,
  f.matchday,
  f.home_club_short_name,
  f.away_club_short_name,
  f.status,
  f.home_goals,
  f.away_goals,
  gs.tv_per_match_amount AS amount_per_club
FROM public.competition_tv_fixture_selection s
JOIN public.competition_fixtures f ON f.id = s.fixture_id
CROSS JOIN public.global_settings gs
WHERE gs.id = 1;

GRANT SELECT ON public.competition_tv_fixtures_public TO authenticated;
GRANT SELECT ON public.competition_tv_fixtures_public TO anon;

-- ---------------------------------------------------------------------------
-- Admin RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.admin_update_tv_settings(p_settings jsonb)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_settings IS NULL OR jsonb_typeof(p_settings) <> 'object' THEN
    RAISE EXCEPTION 'settings must be a JSON object';
  END IF;

  UPDATE public.global_settings
  SET
    tv_per_match_amount = coalesce((p_settings->>'tv_per_match_amount')::numeric, tv_per_match_amount),
    tv_matches_per_month = coalesce((p_settings->>'tv_matches_per_month')::smallint, tv_matches_per_month),
    tv_club_min_season = coalesce((p_settings->>'tv_club_min_season')::smallint, tv_club_min_season),
    tv_club_max_season = coalesce((p_settings->>'tv_club_max_season')::smallint, tv_club_max_season),
    tv_weight_top8_clash = coalesce((p_settings->>'tv_weight_top8_clash')::smallint, tv_weight_top8_clash),
    tv_weight_title_race = coalesce((p_settings->>'tv_weight_title_race')::smallint, tv_weight_title_race),
    tv_weight_promotion = coalesce((p_settings->>'tv_weight_promotion')::smallint, tv_weight_promotion),
    tv_weight_relegation = coalesce((p_settings->>'tv_weight_relegation')::smallint, tv_weight_relegation),
    tv_weight_super8 = coalesce((p_settings->>'tv_weight_super8')::smallint, tv_weight_super8),
    tv_weight_playoff = coalesce((p_settings->>'tv_weight_playoff')::smallint, tv_weight_playoff),
    tv_weight_dry_spell = coalesce((p_settings->>'tv_weight_dry_spell')::smallint, tv_weight_dry_spell),
    tv_weight_below_min = coalesce((p_settings->>'tv_weight_below_min')::smallint, tv_weight_below_min),
    updated_at = now()
  WHERE id = 1;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_select_tv_month(
  p_season_id bigint,
  p_division text,
  p_gpsl_month text,
  p_replace boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_n int;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  v_n := public.competition_tv_select_division_month(
    p_season_id, p_division, p_gpsl_month, coalesce(p_replace, false)
  );

  RETURN jsonb_build_object(
    'season_id', p_season_id,
    'division', p_division,
    'gpsl_month', p_gpsl_month,
    'fixtures_selected', v_n
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_select_tv_season(
  p_season_id bigint DEFAULT NULL,
  p_replace boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No season';
  END IF;

  RETURN public.competition_tv_select_season(v_season_id, coalesce(p_replace, false));
END;
$function$;

-- ---------------------------------------------------------------------------
-- Hooks: pay TV on result confirm (league fixtures only)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_confirm_result(
  p_submission_id bigint,
  p_confirmer_player_stats jsonb DEFAULT '[]'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
  v_opponent text;
  v_home_name text;
  v_away_name text;
  v_label text;
  v_home_total smallint;
  v_away_total smallint;
  v_body text;
  v_pen_winner_name text;
  v_confirmer_expected int;
BEGIN
  IF v_club IS NULL THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  IF p_confirmer_player_stats IS NULL OR jsonb_typeof(p_confirmer_player_stats) <> 'array' THEN
    RAISE EXCEPTION 'player_stats must be a JSON array';
  END IF;

  IF jsonb_array_length(p_confirmer_player_stats) = 0 THEN
    RAISE EXCEPTION 'Enter your squad match stats (11 starters) before confirming';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  v_opponent := public.competition_fixture_opponent(v_sub.fixture_id, v_club);
  IF v_opponent <> v_sub.submitted_by_club THEN
    RAISE EXCEPTION 'Only the opponent can confirm this result';
  END IF;

  v_confirmer_expected := public.competition_expected_goals_for_club(v_fixture, v_sub, v_club);

  IF v_fixture.competition_type = 'cup' THEN
    SELECT t.home_total, t.away_total
    INTO v_home_total, v_away_total
    FROM public.competition_cup_open_play_totals(
      v_sub.home_goals, v_sub.away_goals, v_sub.et_home_goals, v_sub.et_away_goals
    ) t;

    IF public.competition_cup_winner_from_submission(
      v_sub.home_goals, v_sub.away_goals, v_sub.et_home_goals, v_sub.et_away_goals,
      v_sub.pen_winner_club_short_name,
      v_fixture.home_club_short_name, v_fixture.away_club_short_name
    ) IS NULL THEN
      RAISE EXCEPTION 'Invalid cup submission — extra time or penalties required';
    END IF;

    UPDATE public.competition_fixtures
    SET home_goals = v_home_total,
        away_goals = v_away_total,
        cup_pen_winner_club_short_name = v_sub.pen_winner_club_short_name,
        status = 'played'
    WHERE id = v_sub.fixture_id;
  ELSE
    v_home_total := v_sub.home_goals;
    v_away_total := v_sub.away_goals;

    UPDATE public.competition_fixtures
    SET home_goals = v_sub.home_goals,
        away_goals = v_sub.away_goals,
        cup_pen_winner_club_short_name = NULL,
        status = 'played'
    WHERE id = v_sub.fixture_id;
  END IF;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);

  PERFORM public.competition_apply_club_player_stats(
    v_fixture.id,
    v_fixture.season_id,
    v_club,
    p_confirmer_player_stats,
    v_confirmer_expected
  );

  PERFORM public.competition_settle_fixture_gates(v_sub.fixture_id);
  PERFORM public.competition_tv_settle_fixture(v_sub.fixture_id);

  IF v_fixture.competition_type = 'cup' THEN
    PERFORM public.competition_cup_on_fixture_played(v_sub.fixture_id);
  ELSIF v_fixture.competition_type = 'league' THEN
    PERFORM public.competition_try_pay_league_division_prizes(v_fixture.season_id, v_fixture.division);
  END IF;

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = v_club,
      responded_at = now()
  WHERE id = p_submission_id;

  UPDATE public.competition_inbox
  SET read_at = coalesce(read_at, now())
  WHERE submission_id = p_submission_id
    AND recipient_club_short_name = v_club
    AND message_type = 'result_to_confirm';

  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  v_label := CASE
    WHEN v_fixture.competition_type = 'cup' THEN public.competition_cup_fixture_label(v_fixture)
    ELSE format('Matchday %s', v_fixture.matchday)
  END;

  IF v_sub.et_home_goals IS NOT NULL THEN
    v_body := format(
      '%s — %s–%s confirmed (90 min %s–%s, after ET %s–%s).',
      v_label, v_home_total, v_away_total,
      v_sub.home_goals, v_sub.away_goals, v_sub.et_home_goals, v_sub.et_away_goals
    );
  ELSE
    v_body := format(
      '%s — %s–%s confirmed (90 min %s–%s).',
      v_label, v_home_total, v_away_total, v_sub.home_goals, v_sub.away_goals
    );
  END IF;

  IF v_sub.pen_winner_club_short_name IS NOT NULL THEN
    SELECT "Club" INTO v_pen_winner_name FROM public."Clubs" WHERE "ShortName" = v_sub.pen_winner_club_short_name;
    v_body := v_body || format(' Pens: %s won.', coalesce(v_pen_winner_name, v_sub.pen_winner_club_short_name));
  END IF;

  PERFORM public.competition_inbox_notify(
    v_sub.submitted_by_club,
    'result_confirmed',
    v_sub.fixture_id,
    p_submission_id,
    format('Result confirmed: %s vs %s', v_home_name, v_away_name),
    v_body
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_confirm_submission(p_submission_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  UPDATE public.competition_fixtures
  SET home_goals = v_sub.home_goals,
      away_goals = v_sub.away_goals,
      status = 'played'
  WHERE id = v_sub.fixture_id;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);
  PERFORM public.competition_settle_fixture_gates(v_sub.fixture_id);
  PERFORM public.competition_tv_settle_fixture(v_sub.fixture_id);

  IF v_fixture.competition_type = 'cup' THEN
    PERFORM public.competition_cup_on_fixture_played(v_sub.fixture_id);
  ELSIF v_fixture.competition_type = 'league' THEN
    PERFORM public.competition_try_pay_league_division_prizes(v_fixture.season_id, v_fixture.division);
  END IF;

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = 'ADMIN',
      responded_at = now()
  WHERE id = p_submission_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_record_result(
  p_fixture_id bigint,
  p_home_goals smallint,
  p_away_goals smallint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_home_goals IS NULL OR p_away_goals IS NULL OR p_home_goals < 0 OR p_away_goals < 0 THEN
    RAISE EXCEPTION 'Invalid score';
  END IF;

  SELECT * INTO v_fixture
  FROM public.competition_fixtures
  WHERE id = p_fixture_id
    AND competition_type IN ('league', 'cup');

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = p_home_goals,
      away_goals = p_away_goals,
      status = 'played'
  WHERE id = p_fixture_id;

  PERFORM public.competition_settle_fixture_gates(p_fixture_id);
  PERFORM public.competition_tv_settle_fixture(p_fixture_id);

  IF v_fixture.competition_type = 'cup' THEN
    PERFORM public.competition_cup_on_fixture_played(p_fixture_id);
  ELSIF v_fixture.competition_type = 'league'
    AND EXISTS (
      SELECT 1
      FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public'
        AND p.proname = 'competition_try_pay_league_division_prizes'
    ) THEN
    EXECUTE 'SELECT public.competition_try_pay_league_division_prizes($1, $2)'
    USING v_fixture.season_id, v_fixture.division;
  END IF;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.admin_update_tv_settings(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_select_tv_month(bigint, text, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_select_tv_season(bigint, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_backfill_tv_revenue(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_tv_club_preview(text) TO authenticated;
