-- =============================================================================
-- GPSL — Club history, player career archives, season awards & Ballon d'Or
-- Run once after competition_phase6_cups.sql (and match stats patches).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extend club season archive (full league row + season_id)
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'competition_club_season_archive'
      AND column_name = 'season_id'
  ) THEN
    ALTER TABLE public.competition_club_season_archive
      ADD COLUMN season_id bigint REFERENCES public.competition_seasons (id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'competition_club_season_archive'
      AND column_name = 'mp'
  ) THEN
    ALTER TABLE public.competition_club_season_archive
      ADD COLUMN mp smallint,
      ADD COLUMN won smallint,
      ADD COLUMN drawn smallint,
      ADD COLUMN lost smallint,
      ADD COLUMN gf smallint,
      ADD COLUMN ga smallint,
      ADD COLUMN gd smallint,
      ADD COLUMN pts smallint;
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Cup champions per season
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_cup_season_winner (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  season_label text NOT NULL,
  cup_code text NOT NULL CHECK (
    cup_code IN ('super8', 'plate', 'shield', 'bowl', 'league_cup')
  ),
  winner_club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  runner_up_club_short_name text REFERENCES public."Clubs" ("ShortName"),
  final_fixture_id bigint REFERENCES public.competition_fixtures (id) ON DELETE SET NULL,
  archived_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_cup_season_winner_unique UNIQUE (season_id, cup_code)
);

CREATE INDEX IF NOT EXISTS competition_cup_season_winner_club_idx
  ON public.competition_cup_season_winner (winner_club_short_name, season_id DESC);

-- ---------------------------------------------------------------------------
-- Player season archive (survives season rollover)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_player_season_archive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  season_label text NOT NULL,
  player_id text NOT NULL,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  division text CHECK (
    division IS NULL OR division IN ('superleague', 'championship_a', 'championship_b')
  ),
  player_position text,
  stat_role text NOT NULL DEFAULT 'outfield' CHECK (
    stat_role IN ('goalkeeper', 'defender', 'midfielder', 'forward', 'outfield')
  ),
  appearances int NOT NULL DEFAULT 0,
  starts int NOT NULL DEFAULT 0,
  goals int NOT NULL DEFAULT 0,
  assists int NOT NULL DEFAULT 0,
  avg_rating numeric(4, 2),
  potm_awards int NOT NULL DEFAULT 0,
  clean_sheets int NOT NULL DEFAULT 0,
  ballon_points numeric(10, 2) NOT NULL DEFAULT 0,
  archived_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_player_season_archive_unique
    UNIQUE (season_id, player_id, club_short_name)
);

CREATE INDEX IF NOT EXISTS competition_player_season_archive_player_idx
  ON public.competition_player_season_archive (player_id, season_id DESC);

CREATE INDEX IF NOT EXISTS competition_player_season_archive_club_idx
  ON public.competition_player_season_archive (club_short_name, season_id DESC);

-- ---------------------------------------------------------------------------
-- Season awards (Ballon d'Or, golden boot, etc.)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_season_award (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  season_label text NOT NULL,
  award_type text NOT NULL CHECK (
    award_type IN (
      'ballon_dor',
      'golden_boot',
      'golden_playmaker',
      'golden_glove',
      'season_potm'
    )
  ),
  player_id text NOT NULL,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  stat_value numeric(12, 2) NOT NULL DEFAULT 0,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  awarded_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_season_award_unique UNIQUE (season_id, award_type)
);

CREATE INDEX IF NOT EXISTS competition_season_award_player_idx
  ON public.competition_season_award (player_id);

-- ---------------------------------------------------------------------------
-- Position role helpers (Ballon weighting)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_player_stat_role(p_position text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE upper(btrim(coalesce(p_position, '')))
    WHEN 'GK' THEN 'goalkeeper'
    WHEN 'CB' THEN 'defender'
    WHEN 'LB' THEN 'defender'
    WHEN 'RB' THEN 'defender'
    WHEN 'LWB' THEN 'defender'
    WHEN 'RWB' THEN 'defender'
    WHEN 'DMF' THEN 'defender'
    WHEN 'CMF' THEN 'midfielder'
    WHEN 'LMF' THEN 'midfielder'
    WHEN 'RMF' THEN 'midfielder'
    WHEN 'AMF' THEN 'midfielder'
    WHEN 'WG' THEN 'midfielder'
    WHEN 'SS' THEN 'forward'
    WHEN 'CF' THEN 'forward'
    ELSE 'outfield'
  END;
$$;

CREATE OR REPLACE FUNCTION public.competition_player_conceded_in_fixture(
  p_fixture_id bigint,
  p_club_short_name text
)
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE
    WHEN f.home_club_short_name = p_club_short_name THEN coalesce(f.away_goals, 0)
    ELSE coalesce(f.home_goals, 0)
  END::int
  FROM public.competition_fixtures f
  WHERE f.id = p_fixture_id;
$$;

CREATE OR REPLACE FUNCTION public.competition_player_clean_sheets(
  p_season_id bigint,
  p_player_id text,
  p_club_short_name text DEFAULT NULL,
  p_include_cups boolean DEFAULT true
)
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT count(*)::int
  FROM public.competition_match_player_stats m
  JOIN public.competition_fixtures f ON f.id = m.fixture_id
  JOIN public."Players" p ON p."Konami_ID"::text = m.player_id
  WHERE m.season_id = p_season_id
    AND m.player_id = btrim(p_player_id)
    AND m.started = true
    AND f.status = 'played'
    AND (
      p_include_cups
      OR f.competition_type = 'league'
    )
    AND (
      p_club_short_name IS NULL
      OR m.club_short_name = btrim(p_club_short_name)
    )
    AND public.competition_player_stat_role(p."Position") IN ('goalkeeper', 'defender')
    AND public.competition_player_conceded_in_fixture(f.id, m.club_short_name) = 0;
$$;

-- Ballon d'Or points (league + cups; role-weighted)
CREATE OR REPLACE FUNCTION public.competition_player_ballon_points(
  p_appearances int,
  p_goals int,
  p_assists int,
  p_avg_rating numeric,
  p_potm int,
  p_clean_sheets int,
  p_stat_role text
)
RETURNS numeric
LANGUAGE plpgsql
IMMUTABLE
AS $function$
DECLARE
  v_apps numeric := greatest(coalesce(p_appearances, 0), 0);
  v_goals numeric := greatest(coalesce(p_goals, 0), 0);
  v_assists numeric := greatest(coalesce(p_assists, 0), 0);
  v_rating numeric := coalesce(p_avg_rating, 0);
  v_potm numeric := greatest(coalesce(p_potm, 0), 0);
  v_cs numeric := greatest(coalesce(p_clean_sheets, 0), 0);
  v_role text := coalesce(p_stat_role, 'outfield');
BEGIN
  IF v_role = 'goalkeeper' THEN
    RETURN round(
      v_cs * 18 + v_potm * 15 + v_rating * 12 + v_apps * 1 + v_assists * 2,
      2
    );
  ELSIF v_role = 'defender' THEN
    RETURN round(
      v_cs * 12 + v_goals * 6 + v_assists * 4 + v_potm * 14 + v_rating * 10 + v_apps * 0.5,
      2
    );
  ELSIF v_role = 'midfielder' THEN
    RETURN round(
      v_goals * 8 + v_assists * 6 + v_potm * 16 + v_rating * 10 + v_apps * 0.4 + v_cs * 2,
      2
    );
  ELSIF v_role = 'forward' THEN
    RETURN round(
      v_goals * 10 + v_assists * 5 + v_potm * 18 + v_rating * 9 + v_apps * 0.3,
      2
    );
  END IF;

  RETURN round(
    v_goals * 8 + v_assists * 5 + v_potm * 14 + v_rating * 9 + v_apps * 0.3,
    2
  );
END;
$function$;

-- Aggregate live stats for one player/club/season from match rows
CREATE OR REPLACE FUNCTION public.competition_aggregate_player_season_row(
  p_season_id bigint,
  p_player_id text,
  p_club_short_name text
)
RETURNS TABLE (
  appearances int,
  starts int,
  goals int,
  assists int,
  avg_rating numeric,
  potm_awards int,
  clean_sheets int,
  player_position text,
  stat_role text,
  ballon_points numeric
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_apps int;
  v_starts int;
  v_goals int;
  v_assists int;
  v_avg numeric;
  v_potm int;
  v_cs int;
  v_pos text;
  v_role text;
BEGIN
  SELECT
    count(*) FILTER (WHERE m.appeared)::int,
    count(*) FILTER (WHERE m.started)::int,
    coalesce(sum(m.goals), 0)::int,
    coalesce(sum(m.assists), 0)::int,
    round(avg(m.rating) FILTER (WHERE m.rating IS NOT NULL), 2),
    count(*) FILTER (WHERE m.is_player_of_match)::int
  INTO v_apps, v_starts, v_goals, v_assists, v_avg, v_potm
  FROM public.competition_match_player_stats m
  JOIN public.competition_fixtures f ON f.id = m.fixture_id
  WHERE m.season_id = p_season_id
    AND m.player_id = btrim(p_player_id)
    AND m.club_short_name = btrim(p_club_short_name)
    AND f.status = 'played';

  SELECT p."Position"
  INTO v_pos
  FROM public."Players" p
  WHERE p."Konami_ID"::text = btrim(p_player_id)
  LIMIT 1;

  v_role := public.competition_player_stat_role(v_pos);
  v_cs := public.competition_player_clean_sheets(
    p_season_id, p_player_id, p_club_short_name, true
  );

  RETURN QUERY
  SELECT
    coalesce(v_apps, 0),
    coalesce(v_starts, 0),
    coalesce(v_goals, 0),
    coalesce(v_assists, 0),
    v_avg,
    coalesce(v_potm, 0),
    coalesce(v_cs, 0),
    v_pos,
    v_role,
    public.competition_player_ballon_points(
      coalesce(v_apps, 0), coalesce(v_goals, 0), coalesce(v_assists, 0),
      v_avg, coalesce(v_potm, 0), coalesce(v_cs, 0), v_role
    );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Archive season (admin or SQL Editor)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_admin_archive_season(p_season_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season public.competition_seasons%rowtype;
  v_row record;
  v_cup record;
  v_player record;
  v_agg record;
  v_max_round int;
  v_winner text;
  v_runner text;
  v_fix_id bigint;
  v_ballon record;
  v_boot record;
  v_play record;
  v_potm record;
  v_glove record;
  v_clubs int := 0;
  v_players int := 0;
  v_cups int := 0;
  v_finance int := 0;
BEGIN
  IF auth.uid() IS NOT NULL AND NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    SELECT * INTO v_season
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    SELECT * INTO v_season FROM public.competition_seasons WHERE id = p_season_id;
  END IF;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Season not found';
  END IF;

  -- League standings → club archive
  FOR v_row IN
    SELECT *
    FROM public.competition_standings_public s
    WHERE s.season_id = v_season.id
    ORDER BY s.division, s.table_position
  LOOP
    INSERT INTO public.competition_club_season_archive (
      club_short_name, season_label, division, final_position,
      season_id, mp, won, drawn, lost, gf, ga, gd, pts
    )
    VALUES (
      v_row.club_short_name,
      v_season.label,
      v_row.division,
      v_row.table_position::smallint,
      v_season.id,
      v_row.mp::smallint,
      v_row.w::smallint,
      v_row.d::smallint,
      v_row.l::smallint,
      v_row.gf::smallint,
      v_row.ga::smallint,
      v_row.gd::smallint,
      v_row.pts::smallint
    )
    ON CONFLICT (club_short_name, season_label)
    DO UPDATE SET
      division = excluded.division,
      final_position = excluded.final_position,
      season_id = excluded.season_id,
      mp = excluded.mp,
      won = excluded.won,
      drawn = excluded.drawn,
      lost = excluded.lost,
      gf = excluded.gf,
      ga = excluded.ga,
      gd = excluded.gd,
      pts = excluded.pts;

    v_clubs := v_clubs + 1;
  END LOOP;

  -- Cup winners (final round)
  FOR v_cup IN
    SELECT unnest(ARRAY['super8','plate','shield','bowl','league_cup']) AS cup_code
  LOOP
    SELECT max(n.round_no) INTO v_max_round
    FROM public.competition_cup_bracket_nodes n
    WHERE n.season_id = v_season.id AND n.cup_code = v_cup.cup_code;

    IF v_max_round IS NULL THEN
      CONTINUE;
    END IF;

    SELECT n.winner_club_short_name, n.fixture_id
    INTO v_winner, v_fix_id
    FROM public.competition_cup_bracket_nodes n
    WHERE n.season_id = v_season.id
      AND n.cup_code = v_cup.cup_code
      AND n.round_no = v_max_round
      AND n.winner_club_short_name IS NOT NULL
    ORDER BY n.match_no
    LIMIT 1;

    IF v_winner IS NULL THEN
      CONTINUE;
    END IF;

    SELECT CASE
      WHEN f.home_club_short_name = v_winner THEN f.away_club_short_name
      ELSE f.home_club_short_name
    END
    INTO v_runner
    FROM public.competition_fixtures f
    WHERE f.id = v_fix_id;

    INSERT INTO public.competition_cup_season_winner (
      season_id, season_label, cup_code,
      winner_club_short_name, runner_up_club_short_name, final_fixture_id
    )
    VALUES (
      v_season.id, v_season.label, v_cup.cup_code,
      v_winner, v_runner, v_fix_id
    )
    ON CONFLICT (season_id, cup_code)
    DO UPDATE SET
      winner_club_short_name = excluded.winner_club_short_name,
      runner_up_club_short_name = excluded.runner_up_club_short_name,
      final_fixture_id = excluded.final_fixture_id,
      archived_at = now();

    v_cups := v_cups + 1;
  END LOOP;

  -- Player season rows
  FOR v_player IN
    SELECT DISTINCT m.player_id, m.club_short_name, ccs.division
    FROM public.competition_match_player_stats m
    JOIN public.competition_fixtures f ON f.id = m.fixture_id
    LEFT JOIN public.competition_club_seasons ccs
      ON ccs.season_id = m.season_id AND ccs.club_short_name = m.club_short_name
    WHERE m.season_id = v_season.id
      AND f.status = 'played'
      AND m.appeared = true
  LOOP
    SELECT * INTO v_agg
    FROM public.competition_aggregate_player_season_row(
      v_season.id, v_player.player_id, v_player.club_short_name
    );

    INSERT INTO public.competition_player_season_archive (
      season_id, season_label, player_id, club_short_name, division,
      player_position, stat_role,
      appearances, starts, goals, assists, avg_rating, potm_awards,
      clean_sheets, ballon_points
    )
    VALUES (
      v_season.id, v_season.label, v_player.player_id, v_player.club_short_name,
      v_player.division, v_agg.player_position, v_agg.stat_role,
      v_agg.appearances, v_agg.starts, v_agg.goals, v_agg.assists,
      v_agg.avg_rating, v_agg.potm_awards, v_agg.clean_sheets, v_agg.ballon_points
    )
    ON CONFLICT (season_id, player_id, club_short_name)
    DO UPDATE SET
      division = excluded.division,
      player_position = excluded.player_position,
      stat_role = excluded.stat_role,
      appearances = excluded.appearances,
      starts = excluded.starts,
      goals = excluded.goals,
      assists = excluded.assists,
      avg_rating = excluded.avg_rating,
      potm_awards = excluded.potm_awards,
      clean_sheets = excluded.clean_sheets,
      ballon_points = excluded.ballon_points,
      archived_at = now();

    v_players := v_players + 1;
  END LOOP;

  -- Season awards (min 5 league apps for Ballon)
  DELETE FROM public.competition_season_award WHERE season_id = v_season.id;

  SELECT a.*
  INTO v_ballon
  FROM public.competition_player_season_archive a
  WHERE a.season_id = v_season.id
    AND a.appearances >= 5
  ORDER BY a.ballon_points DESC, a.goals DESC, a.assists DESC
  LIMIT 1;

  IF FOUND AND v_ballon.ballon_points > 0 THEN
    INSERT INTO public.competition_season_award (
      season_id, season_label, award_type, player_id, club_short_name,
      stat_value, detail
    )
    VALUES (
      v_season.id, v_season.label, 'ballon_dor',
      v_ballon.player_id, v_ballon.club_short_name,
      v_ballon.ballon_points,
      jsonb_build_object(
        'goals', v_ballon.goals,
        'assists', v_ballon.assists,
        'potm', v_ballon.potm_awards,
        'clean_sheets', v_ballon.clean_sheets,
        'avg_rating', v_ballon.avg_rating,
        'stat_role', v_ballon.stat_role
      )
    );
  END IF;

  SELECT a.*
  INTO v_boot
  FROM public.competition_player_season_archive a
  WHERE a.season_id = v_season.id AND a.goals > 0
  ORDER BY a.goals DESC, a.assists DESC
  LIMIT 1;

  IF FOUND THEN
    INSERT INTO public.competition_season_award (
      season_id, season_label, award_type, player_id, club_short_name, stat_value
    )
    VALUES (
      v_season.id, v_season.label, 'golden_boot',
      v_boot.player_id, v_boot.club_short_name, v_boot.goals
    );
  END IF;

  SELECT a.*
  INTO v_play
  FROM public.competition_player_season_archive a
  WHERE a.season_id = v_season.id AND a.assists > 0
  ORDER BY a.assists DESC, a.goals DESC
  LIMIT 1;

  IF FOUND THEN
    INSERT INTO public.competition_season_award (
      season_id, season_label, award_type, player_id, club_short_name, stat_value
    )
    VALUES (
      v_season.id, v_season.label, 'golden_playmaker',
      v_play.player_id, v_play.club_short_name, v_play.assists
    );
  END IF;

  SELECT a.*
  INTO v_potm
  FROM public.competition_player_season_archive a
  WHERE a.season_id = v_season.id AND a.potm_awards > 0
  ORDER BY a.potm_awards DESC, a.goals DESC
  LIMIT 1;

  IF FOUND THEN
    INSERT INTO public.competition_season_award (
      season_id, season_label, award_type, player_id, club_short_name, stat_value
    )
    VALUES (
      v_season.id, v_season.label, 'season_potm',
      v_potm.player_id, v_potm.club_short_name, v_potm.potm_awards
    );
  END IF;

  SELECT a.*
  INTO v_glove
  FROM public.competition_player_season_archive a
  WHERE a.season_id = v_season.id
    AND a.stat_role = 'goalkeeper'
    AND a.clean_sheets > 0
  ORDER BY a.clean_sheets DESC, a.avg_rating DESC NULLS LAST
  LIMIT 1;

  IF FOUND THEN
    INSERT INTO public.competition_season_award (
      season_id, season_label, award_type, player_id, club_short_name, stat_value
    )
    VALUES (
      v_season.id, v_season.label, 'golden_glove',
      v_glove.player_id, v_glove.club_short_name, v_glove.clean_sheets
    );
  END IF;

  v_finance := public.competition_archive_club_finances_for_season(v_season.id);

  RETURN jsonb_build_object(
    'ok', true,
    'season_id', v_season.id,
    'season_label', v_season.label,
    'clubs_archived', v_clubs,
    'players_archived', v_players,
    'cups_archived', v_cups,
    'clubs_finance_archived', v_finance
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public views
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_club_honours_public
WITH (security_invoker = false)
AS
SELECT
  a.club_short_name,
  c."Club" AS club_name,
  a.season_label,
  a.season_id,
  'league_champion'::text AS honour_type,
  CASE a.division
    WHEN 'superleague' THEN 'SuperLeague champions'
    WHEN 'championship_a' THEN 'Championship A champions'
    WHEN 'championship_b' THEN 'Championship B champions'
    ELSE a.division
  END AS honour_label,
  a.division,
  NULL::text AS cup_code,
  a.created_at AS honoured_at
FROM public.competition_club_season_archive a
JOIN public."Clubs" c ON c."ShortName" = a.club_short_name
WHERE a.final_position = 1

UNION ALL

SELECT
  w.winner_club_short_name,
  c."Club",
  w.season_label,
  w.season_id,
  'cup_winner',
  CASE w.cup_code
    WHEN 'super8' THEN 'Super8 winners'
    WHEN 'plate' THEN 'Plate winners'
    WHEN 'shield' THEN 'Shield winners'
    WHEN 'bowl' THEN 'Bowl winners'
    WHEN 'league_cup' THEN 'League Cup winners'
    ELSE w.cup_code
  END,
  NULL,
  w.cup_code,
  w.archived_at
FROM public.competition_cup_season_winner w
JOIN public."Clubs" c ON c."ShortName" = w.winner_club_short_name;

CREATE OR REPLACE VIEW public.competition_player_career_public
WITH (security_invoker = false)
AS
SELECT
  a.season_id,
  a.season_label,
  a.player_id,
  p."Name" AS player_name,
  a.club_short_name,
  c."Club" AS club_name,
  a.division,
  a.player_position,
  a.stat_role,
  a.appearances,
  a.starts,
  a.goals,
  a.assists,
  a.avg_rating,
  a.potm_awards,
  a.clean_sheets,
  a.ballon_points,
  false AS is_live,
  a.archived_at AS as_of
FROM public.competition_player_season_archive a
JOIN public."Players" p ON p."Konami_ID"::text = a.player_id
JOIN public."Clubs" c ON c."ShortName" = a.club_short_name

UNION ALL

SELECT
  m.season_id,
  s.label,
  m.player_id,
  p."Name",
  m.club_short_name,
  c."Club",
  ccs.division,
  p."Position",
  public.competition_player_stat_role(p."Position"),
  count(*) FILTER (WHERE m.appeared)::int,
  count(*) FILTER (WHERE m.started)::int,
  coalesce(sum(m.goals), 0)::int,
  coalesce(sum(m.assists), 0)::int,
  round(avg(m.rating) FILTER (WHERE m.rating IS NOT NULL), 2),
  count(*) FILTER (WHERE m.is_player_of_match)::int,
  public.competition_player_clean_sheets(m.season_id, m.player_id, m.club_short_name, true),
  public.competition_player_ballon_points(
    count(*) FILTER (WHERE m.appeared)::int,
    coalesce(sum(m.goals), 0)::int,
    coalesce(sum(m.assists), 0)::int,
    round(avg(m.rating) FILTER (WHERE m.rating IS NOT NULL), 2),
    count(*) FILTER (WHERE m.is_player_of_match)::int,
    public.competition_player_clean_sheets(m.season_id, m.player_id, m.club_short_name, true),
    public.competition_player_stat_role(p."Position")
  ),
  true,
  now()
FROM public.competition_match_player_stats m
JOIN public.competition_fixtures f ON f.id = m.fixture_id
JOIN public.competition_seasons s ON s.id = m.season_id
JOIN public."Players" p ON p."Konami_ID"::text = m.player_id
JOIN public."Clubs" c ON c."ShortName" = m.club_short_name
LEFT JOIN public.competition_club_seasons ccs
  ON ccs.season_id = m.season_id AND ccs.club_short_name = m.club_short_name
WHERE s.is_current = true
  AND s.status = 'active'
  AND f.status = 'played'
  AND NOT EXISTS (
    SELECT 1
    FROM public.competition_player_season_archive ar
    WHERE ar.season_id = m.season_id
      AND ar.player_id = m.player_id
      AND ar.club_short_name = m.club_short_name
  )
GROUP BY
  m.season_id, s.label, m.player_id, p."Name", m.club_short_name,
  c."Club", ccs.division, p."Position";

CREATE OR REPLACE VIEW public.competition_season_awards_public
WITH (security_invoker = false)
AS
SELECT
  a.season_id,
  a.season_label,
  a.award_type,
  a.player_id,
  p."Name" AS player_name,
  a.club_short_name,
  c."Club" AS club_name,
  a.stat_value,
  a.detail,
  a.awarded_at
FROM public.competition_season_award a
JOIN public."Players" p ON p."Konami_ID"::text = a.player_id
JOIN public."Clubs" c ON c."ShortName" = a.club_short_name;

CREATE OR REPLACE VIEW public.competition_club_season_history_public
WITH (security_invoker = false)
AS
SELECT
  a.club_short_name,
  c."Club" AS club_name,
  a.season_label,
  a.season_id,
  a.division,
  a.final_position,
  a.mp,
  a.won,
  a.drawn,
  a.lost,
  a.gf,
  a.ga,
  a.gd,
  a.pts,
  a.created_at
FROM public.competition_club_season_archive a
JOIN public."Clubs" c ON c."ShortName" = a.club_short_name;

-- ---------------------------------------------------------------------------
-- Transfer season label (for club history records)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.transfer_history_season_label(p_transfer_time timestamptz)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(
    (
      SELECT s.label
      FROM public.competition_seasons s
      WHERE p_transfer_time IS NOT NULL
        AND s.started_at IS NOT NULL
        AND p_transfer_time >= s.started_at
        AND (s.ended_at IS NULL OR p_transfer_time < s.ended_at)
      ORDER BY s.started_at DESC
      LIMIT 1
    ),
    (
      SELECT s.label
      FROM public.competition_seasons s
      WHERE s.is_current
      ORDER BY s.id DESC
      LIMIT 1
    ),
    to_char(p_transfer_time AT TIME ZONE 'UTC', 'YYYY')
  );
$$;

-- ---------------------------------------------------------------------------
-- Club history bundle RPC
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_club_history_bundle(p_club_short_name text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := upper(btrim(p_club_short_name));
  v_honours jsonb;
  v_seasons jsonb;
  v_awards jsonb;
  v_records jsonb;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RETURN '{}'::jsonb;
  END IF;

  SELECT coalesce(jsonb_agg(row_to_json(h) ORDER BY h.honoured_at DESC), '[]'::jsonb)
  INTO v_honours
  FROM public.competition_club_honours_public h
  WHERE h.club_short_name = v_club;

  SELECT coalesce(jsonb_agg(row_to_json(s) ORDER BY s.season_label DESC), '[]'::jsonb)
  INTO v_seasons
  FROM public.competition_club_season_history_public s
  WHERE s.club_short_name = v_club;

  SELECT coalesce(jsonb_agg(row_to_json(a) ORDER BY a.season_label DESC), '[]'::jsonb)
  INTO v_awards
  FROM public.competition_season_awards_public a
  WHERE a.club_short_name = v_club
    AND a.award_type = 'ballon_dor';

  WITH career AS (
    SELECT *
    FROM public.competition_player_career_public
    WHERE club_short_name = v_club
  ),
  totals AS (
    SELECT
      player_id,
      max(player_name) AS player_name,
      sum(goals)::int AS total_goals,
      sum(assists)::int AS total_assists,
      sum(potm_awards)::int AS total_potm,
      sum(appearances)::int AS total_apps
    FROM career
    GROUP BY player_id
  ),
  season_totals AS (
    SELECT
      player_id,
      max(player_name) AS player_name,
      season_label,
      sum(goals)::int AS goals,
      sum(assists)::int AS assists,
      sum(potm_awards)::int AS potm_awards
    FROM career
    GROUP BY player_id, season_label
  )
  SELECT jsonb_build_object(
    'all_time_top_scorer',
      (SELECT row_to_json(t) FROM totals t ORDER BY total_goals DESC, total_assists DESC LIMIT 1),
    'all_time_top_assists',
      (SELECT row_to_json(t) FROM totals t ORDER BY total_assists DESC, total_goals DESC LIMIT 1),
    'all_time_top_potm',
      (SELECT row_to_json(t) FROM totals t ORDER BY total_potm DESC, total_goals DESC LIMIT 1),
    'season_top_goals',
      (SELECT row_to_json(s) FROM season_totals s ORDER BY goals DESC, assists DESC LIMIT 1),
    'season_top_assists',
      (SELECT row_to_json(s) FROM season_totals s ORDER BY assists DESC, goals DESC LIMIT 1),
    'season_top_potm',
      (SELECT row_to_json(s) FROM season_totals s ORDER BY potm_awards DESC, goals DESC LIMIT 1),
    'record_signing',
      (
        SELECT row_to_json(x)
        FROM (
          SELECT
            h.player_id::text AS player_id,
            p."Name" AS player_name,
            h.fee::numeric AS fee,
            coalesce(h.agent_fee, 0)::numeric AS agent_fee,
            (coalesce(h.fee, 0) + coalesce(h.agent_fee, 0))::numeric AS total_cost,
            public.transfer_history_season_label(h.transfer_time) AS season_label,
            h.seller_club_id,
            h.buyer_club_id,
            h.foreign_buyer_name,
            h.transfer_sale_note,
            h.transfer_time
          FROM public."Transfer_History" h
          LEFT JOIN public."Players" p ON p."Konami_ID"::text = h.player_id::text
          WHERE upper(btrim(h.buyer_club_id)) = v_club
            AND coalesce(h.fee, 0) > 0
          ORDER BY
            (coalesce(h.fee, 0) + coalesce(h.agent_fee, 0)) DESC,
            h.fee DESC,
            h.transfer_time DESC
          LIMIT 1
        ) x
      ),
    'record_sale',
      (
        SELECT row_to_json(x)
        FROM (
          SELECT
            h.player_id::text AS player_id,
            p."Name" AS player_name,
            h.fee::numeric AS fee,
            public.transfer_history_season_label(h.transfer_time) AS season_label,
            h.seller_club_id,
            h.buyer_club_id,
            h.foreign_buyer_name,
            h.transfer_sale_note,
            h.transfer_time
          FROM public."Transfer_History" h
          LEFT JOIN public."Players" p ON p."Konami_ID"::text = h.player_id::text
          WHERE upper(btrim(h.seller_club_id)) = v_club
            AND coalesce(h.fee, 0) > 0
          ORDER BY h.fee DESC, h.transfer_time DESC
          LIMIT 1
        ) x
      )
  )
  INTO v_records;

  RETURN jsonb_build_object(
    'club_short_name', v_club,
    'honours', coalesce(v_honours, '[]'::jsonb),
    'seasons', coalesce(v_seasons, '[]'::jsonb),
    'ballon_winners', coalesce(v_awards, '[]'::jsonb),
    'records', coalesce(v_records, '{}'::jsonb)
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_player_career_bundle(p_player_id text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_pid text := btrim(p_player_id);
  v_player jsonb;
  v_stints jsonb;
  v_awards jsonb;
  v_totals jsonb;
BEGIN
  SELECT to_jsonb(p)
  INTO v_player
  FROM (
    SELECT
      p."Konami_ID" AS player_id,
      p."Name" AS player_name,
      p."Position" AS position,
      p."Rating" AS rating,
      p."Nation" AS nation,
      p."Contracted_Team" AS current_club
    FROM public."Players" p
    WHERE p."Konami_ID"::text = v_pid
    LIMIT 1
  ) p;

  SELECT coalesce(jsonb_agg(row_to_json(c) ORDER BY c.season_label DESC), '[]'::jsonb)
  INTO v_stints
  FROM public.competition_player_career_public c
  WHERE c.player_id = v_pid;

  SELECT coalesce(jsonb_agg(row_to_json(a) ORDER BY a.season_label DESC), '[]'::jsonb)
  INTO v_awards
  FROM public.competition_season_awards_public a
  WHERE a.player_id = v_pid;

  SELECT jsonb_build_object(
    'appearances', coalesce(sum(appearances), 0),
    'goals', coalesce(sum(goals), 0),
    'assists', coalesce(sum(assists), 0),
    'potm_awards', coalesce(sum(potm_awards), 0),
    'clean_sheets', coalesce(sum(clean_sheets), 0),
    'avg_rating', round(avg(avg_rating) FILTER (WHERE avg_rating IS NOT NULL), 2)
  )
  INTO v_totals
  FROM public.competition_player_career_public c
  WHERE c.player_id = v_pid;

  RETURN jsonb_build_object(
    'player', coalesce(v_player, '{}'::jsonb),
    'stints', coalesce(v_stints, '[]'::jsonb),
    'awards', coalesce(v_awards, '[]'::jsonb),
    'totals', coalesce(v_totals, '{}'::jsonb)
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- RLS + grants
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_cup_season_winner ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_player_season_archive ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_season_award ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_cup_season_winner_select ON public.competition_cup_season_winner;
CREATE POLICY competition_cup_season_winner_select ON public.competition_cup_season_winner
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_player_season_archive_select ON public.competition_player_season_archive;
CREATE POLICY competition_player_season_archive_select ON public.competition_player_season_archive
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_season_award_select ON public.competition_season_award;
CREATE POLICY competition_season_award_select ON public.competition_season_award
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_cup_season_winner_admin ON public.competition_cup_season_winner;
CREATE POLICY competition_cup_season_winner_admin ON public.competition_cup_season_winner
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS competition_player_season_archive_admin ON public.competition_player_season_archive;
CREATE POLICY competition_player_season_archive_admin ON public.competition_player_season_archive
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS competition_season_award_admin ON public.competition_season_award;
CREATE POLICY competition_season_award_admin ON public.competition_season_award
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.competition_cup_season_winner TO authenticated;
GRANT SELECT ON public.competition_player_season_archive TO authenticated;
GRANT SELECT ON public.competition_season_award TO authenticated;

GRANT SELECT ON public.competition_club_honours_public TO authenticated;
GRANT SELECT ON public.competition_club_honours_public TO anon;
GRANT SELECT ON public.competition_player_career_public TO authenticated;
GRANT SELECT ON public.competition_player_career_public TO anon;
GRANT SELECT ON public.competition_season_awards_public TO authenticated;
GRANT SELECT ON public.competition_season_awards_public TO anon;
GRANT SELECT ON public.competition_club_season_history_public TO authenticated;
GRANT SELECT ON public.competition_club_season_history_public TO anon;

GRANT EXECUTE ON FUNCTION public.competition_admin_archive_season(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.transfer_history_season_label(timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.transfer_history_season_label(timestamptz) TO anon;
GRANT EXECUTE ON FUNCTION public.competition_club_history_bundle(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_club_history_bundle(text) TO anon;
GRANT EXECUTE ON FUNCTION public.competition_player_career_bundle(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_player_career_bundle(text) TO anon;

NOTIFY pgrst, 'reload schema';
