-- =============================================================================
-- GPSL Competition — Phase 0: seasons, divisions, 60-club registration, CH draw
-- Run once in Supabase SQL Editor after transfer / special auction scripts.
-- Spec: docs/competition-spec.md
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_seasons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label text NOT NULL,
  status text NOT NULL DEFAULT 'setup' CHECK (status IN ('setup', 'active', 'complete')),
  is_current boolean NOT NULL DEFAULT false,
  championship_drawn_at timestamptz,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_seasons_label_key UNIQUE (label)
);

CREATE UNIQUE INDEX IF NOT EXISTS competition_seasons_one_current_idx
  ON public.competition_seasons (is_current)
  WHERE is_current = true;

CREATE TABLE IF NOT EXISTS public.competition_club_seasons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  division text NOT NULL DEFAULT 'unassigned' CHECK (
    division IN (
      'unassigned',
      'superleague',
      'championship_pool',
      'championship_a',
      'championship_b'
    )
  ),
  league_position smallint CHECK (
    league_position IS NULL OR (league_position >= 1 AND league_position <= 20)
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_club_seasons_unique UNIQUE (season_id, club_short_name)
);

CREATE INDEX IF NOT EXISTS competition_club_seasons_season_div_idx
  ON public.competition_club_seasons (season_id, division);

-- ---------------------------------------------------------------------------
-- Helpers (is_gpsl_admin may already exist from special_auctions.sql)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.is_gpsl_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(auth.jwt() ->> 'email', '') = 'rotavator66@outlook.com';
$$;

CREATE OR REPLACE FUNCTION public.competition_division_counts(p_season_id bigint)
RETURNS TABLE (division text, cnt bigint)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT ccs.division, count(*)::bigint
  FROM public.competition_club_seasons ccs
  WHERE ccs.season_id = p_season_id
  GROUP BY ccs.division;
$$;

CREATE OR REPLACE FUNCTION public.competition_assert_setup_season(p_season_id bigint)
RETURNS public.competition_seasons
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season public.competition_seasons;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_season
  FROM public.competition_seasons
  WHERE id = p_season_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Season not found';
  END IF;

  IF v_season.status <> 'setup' THEN
    RAISE EXCEPTION 'Season is not in setup status';
  END IF;

  RETURN v_season;
END;
$function$;

-- ---------------------------------------------------------------------------
-- RPC: create season + seed all 60 clubs as unassigned
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_create_season(p_label text)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_label text := trim(p_label);
  v_season_id bigint;
  v_club_count bigint;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF v_label IS NULL OR v_label = '' THEN
    RAISE EXCEPTION 'Season label is required';
  END IF;

  INSERT INTO public.competition_seasons (label, status, is_current)
  VALUES (v_label, 'setup', false)
  RETURNING id INTO v_season_id;

  INSERT INTO public.competition_club_seasons (season_id, club_short_name, division)
  SELECT v_season_id, c."ShortName", 'unassigned'
  FROM public."Clubs" c
  ORDER BY c."ShortName";

  GET DIAGNOSTICS v_club_count = ROW_COUNT;

  IF v_club_count <> 60 THEN
    RAISE EXCEPTION 'Expected 60 clubs, found %', v_club_count;
  END IF;

  RETURN v_season_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- RPC: set one club division during setup
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_set_club_division(
  p_season_id bigint,
  p_club_short_name text,
  p_division text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  PERFORM public.competition_assert_setup_season(p_season_id);

  IF p_division NOT IN ('unassigned', 'superleague', 'championship_pool') THEN
    RAISE EXCEPTION 'Invalid setup division: %', p_division;
  END IF;

  UPDATE public.competition_club_seasons
  SET division = p_division
  WHERE season_id = p_season_id
    AND club_short_name = p_club_short_name;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Club not registered for this season';
  END IF;
END;
$function$;

-- ---------------------------------------------------------------------------
-- RPC: bulk assign divisions (admin UI save)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_bulk_set_divisions(
  p_season_id bigint,
  p_assignments jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_item jsonb;
  v_club text;
  v_division text;
BEGIN
  PERFORM public.competition_assert_setup_season(p_season_id);

  IF p_assignments IS NULL OR jsonb_typeof(p_assignments) <> 'array' THEN
    RAISE EXCEPTION 'Assignments must be a JSON array';
  END IF;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_assignments)
  LOOP
    v_club := trim(both '"' FROM (v_item ->> 'club'));
    v_division := v_item ->> 'division';

    IF v_club IS NULL OR v_club = '' THEN
      RAISE EXCEPTION 'Each assignment needs club';
    END IF;

    IF v_division NOT IN ('unassigned', 'superleague', 'championship_pool') THEN
      RAISE EXCEPTION 'Invalid division for %: %', v_club, v_division;
    END IF;

    UPDATE public.competition_club_seasons
    SET division = v_division
    WHERE season_id = p_season_id
      AND club_short_name = v_club;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Club not registered for this season: %', v_club;
    END IF;
  END LOOP;
END;
$function$;

-- ---------------------------------------------------------------------------
-- RPC: random Championship A / B draw (40 pool clubs → 20 + 20)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_draw_championship_ab(p_season_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_pool_count bigint;
  v_sl_count bigint;
BEGIN
  PERFORM public.competition_assert_setup_season(p_season_id);

  SELECT count(*) INTO v_sl_count
  FROM public.competition_club_seasons
  WHERE season_id = p_season_id AND division = 'superleague';

  IF v_sl_count <> 20 THEN
    RAISE EXCEPTION 'SuperLeague must have exactly 20 clubs (currently %)', v_sl_count;
  END IF;

  SELECT count(*) INTO v_pool_count
  FROM public.competition_club_seasons
  WHERE season_id = p_season_id AND division = 'championship_pool';

  IF v_pool_count <> 40 THEN
    RAISE EXCEPTION 'Championship pool must have exactly 40 clubs (currently %)', v_pool_count;
  END IF;

  WITH ranked AS (
    SELECT
      club_short_name,
      row_number() OVER (ORDER BY random()) AS rn
    FROM public.competition_club_seasons
    WHERE season_id = p_season_id
      AND division = 'championship_pool'
  )
  UPDATE public.competition_club_seasons ccs
  SET division = CASE
    WHEN r.rn <= 20 THEN 'championship_a'
    ELSE 'championship_b'
  END
  FROM ranked r
  WHERE ccs.season_id = p_season_id
    AND ccs.club_short_name = r.club_short_name;

  UPDATE public.competition_seasons
  SET championship_drawn_at = now()
  WHERE id = p_season_id;

  RETURN jsonb_build_object(
    'championship_a',
    (SELECT count(*) FROM public.competition_club_seasons
     WHERE season_id = p_season_id AND division = 'championship_a'),
    'championship_b',
    (SELECT count(*) FROM public.competition_club_seasons
     WHERE season_id = p_season_id AND division = 'championship_b')
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- RPC: activate season (20 + 20 + 20, becomes current)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_activate_season(p_season_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_sl bigint;
  v_a bigint;
  v_b bigint;
  v_bad bigint;
BEGIN
  PERFORM public.competition_assert_setup_season(p_season_id);

  SELECT count(*) INTO v_sl
  FROM public.competition_club_seasons
  WHERE season_id = p_season_id AND division = 'superleague';

  SELECT count(*) INTO v_a
  FROM public.competition_club_seasons
  WHERE season_id = p_season_id AND division = 'championship_a';

  SELECT count(*) INTO v_b
  FROM public.competition_club_seasons
  WHERE season_id = p_season_id AND division = 'championship_b';

  SELECT count(*) INTO v_bad
  FROM public.competition_club_seasons
  WHERE season_id = p_season_id
    AND division IN ('unassigned', 'championship_pool');

  IF v_sl <> 20 OR v_a <> 20 OR v_b <> 20 THEN
    RAISE EXCEPTION 'Need 20 SuperLeague + 20 CH A + 20 CH B (have % / % / %)',
      v_sl, v_a, v_b;
  END IF;

  IF v_bad > 0 THEN
    RAISE EXCEPTION '% clubs still unassigned or in championship pool', v_bad;
  END IF;

  UPDATE public.competition_seasons
  SET is_current = false
  WHERE is_current = true;

  UPDATE public.competition_seasons
  SET status = 'active',
      is_current = true,
      started_at = coalesce(started_at, now())
  WHERE id = p_season_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- RPC: re-draw A/B (setup only, pool clubs must be restored first)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_reset_championship_draw(p_season_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  PERFORM public.competition_assert_setup_season(p_season_id);

  UPDATE public.competition_club_seasons
  SET division = 'championship_pool'
  WHERE season_id = p_season_id
    AND division IN ('championship_a', 'championship_b');

  UPDATE public.competition_seasons
  SET championship_drawn_at = NULL
  WHERE id = p_season_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public read view (current + active seasons)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_season_public
WITH (security_invoker = false)
AS
SELECT
  id,
  label,
  status,
  is_current,
  championship_drawn_at,
  started_at,
  ended_at,
  created_at
FROM public.competition_seasons
WHERE status IN ('setup', 'active')
ORDER BY is_current DESC, created_at DESC;

GRANT SELECT ON public.competition_season_public TO authenticated;
GRANT SELECT ON public.competition_season_public TO anon;

CREATE OR REPLACE VIEW public.competition_club_season_public
WITH (security_invoker = false)
AS
SELECT
  ccs.id,
  ccs.season_id,
  ccs.club_short_name,
  c."Club" AS club_name,
  ccs.division,
  ccs.league_position
FROM public.competition_club_seasons ccs
JOIN public."Clubs" c ON c."ShortName" = ccs.club_short_name
JOIN public.competition_seasons s ON s.id = ccs.season_id
WHERE s.status = 'active' AND s.is_current = true;

GRANT SELECT ON public.competition_club_season_public TO authenticated;
GRANT SELECT ON public.competition_club_season_public TO anon;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_club_seasons ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_seasons_select ON public.competition_seasons;
CREATE POLICY competition_seasons_select ON public.competition_seasons
  FOR SELECT
  TO authenticated
  USING (status IN ('active', 'setup'));

DROP POLICY IF EXISTS competition_seasons_admin ON public.competition_seasons;
CREATE POLICY competition_seasons_admin ON public.competition_seasons
  FOR ALL
  TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS competition_club_seasons_select ON public.competition_club_seasons;
CREATE POLICY competition_club_seasons_select ON public.competition_club_seasons
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.competition_seasons s
      WHERE s.id = season_id
        AND s.status IN ('active', 'setup')
    )
  );

DROP POLICY IF EXISTS competition_club_seasons_admin ON public.competition_club_seasons;
CREATE POLICY competition_club_seasons_admin ON public.competition_club_seasons
  FOR ALL
  TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.competition_seasons TO authenticated;
GRANT SELECT ON public.competition_club_seasons TO authenticated;

GRANT EXECUTE ON FUNCTION public.competition_create_season(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_set_club_division(bigint, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_bulk_set_divisions(bigint, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_draw_championship_ab(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_activate_season(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_reset_championship_draw(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_division_counts(bigint) TO authenticated;
