-- =============================================================================
-- GPSL Competition — Phase 6: prestige cups + league cup (knockout brackets)
-- Requires: competition_phase0–5
-- Spec: docs/competition-spec.md
-- =============================================================================

-- Cup fixtures use division = 'cup', competition_type = 'cup', cup_code + cup_round + cup_match

ALTER TABLE public.competition_fixtures
  DROP CONSTRAINT IF EXISTS competition_fixtures_division_check;

ALTER TABLE public.competition_fixtures
  ADD CONSTRAINT competition_fixtures_division_check
  CHECK (division IN ('superleague', 'championship_a', 'championship_b', 'cup'));

ALTER TABLE public.competition_fixtures
  ADD COLUMN IF NOT EXISTS cup_code text,
  ADD COLUMN IF NOT EXISTS cup_round smallint,
  ADD COLUMN IF NOT EXISTS cup_match smallint;

ALTER TABLE public.competition_fixtures
  DROP CONSTRAINT IF EXISTS competition_fixtures_cup_fields_check;

ALTER TABLE public.competition_fixtures
  ADD CONSTRAINT competition_fixtures_cup_fields_check
  CHECK (
    (competition_type = 'league' AND cup_code IS NULL)
    OR (
      competition_type = 'cup'
      AND cup_code IN ('super8', 'plate', 'shield', 'spoon', 'league_cup')
      AND cup_round IS NOT NULL
      AND cup_match IS NOT NULL
    )
  );

CREATE UNIQUE INDEX IF NOT EXISTS competition_fixtures_cup_unique_idx
  ON public.competition_fixtures (season_id, cup_code, cup_round, cup_match)
  WHERE competition_type = 'cup';

-- ---------------------------------------------------------------------------
-- Bracket nodes (winner feeds child node home/away slot)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_cup_bracket_nodes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  cup_code text NOT NULL CHECK (
    cup_code IN ('super8', 'plate', 'shield', 'spoon', 'league_cup')
  ),
  round_no smallint NOT NULL CHECK (round_no >= 1),
  match_no smallint NOT NULL CHECK (match_no >= 1),
  home_club_short_name text REFERENCES public."Clubs" ("ShortName"),
  away_club_short_name text REFERENCES public."Clubs" ("ShortName"),
  fixture_id bigint REFERENCES public.competition_fixtures (id) ON DELETE SET NULL,
  winner_club_short_name text REFERENCES public."Clubs" ("ShortName"),
  child_node_id bigint REFERENCES public.competition_cup_bracket_nodes (id) ON DELETE SET NULL,
  child_slot text CHECK (child_slot IS NULL OR child_slot IN ('home', 'away')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_cup_bracket_nodes_unique UNIQUE (season_id, cup_code, round_no, match_no)
);

CREATE INDEX IF NOT EXISTS competition_cup_bracket_nodes_fixture_idx
  ON public.competition_cup_bracket_nodes (fixture_id);

-- Manual qualifiers (CH 16v17 shield/spoon playoffs before draw)
CREATE TABLE IF NOT EXISTS public.competition_cup_manual_qualifiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  cup_code text NOT NULL CHECK (cup_code IN ('shield', 'spoon')),
  division text NOT NULL CHECK (division IN ('championship_a', 'championship_b')),
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  qualifier_role text NOT NULL CHECK (qualifier_role IN ('shield_playoff_winner', 'spoon_playoff_loser')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_cup_manual_qualifiers_unique UNIQUE (
    season_id, cup_code, division, qualifier_role
  )
);

-- Prize money config (instant payout on confirm)
CREATE TABLE IF NOT EXISTS public.competition_cup_prize_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  cup_code text NOT NULL CHECK (
    cup_code IN ('super8', 'plate', 'shield', 'spoon', 'league_cup')
  ),
  stage text NOT NULL CHECK (
    stage IN ('appearance', 'r1', 'r2', 'qf', 'sf', 'final', 'winner')
  ),
  amount numeric(14, 2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
  CONSTRAINT competition_cup_prize_config_unique UNIQUE (season_id, cup_code, stage)
);

-- Track per-fixture prize paid (idempotent)
CREATE TABLE IF NOT EXISTS public.competition_cup_prize_paid (
  fixture_id bigint NOT NULL REFERENCES public.competition_fixtures (id) ON DELETE CASCADE,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  stage text NOT NULL,
  amount numeric(14, 2) NOT NULL,
  PRIMARY KEY (fixture_id, club_short_name, stage)
);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_active_season_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id
  FROM public.competition_seasons
  WHERE is_current = true AND status = 'active'
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.competition_cup_round_stage(p_cup_code text, p_round_no int, p_max_round int)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $function$
BEGIN
  IF p_round_no = p_max_round THEN
    RETURN 'final';
  ELSIF p_round_no = p_max_round - 1 THEN
    RETURN 'sf';
  ELSIF p_round_no = p_max_round - 2 THEN
    RETURN 'qf';
  ELSIF p_round_no = 1 THEN
    RETURN 'r1';
  ELSE
    RETURN 'r2';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_cup_fixture_label(p_fixture public.competition_fixtures)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT format(
    '%s R%s M%s',
    upper(replace(coalesce(p_fixture.cup_code, 'cup'), '_', ' ')),
    p_fixture.cup_round,
    p_fixture.cup_match
  );
$$;

-- ---------------------------------------------------------------------------
-- Qualification lists from standings (+ manual playoff slots)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_qualify_cup_clubs(
  p_season_id bigint,
  p_cup_code text
)
RETURNS text[]
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_clubs text[] := ARRAY[]::text[];
BEGIN
  IF p_cup_code = 'super8' THEN
    SELECT array_agg(s.club_short_name ORDER BY s.table_position)
    INTO v_clubs
    FROM public.competition_standings_public s
    WHERE s.season_id = p_season_id
      AND s.division = 'superleague'
      AND s.table_position <= 8;
  ELSIF p_cup_code = 'plate' THEN
    SELECT array_agg(x.club ORDER BY x.sort_key, x.club)
    INTO v_clubs
    FROM (
      SELECT s.club_short_name AS club, s.table_position AS sort_key
      FROM public.competition_standings_public s
      WHERE s.season_id = p_season_id
        AND s.division = 'superleague'
        AND s.table_position BETWEEN 9 AND 16
      UNION ALL
      SELECT s.club_short_name, 100 + s.table_position
      FROM public.competition_standings_public s
      WHERE s.season_id = p_season_id
        AND s.division = 'championship_a'
        AND s.table_position <= 4
      UNION ALL
      SELECT s.club_short_name, 200 + s.table_position
      FROM public.competition_standings_public s
      WHERE s.season_id = p_season_id
        AND s.division = 'championship_b'
        AND s.table_position <= 4
    ) x;
  ELSIF p_cup_code = 'shield' THEN
    SELECT array_agg(x.club ORDER BY x.sort_key, x.club)
    INTO v_clubs
    FROM (
      SELECT s.club_short_name AS club, s.table_position AS sort_key
      FROM public.competition_standings_public s
      WHERE s.season_id = p_season_id
        AND s.division = 'superleague'
        AND s.table_position BETWEEN 17 AND 20
      UNION ALL
      SELECT s.club_short_name, 100 + s.table_position
      FROM public.competition_standings_public s
      WHERE s.season_id = p_season_id
        AND s.division = 'championship_a'
        AND s.table_position BETWEEN 5 AND 15
      UNION ALL
      SELECT s.club_short_name, 100 + s.table_position
      FROM public.competition_standings_public s
      WHERE s.season_id = p_season_id
        AND s.division = 'championship_b'
        AND s.table_position BETWEEN 5 AND 15
      UNION ALL
      SELECT q.club_short_name, 50
      FROM public.competition_cup_manual_qualifiers q
      WHERE q.season_id = p_season_id
        AND q.cup_code = 'shield'
        AND q.qualifier_role = 'shield_playoff_winner'
    ) x;
  ELSIF p_cup_code = 'spoon' THEN
    SELECT array_agg(x.club ORDER BY x.sort_key, x.club)
    INTO v_clubs
    FROM (
      SELECT s.club_short_name AS club, s.table_position AS sort_key
      FROM public.competition_standings_public s
      WHERE s.season_id = p_season_id
        AND s.division = 'championship_a'
        AND s.table_position >= 18
      UNION ALL
      SELECT s.club_short_name, 100 + s.table_position
      FROM public.competition_standings_public s
      WHERE s.season_id = p_season_id
        AND s.division = 'championship_b'
        AND s.table_position >= 18
      UNION ALL
      SELECT q.club_short_name, 50
      FROM public.competition_cup_manual_qualifiers q
      WHERE q.season_id = p_season_id
        AND q.cup_code = 'spoon'
        AND q.qualifier_role = 'spoon_playoff_loser'
    ) x;
  ELSIF p_cup_code = 'league_cup' THEN
    SELECT array_agg(ccs.club_short_name ORDER BY ccs.club_short_name)
    INTO v_clubs
    FROM public.competition_club_seasons ccs
    WHERE ccs.season_id = p_season_id
      AND ccs.division IN ('superleague', 'championship_a', 'championship_b');
  END IF;

  RETURN coalesce(v_clubs, ARRAY[]::text[]);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Create cup fixture for a bracket node
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_create_cup_fixture_for_node(p_node_id bigint)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_node public.competition_cup_bracket_nodes;
  v_fixture_id bigint;
BEGIN
  SELECT * INTO v_node FROM public.competition_cup_bracket_nodes WHERE id = p_node_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Bracket node not found';
  END IF;

  IF v_node.home_club_short_name IS NULL OR v_node.away_club_short_name IS NULL THEN
    RETURN NULL;
  END IF;

  IF v_node.fixture_id IS NOT NULL THEN
    RETURN v_node.fixture_id;
  END IF;

  INSERT INTO public.competition_fixtures (
    season_id,
    division,
    competition_type,
    matchday,
    gpsl_month,
    week_in_month,
    home_club_short_name,
    away_club_short_name,
    weather,
    cup_code,
    cup_round,
    cup_match
  )
  VALUES (
    v_node.season_id,
    'cup',
    'cup',
    v_node.round_no,
    'may',
    1,
    v_node.home_club_short_name,
    v_node.away_club_short_name,
    'clear',
    v_node.cup_code,
    v_node.round_no,
    v_node.match_no
  )
  RETURNING id INTO v_fixture_id;

  UPDATE public.competition_cup_bracket_nodes
  SET fixture_id = v_fixture_id
  WHERE id = p_node_id;

  RETURN v_fixture_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Build knockout bracket (power-of-2 with byes for top seeds)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_build_knockout_bracket(
  p_season_id bigint,
  p_cup_code text,
  p_clubs text[]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_n int;
  v_target int := 1;
  v_byes int;
  v_players text[];
  v_byes_clubs text[];
  v_round int;
  v_max_round int;
  v_matches_in_round int;
  v_match int;
  v_home text;
  v_away text;
  v_i int;
  v_idx int;
  v_node_id bigint;
  v_parent_id bigint;
  v_child_id bigint;
  v_prev_round_ids bigint[];
  v_curr_round_ids bigint[];
  v_r2_ids bigint[];
  v_node record;
  v_r1_count int := 0;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_clubs IS NULL OR array_length(p_clubs, 1) IS NULL OR array_length(p_clubs, 1) < 2 THEN
    RAISE EXCEPTION 'Need at least 2 clubs to draw %', p_cup_code;
  END IF;

  DELETE FROM public.competition_cup_bracket_nodes
  WHERE season_id = p_season_id AND cup_code = p_cup_code;

  DELETE FROM public.competition_fixtures
  WHERE season_id = p_season_id
    AND competition_type = 'cup'
    AND cup_code = p_cup_code;

  v_n := array_length(p_clubs, 1);
  WHILE v_target < v_n LOOP
    v_target := v_target * 2;
  END LOOP;

  v_byes := v_target - v_n;
  v_byes_clubs := p_clubs[1:v_byes];
  v_players := p_clubs[(v_byes + 1):v_n];

  v_max_round := 0;
  v_matches_in_round := v_target / 2;
  WHILE v_matches_in_round >= 1 LOOP
    v_max_round := v_max_round + 1;
    v_matches_in_round := v_matches_in_round / 2;
  END LOOP;

  v_prev_round_ids := NULL;

  FOR v_round IN 1..v_max_round LOOP
    v_matches_in_round := (v_target / 2) / power(2, v_round - 1)::int;
    v_curr_round_ids := ARRAY[]::bigint[];

    FOR v_match IN 1..v_matches_in_round LOOP
      v_home := NULL;
      v_away := NULL;

      IF v_round = 1 THEN
        v_idx := (v_match - 1) * 2 + 1;
        IF v_idx <= array_length(v_players, 1) THEN
          v_home := v_players[v_idx];
        END IF;
        IF v_idx + 1 <= array_length(v_players, 1) THEN
          v_away := v_players[v_idx + 1];
        END IF;
      END IF;

      INSERT INTO public.competition_cup_bracket_nodes (
        season_id, cup_code, round_no, match_no,
        home_club_short_name, away_club_short_name
      )
      VALUES (p_season_id, p_cup_code, v_round, v_match, v_home, v_away)
      RETURNING id INTO v_node_id;

      v_curr_round_ids := array_append(v_curr_round_ids, v_node_id);

      IF v_round = 1 AND v_home IS NOT NULL AND v_away IS NOT NULL THEN
        PERFORM public.competition_create_cup_fixture_for_node(v_node_id);
        v_r1_count := v_r1_count + 1;
      END IF;
    END LOOP;

    IF v_prev_round_ids IS NOT NULL THEN
      FOR v_i IN 1..array_length(v_prev_round_ids, 1) LOOP
        v_parent_id := v_prev_round_ids[v_i];
        v_child_id := v_curr_round_ids[(v_i + 1) / 2];
        UPDATE public.competition_cup_bracket_nodes
        SET child_node_id = v_child_id,
            child_slot = CASE WHEN v_i % 2 = 1 THEN 'home' ELSE 'away' END
        WHERE id = v_parent_id;
      END LOOP;
    END IF;

    v_prev_round_ids := v_curr_round_ids;
  END LOOP;

  -- Seed bye clubs into round 2 nodes (in match order)
  SELECT array_agg(id ORDER BY match_no)
  INTO v_r2_ids
  FROM public.competition_cup_bracket_nodes
  WHERE season_id = p_season_id
    AND cup_code = p_cup_code
    AND round_no = 2;

  v_i := 1;
  FOR v_match IN 1..coalesce(array_length(v_byes_clubs, 1), 0) LOOP
    EXIT WHEN v_r2_ids IS NULL OR v_i > array_length(v_r2_ids, 1);
    UPDATE public.competition_cup_bracket_nodes n
    SET home_club_short_name = coalesce(n.home_club_short_name, v_byes_clubs[v_match])
    WHERE n.id = v_r2_ids[v_i];
    v_i := v_i + 1;
  END LOOP;

  -- Auto-advance walkover R1 (no away)
  FOR v_node IN
    SELECT * FROM public.competition_cup_bracket_nodes
    WHERE season_id = p_season_id AND cup_code = p_cup_code AND round_no = 1
  LOOP
    IF v_node.away_club_short_name IS NULL
       AND v_node.home_club_short_name IS NOT NULL
       AND v_node.winner_club_short_name IS NULL THEN
      UPDATE public.competition_cup_bracket_nodes
      SET winner_club_short_name = v_node.home_club_short_name
      WHERE id = v_node.id;
      PERFORM public.competition_cup_advance_node_winner(v_node.id);
    END IF;
  END LOOP;

  -- Create fixtures for any round-2+ nodes that already have both clubs
  FOR v_node IN
    SELECT * FROM public.competition_cup_bracket_nodes
    WHERE season_id = p_season_id
      AND cup_code = p_cup_code
      AND home_club_short_name IS NOT NULL
      AND away_club_short_name IS NOT NULL
      AND fixture_id IS NULL
  LOOP
    PERFORM public.competition_create_cup_fixture_for_node(v_node.id);
  END LOOP;

  RETURN jsonb_build_object(
    'cup_code', p_cup_code,
    'clubs', v_n,
    'byes', v_byes,
    'rounds', v_max_round,
    'r1_fixtures', v_r1_count
  );
END;
$function$;

-- ---------------------------------------------------------------------------
-- Advance winner into child bracket slot
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_cup_advance_node_winner(p_node_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_node public.competition_cup_bracket_nodes;
  v_child public.competition_cup_bracket_nodes;
  v_winner text;
BEGIN
  SELECT * INTO v_node FROM public.competition_cup_bracket_nodes WHERE id = p_node_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  v_winner := v_node.winner_club_short_name;
  IF v_winner IS NULL OR v_node.child_node_id IS NULL OR v_node.child_slot IS NULL THEN
    RETURN;
  END IF;

  SELECT * INTO v_child FROM public.competition_cup_bracket_nodes WHERE id = v_node.child_node_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  IF v_node.child_slot = 'home' THEN
    UPDATE public.competition_cup_bracket_nodes
    SET home_club_short_name = v_winner
    WHERE id = v_child.id
      AND home_club_short_name IS DISTINCT FROM v_winner;
  ELSE
    UPDATE public.competition_cup_bracket_nodes
    SET away_club_short_name = v_winner
    WHERE id = v_child.id
      AND away_club_short_name IS DISTINCT FROM v_winner;
  END IF;

  SELECT * INTO v_child FROM public.competition_cup_bracket_nodes WHERE id = v_node.child_node_id;

  IF v_child.home_club_short_name IS NOT NULL AND v_child.away_club_short_name IS NOT NULL THEN
    PERFORM public.competition_create_cup_fixture_for_node(v_child.id);
  END IF;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Cup prizes (instant on confirm)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_pay_cup_fixture_prizes(p_fixture_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_max_round int;
  v_stage text;
  v_winner text;
  v_amount numeric;
  v_club text;
BEGIN
  SELECT * INTO v_fixture
  FROM public.competition_fixtures
  WHERE id = p_fixture_id AND competition_type = 'cup';

  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT max(round_no) INTO v_max_round
  FROM public.competition_cup_bracket_nodes
  WHERE season_id = v_fixture.season_id AND cup_code = v_fixture.cup_code;

  v_stage := public.competition_cup_round_stage(
    v_fixture.cup_code,
    v_fixture.cup_round,
    coalesce(v_max_round, v_fixture.cup_round)
  );

  IF v_fixture.home_goals > v_fixture.away_goals THEN
    v_winner := v_fixture.home_club_short_name;
  ELSIF v_fixture.away_goals > v_fixture.home_goals THEN
    v_winner := v_fixture.away_club_short_name;
  ELSE
    RETURN;
  END IF;

  FOREACH v_club IN ARRAY ARRAY[v_fixture.home_club_short_name, v_fixture.away_club_short_name]
  LOOP
    SELECT amount INTO v_amount
    FROM public.competition_cup_prize_config
    WHERE season_id = v_fixture.season_id
      AND cup_code = v_fixture.cup_code
      AND stage = 'appearance';

    IF v_amount IS NOT NULL AND v_amount > 0
       AND NOT EXISTS (
         SELECT 1 FROM public.competition_cup_prize_paid
         WHERE fixture_id = p_fixture_id
           AND club_short_name = v_club
           AND stage = 'appearance'
       ) THEN
      PERFORM public.competition_credit_club_balance(v_club, v_amount);
      INSERT INTO public.competition_finance_ledger (
        season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
      )
      VALUES (
        v_fixture.season_id,
        p_fixture_id,
        v_club,
        'prize',
        v_amount,
        format('%s appearance — %s', upper(v_fixture.cup_code), public.competition_cup_fixture_label(v_fixture)),
        jsonb_build_object('cup_code', v_fixture.cup_code, 'stage', 'appearance')
      );
      INSERT INTO public.competition_cup_prize_paid (fixture_id, club_short_name, stage, amount)
      VALUES (p_fixture_id, v_club, 'appearance', v_amount);
    END IF;
  END LOOP;

  SELECT amount INTO v_amount
  FROM public.competition_cup_prize_config
  WHERE season_id = v_fixture.season_id
    AND cup_code = v_fixture.cup_code
    AND stage = v_stage;

  IF v_amount IS NOT NULL AND v_amount > 0
     AND NOT EXISTS (
       SELECT 1 FROM public.competition_cup_prize_paid
       WHERE fixture_id = p_fixture_id
         AND club_short_name = v_winner
         AND stage = v_stage
     ) THEN
    PERFORM public.competition_credit_club_balance(v_winner, v_amount);
    INSERT INTO public.competition_finance_ledger (
      season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
    )
    VALUES (
      v_fixture.season_id,
      p_fixture_id,
      v_winner,
      'prize',
      v_amount,
      format('%s %s winner — %s', upper(v_fixture.cup_code), v_stage, public.competition_cup_fixture_label(v_fixture)),
      jsonb_build_object('cup_code', v_fixture.cup_code, 'stage', v_stage)
    );
    INSERT INTO public.competition_cup_prize_paid (fixture_id, club_short_name, stage, amount)
    VALUES (p_fixture_id, v_winner, v_stage, v_amount);
  END IF;

  IF v_fixture.cup_round = v_max_round THEN
    SELECT amount INTO v_amount
    FROM public.competition_cup_prize_config
    WHERE season_id = v_fixture.season_id
      AND cup_code = v_fixture.cup_code
      AND stage = 'winner';

    IF v_amount IS NOT NULL AND v_amount > 0
       AND NOT EXISTS (
         SELECT 1 FROM public.competition_cup_prize_paid
         WHERE fixture_id = p_fixture_id
           AND club_short_name = v_winner
           AND stage = 'winner'
       ) THEN
      PERFORM public.competition_credit_club_balance(v_winner, v_amount);
      INSERT INTO public.competition_finance_ledger (
        season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
      )
      VALUES (
        v_fixture.season_id,
        p_fixture_id,
        v_winner,
        'prize',
        v_amount,
        format('%s champion — %s', upper(v_fixture.cup_code), public.competition_cup_fixture_label(v_fixture)),
        jsonb_build_object('cup_code', v_fixture.cup_code, 'stage', 'winner')
      );
      INSERT INTO public.competition_cup_prize_paid (fixture_id, club_short_name, stage, amount)
      VALUES (p_fixture_id, v_winner, 'winner', v_amount);
    END IF;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_cup_on_fixture_played(p_fixture_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_node public.competition_cup_bracket_nodes;
  v_winner text;
BEGIN
  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = p_fixture_id;
  IF NOT FOUND OR v_fixture.competition_type <> 'cup' THEN
    RETURN;
  END IF;

  IF v_fixture.home_goals = v_fixture.away_goals THEN
    RETURN;
  END IF;

  IF v_fixture.home_goals > v_fixture.away_goals THEN
    v_winner := v_fixture.home_club_short_name;
  ELSE
    v_winner := v_fixture.away_club_short_name;
  END IF;

  SELECT * INTO v_node
  FROM public.competition_cup_bracket_nodes
  WHERE fixture_id = p_fixture_id;

  IF FOUND THEN
    UPDATE public.competition_cup_bracket_nodes
    SET winner_club_short_name = v_winner
    WHERE id = v_node.id;
    PERFORM public.competition_cup_advance_node_winner(v_node.id);
  END IF;

  PERFORM public.competition_pay_cup_fixture_prizes(p_fixture_id);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Admin draws
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_shuffle_club_array(p_clubs text[])
RETURNS text[]
LANGUAGE plpgsql
IMMUTABLE
AS $function$
DECLARE
  v_result text[] := p_clubs;
  v_i int;
  v_j int;
  v_tmp text;
BEGIN
  IF v_result IS NULL THEN
    RETURN v_result;
  END IF;

  FOR v_i IN REVERSE array_length(v_result, 1)..2 LOOP
    v_j := 1 + floor(random() * v_i)::int;
    v_tmp := v_result[v_i];
    v_result[v_i] := v_result[v_j];
    v_result[v_j] := v_tmp;
  END LOOP;

  RETURN v_result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_draw_prestige_cup(
  p_season_id bigint,
  p_cup_code text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_clubs text[];
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_cup_code NOT IN ('super8', 'plate', 'shield', 'spoon') THEN
    RAISE EXCEPTION 'Invalid prestige cup code';
  END IF;

  v_clubs := public.competition_qualify_cup_clubs(p_season_id, p_cup_code);

  IF coalesce(array_length(v_clubs, 1), 0) < 2 THEN
    RAISE EXCEPTION 'Not enough qualified clubs for % (% found)', p_cup_code, coalesce(array_length(v_clubs, 1), 0);
  END IF;

  v_clubs := public.competition_shuffle_club_array(v_clubs);

  RETURN public.competition_build_knockout_bracket(p_season_id, p_cup_code, v_clubs);
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_draw_league_cup(
  p_season_id bigint,
  p_byes smallint DEFAULT 4
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_clubs text[];
  v_byes int := greatest(coalesce(p_byes, 4), 0);
  v_n int;
  v_target int := 1;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  v_clubs := public.competition_qualify_cup_clubs(p_season_id, 'league_cup');

  IF coalesce(array_length(v_clubs, 1), 0) < 8 THEN
    RAISE EXCEPTION 'Need at least 8 clubs in season for league cup';
  END IF;

  v_n := array_length(v_clubs, 1);
  WHILE v_target < v_n LOOP
    v_target := v_target * 2;
  END LOOP;

  IF v_byes <> v_target - v_n THEN
    RAISE EXCEPTION 'League cup needs exactly % byes for % clubs (got p_byes=%)', v_target - v_n, v_n, p_byes;
  END IF;

  v_clubs := public.competition_shuffle_club_array(v_clubs);

  RETURN public.competition_build_knockout_bracket(p_season_id, 'league_cup', v_clubs);
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_set_cup_prize(
  p_season_id bigint,
  p_cup_code text,
  p_stage text,
  p_amount numeric
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  INSERT INTO public.competition_cup_prize_config (season_id, cup_code, stage, amount)
  VALUES (p_season_id, p_cup_code, p_stage, coalesce(p_amount, 0))
  ON CONFLICT (season_id, cup_code, stage)
  DO UPDATE SET amount = excluded.amount;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_set_playoff_qualifier(
  p_season_id bigint,
  p_cup_code text,
  p_division text,
  p_club_short_name text,
  p_role text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  INSERT INTO public.competition_cup_manual_qualifiers (
    season_id, cup_code, division, club_short_name, qualifier_role
  )
  VALUES (p_season_id, p_cup_code, p_division, upper(trim(p_club_short_name)), p_role)
  ON CONFLICT (season_id, cup_code, division, qualifier_role)
  DO UPDATE SET club_short_name = excluded.club_short_name;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_delete_cup_bracket(
  p_season_id bigint,
  p_cup_code text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  DELETE FROM public.competition_fixtures
  WHERE season_id = p_season_id
    AND competition_type = 'cup'
    AND cup_code = p_cup_code;

  DELETE FROM public.competition_cup_bracket_nodes
  WHERE season_id = p_season_id AND cup_code = p_cup_code;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Submit: no draws in cup; confirm: bracket + prizes
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_submit_result(
  p_fixture_id bigint,
  p_home_goals smallint,
  p_away_goals smallint,
  p_player_stats jsonb DEFAULT '[]'::jsonb
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_fixture public.competition_fixtures;
  v_opponent text;
  v_submission_id bigint;
  v_home_name text;
  v_away_name text;
  v_title text;
  v_body text;
  v_label text;
BEGIN
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  IF p_home_goals IS NULL OR p_away_goals IS NULL OR p_home_goals < 0 OR p_away_goals < 0 THEN
    RAISE EXCEPTION 'Invalid score';
  END IF;

  IF p_player_stats IS NOT NULL AND jsonb_typeof(p_player_stats) <> 'array' THEN
    RAISE EXCEPTION 'player_stats must be a JSON array';
  END IF;

  SELECT f.* INTO v_fixture
  FROM public.competition_fixtures f
  JOIN public.competition_seasons s ON s.id = f.season_id
  WHERE f.id = p_fixture_id
    AND s.is_current = true
    AND s.status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found on current season';
  END IF;

  IF v_fixture.competition_type = 'cup' AND p_home_goals = p_away_goals THEN
    RAISE EXCEPTION 'Cup matches cannot end in a draw — pick a winner';
  END IF;

  IF v_fixture.status <> 'scheduled' THEN
    RAISE EXCEPTION 'Fixture is not open for result entry';
  END IF;

  IF v_club NOT IN (v_fixture.home_club_short_name, v_fixture.away_club_short_name) THEN
    RAISE EXCEPTION 'Your club is not in this fixture';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.competition_result_submissions s
    WHERE s.fixture_id = p_fixture_id AND s.status = 'pending'
  ) THEN
    RAISE EXCEPTION 'A result is already awaiting confirmation for this fixture';
  END IF;

  v_opponent := public.competition_fixture_opponent(p_fixture_id, v_club);

  INSERT INTO public.competition_result_submissions (
    fixture_id, submitted_by_club, home_goals, away_goals, status, player_stats
  )
  VALUES (
    p_fixture_id, v_club, p_home_goals, p_away_goals, 'pending',
    coalesce(p_player_stats, '[]'::jsonb)
  )
  RETURNING id INTO v_submission_id;

  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  v_label := CASE
    WHEN v_fixture.competition_type = 'cup' THEN public.competition_cup_fixture_label(v_fixture)
    ELSE format('Matchday %s', v_fixture.matchday)
  END;

  v_title := format('Confirm result: %s vs %s', v_home_name, v_away_name);
  v_body := format(
    '%s — %s submitted %s %s–%s %s. Confirm or reject.',
    v_label,
    v_club,
    v_home_name,
    p_home_goals,
    p_away_goals,
    v_away_name
  );

  PERFORM public.competition_inbox_notify(
    v_opponent, 'result_to_confirm', p_fixture_id, v_submission_id, v_title, v_body
  );

  RETURN v_submission_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_confirm_result(p_submission_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
  v_opponent text;
  v_home_name text;
  v_away_name text;
  v_label text;
BEGIN
  IF v_club IS NULL THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  v_opponent := public.competition_fixture_opponent(v_sub.fixture_id, v_club);
  IF v_opponent <> v_sub.submitted_by_club THEN
    RAISE EXCEPTION 'Only the opponent can confirm this result';
  END IF;

  IF v_fixture.competition_type = 'cup' AND v_sub.home_goals = v_sub.away_goals THEN
    RAISE EXCEPTION 'Cup matches cannot end in a draw';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = v_sub.home_goals,
      away_goals = v_sub.away_goals,
      status = 'played'
  WHERE id = v_sub.fixture_id;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);
  PERFORM public.competition_settle_fixture_gates(v_sub.fixture_id);
  PERFORM public.competition_cup_on_fixture_played(v_sub.fixture_id);

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = v_club,
      responded_at = now()
  WHERE id = p_submission_id;

  UPDATE public.competition_inbox
  SET read_at = coalesce(read_at, now())
  WHERE submission_id = p_submission_id
    AND recipient_club_short_name = v_club
    AND message_type = 'result_to_confirm';

  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  v_label := CASE
    WHEN v_fixture.competition_type = 'cup' THEN public.competition_cup_fixture_label(v_fixture)
    ELSE format('Matchday %s', v_fixture.matchday)
  END;

  PERFORM public.competition_inbox_notify(
    v_sub.submitted_by_club,
    'result_confirmed',
    v_sub.fixture_id,
    p_submission_id,
    format('Result confirmed: %s vs %s', v_home_name, v_away_name),
    format(
      '%s — %s–%s confirmed. Table/stats/gates/cup bracket updated.',
      v_label,
      v_sub.home_goals,
      v_sub.away_goals
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_confirm_submission(p_submission_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_sub public.competition_result_submissions;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = v_sub.home_goals,
      away_goals = v_sub.away_goals,
      status = 'played'
  WHERE id = v_sub.fixture_id;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);
  PERFORM public.competition_settle_fixture_gates(v_sub.fixture_id);
  PERFORM public.competition_cup_on_fixture_played(v_sub.fixture_id);

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = 'ADMIN',
      responded_at = now()
  WHERE id = p_submission_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public views (DROP required when column list changes — CREATE OR REPLACE fails)
-- ---------------------------------------------------------------------------

DROP VIEW IF EXISTS public.competition_cup_qualified_public;
DROP VIEW IF EXISTS public.competition_cup_bracket_public;
DROP VIEW IF EXISTS public.competition_fixtures_public;

CREATE VIEW public.competition_fixtures_public
WITH (security_invoker = false)
AS
SELECT
  f.id,
  f.season_id,
  f.division,
  f.competition_type,
  f.cup_code,
  f.cup_round,
  f.cup_match,
  f.matchday,
  f.gpsl_month,
  f.week_in_month,
  f.home_club_short_name,
  hc."Club" AS home_club_name,
  f.away_club_short_name,
  ac."Club" AS away_club_name,
  f.weather,
  f.home_goals,
  f.away_goals,
  f.status,
  sub.submission_id,
  sub.submission_status,
  sub.submitted_by_club,
  sub.proposed_home_goals,
  sub.proposed_away_goals
FROM public.competition_fixtures f
JOIN public.competition_seasons s ON s.id = f.season_id
JOIN public."Clubs" hc ON hc."ShortName" = f.home_club_short_name
JOIN public."Clubs" ac ON ac."ShortName" = f.away_club_short_name
LEFT JOIN LATERAL (
  SELECT
    rs.id AS submission_id,
    rs.status AS submission_status,
    rs.submitted_by_club,
    rs.home_goals AS proposed_home_goals,
    rs.away_goals AS proposed_away_goals
  FROM public.competition_result_submissions rs
  WHERE rs.fixture_id = f.id AND rs.status = 'pending'
  LIMIT 1
) sub ON true
WHERE s.status = 'active' AND s.is_current = true;

CREATE VIEW public.competition_cup_bracket_public
WITH (security_invoker = false)
AS
SELECT
  n.id,
  n.season_id,
  n.cup_code,
  n.round_no,
  n.match_no,
  n.home_club_short_name,
  hc."Club" AS home_club_name,
  n.away_club_short_name,
  ac."Club" AS away_club_name,
  n.winner_club_short_name,
  wc."Club" AS winner_club_name,
  n.fixture_id,
  f.status AS fixture_status,
  f.home_goals,
  f.away_goals,
  n.child_node_id,
  n.child_slot
FROM public.competition_cup_bracket_nodes n
JOIN public.competition_seasons s ON s.id = n.season_id
LEFT JOIN public."Clubs" hc ON hc."ShortName" = n.home_club_short_name
LEFT JOIN public."Clubs" ac ON ac."ShortName" = n.away_club_short_name
LEFT JOIN public."Clubs" wc ON wc."ShortName" = n.winner_club_short_name
LEFT JOIN public.competition_fixtures f ON f.id = n.fixture_id
WHERE s.status = 'active' AND s.is_current = true;

CREATE VIEW public.competition_cup_qualified_public
WITH (security_invoker = false)
AS
SELECT
  s.id AS season_id,
  cup.cup_code,
  q.club_short_name
FROM public.competition_seasons s
CROSS JOIN (
  VALUES ('super8'), ('plate'), ('shield'), ('spoon'), ('league_cup')
) AS cup(cup_code)
CROSS JOIN LATERAL unnest(public.competition_qualify_cup_clubs(s.id, cup.cup_code)) AS q(club_short_name)
WHERE s.is_current = true AND s.status = 'active';

GRANT SELECT ON public.competition_fixtures_public TO authenticated;
GRANT SELECT ON public.competition_fixtures_public TO anon;
GRANT SELECT ON public.competition_cup_bracket_public TO authenticated;
GRANT SELECT ON public.competition_cup_bracket_public TO anon;
GRANT SELECT ON public.competition_cup_qualified_public TO authenticated;
GRANT SELECT ON public.competition_cup_qualified_public TO anon;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_cup_bracket_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_cup_manual_qualifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_cup_prize_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_cup_prize_paid ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_cup_bracket_select ON public.competition_cup_bracket_nodes;
CREATE POLICY competition_cup_bracket_select ON public.competition_cup_bracket_nodes
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_cup_bracket_admin ON public.competition_cup_bracket_nodes;
CREATE POLICY competition_cup_bracket_admin ON public.competition_cup_bracket_nodes
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS competition_cup_manual_admin ON public.competition_cup_manual_qualifiers;
CREATE POLICY competition_cup_manual_admin ON public.competition_cup_manual_qualifiers
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS competition_cup_manual_select ON public.competition_cup_manual_qualifiers;
CREATE POLICY competition_cup_manual_select ON public.competition_cup_manual_qualifiers
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_cup_prize_config_select ON public.competition_cup_prize_config;
CREATE POLICY competition_cup_prize_config_select ON public.competition_cup_prize_config
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_cup_prize_config_admin ON public.competition_cup_prize_config;
CREATE POLICY competition_cup_prize_config_admin ON public.competition_cup_prize_config
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS competition_cup_prize_paid_select ON public.competition_cup_prize_paid;
CREATE POLICY competition_cup_prize_paid_select ON public.competition_cup_prize_paid
  FOR SELECT TO authenticated USING (true);

GRANT SELECT ON public.competition_cup_bracket_nodes TO authenticated;
GRANT SELECT ON public.competition_cup_manual_qualifiers TO authenticated;
GRANT SELECT ON public.competition_cup_prize_config TO authenticated;

GRANT EXECUTE ON FUNCTION public.competition_draw_league_cup(bigint, smallint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_draw_prestige_cup(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_delete_cup_bracket(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_set_cup_prize(bigint, text, text, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_set_playoff_qualifier(bigint, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_qualify_cup_clubs(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_estimate_gate_for_club(text, bigint, text) TO authenticated;

-- Cup gates: use home club's league division for table position (not division = 'cup')
CREATE OR REPLACE FUNCTION public.competition_settle_fixture_gates(p_fixture_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
  v_capacity int;
  v_pos int;
  v_hist numeric;
  v_breakdown jsonb;
  v_total numeric;
  v_home_share numeric;
  v_away_share numeric;
  v_desc text;
  v_home_club text;
  v_away_club text;
  v_division text;
BEGIN
  IF p_fixture_id IS NULL THEN
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.competition_finance_ledger
    WHERE fixture_id = p_fixture_id
      AND entry_type IN ('gate_league_home', 'gate_cup_share')
  ) THEN
    RETURN;
  END IF;

  SELECT * INTO v_fixture
  FROM public.competition_fixtures
  WHERE id = p_fixture_id
    AND status = 'played'
    AND home_goals IS NOT NULL
    AND away_goals IS NOT NULL;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  v_home_club := v_fixture.home_club_short_name;
  v_away_club := v_fixture.away_club_short_name;

  IF v_fixture.competition_type = 'cup' THEN
    SELECT ccs.division INTO v_division
    FROM public.competition_club_seasons ccs
    WHERE ccs.season_id = v_fixture.season_id
      AND ccs.club_short_name = v_home_club;
  ELSE
    v_division := v_fixture.division;
  END IF;

  v_division := coalesce(v_division, 'superleague');

  SELECT coalesce(c."Capacity", 0)::int INTO v_capacity
  FROM public."Clubs" c
  WHERE c."ShortName" = v_home_club;

  v_pos := public.competition_club_table_position(
    v_fixture.season_id,
    v_division,
    v_home_club
  );
  v_hist := public.competition_club_history_avg_position(v_home_club, 5);
  v_breakdown := public.competition_compute_gate_total(v_capacity, v_pos, v_hist);
  v_total := (v_breakdown ->> 'total_gate')::numeric;

  IF v_total IS NULL OR v_total <= 0 THEN
    RETURN;
  END IF;

  IF v_fixture.competition_type = 'league' THEN
    v_desc := format(
      'Gate MD%s — %s vs %s (home 100%%) · fill %s%%',
      v_fixture.matchday,
      v_home_club,
      v_away_club,
      round(((v_breakdown ->> 'attendance_rate')::numeric) * 100, 1)
    );

    PERFORM public.competition_credit_club_balance(v_home_club, v_total);

    INSERT INTO public.competition_finance_ledger (
      season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
    )
    VALUES (
      v_fixture.season_id,
      p_fixture_id,
      v_home_club,
      'gate_league_home',
      v_total,
      v_desc,
      v_breakdown
    );
  ELSIF v_fixture.competition_type = 'cup' THEN
    v_home_share := round(v_total / 2.0, 2);
    v_away_share := v_total - v_home_share;

    v_desc := format(
      '%s R%s — %s vs %s (50/50 gate)',
      upper(v_fixture.cup_code),
      v_fixture.cup_round,
      v_home_club,
      v_away_club
    );

    PERFORM public.competition_credit_club_balance(v_home_club, v_home_share);
    PERFORM public.competition_credit_club_balance(v_away_club, v_away_share);

    INSERT INTO public.competition_finance_ledger (
      season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
    )
    VALUES
      (
        v_fixture.season_id,
        p_fixture_id,
        v_home_club,
        'gate_cup_share',
        v_home_share,
        v_desc || ' (home)',
        v_breakdown || jsonb_build_object('split', 'home')
      ),
      (
        v_fixture.season_id,
        p_fixture_id,
        v_away_club,
        'gate_cup_share',
        v_away_share,
        v_desc || ' (away)',
        v_breakdown || jsonb_build_object('split', 'away')
      );
  END IF;
END;
$function$;
