-- =============================================================================
-- GPSL Competition — League prize money (config, EOS payout, standings display)
-- Run once in Supabase SQL Editor after competition_phase5_finances.sql
-- (and after stadium_expansion.sql / central_bank_phase1.sql if those extended ledger types).
-- Also re-patches result confirmation to auto-pay when a division's 38 league
-- matches are complete.
-- =============================================================================

-- Constants: 20 clubs per division, 38 league matches each (double round-robin).

-- ---------------------------------------------------------------------------
-- Ledger: prize_league entry type
-- ---------------------------------------------------------------------------

ALTER TABLE public.competition_finance_ledger
  DROP CONSTRAINT IF EXISTS competition_finance_ledger_entry_type_check;

ALTER TABLE public.competition_finance_ledger
  ADD CONSTRAINT competition_finance_ledger_entry_type_check
  CHECK (
    entry_type IN (
      'gate_league_home',
      'gate_cup_share',
      'prize',
      'prize_league',
      'adjustment',
      'admin_one_off_injection',
      'admin_purchase_payment',
      'transfer_sale',
      'transfer_purchase',
      'transfer_agent_fee',
      'transfer_foreign_sale',
      'transfer_overflow_release',
      'loan_drawdown',
      'loan_repayment_principal',
      'loan_interest_payment',
      'infra_maintenance',
      'infra_purchase',
      'infra_expansion',
      'infra_expansion_refund',
      'infra_expansion_penalty'
    )
  );

-- ---------------------------------------------------------------------------
-- Config + paid tracking
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.competition_league_prize_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  division text NOT NULL CHECK (
    division IN ('superleague', 'championship_a', 'championship_b')
  ),
  position smallint NOT NULL CHECK (position >= 1 AND position <= 20),
  amount numeric(14, 2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT competition_league_prize_config_unique UNIQUE (season_id, division, position)
);

CREATE TABLE IF NOT EXISTS public.competition_league_prize_paid (
  season_id bigint NOT NULL REFERENCES public.competition_seasons (id) ON DELETE CASCADE,
  division text NOT NULL CHECK (
    division IN ('superleague', 'championship_a', 'championship_b')
  ),
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  table_position smallint NOT NULL CHECK (table_position >= 1 AND table_position <= 20),
  amount numeric(14, 2) NOT NULL CHECK (amount > 0),
  paid_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (season_id, division, club_short_name)
);

CREATE INDEX IF NOT EXISTS competition_league_prize_config_season_idx
  ON public.competition_league_prize_config (season_id, division);

-- ---------------------------------------------------------------------------
-- Public views
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.competition_league_prize_config_public
WITH (security_invoker = false)
AS
SELECT season_id, division, position, amount
FROM public.competition_league_prize_config;

CREATE OR REPLACE VIEW public.competition_standings_prizes_public
WITH (security_invoker = false)
AS
SELECT
  s.season_id,
  s.division,
  s.club_short_name,
  s.club_name,
  s.table_position,
  s.mp,
  s.w,
  s.d,
  s.l,
  s.gf,
  s.ga,
  s.gd,
  s.pts,
  s.form_last10,
  coalesce(pc.amount, 0)::numeric(14, 2) AS league_prize_amount,
  (pp.club_short_name IS NOT NULL) AS league_prize_paid
FROM public.competition_standings_public s
LEFT JOIN public.competition_league_prize_config pc
  ON pc.season_id = s.season_id
 AND pc.division = s.division
 AND pc.position = s.table_position
LEFT JOIN public.competition_league_prize_paid pp
  ON pp.season_id = s.season_id
 AND pp.division = s.division
 AND pp.club_short_name = s.club_short_name;

GRANT SELECT ON public.competition_league_prize_config_public TO authenticated;
GRANT SELECT ON public.competition_league_prize_config_public TO anon;
GRANT SELECT ON public.competition_standings_prizes_public TO authenticated;
GRANT SELECT ON public.competition_standings_prizes_public TO anon;

ALTER TABLE public.competition_league_prize_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competition_league_prize_paid ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competition_league_prize_config_select ON public.competition_league_prize_config;
CREATE POLICY competition_league_prize_config_select ON public.competition_league_prize_config
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS competition_league_prize_paid_select ON public.competition_league_prize_paid;
CREATE POLICY competition_league_prize_paid_select ON public.competition_league_prize_paid
  FOR SELECT TO authenticated USING (true);

-- ---------------------------------------------------------------------------
-- Division complete? (all league fixtures played, every club on 38 MP)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_division_league_complete(
  p_season_id bigint,
  p_division text
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_unplayed int;
  v_clubs_incomplete int;
BEGIN
  IF p_season_id IS NULL OR p_division IS NULL OR p_division = '' THEN
    RETURN false;
  END IF;

  SELECT count(*)::int INTO v_unplayed
  FROM public.competition_fixtures f
  WHERE f.season_id = p_season_id
    AND f.division = p_division
    AND f.competition_type = 'league'
    AND f.status <> 'played';

  IF v_unplayed > 0 THEN
    RETURN false;
  END IF;

  SELECT count(*)::int INTO v_clubs_incomplete
  FROM public.competition_standings_public s
  WHERE s.season_id = p_season_id
    AND s.division = p_division
    AND s.mp < 38;

  RETURN v_clubs_incomplete = 0;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Pay league prizes for one division (idempotent)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_pay_league_division_prizes(
  p_season_id bigint,
  p_division text
)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_row record;
  v_amount numeric;
  v_paid int := 0;
  v_div_label text;
BEGIN
  IF p_season_id IS NULL OR p_division IS NULL THEN
    RETURN 0;
  END IF;

  IF NOT public.competition_division_league_complete(p_season_id, p_division) THEN
    RETURN 0;
  END IF;

  v_div_label := CASE p_division
    WHEN 'superleague' THEN 'SuperLeague'
    WHEN 'championship_a' THEN 'Championship A'
    WHEN 'championship_b' THEN 'Championship B'
    ELSE p_division
  END;

  FOR v_row IN
    SELECT
      s.club_short_name,
      s.table_position,
      s.club_name
    FROM public.competition_standings_public s
    WHERE s.season_id = p_season_id
      AND s.division = p_division
    ORDER BY s.table_position
  LOOP
    IF EXISTS (
      SELECT 1 FROM public.competition_league_prize_paid pp
      WHERE pp.season_id = p_season_id
        AND pp.division = p_division
        AND pp.club_short_name = v_row.club_short_name
    ) THEN
      CONTINUE;
    END IF;

    SELECT pc.amount INTO v_amount
    FROM public.competition_league_prize_config pc
    WHERE pc.season_id = p_season_id
      AND pc.division = p_division
      AND pc.position = v_row.table_position;

    IF v_amount IS NULL OR v_amount <= 0 THEN
      CONTINUE;
    END IF;

    PERFORM public.competition_credit_club_balance(v_row.club_short_name, v_amount);

    INSERT INTO public.competition_finance_ledger (
      season_id, fixture_id, club_short_name, entry_type, amount, description, metadata
    )
    VALUES (
      p_season_id,
      NULL,
      v_row.club_short_name,
      'prize_league',
      v_amount,
      format('%s league prize — position %s', v_div_label, v_row.table_position),
      jsonb_build_object(
        'division', p_division,
        'table_position', v_row.table_position,
        'club_name', v_row.club_name
      )
    );

    INSERT INTO public.competition_league_prize_paid (
      season_id, division, club_short_name, table_position, amount
    )
    VALUES (
      p_season_id, p_division, v_row.club_short_name, v_row.table_position, v_amount
    );

    v_paid := v_paid + 1;
  END LOOP;

  RETURN v_paid;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_try_pay_league_division_prizes(
  p_season_id bigint,
  p_division text
)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  RETURN public.competition_pay_league_division_prizes(p_season_id, p_division);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Admin RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_admin_save_league_prizes(
  p_season_id bigint,
  p_division text,
  p_amounts jsonb
)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_key text;
  v_pos int;
  v_amount numeric;
  v_count int := 0;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    RAISE EXCEPTION 'season_id required';
  END IF;

  IF p_division IS NULL OR p_division NOT IN ('superleague', 'championship_a', 'championship_b') THEN
    RAISE EXCEPTION 'Invalid division';
  END IF;

  IF p_amounts IS NULL OR jsonb_typeof(p_amounts) <> 'object' THEN
    RAISE EXCEPTION 'amounts must be a JSON object keyed by position (1–20)';
  END IF;

  FOR v_key, v_amount IN
    SELECT key, (value #>> '{}')::numeric
    FROM jsonb_each(p_amounts)
  LOOP
    v_pos := v_key::int;
    IF v_pos < 1 OR v_pos > 20 THEN
      CONTINUE;
    END IF;
    IF v_amount IS NULL OR v_amount < 0 THEN
      v_amount := 0;
    END IF;

    INSERT INTO public.competition_league_prize_config (season_id, division, position, amount)
    VALUES (p_season_id, p_division, v_pos, v_amount)
    ON CONFLICT (season_id, division, position)
    DO UPDATE SET amount = EXCLUDED.amount, updated_at = now();

    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_seed_league_prize_defaults(
  p_season_id bigint
)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_div text;
  v_pos int;
  v_amount numeric;
  v_count int := 0;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    RAISE EXCEPTION 'season_id required';
  END IF;

  FOREACH v_div IN ARRAY ARRAY['superleague', 'championship_a', 'championship_b']
  LOOP
    FOR v_pos IN 1..20
    LOOP
      IF v_div = 'superleague' THEN
        v_amount := CASE
          WHEN v_pos = 1 THEN 30000000
          WHEN v_pos = 2 THEN 25000000
          WHEN v_pos = 3 THEN 22000000
          WHEN v_pos = 4 THEN 20000000
          WHEN v_pos <= 8 THEN 15000000
          WHEN v_pos <= 16 THEN 10000000
          ELSE 5000000
        END;
      ELSE
        v_amount := CASE
          WHEN v_pos = 1 THEN 15000000
          WHEN v_pos = 2 THEN 12000000
          WHEN v_pos = 3 THEN 10000000
          WHEN v_pos <= 6 THEN 8000000
          WHEN v_pos <= 14 THEN 5000000
          ELSE 3000000
        END;
      END IF;

      INSERT INTO public.competition_league_prize_config (season_id, division, position, amount)
      VALUES (p_season_id, v_div, v_pos, v_amount)
      ON CONFLICT (season_id, division, position) DO NOTHING;

      IF FOUND THEN
        v_count := v_count + 1;
      END IF;
    END LOOP;
  END LOOP;

  RETURN v_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_pay_league_prizes(
  p_season_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_season_id bigint;
  v_div text;
  v_paid int;
  v_total int := 0;
  v_result jsonb := '{}'::jsonb;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_season_id IS NULL THEN
    SELECT id INTO v_season_id
    FROM public.competition_seasons
    WHERE is_current = true
    ORDER BY id DESC
    LIMIT 1;
  ELSE
    v_season_id := p_season_id;
  END IF;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No season';
  END IF;

  FOREACH v_div IN ARRAY ARRAY['superleague', 'championship_a', 'championship_b']
  LOOP
    v_paid := public.competition_pay_league_division_prizes(v_season_id, v_div);
    v_result := v_result || jsonb_build_object(v_div, v_paid);
    v_total := v_total + v_paid;
  END LOOP;

  RETURN jsonb_build_object('season_id', v_season_id, 'clubs_paid', v_total, 'by_division', v_result);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Hook: owner confirm (with opponent stats — current production shape)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.competition_confirm_result(
  p_submission_id bigint,
  p_confirmer_player_stats jsonb DEFAULT '[]'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text := public.my_club_shortname();
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
  v_opponent text;
  v_home_name text;
  v_away_name text;
  v_label text;
  v_home_total smallint;
  v_away_total smallint;
  v_body text;
  v_pen_winner_name text;
  v_confirmer_expected int;
BEGIN
  IF v_club IS NULL THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  IF p_confirmer_player_stats IS NULL OR jsonb_typeof(p_confirmer_player_stats) <> 'array' THEN
    RAISE EXCEPTION 'player_stats must be a JSON array';
  END IF;

  IF jsonb_array_length(p_confirmer_player_stats) = 0 THEN
    RAISE EXCEPTION 'Enter your squad match stats (11 starters) before confirming';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  v_opponent := public.competition_fixture_opponent(v_sub.fixture_id, v_club);
  IF v_opponent <> v_sub.submitted_by_club THEN
    RAISE EXCEPTION 'Only the opponent can confirm this result';
  END IF;

  v_confirmer_expected := public.competition_expected_goals_for_club(v_fixture, v_sub, v_club);

  IF v_fixture.competition_type = 'cup' THEN
    SELECT t.home_total, t.away_total
    INTO v_home_total, v_away_total
    FROM public.competition_cup_open_play_totals(
      v_sub.home_goals, v_sub.away_goals, v_sub.et_home_goals, v_sub.et_away_goals
    ) t;

    IF public.competition_cup_winner_from_submission(
      v_sub.home_goals, v_sub.away_goals, v_sub.et_home_goals, v_sub.et_away_goals,
      v_sub.pen_winner_club_short_name,
      v_fixture.home_club_short_name, v_fixture.away_club_short_name
    ) IS NULL THEN
      RAISE EXCEPTION 'Invalid cup submission — extra time or penalties required';
    END IF;

    UPDATE public.competition_fixtures
    SET home_goals = v_home_total,
        away_goals = v_away_total,
        cup_pen_winner_club_short_name = v_sub.pen_winner_club_short_name,
        status = 'played'
    WHERE id = v_sub.fixture_id;
  ELSE
    v_home_total := v_sub.home_goals;
    v_away_total := v_sub.away_goals;

    UPDATE public.competition_fixtures
    SET home_goals = v_sub.home_goals,
        away_goals = v_sub.away_goals,
        cup_pen_winner_club_short_name = NULL,
        status = 'played'
    WHERE id = v_sub.fixture_id;
  END IF;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);

  PERFORM public.competition_apply_club_player_stats(
    v_fixture.id,
    v_fixture.season_id,
    v_club,
    p_confirmer_player_stats,
    v_confirmer_expected
  );

  PERFORM public.competition_settle_fixture_gates(v_sub.fixture_id);

  IF v_fixture.competition_type = 'cup' THEN
    PERFORM public.competition_cup_on_fixture_played(v_sub.fixture_id);
  ELSIF v_fixture.competition_type = 'league' THEN
    PERFORM public.competition_try_pay_league_division_prizes(v_fixture.season_id, v_fixture.division);
  END IF;

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = v_club,
      responded_at = now()
  WHERE id = p_submission_id;

  UPDATE public.competition_inbox
  SET read_at = coalesce(read_at, now())
  WHERE submission_id = p_submission_id
    AND recipient_club_short_name = v_club
    AND message_type = 'result_to_confirm';

  SELECT "Club" INTO v_home_name FROM public."Clubs" WHERE "ShortName" = v_fixture.home_club_short_name;
  SELECT "Club" INTO v_away_name FROM public."Clubs" WHERE "ShortName" = v_fixture.away_club_short_name;

  v_label := CASE
    WHEN v_fixture.competition_type = 'cup' THEN public.competition_cup_fixture_label(v_fixture)
    ELSE format('Matchday %s', v_fixture.matchday)
  END;

  IF v_sub.et_home_goals IS NOT NULL THEN
    v_body := format(
      '%s — %s–%s confirmed (90 min %s–%s, after ET %s–%s).',
      v_label, v_home_total, v_away_total,
      v_sub.home_goals, v_sub.away_goals, v_sub.et_home_goals, v_sub.et_away_goals
    );
  ELSE
    v_body := format(
      '%s — %s–%s confirmed (90 min %s–%s).',
      v_label, v_home_total, v_away_total, v_sub.home_goals, v_sub.away_goals
    );
  END IF;

  IF v_sub.pen_winner_club_short_name IS NOT NULL THEN
    SELECT "Club" INTO v_pen_winner_name FROM public."Clubs" WHERE "ShortName" = v_sub.pen_winner_club_short_name;
    v_body := v_body || format(' Pens: %s won.', coalesce(v_pen_winner_name, v_sub.pen_winner_club_short_name));
  END IF;

  PERFORM public.competition_inbox_notify(
    v_sub.submitted_by_club,
    'result_confirmed',
    v_sub.fixture_id,
    p_submission_id,
    format('Result confirmed: %s vs %s', v_home_name, v_away_name),
    v_body
  );
END;
$function$;

-- Admin confirm + direct record (league prize hook)
CREATE OR REPLACE FUNCTION public.competition_admin_confirm_submission(p_submission_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_sub public.competition_result_submissions;
  v_fixture public.competition_fixtures;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_sub
  FROM public.competition_result_submissions
  WHERE id = p_submission_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending submission not found';
  END IF;

  SELECT * INTO v_fixture FROM public.competition_fixtures WHERE id = v_sub.fixture_id;

  UPDATE public.competition_fixtures
  SET home_goals = v_sub.home_goals,
      away_goals = v_sub.away_goals,
      status = 'played'
  WHERE id = v_sub.fixture_id;

  PERFORM public.competition_apply_submission_player_stats(p_submission_id);
  PERFORM public.competition_settle_fixture_gates(v_sub.fixture_id);

  IF v_fixture.competition_type = 'cup' THEN
    PERFORM public.competition_cup_on_fixture_played(v_sub.fixture_id);
  ELSIF v_fixture.competition_type = 'league' THEN
    PERFORM public.competition_try_pay_league_division_prizes(v_fixture.season_id, v_fixture.division);
  END IF;

  UPDATE public.competition_result_submissions
  SET status = 'confirmed',
      responded_by_club = 'ADMIN',
      responded_at = now()
  WHERE id = p_submission_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.competition_admin_record_result(
  p_fixture_id bigint,
  p_home_goals smallint,
  p_away_goals smallint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_fixture public.competition_fixtures;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_home_goals IS NULL OR p_away_goals IS NULL OR p_home_goals < 0 OR p_away_goals < 0 THEN
    RAISE EXCEPTION 'Invalid score';
  END IF;

  SELECT * INTO v_fixture
  FROM public.competition_fixtures
  WHERE id = p_fixture_id
    AND competition_type IN ('league', 'cup');

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fixture not found';
  END IF;

  UPDATE public.competition_fixtures
  SET home_goals = p_home_goals,
      away_goals = p_away_goals,
      status = 'played'
  WHERE id = p_fixture_id;

  PERFORM public.competition_settle_fixture_gates(p_fixture_id);

  IF v_fixture.competition_type = 'cup' THEN
    PERFORM public.competition_cup_on_fixture_played(p_fixture_id);
  ELSIF v_fixture.competition_type = 'league' THEN
    PERFORM public.competition_try_pay_league_division_prizes(v_fixture.season_id, v_fixture.division);
  END IF;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.competition_division_league_complete(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_save_league_prizes(bigint, text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_seed_league_prize_defaults(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.competition_admin_pay_league_prizes(bigint) TO authenticated;
