-- =============================================================================
-- Special auctions: lowest unique bid + snap auction
-- Run once in Supabase SQL Editor.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.special_auctions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_type text NOT NULL CHECK (auction_type IN ('lowest_unique', 'snap')),
  title text NOT NULL,
  status text NOT NULL DEFAULT 'draft' CHECK (
    status IN ('draft', 'active', 'revealed', 'settled', 'cancelled')
  ),
  start_time timestamptz NOT NULL,
  end_time timestamptz NOT NULL,
  prize_type text NOT NULL CHECK (prize_type IN ('player', 'cash', 'discount')),
  prize_player_id text,
  prize_cash_amount numeric,
  prize_discount_label text,
  player_mode text CHECK (player_mode IN ('known', 'mystery')),
  mystery_clue text,
  known_player_id text,
  snap_loss_fee numeric NOT NULL DEFAULT 250000,
  snap_win_fee numeric NOT NULL DEFAULT 500000,
  winning_club_id text,
  winning_amount numeric,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.special_auction_bids (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_id bigint NOT NULL REFERENCES public.special_auctions (id) ON DELETE CASCADE,
  club_id text NOT NULL,
  owner_id uuid NOT NULL,
  bid_amount numeric NOT NULL CHECK (bid_amount > 0),
  bid_time timestamptz NOT NULL DEFAULT now(),
  is_winner boolean NOT NULL DEFAULT false,
  fee_charged numeric,
  UNIQUE (auction_id, club_id)
);

CREATE INDEX IF NOT EXISTS special_auction_bids_auction_id_idx
  ON public.special_auction_bids (auction_id);

CREATE UNIQUE INDEX IF NOT EXISTS special_auctions_one_active_idx
  ON public.special_auctions ((true))
  WHERE status = 'active';

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.is_gpsl_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(auth.jwt() ->> 'email', '') = 'rotavator66@outlook.com';
$$;

CREATE OR REPLACE FUNCTION public.my_club_shortname()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT "ShortName"
  FROM public."Clubs"
  WHERE owner_id = auth.uid()
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.round_bid_to_million(p_amount numeric)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT round(p_amount / 1000000.0) * 1000000;
$$;

CREATE OR REPLACE FUNCTION public.special_auction_can_view_bid(
  p_auction_id bigint,
  p_club_id text
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.special_auctions a
    WHERE a.id = p_auction_id
      AND (
        public.is_gpsl_admin()
        OR a.status IN ('revealed', 'settled')
        OR (a.auction_type = 'snap' AND a.status = 'active')
        OR (
          p_club_id IS NOT NULL
          AND p_club_id = public.my_club_shortname()
        )
      )
  );
$$;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.special_auctions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.special_auction_bids ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS special_auctions_select ON public.special_auctions;
CREATE POLICY special_auctions_select ON public.special_auctions
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS special_auctions_admin_write ON public.special_auctions;
CREATE POLICY special_auctions_admin_write ON public.special_auctions
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

DROP POLICY IF EXISTS special_auction_bids_select ON public.special_auction_bids;
CREATE POLICY special_auction_bids_select ON public.special_auction_bids
  FOR SELECT TO authenticated
  USING (
    public.special_auction_can_view_bid(auction_id, club_id)
  );

DROP POLICY IF EXISTS special_auction_bids_insert_own ON public.special_auction_bids;
CREATE POLICY special_auction_bids_insert_own ON public.special_auction_bids
  FOR INSERT TO authenticated
  WITH CHECK (
    club_id = public.my_club_shortname()
    AND owner_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.special_auctions a
      WHERE a.id = auction_id
        AND a.status = 'active'
        AND now() >= a.start_time
        AND now() < a.end_time
    )
  );

DROP POLICY IF EXISTS special_auction_bids_admin ON public.special_auction_bids;
CREATE POLICY special_auction_bids_admin ON public.special_auction_bids
  FOR ALL TO authenticated
  USING (public.is_gpsl_admin())
  WITH CHECK (public.is_gpsl_admin());

GRANT SELECT ON public.special_auctions TO authenticated;
GRANT SELECT, INSERT ON public.special_auction_bids TO authenticated;
GRANT ALL ON public.special_auctions TO authenticated;
GRANT ALL ON public.special_auction_bids TO authenticated;

-- ---------------------------------------------------------------------------
-- Submit bid (owners) — one bid per club; LUB rounds to nearest 1M
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.special_auction_submit_bid(
  p_auction_id bigint,
  p_amount numeric
)
RETURNS public.special_auction_bids
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_auction public.special_auctions%rowtype;
  v_club text;
  v_amount numeric;
  v_row public.special_auction_bids%rowtype;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR btrim(v_club) = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_auction
  FROM public.special_auctions
  WHERE id = p_auction_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Auction not found';
  END IF;

  IF v_auction.status <> 'active' THEN
    RAISE EXCEPTION 'Auction is not active';
  END IF;

  IF now() < v_auction.start_time OR now() >= v_auction.end_time THEN
    RAISE EXCEPTION 'Auction is not open for bidding';
  END IF;

  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'Bid must be a positive amount';
  END IF;

  IF v_auction.auction_type = 'lowest_unique' THEN
    v_amount := public.round_bid_to_million(p_amount);
    IF v_amount < 1000000 THEN
      RAISE EXCEPTION 'Lowest unique bids must be at least ₿1,000,000';
    END IF;
  ELSE
    v_amount := round(p_amount);
    IF v_amount < 1000000 THEN
      RAISE EXCEPTION 'Snap bids must be at least ₿1,000,000';
    END IF;
  END IF;

  INSERT INTO public.special_auction_bids (
    auction_id, club_id, owner_id, bid_amount
  )
  VALUES (
    p_auction_id, v_club, auth.uid(), v_amount
  )
  ON CONFLICT (auction_id, club_id) DO UPDATE
  SET bid_amount = EXCLUDED.bid_amount,
      bid_time = now()
  WHERE public.special_auction_bids.auction_id = p_auction_id
    AND public.special_auction_bids.club_id = v_club
    AND v_auction.auction_type = 'snap';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'You already submitted a bid for this auction';
  END IF;

  SELECT * INTO v_row
  FROM public.special_auction_bids
  WHERE auction_id = p_auction_id AND club_id = v_club;

  RETURN v_row;
END;
$function$;

-- Fix snap upsert: ON CONFLICT DO UPDATE only for snap; LUB should fail on duplicate
-- Re-write submit without upsert for LUB

DROP FUNCTION IF EXISTS public.special_auction_submit_bid(bigint, numeric);

CREATE OR REPLACE FUNCTION public.special_auction_submit_bid(
  p_auction_id bigint,
  p_amount numeric
)
RETURNS public.special_auction_bids
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_auction public.special_auctions%rowtype;
  v_club text;
  v_amount numeric;
  v_row public.special_auction_bids%rowtype;
  v_existing bigint;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR btrim(v_club) = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT * INTO v_auction FROM public.special_auctions WHERE id = p_auction_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Auction not found'; END IF;
  IF v_auction.status <> 'active' THEN RAISE EXCEPTION 'Auction is not active'; END IF;
  IF now() < v_auction.start_time OR now() >= v_auction.end_time THEN
    RAISE EXCEPTION 'Auction is not open for bidding';
  END IF;
  IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'Bid must be positive'; END IF;

  SELECT id INTO v_existing
  FROM public.special_auction_bids
  WHERE auction_id = p_auction_id AND club_id = v_club;

  IF v_auction.auction_type = 'lowest_unique' THEN
    IF v_existing IS NOT NULL THEN
      RAISE EXCEPTION 'You already submitted your secret bid';
    END IF;
    v_amount := public.round_bid_to_million(p_amount);
    IF v_amount < 1000000 THEN
      RAISE EXCEPTION 'Bid must be at least ₿1,000,000 (rounded to nearest million)';
    END IF;
  ELSE
    v_amount := round(p_amount);
    IF v_amount < 1000000 THEN RAISE EXCEPTION 'Bid must be at least ₿1,000,000'; END IF;
    IF v_existing IS NOT NULL THEN
      UPDATE public.special_auction_bids
      SET bid_amount = v_amount, bid_time = now()
      WHERE id = v_existing;
      SELECT * INTO v_row FROM public.special_auction_bids WHERE id = v_existing;
      RETURN v_row;
    END IF;
  END IF;

  INSERT INTO public.special_auction_bids (auction_id, club_id, owner_id, bid_amount)
  VALUES (p_auction_id, v_club, auth.uid(), v_amount)
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.special_auction_submit_bid(bigint, numeric) TO authenticated;

-- ---------------------------------------------------------------------------
-- Reveal (LUB) — show all bids, compute lowest unique, no finances yet
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.special_auction_reveal_lowest_unique(p_auction_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_auction public.special_auctions%rowtype;
  v_win_club text;
  v_win_amount numeric;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_auction FROM public.special_auctions WHERE id = p_auction_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Auction not found'; END IF;
  IF v_auction.auction_type <> 'lowest_unique' THEN
    RAISE EXCEPTION 'Not a lowest unique auction';
  END IF;

  SELECT b.club_id, b.bid_amount
  INTO v_win_club, v_win_amount
  FROM public.special_auction_bids b
  WHERE b.auction_id = p_auction_id
    AND (
      SELECT count(*) FROM public.special_auction_bids x
      WHERE x.auction_id = p_auction_id AND x.bid_amount = b.bid_amount
    ) = 1
  ORDER BY b.bid_amount ASC
  LIMIT 1;

  UPDATE public.special_auction_bids
  SET is_winner = false
  WHERE auction_id = p_auction_id;

  IF v_win_club IS NOT NULL THEN
    UPDATE public.special_auction_bids
    SET is_winner = true
    WHERE auction_id = p_auction_id AND club_id = v_win_club;
  END IF;

  UPDATE public.special_auctions
  SET status = 'revealed',
      winning_club_id = v_win_club,
      winning_amount = v_win_amount,
      updated_at = now()
  WHERE id = p_auction_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Settle — award prize + charge fees
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.special_auction_award_prize(
  p_auction public.special_auctions,
  p_winner_club text,
  p_win_amount numeric
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_player "Players"%rowtype;
BEGIN
  IF p_winner_club IS NULL THEN
    RETURN;
  END IF;

  IF p_auction.prize_type = 'player' AND p_auction.prize_player_id IS NOT NULL THEN
    SELECT * INTO v_player
    FROM public."Players"
    WHERE "Konami_ID"::text = p_auction.prize_player_id
    FOR UPDATE;

    IF FOUND THEN
      UPDATE public."Players"
      SET "Contracted_Team" = p_winner_club
      WHERE "Konami_ID"::text = p_auction.prize_player_id;
    END IF;
  ELSIF p_auction.prize_type = 'cash' AND coalesce(p_auction.prize_cash_amount, 0) > 0 THEN
    UPDATE public."Club_Finances"
    SET balance = balance + p_auction.prize_cash_amount
    WHERE club_name = p_winner_club;
  END IF;
  -- discount: label only (no automatic ledger)
END;
$function$;

CREATE OR REPLACE FUNCTION public.special_auction_settle(p_auction_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_auction public.special_auctions%rowtype;
  v_win_club text;
  v_win_amount numeric;
  v_bid record;
  v_fee numeric;
  v_balance numeric;
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT * INTO v_auction FROM public.special_auctions WHERE id = p_auction_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Auction not found'; END IF;

  IF v_auction.auction_type = 'lowest_unique' THEN
    IF v_auction.status = 'active' THEN
      PERFORM public.special_auction_reveal_lowest_unique(p_auction_id);
      SELECT * INTO v_auction FROM public.special_auctions WHERE id = p_auction_id;
    END IF;
    IF v_auction.status NOT IN ('revealed', 'settled') THEN
      RAISE EXCEPTION 'Reveal the lowest unique auction first';
    END IF;
    v_win_club := v_auction.winning_club_id;
    v_win_amount := v_auction.winning_amount;

    IF v_win_club IS NULL THEN
      UPDATE public.special_auctions SET status = 'settled', updated_at = now() WHERE id = p_auction_id;
      RETURN;
    END IF;

    SELECT balance INTO v_balance FROM public."Club_Finances" WHERE club_name = v_win_club FOR UPDATE;
    UPDATE public."Club_Finances"
    SET balance = coalesce(v_balance, 0) - v_win_amount
    WHERE club_name = v_win_club;

    UPDATE public.special_auction_bids
    SET fee_charged = v_win_amount
    WHERE auction_id = p_auction_id AND club_id = v_win_club;

    PERFORM public.special_auction_award_prize(v_auction, v_win_club, v_win_amount);

  ELSIF v_auction.auction_type = 'snap' THEN
    SELECT club_id, bid_amount
    INTO v_win_club, v_win_amount
    FROM public.special_auction_bids
    WHERE auction_id = p_auction_id
    ORDER BY bid_amount DESC, bid_time ASC
    LIMIT 1;

    UPDATE public.special_auction_bids SET is_winner = false WHERE auction_id = p_auction_id;
    IF v_win_club IS NOT NULL THEN
      UPDATE public.special_auction_bids SET is_winner = true
      WHERE auction_id = p_auction_id AND club_id = v_win_club;
    END IF;

    FOR v_bid IN
      SELECT club_id, bid_amount FROM public.special_auction_bids WHERE auction_id = p_auction_id
    LOOP
      IF v_bid.club_id = v_win_club THEN
        v_fee := coalesce(v_auction.snap_win_fee, 500000) + coalesce(v_win_amount, 0);
      ELSE
        v_fee := coalesce(v_auction.snap_loss_fee, 250000);
      END IF;

      SELECT balance INTO v_balance FROM public."Club_Finances" WHERE club_name = v_bid.club_id FOR UPDATE;
      IF v_balance IS NOT NULL THEN
        UPDATE public."Club_Finances" SET balance = v_balance - v_fee WHERE club_name = v_bid.club_id;
      END IF;

      UPDATE public.special_auction_bids SET fee_charged = v_fee
      WHERE auction_id = p_auction_id AND club_id = v_bid.club_id;
    END LOOP;

    UPDATE public.special_auctions
    SET winning_club_id = v_win_club,
        winning_amount = v_win_amount,
        status = 'settled',
        updated_at = now()
    WHERE id = p_auction_id;

    PERFORM public.special_auction_award_prize(v_auction, v_win_club, v_win_amount);
  END IF;

  IF v_auction.auction_type = 'lowest_unique' AND v_auction.status = 'revealed' THEN
    UPDATE public.special_auctions SET status = 'settled', updated_at = now() WHERE id = p_auction_id;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.special_auction_activate(p_auction_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN RAISE EXCEPTION 'Admin only'; END IF;

  UPDATE public.special_auctions SET status = 'draft', updated_at = now() WHERE status = 'active';

  UPDATE public.special_auctions
  SET status = 'active', updated_at = now()
  WHERE id = p_auction_id;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.special_auction_reveal_lowest_unique(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.special_auction_settle(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.special_auction_activate(bigint) TO authenticated;
