-- =============================================================================
-- Stadium capacity expansion — quotes, pre-build, 4-week delivery, ledger
-- Run once in Supabase SQL Editor (after central_bank_phase1, player_wage_settings).
-- Future: new-stadium builds (full GPSL season) — not in this migration.
-- =============================================================================

-- Original capacity (AR) — never reduced; live Capacity grows with expansions.
ALTER TABLE public."Clubs"
  ADD COLUMN IF NOT EXISTS base_capacity integer;

UPDATE public."Clubs"
SET base_capacity = coalesce("Capacity", 0)::int
WHERE base_capacity IS NULL;

ALTER TABLE public."Clubs"
  ALTER COLUMN base_capacity SET DEFAULT 0;

-- Admin tier costs (defaults match legacy spreadsheet formula).
ALTER TABLE public.global_settings
  ADD COLUMN IF NOT EXISTS stadium_cost_tier1 numeric(14, 2) NOT NULL DEFAULT 5000,
  ADD COLUMN IF NOT EXISTS stadium_cost_tier2 numeric(14, 2) NOT NULL DEFAULT 7500,
  ADD COLUMN IF NOT EXISTS stadium_cost_tier3 numeric(14, 2) NOT NULL DEFAULT 10000,
  ADD COLUMN IF NOT EXISTS stadium_capacity_tier_mid integer NOT NULL DEFAULT 30000,
  ADD COLUMN IF NOT EXISTS stadium_capacity_tier_high integer NOT NULL DEFAULT 50000,
  ADD COLUMN IF NOT EXISTS stadium_expansion_cancel_penalty numeric(14, 2) NOT NULL DEFAULT 1000000;

COMMENT ON COLUMN public.global_settings.stadium_cost_tier1 IS
  'Expansion cost per seat when current capacity < tier_mid.';
COMMENT ON COLUMN public.global_settings.stadium_cost_tier2 IS
  'Expansion cost per seat when tier_mid <= current capacity <= tier_high.';
COMMENT ON COLUMN public.global_settings.stadium_cost_tier3 IS
  'Expansion cost per seat when current capacity > tier_high.';

DROP VIEW IF EXISTS public.global_settings_public;

CREATE VIEW public.global_settings_public
WITH (security_invoker = false)
AS
SELECT
  id,
  transfer_window_open,
  draft_auction_enabled,
  draft_auction_start_time,
  updated_at,
  wage_pct_superleague,
  wage_pct_championship,
  stadium_cost_tier1,
  stadium_cost_tier2,
  stadium_cost_tier3,
  stadium_capacity_tier_mid,
  stadium_capacity_tier_high,
  stadium_expansion_cancel_penalty
FROM public.global_settings;

GRANT SELECT ON public.global_settings_public TO authenticated;
GRANT SELECT ON public.global_settings_public TO anon;

-- Ledger entry types for expansion payments / refunds / penalty
ALTER TABLE public.competition_finance_ledger
  DROP CONSTRAINT IF EXISTS competition_finance_ledger_entry_type_check;

ALTER TABLE public.competition_finance_ledger
  ADD CONSTRAINT competition_finance_ledger_entry_type_check
  CHECK (
    entry_type IN (
      'gate_league_home',
      'gate_cup_share',
      'prize',
      'adjustment',
      'admin_one_off_injection',
      'admin_purchase_payment',
      'transfer_sale',
      'transfer_purchase',
      'transfer_agent_fee',
      'transfer_foreign_sale',
      'transfer_overflow_release',
      'loan_drawdown',
      'loan_repayment_principal',
      'loan_interest_payment',
      'infra_maintenance',
      'infra_purchase',
      'infra_expansion',
      'infra_expansion_refund',
      'infra_expansion_penalty'
    )
  );

-- ---------------------------------------------------------------------------
-- Quotes & orders
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.stadium_expansion_quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  seats integer NOT NULL CHECK (seats > 0),
  capacity_at_quote integer NOT NULL CHECK (capacity_at_quote >= 0),
  cost_per_seat numeric(14, 2) NOT NULL CHECK (cost_per_seat > 0),
  total_cost numeric(14, 2) NOT NULL CHECK (total_cost > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  consumed_at timestamptz,
  consumed_order_id bigint
);

CREATE TABLE IF NOT EXISTS public.stadium_expansion_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_short_name text NOT NULL REFERENCES public."Clubs" ("ShortName"),
  season_id_ordered bigint NOT NULL REFERENCES public.competition_seasons (id),
  quote_id bigint REFERENCES public.stadium_expansion_quotes (id),
  seats_ordered integer NOT NULL CHECK (seats_ordered > 0),
  total_cost_paid numeric(14, 2) NOT NULL CHECK (total_cost_paid > 0),
  cost_per_seat numeric(14, 2) NOT NULL,
  capacity_at_order integer NOT NULL,
  base_capacity_at_order integer NOT NULL,
  max_capacity_at_order integer NOT NULL,
  status text NOT NULL DEFAULT 'pre_build' CHECK (
    status IN (
      'pre_build',
      'awaiting_goahead',
      'building',
      'completed',
      'cancelled'
    )
  ),
  seats_delivered integer NOT NULL DEFAULT 0 CHECK (seats_delivered >= 0),
  build_weeks_applied smallint NOT NULL DEFAULT 0 CHECK (build_weeks_applied >= 0 AND build_weeks_applied <= 4),
  ordered_at timestamptz NOT NULL DEFAULT now(),
  build_started_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  goahead_decision text CHECK (goahead_decision IN ('continue', 'cancel', 'auto_continue')),
  ledger_payment_id bigint,
  CONSTRAINT stadium_expansion_orders_delivered_le_seats
    CHECK (seats_delivered <= seats_ordered)
);

CREATE INDEX IF NOT EXISTS stadium_expansion_orders_club_idx
  ON public.stadium_expansion_orders (club_short_name, ordered_at DESC);

CREATE INDEX IF NOT EXISTS stadium_expansion_quotes_club_idx
  ON public.stadium_expansion_quotes (club_short_name, created_at DESC);

-- ---------------------------------------------------------------------------
-- Capacity cap (from original / base_capacity)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.stadium_max_capacity(p_base_capacity integer)
RETURNS integer
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN coalesce(p_base_capacity, 0) <= 15000 THEN 25000
    WHEN p_base_capacity <= 25000 THEN 30000
    WHEN p_base_capacity <= 35000 THEN 40000
    WHEN p_base_capacity <= 45000 THEN 50000
    WHEN p_base_capacity <= 50000 THEN 55000
    WHEN p_base_capacity <= 55000 THEN 60000
    ELSE p_base_capacity
  END;
$$;

CREATE OR REPLACE FUNCTION public.stadium_expansion_headroom(
  p_club_short_name text
)
RETURNS integer
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_base int;
  v_current int;
  v_max int;
  v_reserved int := 0;
BEGIN
  SELECT
    coalesce(c.base_capacity, c."Capacity", 0)::int,
    coalesce(c."Capacity", 0)::int
  INTO v_base, v_current
  FROM public."Clubs" c
  WHERE c."ShortName" = p_club_short_name;

  IF NOT FOUND THEN
    RETURN 0;
  END IF;

  v_max := public.stadium_max_capacity(v_base);

  SELECT coalesce(sum(greatest(o.seats_ordered - o.seats_delivered, 0)), 0)::int
  INTO v_reserved
  FROM public.stadium_expansion_orders o
  WHERE o.club_short_name = p_club_short_name
    AND o.status IN ('pre_build', 'awaiting_goahead', 'building');

  RETURN greatest(v_max - v_current - v_reserved, 0);
END;
$function$;

-- ---------------------------------------------------------------------------
-- Tiered cost per seat (current capacity × admin tier rates)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.stadium_expansion_cost_per_seat(p_current_capacity integer)
RETURNS numeric
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_current int := greatest(coalesce(p_current_capacity, 0), 0);
  v_t1 numeric;
  v_t2 numeric;
  v_t3 numeric;
  v_mid int;
  v_high int;
BEGIN
  SELECT
    stadium_cost_tier1,
    stadium_cost_tier2,
    stadium_cost_tier3,
    stadium_capacity_tier_mid,
    stadium_capacity_tier_high
  INTO v_t1, v_t2, v_t3, v_mid, v_high
  FROM public.global_settings
  WHERE id = 1;

  v_t1 := coalesce(v_t1, 5000);
  v_t2 := coalesce(v_t2, 7500);
  v_t3 := coalesce(v_t3, 10000);
  v_mid := coalesce(v_mid, 30000);
  v_high := coalesce(v_high, 50000);

  IF v_current < v_mid THEN
    RETURN v_t1;
  ELSIF v_current <= v_high THEN
    RETURN v_t2;
  END IF;

  RETURN v_t3;
END;
$function$;

-- Next Friday 19:00 UK strictly after p_ts (GPSL week boundary).
CREATE OR REPLACE FUNCTION public.stadium_next_friday_7pm_uk_after(p_ts timestamptz)
RETURNS timestamptz
LANGUAGE plpgsql
IMMUTABLE
AS $function$
DECLARE
  v_local timestamp;
  v_dow int;
  v_days int;
  v_candidate timestamp;
BEGIN
  v_local := p_ts AT TIME ZONE 'Europe/London';
  v_dow := extract(dow from v_local)::int; -- 0=Sun … 5=Fri

  v_days := (5 - v_dow + 7) % 7;
  v_candidate := date_trunc('day', v_local) + make_interval(days => v_days) + interval '19 hours';

  IF v_candidate <= v_local THEN
    v_candidate := v_candidate + interval '7 days';
  END IF;

  RETURN v_candidate AT TIME ZONE 'Europe/London';
END;
$function$;

CREATE OR REPLACE FUNCTION public.stadium_expansion_pre_build_day(p_ordered_at timestamptz)
RETURNS integer
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT greatest(
    1,
    (
      (now() AT TIME ZONE 'Europe/London')::date
      - (p_ordered_at AT TIME ZONE 'Europe/London')::date
      + 1
    )::integer
  );
$$;

CREATE OR REPLACE FUNCTION public.stadium_expansion_pre_build_message(p_day integer, p_seats integer)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE p_day
    WHEN 1 THEN format('%s seats ordered', p_seats)
    WHEN 2 THEN 'Rapid Build Co confirmed order'
    WHEN 3 THEN 'Rapid Build Co sourcing materials and workforce'
    WHEN 4 THEN 'Rapid Build Co deploying to site'
    WHEN 5 THEN 'Rapid Build Co preparing site'
    WHEN 6 THEN 'Rapid Build Co beginning work'
    ELSE 'Rapid Build Co — awaiting your decision'
  END;
$$;

CREATE OR REPLACE FUNCTION public.stadium_expansion_day7_deadline_uk(p_ordered_at timestamptz)
RETURNS timestamptz
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT (
    ((p_ordered_at AT TIME ZONE 'Europe/London')::date + 6)::timestamp
    + interval '19 hours'
  ) AT TIME ZONE 'Europe/London';
$$;

-- ---------------------------------------------------------------------------
-- Progress sync (call on stadium page load / after admin calendar tick)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.stadium_expansion_sync_progress(p_club_short_name text DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_row public.stadium_expansion_orders;
  v_day int;
  v_deadline timestamptz;
  v_weeks int;
  v_target int;
  v_add int;
  v_boundary timestamptz;
  v_ts timestamptz;
  i int;
BEGIN
  FOR v_row IN
    SELECT o.*
    FROM public.stadium_expansion_orders o
    WHERE o.status IN ('pre_build', 'awaiting_goahead', 'building')
      AND (p_club_short_name IS NULL OR o.club_short_name = p_club_short_name)
    FOR UPDATE OF o
  LOOP
    IF v_row.status IN ('pre_build', 'awaiting_goahead') THEN
      v_day := public.stadium_expansion_pre_build_day(v_row.ordered_at);
      v_deadline := public.stadium_expansion_day7_deadline_uk(v_row.ordered_at);

      IF v_day < 7 THEN
        UPDATE public.stadium_expansion_orders
        SET status = 'pre_build'
        WHERE id = v_row.id;
        CONTINUE;
      END IF;

      IF v_row.status = 'pre_build' AND now() < v_deadline THEN
        UPDATE public.stadium_expansion_orders
        SET status = 'awaiting_goahead'
        WHERE id = v_row.id;
        CONTINUE;
      END IF;

      IF v_row.status = 'awaiting_goahead' AND now() >= v_deadline AND v_row.goahead_decision IS NULL THEN
        UPDATE public.stadium_expansion_orders
        SET
          status = 'building',
          build_started_at = now(),
          goahead_decision = 'auto_continue'
        WHERE id = v_row.id;

        SELECT * INTO v_row FROM public.stadium_expansion_orders WHERE id = v_row.id;
      END IF;
    END IF;

    IF v_row.status = 'building' AND v_row.build_started_at IS NOT NULL THEN
      v_weeks := 0;
      v_ts := v_row.build_started_at;

      FOR i IN 1..4 LOOP
        v_boundary := public.stadium_next_friday_7pm_uk_after(v_ts);
        EXIT WHEN now() < v_boundary;
        v_weeks := i;
        v_ts := v_boundary;
      END LOOP;

      v_target := (v_row.seats_ordered * least(v_weeks, 4) / 4)::int;
      v_add := greatest(v_target - v_row.seats_delivered, 0);

      IF v_add > 0 THEN
        UPDATE public."Clubs"
        SET "Capacity" = coalesce("Capacity", 0) + v_add
        WHERE "ShortName" = v_row.club_short_name;

        UPDATE public.stadium_expansion_orders
        SET
          seats_delivered = v_target,
          build_weeks_applied = least(v_weeks, 4)::smallint
        WHERE id = v_row.id;
      END IF;

      IF v_weeks >= 4 OR v_target >= v_row.seats_ordered THEN
        UPDATE public.stadium_expansion_orders
        SET
          status = 'completed',
          completed_at = now(),
          seats_delivered = v_row.seats_ordered,
          build_weeks_applied = 4
        WHERE id = v_row.id
          AND status = 'building';
      END IF;
    END IF;
  END LOOP;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Owner RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.stadium_expansion_create_quote(p_seats integer)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_current int;
  v_base int;
  v_max int;
  v_headroom int;
  v_cps numeric;
  v_total numeric;
  v_quote_id bigint;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  IF p_seats IS NULL OR p_seats <= 0 THEN
    RAISE EXCEPTION 'Enter a positive number of seats';
  END IF;

  PERFORM public.stadium_expansion_sync_progress(v_club);

  SELECT coalesce(c."Capacity", 0)::int, coalesce(c.base_capacity, c."Capacity", 0)::int
  INTO v_current, v_base
  FROM public."Clubs" c
  WHERE c."ShortName" = v_club;

  v_max := public.stadium_max_capacity(v_base);
  v_headroom := public.stadium_expansion_headroom(v_club);

  IF v_headroom <= 0 THEN
    RAISE EXCEPTION 'Stadium is at maximum capacity — expansion not available';
  END IF;

  IF p_seats > v_headroom THEN
    RAISE EXCEPTION 'Maximum % seats can be added (cap %, current %)',
      v_headroom, v_max, v_current;
  END IF;

  v_cps := public.stadium_expansion_cost_per_seat(v_current);
  v_total := round(v_cps * p_seats, 0);

  INSERT INTO public.stadium_expansion_quotes (
    club_short_name, seats, capacity_at_quote, cost_per_seat, total_cost
  )
  VALUES (v_club, p_seats, v_current, v_cps, v_total)
  RETURNING id INTO v_quote_id;

  RETURN jsonb_build_object(
    'quote_id', v_quote_id,
    'seats', p_seats,
    'cost_per_seat', v_cps,
    'total_cost', v_total,
    'capacity_at_quote', v_current,
    'max_capacity', v_max,
    'headroom', v_headroom
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.stadium_expansion_place_order(p_quote_id bigint)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_season_id bigint;
  v_quote public.stadium_expansion_quotes;
  v_base int;
  v_current int;
  v_max int;
  v_balance numeric;
  v_order_id bigint;
  v_ledger_id bigint;
BEGIN
  v_club := public.my_club_shortname();
  IF v_club IS NULL OR v_club = '' THEN
    RAISE EXCEPTION 'No club linked to this account';
  END IF;

  SELECT id INTO v_season_id
  FROM public.competition_seasons
  WHERE is_current = true AND status = 'active'
  LIMIT 1;

  IF v_season_id IS NULL THEN
    RAISE EXCEPTION 'No active competition season';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.stadium_expansion_orders o
    WHERE o.club_short_name = v_club AND o.season_id_ordered = v_season_id
  ) THEN
    RAISE EXCEPTION 'Only one stadium expansion order per season';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.stadium_expansion_orders o
    WHERE o.club_short_name = v_club
      AND o.status IN ('pre_build', 'awaiting_goahead', 'building')
  ) THEN
    RAISE EXCEPTION 'An expansion is already in progress';
  END IF;

  SELECT * INTO v_quote
  FROM public.stadium_expansion_quotes q
  WHERE q.id = p_quote_id
    AND q.club_short_name = v_club
    AND q.consumed_at IS NULL;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Quote not found or already used';
  END IF;

  PERFORM public.stadium_expansion_sync_progress(v_club);

  SELECT coalesce(c."Capacity", 0)::int, coalesce(c.base_capacity, c."Capacity", 0)::int
  INTO v_current, v_base
  FROM public."Clubs" c
  WHERE c."ShortName" = v_club;

  v_max := public.stadium_max_capacity(v_base);

  IF v_quote.seats > public.stadium_expansion_headroom(v_club) THEN
    RAISE EXCEPTION 'Quote is no longer valid — capacity headroom changed';
  END IF;

  SELECT balance INTO v_balance
  FROM public."Club_Finances"
  WHERE club_name = v_club
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Club finances not found';
  END IF;

  IF v_balance < v_quote.total_cost THEN
    RAISE EXCEPTION 'Insufficient balance (need %, have %)',
      v_quote.total_cost, v_balance;
  END IF;

  v_ledger_id := public.post_club_ledger(
    v_club,
    'infra_expansion',
    -v_quote.total_cost,
    format('Stadium expansion — %s seats ordered', v_quote.seats),
    jsonb_build_object('quote_id', p_quote_id, 'seats', v_quote.seats),
    v_season_id,
    NULL,
    false,
    true
  );

  INSERT INTO public.stadium_expansion_orders (
    club_short_name,
    season_id_ordered,
    quote_id,
    seats_ordered,
    total_cost_paid,
    cost_per_seat,
    capacity_at_order,
    base_capacity_at_order,
    max_capacity_at_order,
    status,
    ledger_payment_id
  )
  VALUES (
    v_club,
    v_season_id,
    p_quote_id,
    v_quote.seats,
    v_quote.total_cost,
    v_quote.cost_per_seat,
    v_current,
    v_base,
    v_max,
    'pre_build',
    v_ledger_id
  )
  RETURNING id INTO v_order_id;

  UPDATE public.stadium_expansion_quotes
  SET consumed_at = now(), consumed_order_id = v_order_id
  WHERE id = p_quote_id;

  RETURN v_order_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.stadium_expansion_pre_build_cancel(p_order_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_row public.stadium_expansion_orders;
BEGIN
  v_club := public.my_club_shortname();

  SELECT * INTO v_row
  FROM public.stadium_expansion_orders o
  WHERE o.id = p_order_id AND o.club_short_name = v_club
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order not found';
  END IF;

  IF v_row.status NOT IN ('pre_build', 'awaiting_goahead') THEN
    RAISE EXCEPTION 'Cannot cancel at this stage';
  END IF;

  IF public.stadium_expansion_pre_build_day(v_row.ordered_at) >= 7 THEN
    RAISE EXCEPTION 'Use day-7 cancel (penalty applies) instead';
  END IF;

  PERFORM public.post_club_ledger(
    v_club,
    'infra_expansion_refund',
    v_row.total_cost_paid,
    format('Stadium expansion cancelled — full refund (%s seats)', v_row.seats_ordered),
    jsonb_build_object('order_id', p_order_id),
    v_row.season_id_ordered,
    NULL,
    false,
    true
  );

  UPDATE public.stadium_expansion_orders
  SET status = 'cancelled', cancelled_at = now()
  WHERE id = p_order_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.stadium_expansion_day7_decision(
  p_order_id bigint,
  p_continue boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_row public.stadium_expansion_orders;
  v_penalty numeric;
  v_refund numeric;
BEGIN
  v_club := public.my_club_shortname();

  PERFORM public.stadium_expansion_sync_progress(v_club);

  SELECT * INTO v_row
  FROM public.stadium_expansion_orders o
  WHERE o.id = p_order_id AND o.club_short_name = v_club
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order not found';
  END IF;

  IF v_row.status <> 'awaiting_goahead' THEN
    RAISE EXCEPTION 'Not awaiting day-7 decision (status %)', v_row.status;
  END IF;

  IF now() >= public.stadium_expansion_day7_deadline_uk(v_row.ordered_at) THEN
    RAISE EXCEPTION 'Day-7 decision window has closed';
  END IF;

  IF p_continue THEN
    UPDATE public.stadium_expansion_orders
    SET
      status = 'building',
      build_started_at = now(),
      goahead_decision = 'continue'
    WHERE id = p_order_id;
    RETURN;
  END IF;

  SELECT coalesce(stadium_expansion_cancel_penalty, 1000000)
  INTO v_penalty
  FROM public.global_settings
  WHERE id = 1;

  v_refund := greatest(v_row.total_cost_paid - v_penalty, 0);

  IF v_penalty > 0 THEN
    PERFORM public.post_club_ledger(
      v_club,
      'infra_expansion_penalty',
      -v_penalty,
      'Rapid Build Co cancellation fee',
      jsonb_build_object('order_id', p_order_id),
      v_row.season_id_ordered,
      NULL,
      false,
      true
    );
  END IF;

  IF v_refund > 0 THEN
    PERFORM public.post_club_ledger(
      v_club,
      'infra_expansion_refund',
      v_refund,
      format('Stadium expansion cancelled — partial refund (%s seats)', v_row.seats_ordered),
      jsonb_build_object('order_id', p_order_id, 'penalty', v_penalty),
      v_row.season_id_ordered,
      NULL,
      false,
      true
    );
  END IF;

  UPDATE public.stadium_expansion_orders
  SET
    status = 'cancelled',
    cancelled_at = now(),
    goahead_decision = 'cancel'
  WHERE id = p_order_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.stadium_expansion_cancel_build(p_order_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_club text;
  v_row public.stadium_expansion_orders;
BEGIN
  v_club := public.my_club_shortname();

  PERFORM public.stadium_expansion_sync_progress(v_club);

  SELECT * INTO v_row
  FROM public.stadium_expansion_orders o
  WHERE o.id = p_order_id AND o.club_short_name = v_club
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order not found';
  END IF;

  IF v_row.status <> 'building' THEN
    RAISE EXCEPTION 'Build is not active';
  END IF;

  IF v_row.seats_delivered > 0 OR v_row.build_weeks_applied > 0 THEN
    RAISE EXCEPTION 'Cannot cancel after the first build week has completed';
  END IF;

  PERFORM public.post_club_ledger(
    v_club,
    'infra_expansion_refund',
    v_row.total_cost_paid,
    format('Stadium build cancelled — full refund (%s seats)', v_row.seats_ordered),
    jsonb_build_object('order_id', p_order_id),
    v_row.season_id_ordered,
    NULL,
    false,
    true
  );

  UPDATE public.stadium_expansion_orders
  SET status = 'cancelled', cancelled_at = now()
  WHERE id = p_order_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Public status view (owner club)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.stadium_expansion_status_public
WITH (security_invoker = false)
AS
SELECT
  c."ShortName" AS club_short_name,
  coalesce(c.base_capacity, c."Capacity", 0)::int AS base_capacity,
  coalesce(c."Capacity", 0)::int AS current_capacity,
  public.stadium_max_capacity(coalesce(c.base_capacity, c."Capacity", 0)::int) AS max_capacity,
  public.stadium_expansion_headroom(c."ShortName") AS headroom,
  public.stadium_expansion_cost_per_seat(coalesce(c."Capacity", 0)::int) AS cost_per_seat,
  o.id AS active_order_id,
  o.seats_ordered,
  o.seats_delivered,
  o.total_cost_paid,
  o.status AS order_status,
  o.ordered_at,
  o.build_started_at,
  public.stadium_expansion_pre_build_day(o.ordered_at) AS pre_build_day,
  public.stadium_expansion_pre_build_message(
    least(public.stadium_expansion_pre_build_day(o.ordered_at), 6),
    o.seats_ordered
  ) AS pre_build_message,
  public.stadium_expansion_day7_deadline_uk(o.ordered_at) AS day7_deadline_uk,
  (o.status = 'awaiting_goahead' AND now() < public.stadium_expansion_day7_deadline_uk(o.ordered_at)) AS day7_decision_open,
  o.build_weeks_applied,
  CASE
    WHEN o.status = 'building' THEN round(100.0 * o.seats_delivered / nullif(o.seats_ordered, 0), 0)
    ELSE NULL
  END AS build_progress_pct
FROM public."Clubs" c
LEFT JOIN LATERAL (
  SELECT ord.*
  FROM public.stadium_expansion_orders ord
  WHERE ord.club_short_name = c."ShortName"
    AND ord.status IN ('pre_build', 'awaiting_goahead', 'building')
  ORDER BY ord.ordered_at DESC
  LIMIT 1
) o ON true
WHERE c."ShortName" = public.my_club_shortname();

CREATE OR REPLACE VIEW public.stadium_expansion_quotes_public
WITH (security_invoker = false)
AS
SELECT
  q.id,
  q.club_short_name,
  q.seats,
  q.capacity_at_quote,
  q.cost_per_seat,
  q.total_cost,
  q.created_at
FROM public.stadium_expansion_quotes q
WHERE q.club_short_name = public.my_club_shortname()
  AND q.consumed_at IS NULL
ORDER BY q.created_at DESC;

-- ---------------------------------------------------------------------------
-- Admin
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.admin_update_stadium_cost_settings(
  p_tier1 numeric,
  p_tier2 numeric,
  p_tier3 numeric,
  p_tier_mid integer DEFAULT NULL,
  p_tier_high integer DEFAULT NULL,
  p_cancel_penalty numeric DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NOT public.is_gpsl_admin() THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  IF p_tier1 IS NULL OR p_tier1 <= 0 OR p_tier2 IS NULL OR p_tier2 <= 0 OR p_tier3 IS NULL OR p_tier3 <= 0 THEN
    RAISE EXCEPTION 'Tier costs must be positive';
  END IF;

  UPDATE public.global_settings
  SET
    stadium_cost_tier1 = round(p_tier1, 2),
    stadium_cost_tier2 = round(p_tier2, 2),
    stadium_cost_tier3 = round(p_tier3, 2),
    stadium_capacity_tier_mid = coalesce(p_tier_mid, stadium_capacity_tier_mid),
    stadium_capacity_tier_high = coalesce(p_tier_high, stadium_capacity_tier_high),
    stadium_expansion_cancel_penalty = coalesce(round(p_cancel_penalty, 2), stadium_expansion_cancel_penalty),
    updated_at = now()
  WHERE id = 1;
END;
$function$;

-- RLS
ALTER TABLE public.stadium_expansion_quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stadium_expansion_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS stadium_expansion_quotes_select ON public.stadium_expansion_quotes;
CREATE POLICY stadium_expansion_quotes_select ON public.stadium_expansion_quotes
  FOR SELECT TO authenticated
  USING (club_short_name = public.my_club_shortname());

DROP POLICY IF EXISTS stadium_expansion_orders_select ON public.stadium_expansion_orders;
CREATE POLICY stadium_expansion_orders_select ON public.stadium_expansion_orders
  FOR SELECT TO authenticated
  USING (club_short_name = public.my_club_shortname());

GRANT SELECT ON public.stadium_expansion_status_public TO authenticated;
GRANT SELECT ON public.stadium_expansion_quotes_public TO authenticated;
GRANT SELECT ON public.stadium_expansion_quotes TO authenticated;
GRANT SELECT ON public.stadium_expansion_orders TO authenticated;

GRANT EXECUTE ON FUNCTION public.stadium_expansion_create_quote(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.stadium_expansion_place_order(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.stadium_expansion_pre_build_cancel(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.stadium_expansion_day7_decision(bigint, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.stadium_expansion_cancel_build(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.stadium_expansion_sync_progress(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.stadium_max_capacity(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_stadium_cost_settings(numeric, numeric, numeric, integer, integer, numeric) TO authenticated;

NOTIFY pgrst, 'reload schema';
