-- =============================================================================
-- Transfer inbox notifications — buyer & seller notified on completed deals
-- Run once after competition_phase3_matchday.sql (competition_inbox table).
-- =============================================================================

-- Stable id on Transfer_History (needed for inbox links / dedupe)
DO $id$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'Transfer_History'
      AND column_name = 'id'
  ) THEN
    ALTER TABLE public."Transfer_History"
      ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END;
$id$;

ALTER TABLE public.competition_inbox
  ADD COLUMN IF NOT EXISTS transfer_history_id bigint,
  ADD COLUMN IF NOT EXISTS transfer_listing_id bigint;

ALTER TABLE public.competition_inbox
  DROP CONSTRAINT IF EXISTS competition_inbox_message_type_check;

ALTER TABLE public.competition_inbox
  ADD CONSTRAINT competition_inbox_message_type_check
  CHECK (
    message_type IN (
      'result_to_confirm',
      'result_rejected',
      'result_confirmed',
      'transfer_signed',
      'transfer_sold'
    )
  );

CREATE INDEX IF NOT EXISTS competition_inbox_transfer_history_idx
  ON public.competition_inbox (transfer_history_id)
  WHERE transfer_history_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.transfer_club_display_name(p_short text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE
    WHEN p_short IS NULL OR btrim(p_short) = '' THEN NULL
    WHEN p_short = 'FOREIGN' THEN 'Foreign club'
    ELSE coalesce(
      (SELECT c."Club" FROM public."Clubs" c WHERE c."ShortName" = p_short LIMIT 1),
      p_short
    )
  END;
$$;

CREATE OR REPLACE FUNCTION public.transfer_format_money(p_amount numeric)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT '₿ ' || to_char(coalesce(p_amount, 0), 'FM999,999,999,999,990');
$$;

CREATE OR REPLACE FUNCTION public.transfer_classify_method(
  p_seller_club text,
  p_buyer_club text,
  p_listing_id bigint,
  p_sale_note text,
  p_foreign_buyer_name text,
  p_method_override text DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_listing_type text;
  v_note text := coalesce(btrim(p_sale_note), '');
  v_buyer text := btrim(coalesce(p_buyer_club, ''));
  v_seller text := btrim(coalesce(p_seller_club, ''));
BEGIN
  IF p_method_override IS NOT NULL AND btrim(p_method_override) <> '' THEN
    RETURN btrim(p_method_override);
  END IF;

  IF p_listing_id IS NOT NULL THEN
    SELECT l.listing_type INTO v_listing_type
    FROM public."Player_Transfer_Listings" l
    WHERE l.id = p_listing_id;
  END IF;

  IF v_listing_type = 'draft' THEN
    RETURN 'Draft auction';
  END IF;

  IF v_note = 'squad_overflow' THEN
    IF v_buyer = 'FOREIGN' AND coalesce(btrim(p_foreign_buyer_name), '') <> '' THEN
      RETURN 'Foreign sale (squad over 28)';
    END IF;
    RETURN 'Squad release (market value, over 28)';
  END IF;

  IF v_buyer = 'FOREIGN' THEN
    IF coalesce(btrim(p_foreign_buyer_name), '') <> '' THEN
      RETURN 'Foreign sale — ' || btrim(p_foreign_buyer_name);
    END IF;
    RETURN 'Foreign sale';
  END IF;

  IF v_listing_type = 'direct' THEN
    RETURN 'Direct offer (transfer market)';
  END IF;

  IF v_seller <> '' AND v_buyer <> '' THEN
    RETURN 'Transfer list (auction)';
  END IF;

  IF v_seller = '' AND v_buyer <> '' THEN
    RETURN 'Draft auction signing';
  END IF;

  RETURN 'Player transfer';
END;
$function$;

CREATE OR REPLACE FUNCTION public.transfer_inbox_send_one(
  p_recipient_club text,
  p_message_type text,
  p_title text,
  p_body text,
  p_transfer_history_id bigint DEFAULT NULL,
  p_listing_id bigint DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_id bigint;
  v_recipient text := btrim(p_recipient_club);
BEGIN
  IF v_recipient IS NULL OR v_recipient = '' OR v_recipient = 'FOREIGN' THEN
    RETURN NULL;
  END IF;

  IF p_transfer_history_id IS NOT NULL AND EXISTS (
    SELECT 1
    FROM public.competition_inbox i
    WHERE i.transfer_history_id = p_transfer_history_id
      AND i.recipient_club_short_name = v_recipient
      AND i.message_type = p_message_type
  ) THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.competition_inbox (
    recipient_club_short_name,
    message_type,
    fixture_id,
    submission_id,
    transfer_history_id,
    transfer_listing_id,
    title,
    body
  )
  VALUES (
    v_recipient,
    p_message_type,
    NULL,
    NULL,
    p_transfer_history_id,
    p_listing_id,
    p_title,
    p_body
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.transfer_inbox_notify_deal(
  p_player_id text,
  p_player_name text,
  p_seller_club text,
  p_buyer_club text,
  p_fee numeric,
  p_agent_fee numeric DEFAULT 0,
  p_listing_id bigint DEFAULT NULL,
  p_transfer_history_id bigint DEFAULT NULL,
  p_sale_note text DEFAULT NULL,
  p_foreign_buyer_name text DEFAULT NULL,
  p_method_override text DEFAULT NULL,
  p_extra_detail text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_player text := coalesce(nullif(btrim(p_player_name), ''), 'Player ' || btrim(p_player_id));
  v_seller text := btrim(coalesce(p_seller_club, ''));
  v_buyer text := btrim(coalesce(p_buyer_club, ''));
  v_method text;
  v_fee_line text;
  v_agent_line text;
  v_listing_line text;
  v_buyer_label text;
  v_seller_label text;
  v_body_buy text;
  v_body_sell text;
  v_extra text := nullif(btrim(p_extra_detail), '');
BEGIN
  v_method := public.transfer_classify_method(
    v_seller,
    v_buyer,
    p_listing_id,
    p_sale_note,
    p_foreign_buyer_name,
    p_method_override
  );

  v_fee_line := 'Fee paid: ' || public.transfer_format_money(coalesce(p_fee, 0));
  v_agent_line := CASE
    WHEN coalesce(p_agent_fee, 0) > 0 THEN
      E'Agent fee: ' || public.transfer_format_money(p_agent_fee)
    ELSE NULL
  END;
  v_listing_line := CASE
    WHEN p_listing_id IS NOT NULL THEN 'Listing #' || p_listing_id::text
    ELSE NULL
  END;

  v_buyer_label := CASE
    WHEN v_buyer = 'FOREIGN' THEN coalesce(nullif(btrim(p_foreign_buyer_name), ''), 'Foreign club')
    ELSE public.transfer_club_display_name(v_buyer)
  END;

  v_seller_label := public.transfer_club_display_name(v_seller);

  IF v_buyer <> '' AND v_buyer <> 'FOREIGN' THEN
    v_body_buy := concat_ws(
      E'\n',
      'Player: ' || v_player,
      'Method: ' || v_method,
      CASE WHEN v_seller <> '' THEN 'Signed from: ' || v_seller_label ELSE 'Previous club: Free agent' END,
      'Your club: ' || public.transfer_club_display_name(v_buyer),
      v_fee_line,
      v_agent_line,
      v_listing_line,
      v_extra
    );

    PERFORM public.transfer_inbox_send_one(
      v_buyer,
      'transfer_signed',
      'Signed ' || v_player,
      v_body_buy,
      p_transfer_history_id,
      p_listing_id
    );
  END IF;

  IF v_seller <> '' THEN
    v_body_sell := concat_ws(
      E'\n',
      'Player: ' || v_player,
      'Method: ' || v_method,
      'Sold to: ' || coalesce(v_buyer_label, 'Free agent / released'),
      'Your club: ' || v_seller_label,
      CASE
        WHEN v_buyer = 'FOREIGN' OR coalesce(p_fee, 0) > 0 THEN
          'Sale proceeds: ' || public.transfer_format_money(coalesce(p_fee, 0))
        ELSE 'No transfer fee'
      END,
      v_listing_line,
      v_extra
    );

    PERFORM public.transfer_inbox_send_one(
      v_seller,
      'transfer_sold',
      'Sold ' || v_player,
      v_body_sell,
      p_transfer_history_id,
      p_listing_id
    );
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.transfer_inbox_notify_from_history(p_transfer_history_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_h public."Transfer_History"%rowtype;
  v_name text;
BEGIN
  SELECT * INTO v_h
  FROM public."Transfer_History" h
  WHERE h.id = p_transfer_history_id;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT p."Name" INTO v_name
  FROM public."Players" p
  WHERE p."Konami_ID"::text = v_h.player_id::text
  LIMIT 1;

  PERFORM public.transfer_inbox_notify_deal(
    v_h.player_id::text,
    v_name,
    v_h.seller_club_id,
    v_h.buyer_club_id,
    v_h.fee,
    coalesce(v_h.agent_fee, 0),
    v_h.listing_id,
    v_h.id,
    v_h.transfer_sale_note,
    v_h.foreign_buyer_name,
    NULL,
    NULL
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.trg_transfer_history_inbox_notify()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF NEW.id IS NOT NULL THEN
    PERFORM public.transfer_inbox_notify_from_history(NEW.id);
  ELSE
    PERFORM public.transfer_inbox_notify_deal(
      NEW.player_id::text,
      (SELECT p."Name" FROM public."Players" p WHERE p."Konami_ID"::text = NEW.player_id::text LIMIT 1),
      NEW.seller_club_id,
      NEW.buyer_club_id,
      NEW.fee,
      coalesce(NEW.agent_fee, 0),
      NEW.listing_id,
      NULL,
      NEW.transfer_sale_note,
      NEW.foreign_buyer_name,
      NULL,
      NULL
    );
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS transfer_history_inbox_notify ON public."Transfer_History";

CREATE TRIGGER transfer_history_inbox_notify
  AFTER INSERT ON public."Transfer_History"
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_transfer_history_inbox_notify();

-- Special auction player prize (no Transfer_History row)
CREATE OR REPLACE FUNCTION public.special_auction_award_prize(
  p_auction public.special_auctions,
  p_winner_club text,
  p_win_amount numeric
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_player public."Players"%rowtype;
  v_title text;
BEGIN
  IF p_winner_club IS NULL THEN
    RETURN;
  END IF;

  IF p_auction.prize_type = 'player' AND p_auction.prize_player_id IS NOT NULL THEN
    SELECT * INTO v_player
    FROM public."Players"
    WHERE "Konami_ID"::text = p_auction.prize_player_id
    FOR UPDATE;

    IF FOUND THEN
      PERFORM public.player_assign_to_club(
        p_auction.prize_player_id,
        p_winner_club
      );

      v_title := coalesce(nullif(btrim(p_auction.title), ''), 'Special auction');

      PERFORM public.transfer_inbox_notify_deal(
        p_auction.prize_player_id,
        v_player."Name",
        NULL,
        p_winner_club,
        coalesce(p_win_amount, 0),
        0,
        NULL,
        NULL,
        NULL,
        NULL,
        'Special auction',
        'Auction: ' || v_title || E'\nWinning bid: ' || public.transfer_format_money(coalesce(p_win_amount, 0))
      );
    END IF;
  ELSIF p_auction.prize_type = 'cash' AND coalesce(p_auction.prize_cash_amount, 0) > 0 THEN
    UPDATE public."Club_Finances"
    SET balance = balance + p_auction.prize_cash_amount
    WHERE club_name = p_winner_club;
  END IF;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.transfer_inbox_notify_from_history(bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';
