#!/usr/bin/env python3
"""Build gpsl_sport_template_packs.sql seed from FEEDBACK CSV."""
from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

ROOT = Path(r"d:\GPSL_Cursor")
CSV_PATH = ROOT / "gpsl_sport_templates_FEEDBACK.csv"
OUT_PATH = ROOT / "supabase" / "sql" / "patches" / "gpsl_sport_template_packs.sql"


def sql_escape(s: str) -> str:
    return (s or "").replace("'", "''")


def main() -> None:
    rows = list(csv.DictReader(CSV_PATH.open(encoding="utf-8")))
    packs: dict[tuple[str, str], dict[str, str]] = defaultdict(dict)
    priority: dict[tuple[str, str], int] = {}
    for r in rows:
        key = (r["scenario"], r["pack_id"])
        packs[key][r["field"]] = r["template"]
        priority[key] = 10 if (r.get("priority") or "").lower() == "high" else 5

    value_lines = []
    for (scenario, pack_id), fields in sorted(packs.items()):
        for need in ("headline", "subhead", "body"):
            if need not in fields:
                raise SystemExit(f"missing {need} for {scenario}/{pack_id}")
        value_lines.append(
            "  ("
            f"'{sql_escape(pack_id)}', "
            f"'{sql_escape(scenario)}', "
            f"E'{sql_escape(fields['headline'])}', "
            f"E'{sql_escape(fields['subhead'])}', "
            f"E'{sql_escape(fields['body'])}', "
            f"{priority[(scenario, pack_id)]}"
            ")"
        )

    values_sql = ",\n".join(value_lines)

    sql = f"""-- =============================================================================
-- GPSL Sport — paired story packs + cooldown picker
--
-- • Packs keep headline/subhead/body glued (never mix across packs)
-- • Same pack cannot appear twice in one edition (exclude list)
-- • Packs used in the last N published editions are deprioritised (cooldown)
-- • Seeded from gpsl_sport_templates_FEEDBACK.csv (human-voice variants)
--
-- Safe re-run.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.gpsl_sport_template_packs (
  pack_id text PRIMARY KEY,
  scenario text NOT NULL,
  headline text NOT NULL,
  subhead text NOT NULL DEFAULT '',
  body text NOT NULL,
  priority smallint NOT NULL DEFAULT 5,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS gpsl_sport_template_packs_scenario_idx
  ON public.gpsl_sport_template_packs (scenario)
  WHERE active;

CREATE TABLE IF NOT EXISTS public.gpsl_sport_template_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  edition_id bigint REFERENCES public.gpsl_sport_editions (id) ON DELETE CASCADE,
  season_id bigint,
  gpsl_month text,
  scenario text NOT NULL,
  pack_id text NOT NULL REFERENCES public.gpsl_sport_template_packs (pack_id),
  slot text NOT NULL DEFAULT 'lead',
  used_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS gpsl_sport_template_usage_recent_idx
  ON public.gpsl_sport_template_usage (scenario, used_at DESC);

COMMENT ON TABLE public.gpsl_sport_template_packs IS
  'Paired GPSL Sport copy packs (headline+subhead+body) for random selection.';
COMMENT ON TABLE public.gpsl_sport_template_usage IS
  'Tracks which packs appeared in which editions for cooldown / no-repeat.';

-- Refresh seed from FEEDBACK CSV (replace all seeded packs)
DELETE FROM public.gpsl_sport_template_usage
WHERE pack_id IN (SELECT pack_id FROM public.gpsl_sport_template_packs);

DELETE FROM public.gpsl_sport_template_packs;

INSERT INTO public.gpsl_sport_template_packs (
  pack_id, scenario, headline, subhead, body, priority
) VALUES
{values_sql};

CREATE OR REPLACE FUNCTION public.gpsl_sport_compose_story_from_packs(
  p_scenario text,
  p_seed text,
  p_vars jsonb,
  p_season_id bigint DEFAULT NULL,
  p_exclude_pack_ids text[] DEFAULT '{{}}',
  p_cooldown_editions int DEFAULT 3
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_candidates text[];
  v_cooled text[];
  v_pick text;
  v_row public.gpsl_sport_template_packs;
  v_cooldown int := greatest(coalesce(p_cooldown_editions, 3), 0);
  v_exclude text[] := coalesce(p_exclude_pack_ids, '{{}}');
BEGIN
  IF coalesce(nullif(btrim(p_scenario), ''), '') = '' THEN
    RETURN NULL;
  END IF;

  IF to_regclass('public.gpsl_sport_template_packs') IS NULL THEN
    RETURN NULL;
  END IF;

  -- Packs used in the last N published editions for this scenario
  IF v_cooldown > 0
     AND to_regclass('public.gpsl_sport_template_usage') IS NOT NULL
     AND to_regclass('public.gpsl_sport_editions') IS NOT NULL THEN
    SELECT coalesce(array_agg(DISTINCT u.pack_id), '{{}}')
    INTO v_cooled
    FROM public.gpsl_sport_template_usage u
    WHERE u.scenario = p_scenario
      AND u.edition_id IN (
        SELECT e.id
        FROM public.gpsl_sport_editions e
        ORDER BY e.published_at DESC NULLS LAST, e.id DESC
        LIMIT v_cooldown
      );
  ELSE
    v_cooled := '{{}}';
  END IF;

  SELECT coalesce(array_agg(p.pack_id ORDER BY p.priority DESC, p.pack_id), '{{}}')
  INTO v_candidates
  FROM public.gpsl_sport_template_packs p
  WHERE p.active
    AND p.scenario = p_scenario
    AND NOT (p.pack_id = ANY (v_exclude))
    AND NOT (p.pack_id = ANY (v_cooled));

  -- Soft fallback: ignore cooldown if it wiped the bank
  IF coalesce(array_length(v_candidates, 1), 0) = 0 THEN
    SELECT coalesce(array_agg(p.pack_id ORDER BY p.priority DESC, p.pack_id), '{{}}')
    INTO v_candidates
    FROM public.gpsl_sport_template_packs p
    WHERE p.active
      AND p.scenario = p_scenario
      AND NOT (p.pack_id = ANY (v_exclude));
  END IF;

  IF coalesce(array_length(v_candidates, 1), 0) = 0 THEN
    RETURN NULL;
  END IF;

  v_pick := v_candidates[
    1 + (abs(hashtext(coalesce(p_seed, p_scenario))) % array_length(v_candidates, 1))
  ];

  SELECT * INTO v_row
  FROM public.gpsl_sport_template_packs p
  WHERE p.pack_id = v_pick;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  RETURN jsonb_build_object(
    'pack_id', v_row.pack_id,
    'scenario', v_row.scenario,
    'headline', public.gpsl_sport_apply_template(v_row.headline, p_vars),
    'subhead', public.gpsl_sport_apply_template(v_row.subhead, p_vars),
    'body', public.gpsl_sport_apply_template(v_row.body, p_vars)
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.gpsl_sport_record_pack_usage(
  p_edition_id bigint,
  p_season_id bigint,
  p_gpsl_month text,
  p_scenario text,
  p_pack_id text,
  p_slot text DEFAULT 'lead'
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  IF p_edition_id IS NULL OR coalesce(nullif(btrim(p_pack_id), ''), '') IS NULL THEN
    RETURN;
  END IF;
  IF to_regclass('public.gpsl_sport_template_usage') IS NULL THEN
    RETURN;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.gpsl_sport_template_packs p WHERE p.pack_id = p_pack_id
  ) THEN
    RETURN;
  END IF;

  INSERT INTO public.gpsl_sport_template_usage (
    edition_id, season_id, gpsl_month, scenario, pack_id, slot
  ) VALUES (
    p_edition_id, p_season_id, lower(nullif(btrim(p_gpsl_month), '')),
    coalesce(nullif(btrim(p_scenario), ''), 'unknown'),
    p_pack_id,
    coalesce(nullif(btrim(p_slot), ''), 'lead')
  );
END;
$function$;

GRANT SELECT ON public.gpsl_sport_template_packs TO authenticated;
GRANT SELECT ON public.gpsl_sport_template_usage TO authenticated;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_compose_story_from_packs(text, text, jsonb, bigint, text[], int)
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.gpsl_sport_record_pack_usage(bigint, bigint, text, text, text, text)
  TO authenticated, service_role;
"""
    OUT_PATH.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUT_PATH} with {len(value_lines)} packs")


if __name__ == "__main__":
    main()
